import { formatDaily, type DailyEntry } from "./paper-daily-format";

const entries: DailyEntry[] = [
  {
    title: "DexTacWAM: A Visuo-Tactile World-Action Model for Dexterous Manipulation", arxivId: "2609.24976", url: "https://arxiv.org/abs/2609.24976",
    institutions: ["University of Illinois Urbana-Champaign", "University of California, Berkeley", "Northwestern University"], signal: "把未来指尖接触也作为世界模型预测目标，而不只在动作头拼接触觉。",
    tags: ["Visuo-Tactile WAM", "Dexterous", "Contact Prediction"], classification: { research: "WAM", training: "Post-training", modalities: ["Tactile"], platforms: ["机械臂", "灵巧手"] },
    motivation: "视觉未来不能充分表示遮挡下的接触、滑移和握持状态，直接触觉条件也未必学到接触演化。",
    methodSummary: "逐指触觉经过冻结视觉 VAE，再按手指身份、手姿和时间压缩为每手一个潜表示，与视频一起去噪；动作专家读取联合预测特征。",
    architecture: "2B 视频世界模型加 160M 动作专家；五指到单手的 5:1 压缩器，以及分别归一化视觉/触觉 K/V 的共享 cross-attention。",
    data: "约四小时、488 段双手触觉数据用于编码适配，其中 24 段留作评估；六项下游真机任务各约 100 条示范。",
    experiments: "每任务每方法 20 次。六任务平均完成分 70.6，RDP 为 38.0；四项二元任务合计 55/80 对 24/80。",
    novelty: "在保留触觉特征和动作专家的消融中，去掉触觉世界预测后，四任务平均分由 74.7 降至 26.6。",
    strengths: "包含触觉预测、压缩、归一化及未见物体配置测试，主要结果来自真实闭环操作。",
    limitations: "仅验证一种 Sharpa 手和传感配置；基线的触觉表示与动作参数化不完全一致，成功示范训练也缺少恢复覆盖。",
    transfer: "接触信息可进入世界状态与预测损失，而不仅作为动作策略的附加输入。",
    technique: ["单通道触觉先通过 1×1 GrayToRGB 投影，再复用冻结 LTX 视觉 VAE。每手五个指尖 latent 加身份嵌入，以手姿条件 query 做集合 self-attention，并用时间模块保留滑移和接触释放等变化。", "左右手 latent 沿视图维度接入视频 DiT，联合损失为 L_world = L_video + L_touch。动作分支在共享 cross-attention 之前分别对视觉和触觉 K/V 做 RMS 归一化，防止两种特征尺度差异破坏优化。", "训练依次适配触觉编码器、按任务微调世界模型、加入新的动作专家。动作目标包含相对末端运动、手部命令和十指各六维力相关目标；不存在另行执行的在线 RL 阶段。"],
    evaluation: ["六任务涵盖遮挡抓取、双手交接、擦拭、用夹子转移番茄、分碗和拧瓶盖。交接与擦拭使用分阶段加分，其他四项是二元成功，因此 70.6 是混合任务分，不是 70.6% 的整任务成功率。", "四项二元任务合计 55/80（68.8%），RDP 为 24/80（30.0%）。未见碗颜色为 13/20，未见堆叠高度为 12/20。", "去掉触觉世界预测后四任务均分 26.6 对完整 74.7；去掉分模态 K/V 归一化的版本未收敛。压缩保留 89.4% 的接触召回，训练/推理加速分别为 2.26×/1.29×，均相对未压缩配置。"],
    comparison: "π0.5、ViTacFormer、RDP、Genie Envisioner；直接触觉条件、压缩器及归一化消融。",
    implementation: ["世界/动作阶段有效 batch 64，AdamW 学习率分别 3e-4/5e-5，BF16；动作块 54、记忆帧 4、预测视频块 9。三阶段冻结模块和优化器参数在附录表 8 列出。"],
    figureFile: "2609.24976-fig1.png", figureAlt: "DexTacWAM 联合视觉触觉世界建模与动作生成", figureCaption: "Figure 1 · 指尖触觉与视觉一起进入世界—动作模型。来源：arXiv 原图。",
  },
  {
    title: "PAKT: Physically-Aligned Kinesthetic Teaching for Reinforcement Learning", arxivId: "2609.25630", url: "https://arxiv.org/abs/2609.25630",
    resources: [{"label":"项目页","url":"https://pakt-website.github.io/pakt-website"}],
    institutions: ["NVIDIA"], signal: "让人工牵引示教与策略执行遵守同一速度、加速度和 jerk 限制。",
    tags: ["Kinesthetic Teaching", "Real-world RL", "Control"], classification: { research: "其他", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    motivation: "人手能牵引出的轨迹未必能由机器人策略重放；底层控制差异也会影响 RL 的效率和接触稳定性。",
    methodSummary: "导纳控制把人的力转为运动目标，统一参考生成器限制运动学量，再由阻抗控制器执行；使用带示范与人工介入的离策略 RL。",
    architecture: "RLPD/SAC 像素策略接三阶参考滤波和笛卡尔阻抗栈；10 Hz 高层命令由 1 kHz 控制环跟踪。",
    data: "四项插装任务各方法 20 条初始示范与在线交互；RAM 插入重复五个训练 seed，其余任务各一次训练。",
    experiments: "各任务最终 100 次试验。PAKT 的插销、RAM、限位件、汇流排成功率为 100%、98%、99%、99%；相对 HIL-SERL 的成功动作周期缩短 23–48%。",
    novelty: "三路对照把控制栈和示教接口分开：更快周期主要来自控制栈，牵引示教进一步减少人工介入。",
    strengths: "复现参数详细，且用混合版本区分低层控制和人工接口的贡献。",
    limitations: "只有一名知情操作员，不能推断普遍易用性；任务从预抓取开始，周期统计只包含成功试验。",
    transfer: "比较真机学习算法时，应同时统一示教可执行性和底层控制，否则接口改进容易被误当成 RL 算法收益。",
    technique: ["人工模式通过导纳方程 M_a ẍ = f_ext − D_a ẋ − K_a x 将外力映射为参考运动，随后与策略模式共同经过三阶临界阻尼参考生成器。两种模式都限制速度、加速度和 jerk，减少示教与部署的动态不匹配。", "阻抗层含惯性相关补偿与期望速度/加速度；关节力矩估计只用于牵引控制，不作为策略额外观测。策略输入仍为两个腕部 RGB、笛卡尔位姿和速度，输出六维增量。", "基线使用 HIL-SERL 原控制与 SpaceMouse，混合版本使用新控制栈但保留 SpaceMouse，PAKT 再替换成牵引接口。三者保持示范预算、复位和学习程序一致。"],
    evaluation: ["PAKT 对四任务的成功率为 1.00/0.98/0.99/0.99，基线为 1.00/0.88/0.99/0.85；RAM 的数字为五 seed 均值，每次最终评测 100 次。", "相对基线，累计介入计数下降 62–86%；相对同控制栈的混合版下降 34–64%。该计数是训练步上介入率的离散累计，不是独立人工纠正事件个数。周期只统计成功试验，失败和超时不在均值内。", "跟踪相近的两个控制器中，PAKT 的硬接触峰值 22.5 N，简化版本 33.9 N。10 N 停止条件仅在 10 Hz 高层检查，不能把该阈值理解为全系统始终满足的力上限。"],
    comparison: "HIL-SERL、同控制栈+SpaceMouse，以及五种阻抗控制器。",
    implementation: ["冻结 ResNet-10，actor/critic 均为两层 256 维 MLP；batch 256，示范/在线各半，γ=0.97，学习率 3e-4。Franka 控制使用 Jetson Orin AGX，学习与分类器使用 RTX 4090。"],
    figureFile: "2609.25630-fig1.png", figureAlt: "PAKT 人工牵引、参考生成器与强化学习控制流程", figureCaption: "Figure 1 · 人工示教和策略执行共用物理约束与控制栈。来源：arXiv 原论文。",
  },
  {
    title: "InsertAnything: Generalizable Contact-Rich Precision Insertion from Simulation to Reality", arxivId: "2609.24511", url: "https://arxiv.org/abs/2609.24511",
    resources: [{"label":"项目页","url":"https://mzhsoul.github.io/InsertAnything/"}],
    institutions: ["Institute of Automation, Chinese Academy of Sciences", "University of Chinese Academy of Sciences", "PaXini AI"], signal: "仅用仿真训练，以三维指尖力反馈修正目标位姿误差，并迁移到未见插接件。",
    tags: ["Precision Insertion", "Force Feedback", "Sim2Real"], classification: { research: "其他", training: "RL", modalities: ["Force / Torque"], data: "合成 / 仿真数据", deployment: "Sim2Real", platforms: ["机械臂", "夹爪"] },
    motivation: "紧间隙插装对定位误差敏感，单纯朝名义孔位运动容易卡滞或产生过大接触力。",
    methodSummary: "PPO 从位姿和三维指尖力输出运动修正，用先对齐后推进的门控奖励训练，并通过力信号平滑、状态无关探索方差与随机化提升迁移稳定性。",
    architecture: "状态策略配合顺应跟踪控制器；紧凑力反馈不要求在策略内处理完整触觉图像或识别物体几何类别。",
    data: "标准孔形与间隙的随机化仿真，无真实示范和真机策略微调；泛化试验复用六边形插入训练得到的一个策略。",
    experiments: "四类紧间隙实物各 20 次，带力策略为 20/20、20/20、17/20、18/20；八类未见真实插接任务合计 152/160。",
    novelty: "在单一模拟孔形上学习的接触修正可迁移到连接器和齿轮；同策略屏蔽力信号的消融进一步分离其作用。",
    strengths: "同时测试间隙、几何和毫米级定位偏差，报告成功次数及峰值接触力。",
    limitations: "目标孔位需先给定或标定；抓取和转运由规划器处理，官方 20 项测试采用人工报告状态的协议，不是全流程无人化。",
    transfer: "精密装配可先训练通用接触纠偏，再与外部定位和抓取模块组合。",
    technique: ["奖励分别衡量平面位置、偏航角和插入深度，深度项只有在平面/方向对齐条件下才被强化，降低尚未对齐就向下硬压的诱因。动作还受到幅度与变化惩罚。", "力输入用 f̄_t = αf_t + (1 − α)f̄_(t−1) 平滑，策略使用可学习但与状态无关的高斯标准差，避免带噪接触观测同时引起均值和探索方差剧烈变化。随机化覆盖孔位偏差、力噪声、摩擦和控制刚度。"],
    evaluation: ["真实 Hexagon-IV 中加入 0–3 mm 孔位偏差，带力策略 38/45，位姿策略 31/45；平均峰值接触力为 2.65 N 对 3.08 N。最难 2–3 mm 组分别 11/15 与 7/15。", "八类未见任务用同一个 Hexagon-III 策略，各 20 次、合计 152/160。ManipulationNet 的 20/20 则是五种孔形各四种间隙，由五个按形状训练的策略完成，不能描述为一个策略完成全部官方项目。", "Square-IV 仿真消融中，两种稳定化都移除时最终窗口成功率 0.348；仅平滑 0.555，仅固定形式方差 0.777，两者结合 0.842。"],
    comparison: "无力 PPO、同策略力输入清零、奖励/平滑/探索方差消融及经典插入控制。",
    implementation: ["补充材料列出奖励阈值、随机化范围、力/动作滤波、阻抗和零空间控制；平面静态孔位噪声标准差 1 mm，动态力噪声 0.1 N。"],
    figureFile: "2609.24511-fig1.png", figureAlt: "InsertAnything 仿真力反馈学习与真机插接迁移", figureCaption: "Figure 1 · 从仿真力反馈策略到不同形状与间隙的真实插接。来源：arXiv 原图。",
  },
  {
    title: "Touch2Robot: Robot Touch in the Human Demonstration Loop", arxivId: "2609.24660", url: "https://arxiv.org/abs/2609.24660",
    resources: [{"label":"项目页","url":"https://Touch2Robot.github.io/"}],
    institutions: ["BIGAI", "ShanghaiTech University", "Shanghai Jiao Tong University", "Beihang University"], signal: "采人类示范时，实时显示目标机器人手将如何接触物体，让操作者当场调整。",
    tags: ["Human Demonstration", "Tactile Retargeting", "Data Quality"], classification: { research: "其他", training: "RL", modalities: ["Tactile"], data: "UMI / Ego / Human Video", deployment: "跨本体迁移", platforms: ["机械臂", "灵巧手"] },
    motivation: "人手能完成的接触未必适合机器人，录完再离线重定向可能保留大量不可执行示范。",
    methodSummary: "以物体运动和人手触觉训练物体专属 RL teacher，蒸馏成统一实时重定向器，再在 VR 中可视化目标机器人的接触，闭环指导采集。",
    architecture: "PointNet 几何特征加因果 Transformer，读取人手运动、触觉和物体历史，输出机器人关节目标及接触状态。",
    data: "四任务人类动作/触觉/物体轨迹，RL 教师轨迹用于蒸馏；真机使用 xArm6+带 TwinTac/FSR 的 LEAP Hand。",
    experiments: "四任务平均回放完成分从视觉反馈的 37.9 提至 72.1；训练下游 Diffusion Policy 后均分从 32.9 提至 62.0。",
    novelty: "接触反馈在采集时改变人的动作，而不仅在采集后变换已有轨迹。",
    strengths: "从接触重建质量、采集效率到下游策略分层验证，能够追踪数据接口的收益。",
    limitations: "依赖物体跟踪、几何与触觉设备；接触重建对真实传感的 F1 仅 44.2%，并非高精度力场复原。",
    transfer: "人类数据采集可以加入目标本体的可执行性反馈，提前纠正无法迁移的握持方式。",
    technique: ["Teacher 奖励同时跟踪物体运动、当前接触模式与接触变化，约束相对几何重定向的残差。统一 student 学关节目标 MSE 与接触 BCE，输入含 32 维 PointNet 几何及历史，避免逐条示范单独在线求解。", "VR 以 30 Hz 显示仿真重建的机器人手与接触区域，端到端约 122 ms；重定向网络本身约 1.12 ms，两者不可混为一谈。随后用 SAM/ProPainter 去除人手并渲染机器人手，构造下游策略观察。"],
    evaluation: ["Pick、Rotate、Wipe、Drawer 的真实回放完成分为 62.5、59.0、90.0、77.0，平均 72.1；视觉反馈均值 37.9。每条可成功回放示范的采集时间为 18.2 秒，对照 58.6 秒。", "下游 DP 四任务平均完成分 62.0，对视觉反馈数据的 32.9。重建接触相对真机的 F1 为 44.19%，接触发生时间误差 857.4 ms；去触觉奖励为 24.58% 与 1694.4 ms。", "统一重定向器相对专物体 teacher 有蒸馏损失：物体误差 18.05% 对 8.64%，接触 F1 65.46% 对 73.70%；去几何或接触辅助目标进一步下降。"],
    comparison: "离线重定向、仅视觉反馈、ConTrack/DexMachina、去触觉奖励及 student 模块消融。",
    implementation: ["Student 历史 16、4 层/8 头 Transformer、batch 128、AdamW 3e-4。DP 20 Hz、观测 5 帧、预测 24 步执行 16 步，训练 50k 更新。"],
    figureFile: "2609.24660-fig2.png", figureAlt: "Touch2Robot 触觉引导教师、蒸馏和闭环数据采集", figureCaption: "Figure 2 · 接触引导 RL、统一重定向器与实时采集反馈。来源：arXiv 原图。",
  },
  {
    title: "Rolling-WAM: World Action Models with Rolling Imagination", arxivId: "2609.30247", url: "https://arxiv.org/abs/2609.30247",
    resources: [{"label":"项目页","url":"https://rolling-wam.github.io/"}],
    institutions: ["University of Southern California", "Brown University", "Fudan University", "Toyota Research Institute"], signal: "把未来视频和动作的去噪分摊到连续重规划周期，保留一个不断修正的未来窗口。",
    tags: ["Rolling Diffusion", "World Action Model", "Low Latency"], classification: { research: "WAM", training: "BC", deployment: "真机部署优化", platforms: ["Humanoid", "灵巧手"] },
    motivation: "每次重新生成完整未来会拉长重规划等待，影响接触与连续动作。",
    methodSummary: "维护噪声水平交错的滑动视频—动作窗口，先完成即将执行的动作块，远期块在后续观测到来时继续细化。",
    architecture: "Wan2.2 视频专家与约 1B 动作专家联合 flow matching；按块设置噪声时间并限制跨块动作注意力。",
    data: "LIBERO、RoboTwin 示范；G1 三任务每项 50 条、10 Hz 数据，一套策略联合训练，无额外机器人预训练。",
    experiments: "G1 三任务每项 20 次，平均成功 85.0%，Joint-WAM 78.3%，Fast-WAM 75.0%；A100 稳态重规划 215 ms 对 978/548 ms。",
    novelty: "不是单纯减少全部去噪步数，而是让保留的未来块跨周期累积计算，结合新观察持续更新。",
    strengths: "同时报告延迟、仿真大基准和真机成功；明确区分初始化与稳态开销。",
    limitations: "4.5× 加速不包含首轮初始化，且预测窗口与基线不同；实时扰动下长期保留预测的边界仍有限。",
    transfer: "连续控制可复用未执行的未来计算，而不是每次从白噪声重新规划整个动作时域。",
    technique: ["窗口包含 W 个动作/视频块，越远的块噪声越高。每周期把第一个块完全去噪并执行，剩余块向前移动，新块从高斯噪声加入；新的图像条件修正后续预测。", "默认 N=10、W=5、每块 16 动作，因此稳态每周期仅运行 N/W=2 次去噪，却维持 80 动作的预测窗口。训练混合初始化模式和滚动模式，概率分别 0.2/0.8；视频与动作损失权重均为 1。"],
    evaluation: ["G1 的放玩偶、叠盘、倒珠各 20 次，Rolling-WAM 为 85%、100%、70%；Joint-WAM 为 70%、100%、65%。同一个策略使用共 150 条示范。", "A100、384×320 输入、每次执行 16 动作的稳态计时包含编码与去噪，但不含初始化：Rolling 215 ms，Joint 978 ms，Fast 548 ms。Rolling 预测 80 步而两基线预测 16 步。", "LIBERO 平均 98.1%，低于 Joint-WAM 的 98.5%；RoboTwin 全 50 任务 clean/random 为 93.54%/92.98%。六任务调度消融中，部分随机调度的任务成功可略高，标准滚动主要兼顾两基准和效率。"],
    comparison: "Joint-WAM、Fast-WAM、π0.5、GR00T N1.7；窗口、噪声调度和跨块注意力消融。",
    implementation: ["动作专家 30 层、hidden 1024；冻结 VAE/文本编码器，AdamW 1e-4、weight decay 1e-2、BF16。G1 训练 7500 步、有效 batch 192，动作包含 64 维 SONIC latent 和双手命令。"],
    figureFile: "2609.30247-fig2.png", figureAlt: "Rolling-WAM 跨周期的视频动作滑窗去噪", figureCaption: "Rolling-WAM 原论文方法图：近端先执行，远端保留并继续去噪。来源：arXiv 原图。",
  },
  {
    title: "DeltaWAM: Delta World Action Models for Bimanual Manipulation", arxivId: "2609.28811", url: "https://arxiv.org/abs/2609.28811",
    resources: [{"label":"项目页","url":"https://aigeeksgroup.github.io/DeltaWAM"},{"label":"GitHub","url":"https://github.com/AIGeeksGroup/DeltaWAM"}],
    institutions: ["Peking University", "AI Robotics"], signal: "用稠密参考帧与稀疏变化分开表示世界，并增量缓存已发生的变化。",
    tags: ["Visual Delta", "Streaming Memory", "WAM"], classification: { research: "WAM", training: "BC", deployment: "真机部署优化", platforms: ["机械臂", "夹爪"] },
    motivation: "未来视频里大量内容不变，重复预测与编码完整帧浪费计算并引入外观干扰。",
    methodSummary: "联合预测 visual delta 和动作，参考帧提供语义上下文；Streaming Delta Memory 保存已观察变化的 K/V，并周期性刷新参考。",
    architecture: "Anchor、Delta、Action 三路；比较视觉共享、完全分离和动作共享三种配置，后者带流私有残差专家。",
    data: "RoboTwin 前十任务各 550 示范，分为两个五任务训练组；真机 WAM 先用 RoboCOIN 的 325.7 小时 RealMan 数据预训练，再对三任务各 100 条示范微调。",
    experiments: "真机三任务各 20 次，完整成功 25/60（41.67%），π0.5 为 23/60、Fast-WAM 为 21/60；单步推理从 121.02 降至 76.76 ms。",
    novelty: "同一种 delta 既监督未来变化，也编码过去变化以更新缓存，减少重型视频专家反复处理完整图像。",
    strengths: "披露 delta 编码本身的 FLOPs，成功率、阶段进度与缓存效率分别报告。",
    limitations: "真机成功差距仅数次试验，且预训练来源不同；仿真只测十任务，不是完整 RoboTwin 基准。",
    transfer: "视频控制系统可把静态参考与动态更新拆开，但需把增量编码和缓存刷新的成本一起核算。",
    technique: ["冻结 delta encoder 从相邻观察提取变化 token；未来 delta 和动作分别加噪，以 L = λΔLΔ + λaLa 联合训练。参考路单向提供条件，避免未来监督泄漏进历史输入。", "SDM 用零噪声的已发生 delta 追加各层 K/V，历史缓存保持不动；每四次重规划周期摊销一次参考刷新。异步更新可在前一个动作块执行完之前开始，代价是有界的视觉陈旧。"],
    evaluation: ["十任务汇总 clean/random 为 85.4%/83.9%，Fast-WAM 为 81.3%/75.8%；两组五任务由不同模型训练，不能称为单模型十任务结果。", "真机总完整成功为 25/60，阶段进度为 72.14%，Fast-WAM 为 69.29%；π0.5 在桌面整理单任务上更好。", "单步配置的延迟降低 36.57%、FLOPs 降低 31.55%，但在初始五任务 clean 的单步成功为 71.6%，Fast-WAM 为 72.8%。去 SDM 的多步配置 clean 86.4%，加 SDM 为 82.8%，random 则由 82.6% 升至 86.6%。"],
    comparison: "同 LoRA 配置 Fast-WAM、π0.5、三种共享架构、delta encoder 与 SDM 消融。",
    implementation: ["Wan2.2-TI2V-5B 初始化，LoRA rank 64/alpha 128；15000 步、global batch 64、AdamW 1e-4。真机额外预训练 50000 步；仿真每任务每设置 100 次，同环境 seed。"],
    figureFile: "2609.28811-fig2.png", figureAlt: "DeltaWAM 稠密参考、稀疏变化与动作的三流结构", figureCaption: "Figure 2 · Anchor、Delta、Action 的共享方式与信息流。来源：arXiv 原图。",
  },
  {
    title: "PolyUMI: Accessible Visual-Tactile-Audio Data Collection for Object Inference and Manipulation", arxivId: "2609.29760", url: "https://arxiv.org/abs/2609.29760",
    resources: [{"label":"项目页","url":"https://polyumi-vista.github.io"}],
    institutions: ["Northwestern University", "TU Darmstadt / PEARL Lab", "Hessian.AI", "Robotics Institute Germany"], signal: "让同一个传感指同时采集视觉、光学触觉和接触音频，并从手持采集端移到机器人端。",
    tags: ["UMI", "Tactile", "Contact Audio"], classification: { research: "其他", training: "BC", modalities: ["Tactile", "Audio"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"] },
    motivation: "视觉难以观测滑移和遮挡内的接触；采集与部署传感几何不同又会造成额外域差。",
    methodSummary: "无线手持 PolyUMI 采同步多模态示范，VisTA 对各传感器的局部 token 做时空融合，再通过 flow-matching 动作头预测相对运动。",
    architecture: "视觉/触觉 CNN、接触音频 log-Mel CNN、状态 MLP，接八层融合 Transformer 和十八层动作 DiT。",
    data: "形状识别 2700 触觉图；盒内物体三类各 30 段；滑移控制 80 条示范，另有擦板和拧灯泡真机任务。",
    experiments: "滑移任务完整多模态为 8/10，纯视觉 2/10；形状分类 92.3%。灯泡任务各法均至少 80%，纯视觉 DP 最好，额外模态并非总有收益。",
    novelty: "硬件保留采集/部署接触几何，策略保留局部跨模态 token，而不是只拼接每个传感器的池化向量。",
    strengths: "包含模态消融与信息价值较低的反例，硬件设计和同步协议较具体。",
    limitations: "闭环滑移只有十次试验；多模态传感需要同步及夹爪改装，不能把局部任务收益概括为全面提升。",
    transfer: "新传感模态应先验证能否提供视觉看不到的信息，再考虑融合网络复杂度。",
    technique: ["原生触觉 20 fps、腕部视频 60 fps、接触音频 16 kHz，按最迟到达的观测对齐到 10 Hz。音频转为 128 mel bins、25 ms 窗/10 ms hop，保留约 0.5 秒。", "VisTA 使用两帧图像历史和 294 个融合 token，hidden 624、八头 self-attention；动作 DiT 预测 16 步、每步 10 维的相对位姿/夹爪命令。实时执行只取前三步，并补偿传感到控制的总延迟。"],
    evaluation: ["滑移控制要求螺丝刀转到目标角度且不掉落。V+T+A 为 8/10，T+A 为 7/10，V+T 和 V+A 均为 3/10，纯视觉为 2/10。", "触觉形状识别按场景划分训练/测试，1986/714 张而非随机混帧，准确率 92.3%。盒内物体分类加入音频约 80%，无音频约 42–44%。", "擦板中 VisTA 更稳定地保持接触并沿线擦除；灯泡任务主要失败在阶段转换，所有方法至少 80% 且纯视觉 DP 最好。两者说明接触反馈的作用依赖任务。"],
    comparison: "纯视觉 DP、MulSA、Sparsh-X、PolyTouch 与 V/T/A 组合消融。",
    implementation: ["同一实验中数据、训练预算和预测时域一致，训练 120 epoch；FR3 以 1 kHz 阻抗控制跟踪，改装 Franka Hand 支持 200 Hz 位置控制。单个多模态指物料约 235.96 美元。"],
    figureFile: "2609.29760-fig3.png", figureAlt: "PolyUMI VisTA 视觉触觉音频 token 融合架构", figureCaption: "Figure 3 · 传感器特定编码、联合注意力与动作 flow matching。来源：arXiv 原图。",
  },
  {
    title: "Learning from Mixed-Quality Deployment Experience for Robot Manipulation", arxivId: "2609.29000", url: "https://arxiv.org/abs/2609.29000",
    institutions: ["Nanyang Technological University", "Changan Automobile", "Guangzhou Cloudbutterfly Technology"], signal: "让失败和部分成功的自主 rollout 也参与后训练，但用预测式 critic 区分动作质量。",
    tags: ["PACL", "Offline RL", "Deployment Data"], classification: { research: "其他", training: "RL", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    motivation: "直接模仿所有部署数据会复制错误，稀疏奖励下的离线 critic 又可能缺少足够监督。",
    methodSummary: "PACL 用动作块 TD 学习加未来 latent 预测训练 critic，把动作划成高/低/中性质量条件，训练条件扩散 actor，并在执行时重排候选。",
    architecture: "共享视觉状态编码、双 Q/V 头和未来变化预测器，接带质量条件的 diffusion U-Net。",
    data: "仿真四任务各 200 人类示范加 500 自主 rollout；Franka 三任务各 50 示范加 50 rollout，无额外人工纠正。",
    experiments: "真机各 25 次，PickCup/StackCup/MoveSpoon 为 25/25、25/25、21/25，初始 DP 为 21/25、18/25、16/25；仿真各 250 次。",
    novelty: "未来状态差分给稀疏价值学习提供辅助监督，质量条件使失败轨迹不再与成功示范等价处理。",
    strengths: "同一 DP 起点比较多种后训练方法，包含数据组成、critic 结构和候选数消融。",
    limitations: "推理需 100 步 DDIM 与 12 个候选，速度代价不小；任务范围和真机试验数量有限。",
    transfer: "复用部署数据时，可以分离“从所有经验学价值”和“按质量条件学动作”两种监督。",
    technique: ["Critic 目标为 Y = R_chunk + (1 − done)γᴷV(s′)，并预测执行部分动作块后的 latent 变化；总损失包含 Q、expectile V 和 dynamics 项，避免仅靠稀疏终点标签塑造表示。", "根据 Q 值分位数将部署动作赋为高、低或空质量条件，所有数据共同训练 actor；推理生成多个动作块，再用 critic 选择。人类示范和自主失败仍分开记录，方法不需要为失败轨迹伪造成功标签。"],
    evaluation: ["真机三任务共 75 次，PACL 为 71/75，初始 DP 为 55/75；RISE 为 25/25、24/25、20/25，与 PACL 的差别只有两次完成，不能夸大成稳定大幅领先。", "仿真 Can/Transport/Square/ToolHang 为 98.4%、96.0%、93.2%、82.8%。Transport 的候选数消融中，普通 chunk critic 在 N=4/16 为 85.2%/63.6%，预测式 PACL 为 89.2%/80.4%，更多候选并不单调更好。", "固定 50 epoch 的数据消融中，Square 的仅成功数据版本为 77.6%，完整 700 轨迹版本为 93.2%；数据量与组成共同变化，不能单独归因为失败样本本身。"],
    comparison: "SUB、自模仿、SSDF、DQL、IDQL、RISE，以及一步/动作块、预测辅助和数据组成消融。",
    implementation: ["H_obs=2、H_action=8、γ=0.99、expectile 0.9、动态损失权重 0.5；后训练 50 epoch，图像主干 1e-5、条件和 U-Net 1e-4。DDIM 100 步，N=12。"],
    figureFile: "2609.29000-fig1.png", figureAlt: "PACL 预测式动作块价值学习和质量条件策略", figureCaption: "PACL 原论文方法图：混合质量经验连接 critic 与条件动作学习。来源：arXiv 原图。",
  },
  {
    title: "Behavior-Aligned Action Tokenization for Robot Policy Learning", arxivId: "2609.27513", url: "https://arxiv.org/abs/2609.27513",
    institutions: ["Southern University of Science and Technology", "Dexmal", "National University of Singapore", "Zhejiang University"], signal: "按运动形态对齐动作 token，而不是只优化动作的逐点重建误差。",
    tags: ["BAAT", "Action Tokenization", "Soft-DTW"], classification: { research: "表征学习", training: "BC", platforms: ["机械臂", "灵巧手", "夹爪"] },
    motivation: "不同速度和阶段的相似动作可能被编码为不同 token，妨碍跨任务共享局部运动。",
    methodSummary: "Soft-DTW 在批内选择相似动作块，对量化坐标做对齐；带执行历史的 diffusion decoder 重建动作，冻结 tokenizer 后训练自回归策略。",
    architecture: "动作编码器、FSQ 量化、历史条件扩散解码器与因子化自回归 token 预测器。",
    data: "LIBERO 四套共 40 任务，另选 RoboCasa 四任务和 RoboTwin 四任务；真实双臂刷牙用具整理与 56-DoF 物体分拣。",
    experiments: "真机各 20 次，BAAT 为 14/20 和 9/20，OAT 为 13/20 和 4/20；分拣与 DP 同为 9/20。三个仿真基准均值 45.2%，OAT 38.0%。",
    novelty: "tokenizer 同时优化行为对应和重建；适量对齐可提高闭环策略表现，即使离线重放精度下降。",
    strengths: "把重建、重放、闭环成功分别测量，避免把低 MSE 直接当成好控制表示。",
    limitations: "真实两任务样本较少；强对齐会抹掉关键动作细节，LIBERO 单套训练和联合训练结论不同。",
    transfer: "设计动作 tokenizer 时，除了重建保真度，还可检查跨任务共享与实际闭环可学性。",
    technique: ["动作先转为归一化运动增量，用允许时间伸缩的 Soft-DTW 挑选相似块；它提供弱行为对应，并不等价于任务语义相同。量化后的表示被拉近，同时由历史条件解码器保留执行细节。", "联合目标为 L_tokenizer = L_reconstruction + 0.1L_alignment。之后冻结 tokenizer 和 decoder，把示范离线编码成类别标签，训练自回归策略；部署根据已执行动作历史重建连续控制。"],
    evaluation: ["LIBERO-All 中无对齐的策略成功为 70.2%，权重 0.1 时为 79.0%，但重放成功从 80.5% 降至 71.5%；权重 0.3 后策略跌至 57.9%，0.5 时崩溃。", "将 Soft-DTW 换成逐点 L2 配对，策略为 73.0%，低于 79.0%。Transformer decoder 重建更准，却只有 69.4% 闭环成功，diffusion 为 79.0%。", "真实整理为 14/20，对 OAT 13/20、DP 11/20；高维分拣为 9/20，与 DP 相同。带历史的解码把离线跨块跳变 p95 从 6.359 降至 3.203，单位为原始关节目标，并非毫米。"],
    comparison: "FAST、OAT、坐标分桶、DP；对齐权重、配对距离、decoder 和执行历史消融。",
    implementation: ["16 latent slots、hidden 512、每 slot 四个 FSQ 因子，levels=(8,5,5,5)；预测 20 步执行 16 步。仿真三 seed，每任务每 seed 50 次最终 checkpoint 评测。"],
    figureFile: "2609.27513-fig1.png", figureAlt: "BAAT 行为对应、量化动作和策略训练流程", figureCaption: "Figure 1 · Soft-DTW 行为配对监督动作量化，再训练自回归控制。来源：arXiv 原图。",
  },
];

export const paperDaily20260925 = formatDaily(entries, "2026-09-25");
