import type { Paper } from "./site-data";

type Entry = Omit<Paper, "rank" | "figures" | "optimization" | "experimentDetails" | "reproducibilityDetails" | "deepDive"> & {
  figureFile: string;
  figureAlt: string;
  figureCaption: string;
  technique: string[];
  evaluation: string[];
  comparison: string;
  reproducibilityStatus: "资源较完整" | "部分可复现" | "信息不足";
  implementation: string[];
  missing: string[];
};

const makePaper = (entry: Entry, index: number): Paper => ({
  ...entry,
  rank: index + 1,
  optimization: entry.technique.join("；"),
  experimentDetails: [{ title: "原文实验与消融", setup: entry.experiments, comparisons: entry.comparison, results: entry.evaluation }],
  reproducibilityDetails: {
    status: entry.reproducibilityStatus,
    verifiedResources: entry.resources?.map((resource) => `${resource.label}: ${resource.url}`) ?? ["arXiv 论文正文"],
    implementation: entry.implementation,
    missing: entry.missing,
  },
  deepDive: {
    lead: entry.methodSummary ?? entry.signal,
    sections: [{ title: "方法与模型改进", paragraphs: entry.technique }],
    experimentReading: entry.evaluation,
    reflections: [entry.transfer],
  },
  figures: [{ src: `/report-assets/2026-09-11/${entry.figureFile}`, alt: entry.figureAlt, caption: entry.figureCaption }],
});

const entries: Entry[] = [
  {
    title: "ICI-VLA: In-Context Imitation with Spatiotemporally Aligned Demonstrations for Vision-Language-Action Models",
    arxivId: "2609.07581", url: "https://arxiv.org/abs/2609.07581",
    institutions: ["Wuhan University", "Institute of Technological Sciences, Wuhan University"],
    signal: "把检索到的长轨迹切成与当前子阶段对齐的微演示，并在上下文中隐藏目标动作，使冻结 VLA 能直接模仿。",
    tags: ["In-Context Imitation", "Retrieval", "VLA"],
    classification: { research: "VLA", training: "Test-time Adaptation", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "整段示范包含大量与当前决策无关的动作，直接拼接既浪费上下文，也容易把未来动作泄漏给模型。",
    methodSummary: "ICI-VLA 先用语义过滤和动态时间规整找到相似阶段，再将对齐片段编码为紧凑微演示；训练时用目标动作掩码迫使模型依赖演示与观测推断动作。",
    architecture: "Qwen3-VL-4B 负责文本化动作预测，Qwen3-VL-Embedding-2B 检索演示；检索器、时序对齐器和 RD 编码器组成可插拔上下文模块。",
    data: "约 11,200 条长轨迹（含约 1,000 条实体 Aloha 演示）切分为 139,659 个微演示。",
    experiments: "LIBERO 与 RoboTwin2 每任务 10 次；实体 Aloha 四任务各 250 次，共 1,000 次，并报告 Wilson 置信区间。",
    novelty: "LIBERO 97.7%、RoboTwin2 60.4%；实体平均 83.2%，高于 π0 的 66.4% 与 VLA0 的 63.0%。",
    strengths: "大规模仿真与千次真机试验相互印证，且掩码、语义过滤和 DTW 都有独立消融。",
    limitations: "性能依赖演示覆盖与检索质量，长库检索和对齐仍带来额外时延。",
    transfer: "上下文学习在机器人上更像在线案例检索：先把示范对齐到当前阶段，再让策略读取，而不是盲目增加上下文长度。",
    technique: ["语义过滤先缩小候选，DTW 再按视觉—动作进度切出同阶段微演示。", "目标动作掩码阻止复制标签；部署时主干保持冻结，只更换检索到的演示。"],
    evaluation: ["去掉动作掩码后 LIBERO/RoboTwin2 降至 71.5/10.7；去掉 DTW 为 92.5/31.4，去掉语义过滤为 88.4/38.1。", "实体四任务 1,000 次总成功率 83.2%，95% Wilson 区间为 80.8%–85.4%。"],
    comparison: "π0、VLA0，以及无动作掩码、无 DTW、无语义过滤的成组消融。",
    reproducibilityStatus: "部分可复现", implementation: ["正文披露模型、检索/对齐流程、数据规模、rollout 数与置信区间。"], missing: ["完整演示库、训练代码与检索时延细节未确认公开。"],
    figureFile: "2609.07581-fig2.png", figureAlt: "ICI-VLA 检索并对齐微演示的完整流程", figureCaption: "Figure 2 · 语义检索、时序对齐、演示编码和目标动作掩码。来源：arXiv 原图。",
  },
  {
    title: "Dex-X: Learning Visual-Tactile Dexterous Manipulation From Human Videos with Simulated Interaction",
    arxivId: "2609.07747", url: "https://arxiv.org/abs/2609.07747",
    institutions: ["Tsinghua University", "Shanghai Qizhi Institute", "Sharpa", "Tongji University", "Renmin University of China"],
    signal: "从普通人手视频恢复手—物轨迹，在仿真中补上接触与触觉，再蒸馏到 29-DoF 灵巧手。",
    tags: ["Dexterous Manipulation", "Human Video", "Visual-Tactile"],
    classification: { research: "VLA", training: "BC", modalities: ["Tactile", "Point Cloud / 3D"], data: "UMI / Ego / Human Video", platforms: ["灵巧手"], deployment: "Sim2Real" },
    motivation: "人类视频规模大但没有机器人动作和触觉；只做运动学重定向又无法得到稳定接触策略。",
    methodSummary: "Dex-X 用姿态估计重建 30 Hz 人手与物体轨迹，重定向为仿真目标；状态专家通过 RL 学交互，再以 DAgger 蒸馏成读取点云和触觉的视觉策略。",
    architecture: "FoundationPose/WiLoR 提取轨迹，仿真专家访问完整状态；部署策略用 PointNet 编码统一点云，并把触觉接触点作为表面点加入。",
    data: "人类视频提供任务轨迹，仿真生成状态—动作—触觉监督；真机使用 29-DoF 灵巧手完成四类物体操作。",
    experiments: "仿真比较运动学模仿与 ManipTrans；真机四任务各 30 次，并逐项去掉视觉或触觉。",
    novelty: "仿真平均 65.9%，对比 ManipTrans 21.9% 和纯运动学 5.2%；真机各任务成功 28/30、24/30、22/30、16/30。",
    strengths: "把人类视频的规模优势与仿真接触监督结合，真机消融清楚显示视觉和触觉互补。",
    limitations: "轨迹重建误差、仿真接触差异和特定灵巧手形态仍限制跨硬件迁移。",
    transfer: "人类视频不必直接监督机器人动作；可以先恢复意图轨迹，再让仿真交互解决接触可执行性。",
    technique: ["先重建并重定向手—物运动，再用状态专家 RL 把几何目标变成可执行接触策略。", "DAgger 将专家蒸馏到视触觉学生，统一点云显式保留接触位置。"],
    evaluation: ["完整视触觉策略在立方体任务 28/30；无视觉 14/30、无触觉 11/30、仅本体 8/30。", "四项真机均为零样本 sim-to-real，最难的刮板任务仍达到 16/30。"],
    comparison: "运动学重定向、ManipTrans、完整视触觉策略及无视觉/无触觉/仅本体消融。",
    reproducibilityStatus: "部分可复现", implementation: ["论文给出重建、RL、DAgger、点云触觉表示和每任务 30 次真机协议。"], missing: ["完整视频数据、仿真资产与硬件复现包未确认公开。"],
    figureFile: "2609.07747-fig2.png", figureAlt: "Dex-X 从人类视频到仿真交互和真机策略的训练流程", figureCaption: "Figure 2 · 人类轨迹重建、仿真专家、DAgger 与视触觉部署。来源：arXiv 原图。",
  },
  {
    title: "Zero-Shot Sim-to-Real Contact-Rich Assembly via Proprioception-Anchored Cross-Modal Pretraining",
    arxivId: "2609.07534", url: "https://arxiv.org/abs/2609.07534",
    institutions: ["Shanghai Jiao Tong University", "CoreNetic.ai"],
    signal: "以跨域更稳定的本体状态变化监督视觉和力觉动态表征，实现接触装配的零样本 sim-to-real。",
    tags: ["PACE", "Contact-Rich Assembly", "Sim2Real"],
    classification: { research: "表征学习", training: "Pre-training", modalities: ["Force / Torque", "State / Proprioception"], platforms: ["机械臂", "夹爪"], deployment: "Sim2Real" },
    motivation: "渲染外观、接触动力学和力矩传感都存在域差，而标定后的关节位置与一致计算的速度相对稳定。",
    methodSummary: "PACE 用零和时序卷积去掉静态偏差，以视觉/力觉运动码预测本体状态转移并做循环一致性，再冻结编码器训练非对称 actor–critic。",
    architecture: "双腕相机、六轴 F/T 和 14 维本体输入；冻结视觉骨干、注意力池化、模态专属时序核与 256 维融合表示。",
    data: "四项装配任务各由特权 PPO 专家采 300 条仿真轨迹，80:20 划分；无需真机策略微调或物体位姿跟踪。",
    experiments: "四项任务每种方法真机连续 30 次；仿真每配置 3 个种子、每种子 100 个 episode。",
    novelty: "真机平均成功率 93.3%，仿真到真机仅下降 2.7 个百分点，并对视觉与接触扰动保持鲁棒。",
    strengths: "评测覆盖亚毫米装配、严格连续真机试验和多种表示/传感消融。",
    limitations: "只覆盖准静态单臂装配；对高速接触、不同机器人与传感器标定误差的泛化未知。",
    transfer: "跨域监督不必直接对齐所有传感器；可寻找两域共享的物理量作为锚点，让其他模态只保留与运动相关的变化。",
    technique: ["零和时序核压制外观与传感器静态偏置，正反向本体转移预测约束运动码。", "编码器冻结后仅在仿真训练策略，真机直接像素与力觉闭环部署。"],
    evaluation: ["四任务真机平均 93.3%，平均 sim-to-real drop 为 2.7 点。", "与位姿输入、MSDP、AugInsert 等基线及去除本体锚定/时间差分/单模态配置比较。"],
    comparison: "位姿策略、MSDP、AugInsert、通用视觉特征与 PACE 组件/模态消融。",
    reproducibilityStatus: "部分可复现", implementation: ["正文给出观测/动作维度、每任务 300 条专家轨迹、种子和真机 trial 数。"], missing: ["代码、仿真任务配置和完整训练权重未确认公开。"],
    figureFile: "2609.07534-fig2.png", figureAlt: "PACE 以本体状态转移锚定视觉和力觉特征", figureCaption: "Figure 2 · 模态专属时间差分、运动码和本体锚定编码器。来源：arXiv 原图。",
  },
  {
    title: "GIFT: Goal-Injected Fine-Tuning for Efficient Manipulation Policy Adaptation",
    arxivId: "2609.07006", url: "https://arxiv.org/abs/2609.07006",
    institutions: ["Nanjing University of Aeronautics and Astronautics", "Key Laboratory of Brain-Machine Intelligence Technology, Ministry of Education"],
    signal: "用图像编辑器合成目标观测，将目标—当前视觉差注入 VLA，只微调少量新增模块与动作头。",
    tags: ["Goal Image", "Efficient Fine-Tuning", "VLA"],
    classification: { research: "VLA", training: "Post-training", data: "数据增强", platforms: ["机械臂", "夹爪"] },
    motivation: "少量演示适配新任务时，基础策略往往不知道最终视觉目标；全量微调成本高且易遗忘。",
    methodSummary: "GIFT 从初始观测生成目标图像，计算目标与当前视觉表征差，经零初始化卷积注入主干；冻结大部分 VLA，仅更新目标投影、注入层和动作头。",
    architecture: "目标图与当前观测共享视觉编码，语义差分经 zero-conv 加到 VLA 特征；每步复用目标条件生成动作。",
    data: "两项真机任务各 30 条演示，分别测试分布内与分布外摆放。",
    experiments: "每任务、每设置 30 次真机试验；比较 π0.5 基线、GIFT 及目标注入组件。",
    novelty: "任务一 ID/OOD 从 56.7/33.3% 升至 71.7/51.7%；任务二从 36.7/23.3% 升至 43.3/36.7%。",
    strengths: "少数据、真实部署和 ID/OOD 分开报告，收益主要来自显式目标条件而非扩大微调范围。",
    limitations: "目标图生成增加前处理成本，且适配上限仍受基础策略动作能力约束。",
    transfer: "目标状态难以语言精确描述时，可把“完成后的样子”作为稠密视觉条件注入策略。",
    technique: ["图像编辑器从初始观测构造目标图，语义差分显式表达当前与目标之间的缺口。", "零初始化注入层避免破坏预训练表征，只训练小模块和动作头。"],
    evaluation: ["任务一 OOD 提升 18.4 点，任务二 OOD 提升 13.4 点。", "每个百分比均来自 30 次真机试验，而非离线预测。"],
    comparison: "π0.5 与 GIFT，在两个任务的 ID/OOD 条件下成对比较。",
    reproducibilityStatus: "部分可复现", implementation: ["正文披露微调模块、目标生成方式、演示量和每设置 trial 数。"], missing: ["图像编辑模型、训练代码和完整随机种子未确认公开。"],
    figureFile: "2609.07006-fig1.png", figureAlt: "GIFT 目标图生成和逐步策略执行概览", figureCaption: "Figure 1 · 目标图生成与目标条件策略执行。来源：arXiv 原图。",
  },
  {
    title: "DeCAL: Towards Physically-Grounded Dexterous Vision-Language-Action Models via Contact-Aware Latent Co-Imagination",
    arxivId: "2609.09119", url: "https://arxiv.org/abs/2609.09119",
    institutions: ["Peking University", "Beijing Academy of Artificial Intelligence"],
    signal: "让视觉未来与触觉接触未来在潜空间共同想象，再由不同流匹配分支控制手臂和灵巧手。",
    tags: ["Dexterous VLA", "Tactile", "Latent World Model"],
    classification: { research: "WAM", training: "Post-training", modalities: ["Tactile"], platforms: ["机械臂", "灵巧手"], deployment: "真机部署优化" },
    motivation: "灵巧操作需要预测接触后果；仅视觉 VLA 容易在遮挡和微小受力变化下产生物理上不可靠的动作。",
    methodSummary: "DeCAL 用三专家 MoT 分离理解、未来生成和动作，触觉交叉注意与接触门控共同预测视觉/触觉潜变量，再用手臂—手指分解 flow matching 输出动作。",
    architecture: "理解专家与视觉未来专家基于 Qwen3-VL，动作专家融合视觉、触觉和未来潜变量；手臂与手部分别建模。",
    data: "双 UR5、两只 22-DoF SharpaWave、三台 RealSense D435 和 320×240 指尖触觉，以 30 Hz 执行六项任务。",
    experiments: "六项真机任务每方法各 20 次，并测试未见物体、接触模块和未来预测消融。",
    novelty: "平均成功率比最强基线高超过 15 点；未见物体最终阶段达到 0.75，比基线高 30 点；每动作块延迟 0.27 秒。",
    strengths: "完整双臂灵巧硬件、六任务与未见物体评测，接触表征和动作分解均有消融。",
    limitations: "硬件堆栈昂贵，触觉标定和双手同步复杂；跨传感器与跨手型迁移尚未验证。",
    transfer: "未来预测若要服务接触控制，应把视觉结果和触觉结果放进同一潜空间，并让动作生成按肢体动力学拆分。",
    technique: ["接触门控只在物理交互阶段强调触觉，视觉—触觉交叉注意共同预测未来潜变量。", "手臂和灵巧手使用分解 flow matching，降低统一高维动作空间的冲突。"],
    evaluation: ["六项真机任务每项 20 次，平均领先最强基线超过 15 点。", "未见物体最终阶段 75%，动作块端到端延迟 0.27 秒。"],
    comparison: "视觉 VLA、视触觉策略、去除接触门控/未来预测及统一动作头等配置。",
    reproducibilityStatus: "部分可复现", implementation: ["正文给出三专家结构、硬件规格、30 Hz 控制和 20 次/任务协议。"], missing: ["训练数据、触觉标定工具与模型权重未确认公开。"],
    figureFile: "2609.09119-fig2.png", figureAlt: "DeCAL 视觉触觉潜变量共想象与动作生成架构", figureCaption: "Figure 2 · 三专家、接触门控、未来潜变量与分解动作头。来源：arXiv 原图。",
  },
  {
    title: "HuRo: Robotizing Human Videos for Scalable VLA Pretraining",
    arxivId: "2609.10706", url: "https://arxiv.org/abs/2609.10706",
    institutions: ["RLWRLD", "Yonsei University"],
    signal: "把公开视频中的人手外观替换成机器人，并把手部运动转为机器人动作，形成可直接预训练 VLA 的大规模数据。",
    tags: ["Human Video", "Robotization", "VLA Pretraining"],
    classification: { research: "VLA", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://3587jjh.github.io/HuRo/" }],
    motivation: "人类视频数量远大于机器人数据，但外观与动作空间不匹配，直接混训会让 VLA 学到错误的本体先验。",
    methodSummary: "HuRo 先重定向人手轨迹，再用视觉覆盖把人手替换成机器人末端执行器，同时生成语言与机器人动作标签。",
    architecture: "机器人化管线产出统一机器人观测—动作对，先做 VLM/VLA 预训练，再在少量实体机器人数据上微调。",
    data: "五个人类视频来源合计 63 万段、1.42 亿帧；实体 ALLEX 四任务用于迁移评测。",
    experiments: "比较不同预训练数据比例、原始人类视频与机器人化视频，并在 ID/OOD 真机任务上评测。",
    novelty: "随数据比例从 0% 增至 100%，平均成功率 51.5→80.3；ID 68.1→88.4，OOD 34.9→72.2。",
    strengths: "数据规模大、缩放曲线明确，OOD 收益比 ID 更大，支持机器人化而非简单混入人类视频。",
    limitations: "视觉覆盖会产生遮挡伪影；动作重定向没有完整建模碰撞、接触、力和触觉。",
    transfer: "利用人类视频时应同时修正外观和动作语义，让预训练分布在进入策略前先变成“机器人视角”。",
    technique: ["重定向把人手运动转换成机器人动作，视觉覆盖同步替换图像中的执行器外观。", "机器人化数据用于预训练，少量目标机器人数据负责最后的动力学适配。"],
    evaluation: ["全量机器人化预训练平均 80.3%，无该预训练为 51.5%。", "OOD 成功率从 34.9% 提至 72.2%，显示大规模语义与动作覆盖主要改善组合泛化。"],
    comparison: "无预训练、不同机器人化数据比例、原始人类视频预训练与 HuRo。",
    reproducibilityStatus: "部分可复现", implementation: ["项目页和正文给出五类数据源、总规模、机器人化流程与缩放实验。"], missing: ["完整处理代码、授权后的视频分发范围与真机逐任务 trial 数需核对。"],
    figureFile: "2609.10706-fig1.png", figureAlt: "HuRo 大规模人类视频机器人化和 VLA 预训练", figureCaption: "Figure 1 · 人类数据、机器人化管线、预训练与实体部署。来源：arXiv 原图。",
  },
  {
    title: "RoboDrop: Curating VLA Post-Training Data via Local Gradient Compatibility",
    arxivId: "2609.10021", url: "https://arxiv.org/abs/2609.10021",
    institutions: ["Tsinghua University", "Striding AI"],
    signal: "在训练过程中比较候选 episode 与局部干净验证集的梯度方向，只保留会改善邻近任务的示范。",
    tags: ["Data Curation", "Gradient Compatibility", "VLA"],
    classification: { research: "VLA", training: "Post-training", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    motivation: "示范数据的质量因任务和视觉上下文而异，使用全局损失或静态规则会误删困难但有用的轨迹。",
    methodSummary: "RoboDrop 用 T5 任务语义和 DINO 视觉近邻构造局部验证参照，计算候选与参照梯度余弦兼容性；episode 内聚合并可用 GMM 自动切分。",
    architecture: "先热身一轮，再在线缓存/周期刷新局部梯度；CountSketch 将梯度压到 4096 维，降低打分开销。",
    data: "LIBERO 受控污染、自然质量差异示范和实体机器人后训练集。",
    experiments: "四类受控污染报告 AUROC；跨骨干比较数据筛选方法，并在真机后训练中检查成功率。",
    novelty: "四类污染平均 AUROC 88.33%；真机成功率从未筛选数据的 35.0% 提至 67.5%。",
    strengths: "评分与训练目标直接对齐，又通过语义和视觉近邻避免拿无关任务作参照。",
    limitations: "需要额外验证集和周期梯度计算；局部近邻错误会把偏差反馈给筛选器。",
    transfer: "数据质量是条件化概念：判断一条轨迹是否有用，应问它是否改善相似任务，而不是只看全局 loss。",
    technique: ["T5 与 DINO 共同选出语义和视觉近邻，构造每条样本的局部验证梯度。", "缓存梯度、CountSketch 与每 200 步刷新控制在线打分成本，GMM 可自动定阈值。"],
    evaluation: ["受控污染平均 AUROC 88.33%，覆盖错误动作、错误目标与视觉异常等四类噪声。", "实体后训练成功率 35.0→67.5%，说明离线识别能力转化为策略收益。"],
    comparison: "损失筛选、全局梯度方法、数据影响基线、不同 VLA 骨干及 GMM 自动过滤。",
    reproducibilityStatus: "部分可复现", implementation: ["正文披露热身轮、Kvis=10、刷新间隔 200、4096 维 CountSketch 和 episode 聚合。"], missing: ["代码、实体数据与完整真机 trial accounting 未确认公开。"],
    figureFile: "2609.10021-fig1.png", figureAlt: "RoboDrop 局部梯度兼容性数据筛选流程", figureCaption: "Figure 1(a) · 候选轨迹、局部验证梯度与自动过滤。来源：arXiv 原图。",
  },
  {
    title: "HaWMPO: Hallucination-Aware World Model-based Policy Optimization for Generalist Robot Policy",
    arxivId: "2609.09941", url: "https://arxiv.org/abs/2609.09941",
    institutions: ["Joy Future Academy, JD", "Jilin University"],
    signal: "用独立幻觉模型给世界模型 rollout 估计可信度，把不可靠想象的奖励软降权再做策略优化。",
    tags: ["World Model", "Policy Optimization", "Hallucination"],
    classification: { research: "WAM", training: "RL", modalities: ["Depth / RGB-D"], platforms: ["机械臂", "Humanoid"] },
    motivation: "世界模型可以低成本生成策略训练轨迹，但视觉幻觉会把错误未来当成高奖励经验。",
    methodSummary: "HaWMPO 联合 DINOv3、深度、光流和 MUSIQ 信号训练幻觉评分器，将其作为软置信权重调整 reward，再用 GRPO 更新 VLA。",
    architecture: "动作条件世界模型生成未来帧；VLA rollout、奖励模型和幻觉模型共同产生组内相对优势，可靠样本权重更高。",
    data: "LIBERO 四套任务与 Unitree G1 两项实体任务；真实 rollout 仅用于评测。",
    experiments: "LIBERO 比较 SFT、WMPO、WoVR 与 HaWMPO；G1 两任务每方法各 20 次。",
    novelty: "LIBERO 平均 63.7%，比基础策略高 15 点、比 WMPO 高 6.9 点、比 WoVR 高 2.8 点；真机平均 80%。",
    strengths: "把世界模型质量从隐含假设变成可测权重，感知指标、奖励与策略优化形成闭环。",
    limitations: "真机只覆盖两项短程任务，幻觉信号仍由人工选定的视觉指标构成。",
    transfer: "用生成模型训练策略时，先估计每条想象轨迹的可信度，再讨论奖励高低。",
    technique: ["多视觉信号融合成幻觉评分，覆盖语义、几何、运动与图像质量。", "Reward-Soft 在 GRPO 内连续降权可疑 rollout，避免硬删除造成样本不足。"],
    evaluation: ["LIBERO 63.7%，相对 SFT +15.0、WMPO +6.9、WoVR +2.8 点。", "G1 两任务各 20 次，平均 80%；SFT 67.5%、WoVR 72.5%。"],
    comparison: "SFT、普通世界模型策略优化 WMPO、WoVR 和不同幻觉信号消融。",
    reproducibilityStatus: "部分可复现", implementation: ["论文给出世界模型、四类幻觉信号、Reward-Soft/GRPO 结构和真机次数。"], missing: ["代码、奖励模型标注与更长时真机验证未确认公开。"],
    figureFile: "2609.09941-fig1.png", figureAlt: "HaWMPO 世界模型幻觉估计与策略优化闭环", figureCaption: "Figure 1 · 世界模型 rollout、幻觉评分、软奖励与策略更新。来源：arXiv 原图。",
  },
  {
    title: "UniMPA: A Unified Memory-Prediction-Action Model via Action-Grounded Transition Modeling",
    arxivId: "2609.11875", url: "https://arxiv.org/abs/2609.11875",
    institutions: ["Harbin Institute of Technology, Shenzhen", "Nanyang Technological University S-Lab"],
    signal: "用动作锚定的双向记忆统一历史检索、未来预测与动作生成，只在关键状态转移时触发像素预测。",
    tags: ["Memory", "Future Prediction", "VLA"],
    classification: { research: "Memory", training: "Pre-training", modalities: ["State / Proprioception"], platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "现有 VLA 往往把记忆、世界模型和动作头独立堆叠，既重复计算，又没有用动作定义哪些状态转移值得保留。",
    methodSummary: "UniMPA 以动作键组织视觉—动作与动作—视觉记忆库，训练时重建未来；部署时保留潜变量记忆，并由 transition-critical gate 选择性触发像素未来校准。",
    architecture: "VLM 骨干连接世界专家、双向 memory bank、触发门、像素预测器和原型偏置 flow action proposer。",
    data: "LIBERO、LIBERO-Plus、RoboTwin 困难任务与两类双臂真机平台，覆盖七套实体任务。",
    experiments: "仿真跨三类基准比较；真机覆盖两平台七套任务，并消融记忆方向、触发门和像素分支。",
    novelty: "LIBERO 98.6% 对 π0.5 的 96.9%；LIBERO-Plus 85.3% 对 73.6%；RoboTwin 困难任务提升 18.5 点，真机平均提升 12.6 点。",
    strengths: "统一结构同时覆盖记忆、未来和动作，仿真困难集与双平台真机均有收益。",
    limitations: "训练额外增加约 25%–50% epoch；超大像素预测分支和长历史库的部署成本仍需详细测量。",
    transfer: "记忆应围绕动作导致的状态转移建索引；昂贵未来预测只在转移关键时刻调用。",
    technique: ["双向 memory bank 同时学习由视觉检索动作和由动作检索未来视觉。", "触发门检测关键转移，平时只维护潜记忆；必要时用像素未来校准动作原型。"],
    evaluation: ["LIBERO 98.6%、LIBERO-Plus 85.3%，分别高于 π0.5 的 96.9% 和 73.6%。", "RoboTwin hard +18.5 点，双臂真机七套任务平均 +12.6 点。"],
    comparison: "π0.5、VLA/WAM 基线，以及无记忆、单向记忆、无触发门、无像素校准等消融。",
    reproducibilityStatus: "部分可复现", implementation: ["正文披露两阶段训练、双向记忆、触发门、数据集和相对训练开销。"], missing: ["代码、模型权重与真机逐任务 trial accounting 未确认公开。"],
    figureFile: "2609.11875-fig2.png", figureAlt: "UniMPA 统一记忆预测动作框架", figureCaption: "Figure 2 · 双向记忆、选择性未来预测和动作 proposer。来源：arXiv 原图。",
  },
  {
    title: "IMLE-VLA: Fast Single-Step Action Generation for Vision-Language-Action Policies",
    arxivId: "2609.10915", url: "https://arxiv.org/abs/2609.10915",
    institutions: ["Simon Fraser University", "University of Pennsylvania", "Amii", "Canada CIFAR AI Chair"],
    signal: "用条件 IMLE 的多候选最近样本训练替代十步 flow matching，把动作块生成压缩到一次前向。",
    tags: ["Fast Inference", "IMLE", "VLA"],
    classification: { research: "VLA", training: "Post-training", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "扩散/流匹配动作头每个动作块要多次迭代，控制频率和吞吐成为 VLA 真机部署瓶颈。",
    methodSummary: "IMLE-VLA 每个条件采两个单步动作候选，只让最接近示范动作的候选反向传播，从而保留多模态分布而无需迭代去噪。",
    architecture: "保留 3B π0.5 视觉语言主干，替换 flow-matching action head；单次前向直接产生完整 action chunk。",
    data: "LIBERO 四套 40 任务与 Franka 四项实体操作。",
    experiments: "LIBERO 每任务 50 个 episode；真机比较成功率、控制频率、端到端耗时与动作 jerk。",
    novelty: "达到 55 Hz 对 flow matching 的 15 Hz，吞吐最高提升 11×；LIBERO 平均 98.0%，并降低真机动作 jerk。",
    strengths: "速度收益来自动作头算法而非缩小主干，且仿真成功率和真机平滑性没有明显交换。",
    limitations: "动态反应只在单项任务中验证；推理速度基于 L40S，跨硬件对比并不完全等价。",
    transfer: "高频控制不一定需要迭代生成；用多候选训练可以把多模态性转移到单步采样。",
    technique: ["每个条件采 m=2 个动作块，按最近样本分配梯度，避免平均化多个可行动作。", "推理时只保留一次动作头前向，主干和动作块接口与 π0.5 兼容。"],
    evaluation: ["LIBERO 40 任务各 50 episode，平均 98.0%。", "55 Hz 对 15 Hz；真机 wall time 缩短 3.9–6.6×，吞吐最高 11×，jerk 降低 2.2–3.0×。"],
    comparison: "π0.5 十步 flow matching、单步回归和 IMLE 候选数/训练目标消融。",
    reproducibilityStatus: "部分可复现", implementation: ["正文给出 3B 主干、m=2、40×50 仿真协议、控制频率与硬件。"], missing: ["代码、权重和真机逐任务 trial 数未确认公开；跨 GPU 延迟需复测。"],
    figureFile: "2609.10915-fig1.png", figureAlt: "IMLE-VLA 单步动作头与 flow matching 对比", figureCaption: "Figure 1 · 单步 IMLE 动作头与十步 flow matching 的速度对比。来源：arXiv 原图。",
  },
];

export const paperDaily20260911 = entries.map(makePaper);
