import type { Paper } from "./site-data";

export const paperDaily20260727Fresh: Paper[] = [
  {
    rank: 1,
    title: "ViTacWorld: Scaling Visuo-Tactile World Models for Contact-Rich Robot Manipulation",
    arxivId: "2607.22530",
    url: "https://arxiv.org/abs/2607.22530",
    institutions: ["ShanghaiTech University", "InstAdapt"],
    signal: "把视觉、触觉和动作放进同一个可生成 rollout 的世界模型，用合成轨迹补足昂贵的真机接触数据",
    tags: ["Visuo-Tactile", "World Model", "Data Augmentation"],
    classification: { research: "WM", training: "Pre-training", modalities: ["Tactile", "State / Proprioception"], data: "合成 / 仿真数据", platforms: ["机械臂", "夹爪"], deployment: "Real2Sim2Real" },
    resources: [{ label: "项目页", url: "https://vitacworld.github.io/" }],
    motivation: "接触丰富任务里，视觉看不到的受力与滑移会直接决定成败，但真实触觉数据采集慢、依赖传感器，任务覆盖也有限。",
    methodSummary: "ViTacWorld 把触觉作为额外生成视角，依据动作同步预测第三视角、腕部视觉和触觉未来；生成的 rollout 一方面扩充策略训练集，另一方面用于离线预测策略是否会成功。",
    architecture: "视觉与触觉分别编码为 latent token，经 view-aware DiT 与跨视角注意力对齐；动作作为条件驱动多视角未来生成。模型继承视频生成先验，再学习接触动力学。",
    optimization: "第一阶段混合公开真实触觉数据与 Isaac Sim/Xense 仿真数据预训练，第二阶段用目标真机示范和包含成败的 policy rollout 微调；下游比较 ACT 与 π0.5 的视觉/触觉策略。",
    data: "预训练使用 OmniViTac 中超过 16K 条轨迹和超过 5K 条任务对齐仿真轨迹，总量超过 21K；目标域另有 300 条真机专家示范、每任务 50 条策略 rollout。",
    experiments: "Franka Panda + Robotiq 2F-85 + Xense 触觉完成充电器插接、黄瓜削皮、U 形块插入和方块插入，每个策略/任务 10 次；π0.5+tactile 的四任务平均成功率由 42.5% 提升到 67.5%。",
    novelty: "相对只把世界模型当视频预测器或策略内部辅助头，本文直接生成同步的视觉—触觉—动作轨迹，并验证这些轨迹能改善下游触觉策略。",
    experimentDetails: [
      { title: "真机数据增强", setup: "四个接触丰富任务；300 条专家示范用于策略 warm-up，每任务再采 50 条含成功与失败的 policy rollout；每个最终策略在每任务运行 10 次。", comparisons: "ACT、π0.5 的视觉版本、触觉版本，以及加入一轮或两轮 ViTacWorld 合成 rollout 的版本。", results: ["π0.5+tactile 的平均成功率从 42.5% 增至 67.5%。", "ACT+tactile 从 15.0% 增至 27.5%；纯视觉 π0.5 从 35.0% 增至 47.5%。", "改进覆盖插接、削皮和精密插入，而不是只在单一任务上报告。"], evidenceNote: "每任务 10 次可支持大幅差异，但不适合对接近的数值作精细排序。" },
      { title: "世界模型作为策略评估器", setup: "在相同初始观测下生成三条 imagined rollout，以多数票预测成败，并与对应真机执行逐项匹配。", comparisons: "ViTacWorld 的预测结果与真实策略执行结果。", results: ["U-Block 插入中真机 10 次成功 8 次，模型预测成功 7 次。", "10 个初始状态中有 9 个判断与真机一致，两个真实失败均被预测为失败。"], evidenceNote: "该评估只在受控初始条件和有限任务上验证，不能直接等同于通用离线评测器。" },
    ],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、数据组成、训练阶段、硬件和逐任务评估协议可核验。"], implementation: ["13 帧窗口、15 Hz；Stage-I 全局 batch 256、30K steps、学习率 3e-5，使用 32 张 H20 约 50 小时。", "公开数据与仿真数据约按 2:1 采样；真实传感器为 Xense，视觉为 D435 与 ZED Mini。"], missing: ["完整训练代码、权重和目标域真机数据尚未在论文 v1 中确认全部开放。"] },
    deepDive: { lead: "ViTacWorld 的核心不是简单把触觉拼到策略输入，而是把触觉变化建模成动作后果，使世界模型真正能够生成接触过程。", sections: [{ title: "多视角动作条件生成", paragraphs: ["第三视角、腕部相机和触觉图像分别编码；view identity 和跨视角注意力负责保持同一时刻的接触事件一致。", "动作条件决定未来 robot-object interaction，触觉分支提供视觉中不可见的局部接触约束。"] }, { title: "从广域预训练到目标 rollout", paragraphs: ["公开数据提供多种触觉传感器与交互类型，任务对齐仿真补充目标装置附近的接触模式。", "最终用真实策略 rollout 微调，是为了让生成分布接近下游策略真正会访问的状态，包括失败和偏离轨迹。"] }], experimentReading: ["四任务、两类策略主干和视觉/触觉对照形成了较完整的证据链。", "合成 rollout 的收益明显，但每任务 10 次和特定触觉硬件限制了统计精度与跨平台结论。"], reflections: [] },
    strengths: "同时给出数据规模、真机对照、策略主干对照和评估器匹配结果，消融与应用链条较完整。",
    limitations: "强依赖特定光学触觉传感器和较大的视频模型训练资源；真机任务、平台与评估次数仍有限。",
    transfer: "已有视觉策略可把触觉当成一个生成视角，并用真实失败 rollout 做目标域微调，而不必从零训练完整世界模型。",
    figures: [{ src: "/report-assets/2026-07-27/2607.22530-fig1.png", alt: "ViTacWorld 多视角视觉触觉世界模型与两阶段训练流程", caption: "Figure 1 · ViTacWorld 的模型、数据扩增和策略评估流程。图片来自 arXiv v1 HTML 原图。" }],
  },
  {
    rank: 2,
    title: "The Curse of Precision: A Data Scaling Law for High-Precision Robotic Manipulation",
    arxivId: "2607.23108",
    url: "https://arxiv.org/abs/2607.23108",
    institutions: ["Tsinghua University", "Institute for Embodied Intelligence and Robotics, Tsinghua University", "OpenMind Robotics"],
    signal: "把高精度模仿学习的数据成本写成可拟合的 scaling law，并把传感器和专家质量显式纳入可达精度上限",
    tags: ["Scaling Law", "Precision", "Imitation Learning"],
    classification: { research: "其他", training: "BC", modalities: ["State / Proprioception"], data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    motivation: "开放世界研究常问数据多样性如何提高泛化，而装配类任务更关心从 99% 到 99.9% 或从毫米到亚毫米时，示范数量会怎样增长。",
    methodSummary: "论文在不同几何间隙与数据量下拟合成功率曲线，提出 log(N) 与 1/(P-c) 成正比；其中 c 不是任务常数，而是整套传感、专家和策略系统的极限精度。",
    architecture: "策略采用图像或状态观测的模仿学习系统；研究重点不是新网络，而是严格控制数据量、目标公差、观测配置和专家质量，并跨任务拟合共同的精度 scaling 形式。",
    optimization: "在相同策略训练流程下系统扫描数据集规模与公差，并分别加入腕部相机或更有效的专家策略，观察拟合参数 c 是否下降。",
    data: "ManiSkill3 的 Peg Insertion、Stack Cuboid 与 Roll Ball；超过 100 次独立模型训练、数万次评估 rollout，数据量与任务精度按网格变化。",
    experiments: "三类任务均出现靠近极限精度时数据需求急剧上升的现象；增加腕部相机或改进专家会降低 c，说明继续堆同质示范不能替代系统能力改造。",
    novelty: "相对以对象/场景数量为横轴的机器人 scaling law，本文把几何精度设为自变量，并用可达极限 c 区分数据瓶颈与系统瓶颈。",
    experimentDetails: [{ title: "精度—数据规模扫描", setup: "Peg Insertion 与 Stack Cuboid 使用图像观测，Roll Ball 使用状态观测；对多档公差和示范数量独立训练并进行数万次 rollout。", comparisons: "幂律/指数等备选拟合，以及不同相机配置和专家策略。", results: ["log(N) ∝ 1/(P-c) 能描述靠近极限精度时的超快数据增长。", "腕部相机与更强专家会显著改变 c，而不仅是沿同一曲线移动。", "状态任务也出现相同结构，说明现象不只来自图像编码器。"], evidenceNote: "全部核心实验在高保真仿真中完成，尚未给出真实装配线上的跨日漂移验证。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["任务、扫描变量、拟合形式、训练次数和评估规模在正文中给出。"], implementation: ["使用 ManiSkill3；总计超过 100 个独立训练 run 和数万条评估 rollout。", "关键诊断是比较不同 sensor/expert 条件下的极限参数 c。"], missing: ["论文 v1 未确认完整训练代码与全部生成示范开放；没有真机协议。"] },
    deepDive: { lead: "这篇工作的实用价值在于：当精度曲线接近 c 时，继续加同质数据的边际成本会急剧恶化，此时应优先改传感或专家。", sections: [{ title: "极限精度参数", paragraphs: ["P 表示目标公差，N 表示达到固定成功率所需示范数；当 P 接近 c，分母趋近零，数据需求快速上升。", "c 随系统配置变化，因此可被用于定位当前瓶颈是感知、专家还是策略表达。"] }, { title: "怎样读这条曲线", paragraphs: ["它不是声称所有机器人任务共享同一个常数，而是声称在给定系统与任务下，精度扫描可由同一函数形式描述。", "相机和专家对照表明，数据 scaling 与系统工程不能被拆开解释。"] }], equations: [{ name: "高精度数据 scaling law", expression: "log(N) ∝ 1 / (P - c)", explanation: "N 为达到固定成功率所需示范数，P 为目标精度，c 为当前 agent system 的极限精度。" }], experimentReading: ["训练和 rollout 数量足以支持曲线形状，但证据来自仿真。", "对 c 的解释建立在受控干预上，比只展示拟合优度更有说服力。"], reflections: [] },
    strengths: "超过 100 次训练、数万次 rollout，并通过相机和专家干预验证参数含义。",
    limitations: "没有真机高精度装配验证；不同算法、硬件误差与长期漂移是否仍服从同一形式未知。",
    transfer: "高精度项目可先做小规模公差扫描拟合 c，再决定预算应投向新增示范、腕部视觉还是专家控制器。",
    figures: [{ src: "/report-assets/2026-07-27/2607.23108-fig4.png", alt: "Peg insertion 中公差与示范数量对应的成功率曲线", caption: "Figure 4 · Peg Insertion 的精度—数据规模曲线。图片来自 arXiv v1 HTML 原图。" }],
  },
  {
    rank: 3,
    title: "One Hand Watches The Other: Dynamic Multi-Agent Cooperation for Sample-Efficient Bimanual Manipulation in Dynamic Environments",
    arxivId: "2607.22119",
    url: "https://arxiv.org/abs/2607.22119",
    institutions: ["University of Freiburg"],
    signal: "把另一只机械臂视为动态任务参数，让多流策略从静态示范零样本迁移到动态双臂协作",
    tags: ["Bimanual", "Dynamic Manipulation", "Multi-Stream Policy"],
    classification: { research: "表征学习", training: "BC", modalities: ["State / Proprioception"], platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    motivation: "task-parameterized 多流策略通常假设参考坐标系来自外部静态物体；双臂协作中，一只手操纵的物体和自身姿态会成为另一只手的动态环境。",
    methodSummary: "DynaMAC 从示范中估计物体与机械臂之间的运动学联系，把对侧机械臂和动态物体都表示为随时间变化的 task parameter，再由多流策略在这些局部坐标系中生成动作。",
    architecture: "框架对底层策略主干无关：每个运动流在对应参考系中建模，执行时根据动态 frame 合成；双臂没有固定 leader-follower，也不增加单独的协调网络。",
    optimization: "只用静态示范训练运动流，测试时在线更新动态参考系；DynaBench 分开测单臂动态环境、双臂交接和动态物体操作。",
    data: "核心设置以少量静态示范学习；论文报告其示范量比领先概率/生成式基线少 20 倍，并专门构建 DynaBench 做动态与双臂评估。",
    experiments: "跨动态环境和双臂任务，DynaMAC 相对主要基线提升超过 35 个百分点；关键结果是从静态示范到动态场景的零样本迁移。",
    novelty: "相对把 task frame 当作外生量的多流方法，DynaMAC 允许 frame 由另一只手的动作内生地产生，从而统一动态操纵与双臂协调。",
    experimentDetails: [{ title: "DynaBench 动态与双臂评估", setup: "静态示范训练，动态物体与双臂协作测试；比较不同示范预算。", comparisons: "领先概率策略、生成式策略以及不建模内生动态 frame 的多流基线。", results: ["整体领先超过 35 个百分点。", "达到结果所需样本量比比较方法少 20 倍。", "静态示范可以零样本用于动态环境，减少专门采集同步双臂数据的需求。"], evidenceNote: "论文强调相对提升和样本倍率；各任务绝对成功率应结合原表逐项阅读。" }],
    reproducibilityDetails: { status: "信息不足", verifiedResources: ["DynaBench 任务定义、框架和对照结论可从正文核验。"], implementation: ["核心实现依赖动态 task frame、运动学关系估计和多流策略组合。"], missing: ["论文 v1 未确认公开代码/数据；跨机器人硬件和大规模人机协作尚未验证。"] },
    deepDive: { lead: "DynaMAC 把协作问题改写为参考系问题：另一只手不再只是需要预测的扰动，而是能被当前策略直接读取的动态坐标系。", sections: [{ title: "内生 task parameter", paragraphs: ["对环境中独立运动的物体和被机器人操纵的物体分别建模运动联系，避免把因果来源混在同一流中。", "当一只手抬起物体时，另一只手的目标姿态随该手与物体共同变化，自然形成交接条件。"] }, { title: "样本效率来源", paragraphs: ["局部运动模式在参考系中保持不变，动态变化由 frame 变换承担，因此无需覆盖所有双臂相对位置。", "这种归纳偏置适合结构明确的协作任务，但依赖可跟踪的对象和可靠的运动学对应。"] }], experimentReading: ["静态到动态零样本迁移直接对应方法假设。", "超过 35 点与 20 倍样本优势显著，但公开资源和跨硬件验证仍决定其实际复用难度。"], reflections: [] },
    strengths: "方法归纳偏置清楚，样本效率、动态泛化和双臂协作由同一机制解释。",
    limitations: "需要稳定的对象/手臂 frame 与运动学关系；对遮挡、柔性物体和接触状态估计误差的稳健性仍有限。",
    transfer: "已有 task-parameterized policy 可把对侧机械臂或移动目标注册为动态 frame，优先验证是否能减少同步双臂示范。",
    figures: [{ src: "/report-assets/2026-07-27/2607.22119-fig1.png", alt: "DynaMAC 将动态物体和另一只手作为任务参数的双臂协作示意", caption: "Figure 1 · DynaMAC 的动态参考系与双臂交接示意。图片来自 arXiv v1 HTML 原图。" }],
  },
  {
    rank: 4,
    title: "Robot-Factored World Models via Robot Rendering",
    arxivId: "2607.22535",
    url: "https://arxiv.org/abs/2607.22535",
    institutions: ["Seoul National University", "RLWRLD"],
    signal: "先用控制器、运动学和 URDF 把动作渲染成机器人几何，再让视频世界模型只学习场景对该几何运动的响应",
    tags: ["World Model", "Robot Rendering", "Cross-Embodiment"],
    classification: { research: "WM", training: "Pre-training", modalities: ["Depth / RGB-D", "State / Proprioception"], data: "跨本体数据", platforms: ["机械臂", "Humanoid", "夹爪"], deployment: "跨本体迁移" },
    motivation: "直接用关节/末端命令条件化视频模型，要求模型同时学习控制器如何实现动作与环境如何响应；用真实未来状态又会泄漏本应预测的接触结果。",
    methodSummary: "先让机器人自己的控制器与运动学把命令 rollout 成 nominal trajectory，再通过 URDF 渲染 RGB/深度机器人几何；世界模型接收静态场景上下文与渲染几何，预测物体响应。",
    architecture: "camera-aware 静态 RGB/depth 提供场景与视角，robot mask/RGB、end-effector depth 和 scene depth 编码动作实现；视频 diffusion backbone 只需要学习接触后的场景变化。",
    optimization: "以 Wan 2.1 14B 视频模型为主干，在 DROID 与 RoboCasa-GR1 等轨迹上微调；比较向量动作、未来状态、robot rendering、depth 消融与未见本体组合。",
    data: "使用真实 DROID 和仿真 RoboCasa-GR1 轨迹，并通过控制器、运动学与 URDF 为各本体生成 nominal robot render；另用人类手部运动重定向生成机器人视频。",
    experiments: "渲染接口在主比较中优于 vector-conditioned baseline，并能在推理时组合未见机器人本体；depth 消融显示仅靠二维重叠不足以可靠表达接触与遮挡。",
    novelty: "它不强迫一个共享网络隐式学习各本体的 action realization，而是用部署时可得的显式几何作为统一 action interface。",
    experimentDetails: [{ title: "动作接口与跨本体对照", setup: "真实 DROID 与 RoboCasa-GR1，比较同一视频模型在不同动作条件表示下的未来视频预测。", comparisons: "动作向量、未来 robot state、RGB robot rendering、加入 end-effector/scene depth，以及未见本体组合。", results: ["robot-factored rendering 优于向量条件化接口。", "加入 depth 能改善接触距离与遮挡判断。", "同一接口能在推理时接收未见本体的 URDF rendering，并将人类演示重定向成机器人视频。"], evidenceNote: "结果主要评估世界模型预测质量与定性本体组合，尚未系统报告由此带来的真实策略成功率。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["数据源、渲染因素、Wan 2.1 主干和训练超参表可核验。"], implementation: ["nominal trajectory 来自部署控制器与运动学，不读取交互后的真实 robot state。", "训练输入显式分离静态场景、robot geometry、end-effector depth 与 scene depth。"], missing: ["完整训练代码和权重尚未确认公开；未提供闭环真机策略评估。"] },
    deepDive: { lead: "Robot-Factored WM 的关键边界是：允许把机器人自身可计算的运动渲染给模型，但不允许把接触后真实状态作为条件泄漏。", sections: [{ title: "动作实现外置", paragraphs: ["控制器把命令变成 nominal joint trajectory，URDF 再将它转成相机坐标下的可见几何。", "这样同一视频模型面对不同本体时仍看到统一的像素/深度接口，而不是语义不同的关节向量。"] }, { title: "场景响应内置", paragraphs: ["物体是否移动、接触是否发生与遮挡如何变化仍由生成模型预测。", "end-effector 与 scene depth 提供二维 mask 无法表达的前后关系，降低假接触。"] }], experimentReading: ["跨本体和人类演示应用说明接口具有组合性。", "没有闭环真实控制增益，因此更适合视作世界模型表示研究，而非已经验证的通用策略方案。"], reflections: [] },
    strengths: "清楚拆分 action realization 与 scene response，并用 depth 和跨本体实验验证各因素。",
    limitations: "依赖准确 URDF、控制器、相机标定与 nominal trajectory；现实接触偏差仍要由大模型吸收。",
    transfer: "跨本体世界模型可优先统一到 robot RGB/depth rendering，而不是强行对齐不同维度的 action vector。",
    figures: [{ src: "/report-assets/2026-07-27/2607.22535-fig1.png", alt: "Robot-Factored World Model 将机器人因素渲染成统一视觉接口", caption: "Figure 1 · robot factors、共享视觉接口与视频世界模型。图片来自 arXiv v1 HTML 原图。" }],
  },
  {
    rank: 5,
    title: "MEMENTO: Memory-Guided Memetic Code-as-Policy Evolution",
    arxivId: "2607.22832",
    url: "https://arxiv.org/abs/2607.22832",
    institutions: ["Örebro University"],
    signal: "先演化 rollout evaluator，再用带拒绝记忆的局部搜索、宏突变和交叉共同改写可执行机器人策略代码",
    tags: ["Code-as-Policy", "Memory", "Evolutionary Search"],
    classification: { research: "Memory", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪", "其他平台"], deployment: "Sim2Real" },
    detailAttributes: { memoryImplementation: "Rejected-proposal memory and elite search state", memoryHorizon: "Across policy-search generations" },
    resources: [{ label: "GitHub", url: "https://github.com/sygkounas/MEMENTO" }],
    motivation: "长时 code-as-policy 的失败反馈很稀疏；现有 LLM evolution 多在独立候选间选择，缺少围绕已接受策略的连续局部改进和失败提案记忆。",
    methodSummary: "MEMENTO 先演化一个把 rollout 映射为标量 fitness 与结构化反馈的 evaluator，并冻结它；随后以单一 elite 为核心，同时运行带拒绝记忆的 hill-climb、macro-mutation 和 crossover。",
    architecture: "策略是调用感知与控制 primitive 的可执行程序；evaluator 提供选择分数和反馈维度，搜索状态保存当前 elite、被拒提案及三个分支的候选。",
    optimization: "每代先做连续微小修改，再从 elite 做大跨度宏突变，并交叉两支最佳候选；各候选通过环境 rollout 评估，最优者成为下一代 elite。",
    data: "Robosuite Franka Tower-of-Hanoi 与 AI2-THOR household interaction 的在线 rollout；还评估 held-out 物体配置与未见室内场景。",
    experiments: "MEMENTO 在任务成功与 held-out 泛化上超过适配后的 Eureka、REvolve；零样本、未演化 evaluator 和删除搜索分支均退化，最终 Hanoi 策略迁移到真实 Franka。",
    novelty: "相对只做群体变异的 LLM evolution，它把 memetic local search、拒绝记忆和多分支重组放入同一执行反馈循环，并先优化 evaluator。",
    experimentDetails: [{ title: "两类长时环境与消融", setup: "Robosuite Tower-of-Hanoi 与部分可观测 AI2-THOR；训练场景搜索，held-out 几何/场景评估。", comparisons: "Eureka、REvolve、零样本生成、固定/未演化 evaluator，以及移除 hill-climb、macro-mutation 或 crossover 的变体。", results: ["完整 MEMENTO 在两个域的任务成功和 held-out 泛化上优于基线。", "零样本生成与未演化 evaluator 无法解决两个域。", "删除任一搜索分支都会降低表现，说明局部改进与大跨度探索互补。"], evidenceNote: "正文给出任务/消融趋势；不同域的 fitness 定义不同，绝对分数不宜横向比较。" }, { title: "物理 Franka 迁移", setup: "将仿真中演化的 Tower-of-Hanoi 程序部署到真实 Franka。", comparisons: "验证可执行程序与控制 primitive 的 sim-to-real 可行性。", results: ["最佳策略能在真实机械臂上执行长时 Hanoi 序列。", "该实验展示可行性，但不是大样本成功率或多扰动泛化统计。"], evidenceNote: "真机证据偏示范性，不能替代重复试验。" }],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["代码、prompts 和视频已公开；环境与比较方法在论文中说明。"], implementation: ["evaluator 先演化后冻结；policy search 包含 memory-guided hill climb、macro-mutation 与 crossover。"], missing: ["真实 Franka 的重复次数与误差统计不足；调用 LLM 的版本和成本会影响复现。"] },
    deepDive: { lead: "MEMENTO 把 evaluator 与 policy 分成两个搜索阶段，避免一边改评分标准、一边改策略导致目标漂移。", sections: [{ title: "固定 evaluator 后的三路搜索", paragraphs: ["hill-climb 只从当前接受候选做小改动，并把被拒方案留作负面记忆；macro-mutation 允许跳到更远的代码结构。", "crossover 把局部最优与大跨度候选重组，最终仍通过真实 rollout fitness 选择。"] }, { title: "记忆的作用", paragraphs: ["这里的 memory 不是机器人时序感知记忆，而是跨搜索代保存已尝试、已拒绝的程序编辑。", "结构化 feedback 决定下一轮改代码的方向，标量 fitness 只负责接受与 elite 选择。"] }], experimentReading: ["两类环境、held-out 泛化和分支消融支持搜索结构。", "真机只说明 sim-to-real 可行，尚不足以评价可靠性。"], reflections: [] },
    strengths: "基线、零样本、evaluator 和搜索分支消融完整，并公开代码与 prompts。",
    limitations: "强依赖环境 API、LLM 代码质量和 evaluator 设计；真机只做可行性展示。",
    transfer: "可把长时策略优化拆成固定 evaluator 与多尺度程序编辑，并保存 rejected edit，避免重复探索相同错误。",
    figures: [{ src: "/report-assets/2026-07-27/2607.22832-fig1.png", alt: "MEMENTO evaluator evolution 与三路 policy code search", caption: "Figure 1 · MEMENTO 的 evaluator 演化和 policy 搜索流程。图片来自 arXiv v1 HTML 原图。" }],
  },
];
