import type { Paper, PaperEquation } from "./site-data";

type Entry = Omit<
  Paper,
  "rank" | "figures" | "optimization" | "experimentDetails" | "reproducibilityDetails" | "deepDive"
> & {
  figureFile: string;
  figureAlt: string;
  figureCaption: string;
  technique: string[];
  evaluation: string[];
  comparison: string;
  reproducibilityStatus: "资源较完整" | "部分可复现" | "信息不足";
  implementation: string[];
  missing: string[];
  equations?: PaperEquation[];
};

const makePaper = (entry: Entry, index: number): Paper => ({
  ...entry,
  rank: index + 1,
  optimization: entry.technique.join("；"),
  experimentDetails: [{ title: "原文实验与消融", setup: entry.experiments, comparisons: entry.comparison, results: entry.evaluation }],
  reproducibilityDetails: {
    status: entry.reproducibilityStatus,
    verifiedResources: entry.resources?.map((resource) => `${resource.label}: ${resource.url}`) ?? ["arXiv 论文正文"],
    implementation: entry.implementation,
    missing: entry.missing,
  },
  deepDive: {
    lead: entry.methodSummary ?? entry.signal,
    sections: [{ title: "方法与模型改进", paragraphs: entry.technique }],
    equations: entry.equations,
    experimentReading: entry.evaluation,
    reflections: [entry.transfer],
  },
  figures: [{ src: `/report-assets/2026-08-21/${entry.figureFile}`, alt: entry.figureAlt, caption: entry.figureCaption }],
});

const entries: Entry[] = [
  {
    title: "HAF: Adapting Generalist VLAs to Humanoid Whole-Body Loco-manipulation via Hierarchical Action Flow and Spectral Latent RL",
    arxivId: "2608.16837",
    url: "https://arxiv.org/abs/2608.16837",
    institutions: ["Peking University", "Beijing Innovation Center of Humanoid Robotics", "Xi'an Jiaotong University", "Nankai University"],
    signal: "把人形全身 flow action 按运动依赖分阶段生成，再在冻结 VLA 的低频噪声 latent 上做真实机器人 RL。",
    tags: ["Humanoid", "Whole-body VLA", "Latent RL"],
    classification: { research: "VLA", training: "RL", platforms: ["Humanoid", "灵巧手"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://grange007.github.io/HAF" }],
    motivation: "通用 flow-VLA 直接一次生成腿、腰和双臂动作容易失配；在原始高维全身动作上做真实机器人 RL 又慢且不安全。",
    methodSummary: "HAF-VLA 依次生成 locomotion、torso 与 dual-arm action flow，并用 cross-stage KV 保留依赖；HAF-Steer 将反演噪声沿时间做 DCT 压缩，在冻结 VLA 上训练正则化 SAC。",
    architecture: "预训练 flow-matching VLA 外接三阶段 action expert；RL 分支只更新 spectral actor、双 critic、target critic 与温度参数，不回传大型主干。",
    data: "两种人形机器人、七项家庭 loco-manipulation 真机任务；BC 示范用于离线初始化，HAF-Steer 再混合 offline replay 与逐步增加的在线交互。",
    experiments: "七项长时任务每方法每任务 10 次，以里程碑归一化分数评估；另测视觉/位置扰动、Laundry Loading 架构消融和 RL 适配。",
    novelty: "HAF-VLA 七任务平均由最强 π0.5 的 53.3% 提至 70.5%；Laundry Loading 完整层级 66.7%，all-joint 53.3%、arm-first 50.0%、30-step π0.5 20.0%。",
    strengths: "在两台真机覆盖行走、弯腰、搬运、投掷和双臂操作；层级顺序、总去噪步数与 latent RL 均有对照。",
    limitations: "每任务 10 次，统计不确定性有限；spectral RL 仍需要真实在线探索，安全和数据成本尚未量化到跨平台尺度。",
    transfer: "高维 action chunk 可按物理依赖分阶段生成；RL 可优先搜索时间低频 latent，保留 BC 先验并抑制高频抖动。",
    technique: [
      "三阶段各做 10 次 flow denoising，动作维度从底盘/下肢逐步扩到腰与双臂；stage embedding 与 KV cache 传递前序运动条件。",
      "利用 flow 可逆性把示范动作反演到噪声轨迹，再用 DCT 只保留低频系数，显著缩小 SAC 的探索空间。",
      "训练从 demonstration-regularized offline SAC 开始，逐步降低离线采样比例并增加在线数据；VLA backbone 全程冻结。",
    ],
    evaluation: [
      "七任务 10-rollout 平均 70.5%，在需要先移动再精细操作的 Box Transfer、Ball Tossing、Laundry Loading 增益最明显。",
      "等总去噪步数消融说明收益来自有方向的 coarse-to-fine 顺序，不是计算量增加。",
      "论文还在视觉和目标位置扰动下测试 HAF-Steer，但样本量仍不足以支持广泛的 OOD 结论。",
    ],
    comparison: "π0.5、GR00T N1.7、Cosmos Policy、单阶段 VLA、all-joint/arm-first 层级，以及无 HAF-Steer 的离线策略。",
    reproducibilityStatus: "部分可复现",
    implementation: ["给出三阶段去噪步数、DCT latent、SAC 更新项、七任务判据与每项 10 次协议。"],
    missing: ["未确认完整训练代码、机器人数据与 checkpoint 公开；在线 RL 的实际交互时长未统一披露。"],
    figureFile: "2608.16837-fig1.png",
    figureAlt: "HAF-VLA 分层全身动作流和 HAF-Steer spectral latent RL 总览",
    figureCaption: "Figure 1 · 七项人形真机任务、分层 action flow 与 DCT latent RL。来源：arXiv 原图。",
  },
  {
    title: "Hydra-0: Action Flow for Generalist World Modeling and Control",
    arxivId: "2608.18077",
    url: "https://arxiv.org/abs/2608.18077",
    institutions: ["NVIDIA", "Brown University", "Columbia University", "Harvard University"],
    signal: "用像素空间 action flow 作为跨本体、跨视频 backbone 的统一 WAM 条件，并反向用于机器人控制。",
    tags: ["WAM", "Action Flow", "Cross-Embodiment"],
    classification: { research: "WAM", training: "Pre-training", data: "跨本体数据", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    motivation: "关节 action 与本体绑定，难以让同一个 world model 同时利用人类视频、多种机器人和不同控制空间。",
    methodSummary: "从几何/视频恢复 embodiment 与 object flow，以视觉坐标中的运动作为统一条件；forward mode 预测后果，inverse mode 从目标 object flow 推回 robot flow 和 action。",
    architecture: "在 Wan2.2、Cosmos 2.5 等视频模型上做 action-flow mid-training；部署端改造成因果 autoregressive rollout，并用 DMD2 蒸馏少步采样。",
    data: "多本体机器人交互与 video-only 片段混合；Wan2.2 A14B 配置用 32×H100 训练 40k steps，控制读出使用成败兼有的真实 rollout。",
    experiments: "评估机器人/物体运动误差、变形物体 zero-shot 组合、数据效率、RoboLab 五策略 replay 排序和真实机器人 inverse control。",
    novelty: "最佳配置相对 action-conditioned Cosmos 2.5 将 robot/object motion error 降 90.4%/60.2%；RoboLab replay 与参考成功率相关 r=0.96。",
    strengths: "同一接口横跨不同视频 backbone、本体、forward evaluation 和 inverse control；不仅展示视频，还检查运动误差与策略排序。",
    limitations: "大规模训练成本高；真机 inverse-control 主要是 proof-of-concept，未给出足够重复次数来说明成功率。",
    transfer: "跨本体 WAM 可把低层 action 先投影为相机坐标运动，让人类 object flow 与机器人 link flow 进入同一条件空间。",
    technique: [
      "有标定时用 link transform 传播机器人表面点并投影成 flow；video-only 数据则用跟踪估计 embodiment/object motion。",
      "未来视频仍是训练 target，action flow 只替换本体绑定的 action conditioning，因此可复用已有视频生成 backbone。",
      "inverse mode 把人类演示的 object flow 当任务意图，模型推断兼容 robot flow，再由 action head 解码执行动作。",
    ],
    evaluation: [
      "运动误差降幅在相同 Cosmos 2.5 backbone 下计算，隔离 conditioning interface 的贡献。",
      "五个 RoboLab policy 的 replay aggregate 与真实参考成功率 Pearson r=0.96，支持作为 open-loop evaluator 的潜力。",
      "真实控制能从人类 object flow 产生可执行动作，但论文没有提供与强 VLA 的大规模闭环成功率表。",
    ],
    comparison: "action-conditioned Cosmos 2.5、不同 action-flow 构造、Wan2.2/Cosmos backbone、few-step distillation 与 RoboLab reference。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文披露 backbone、40k steps、32×H100、因果转换与 DMD2 部署路径。"],
    missing: ["未确认完整模型权重与训练数据公开；inverse-control 真机评测的 trial-level 统计不足。"],
    figureFile: "2608.18077-fig1.png",
    figureAlt: "Hydra-0 action flow world model 的离线训练和在线部署",
    figureCaption: "Figure 1 · 多本体/video-derived action flow 训练，以及仿真生成 robot flow 后的因果现实 rollout。来源：arXiv 原图。",
  },
  {
    title: "MatchingPolicy: Correspondence-Aware Policy Enables Cross-Object In-Context Learning",
    arxivId: "2608.16715",
    url: "https://arxiv.org/abs/2608.16715",
    institutions: ["Hong Kong University of Science and Technology"],
    signal: "把 demo-to-scene 语义对应与动作适配拆开，让一条演示跨物体实例甚至跨类别执行。",
    tags: ["In-Context Learning", "Correspondence", "Diffusion Policy"],
    classification: { research: "表征学习", training: "BC", modalities: ["Point Cloud / 3D"], data: "合成 / 仿真数据", platforms: ["机械臂", "夹爪"], deployment: "Sim2Real" },
    resources: [{ label: "项目页", url: "https://matchingpolicy.github.io" }],
    motivation: "单模型同时从少量机器人数据找语义对应并适配动作，容易在新形状和新类别上两头失败。",
    methodSummary: "先用视觉基础模型做 view matching，再以 point matching 建立 dense correspondence；graph diffusion policy 直接条件化匹配点，输出 6D gripper poses。",
    architecture: "训练用仿真生成的 RGB-D/point-cloud 轨迹和 ground-truth template correspondence；部署只替换为 VFM+tracker 的在线对应模块，动作网络不再微调。",
    data: "程序化 RLBench reference demos 经物体姿态和场景重定向生成 synthetic correspondence dataset；真机每任务只给一条示范。",
    experiments: "36 项 RLBench、六项难任务 two-demo 比较，以及 AirBot Pro 四项真机任务；Layout-Easy/Hard/Shape 每任务每 setting 10 次。",
    novelty: "真机三种设置平均 77.5%/65.0%/72.5%，在 novel shape 仍明显高于 InstantPolicy，并展示 pot→teapot 的跨类别 lid placement。",
    strengths: "真机无需 fine-tuning，实验显式覆盖大位姿变化、新实例与跨类别；对应模块和 policy 都有消融。",
    limitations: "训练 1M steps、4×A6000 约七天；性能依赖 segment/matching 质量，遮挡或重复纹理下对应错误会直接传到动作。",
    transfer: "把 foundation-model correspondence 作为显式接口，比让 policy 隐式学齐所有视觉不变量更容易定位跨物体失败。",
    technique: [
      "view matching 先选与当前观测最相近的示范视图，point matching 再在 object mask 内建立跨场景稠密语义点。",
      "对应点形成图结构，diffusion policy 在几何关系上预测 gripper pose 序列；真实部署仍使用同一动作预测器。",
      "仿真模板空间提供可规模化 ground-truth correspondence，并通过丢点模拟部分可见性。",
    ],
    evaluation: [
      "四项真机×三设置×10 次，Layout-Hard 仍为 65.0%，Shape 为 72.5%。",
      "RLBench 还比较 NoFT/FT 和仅两条演示的 KAT、RDT-1B，完整方法在难任务平均最好。",
      "消融表明 naive feature matching 在困难布局大幅下降，两阶段匹配与 policy conditioning 缺一不可。",
    ],
    comparison: "InstantPolicy、KAT、RDT-1B、RLBench 多任务基线，以及 naive matching、不同对应/动作模块消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["AdamW 1e-5、1M steps、4×A6000、RTX4080 evaluation 和完整真机 trial protocol 已披露。"],
    missing: ["未确认 synthetic dataset、训练代码和 checkpoint 公开。"],
    figureFile: "2608.16715-fig1.png",
    figureAlt: "MatchingPolicy 两阶段对应提取和 correspondence-aware diffusion policy",
    figureCaption: "Figure 1 · 从 demo/test frames 建立对应点，再预测运动并执行。来源：arXiv 原图。",
  },
  {
    title: "GigaBrain-WBC-0.5: A Behavior World Model for Robust Whole-Body Control with Environment Interaction",
    arxivId: "2608.18234",
    url: "https://arxiv.org/abs/2608.18234",
    institutions: ["DeepLeap Research"],
    signal: "让人形 whole-body controller 同时预测动作、下一状态和下一行为命令分布，并用该分布拦截不可能指令。",
    tags: ["Humanoid", "Behavior World Model", "Whole-body Control"],
    classification: { research: "WM", training: "Pre-training", modalities: ["State / Proprioception"], platforms: ["Humanoid"], deployment: "Sim2Real" },
    motivation: "大规模 motion tracker 通常只在平地跟踪参考动作，面对地形、缺失支撑、不合理命令和摔倒时缺少环境条件下的可行性模型。",
    methodSummary: "自动从 retargeted motion 恢复 3D terrain/contact annotation；causal Transformer 联合预测 action、next state 与 latent command distribution。",
    architecture: "reference window 和 2,000+ 小时 motion data 编码后进入六层 causal Transformer；policy/state/behavior 三头共享表征，部署用 GMM likelihood 做命令投影。",
    data: "大规模人类 motion corpus 自动生成带地形交互的训练样本；主要在 Unitree G1 训练，并以简单 fine-tuning 迁移 Maker L01。",
    experiments: "地形交互、不合理命令、跌倒恢复和扰动四类仿真/硬件测试，对比三种大规模 tracker，并做 terrain annotation 与 projection 消融。",
    novelty: "地形交互 81.3%（强基线 4.3 倍）、不合理命令 83.1%、跌倒恢复 99.3%（16.8 倍）；硬件展示缺失支撑和跨人形迁移。",
    strengths: "不是给 tracker 继续堆动作，而是学习环境条件下的行为可行分布；地形、命令、恢复和本体迁移均覆盖。",
    limitations: "硬件结果以展示性 trial 为主，未像仿真表那样给出完整重复次数；行为命令分布的错误投影可能过度保守。",
    transfer: "低层控制器可增加 next-state/command-density 辅助头，在部署时把明显 OOD command 拉回已学行为流形。",
    technique: [
      "terrain annotation 从普通 retargeted clips 恢复脚/手接触几何，无需为每段 motion 人工搭建场景。",
      "共享 causal model 同时输出 torque/action、下一 proprioceptive state 和下一 latent command 的 GMM。",
      "若命令在预测分布下概率过低，则沿 Mahalanobis-radius 投影到可行区域，以 best-effort 行为替代直接拒绝。",
    ],
    evaluation: [
      "四个 regime 都与三种大规模 tracker 对照；地形和 fall recovery 的倍数增益来自相同成功判据。",
      "自动地形标注与命令 projection 均有独立消融，说明鲁棒性不只是训练 motion 规模。",
      "Unitree G1 checkpoint 经少量 fine-tuning 迁移 Maker L01，但跨本体定量范围仍有限。",
    ],
    comparison: "三种 large-scale motion tracker，移除 behavior head、terrain annotation、OOD projection 的消融，以及 G1→L01。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文给出 causal Transformer、三预测头、GMM projection 与自动地形标注流程。"],
    missing: ["未确认完整代码/checkpoint 和硬件 trial 统计公开。"],
    figureFile: "2608.18234-fig2.png",
    figureAlt: "GigaBrain-WBC 行为世界模型和不合理命令投影",
    figureCaption: "Figure 2 · motion/terrain encoding、动作/状态/行为三头，以及部署时 GMM 命令投影。来源：arXiv 原图。",
  },
  {
    title: "SparkVLA: Stop-Aware Hierarchical VLA with Adaptive Action Chunking for Long-Horizon Manipulation",
    arxivId: "2608.16172",
    url: "https://arxiv.org/abs/2608.16172",
    institutions: ["Beijing Institute of Technology", "Tsinghua University"],
    signal: "把“是否结束子任务”和“执行多长 action prefix”放进同一个排序器，避免长时层级 VLA 的接口冲突。",
    tags: ["Hierarchical VLA", "Subtask", "Adaptive Chunking"],
    classification: { research: "Subtask", training: "Post-training", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://icr-lab.github.io/SparkVLA" }],
    motivation: "独立 stop head 与 chunk selector 会互相矛盾：该不该停取决于拟执行动作，而最佳动作长度又取决于子任务边界。",
    methodSummary: "Stop 与所有 action-prefix 长度组成统一 ordinal ranking；history-aware subtask anchor 记录起始状态和已完成历史，并引导视觉 token pruning。",
    architecture: "高层 planner 生成 subtask 和 anchor，低层 VLA 生成 action chunk；只在 decision boundary 用 planner hidden feature 做 full-attention selector。",
    data: "RoboCerebra 1,000 条、100 task variants、平均 9.1 subtasks；主评测 60 held-out cases×10 rollouts，另有 LIBERO 与三项真机长任务。",
    experiments: "RoboCerebra 六条件 600 episodes、LIBERO 40 tasks，以及 Shelf Arrangement、Drawer Restocking、Tea Preparation 真机 rollout；逐项消融 stop/chunk/anchor。",
    novelty: "RoboCerebra 平均 47.12%，高官方 HPE 30.57 点、高可复现 Mem-0 26.83 点；unified Stop 使 Stop Acc. 80.37%→96.65%。",
    strengths: "接口问题定义清晰，跨 OpenVLA-OFT/SmolVLA executor 都提升；主表、stop 精度、chunk 和 memory 条件相互印证。",
    limitations: "真机部分没有和仿真同等完整的 trial-level 数字；依赖 subtask annotation 和高层 planner 的正确分解。",
    transfer: "层级策略里 stop 与 action horizon 应联合决策；subtask onset anchor 可以作为轻量短期记忆而不拼接全部历史帧。",
    technique: [
      "候选集合包含 Stop 与多个 action prefix，使用 ordinal preference 学一个统一分数，推理时直接取最高项。",
      "subtask 起始 hidden state 与 anchor history 自注意融合，保留已完成对象和当前目标；anchor-guided pruning 只留相关视觉 token。",
      "selector 放在 planner backbone 而非 action executor，因为前者持有任务进度和历史；只在 chunk boundary 计算。",
    ],
    evaluation: [
      "Dynamic Observation 和 Memory Expansion 分别提升 34.78/47.69 点，符合更频繁 re-observation 与历史 anchor 的设计目标。",
      "fixed horizon→RLPD→AQC→pairwise ranking 为 34.26%→40.92%→42.53%，再统一 Stop 达 47.12%。",
      "视觉路径从无 pruning 40.03% 到 spatial 43.46%、raw anchor 45.18%、history-aware 47.12%。",
    ],
    comparison: "OpenVLA-OFT、SmolVLA、π0.5、HPE、Mem-0、RLPD/AQC chunking，以及 stop/anchor/pruning/placement 消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["提供 Python/PyTorch/CUDA 环境、4×A100 selector run、训练包依赖和 600-episode protocol。"],
    missing: ["项目页代码/数据完整下载状态未确认；真实机器人试验次数披露不足。"],
    figureFile: "2608.16172-fig2.png",
    figureAlt: "SparkVLA 历史 anchor、视觉 pruning 与 Stop-prefix 统一排序",
    figureCaption: "Figure 2 · 高层 subtask anchor、视觉压缩和 Stop-aware action-prefix ranking。来源：arXiv 原图。",
  },
  {
    title: "UniReflex: Plug-and-Play Force Control for Pretrained Generative Policies via Fast-Slow Reflex",
    arxivId: "2608.17432",
    url: "https://arxiv.org/abs/2608.17432",
    institutions: ["Tsinghua University Shenzhen International Graduate School", "Nanyang Technological University", "X Square Robot", "Xspark AI"],
    signal: "冻结慢速生成策略，拦截其内部 latent，用一个快速 GRU 预测变刚度和参考力来补接触反射。",
    tags: ["Force Control", "Fast-Slow", "Generative Policy"],
    classification: { research: "VLA", training: "Post-training", modalities: ["Force / Torque"], platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://unireflex.github.io/" }],
    motivation: "Diffusion/flow policy 输出位置 action，频率较低且不显式适应接触力；联合重训 force head 成本高，也可能破坏预训练能力。",
    methodSummary: "从遥操作 effort 恢复 variable-stiffness label；在冻结 backbone 的中间表征上接入 fast GRU，输出各向异性刚度和 reference wrench，并由 gate 决定反射强度。",
    architecture: "slow policy 继续给 reference pose；fast loop 读取 proprioception、F/T 与 intercepted latent，通过 impedance controller 修正高频接触。",
    data: "三项双臂接触任务的遥操作数据，使用动作、F/T 与 effort 恢复监督；在多个 generative backbone 上验证 plug-and-play。",
    experiments: "真机任务比较位置控制、直接 force policy、joint fine-tuning 与 UniReflex；报告成功率、力误差、组件消融和训练吞吐。",
    novelty: "完整系统任务成功率约 70%–90%，移除关键组件常降到 20%–50%；F/T error 约 5.8–8.9，对照 28.3–38.7；反向训练快 25–66 倍。",
    strengths: "接触闭环、多个 backbone、真实 F/T 指标和成本消融齐全；只训练 0.188%–0.375% backbone 参数。",
    limitations: "依赖可用的 effort/F/T 与稳定底层阻抗控制；快速反射只补局部接触，不能修正慢策略的高层任务错误。",
    transfer: "可把 fast force loop 作为冻结 VLA 的外接后训练模块，用中层 latent 提供任务语义而不重训全栈。",
    technique: [
      "从示范的 pose、velocity、wrench 与 effort 反推出 normalized anisotropic stiffness 和 reference wrench 标签。",
      "fast GRU 拦截慢 policy 中层 latent，并和实时 F/T、proprioception 融合；adaptive gate 在自由空间减弱、接触时增强修正。",
      "推理把 reference pose 与 reflex wrench/stiffness 送入 variable impedance controller，保持慢规划与快控制解耦。",
    ],
    evaluation: [
      "三项双臂真机任务完整方法约 70%–90%；去掉 latent、gate 或变刚度后的下降表明不是单纯加 force sensor。",
      "force tracking error 从几十量级降到个位数，同时保持任务完成，而非只优化力曲线。",
      "单 A800 上只训练 fast GRU，backward latency 相对全栈 joint fine-tuning 低 25–66 倍。",
    ],
    comparison: "多个 diffusion/flow backbone、position-only、force-aware joint tuning，以及 latent interception、gate、stiffness 各组件消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["给出标签恢复、GRU 接口、impedance control、trainable ratio 和吞吐测量。"],
    missing: ["未确认代码/数据公开；硬件 F/T 与控制器参数跨平台重用仍需标定。"],
    figureFile: "2608.17432-fig1.png",
    figureAlt: "UniReflex 从慢生成策略拦截 latent 并驱动快速力反射",
    figureCaption: "Figure 1 · effort label recovery、fast-slow policy、变阻抗输出与接触 gate。来源：arXiv 原图。",
  },
  {
    title: "ADEPT: Pre-Training Dexterity for Sample Efficient RL and Sim-to-Real Transfer",
    arxivId: "2608.19182",
    url: "https://arxiv.org/abs/2608.19182",
    institutions: ["NVIDIA", "University of Michigan Robotics"],
    signal: "先用通用 reposing RL 学灵巧性，再用稳定的 teacher post-training 与视觉/触觉 student 蒸馏迁移到真机插入。",
    tags: ["Dexterous Manipulation", "RL", "Sim2Real"],
    classification: { research: "其他", training: "RL", modalities: ["Tactile"], platforms: ["机械臂", "灵巧手"], deployment: "Sim2Real" },
    resources: [{ label: "项目页", url: "https://adept-dexterity.github.io" }],
    motivation: "每个新灵巧任务从零做 RL 浪费通用抓取/重定向能力；直接 fine-tune 又会让旧 critic 的错误 advantage 快速破坏预训练策略。",
    methodSummary: "通用 object reposing PPO pretrain 后，以 BC distillation、critic warm-up、保守 PPO 顺序做下游 post-training；再 DAgger 蒸馏到感知 student。",
    architecture: "state teacher 控制 23/29-DoF C-space，Geometric Fabric 处理碰撞、关节限位和动力学平滑；student 输入双 RGB，Sharpa 另加五指 tactile maps。",
    data: "预训练随机 16 类 primitive shapes；下游 FMB star 与 square/round peg、dish rack。视觉/触觉 student 在仿真 rollout 上 DAgger，无真实示范。",
    experiments: "五种子 post-training 消融、1,024-episode 仿真评估，以及 Kuka-Allegro 与 Flexiv-Sharpa 零样本 sim-to-real，每项真机 10 次。",
    novelty: "真机 Kuka star/square-round/dish 为 5/10、3/10、6/10；Flexiv-Sharpa square-round 为 8/10；naive PPO 会把成功率迅速训练到零。",
    strengths: "两个高自由度本体、视觉与触觉、困难接触插入和完整 RL 稳定性消融；低层 Fabric 在 sim/real 共用。",
    limitations: "真实成功率仍有明显失败且每任务只有 10 次；系统依赖复杂仿真、Fabric 和大量并行 RL 资源。",
    transfer: "已有通用 dexterity teacher 时，应先重校准新 reward critic，再限制 actor 更新；安全低层控制接口要在 sim/real 统一。",
    technique: [
      "reposing pretrain 用 ADR、PBT 和 PPO覆盖 reach-grasp-lift-reorient-transport，物体 point cloud 促进 OOD shape 泛化。",
      "下游依次做 BC actor distillation、冻结 actor 的 critic warm-up、conservative PPO，避免新 reward 下旧 critic 给出错误梯度。",
      "全关节 Geometric Fabric 作为二阶系统处理限制；视觉/触觉 student 用 DAgger 模仿 state teacher 并零样本上真机。",
    ],
    equations: [{ name: "Geometric Fabric", expression: "M(q,q̇)q̈ + f(q,q̇) + fπ(a) = 0", explanation: "自主几何/阻尼项负责限制与平滑，策略只提供全关节 forcing target。" }],
    evaluation: [
      "五种子消融中 naive fine-tuning 很快遗忘 reposing；完整三步 recipe 才能稳定到最终 ADR。",
      "仿真 teacher 在 Kuka 两 peg 聚合 85.0%、Flexiv square/round 89.2%；感知 student 的 sim-to-real 差距仍明显。",
      "Flexiv 以五指触觉达到 8/10，是最强真机分项，但论文没有同平台 vision-only 的等规模真实对照。",
    ],
    comparison: "from-scratch/naive PPO、移除 BC distill/critic warm-up/conservative update、不同 ADR，以及两个本体的 teacher/student。",
    reproducibilityStatus: "部分可复现",
    implementation: ["附录给出 reward、observation、Fabric、学生结构、Jetson/工作站部署拓扑和真机任务判据。"],
    missing: ["未确认训练代码、仿真资产与 checkpoint 公开；真实试验规模较小。"],
    figureFile: "2608.19182-fig2.png",
    figureAlt: "ADEPT 从通用灵巧预训练到后训练蒸馏和真机部署",
    figureCaption: "Figure 2 · reposing pretrain、稳定下游 post-training、student distillation 与两种真机。来源：arXiv 原图。",
  },
  {
    title: "Dream2Reward: Learning Dense Robotic Reward from Successful Demonstrations",
    arxivId: "2608.18787",
    url: "https://arxiv.org/abs/2608.18787",
    institutions: ["Institute of Automation, Chinese Academy of Sciences", "University of Chinese Academy of Sciences", "JD Explore Academy"],
    signal: "只用成功示范在 latent transition space 学方向与幅值一致性，生成能区分失败阶段的稠密奖励。",
    tags: ["Reward Learning", "Latent Transition", "Offline RL"],
    classification: { research: "表征学习", training: "RL", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    motivation: "二元成功标签太稀疏，VLM reward 容易只看画面相似；采集失败并人工标注成本高。",
    methodSummary: "把成功示范的相邻 latent transition 对齐成语言条件的向量场，reward 同时衡量当前转移方向与预期方向夹角、以及进度幅值。",
    architecture: "视频/语言编码后形成成功轨迹 latent manifold；测试轨迹逐步计算 transition alignment，为 QGF offline RL 提供 dense reward。",
    data: "reward 评估含 400 条真机轨迹：200 条人类成功和 200 条 policy rollout（34 成功/166 失败）；RL 在四项真机任务上使用离线数据。",
    experiments: "reward classification 看 AUC/失败分离；离线 RL 比较 ROBOMETER、Robo-Dopamine、BC，四任务每方法每任务 50 次。",
    novelty: "完整 reward AUC 0.95，去掉语言为 0.80；Dream2Reward-QGF 四任务平均 34.5%，高 ROBOMETER 28.0、Robo-Dopamine 22.5、BC 17.0。",
    strengths: "真实失败数据只用于评测而非训练 reward；reward AUC、组件消融和 200 次/方法真机 policy evaluation 相互支持。",
    limitations: "只从成功 manifold 推断失败程度，示范未覆盖的合理策略可能被误罚；平均策略成功率仍不高。",
    transfer: "若没有高质量失败标注，可先学习成功 transition field，再用独立 policy rollout 检查 reward 是否区分阶段性失败。",
    technique: [
      "对成功轨迹 latent transition 做语言条件聚合，构造局部期望方向与进度幅值。",
      "reward 将方向余弦和长度一致性组合，避免只比较静态 frame embedding。",
      "QGF 用该 dense reward 训练 offline Q/policy，不需要给每条失败人工分级。",
    ],
    evaluation: [
      "400 条真实轨迹上 AUC 0.95；去掉语言条件或幅值/方向项都会降低失败分离。",
      "四任务各 50 次，完整方法成功率为 56%、34%、18%、30%，平均 34.5%。",
      "对照 reward 模型和 BC 的平均值分别为 28.0%、22.5%、17.0%，说明提升不是只来自 QGF 框架。",
    ],
    comparison: "ROBOMETER、Robo-Dopamine、BC、语言/方向/幅值消融，以及 400 条成功失败 reward audit。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文给出 reward 组成、400-trajectory audit、四任务与每项 50 次协议。"],
    missing: ["未确认代码、数据和权重公开；成功示范规模与跨任务复用范围有限。"],
    figureFile: "2608.18787-fig1.png",
    figureAlt: "Dream2Reward 从成功示范学习 latent transition reward",
    figureCaption: "Figure 1 · 成功 transition alignment、失败分离与真实机器人策略收益。来源：arXiv 原图。",
  },
  {
    title: "HiTac-WAM: Hierarchical Tactile Forecasting for Contact-Rich World Action Models",
    arxivId: "2608.19574",
    url: "https://arxiv.org/abs/2608.19574",
    institutions: ["Institute of Automation, Chinese Academy of Sciences", "ImprintX Robotics", "Beijing Academy of Artificial Intelligence"],
    signal: "按接触建立→三维形变→滑移风险的物理顺序预测触觉，再用 forecast 排动作并在线核验。",
    tags: ["Tactile WAM", "Contact-rich", "Action Ranking"],
    classification: { research: "WAM", training: "Post-training", modalities: ["Tactile"], platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "视觉上相似的动作在接触后可能产生完全不同的压力、形变和滑移，纯视频 WAM 难以提前区分。",
    methodSummary: "给每个 candidate action chunk 预测双侧接触、contact-conditioned 3D deformation 与 gated slip；按 forecast quality 排序，执行时以预测触觉为 reference 触发重规划。",
    architecture: "directed attention 允许 tactile query 读取 video/action context，但隔离 video/action query 对触觉历史的反向依赖；三层触觉 head 按物理条件串联。",
    data: "IMETA-Y1、双 DM-Tac W2、三相机；chip grasp、blackboard erase、USB insertion 三任务，30 Hz 触觉历史 4 帧、预测 24 步。",
    experiments: "主 real-robot comparison 共 360 次（每方法每任务 30），另评接触 F1、deformation error、slip AUPRC、K=4 排序和在线异常恢复。",
    novelty: "K=4 forecast ranking 61.1%，完整验证闭环 72.2%，DreamZero 31.1%；contact F1 0.921，deformation L2 降 17.6%，slip AUPRC 提升约 60.4%。",
    strengths: "触觉预测、动作选择与真实执行形成闭环；主表有固定试验数、置信区间和条件依赖消融。",
    limitations: "三项任务/一种触觉传感器，且 tactile module 按任务训练；K=4 sampling 增加推理成本。",
    transfer: "接触世界模型可先预测离散接触阶段，再条件化连续形变和滑移，避免所有 tactile target 平铺并行学习。",
    technique: [
      "tactile query 读取 video-action context；contact head 先输出 onset/release，deformation 只在 contact 条件下预测，slip 再由接触与形变 gating。",
      "对 K 个 action candidate 各生成触觉 forecast，以 contact/deformation/slip cost 排序；选中 forecast 被保留为运行时 reference。",
      "连续三次 anomaly score 超阈值触发 retreat 与 replanning，把预测误差直接转成执行保护。",
    ],
    evaluation: [
      "360 次主评测：DreamZero 31.1%，只做 forecast ranking 61.1%，加在线 verification 72.2%。",
      "层级预测同时改善 contact F1、3D deformation 和低基率 slip AUPRC，附 bootstrap CI。",
      "18 次触发 anomaly 的执行中有 12 次经撤退/重规划成功，说明 verification 有实际恢复贡献。",
    ],
    comparison: "DreamZero、task-progress ranking、tactile-forecast ranking、完整 verification，以及 contact/deformation/slip 条件消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["给出 30 Hz offset、24-step horizon、10k steps、8×H100、loss 权重、K=4 和 trigger 规则。"],
    missing: ["未确认代码、数据和 tactile calibration 工具公开。"],
    figureFile: "2608.19574-fig2.png",
    figureAlt: "HiTac-WAM 层级触觉预测、动作排序和在线验证架构",
    figureCaption: "Figure 2 · directed attention、contact→deformation→slip 预测及执行期验证。来源：arXiv 原图。",
  },
  {
    title: "DECOWAM: Decoupled Whole-Body World Action Model for Mobile Manipulation",
    arxivId: "2608.20114",
    url: "https://arxiv.org/abs/2608.20114",
    institutions: ["Tsinghua University", "Shanghai AI Laboratory", "Harbin Institute of Technology", "DEEP Robotics"],
    signal: "显式拆开移动底盘、机械臂和相机 ego-motion，用冻结 WAM 加小型 adapter 学移动操作。",
    tags: ["WAM", "Mobile Manipulation", "Whole-body"],
    classification: { research: "WAM", training: "Post-training", modalities: ["State / Proprioception"], platforms: ["轮式底盘", "机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "移动操作中相机随底盘运动，像素变化混合了 ego-motion、臂运动和物体变化，单一路径 WAM 难同时预测未来与控制。",
    methodSummary: "冻结 FastWAM 后分别增加 base/arm residual adapters、future-equivalent bottleneck 与分离 latent 的 adversarial objective，action 端显式预测 base velocity。",
    architecture: "world branch 生成八帧未来，action branch 输出 14-D whole-body action；仅训练 25.95M Stage-2 参数，而非更新 6.021B 全栈。",
    data: "ARMDOG 清洗后 1,487 episodes、343,550 frames、约 321 分钟；Stage-2 用 214 episodes/26 tasks，固定 Box-val 23 episodes 做 replay。",
    experiments: "离线 video/action diagnostics 与 FastWAM、Motus、X-WAM 比较；实体 quadruped-arm 每方法 79 次，逐阶段记录 approach/grasp/transport/place 和恢复。",
    novelty: "相对最强 FastWAM 初始化，frame/action MSE 降 15.03%/21.71%；真机完成 46/79（58.2%），FastWAM 57.0%、X-WAM 15.2%，且速度更快。",
    strengths: "数据清洗、匹配接口、训练参数和 79-trial stage breakdown 透明；不只报 end success，还定位移动和运输环节。",
    limitations: "最终成功率只略高 FastWAM 1.2 点；平台名为 quadruped-arm，现有 taxonomy 只能归入移动底盘+机械臂近似类。",
    transfer: "移动相机 WAM 应显式建模 ego-motion，并把 base 与 arm action 分路；小 adapter 可先验证是否真需全模型微调。",
    technique: [
      "14-D action 明确分 arm target、gripper、base velocity 和 padding；视觉分支用未来等价 bottleneck 抑制不相关像素。",
      "冻结主 WAM，只训练 base/arm residual adapters 与 action projection；adversarial loss 促使两个 latent 分离。",
      "数据审计先去重、时间戳插值、短丢帧修复并固定 split manifest，减少离线比较的数据泄漏。",
    ],
    evaluation: [
      "离线同时降低 frame 和 action error，避免只优化其中一支；25.95M trainable 参数约为全栈的很小比例。",
      "79 次真机中 46 次完成、平均 49 s；FastWAM 45 次左右但平均慢 16 s，X-WAM 慢 33 s且成功显著低。",
      "逐阶段结果显示主要收益在 approach、transport、whole-body coordination 与 base displacement robustness。",
    ],
    comparison: "FastWAM 多 checkpoint、Motus、X-WAM、action-only VLA，以及 base/arm adapter、bottleneck、latent separation 消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["数据审计日期/规模、固定 split、14-D action、adapter 参数量和 79-trial 协议均披露。"],
    missing: ["论文称计划发布 HDF5/split/datasheet，但当前公开状态需后续确认。"],
    figureFile: "2608.20114-fig1.png",
    figureAlt: "DECOWAM 冻结 WAM 上的分离 adapter、部署和适配流程",
    figureCaption: "Figure 1 · 冻结 FastWAM 的 base/arm 分路、未来 bottleneck 与实体部署。来源：arXiv 原图。",
  },
  {
    title: "What Matters for Latent Actions in Robot Learning",
    arxivId: "2608.19613",
    url: "https://arxiv.org/abs/2608.19613",
    institutions: ["Fudan University", "Tsinghua University", "Wuhan University", "Xiaomi EV", "Morphi Intelligence"],
    signal: "在统一框架里系统比较 41 种 latent-action 设计，并用 59M 视频帧和真机检验哪些选择真正帮助控制。",
    tags: ["Latent Action", "Video Pre-training", "Ablation Study"],
    classification: { research: "表征学习", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"] },
    motivation: "不同 LAM 工作在不同数据、action head 和 benchmark 上各自报告增益，难判断建模、正则和接入方式谁最重要。",
    methodSummary: "统一 autoencoding LAM，跨 modeling paradigm、objective/regularization、integration strategy 测 41 个选择；先用无 action 视频调 VLM，再用 robot action 后训练。",
    architecture: "700M spatiotemporal IDM/FDM 学 latent action；Stage II 调 Qwen3-VL-4B backbone；Stage III 接 OpenVLA-OFT/DAP 做真实 action learning。",
    data: "约 59M 帧，含 DROID、Language Table、BC-Z、FurnitureBench、Fractal、Bridge、FMB、Hydra、RoboTwin、LIBERO-Plus；真机四任务各 50 条。",
    experiments: "LIBERO、LIBERO-Plus、RoboTwin2.0 三基准、四个 proxy metric 与 Franka Panda 四任务；真机每任务 5 checkpoints×20 次=100 次/方法。",
    novelty: "LA-tuned 真机 317/400（79.25%），原 OpenVLA-OFT 259/400（64.75%）；10k steps 已达 85.0%，高 baseline 40k 的 76.25%。",
    strengths: "超大规模统一消融、三基准、三随机种子和 400 次/方法真机；还报告离散/连续 latent 并非在所有 benchmark 同方向。",
    limitations: "组合数量仍不等于完整因果搜索；训练需 8×H200，proxy metric 对最终控制的预测力有限。",
    transfer: "优先把 latent action 用于 VLM backbone 初始化，而非只接在 action head；正则强度通常比连续正则的具体形式更重要。",
    technique: [
      "Stage I 用无标注视频训练 IDM/FDM；Stage II 用 latent action 调 VLM；Stage III 在同一 robot action data 上比较原始与 LA-tuned 初始化。",
      "连续 latent 比较 AE/VAE/sparsity/SIGReg，离散用 VQ-VAE；同时扫描 8–1024 维和多种集成位置。",
      "真机只用 front RGB、无 joint/wrist view 与数据增强，保持两模型唯一差异为 VLM 是否经过 latent-action tuning。",
    ],
    evaluation: [
      "真机 400 个 rollout/方法，LA-tuned 总成功率高 14.5 个百分点，四类任务均提升。",
      "RoboTwin 的 14-DoF 双臂以 32-D latent 最佳 0.856，8-D 为 0.802；单臂 benchmark 对维度更不敏感。",
      "VQ-VAE 在 LIBERO-Plus OOD 最好 0.517，但在 LIBERO/RoboTwin 并不普遍领先，论文没有把离散化包装成通用答案。",
    ],
    comparison: "41 种 LAM 设计、四个 proxy metrics、OpenVLA-OFT 原始/LA-tuned，以及规模、维度、正则和集成策略消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["给出数据比例、700M/4B backbone、AdamW、8×H200、三阶段和 100-rollout/task 协议。"],
    missing: ["项目页代码/59M 数据清单与预训练 checkpoint 的实际下载状态未确认。"],
    figureFile: "2608.19613-fig1.png",
    figureAlt: "latent action 三阶段流程和 41 类设计维度",
    figureCaption: "Figure 1 · 无标注视频预训练、VLM latent-action tuning、下游 action learning 与设计空间。来源：arXiv 原图。",
  },
  {
    title: "PRISM: Precision and Contact-Rich Real-World Industrial Skill Dataset with Multimodal Sensing",
    arxivId: "2608.17962",
    url: "https://arxiv.org/abs/2608.17962",
    institutions: ["Peking University", "Delta Intelligence", "PKU-Wuhan Institute for Artificial Intelligence", "Hubei Humanoid Robot Innovation Center", "China Academy of Information and Communications Technology"],
    signal: "面向高精度接触操作，提供跨机器人、跨遥操作接口的 RGB-D、力矩、触觉与状态同步数据。",
    tags: ["Dataset", "Contact-rich", "Multimodal"],
    classification: { research: "其他", training: "Pre-training", modalities: ["Depth / RGB-D", "Force / Torque", "Tactile"], data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪", "灵巧手"] },
    resources: [{ label: "项目页", url: "https://tengbo-yu.github.io/PRISM/" }],
    motivation: "家庭 pick-place 数据很少覆盖紧公差、持续接触与力觉变化，难以评估工业插接/装配所需的多模态控制。",
    methodSummary: "以统一校准和时间同步采集多视角 RGB-D、6-axis F/T、proprioception，部分轨迹带触觉；同时保留三种遥操作接口和质量评分。",
    architecture: "这是数据资源而非新模型；用 LeRobot v3 格式训练 ACT、Diffusion Policy 与 π0，并采用全库预训练+任务子集 fine-tuning。",
    data: "5,000+ robot trajectories、等量 paired human demonstrations、45+ 小时、约 27M images、25+ tasks；Franka、Realman、LEJU，多种 gripper/visuotactile hand。",
    experiments: "电子元件插拔、游标卡尺包装、传送带分拣三任务，各 200 demos；比较 100/200 demos、是否全库预训练和三类 BC policy，每配置真机 20 次。",
    novelty: "相较只用任务数据，全库预训练在三策略/三任务上总体提高成功率；论文同时分析遥操作方式对平滑、精度和接触稳定性的影响。",
    strengths: "规模、传感、跨平台、同步/校准、故意扰动和质量控制较完整；与低质量场景系统论文不同，核心贡献是可复用数据与基准。",
    limitations: "工业任务分布仍可能偏向特定设备；触觉只覆盖子集，论文摘要和正文对 human-pair 统计口径需结合 datasheet 核对。",
    transfer: "接触数据集应保留高频 F/T/tactile 原流、校准与时间对齐元数据，并记录操作者修正而不是只留成功末状态。",
    technique: [
      "三套遥操作平台覆盖 exoskeleton、tracker、VR；8 名操作者在采集后继续过滤、标注和评分。",
      "多视角与力/状态严格同步，视觉训练下采样到 15 Hz、chunk size=15；原始接触信号保留更高采样率。",
      "policy protocol 先用全 5,000 demos 预训练 10% steps，再用目标任务 fine-tune 90%，与 task-only 训练匹配总步数。",
    ],
    evaluation: [
      "三任务每配置 20 次真实评测，100/200 demos 与有/无 pretraining 形成数据规模和迁移的控制对照。",
      "ACT、DP、π0 均使用官方 LeRobot 配置，减少为某一模型特调带来的偏差。",
      "传送带任务提供动态操作，但当前 benchmark 仍只有三个代表任务，不能代表全部 25+ 数据分布。",
    ],
    comparison: "Open X-Embodiment、RH20T、REASSEMBLE 等数据集，以及 ACT/DP/π0 的 100/200 demos 和 pretrain/no-pretrain。",
    reproducibilityStatus: "资源较完整",
    implementation: ["项目页给出数据入口；正文披露平台、传感器、同步、LeRobot v3、训练步数和真机协议。"],
    missing: ["完整 datasheet、所有 tactile 子集比例和许可条款需以正式下载包为准。"],
    figureFile: "2608.17962-fig1.png",
    figureAlt: "PRISM 多机器人多模态接触数据集总览",
    figureCaption: "Figure 1 · 5,000+ 机器人轨迹、多视角/多模态传感和 25+ 接触任务。来源：arXiv 原图。",
  },
  {
    title: "Prism-GRPO: Faster VLA Policy Optimization via Splitting Same-Outcome Groups",
    arxivId: "2608.17423",
    url: "https://arxiv.org/abs/2608.17423",
    institutions: ["Purdue University", "AWS AI"],
    signal: "把全成功/全失败的 GRPO group 按执行质量再切分，恢复原本为零的 advantage 并减少机器人 rollout。",
    tags: ["VLA", "GRPO", "RL"],
    classification: { research: "VLA", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    motivation: "二元任务 reward 下，同组样本若全部成功或失败，GRPO 标准化后 advantage 全为零，昂贵 rollout 被直接浪费。",
    methodSummary: "用接触冲击、非目标物体位移或动作平滑度等 execution quality 将 same-outcome group 切成 reward spectrum，再做组内相对优化。",
    architecture: "VLA policy 与 GRPO trainer 不变，只在 group reward construction 和 dynamic filtering 中加入 quality split；理论分析给出梯度对齐条件。",
    data: "四项 RoboTwin 操作任务，含随机摆放、杂乱、光照和背景；真实 Piper 任务用于 shove-cheat 与 clean placement 验证。",
    experiments: "比较 Binary GRPO、RL-ZVP 与不同 quality source；测成功率、达到峰值所需 rollouts、碰撞/平滑度和 group size，另做真实机器人行为对照。",
    novelty: "在四任务达到相当或更高峰值的同时最多减少 56% rollout；same-outcome group 不再全部丢弃，并减少 shove-cheat。",
    strengths: "直接针对二元 reward 的样本浪费，包含理论、四任务、多质量定义和真实行为案例；训练成本报告到 8×H100、12–16 小时。",
    limitations: "质量指标需要任务相关设计，错误 proxy 可能奖励表面平滑而非真实能力；真机证据规模小于仿真。",
    transfer: "二元成功率 RL 可保留 outcome 作为主目标，只在同 outcome 内用物理安全/平滑质量打破平局。",
    technique: [
      "Binary GRPO 的同 reward 组 advantage=0；Prism 仅在此类组内用 quality threshold 重新分层，不改变成功/失败的全局顺序。",
      "quality 可来自峰值非目标接触冲量、场景位移或动作 smoothness；dynamic filter 丢弃仍无信息的 group。",
      "质量权重 λ=0.2 为主设置，并测试阈值、group size 与 quality term placement 的敏感性。",
    ],
    equations: [{ name: "组内相对优势", expression: "Aᵢ = (rᵢ - mean(r_group)) / (std(r_group) + ε)", explanation: "同 outcome 组若 reward 完全相同则 Aᵢ=0；质量切分为组内恢复非零相对信号。" }],
    evaluation: [
      "四任务主曲线比较达到 Binary GRPO 峰值所需 rollout；最大节省约 56%。",
      "碰撞/位移与 smoothness 两类 quality 都能工作，但最佳 threshold 随任务变化。",
      "Piper 真机展示完整方法的 clean placement 与 RL-ZVP shove-cheat，对安全 proxy 有直观支撑但缺少大样本成功率。",
    ],
    comparison: "Binary GRPO、RL-ZVP、不同 quality source/threshold/λ/group size，以及 quality term 放置消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["主设置 λ=0.2、8×H100、512 rollouts/update、12–16h/run 与阈值标定方法已披露。"],
    missing: ["未确认训练代码和完整 robot assets 公开；真机量化 trial 数不足。"],
    figureFile: "2608.17423-fig1.png",
    figureAlt: "Prism-GRPO 将全成功和全失败 group 按执行质量切分",
    figureCaption: "Figure 1 · 标准 Binary GRPO 的零 advantage 与 Prism quality split。来源：arXiv 原始矢量图。",
  },
  {
    title: "RoboEdit: Scaling Robot Learning via Human-to-Robot Video Editing",
    arxivId: "2608.18948",
    url: "https://arxiv.org/abs/2608.18948",
    institutions: ["University of California, Los Angeles", "Massachusetts Institute of Technology", "University of Utah"],
    signal: "把人类操作视频自动编辑为带 3D 手状态的机器人视频，构造跨七种本体的 14M-frame 成对监督。",
    tags: ["Human Video", "Video Editing", "Cross-Embodiment"],
    classification: { research: "表征学习", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "灵巧手", "夹爪"], deployment: "跨本体迁移" },
    motivation: "人类视频规模大但没有机器人外观和 action；直接 retarget 轨迹会留下遮挡、穿透和相机运动不一致。",
    methodSummary: "RoboEdit-ADC 重建 3D hand-object-camera、跨本体 retarget 并做物理修正/修补；RoboEdit-Trans 通过 cross-embodiment adapters 编辑视频并解码逐帧 robot hand state。",
    architecture: "Wan2.1-VACE-1.3B 编辑 backbone 先 task adaptation 后冻结，训练 LoRA/residual adapters；3D state decoder 从生成 latent 恢复结构化动作。",
    data: "RoboEdit-14M 含 174,547 对视频、14.1M paired frames，源自 24,197 人类 clips，覆盖七种机器人本体和多场景。",
    experiments: "视频编辑质量/消融、3D state reconstruction、512 个 Genesis 随机环境轨迹复现，以及 Franka Panda YCB 真实执行展示。",
    novelty: "decoded trajectory controller 在 512 个仿真环境中 Panda/XHand 复现成功率 71%/62%；真实 Franka 证明轨迹可执行，但未给定量成功率。",
    strengths: "数据规模、跨本体、视频与 3D state 双监督较强；编辑模块、物理修正和 downstream controller 都有验证。",
    limitations: "真机只有展示性证据；生成视频伪影和 state decoder 误差可能被 policy 学到，数据许可与开放状态需核验。",
    transfer: "human-to-robot 数据生成不应只替换外观，还要保留相机/物体动力学并输出可监督的 3D state。",
    technique: [
      "ADC 从单目 RGB 恢复 hand-object interaction 与 camera motion，retarget 到目标本体后用深度约束和 physics refinement 减少穿透/漂浮。",
      "Trans 用稀疏 robot keyframes 条件化视频编辑，cross-embodiment adapters 处理外观与运动差异。",
      "3D decoder 直接从编辑 latent 输出 hand state，后续 residual PPO controller 跟踪该轨迹。",
    ],
    evaluation: [
      "174,547 对/14.1M frames 的统计按来源与本体拆分，规模不是由单一视频重复扩增。",
      "512 randomized environments 上 Panda 71%、XHand 62%，表明 decoder 输出可驱动控制，但仍有显著失败。",
      "Franka 真机仅展示 YCB manipulation，缺少重复次数，因此不能把“成功演示”读成稳定部署率。",
    ],
    comparison: "NovaEdit/其他 human-to-robot editing、无物理修正/adapter/state decoder 消融，以及 Panda/XHand trajectory replay。",
    reproducibilityStatus: "信息不足",
    implementation: ["披露 Wan2.1-VACE-1.3B、81-frame clips、keyframe indices、8×H100 workstation 与数据统计。"],
    missing: ["未确认 14M 数据、编辑代码、decoder/controller 权重公开；真机无定量 trial。"],
    figureFile: "2608.18948-fig1.png",
    figureAlt: "RoboEdit 人类视频到机器人视频和 3D state 的处理流程",
    figureCaption: "Figure 1 · human-video masks、跨本体 adapter、视频编辑与 3D robot-state decoder。来源：arXiv 原图。",
  },
];

export const paperDaily20260821: Paper[] = entries.map(makePaper);
