import type { Paper } from "./site-data";

type Entry = Omit<Paper, "rank" | "figures" | "optimization" | "experimentDetails" | "reproducibilityDetails" | "deepDive"> & {
  figureFile: string; figureAlt: string; figureCaption: string; technique: string[]; evaluation: string[];
  comparison: string; reproducibilityStatus: "资源较完整" | "部分可复现" | "信息不足"; implementation: string[]; missing: string[];
};

const makePaper = (entry: Entry, index: number): Paper => ({
  ...entry,
  rank: index + 1,
  optimization: entry.technique.join("；"),
  experimentDetails: [{ title: "原文实验与消融", setup: entry.experiments, comparisons: entry.comparison, results: entry.evaluation }],
  reproducibilityDetails: {
    status: entry.reproducibilityStatus,
    verifiedResources: entry.resources?.map((x) => `${x.label}: ${x.url}`) ?? ["arXiv 论文正文"],
    implementation: entry.implementation,
    missing: entry.missing,
  },
  deepDive: {
    lead: entry.methodSummary ?? entry.signal,
    sections: [{ title: "技术细节", paragraphs: entry.technique }],
    experimentReading: entry.evaluation,
    reflections: [entry.transfer],
  },
  figures: [{ src: `/report-assets/2026-09-18/${entry.figureFile}`, alt: entry.figureAlt, caption: entry.figureCaption }],
});

const entries: Entry[] = [
  {
    title: "WLA³: World Latent Action Modeling for Semantics, Dynamics, and Kinematics", arxivId: "2609.15870", url: "https://arxiv.org/abs/2609.15870",
    institutions: ["Joy Future Academy", "JD Group"], signal: "用同一套世界转移表征连接语义监督、未来动力学和本体动作，把人类视频与异构机器人轨迹放入统一策略训练链路。",
    tags: ["Latent Action", "World Model", "Cross-embodiment"], classification: { research: "WAM", training: "Pre-training", data: "跨本体数据", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://wla-3.github.io/" }],
    motivation: "异构数据缺少统一且低噪的动作标签，单视角 latent action 又容易把遮挡与外观变化误当成物理动作。", methodSummary: "WLAM 从多视角和可用本体状态中学习 32 维局部 latent action 与 1024 维转移特征，分别服务世界模型、VLM 语义监督和机器人动作生成。",
    architecture: "WLAM 负责转移编码；LAC-WM 学动作条件未来特征；SLA 对 30 步片段做语义监督；LARA expert 联合预测 latent action 和本体原生动作。", data: "总语料 84.1K 小时，混合真实机器人、仿真、UMI 与人类第一视角视频；中训练规模从 5K 扩至 20K 小时。",
    experiments: "六项真实机器人任务，另在 LARYBench 测 latent action 表征，并进行数据规模、跨本体、人类视频与模块消融。", novelty: "六项真机平均成功率 81.9%，高于 π0.5 的 66.2%；中训练数据从 5K 增至 20K 小时时由 57.6% 升至 81.9%。",
    strengths: "同一转移表征在语义、动力学与控制三处复用，数据规模曲线和真实闭环共同验证。", limitations: "训练语料与算力规模较大，部分内部数据不可复核；跨本体收益仍依赖机器人动作数据完成落地。", transfer: "异构数据不必先映射到同一原生动作空间，可先用世界状态变化建立共享接口，再保留本体专属控制头。",
    technique: ["跨模态 dropout 要求缺失部分视角或状态时仍能重建端点，重叠窗口余弦约束使局部 latent 方向一致。", "SLA 直接监督 VLM 的片段级物理语义，LARA 则以条件流匹配联合生成 latent 与原生动作。"],
    evaluation: ["最终 32 维 latent action 在 LARYBench 的平均分类准确率为 67.89%。", "论文同时报告真实场景空间、光照和背景变化，但结果仍来自同一团队的数据与硬件栈。"], comparison: "π0.5、既有 latent-action 表征，以及 SLA、LAC-WM、LARA、数据规模和人类视频消融。",
    reproducibilityStatus: "部分可复现", implementation: ["披露 32D/1024D 表征、损失、训练阶段、84.1K 小时数据构成和六项真机协议。"], missing: ["完整内部数据、训练权重和总训练算力未确认公开。"],
    figureFile: "2609.15870-fig1.png", figureAlt: "WLA3 世界转移表征统一语义动力学和控制", figureCaption: "Figure 1 · WLAM 的局部 latent action 与片段转移特征分别进入世界模型、VLM 和动作专家。来源：arXiv 原图。",
  },
  {
    title: "PredTac: Learning Contact-Rich Manipulation with Predicted Touch", arxivId: "2609.15198", url: "https://arxiv.org/abs/2609.15198",
    institutions: ["The Hong Kong University of Science and Technology (Guangzhou)"], signal: "先用真实触觉训练预测器，再让策略只依赖视觉、状态与预测触觉执行，减少部署时触觉硬件负担。",
    tags: ["Predicted Touch", "Contact-rich", "ACT"], classification: { research: "表征学习", training: "BC", modalities: ["Tactile", "State / Proprioception"], platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "真实触觉能缓解接触歧义，但传感器的校准、同步、耐用性和维护成本会阻碍策略部署。", methodSummary: "触觉预测器从因果腕部 RGB 与机器人状态历史恢复空间接触图；冻结后为 ACT 策略提供显式触觉接口，推理时不读取实体触觉。",
    architecture: "两阶段结构：视觉—状态触觉预测器先监督学习，随后冻结；下游 ACT 同时读取当前 RGB、状态和预测触觉。", data: "USB 插入、倒钩抽取和阀门旋转三项接触任务，包含仿真目标偏移与真实机器人轨迹。",
    experiments: "仿真与真机均比较 visual-only、measured-touch 和 predicted-touch；另固定策略重排触觉空间结构以检验因果内容。", novelty: "真机三任务 predicted-touch ACT 为 70.0%、50.0%、90.0%，均值 70.0%，接近 measured-touch 的 72.2%，远高于 visual ACT 的 21.1%。",
    strengths: "真实三任务、实体触觉上界和固定分布重排干预共同说明收益来自接触空间结构。", limitations: "预测器训练阶段仍需要触觉硬件，且研究只覆盖三种固定接触任务；跨传感器和长期漂移尚未验证。", transfer: "可把难部署模态转化为训练期教师和运行期显式中间表征，而不是永久绑定传感器。",
    technique: ["触觉预测以历史视觉和机器人状态为输入，避免使用未来帧造成泄漏。", "空间重排保持数值分布不变却使 Valve 成功率下降 10.7 个百分点，证明策略使用了接触位置而非仅用强度统计。"],
    evaluation: ["仿真三任务较视觉基线提升 8.0–13.7 个百分点。", "真机均值与 measured-touch 仅差 2.2 个百分点，但硬件、任务和训练分布仍较窄。"], comparison: "visual ACT、measured-touch ACT、predicted-touch ACT，以及触觉空间内容干预。",
    reproducibilityStatus: "部分可复现", implementation: ["论文披露两阶段训练、三任务成功率和固定策略干预。"], missing: ["完整数据、传感器长期漂移和跨平台复现实验未公开。"],
    figureFile: "2609.15198-fig1.png", figureAlt: "PredTac 触觉预测和无触觉部署流程", figureCaption: "Figure 1 · 实测触觉只用于训练预测器，冻结预测器随后为策略训练与执行提供预测接触图。来源：arXiv 原图。",
  },
  {
    title: "Real-World Reinforcement Learning with MPC Scaffolding for Dexterous Manipulation", arxivId: "2609.14878", url: "https://arxiv.org/abs/2609.14878",
    institutions: ["Honda Research Institute USA", "Georgia Institute of Technology"], signal: "用少量真机 MPC 轨迹初始化 actor、critic 与 replay，并在在线阶段逐步把控制权交给 SAC。",
    tags: ["Real-world RL", "MPC", "Dexterous Hand"], classification: { research: "其他", training: "RL", platforms: ["灵巧手"] },
    resources: [{ label: "项目页", url: "https://real-world-rl-with-mpc.github.io/" }],
    motivation: "灵巧手真机 RL 的早期探索低效且容易掉落物体，纯模型控制又受动力学误差限制。", methodSummary: "20 条 MPC 真机轨迹同时预训练 actor 与 Soft-SARSA critic；在线 SAC 混合离线和新交互数据，并按日程间歇调用 MPC 引导。",
    architecture: "16-DoF Allegro Hand；采样式 MPC 提供任务导向先验，off-policy SAC 在混合 replay 中训练，MPC 调用随学习进展减少。", data: "初始化使用 12 分钟采集的 20 条 MPC 轨迹，随后进行 7–20 分钟真机在线学习。",
    experiments: "连续掌内旋转、不同物体几何和目标姿态重定向；含预训练、保留 MPC replay 与在线 MPC 引导的独立消融。", novelty: "7 分钟在线 RL 后策略独立评测 5/5 成功；20 分钟后速度超过 MPC 五倍，并连续 1000 圈、110 分钟无掉落。",
    strengths: "报告训练时间、掉落次数、长期连续运行和三个脚手架组件消融，证据链完整。", limitations: "早期 100% 仅来自 5 次策略评测；任务集中在单手旋转，MPC 模型和奖励仍需工程先验。", transfer: "真机 RL 可让模型控制承担早期安全探索与 critic 初始化，再逐步退出而不成为永久控制器。",
    technique: ["MPC 轨迹以行为克隆初始化 actor、以 Soft-SARSA 初始化 critic，降低冷启动价值误差。", "在线阶段把 MPC 与策略轨迹放入同一 replay，调度器逐步减少 MPC 控制比例。"],
    evaluation: ["训练平均约发生三次掉落，明显限制了物理探索成本。", "长期 1000 圈稳定性很强，但尚不能外推到多对象、多阶段灵巧任务。"], comparison: "纯 MPC、无 MPC 预训练、无旧 MPC replay、无在线 MPC 引导等消融。",
    reproducibilityStatus: "部分可复现", implementation: ["公开阶段划分、MPC/SAC 交接、真实交互时间和长期稳定性结果。"], missing: ["硬件控制栈、完整奖励权重与代码公开状态不明确。"],
    figureFile: "2609.14878-fig1.png", figureAlt: "MPC 脚手架辅助真机灵巧手强化学习", figureCaption: "Figure 1 · MPC 数据、actor–critic 预训练与混合 replay 在线 SAC 的三阶段流程。来源：arXiv 原图。",
  },
  {
    title: "Touch2Trace: Tactile-Driven Imitation Learning for Dexterous Cable Tracing", arxivId: "2609.15921", url: "https://arxiv.org/abs/2609.15921",
    institutions: ["Dexterous AI Group, Analog Devices, Inc."], signal: "以高密度压阻触觉和短时本体历史直接学习无视觉电缆追踪，并系统拆解预训练、频率、时间窗与分辨率。",
    tags: ["Tactile", "Cable Tracing", "Imitation Learning"], classification: { research: "表征学习", training: "BC", modalities: ["Tactile", "State / Proprioception"], platforms: ["灵巧手"] },
    motivation: "柔性电缆追踪需要连续调节压力、摩擦和滑移，显式估计线缆状态或视觉观察容易受遮挡。", methodSummary: "冻结的 ViT-MAE 把双指 32×32 压力图编码为触觉 token，三层 causal Transformer 读取 15 帧触觉与 8-DoF 本体状态，以 GMM 头输出关节目标。",
    architecture: "Tesollo DG-5F 手与 TacV5 指尖阵列，60 Hz 控制；ViT-MAE 为 8 层、128 维、8 头，策略 Transformer 为 3 层、256 维、4 头。", data: "16 条真机示范约 14 分钟，训练用 12 条约 10.1 分钟；触觉编码器预训练约 2M 仿真抓取帧和 30K 真机帧。",
    experiments: "训练仅用 USB-0 环形路线；在四种线缆和直线/环形路线零样本评测。每条件 3 seeds×10 rollouts，共 30 次。", novelty: "相对仅本体输入，平均追踪距离由 0.2 cm 升至 20.1 cm，SR@10 由 0% 升至 93%。",
    strengths: "同一真机平台系统控制四个变量，且机械编码器独立测量真实距离。", limitations: "只测电缆追踪，传感器仅测法向压力；论文也指出最优频率和窗口可能随硬件任务变化。", transfer: "在少量任务数据下冻结大规模自监督触觉编码器，比联合微调更能保留可迁移接触结构。",
    technique: ["预训练时随机遮蔽 60–80% 触觉 patch，任务训练阶段冻结 encoder，避免十分钟级数据覆盖通用表征。", "15 帧窗口在 60 Hz 对应约 250 ms；降至 30/15 Hz 时性能显著下降，说明快速闭环与时间上下文共同重要。"],
    evaluation: ["未见 Ethernet 直线条件下，完整模型每条件 30 次；不同材质和路由均有独立统计。", "冻结 encoder 为 20.1 cm；微调为 4.7 cm，随机初始化为 0.2 cm，消融直接支持冻结策略。"], comparison: "proprioception-only、手工压力特征、随机/微调/冻结编码器、控制频率、窗口和分辨率消融。",
    reproducibilityStatus: "部分可复现", implementation: ["传感器、网络层数、数据时长、60 Hz 控制与 30 次/条件协议披露完整。"], missing: ["完整示范数据、传感器制造文件与训练代码未确认公开。"],
    figureFile: "2609.15921-fig1.png", figureAlt: "Touch2Trace 触觉编码和电缆追踪策略", figureCaption: "Figure 1 · 触觉预训练、60 Hz 时序策略和未见线缆零样本评测。来源：arXiv 原图。",
  },
  {
    title: "Modality-Autoregressive World-Action Models", arxivId: "2609.17524", url: "https://arxiv.org/abs/2609.17524",
    institutions: ["Carnegie Mellon University"], signal: "让未来点轨迹、DINO 特征和深度按顺序自回归去噪，最后再生成动作，避免只预测 RGB 带来的冗余。",
    tags: ["World-Action Model", "Multimodal Prediction", "Bimanual"], classification: { research: "WAM", training: "Pre-training", modalities: ["Depth / RGB-D", "Point Cloud / 3D"], platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://adamhung60.github.io/ModAR/" }],
    motivation: "WAM 常把未来 RGB 当唯一预测目标，但几何、语义与运动可由更紧凑模态表达，不同模态组合方式尚未系统比较。", methodSummary: "共享 DiT 通过模态专属 expert 和 head 顺序生成未来点轨迹、DINO 特征、深度等表征，后续模态条件化于先前预测，动作最后生成。",
    architecture: "跨模态 Transformer block 与模态专属 expert 交替；机器人配置和任务 embedding 通过 adaLN 调制各层。", data: "从零训练并改变机器人、人类视频和预测模态混合；另在同一数据上微调视频预训练 Flex-π。",
    experiments: "多数据尺度的系统模态消融，加三项真实双臂任务；比较并行/联合 WAM、顺序 ModAR 与 Flex-π。", novelty: "ModAR 平均成功率 75%，略高于 Flex-π 的 72%，训练 FLOPs 约少 20 倍且不依赖视频预训练。",
    strengths: "把预测模态和数据混合放在统一训练设置下比较，真实双臂实验验证不是纯仿真结论。", limitations: "摘要未给出每项真实任务的试验次数；RGB 结论来自所选任务和表示，不能解释为未来视频普遍无用。", transfer: "世界模型监督可优先选择任务所需的几何、语义和运动表征，而非默认重建完整像素。",
    technique: ["每种未来模态有独立输出头，顺序去噪使深度、特征、点轨迹和动作可利用前序预测。", "从零训练避免视频预训练混杂，Flex-π 在相同数据上的微调提供算力—性能参照。"],
    evaluation: ["点轨迹、DINO 与深度带来稳定收益，额外 RGB 没有一致改善。", "真实三任务显示人类视频会继续提高表现，但原文未把所有条件 trial 数写入摘要。"], comparison: "不同预测模态、数据来源、WAM 组合方式、Flex-π 与训练规模消融。",
    reproducibilityStatus: "部分可复现", implementation: ["项目页、架构图、模态组合和训练 FLOPs 对照可核验。"], missing: ["完整训练数据、权重及逐真机条件 trial 数未确认公开。"],
    figureFile: "2609.17524-fig2.svg", figureAlt: "ModAR 多模态自回归世界动作模型", figureCaption: "Figure 2 · 共享 DiT 顺序去噪未来模态并在最后预测机器人动作。来源：arXiv 原图。",
  },
  {
    title: "XPACE: Joint World and Action Modeling from Heterogeneous Experience", arxivId: "2609.17372", url: "https://arxiv.org/abs/2609.17372",
    institutions: ["XPENG Robotics"], signal: "让同一视频骨干兼作 world-action policy 与可控世界模拟器，再由模拟器生成偏离—恢复轨迹反哺策略。",
    tags: ["World Simulator", "Humanoid", "Recovery Data"], classification: { research: "WAM", training: "Pre-training", data: "跨本体数据", platforms: ["Humanoid"], deployment: "跨本体迁移" },
    motivation: "人类视频覆盖广但缺机器人动作，遥操作可执行却昂贵；单纯联合训练也不能自动产生失败恢复监督。", methodSummary: "不对称 MoT 共享 causal video Transformer 与 action Transformer；粗到细课程逐步强调机器人控制，模拟分支经 self-gradient forcing 后合成恢复轨迹。",
    architecture: "视频—动作模式联合输出未来视频与 action chunk；模拟模式用骨架控制和相机位姿生成未来；多层 video-to-action 连接共享动力学表征。", data: "四层数据金字塔：in-the-wild 第一视角、人类带动作视频、任务/外观对齐 bridge data 与 IRON 遥操作，另有失败恢复数据仅供模拟器。",
    experiments: "XPENG IRON-R01-1.11 人形机器人；每任务每方法 20 次匹配复位，覆盖策略性能、人到机器人迁移、数据消融、泛化与自改进。", novelty: "人类异构数据使未在机器人遥操作中出现的技能可迁移；模拟器合成恢复数据进一步提高真实任务完成率。",
    strengths: "同一模型闭合异构学习、可控模拟和恢复数据回流，真实人形试验每条件 20 次。", limitations: "关键训练数据和 IRON 硬件是内部资源；合成恢复样本需要过滤，模拟偏差仍限制闭环可靠性。", transfer: "世界模型最有价值的用途之一不是单独生成视频，而是产生策略训练中缺少的偏离与恢复片段。",
    technique: ["粗到细训练先保留人类行为覆盖，再逐步增加机器人动作权重，避免快速遗忘。", "模拟器适应自身生成上下文后，在专家轨迹周围合成 deviation–recovery 片段，经筛选后做 DAgger 式微调。"],
    evaluation: ["真实策略、跨本体技能和自改进均在 IRON 上闭环评测，每任务每方法 20 次。", "论文证明恢复数据能提高任务完成，但结论仍限于团队自己的模拟器与机器人分布。"], comparison: "不同数据层、无 bridge data、无恢复合成、不同模拟器适应方式与策略基线。",
    reproducibilityStatus: "信息不足", implementation: ["披露两种运行模式、数据金字塔、IRON 部署与 20 次/条件协议。"], missing: ["内部数据、代码、模型权重和完整训练预算未公开。"],
    figureFile: "2609.17372-fig4.png", figureAlt: "XPACE 共享世界模拟和动作生成架构", figureCaption: "Figure 4 · 共享视频骨干在策略与模拟模式间复用，并生成恢复轨迹反哺策略。来源：arXiv 原图。",
  },
  {
    title: "TEMPO: Learning Temporal Context for Dynamic Robot Manipulation", arxivId: "2609.16864", url: "https://arxiv.org/abs/2609.16864",
    institutions: ["University of California, Irvine"], signal: "用冻结视频模型的运动摘要解决运动歧义，用压缩本体历史解决相似画面对应不同动作的状态混叠。",
    tags: ["Temporal Context", "Dynamic Manipulation", "VLA"], classification: { research: "VLA", training: "Post-training", modalities: ["State / Proprioception"], platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://tempo-robot.github.io/" }],
    motivation: "单帧 VLA 看不到移动物体速度，也无法区分视觉相同但任务阶段不同的状态；扩大模型和降低延迟都不能补回缺失历史。", methodSummary: "TEMPO-MOT 从冻结视频基础模型和流式帧缓存提取运动 code；TEMPO-ACT 把最近命令分桶汇总，两者以 token 与 AdaRMS 残差接入原 VLA。",
    architecture: "不改预训练主干；当前 patch 对历史特征缓存 cross-attention，命令历史做 K 桶平均，两个小投影头提供低开销时间条件。", data: "四项动态真实操作任务，并发布含 50K+ 标注帧的 TEMPO-Bench。",
    experiments: "分别构造运动歧义和状态混叠任务，比较单帧 VLA、仅运动、仅本体历史和完整 TEMPO，并做 probing。", novelty: "Bottle Handover 成功率从 44% 升至 74%，且 TEMPO 是比较方法中唯一解决状态混叠的模型。",
    strengths: "两个失败模式与两个时间信号一一对应，消融和表征 probing 能解释收益来源。", limitations: "仅四项动态任务，视频基础模型与历史窗口选择可能限制跨平台迁移；摘要未给每条件 trial 数。", transfer: "不要把动态操作失败都归因于控制频率；先检查观测是否含足够运动与阶段信息。",
    technique: ["运动 code 捕获场景变化，本体命令历史提供执行阶段，两者分别解决 motion ambiguity 与 state aliasing。", "冻结主干并只训练轻量投影与调制路径，使增加时间上下文不必重训完整 VLA。"],
    evaluation: ["四任务中完整模型持续优于单帧和单一时间信号，两个信号的独立消融符合预期失败模式。", "50K+ 帧 benchmark 支持回归和多选式运动感知评测。"], comparison: "单帧基线、仅 TEMPO-MOT、仅 TEMPO-ACT、历史长度与表征 probing。",
    reproducibilityStatus: "部分可复现", implementation: ["项目页、两支时间模块和 benchmark 规模公开。"], missing: ["完整数据下载、逐条件 trial 数和训练权重状态需进一步确认。"],
    figureFile: "2609.16864-fig3.png", figureAlt: "TEMPO 运动摘要和本体历史双时间通道", figureCaption: "Figure 3 · 冻结视频特征缓存提取运动 code，命令历史压缩后共同条件化动作专家。来源：arXiv 原图。",
  },
  {
    title: "UniDex-ViTac: Learning Unified Visuo-Tactile Dexterous Manipulation Policy from Human Video Data", arxivId: "2609.16504", url: "https://arxiv.org/abs/2609.16504",
    institutions: ["Korea Institute of Science and Technology", "KAIST"], signal: "把人类视频动作参考先转成仿真中带接触标签的机器人轨迹，再训练一个部署时只需点云、本体与四个触觉 bit 的统一策略。",
    tags: ["Human Video", "Visuo-Tactile", "Dexterous"], classification: { research: "VLA", training: "BC", modalities: ["Point Cloud / 3D", "Tactile"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "灵巧手"], deployment: "Sim2Real" },
    resources: [{ label: "项目页", url: "https://unidex-vitac.github.io/" }],
    motivation: "人类视频有丰富灵巧行为却没有机器人动作和触觉，直接模仿难以形成可执行的接触策略。", methodSummary: "对象专属 residual-RL specialist 在仿真中跟随人—物交互参考并产生机器人动作—接触轨迹，随后汇总训练一个 ACT generalist。",
    architecture: "ACT 输入点云、本体状态和四个二值指尖接触；触觉以指尖标签与独立 token 编码，部署不需要对象 ID、位姿或人类参考。", data: "10 个对象的 50 条人类示范生成 10,000 条仿真轨迹；真实测试覆盖 6 个已见和 5 个未见对象。",
    experiments: "无需真机示范或微调，真实 110 次试验；同时在仿真比较有无接触输入和不同对象。", novelty: "真机触觉模型成功 73/110（66.4%），点云-only 为 60/110（54.5%），提升 11.8 个百分点。",
    strengths: "人类视频、仿真接触生成与 110 次零样本真机试验贯通，并覆盖未见对象。", limitations: "接触被压缩为四个二值信号，仿真 specialist 仍按对象训练；人类视频规模只有 50 条。", transfer: "人类视频缺失的机器人动作和触觉可由受物理约束的仿真中间层补齐，再蒸馏为统一策略。",
    technique: ["residual RL specialist 只在训练期访问对象参考和特权状态，成功 rollout 同时产生动作目标与指尖接触。", "generalist 把接触 bit 独立 token 化，避免点云编码器吞掉稀疏接触信号。"],
    evaluation: ["仿真 macro success 为 68.3%，point-cloud-only 为 55.5%。", "真实 73/110 对 60/110，未见对象包含在同一零样本协议中。"], comparison: "点云-only ACT、接触增强 ACT、不同 human-reference 与 specialist 配置消融。",
    reproducibilityStatus: "部分可复现", implementation: ["公开 50→10,000 的数据路径、ACT 输入和 110 次真机统计。"], missing: ["生成轨迹、仿真资产和训练代码未确认公开。"],
    figureFile: "2609.16504-fig1.png", figureAlt: "UniDex-ViTac 人类视频到触觉策略管线", figureCaption: "Figure 1 · 人类视频经仿真 residual RL 生成动作—接触轨迹，再训练统一 ACT。来源：arXiv 原图。",
  },
  {
    title: "Predict Before You Deploy: Offline Prediction of Quantization-Induced Task Degradation for World Action Models", arxivId: "2609.19441", url: "https://arxiv.org/abs/2609.19441",
    institutions: ["Colorado School of Mines", "University of Florida", "USC Institute for Creative Technologies"], signal: "用少量闭环开发结果校准离线动作偏差阈值，在真正部署前筛掉可能破坏 WAM 任务表现的量化配置。",
    tags: ["Quantization", "World-Action Model", "Deployment"], classification: { research: "WAM", training: "Post-training", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "GitHub", url: "https://github.com/jiuyixu25/PreDE" }],
    motivation: "WAM 的视频骨干昂贵，但量化位宽、分组和量化器组合众多，逐个闭环测试成本高且位宽不能单独预测任务损失。", methodSummary: "PreDE 用固定观测日志比较参考与量化动作偏差，再从开发配置的闭环标签校准接受/拒绝阈值；阈值不一致时保守地 defer。",
    architecture: "策略无须改动；离线层只缓存观察、参考动作和候选动作差异，决策层输出 accept、reject 或需要闭环验证。", data: "五个 WAM、四类 benchmark；28 个 held-out 量化配置，另有两套独立微调策略的 450 次 Franka Research 3 真机试验。",
    experiments: "先盲测 held-out 配置的可接受/退化标签，再在真机按预先固定的高/低偏差组验证；同时测延迟和峰值显存。", novelty: "PreDE 对 28 个配置中的 21 个作出预判（75% 覆盖），全部与闭环标签一致；W4A4 真机查询加速 1.37×、峰值显存约降 44%。",
    strengths: "450 次真机试验、预注册分组与 defer 机制避免把不确定配置强行判定。", limitations: "保证依赖同一设置内标签排序假设；7/28 配置必须 defer，阈值跨策略不可共享。", transfer: "部署优化应把行为偏差和系统指标联合筛选，并显式保留“必须闭环验证”的不确定区。",
    technique: ["开发集闭环标签只用于确定允许阈值区间；新配置仅在所有一致阈值给出同一结论时接受或拒绝。", "固定观察日志避免不同 rollout 状态分布干扰离线比较，但也意味着异常状态仍需闭环试验。"],
    evaluation: ["高偏差组在 450 次真机中均出现显著退化，低偏差比较未见显著下降。", "defer 集同时包含可接受配置和一次 33 个百分点损失，说明保守拒绝自动判断是必要的。"], comparison: "位宽规则、共享偏差阈值、策略专属 PreDE 与真实闭环标签。",
    reproducibilityStatus: "资源较完整", implementation: ["GitHub、阈值规则、28 个 held-out 配置与 450 次真机协议公开。"], missing: ["跨更多 WAM 架构和真实任务的外部复现仍缺失。"],
    figureFile: "2609.19441-fig1.png", figureAlt: "PreDE 离线预测量化任务退化流程", figureCaption: "Figure 1 · 由少量闭环开发结果校准阈值，再对新量化配置接受、拒绝或延后判断。来源：arXiv 原图。",
  },
  {
    title: "VLA-ULAP: Interleaving Cloud VLA Calls with Ultra-Lightweight Local Action Prediction at the Edge", arxivId: "2609.18663", url: "https://arxiv.org/abs/2609.18663",
    institutions: ["The University of Tokyo", "Institute of Science Tokyo"], signal: "在云端大 VLA 调用之间插入 7.4M 参数本地预测器，用当前视觉、本体和已执行动作补全 action chunk。",
    tags: ["Edge Inference", "Cloud VLA", "Action Prediction"], classification: { research: "VLA", training: "Post-training", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "十亿参数 VLA 难以在低功耗端侧持续运行，纯云推理又会被网络与服务器延迟限制。", methodSummary: "ULAP 独立训练，不读取 VLA hidden state；系统按比例交替调用远程 VLA 和本地单步 chunk 预测器。",
    architecture: "含冻结视觉 encoder 约 7.4M 参数，输入当前多视角、本体状态与已执行动作历史；Jetson Orin Nano 单次 19.9 ms、0.183 J。", data: "三个仿真 base-policy/benchmark 组合，另在 SO-101 实体机械臂上测试已见与未见放置。",
    experiments: "对比 VLA-only、ACT、SP-VLA、RT-Cache 等本地加速方式；真机按成功 episode 调用数估算时间和设备能耗。", novelty: "移除 48.8–76.7% VLA 调用仍保留 95.0–97.5% 基线成功率；真机保留 95.2–100%，时间降 47.9–58.0%，能耗降 52.1–62.5%。",
    strengths: "同时报告端侧延迟、能耗、成功率和动态任务收益，覆盖云端与本地硬件。", limitations: "能耗按设备测量和成功 episode 调用数估算，不含完整网络/服务器基础设施；当前真机任务较简单。", transfer: "大模型不必每个控制步都运行；可把高层语义决策留给云端，把短时连续动作交给轻量本地模型。",
    technique: ["ULAP 与 VLA 解耦训练，不需要服务器返回中间特征，便于替换不同基础策略。", "已执行动作历史让本地预测器沿用当前 chunk 的动力学趋势，远程调用周期性纠偏。"],
    evaluation: ["Jetson Orin Nano 的 19.9 ms/0.183 J 与 RTX A6000 上 GR00T 的 284.3 ms/50.55 J 构成硬件成本参照。", "动态 LIBERO-Safety 中因响应更快，两个任务比 π0.5 高 11.0 和 15.5 个百分点。"], comparison: "VLA-only、ACT、SP-VLA、RT-Cache 与不同交替频率。",
    reproducibilityStatus: "部分可复现", implementation: ["参数量、端侧硬件、延迟、能耗和仿真/真机 operating point 披露。"], missing: ["真实网络波动、服务器总能耗和更复杂真机任务未覆盖。"],
    figureFile: "2609.18663-fig6.png", figureAlt: "VLA-ULAP 成功率与推理成本权衡", figureCaption: "Figure 6 · 不同本地替代频率下成功率与推理成本的 Pareto 权衡。来源：arXiv 原图。",
  },
  {
    title: "UMI-Bridge: Action-Anchored Latent Alignment across Human and Robot Manipulation Data", arxivId: "2609.18232", url: "https://arxiv.org/abs/2609.18232",
    institutions: ["Tsinghua University", "Simple AI"], signal: "把 UMI 当作人类视频与机器人数据之间的动作锚点，使 latent 按末端运动和夹爪行为而非外观相似性对齐。",
    tags: ["UMI", "Latent Alignment", "Human-to-Robot"], classification: { research: "表征学习", training: "Post-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    motivation: "人类视频、UMI 和机器人数据的视角与本体差异很大，像素对齐容易保留外观而丢失动作等价性。", methodSummary: "先在 ego+UMI 上训练 dual-view latent action model，以 UMI 动作监督锚定 latent；再冻结 wrist teacher 与 dynamics model，正则化 VLA 后训练。",
    architecture: "共享 inverse dynamics encoder 生成 latent；paired ego–UMI、同步 head–wrist 提供跨域约束；训练期额外分支不改变部署时标准 VLA 接口。", data: "匹配的 ego、UMI 和机器人数据；三项主真机任务、两项数据效率任务及两项无任务专属机器人示范的迁移任务。",
    experiments: "比较 robot-only、naive co-training、UMI-Bridge 与不同对齐损失；所有结论来自真实机器人操作。", novelty: "三项真机均值 91.7%，naive co-training 为 73.3%；只用 25% 机器人示范配合 UMI 即超过全量 robot-only。",
    strengths: "同时验证统一成功率、机器人数据效率和 UMI-only 新任务迁移，训练/部署接口边界清楚。", limitations: "需要同步或配对的人类—UMI 片段和共享 wrist 视角；对无夹爪接口或强本体差异的适用性未验证。", transfer: "跨域对齐应围绕动作等价关系设计中间域，而不是追求所有观测在像素或语义上相似。",
    technique: ["UMI 动作回归把 latent 锚定到末端运动与夹爪状态；feature dynamics 约束 latent 可预测视觉转移。", "冻结 wrist teacher 在 VLA 后训练时监督 UMI 与机器人数据，额外分支仅训练期存在。"],
    evaluation: ["两项无 task-specific robot demonstration 的任务成功率为 85% 和 90%。", "对齐、latent dynamics 与不同数据比例消融共同支持动作锚点而非单纯增加数据量。"], comparison: "Robot-only、Naive Co-training、全量/25% 机器人数据与各对齐损失消融。",
    reproducibilityStatus: "部分可复现", implementation: ["论文披露两阶段损失、同步数据关系和七项真机评测结构。"], missing: ["完整数据、代码、每条件 trial 数与模型权重未确认公开。"],
    figureFile: "2609.18232-fig2.png", figureAlt: "UMI-Bridge 动作锚定 latent 对齐", figureCaption: "Figure 2 · UMI 动作监督锚定 latent，并在 VLA 后训练中由冻结 wrist teacher 提供跨域正则。来源：arXiv 原图。",
  },
  {
    title: "WholeBodyWAM: Learning Whole-Body World Action Models with Scalable Motion Priors", arxivId: "2609.18197", url: "https://arxiv.org/abs/2609.18197",
    institutions: ["Nankai University", "Beijing Innovation Center of Humanoid Robotics", "Beijing Institute of Technology", "Tsinghua University"], signal: "先把 4K+ 小时人类与异构 humanoid 运动统一成全身预测先验，再与视频和动作 expert 联合后训练。",
    tags: ["Humanoid", "World-Action Model", "Motion Prior"], classification: { research: "WAM", training: "Pre-training", data: "跨本体数据", platforms: ["Humanoid"], deployment: "跨本体迁移" },
    motivation: "目标人形机器人的全身操作轨迹昂贵，而人类和其他 humanoid 运动虽多却不能直接作为目标机器人动作。", methodSummary: "UniMotion-4K 把多源运动 canonicalize 到统一 63D 表征，语言条件 Motion Expert 先预测未来全身运动，再通过不对称 MoT 接入 Video 与 Action Expert。",
    architecture: "Stage I 预训练 Motion Expert；Stage II 三 expert 分层交互。动作 chunk 一部分直接控制臂、头、腰，其余高层命令交给 RL 全身控制器生成下肢动作。", data: "UniMotion-4K 超过 4,000 小时，来自人类视频、原生 3D motion 数据与多种 humanoid 平台，再配目标机器人示范后训练。",
    experiments: "评测未来运动预测、数据规模、有限目标机器人示范和真实人形操作迁移，并消融 motion prior 与 attention 路径。", novelty: "随运动预训练规模增大，预测和下游任务持续提升；在有限目标示范下预训练 prior 显著提高数据效率。",
    strengths: "把不可直接执行的多源运动转成预测先验，而非强行做动作空间映射，真实 humanoid 结果验证迁移。", limitations: "真实任务 trial 数与精确成功率未在摘要报告；下肢仍依赖独立 RL WBC，系统复杂度较高。", transfer: "异构运动数据可以先教模型预测全身意图，再由目标本体动作专家和控制器完成可执行 grounding。",
    technique: ["canonical 63D motion 隔离来源本体差异，语言条件 Motion Expert 学未来全身动力学。", "不对称 attention 限制跨 expert 信息流，防止动作分支在训练时读取部署不可用的未来信息。"],
    evaluation: ["论文报告 motion-pretraining scale、future-motion prediction 与下游成功同步改善。", "真实迁移存在，但缺少摘要级 trial 数；公开内容不把图中柱高改写为精确数值。"], comparison: "无 motion prior、不同预训练小时数、有限目标示范与 attention 结构消融。",
    reproducibilityStatus: "部分可复现", implementation: ["披露 4K+ 小时、63D 表征、两阶段 MoT 和 WBC 接口。"], missing: ["UniMotion-4K 完整下载、训练权重、真实试验次数与统计未确认公开。"],
    figureFile: "2609.18197-fig2.png", figureAlt: "WholeBodyWAM 运动视频动作三专家架构", figureCaption: "Figure 2 · Motion Expert 先学习 63D 全身运动，再与 Video/Action Expert 联合后训练。来源：arXiv 原图。",
  },
  {
    title: "DexTouch-WM: Learning Action-Conditioned Tactile World Models from Human Touch for Dexterous Robot Manipulation", arxivId: "2609.20649", url: "https://arxiv.org/abs/2609.20649",
    institutions: ["HKUST (Guangzhou)", "Xspark AI", "Peking University", "Tsinghua University", "The University of Hong Kong"], signal: "在人手和灵巧手上使用兼容触觉阵列与动作重定向，让 100 小时人类触摸补充固定的真机世界模型监督。",
    tags: ["Tactile World Model", "Human Touch", "Dexterous"], classification: { research: "WM", training: "Pre-training", modalities: ["Tactile"], data: "UMI / Ego / Human Video", platforms: ["灵巧手"], deployment: "跨本体迁移" },
    motivation: "接触世界模型需要密集触觉交互，但真机采集昂贵且传感布局通常与本体绑定。", methodSummary: "人和机器人使用共享布局的柔性压阻阵列，人手动作重定向到机器人空间；视频 expert 与轻量 tactile expert 通过双模态 joint attention 交换信息。",
    architecture: "指尖/掌部 encoder 加 anatomy-aware token；视觉和触觉保留各自 AdaLN 与 FFN，指令与姿态共同条件化未来 RGB 和压力图生成。", data: "真实机器人监督固定为 5 小时，人类交互从 0 扩至 100 小时；人类和机器人任务集合互不重合。",
    experiments: "评测 held-out 机器人域的视觉、几何与接触预测，并把模型用于策略离线评估与生成合成轨迹，再做真机策略学习。", novelty: "增加人类触摸数据在固定 5 小时机器人监督下持续改善三类机器人域预测，并提高世界模型评估与合成训练的实用性。",
    strengths: "明确控制机器人数据量，任务集合不重合，较能隔离人类触觉规模化的贡献。", limitations: "共享触觉布局与动作重定向是关键前提；摘要没有给出真机策略 trial 数和全部数值。", transfer: "跨本体触觉迁移需要先对齐传感拓扑和动作语义，单纯把不同触觉图拼在一起不足以共享动力学。",
    technique: ["anatomy-aware token 保留每个触觉 pad 的身份，双 expert joint attention 学视觉—接触演化。", "人类动作先重定向到机器人控制空间，使同一个 action-conditioned model 可同时吸收两域数据。"],
    evaluation: ["0→100 小时人类数据的 scaling 在固定 5 小时真机数据下比较，避免机器人数据量混杂。", "论文还把世界模型用于 surrogate evaluation 和 synthetic trajectory generation，但公开卡片不补写摘要未给出的精确成功率。"], comparison: "不同人类触觉小时数、无触觉 expert、不同 token/attention 连接与机器人-only 世界模型。",
    reproducibilityStatus: "部分可复现", implementation: ["共享阵列、动作重定向、5h+0–100h 数据设计和双 expert 结构披露。"], missing: ["完整数据、硬件制造细节、代码与真机策略 trial 数未确认公开。"],
    figureFile: "2609.20649-fig2.png", figureAlt: "DexTouch-WM 视频与触觉双专家架构", figureCaption: "Figure 2 · 视觉和触觉 expert 通过 joint attention 共同预测未来 RGB 与双手压力图。来源：arXiv 原图。",
  },
  {
    title: "TraceFlow: Guiding Frozen Flow-Matching Robot Policies with Success and Failure Traces", arxivId: "2609.20646", url: "https://arxiv.org/abs/2609.20646",
    institutions: ["The University of Hong Kong", "HKU InfoBodied AI Lab", "Southern University of Science and Technology"], signal: "把成功与失败 rollout 的动作密度变成有界 guidance field，在不更新 VLA 权重的情况下修正 flow-matching action chunk。",
    tags: ["Test-time Guidance", "Failure Traces", "Flow Matching"], classification: { research: "Memory", training: "Test-time Adaptation", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    detailAttributes: { memoryImplementation: "TraceBank 中按进度对齐的成功/失败状态—动作窗口", memoryHorizon: "跨 rollout 的部署期记忆" },
    motivation: "冻结 VLA 无法让先前 rollout 的成功或失败改变下一次生成，而现有 test-time 方法通常不用仅带终局 bit 的失败轨迹。", methodSummary: "TraceBank 检索相似状态并按任务进度对齐成功/失败动作窗口；成功密度吸引、失败密度排斥当前 noisy chunk，guidance 只作用于早期流积分。",
    architecture: "VLM 与 action expert 全冻结；额外 retrieval head、Similarity Gate 和持续增长的 TraceBank。每条新 rollout 只需一个终局成败标签。", data: "目标任务训练轨迹初始化记忆库，部署 rollout 逐轮堆叠；真机为有顺序约束的 packing，仿真含 RoboMemArena 与 LIBERO-Plus。",
    experiments: "真机每方法 50 次；仿真按 suite 报告顺序、迁移、计数和遮挡，并跟踪最多十轮堆叠与显著性。", novelty: "真机顺序完成由 21/50 升至 39/50，一轮堆叠后 47/50；错误顺序由 20 次降至 0。",
    strengths: "正面报告仿真负收益、p=0.0733 的不显著结果和有限堆叠峰值，证据边界清楚。", limitations: "按 suite 选择设置，整体 26 任务平均不变；Counting 与 Occlusion 分别下降 1.12、1.42 点，记忆继续堆叠并非单调改善。", transfer: "失败轨迹不必标注失败位置；若能按进度对齐，其动作分布本身可作为 test-time 负证据。",
    technique: ["检索窗口转成成功与失败 action density，对 flow velocity 加有界吸引/排斥修正。", "每轮执行后只写入终局 bit，并在堆叠前对齐进度，避免直接混合不同阶段动作。"],
    evaluation: ["RoboMemArena Sequence 由 78.92% 升至 91.50%，Transferring 由 54.41% 升至 62.00%。", "LIBERO-Plus Long 仅 +1.27 点且 p=0.0733；公开页面保留这一不确定性。"], comparison: "冻结基础策略、成功-only、成功+失败 TraceFlow、不同 guidance 与堆叠轮数。",
    reproducibilityStatus: "部分可复现", implementation: ["公开 guidance 结构、50 次真机协议、各 suite 正负结果和统计。"], missing: ["代码、TraceBank 数据和跨机器人复现未确认公开。"],
    figureFile: "2609.20646-fig1.png", figureAlt: "TraceFlow 成功失败轨迹引导场", figureCaption: "Figure 1 · 成功动作密度吸引、失败动作密度排斥 noisy action chunk，策略权重保持冻结。来源：arXiv 原图。",
  },
  {
    title: "AnyViewDex: View-Invariant Dexterous Manipulation from RGB Observations", arxivId: "2609.20107", url: "https://arxiv.org/abs/2609.20107",
    institutions: ["Robotics Research Center, IIIT Hyderabad", "Veermata Jijabai Technological Institute", "IISER Bhopal"], signal: "训练时用多视角对比与特权 3D 坐标监督把几何写进 RGB 表征，部署时只需未标定单目 RGB 和本体状态。",
    tags: ["View Invariance", "Dexterous", "Sim2Real"], classification: { research: "表征学习", training: "RL", modalities: ["Point Cloud / 3D", "State / Proprioception"], platforms: ["机械臂", "灵巧手"], deployment: "Sim2Real" },
    resources: [{ label: "项目页", url: "https://anyviewdex.github.io/" }],
    motivation: "灵巧策略容易依赖固定相机；测试时加入 RGB-D 或点云又引入标定、噪声和硬件依赖。", methodSummary: "仿真训练同时渲染同一物理状态的多视角图像，用 contrastive alignment 聚合同状态，并回归绝对 3D 对象坐标防止全局池化发生空间坍缩。",
    architecture: "训练期可见特权 3D 几何；部署删去辅助头，只保留单目 RGB encoder、策略与本体输入。方法同时验证 RL 和 teacher–student distillation。", data: "仿真多视角训练；真实 xArm7+16-DoF LEAP Hand，8 个未见对象、6 个未标定视角。",
    experiments: "主硬件评测 480 次，包含所有消融共 2,400 次；比较视觉对比、3D 辅助监督、两者组合和显式深度路线。", novelty: "仅用测试时 RGB 与本体即在 8 个未见对象、6 个视角上达到 76.7% 抓取成功率。",
    strengths: "480 次主试验和 2,400 次含消融硬件执行，视角与对象同时 held out，统计规模充分。", limitations: "策略仍利用仿真中的绝对 3D 教师，任务集中在抓取；更长程、接触丰富的操作尚未验证。", transfer: "测试时不想依赖 3D 传感器时，可把几何作为训练期监督写入 RGB 表征，而非完全舍弃几何。",
    technique: ["同一状态多相机渲染做 contrastive alignment，抑制视角特定外观。", "绝对 3D 坐标回归补充空间 grounding，避免对比学习只保留全局相似性。"],
    evaluation: ["主结果 76.7% 来自 480 次真实抓取，所有消融条件累计 2,400 次。", "零样本部署不使用深度与相机标定，但训练仍依赖仿真几何和 sim-to-real 随机化。"], comparison: "单视角、仅对比、仅 3D 监督、完整模型、RL 与蒸馏路径。",
    reproducibilityStatus: "部分可复现", implementation: ["项目页、仿真监督、xArm7/LEAP Hand 和 480/2,400 次协议公开。"], missing: ["训练代码、仿真资产和跨任务数据未确认公开。"],
    figureFile: "2609.20107-fig2.png", figureAlt: "AnyViewDex 多视角对比与三维监督", figureCaption: "Figure 2 · 同一物理状态的多视角图像做对比对齐，并用训练期 3D 坐标保持空间结构。来源：arXiv 原图。",
  },
  {
    title: "Towards High-DoF Dexterous Manipulation through VLA Post-Training", arxivId: "2609.19666", url: "https://arxiv.org/abs/2609.19666",
    institutions: ["Wuji Technology", "ShanghaiTech University"], signal: "以手部动作 codec 统一 SFT、连续 DAgger 与真机 residual RL，把开放 VLA 适配到 20-DoF 灵巧手。",
    tags: ["VLA Post-training", "Dexterous Hand", "Real-world RL"], classification: { research: "VLA", training: "Post-training", data: "在线数据 / 人工纠正", platforms: ["机械臂", "灵巧手"] },
    resources: [{ label: "项目页", url: "https://wuji.tech/blog/post-training-0" }],
    motivation: "开放 VLA 缺少高自由度手接口，人工接管时手势不连续会污染纠正轨迹，原始关节空间 RL 又极低效。", methodSummary: "时间手部动作 codec 把绝对手指命令压到协调 latent；SFT 后用回滚、姿态对齐与平滑混合采 DAgger，再在 codec latent 上做真机 residual RL。",
    architecture: "双 7-DoF Tianji 臂、双 20-DoF Wuji 手、一个头部和两个腕部 RGB；所有关节位置控制与记录均为 30 Hz。", data: "五项真实任务，覆盖双臂传递、掌内重定向与工具使用；纠正数据和在线交互按后训练阶段逐步加入。",
    experiments: "每项最终策略 20 次，共 100 次；逐阶段比较 SFT、DAgger 和 residual RL，并检查不同 codec 与接管平滑机制。", novelty: "在论文报告的后训练预算内，五项任务最终均为 20/20 成功。",
    strengths: "从动作接口、人在环纠正到真机 RL 形成完整工程链，并有每任务 20 次最终评测。", limitations: "五项任务均在同一双臂灵巧手平台，100% 来自最终固定条件；训练成本和跨对象统计仍需外部复现。", transfer: "高自由度动作先学习协调 latent，再在 latent 上纠错与探索，能同时降低接管断点和 RL 维度。",
    technique: ["buffered rollback 回到接管前状态，pose alignment 与命令 blending 让人类纠正轨迹连续。", "residual RL 不直接扰动 40 个手指关节，而是在 codec 学到的协调 latent 中探索。"],
    evaluation: ["最终五任务各 20 次均成功，总计 100/100；任务含写字、重定向、双臂转移和工具使用。", "结果强但来自单一平台与团队，公开页面不把 100% 外推为开放世界可靠性。"], comparison: "SFT、加入 DAgger、加入 latent residual RL，以及 codec、回滚和混合策略消融。",
    reproducibilityStatus: "部分可复现", implementation: ["项目页、30 Hz 硬件接口、四阶段后训练和 20 次/任务结果公开。"], missing: ["完整数据、在线交互分钟数、训练代码与模型权重未确认公开。"],
    figureFile: "2609.19666-fig1.png", figureAlt: "高自由度灵巧手 VLA 四阶段后训练", figureCaption: "Figure 1 · 动作 codec、SFT、连续 DAgger 与 latent residual RL 逐步提高真机灵巧操作。来源：arXiv 原图。",
  },
];

export const paperDaily20260918 = entries.map(makePaper);
