import type { Paper } from "./site-data";

type Entry = Omit<Paper, "rank" | "figures" | "optimization" | "experimentDetails" | "reproducibilityDetails" | "deepDive"> & {
  figureFile: string; figureAlt: string; figureCaption: string;
  technique: string[]; evaluation: string[]; comparison: string;
  reproducibilityStatus: "资源较完整" | "部分可复现" | "信息不足";
  implementation: string[]; missing: string[];
};

const makePaper = (entry: Entry, index: number): Paper => ({
  ...entry,
  rank: index + 1,
  optimization: entry.technique.join("；"),
  experimentDetails: [{ title: "原文实验与消融", setup: entry.experiments, comparisons: entry.comparison, results: entry.evaluation }],
  reproducibilityDetails: {
    status: entry.reproducibilityStatus,
    verifiedResources: entry.resources?.map((x) => `${x.label}: ${x.url}`) ?? ["arXiv 论文正文"],
    implementation: entry.implementation,
    missing: entry.missing,
  },
  deepDive: {
    lead: entry.methodSummary ?? entry.signal,
    sections: [{ title: "技术细节", paragraphs: entry.technique }],
    experimentReading: entry.evaluation,
    reflections: [entry.transfer],
  },
  figures: [{ src: `/report-assets/2026-09-21/${entry.figureFile}`, alt: entry.figureAlt, caption: entry.figureCaption }],
});

const entries: Entry[] = [
  {
    title: "SeeQ: Training Generalist Value Functions for Long-Horizon Robotic Manipulation", arxivId: "2609.22085", url: "https://arxiv.org/abs/2609.22085",
    institutions: ["Carnegie Mellon University"], signal: "把长程任务的价值预测缩短到当前子任务，并让价值模型自行预测正在执行的子任务。",
    tags: ["Value Function", "Subtask", "Policy Steering"], classification: { research: "Subtask", training: "RL", platforms: ["机械臂", "夹爪"] },
    motivation: "稀疏的整任务奖励让长程操作的价值学习承担过长的信用分配链，失败动作难以定位到具体步骤。",
    methodSummary: "SeeQ 在价值估计前先自回归预测当前子任务文本，再用子任务边界内的 TD 目标训练 Q 值；测试时从固定 π0.5 提议的八个动作块中选最高值。",
    architecture: "PaliGemma 3B 视觉语言骨干接子任务文本解码与标量价值头，价值条件包含状态、候选动作和当前子任务。",
    data: "用 RoboCOIN 双臂数据预训练，覆盖 131 项任务和约 4 万段轨迹；目标任务还需带子任务标注的数据微调。",
    experiments: "xArm-7 与 YAM 双臂平台的四项真机任务，每项每方法 24 次；比较相同底座的 Monte Carlo、整任务 TD 和子任务 SARSA critic，并做预训练及子任务预测消融。",
    novelty: "shirt-hang 从基础策略 10/24 提至 22/24；grocery-packing 从 9/24 提至 17/24，四项任务均按完整完成判定。",
    strengths: "同一候选动作池与真实双臂任务下比较价值目标，消融显示机器人预训练和显式子任务预测都关键。",
    limitations: "训练仍需子任务边界标注与任务微调；当前价值模型只能重排基础策略提出的动作块，受候选动作质量限制。",
    transfer: "长程策略的 critic 可在子任务边界处截断自举，把局部进展估计直接用于动作块重排。",
    technique: ["训练时在子任务边界停止 TD 自举，避免后续步骤的奖励噪声污染当前价值目标。", "先解码当前子任务，再估计候选动作价值；测试不依赖外部子任务分类器。"],
    evaluation: ["shirt-hang 的同骨干整任务 TD 为 12/24、子任务 SARSA 为 13/24，而 SeeQ 为 22/24。", "移除机器人预训练或子任务预测后，shirt-hang 均降至 8/24；每任务 24 次仍不足以精确估计小幅差异。"],
    comparison: "π0.5 原策略、同底座多种 critic，以及无预训练和无子任务预测消融。",
    reproducibilityStatus: "部分可复现", implementation: ["披露子任务 TD 目标、预训练数据规模、动作候选数和四任务 24 次协议。"], missing: ["完整任务标注数据和目标任务微调权重未确认公开。"],
    figureFile: "2609.22085-fig2.png", figureAlt: "SeeQ 子任务预测与动作价值估计结构", figureCaption: "Figure 2 · 价值模型先生成当前子任务文本，再为候选动作块估计 Q 值。来源：arXiv HTML 原图。",
  },
  {
    title: "PSR: Predictive Sensorimotor Representation Learning for Contact-Rich Manipulation", arxivId: "2609.21753", url: "https://arxiv.org/abs/2609.21753",
    institutions: ["Samsung R&D Institute China-Beijing"], signal: "从力矩、关节状态与视觉历史预测未来接触信号，再把分层表征注入 VLA 动作专家。",
    tags: ["Force / Torque", "Sensorimotor", "Contact-rich"], classification: { research: "表征学习", training: "Pre-training", modalities: ["Force / Torque", "State / Proprioception"], platforms: ["机械臂", "夹爪"] },
    motivation: "仅靠视觉和瞬时状态难以区分插接、旋拧等任务中的接触阶段，直接拼接传感器又缺少未来变化监督。",
    methodSummary: "PSR 预训练六层传感运动层级来预测未来力/力矩、关节 effort 与末端位移，再经门控 cross-attention 接入 π0.5 动作专家。",
    architecture: "多模态编码和跨模态瓶颈形成浅、中、深三层表征；动作专家在第 3、6、9、12、15、18 层读取 PSR。",
    data: "六项 RB-Y1 接触任务共 1210 条示范，任务示范量分别为 300、300、200、200、150、60。",
    experiments: "六项真机任务，每方法每任务 20 次，以完整完成为成功；另有两任务的表示和注入位置消融及 PSR 单模型扰动测试。",
    novelty: "六任务 PSR 合计 110/120 次成功（91.7%），π0.5 为 74/120（61.7%）。",
    strengths: "同数据的接触任务对照、多个注入位置消融和四次 PSR 训练重复共同支持未来传感预测的价值。",
    limitations: "基线与 PSR 的传感输入和预训练预算并非全部严格匹配；新物体、长程接触泛化尚未系统验证。",
    transfer: "接触表示可用未来传感读数作训练目标，再以门控方式逐层介入动作生成。",
    technique: ["分别预测未来 12 路力/力矩、20 路关节 effort 和末端关节位移，保留接触的时间方向。", "门控 cross-attention 在动作专家六个深度位置注入层级表征，而非只在输入或末层拼接。"],
    evaluation: ["ForceVLA 为 83/120，适配的 ForceVLA2 为 87/120；输入、参数和预训练预算差异限制横向归因。", "两任务真机消融中，完整 PSR 均为 19/20；去预训练后分别为 14/20 和 11/20，末层单点注入为 10/20 和 11/20。"],
    comparison: "π0.5、ForceVLA 系列，以及无预训练、反向层级、共享深层和末层单点注入消融。",
    reproducibilityStatus: "部分可复现", implementation: ["披露传感目标、注入层、示范分布、每任务 20 次协议与四次训练重复。"], missing: ["完整传感数据、权重及跨硬件复现实验未确认公开。"],
    figureFile: "2609.21753-fig2.png", figureAlt: "PSR 预测力觉与关节状态的分层表示学习", figureCaption: "Figure 2 · 传感运动编码器预测未来力觉、关节 effort 和末端位移，再供动作策略读取。来源：arXiv HTML 原图。",
  },
  {
    title: "From Pretraining to Proficiency: Real-World Subtask RL for Long-Horizon Manipulation with Minimal Human Intervention", arxivId: "2609.21788", url: "https://arxiv.org/abs/2609.21788",
    institutions: ["The University of Texas at Austin", "Autel US", "University of California, Berkeley"], signal: "把真机 RL 集中到基础策略反复失败的子任务，局部验证与复位使稀疏长程奖励更可训练。",
    tags: ["Subtask RL", "Residual Policy", "Real Robot"], classification: { research: "Subtask", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://destiny000621.github.io/PARTS/" }],
    motivation: "完整任务上的 RL 在瓶颈前反复浪费 rollout，后段步骤很少得到局部成功反馈。",
    methodSummary: "PARTS 保持预训练 π0.5 不变，为人工识别的瓶颈训练有界 residual TD3+BC 策略，并用选择器、验证器及复位程序组织局部练习。",
    architecture: "基础策略生成名义动作；子任务选择器在指定状态启用残差；验证器给局部奖励，成功重加权再训练后重新部署。",
    data: "真机在线数据来自 YAM 双臂耳机插入、LEGO 分拣和 Franka 线缆任务；还需操作员设置瓶颈和复位。",
    experiments: "三项真机长程任务，每方法完整任务评测 20 次，并在相同机器人 rollout 时间下对比全任务 RL 方法。",
    novelty: "论文报告双臂任务完整成功率合计由 32% 升至 61%，Franka 任务由 50% 升至 95%；训练用数十分钟级真机交互。",
    strengths: "局部奖励、残差策略和失败重试共同针对长程瓶颈，并用完整任务而非仅局部成功验证。",
    limitations: "瓶颈选择、合约和部分复位仍需要人；成功率受任务设置及基础策略已有能力限制。",
    transfer: "先保留基础策略已稳定的步骤，再对少数失效环节做局部残差 RL，可提高真机数据利用率。",
    technique: ["人指定瓶颈与可验证的子任务合约，代码代理实现选择、成功判定和自动复位程序。", "有界 TD3+BC 残差只在瓶颈启用，成功轨迹重加权再训练后继续在线收集。"],
    evaluation: ["完整任务按每方法每任务 20 次评测；相同 rollout 时间下与 DSRL、EXPO-FT 和 RLT 比较。", "耳机任务的成功重加权消融支持后续迭代收益，但局部人工判定与复位成本未完全自动化。"],
    comparison: "冻结基础策略、全任务 RL 方法以及成功重加权再训练消融。",
    reproducibilityStatus: "部分可复现", implementation: ["项目页、三种真机任务、20 次完整任务协议和训练流程披露。"], missing: ["各任务的人工介入总时长、完整设备/代码和数据状态未确认公开。"],
    figureFile: "2609.21788-fig2.png", figureAlt: "PARTS 子任务合约与残差强化学习流程", figureCaption: "Figure 2 · 选择器、验证器和复位程序把基础策略的瓶颈接入局部 residual RL。来源：arXiv HTML 原图。",
  },
  {
    title: "GALA: Geometry-Aware Latent Action Modeling for Vision-Language-Action Model Pretraining across Embodiments", arxivId: "2609.21948", url: "https://arxiv.org/abs/2609.21948",
    institutions: ["Tsinghua University", "Shanghai Qi Zhi Institute"], signal: "用视觉与末端点云共同编码 latent action，使人类手和异构夹爪的细粒度运动能共享训练信号。",
    tags: ["Latent Action", "Geometry", "Cross-embodiment"], classification: { research: "表征学习", training: "Pre-training", modalities: ["Point Cloud / 3D"], data: "跨本体数据", platforms: ["机械臂", "灵巧手"], deployment: "跨本体迁移" },
    motivation: "纯图像 latent action 容易混淆外观变化与手指运动，异构末端的几何变化又难直接放入同一动作接口。",
    methodSummary: "GALA 联合学习视觉与点云几何 latent，通过 UEMR 的双向转移和成对一致性约束保留跨本体末端运动，再监督 VLA 桥接 token。",
    architecture: "冻结视觉和点云编码器提取状态；视觉与几何 latent 共享时空建模；冻结 latent 监督 VLM bridge token，动作 expert 使用本体专属输出头。",
    data: "组合 EgoDex、HOI4D、DROID、RoboCasa GR1 与自采 XHand/人手交互数据。",
    experiments: "细粒度运动探针、跨本体检索、RoboCasa 与 XHand 四项真机任务；真机每任务 50 次。",
    novelty: "相同数据和底座的 RoboCasa 对照中，GALA 为 55.7%，UniVLA 为 48.0%；XHand 真机四任务均值 75.5%。",
    strengths: "从 latent 诊断、仿真控制到真机灵巧操作的多层证据，并单独消融点云与 UEMR。",
    limitations: "跨团队真机基线骨干和训练设置不完全一致；点云质量与末端几何标定仍影响迁移。",
    transfer: "跨本体动作可先比较末端几何转移，再由各本体动作头映射到原生命令。",
    technique: ["视觉 latent 与点云几何 latent 并行学习，UEMR 以共享末端运动表征约束双向状态转移。", "冻结 GALA 表征给 VLM bridge token 提供监督，动作 expert 通过本体专属 head 输出原生动作。"],
    evaluation: ["RoboCasa 同设置消融：去点云为 50.9%，去 UEMR 为 54.4%，完整模型 55.7%。", "真机均值 75.5%，HARP-VLA 71.5%、π0.5 68.0%；跨方法骨干差异使该差值不能单独归因于 latent。"],
    comparison: "RoboCasa 的 UniVLA 和组件消融，XHand 上的 HARP-VLA、π0.5 与去 UEMR 消融。",
    reproducibilityStatus: "部分可复现", implementation: ["披露多源数据、UEMR、同底座消融和四任务 50 次真机协议。"], missing: ["全部自采数据、权重和独立跨本体复现未确认公开。"],
    figureFile: "2609.21948-fig2.png", figureAlt: "GALA 视觉与点云几何 latent action 联合学习", figureCaption: "Figure 2 · 图像与末端点云转移分别形成 latent，UEMR 约束跨本体几何一致性。来源：arXiv HTML 原图。",
  },
  {
    title: "MT-WAM: Reorienting the One-Pass Predictive Representation Toward Action Generation", arxivId: "2609.21474", url: "https://arxiv.org/abs/2609.21474",
    institutions: ["Aerospace Information Research Institute, Chinese Academy of Sciences", "University of Chinese Academy of Sciences"], signal: "在不推理未来视频的 WAM 中，用未来点轨迹和视觉特征监督改善一次前向的动作条件表示。",
    tags: ["World-Action Model", "Motion Prediction", "One-pass"], classification: { research: "WAM", training: "Pre-training", modalities: ["其他模态"], platforms: ["机械臂", "夹爪"] },
    motivation: "仅靠未来画面重建会把大量外观细节压进单次 video backbone 表征，动作专家难以直接获取关键运动信息。",
    methodSummary: "MT-WAM 复制 video DiT 尾部形成双流动态分支：点轨迹流直接给动作专家 KV，未来 DINOv2 特征流只训练视觉骨干。",
    architecture: "视频主干与前段共享，尾部 10 层复制为 motion/feature 双流；两流独立 FFN 和注意力掩码，推理只复用 video 与 motion KV cache。",
    data: "RoboTwin 50 任务、LIBERO/LIBERO-Plus，以及四项 UR5 真机任务各 100 条示范，共 400 条。",
    experiments: "LIBERO、LIBERO-Plus、RoboTwin 2.0 与四项真机任务；真机每任务每方法 100 次，共 400 次，同样初始配置。",
    novelty: "四项真机平均成功率 77.8%，Fast-WAM 为 67.0%；LIBERO-Plus 为 73.66%，Fast-WAM 为 49.86%。",
    strengths: "相同真机数据和试验配置、跨三个仿真协议及流连接消融，清楚隔离预测监督与推理接口。",
    limitations: "二维轨迹没有显式三维接触几何；目前只验证一个视频骨干和 UR5 单/双臂配置。",
    transfer: "未来预测分支可以只在训练时提供语义监督，推理时仅保留与控制直接相关的运动缓存。",
    technique: ["CoTracker3 产生未来二维点位移目标，冻结 DINOv2 提供未来 patch 特征目标，两者与视频/动作流匹配目标联合训练。", "动作查询读取 motion 流而不读取 feature 流；推理跳过未来视频生成，每次重规划只构建一次缓存。"],
    evaluation: ["LIBERO-Plus 去掉 feature 流后由 73.7% 降到 68.8%；让动作直接读取 feature 流则降至 70.9%。", "相同 GPU 下延迟为 313.5 ms，Fast-WAM 为 296.3 ms；RoboTwin Clean2Rand Random 为 19.4%，仍低于有额外预训练的 HALO 26.4%。"],
    comparison: "Fast-WAM、Fast-WAM-Joint、其他 WAM/VLA，以及视觉流连接和分支深度消融。",
    reproducibilityStatus: "部分可复现", implementation: ["公开训练目标、attention 规则、分支深度、400 次真机协议和推理成本。"], missing: ["完整训练权重、全部训练数据与跨骨干验证未确认公开。"],
    figureFile: "2609.21474-fig2.png", figureAlt: "MT-WAM 双流动态分支与单次缓存推理", figureCaption: "Figure 2 · 未来点轨迹与视觉特征分流训练，动作专家在推理时读取运动缓存。来源：arXiv HTML 原图。",
  },
  {
    title: "Skel-WAM: A Hand-Skeleton-Conditioned World Action Model for Human-to-Robot Manipulation Transfer", arxivId: "2609.21514", url: "https://arxiv.org/abs/2609.21514",
    institutions: ["The Chinese University of Hong Kong", "Shanghai AI Laboratory", "Joy Future Academy"], signal: "把人手与机器人灵巧手映射到双手 21 点骨架，用人类视频补足机器人示范缺少的任务变化。",
    tags: ["Human Video", "Hand Skeleton", "World-Action Model"], classification: { research: "WAM", training: "Pre-training", modalities: ["其他模态"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "灵巧手"], deployment: "跨本体迁移" },
    motivation: "人类视频缺机器人动作，外观与手部关节又不一致，直接共训难把人类任务变化稳定迁移到灵巧手。",
    methodSummary: "Skel-WAM 用场景骨架叠图和结构化 2.5D 手部关键点共同预测未来；共享 Video-Keypoint MoT 学人/机动态，Action Expert 只用机器人动作训练。",
    architecture: "双手各 21 个关键点映射到相同拓扑；Video Expert 与 Keypoint Expert 预测未来，因果 Action Expert 将视频和骨架条件解码为本体动作。",
    data: "每项真机任务平均约 50 条机器人示范和 25 条人类示范；人类片段提供位置、旋转、干扰物与高度变化。",
    experiments: "双 Franka FR3 加 XHand1 的四项双臂真机任务，另有七项仿真任务；机器人设定每任务 24 次、缺失变化每项 9 次、新背景每项 6 次，Stack Cups 机器人设定 18 次。",
    novelty: "四项真机机器人设定平均完整成功率 79.86%，EgoVLA 为 57.64%；人类覆盖的缺失变化从 38.89% 提到 86.11%。",
    strengths: "固定任务语言、明确分离机器人缺失变化，叠图与关键点独立消融能解释迁移来源。",
    limitations: "人手关键点估计、相机标定和人机示范匹配成本较高；缺失变化每条件只有 9 次。",
    transfer: "人类视频可监督共享的未来手部运动，而机器人原生控制头仍只从有动作标签的机器人数据学习。",
    technique: ["手骨架同时保留叠图的场景位置和结构化 2.5D 关键点的手指身份、深度及轨迹。", "人机数据共训 Video-Keypoint MoT；Action Expert 只读机器人动作标签，避免伪造人手对应的机器人命令。"],
    evaluation: ["缺失变化上，去叠图为 50.0%，去关键点为 13.89%，完整模型为 86.11%。", "七项仿真平均成功率 63.29%，EgoVLA 为 55.01%；新背景真机平均成功率 58.33%。"],
    comparison: "ACT、Fast-WAM、LDA、EgoVLA；有无人机共训及两种骨架表示消融。",
    reproducibilityStatus: "部分可复现", implementation: ["披露关键点拓扑、训练目标、示范数量、控制频率和分条件成功定义。"], missing: ["完整人类/机器人示范、关键点处理代码和权重未确认公开。"],
    figureFile: "2609.21514-fig2.png", figureAlt: "Skel-WAM 视频骨架联合预测与机器人动作解码", figureCaption: "Figure 2 · 人机视频共训 Video-Keypoint MoT，机器人示范单独训练 Action Expert。来源：arXiv HTML 原图。",
  },
];

export const paperDaily20260921 = entries.map(makePaper);
