import type { Paper } from "./site-data";

type Entry = Omit<Paper, "rank" | "figures" | "optimization" | "experimentDetails" | "reproducibilityDetails" | "deepDive"> & {
  figure: { number: string; ext?: "png" | "jpg"; alt: string; caption: string };
  technique: string[];
  evaluation: string[];
  comparison: string;
  reproducibilityStatus: Paper["reproducibilityDetails"] extends infer R ? R extends { status: infer S } ? S : never : never;
  implementation: string[];
  missing: string[];
};

const makePaper = (entry: Entry, index: number): Paper => ({
  ...entry,
  rank: index + 1,
  optimization: entry.technique.join("；"),
  experimentDetails: [{
    title: "实验与消融测试",
    setup: entry.experiments,
    comparisons: entry.comparison,
    results: entry.evaluation,
    evidenceNote: "数字均按论文表格、附录或正文中的评测协议复核；未报告的真机重复次数不会由演示视频推断。",
  }],
  reproducibilityDetails: {
    status: entry.reproducibilityStatus,
    verifiedResources: entry.resources?.map((resource) => `${resource.label}: ${resource.url}`) ?? ["arXiv 正文与附录"],
    implementation: entry.implementation,
    missing: entry.missing,
  },
  deepDive: {
    lead: entry.methodSummary ?? entry.signal,
    sections: [
      { title: "技术细节", paragraphs: entry.technique },
      { title: "证据边界", paragraphs: entry.evaluation },
    ],
    experimentReading: entry.evaluation,
    reflections: [entry.transfer],
  },
  figures: [{
    src: `/report-assets/2026-08-14/${entry.arxivId}-fig${entry.figure.number}.${entry.figure.ext ?? "png"}`,
    alt: entry.figure.alt,
    caption: entry.figure.caption,
  }],
});

const entries: Entry[] = [
  {
    title: "FACT: Failure-Aware Causal Training for World-Action Models", arxivId: "2608.10232", url: "https://arxiv.org/abs/2608.10232",
    institutions: ["University of California San Diego"], signal: "把失败轨迹当作动作后果监督，而不是错误动作示范。",
    tags: ["WAM", "Failure Data", "Real Robot"], classification: { research: "WAM", training: "Post-training", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://fact-wam.github.io" }],
    motivation: "只看成功示范的 WAM 容易把坏动作也想象成成功未来；直接模仿失败动作又会污染策略。",
    methodSummary: "共享因果扩散 Transformer 先生成动作，再以干净动作槽预测未来视频和任务进度；失败样本屏蔽动作损失，只保留未来与低进度监督。",
    architecture: "WAN2.2-5B 主干加逐层 action adapter，序列分为观察前缀、噪声动作、干净动作、价值与未来帧槽；部署分两阶段执行并可选价值排序。",
    data: "RoboTwin 50 个任务加入约 1,300 条失败轨迹；五项双臂真机任务在成功示范外每项收集约 30 条失败轨迹。",
    experiments: "RoboTwin 与五项真机任务；真机每个配置 20 次，报告直接执行、失败感知训练和可选候选排序。",
    novelty: "相较只用成功未来监督，FACT 在不模仿坏动作的前提下学习其真实后果；RoboTwin 由 81.8% 提至 85.6%，价值排序为 87.5%。",
    strengths: "失败数据的作用路径、损失掩码和候选排序被分别消融，且真机按固定次数评测。",
    limitations: "需要采集并标出失败发生点；两阶段推理及多候选排序增加延迟，真机任务仍以桌面双臂为主。",
    transfer: "可将失败回放接到已有 WAM 的世界分支，并严格阻断失败动作的 imitation gradient。",
    technique: ["动作块 H=48，失败惩罚系数为 1；未来监督覆盖当前帧及四个未来偏移。", "成功数据优化动作、价值和视频损失；失败数据只优化价值与视频损失，进度目标在失败发生后下调。"],
    evaluation: ["五项真机任务各 20 次：基础 FACT 82%，加入失败数据 89%，再用价值候选排序 92%。", "未见场景平均成功率由 67% 提至 77%，候选排序后为 82%；论文同时报告失败数据规模消融与坏动作未来幻觉诊断。"], comparison: "π0.5、OpenVLA-OFT、WorldVLA、DreamZero 及成功数据/失败数据/价值排序消融。",
    reproducibilityStatus: "部分可复现", implementation: ["论文给出损失、动作/未来时域、学习率与推理步数。"], missing: ["失败轨迹与完整训练代码尚未在本次检查中确认公开。"],
    figure: { number: "2", alt: "FACT 动作先行的失败感知世界动作模型", caption: "Figure 2 · 动作、价值和未来视频的共享因果结构，以及成功/失败样本的损失掩码。来源：arXiv HTML 原图。" },
  },
  {
    title: "RynnValue: Scaling Robotic Value Foundation Models with Temporal Distance", arxivId: "2608.09853", url: "https://arxiv.org/abs/2608.09853",
    institutions: ["DAMO Academy, Alibaba Group", "Hupan Lab"], signal: "用可从时间戳自动生成的有向剩余步数，统一训练跨任务机器人价值模型。",
    tags: ["Reward Model", "Temporal Distance", "Offline / Online RL"], classification: { research: "表征学习", training: "Pre-training", data: "跨本体数据", platforms: ["机械臂"] },
    resources: [{ label: "项目页", url: "https://alibaba-damo-academy.github.io/RynnValue.github.io" }, { label: "GitHub", url: "https://github.com/alibaba-damo-academy/RynnValue" }],
    motivation: "偏好或归一化进度标签依赖任务内部锚点，难以扩展到异构机器人语料。",
    methodSummary: "RynnBrain 在一次前向中回答绝对 temporal distance 与有符号相对位移；随机时序采样、顺序打乱和 value-isolation attention 抑制捷径。",
    architecture: "语言条件的视频编码器交错绝对/相对价值 query，两个分布式预测头输出到目标的距离与帧间位移，并保留语言验证分支。",
    data: "超过 7,000 小时异构具身数据、约 300 万条指令条件片段，覆盖不同本体、视角和任务；时间戳直接产生监督。",
    experiments: "RBM-EVAL-OOD 零样本价值评测，以及真实机器人在线和离线 RL；任务成功按论文协议独立统计。",
    novelty: "时间距离把无偏好标签的大规模语料变成统一 value target；Kendall τ 为 0.675，高于偏好监督模型 0.655 和进度模型 0.292。",
    strengths: "规模、跨本体 OOD、失败/回退敏感性和下游真实 RL 收益形成完整链条，代码仓库已公开。",
    limitations: "时间距离默认示范接近有效路径；等待、循环或不同速度轨迹会使剩余时间与任务价值不完全等价。",
    transfer: "可先把历史轨迹转成相对时间标签预训练 reward backbone，再用少量真实回报校准。",
    technique: ["随机抽取同轨迹时刻并打乱输入顺序，避免模型仅凭序列位置猜进度。", "potential-based shaping 将预测时间距离转换为密集奖励，用于 IQL 与在线 actor–critic。"],
    evaluation: ["RBM-EVAL-OOD 平均 Kendall τ=0.675；进度监督对应值为 0.292。", "真实机器人在线成功率 52.5%→72.5%，离线成功率 63.8%→82.5%；这些数字来自论文下游实验而非价值评测代理指标。"], comparison: "偏好监督 reward model、归一化进度监督、不同采样与 attention 消融。",
    reproducibilityStatus: "资源较完整", implementation: ["项目页、GitHub、模型结构和数据清洗规则可核验。"], missing: ["7,000 小时原始异构数据受各来源许可约束，完整复训成本高。"],
    figure: { number: "1", alt: "RynnValue 时序距离价值模型架构", caption: "Figure 1 · 异构轨迹、RynnBrain 与绝对/相对 temporal-distance 预测头。来源：arXiv HTML 原图。" },
  },
  {
    title: "SLIM-0.5B: Learning Action-Grounded Predictive Latents for Robot Manipulation", arxivId: "2608.09771", url: "https://arxiv.org/abs/2608.09771",
    institutions: ["Fudan University", "Beijing Academy of Artificial Intelligence", "Tsinghua University", "Renmin University of China"], signal: "用双向动作—状态预测目标训练 0.5B 紧凑控制表征。",
    tags: ["Latent Dynamics", "Compact Policy", "Real Robot"], classification: { research: "表征学习", training: "Pre-training", modalities: ["其他模态"], platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://kzz1031.github.io/slim-project-page/" }],
    motivation: "大 VLM 控制主干和像素级未来生成都把大量算力用于与当前动作无关的外观细节。",
    methodSummary: "Masked trajectory prediction 交替遮住动作或未来 latent，分别学习 inverse dynamics 与 action-conditioned forward dynamics；同一 MoT 再以 flow matching 生成动作。",
    architecture: "0.5B Mixture-of-Transformers 联结语言、观察 latent、连续动作 token 与未来槽，无像素解码器，未来预测仅在训练期塑造控制表征。",
    data: "LIBERO、LIBERO-Plus、CALVIN ABC→D；五项真实桌面操作每项 150 条示范，共 750 条。",
    experiments: "仿真长程与 OOD 基准，加真实机器人背景、光照、干扰物与布局变化；同时报告显存、时延和双预测目标消融。",
    novelty: "把动作解释观测变化与动作预测未来变化放在同一紧凑 latent 空间，避免测试时生成未来像素。",
    strengths: "参数量、延迟、显存与控制成功率共同对照，真实 OOD 不是单一干净场景。",
    limitations: "语义开放性仍受紧凑 backbone 限制；真实任务只覆盖单一平台且训练数据按任务收集。",
    transfer: "在现有 diffusion/flow policy 上增加对称的动作遮挡与未来 latent 遮挡，可作为低成本 dynamics regularizer。",
    technique: ["动作遮挡分支从前后观察恢复动作块；未来遮挡分支从当前观察和干净动作预测未来 latent。", "推理只保留观察—动作 MoT 与 flow head，未来槽不触发额外 rollout。"],
    evaluation: ["论文在 LIBERO、LIBERO-Plus、CALVIN 与五项真机任务上同时比较性能和计算量。", "完整消融分开移除 inverse/forward 目标并检查 OOD；公开结论不把模型尺寸优势换算成未报告的部署收益。"], comparison: "π0、π0.5、OpenVLA-OFT 与 WAM 类基线，以及双预测目标和模型规模消融。",
    reproducibilityStatus: "部分可复现", implementation: ["项目页、0.5B 规模、训练目标和各基准协议可核验。"], missing: ["本次检查未确认完整训练权重与真实机器人数据开放。"],
    figure: { number: "1", alt: "SLIM 紧凑动作落地 latent 交互模型", caption: "Figure 1 · 观察 latent、动作 token 与正/逆 dynamics 目标的整体流程。来源：arXiv HTML 原图。" },
  },
  {
    title: "Efficient Real-World Online Reinforcement Learning for Robot Manipulation via Centralized Training and Critic Decomposition", arxivId: "2608.09762", url: "https://arxiv.org/abs/2608.09762",
    institutions: ["Istituto Italiano di Tecnologia", "University of Genova", "TU Delft"], signal: "将连续手臂与离散夹爪拆成两个 actor，用共享分解 critic 稳定真机在线 RL。",
    tags: ["Online RL", "Human Intervention", "Hybrid Action"], classification: { research: "其他", training: "RL", modalities: ["State / Proprioception"], data: "在线数据 / 人工纠正", platforms: ["机械臂", "Humanoid", "夹爪"] },
    resources: [{ label: "项目页", url: "https://hil-harc.github.io/" }],
    motivation: "大范围随机化下，连续位姿和离散夹爪并行学习会产生非平稳性，单一视觉 critic 也容易被噪声拖垮。",
    methodSummary: "CTDE 用共享全局 critic 联合训练连续 SAC 手臂 actor 与离散 SAC 夹爪 actor；HRA 再把 Q 分成任务与抓取两头。",
    architecture: "本地 actor 异步采样，云端 learner 混合 50% 示范/干预与 50% 在线数据；部署时两个 actor 只读取各自局部输入。",
    data: "每任务以 20 条示范启动，训练中记录人工纠正和自主经验；真实任务约 160 分钟、10 Hz、单张 RTX 4090。",
    experiments: "两种真实机械臂完成网球、香蕉放置和锅复位，另在 Unitree G1 仿真做方块搬运；每项最终成功率评测 20 回合。",
    novelty: "在 HIL-SERL 管线内同时解决 hybrid-action 非平稳性与视觉价值回归，随机化范围为基线设置的约 5–25 倍。",
    strengths: "有同预算直接基线、20 回合末端评测、学习曲线、人工数据量和 critic 梯度诊断。",
    limitations: "环境复位仍为人工，奖励来自分类器或人工反馈；G1 结果仅仿真，不能当作人形真机证据。",
    transfer: "对连续运动+离散工具控制，可先共享 centralized critic，再按可分奖励建立多头价值，而不是强行统一 action type。",
    technique: ["连续与离散 SAC actor 共享 centralized multi-head critic，执行时回到 decentralized policy。", "任务奖励与抓取奖励分别回归 Q 值，降低无关视觉/本体噪声对单一 TD target 的干扰。"],
    evaluation: ["真实网球 60%→80%，香蕉 60%→90%；锅复位基线持续失败而本文成功学习。", "三项真实任务和一项 G1 仿真平均成功率由 HIL-SERL 的 40% 提至 75%；每项表格数字基于 20 次评测。"], comparison: "HIL-SERL，同一 RLPD 超参数；另做 CTDE、HRA 与 critic gradient 诊断。",
    reproducibilityStatus: "部分可复现", implementation: ["训练频率、缓冲区比例、观察/动作、随机化和硬件配置均给出。"], missing: ["完整代码与机器人复位装置未在本次检查中确认开放。"],
    figure: { number: "2", alt: "集中训练与分解 critic 的在线 RL 框架", caption: "Figure 2 · 人工纠正、异步采样、双 actor 与 reward-decomposed critic。来源：arXiv HTML 原图。" },
  },
  {
    title: "World Tokens: Enhancing Embodied Policies with Training-Time World Modeling", arxivId: "2608.09730", url: "https://arxiv.org/abs/2608.09730",
    institutions: ["JIUTIAN Research", "Zhongguancun Academy"], signal: "用训练期未来视频监督塑造少量 world tokens，部署时删除视频分支。",
    tags: ["World Tokens", "Training-only WM", "Real Robot"], classification: { research: "WAM", training: "Post-training", modalities: ["其他模态"], platforms: ["机械臂", "夹爪"] },
    motivation: "显式未来视频能提供动力学先验，但把视频生成留在控制环会增加延迟。",
    methodSummary: "World Adapter 从 VLM 特征提炼固定 token，同时条件化视频去噪器和 flow action expert；只在训练中用未来视频损失。",
    architecture: "VLM + World Adapter + action expert；视频 VAE/denoiser 与 Canny 结构锚只服务训练，部署完全移除。",
    data: "LIBERO 与 RoboTwin 训练集；Galaxea R1 Pro 四项真机操作按同一协议收集和评测。",
    experiments: "仿真基准、四项 R1 Pro 闭环任务，每策略每对象 24 次、总计 96 次；含结构锚和 world-token 数量消融。",
    novelty: "把 world modeling 蒸馏为控制 backbone 内部 token，而不是测试时生成未来帧。",
    strengths: "真机 trial 数明确，训练/推理组件边界清楚，并用多个设计因子消融。",
    limitations: "训练仍需昂贵视频去噪器；对快速接触和长时域状态的收益尚未充分分解。",
    transfer: "可把昂贵世界模型作为训练期 teacher，让小型 token adapter 保留对动作有用的预测结构。",
    technique: ["固定数量 world tokens 同时读取语言、多视图与状态，再服务视频和动作两条损失。", "Canny 首帧 latent 抑制外观复制；部署移除视频 tokenizer、denoiser、结构锚与未来目标。"],
    evaluation: ["R1 Pro 四项任务平均 76.0%，无具身预训练的直接基线 Qwen-GR00T 为 59.4%。", "每策略总计 96 次真机 trial；π0.5 的额外具身预训练被作为上下文行而非同资源公平基线。"], comparison: "无 world modeling、共享/独立 adapter、结构锚、token 数量及 Qwen-GR00T、π0.5。",
    reproducibilityStatus: "部分可复现", implementation: ["训练期与部署期模块、真实评测次数和主要超参数可核验。"], missing: ["完整训练代码、权重及真机数据未在本次检查中确认开放。"],
    figure: { number: "2", alt: "World Tokens 训练期世界建模架构", caption: "Figure 2 · World Adapter 同时连接视频去噪器与动作专家，虚线模块部署时移除。来源：arXiv HTML 原图。" },
  },
  {
    title: "Rethink Before You Execute: Adaptive Execution for World Action Models", arxivId: "2608.09492", url: "https://arxiv.org/abs/2608.09492",
    institutions: ["论文 arXiv 版本未标注机构"], signal: "依据执行后任务进度决定继续复用动作块还是提前重规划。",
    tags: ["WAM", "Adaptive Execution", "Progress Monitor"], classification: { research: "WAM", training: "Post-training", modalities: ["State / Proprioception"], platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "固定执行 action chunk 前缀忽略不同任务阶段的可靠性差异：简单阶段浪费重规划，困难阶段又可能执行过头。",
    methodSummary: "Recurrent Progress Monitor 读取观察、指令、剩余动作和执行历史；Adaptive Execution Protocol 以在线校准阈值决定继续或丢弃剩余块。",
    architecture: "轻量 RPM 附着在原 WAM 外部，任务级校准系数慢更新、episode 级系数快更新，无需重训基础策略。",
    data: "复用基础 WAM 的示范轨迹，以归一化时间 u/T 监督进度；LIBERO、RoboTwin 与三项真实任务。",
    experiments: "三项真机任务各 30 次，并在 LIBERO/RoboTwin 多 backbone 上测成功率、WAM 调用次数、延迟和组件消融。",
    novelty: "把是否重规划从动作不确定性代理改成已执行结果的进度判断，并用双时间尺度校准部署偏差。",
    strengths: "同一 backbone 插件式对照、真机次数和推理成本齐全，还构造回文轨迹验证时间标签何时失效。",
    limitations: "u/T 只适用于进度单调任务；循环、回退和视觉别名需要阶段分解或语义进度。",
    transfer: "先为已有 chunk policy 加只读进度监控器，在不改策略权重的情况下试验动态执行时域。",
    technique: ["先无条件执行最短前缀，再比较候选后续动作带来的预测进度增量与校准阈值。", "离线任务校准加在线双时间尺度更新，用目标成功率纠正训练—部署偏差。"],
    evaluation: ["简单真机任务在保持成功率时减少 26.9% WAM 调用；困难任务成功率提高 13.3 个百分点。", "单次 RPM 决策仅占完整 WAM 推理的小部分；论文分别报告 LIBERO、RoboTwin 与 Motus 即插即用结果。"], comparison: "固定执行长度、动作熵/一致性代理、无离线校准、无在线适配及多种 WAM backbone。",
    reproducibilityStatus: "部分可复现", implementation: ["RPM 输入、阈值规则、在线更新和真实评测协议已给出。"], missing: ["作者机构未在 arXiv 版本标注；完整代码未在本次检查中确认开放。"],
    figure: { number: "2", alt: "TempoWAM 进度驱动的自适应执行协议", caption: "Figure 2 · RPM、校准阈值与继续执行/重规划分支。来源：arXiv HTML 原图。" },
  },
  {
    title: "JEPA-WAM: Learning Vision-Language-Action Policies with Joint-Embedding World Modeling", arxivId: "2608.09381", url: "https://arxiv.org/abs/2608.09381",
    institutions: ["XYZ Embodied AI（论文仅披露实习归属）"], signal: "在冻结 V-JEPA 空间预测当前—未来联合目标，让转移监督直接塑造动作 backbone。",
    tags: ["Latent WAM", "V-JEPA", "OOD Generalization"], classification: { research: "WAM", training: "Post-training", modalities: ["其他模态"], platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://spritewithoutice.github.io/JEPA_WAM/" }],
    motivation: "像素 WAM 部署昂贵，而把未来压成少量 global latent 又可能丢失局部对应关系。",
    methodSummary: "冻结 V-JEPA 编码当前与未来帧的联合目标，共享 predictor 同时学习稠密转移与动作 flow；也可插入预训练 π0.5。",
    architecture: "300M V-JEPA 2.1 编码器、共享 transformer predictor 与 DiT action head；训练预测 joint current–future patch target，部署不生成视频。",
    data: "LIBERO/LIBERO-Plus、RoboTwin 2.0 20 个任务，以及五项真实双臂任务的 ID/OOD 条件。",
    experiments: "三类基准与真机规范化完成分；比较 future-only、global compression、共享/分离 predictor 和 pretrained VLA 接入。",
    novelty: "联合当前—未来 target 显式表示变化关系并保留 patch 对应，动作从同一预测器表征读取。",
    strengths: "跨仿真、真实 OOD、probe 与结构消融，且在从零策略和预训练 π0.5 两种初始化上复现趋势。",
    limitations: "依赖 V-JEPA 表征偏好；机构披露不完整，真机域仍集中于桌面双臂。",
    transfer: "将自监督视频 backbone 的 joint-transition target 作为现有 VLA 的辅助头，部署时移除 target encoder。",
    technique: ["每个视角独立编码后按固定相机顺序拼接；未来偏移在 LIBERO 为 31、RoboTwin 为 50。", "共享 predictor 同时接受语言、当前 token 与动作 query；动作 flow loss 和 joint-target cosine loss共同更新。"],
    evaluation: ["LIBERO-Plus 79.2%，π0.5 接入版为 86.3%。", "真实五任务中，基础 JEPA-WAM ID/OOD 为 59.8%/54.2%；π0.5 接入后为 90.3%/84.7%。"], comparison: "π0、π0.5、VLA-JEPA、future-only target、global target 与 predictor 解耦消融。",
    reproducibilityStatus: "部分可复现", implementation: ["项目页、target 构造、动作时域与 probe 诊断可核验。"], missing: ["论文未完整列出机构；训练权重与真机数据开放情况未确认。"],
    figure: { number: "3", alt: "JEPA-WAM 联合嵌入世界建模", caption: "Figure 3 · V-JEPA 联合当前—未来目标、共享预测器与动作生成。来源：arXiv HTML 原图。" },
  },
  {
    title: "Adaptation of Generalist Robot Policies with Minimal Data", arxivId: "2608.11363", url: "https://arxiv.org/abs/2608.11363",
    institutions: ["Carnegie Mellon University"], signal: "用一条示范锚定预训练 VLA，再以 residual 在线 RL 自主改进。",
    tags: ["Minimal Data", "Residual RL", "Real Robot"], classification: { research: "VLA", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://minimal-data-adaptation.github.io" }],
    motivation: "零样本策略常无法在稀疏奖励下探索到首次成功，但为每个新任务重新收集大规模示范也不可扩展。",
    methodSummary: "MiDAS 先用单/少量示范 BC 锚定预训练策略，再训练 value-based residual policy，只在基础动作附近探索。",
    architecture: "冻结或缓慢更新的 VLA 产生 base action，residual actor 在其动作云附近优化；critic 使用自主交互回报。",
    data: "LIBERO、RoboCasa 的一条至少量示范设置；YAM 双臂真机以一条示范启动并进行 6 小时在线交互。",
    experiments: "仿真结果跨 3 个随机种子；真机两任务各 15 次，混合 ID/OOD 物体位置与朝向。",
    novelty: "把 single-demo BC 视为探索锚点而非最终策略，用 residual 参数化保持预训练动作先验。",
    strengths: "一示范极限、自治交互、位置/语言/对象扰动和 residual 设计消融均有直接对照。",
    limitations: "仍需要可在线判定的任务奖励与数小时机器人占用；只评估两项真机任务。",
    transfer: "当新任务零样本成功率为零时，先用一条示范建立可达动作邻域，再把探索约束为 residual。",
    technique: ["Stage I 对单条示范做 BC；Stage II 在 base action 上叠加受限 residual，并以 value-based RL 更新。", "动作云距离分析验证 residual 没有立即偏离预训练策略可行区域。"],
    evaluation: ["真机单示范适配在两项任务上各做 15 次混合 ID/OOD rollout。", "LIBERO 与 RoboCasa 按 3 seeds 报告均值/标准差，并覆盖外观、语言、对象交换、形状与 5/10/20 cm 位置扰动。"], comparison: "单示范 BC、直接全量 RL、不同 residual/anchor 变体与预训练策略零样本。",
    reproducibilityStatus: "部分可复现", implementation: ["项目页、阶段划分、主要超参数和真机协议可核验。"], missing: ["真实环境、奖励检测器与完整交互数据未确认公开。"],
    figure: { number: "1", ext: "jpg", alt: "MiDAS 单示范到在线强化学习流程", caption: "Figure 1 · 单示范 BC 锚定与 residual 在线 RL 两阶段适配。来源：arXiv HTML 原图。" },
  },
  {
    title: "Flex-π: A Multi-Stream World-Action Model with Compute Flexibility", arxivId: "2608.10860", url: "https://arxiv.org/abs/2608.10860",
    institutions: ["University of Washington", "Allen Institute for AI"], signal: "把 RGB、点图、DINO 语义和动作放入同一 latent/MoT，并按需关闭视觉流。",
    tags: ["Multi-stream WAM", "3D Geometry", "Compute Flexibility"], classification: { research: "WAM", training: "Pre-training", modalities: ["Point Cloud / 3D"], platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://flex-pi.github.io/" }],
    motivation: "多数 WAM 只预测为像素重建训练的 RGB latent，缺少几何与对象语义；全流生成又不适合每个部署预算。",
    methodSummary: "同一冻结视频 VAE 编码 RGB 与 pointmap，DINO 提供对象语义；多流 MoT 联合去噪，stream dropout 让单一 checkpoint 支持 action-only 到全生成。",
    architecture: "6B MoT 为 RGB、3D、语义与动作配置独立 expert 和共享 cross-stream attention；per-stream mask 控制推理计算。",
    data: "AGIBOT World 预训练，RoboTwin 2,500 clean + 25,000 randomized 示范，LIBERO 与五项 YAM 双臂真机少样本任务。",
    experiments: "RoboTwin 50 任务、LIBERO 四套件和五项接触密集真机；真机按任务做 10–20 次并用部分得分 rubric。",
    novelty: "无需新传感器或 pointmap 专用 VAE，即可把几何/语义训练信号接入 WAM，且部署可裁剪视觉流。",
    strengths: "性能—延迟前沿、少示范曲线、OOD 与深度输入消融覆盖较全。",
    limitations: "6B 训练成本高；pointmap 来自估计器，几何噪声与真实深度缺失仍会传入策略。",
    transfer: "可先验证现有视觉 VAE 对几何图的重建能力，再通过 stream dropout 训练同一策略适配多种算力档。",
    technique: ["RGB、pointmap、DINO semantic map 映射到同一 VAE latent，并与动作 token 在 MoT 中联合 flow matching。", "cross-modality forcing 防止某一流成为捷径；action-only 推理不生成视觉流。"],
    evaluation: ["RoboTwin 50 任务与 LIBERO 均报告每套件结果，真实 YAM 任务覆盖精细接触和长时域。", "论文报告真机相对强基线可达 2–7 倍，但公开卡片保留原始 rubric 边界，不把部分得分表述为二元成功率。"], comparison: "π0.5、WAM/VLA 基线、不同视觉流、stream dropout、深度输入与 action-only/full 模式。",
    reproducibilityStatus: "部分可复现", implementation: ["项目页、流定义、推理阶梯和完整训练超参数表可核验。"], missing: ["6B 权重及 AGIBOT World 预训练复现成本较高。"],
    figure: { number: "2", alt: "Flex-pi 多流世界动作模型", caption: "Figure 2 · RGB、几何、语义与动作流在 MoT 中的联合训练和可裁剪推理。来源：arXiv HTML 原图。" },
  },
  {
    title: "G0.5: One Autoregressive Stream for Robot Reasoning and Action", arxivId: "2608.11739", url: "https://arxiv.org/abs/2608.11739",
    institutions: ["Galaxea AI"], signal: "让同一自回归 VLM 权重交错生成推理 token 与跨本体动作 token。",
    tags: ["Autoregressive VLA", "CoT", "Cross-Embodiment"], classification: { research: "VLA", training: "Pre-training", modalities: ["其他模态"], data: "跨本体数据", platforms: ["机械臂", "轮式底盘", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://opengalaxea.github.io/G05/" }],
    motivation: "VLM+独立 flow action expert 让语言主干只做上下文编码，推理与动作没有统一生成接口。",
    methodSummary: "一个 decoder 在同一 next-token 目标下生成 CoT 与动作码；ActionCodec 学习跨本体词表，视觉记忆注入数秒历史。",
    architecture: "VLM 接收多视图、指令、本体状态和 embodiment id，交错输出可选 CoT 与 action codes；active-part token 省略不活动控制组。",
    data: "多机器人预训练数据与 VQA 混合；R1-Lite/R1-Pro 真机微调、DROID 后训练、BEHAVIOR 50 项长程任务等七类评测。",
    experiments: "真实机器人微调、DROID 未见环境迁移、语言跟随、LIBERO、RoboTwin、SimplerEnv 和可直接接入的 RL 后训练。",
    novelty: "跨本体动作 tokenizer、原生 CoT 与视觉 memory 都位于单一 AR 流，不再依赖分离 action expert。",
    strengths: "覆盖真实、仿真、长时域、语言操控与 RL；基线和任务拆解消融较完整。",
    limitations: "自回归动作有串行延迟，论文数据混合的逐来源规模与许可仍不足以完整复训。",
    transfer: "可将本体差异压入可学习 ActionCodec，并用 active-part mask 控制每个机器人实际输出维度。",
    technique: ["ActionCodec 把异构连续动作映射到共享离散词表，再解码回各本体控制量。", "视觉记忆把多秒历史送入视觉编码器；CoT、grounding 与动作共享 next-token objective。"],
    evaluation: ["R1 真机微调平均 76.7%，π0.5 为 53.3%，GR00T-N1.7 为 24.4%。", "BEHAVIOR 50 项长程任务 31.4%，π0.5 为 26.3%；DROID 后训练到未见环境/对象为 82.5%。"], comparison: "π0.5、GR00T-N1.7、BEHAVIOR 优胜方案、flow action head 与 CoT/visual-memory 消融。",
    reproducibilityStatus: "部分可复现", implementation: ["项目页、ActionCodec、训练目标和七类评测协议可核验。"], missing: ["完整预训练数据配比、权重与训练代码未在本次检查中确认全部开放。"],
    figure: { number: "3", alt: "G0.5 单一自回归推理动作流", caption: "Figure 3 · 统一自回归训练、ActionCodec 与视觉记忆的模型结构。来源：arXiv HTML 原图。" },
  },
  {
    title: "StellaVLA: In-Context Structured Demonstration for Generalizable Vision-Language-Action Models", arxivId: "2608.11671", url: "https://arxiv.org/abs/2608.11671",
    institutions: ["Stelledge"], signal: "把检索到的一条示范转换成计划、子目标和 2D/3D 动作理由，作为测试时上下文。",
    tags: ["In-Context Learning", "Structured Demonstration", "Human-to-Robot"], classification: { research: "VLA", training: "Post-training", modalities: ["Point Cloud / 3D"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://stelledge.com/blog/stellavla" }],
    motivation: "像素级示范提示容易让策略照搬轨迹，在视角、对象和场景变化时产生 behavioral inertia。",
    methodSummary: "离线管线自动抽取 task plan、subgoal、keyframe、2D 轨迹和 3D motion；双专家训练动作与语言理由，推理仅保留 action expert。",
    architecture: "Qwen3-VL-4B 编码当前观察和 KV-cached 结构化示范；action MLP 回归动作块，spatial-language expert 只在训练期提供辅助监督。",
    data: "LIBERO/LIBERO-Plus、VLA-Arena，以及真实机器人、human-hand 与 XR 示范构成的跨本体上下文池。",
    experiments: "模拟 OOD 榜单与真实跨本体 in-context 测试；消融示范内容、2D/3D motion、检索和 spatial-language loss。",
    novelty: "不是只把轨迹当提示，而是把同一动作转为可复用的阶段理由，并在推理前缓存。",
    strengths: "既检验上下文内容又检查去掉语言专家后的延迟；人/机器人/XR 来源形成迁移对照。",
    limitations: "结构化理由依赖离线 VLM 生成与规则校验；论文未给所有真机条件的统一重复次数。",
    transfer: "可先离线把演示分段并生成 2D/3D steering command，再把语言头限制为训练期正则。",
    technique: ["每个时间步绑定 subtask label 与 segment-level rationale；2D path dropout 和 context dropout 匹配部署缺失。", "全量微调 Qwen3-VL-4B 30k steps、global batch 128；推理不自回归解码语言理由。"],
    evaluation: ["LIBERO 平均 98.8%，LIBERO-Plus 85.1%；VLA-Arena 总分 0.63，π0.5 为 0.44。", "去掉 3D motion 后 LIBERO 均值 97.8%，去掉 2D gripper path 为 97.3%；真机结论仅按论文报告的跨本体协议描述。"], comparison: "π0.5、LingBot-VLA、原始示范提示、移除 2D/3D 字段与不同示范来源。",
    reproducibilityStatus: "部分可复现", implementation: ["项目页、结构化字段、30k-step 配置和主要消融可核验。"], missing: ["离线标注管线、完整真机 trial 数和训练数据未全部开放。"],
    figure: { number: "1", alt: "StellaVLA 结构化示范上下文流程", caption: "Figure 1 · 一条示范的计划、子目标、空间动作与动作专家推理流程。来源：arXiv HTML 原图。" },
  },
  {
    title: "Learning Loco-Manipulation From SMPC Demonstrations With Sparse Offline-to-Online RL", arxivId: "2608.12063", url: "https://arxiv.org/abs/2608.12063",
    institutions: ["RAI Institute", "Technical University of Munich", "ETH Zurich"], signal: "用快速调参的 SMPC 在仿真生成专家数据，再用纯稀疏奖励离线到在线 RL 超越 teacher。",
    tags: ["Loco-Manipulation", "Sparse RL", "SMPC"], classification: { research: "其他", training: "RL", modalities: ["State / Proprioception"], data: "合成 / 仿真数据", platforms: ["Humanoid", "机械臂"], deployment: "Sim2Real" },
    resources: [{ label: "项目页", url: "https://pages.rai-inst.com/smpc2rl/" }],
    motivation: "全身移动操作的 dense reward 设计缓慢且任务特定；纯 sparse reward 又无法从零探索。",
    methodSummary: "SMPC 只在仿真充当自动 teacher 生成离线数据，modified FastTD3 混合离线/在线 replay，以稀疏成功奖励继续优化。",
    architecture: "高层策略输出底盘速度、手臂关节、躯干高度/俯仰增量；冻结 ReLIC 低层控制器负责全身稳定。",
    data: "SMPC 可约 1M samples/hour 生成，任务数据最多约 4M samples；训练评测使用 5 个随机种子。",
    experiments: "仿真覆盖 Spot 推、滚、扶轮胎与 G1 推箱等任务；策略部署到带臂 Spot 和 G1 真机。",
    novelty: "把 MPC 从在线控制器改成离线探索引导，让无人工 shaping 的 RL 用真实 sparse objective 超越 teacher。",
    strengths: "不同形态、5 seeds、数据规模曲线和 teacher/RL 对照较强，并确有两类硬件部署。",
    limitations: "论文未报告硬件成功率或独立 trial 数；因此量化结论主要来自仿真，真机仅证明可部署。",
    transfer: "对难以写 dense reward 的全身任务，可先用可解释优化器填充 replay，再让 off-policy RL 只优化最终目标。",
    technique: ["modified FastTD3 先用 SMPC 数据离线启动，再进入在线仿真采样；奖励仅在任务成功时触发。", "高低层解耦让同一学习框架跨 Spot 与 G1，本体差异主要落在动作维度和低层稳定器。"],
    evaluation: ["主要表格以 5 seeds 比较 SMPC teacher、BC、纯在线 RL 与 offline-to-online RL，并报告训练数据规模消融。", "硬件视频覆盖 Spot 和 G1，但无成功次数/判据；本站不把这些部署演示转换为成功率结论。"], comparison: "SMPC teacher、behavior cloning、无离线数据 RL、不同 expert dataset 规模与 RL 更新策略。",
    reproducibilityStatus: "部分可复现", implementation: ["控制层级、TD3/SMPC 超参数表和数据生成速率可核验。"], missing: ["真机独立重复次数、成功判据和完整环境未报告。"],
    figure: { number: "1", alt: "SMPC 示范到稀疏离线在线强化学习流程", caption: "Figure 1 · SMPC 数据生成、稀疏 RL 学习与硬件部署三阶段。来源：arXiv HTML 原图。" },
  },
  {
    title: "Attention from Action, for Action: Emergent Visual Bottlenecks for Policy Learning", arxivId: "2608.13422", url: "https://arxiv.org/abs/2608.13422",
    institutions: ["KTH Royal Institute of Technology", "University of Freiburg", "Universität Hamburg"], signal: "只靠动作监督学习随任务阶段移动的 ROI，不依赖 gaze、框或 VLM 标签。",
    tags: ["Visual Bottleneck", "ROI", "Imitation Learning"], classification: { research: "表征学习", training: "BC", modalities: ["Mask / Segmentation"], data: "数据增强", platforms: ["机械臂", "夹爪"] },
    motivation: "固定在末端执行器附近的 crop 无法覆盖随阶段变化的目标、工具和落点；外部空间标签又昂贵。",
    methodSummary: "Seeker 从冻结 DINO 特征出发，以任务和本体状态 query 迭代聚合视觉证据，从动作预测反向涌现 ROI。",
    architecture: "query—feature cross-attention 多轮更新后输出 ROI；同一 ROI 可驱动 RGB crop、mask-guided 背景增强与点云过滤，再交给下游策略。",
    data: "仿真多任务分别使用 25/50/100 demonstrations；真机三项操作共享 Seeker 与下游策略训练示范。",
    experiments: "仿真 3 seeds；xArm7 真机三任务在 ID、光照和背景变化下评测，每条件每任务 20 次。",
    novelty: "ROI 由动作损失而非额外空间标签学习，并显式依赖任务与当前状态推进。",
    strengths: "真机 OOD、样本效率、crop/mask/point-cloud 三种接口和 ROI 条件消融齐全。",
    limitations: "冻结 DINO 对透明、反光与精细接触的表示仍可能不足；ROI 会丢弃区域外上下文。",
    transfer: "可把学习到的 ROI 作为统一中间接口，同时控制视觉裁剪、背景增强和 3D 过滤。",
    technique: ["任务与 proprioception 初始化 query，反复读取 DINO feature map 并更新 ROI。", "策略动作损失是唯一空间监督；mask-guided overlay 保留 ROI 内像素并随机化背景。"],
    evaluation: ["真机 ID 平均成功率 76.7%，最佳基线 48.3%；光照/背景变化下为 60.0%，最佳基线 20.0%。", "仿真 100-demo 设置为 62.6%，最佳对照 42.6%；另报告 ROI conditioning、crop 与分辨率消融。"], comparison: "无裁剪、随机增强、末端投影 crop、外部 ROI 与 Seeker 的 task/state conditioning 消融。",
    reproducibilityStatus: "资源较完整", implementation: ["论文提供 Code 链接、训练细节、真实任务表与 ROI 可视化。"], missing: ["真实机器人硬件复现仍依赖标定和下游策略实现。"],
    figure: { number: "1", alt: "Seeker 从动作监督学习视觉 ROI", caption: "Figure 1 · task/state query 从冻结视觉特征中迭代形成控制相关 ROI。来源：arXiv HTML 原图。" },
  },
  {
    title: "ContactGuard: Pre-Contact Execution Monitoring with Action-Conditioned Latent World Models", arxivId: "2608.13438", url: "https://arxiv.org/abs/2608.13438",
    institutions: ["Vanderbilt University", "The University of Sydney", "Australian Centre for Robotics"], signal: "在接触前滚动策略已提出的动作块，以预测未来 latent 决定是否中止。",
    tags: ["Failure Detection", "Latent World Model", "Contact-rich Manipulation"], classification: { research: "WM", training: "Post-training", modalities: ["State / Proprioception"], data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "腕部相机能看清接触，却常在推、夹偏或滑落发生后才检测到失败。",
    methodSummary: "JEPA 风格世界模型从无标签轨迹预测动作条件未来多视图 latent，小型线性 probe 用少量标签判断失败；接触前阈值触发 abort。",
    architecture: "冻结视觉 encoder 编码外部/腕部视图，latent predictor 按计划 action chunk rollout；probe 读取预测 post-contact latent，不修改原策略。",
    data: "无标签机器人轨迹训练世界模型，较小的带成功/失败标签抓取集训练 probe；评测含四类接触密集真实场景。",
    experiments: "离线 held-out AUC、当前 latent/原始动作/腐化动作消融、不同 rollout horizon 与 live robot pre-contact abort。",
    novelty: "不是搜索候选动作，而是验证黑盒策略已经提出的单一动作块，且在接触发生前作出决定。",
    strengths: "世界模型、probe 和阈值在 live rollout 前冻结，避免在线调参污染；多种因果消融检查未来预测是否真有增益。",
    limitations: "只会中止不会生成修复动作；阈值按任务设定，live 试验规模仍有限。",
    transfer: "可在不重训基础策略时增加 veto 层，先从高风险接触事件定义 anchor 与预测 horizon。",
    technique: ["先定位 action chunk 内的预计接触事件，从接触前 observation rollout 到预测 post-contact latent。", "线性 probe 与 world model 分开训练；部署仅比较 failure probability 与每任务阈值。"],
    evaluation: ["论文报告 live real-robot 闭环 abort，并将 world model、probe 和阈值预先冻结。", "预测未来 latent 优于当前观察与原始动作直接分类；腐化动作使性能下降，支持 monitor 使用了 action consequence。"], comparison: "当前 latent probe、raw-action classifier、corrupted-action rollout、无 proprioception 与不同预测时域。",
    reproducibilityStatus: "部分可复现", implementation: ["模型分层、训练数据角色、AUC 协议和 RTX 5090 推理时间表可核验。"], missing: ["完整代码/数据与更大规模现场错误恢复评测未确认开放。"],
    figure: { number: "2", alt: "ContactGuard 接触前动作后果监控", caption: "Figure 2 · 多视图 latent rollout、失败 probe 与 pre-contact abort 接口。来源：arXiv HTML 原图。" },
  },
];

export const paperDaily20260814: Paper[] = entries.map(makePaper);
