import type { Paper } from "./site-data";

const figure = (id: string, number: string, alt: string, caption: string): Paper["figures"] => [{
  src: `/report-assets/2026-08-10/${id}-fig${number}.png`, alt, caption,
}];

export const paperDaily20260810: Paper[] = [
  {
    rank: 1,
    title: "ω-0: A Latent Predictive World Action Model for Concurrent Humanoid Loco-Manipulation",
    arxivId: "2608.06375", url: "https://arxiv.org/abs/2608.06375",
    institutions: ["MARS Lab, Nanyang Technological University", "Peking University", "Beijing Academy of Artificial Intelligence", "HKUST (Guangzhou)"],
    signal: "用未来视觉 latent 约束全身动作 latent，让人形机器人在移动、调整躯干和双手操作之间连续协同，而不是把走路和操作拆成两个控制器。",
    tags: ["Humanoid WAM", "Whole-body Control", "Real Robot"],
    classification: { research: "WAM", training: "Pre-training", modalities: ["Depth / RGB-D", "State / Proprioception"], data: "跨本体数据", platforms: ["Humanoid", "灵巧手"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://gentlefress.github.io/OMEGA-0_page/" }],
    motivation: "现有人形策略常把 locomotion 与 manipulation 分开，视频型 WAM 又不直接输出可执行的全身控制量；两者都难覆盖边走边拿、边调整姿态边操作的家庭任务。",
    methodSummary: "三阶段学习：先把全身运动离散成 FAST token 训练 action VLM，再用 V-JEPA 未来特征与动作扩散联合预训练，最后在 ω-HOME 真机轨迹上微调统一策略。",
    architecture: "Qwen3-VL-2B 提供动作语义前缀；V-JEPA、T5、状态编码和 motion/video queries 经 joint predictor 融合；Action DiT 直接去噪 SONIC 控制器兼容的 66 维全身动作 latent。",
    optimization: "Pre-training + real-robot post-training；未来分支只预测紧凑视觉 embedding，不重建像素视频。训练时加入 receding-horizon temporal context，部署时以少步 DDIM 滚动生成动作块。",
    data: "公开阶段使用 ARCTIC、Xperience 10M、Motion-X 等人体/动作数据；ω-HOME 含 40+ 小时、11 个家庭任务、约 200 条/任务，共 2,220 条同步多视图、深度、SMPL、状态与动作 latent 轨迹。",
    experiments: "11 个真机任务、每种方法每任务 10 次：ego/omni 版本成功率 79.1%/81.8%，对比 π0.5 的 44.5% 与 DiT4DiT 的 43.6%；完整消融覆盖状态、动作语义、未来 latent、RTC 和图像编码器。",
    novelty: "相比将视频生成作为中间控制通路的 WAM，ω-0 用轻量未来 latent 作为辅助目标并直接生成控制器动作；相对 π0.5，omni 设置成功率提高 37.3 个百分点。",
    experimentDetails: [{ title: "11 项真机全身任务与组件消融", setup: "同一模型覆盖 11 个家庭 loco-manipulation 任务；每任务 10 trials，按成功率、41 分子任务得分和首次不可恢复失败前的进度评估。", comparisons: "ACT、Diffusion Policy、π0.5、InternVLA-M1、EgoVLA、DiT4DiT、ψ0 与逐组件消融。", results: ["ω-0-ego/omni 成功率为 79.1%/81.8%，明显高于 π0.5 的 44.5%。", "去掉状态、VLM prefix、未来视频 query 或 RTC 后分别降至约 60.9%、66.4%、64.5% 和 71.8%。", "用偏视频生成的 Wan encoder 代替 V-JEPA 编码当前帧约为 63.6%，说明离线未来重建更准并不等于控制更好。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、完整任务定义、ω-HOME 统计、模型组成和主消融可核验。"], implementation: ["Qwen3-VL-2B、冻结 V-JEPA 与 T5；64 维动作 latent 加双手标量构成 66 维动作。", "三阶段均使用 8 张 H100；Stage 3 混合 11 任务进行单模型微调。"], missing: ["完整代码、权重与 ω-HOME 下载在本次检查时尚未确认公开；真机每任务仅 10 次。"] },
    deepDive: { lead: "核心不是先生成视频再反推动作，而是让动作 query 能读取未来视觉状态的紧凑预测，从而在控制器 latent 空间直接完成全身闭环。", sections: [{ title: "动作语义与未来状态如何汇合", paragraphs: ["Stage 1 用全身 FAST tokenizer 把连续 SMPL/动作片段转成 token，使 VLM 学到语言、图像与全身运动的对应关系。", "Stage 2 让 motion query 关注受未来 V-JEPA 特征监督的 video query，再由 Action DiT 条件生成动作 latent；Stage 3 才把该表征对齐到真机家庭任务。"] }, { title: "部署闭环", paragraphs: ["SONIC 仿真回放把人体运动筛成控制器可跟踪的 latent，过滤不可执行轨迹；真机使用同步状态和多视图观察进行 receding-horizon 执行。", "消融表明状态、动作语义和未来预测都不是装饰项，而 RTC 主要减少滚动执行中的迟疑与不连续修正。"] }], equations: [{ name: "未来视觉辅助目标", expression: "L = L_action + λ · L_future-latent", explanation: "动作扩散是主目标，未来视觉 latent 作为共享 query 的预测约束；论文不要求测试时生成完整视频。" }], experimentReading: ["结果覆盖 11 项真机任务与多类基线，证据强于单任务演示。", "测试次数仍是每任务 10 次，细小差异不宜过度解读。"], reflections: [] },
    strengths: "真机任务覆盖面、全身模型对照和组件消融较完整，且把人体数据、控制器 latent 与视觉预测连成同一训练链。",
    limitations: "依赖 SONIC 控制器与特定全身 latent 接口；模型尚未证明跨另一种人形硬件直接迁移，真机统计量也有限。",
    transfer: "做人形 WAM 时可把未来预测降为 latent 辅助监督，把控制输出留在稳定的低层控制器空间，并用 RTC 缓解动作块滚动时的分布偏移。",
    figures: figure("2608.06375", "2", "ω-0 三阶段全身 world-action model 架构", "Figure 2 · 全身 action VLM、未来视觉 latent 与 Action DiT 的三阶段训练流程。图片来自 arXiv HTML 原图。"),
  },
  {
    rank: 2,
    title: "World-to-Wrist: Task-Conditioned Future Wrist Modeling for Fine-Grained Robot Manipulation",
    arxivId: "2608.05369", url: "https://arxiv.org/abs/2608.05369",
    institutions: ["HKUST", "National University of Singapore", "Nanyang Technological University", "Wuhan University", "Sun Yat-sen University", "Xidian University", "Southeast University"],
    signal: "把未来腕部视角当成动作前的局部预测目标，迫使 VLA 关注夹爪附近即将发生的接触、对齐与遮挡变化。",
    tags: ["VLA", "Future Wrist", "Fine-grained Manipulation"],
    classification: { research: "VLA", training: "Post-training", modalities: ["其他模态"], data: "其他数据方法", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://yyyyu120.github.io/W2-VLA/" }],
    motivation: "把主视角和腕部视角并列编码，未必能让模型理解后者对精细接触更关键；插接、遮挡放置等任务需要预测夹爪附近下一阶段会看到什么。",
    methodSummary: "W²-VLA 用结构化 W²-CoT 塑造固定长度 task-conditioned query，再结合腕部历史预测未来腕部 latent；预测结果通过 adapter 注入 flow-matching 动作头，推理时不解码 CoT。",
    architecture: "Qwen3-VL-4B-Instruct + 32 个上下文 query；冻结 V-JEPA 2.1 ViT-L/384 编码腕部历史，4 层 predictor 预测 16 个未来 latent token，DiT 动作头生成动作块。",
    optimization: "以结构化阶段/物理转移/腕部证据做辅助自回归监督，同时训练 future-wrist latent 与动作 flow matching；测试时只保留 latent 接口，避免显式 CoT 延迟。",
    data: "LIBERO 1,693 条/40 任务；RoboTwin 2,500 条/50 任务；CoBoT Magic 三项真机任务各 100 条遥操作示范。",
    experiments: "LIBERO 98.5%，RoboTwin Easy/Hard 60.71%/18.21%；三项真机标准/OOD 平均 70.0%/52.22%，分别较 VLA-JEPA 高 15.56/14.44 个百分点。",
    novelty: "相对只做通用视觉未来预测的 VLA-JEPA，方法把预测位置限定到 action-proximal wrist，并用任务 query 连接当前语义与未来局部变化。",
    experimentDetails: [{ title: "仿真、真机与延迟消融", setup: "LIBERO、RoboTwin 以及 CoBoT Magic 的清桌、遮挡放置和双臂插接；真机每任务 30 次标准加 30 次 OOD。", comparisons: "π0、OpenVLA-OFT、VLA-JEPA 及去掉 wrist predictor、CoT、query 数量等变体。", results: ["LIBERO 98.5%，最佳对照约 97.2%；RoboTwin Easy 60.71%，对照 52.92%。", "真机 OOD 平均 52.22%，双臂插接 OOD 为 33.33%，π0 为 10.0%。", "去掉 wrist predictor 为 97.5%，去掉 CoT 为 98.0%；显式 CoT 解码超过 1.5 秒，而 16 query 预测约 110.58 ms。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、数据配比、主干/预测器结构、真机协议和消融可核验。"], implementation: ["总参数约 4.97B；V-JEPA 冻结，wrist predictor 4 层；动作块 16 步。"], missing: ["代码和权重是否完整开放仍需后续确认；真机只覆盖单一双臂平台。"] },
    deepDive: { lead: "这篇工作的有效约束是‘预测与动作最相关的未来视角’，而不是把所有相机都交给同一个视觉编码器自行分工。", sections: [{ title: "Task-conditioned latent interface", paragraphs: ["结构化标注包含 Subtask、Reasoning 与 Wrist 三字段，但其作用发生在训练阶段：query hidden state 被塑造成当前任务进度和腕部证据的压缩接口。", "预测器读取 query 与腕部历史，预测未来腕部 latent；adapter 再把这一 future-aware context 送给动作头。"] }, { title: "为什么不在推理时说出 CoT", paragraphs: ["显式生成长推理会打断闭环，且文本可能与低层控制目标冲突；本文把 CoT 留在辅助监督中，测试时只消费 latent。", "腕部-only 配置优于同时预测主视角，说明监督位置的选择比无差别增加预测目标更重要。"] }], experimentReading: ["标准/OOD 各 30 次的真机协议对泛化判断较有帮助。", "RoboTwin Hard 的绝对成功率仍低，未来腕部预测没有解决所有复杂双臂难点。"], reflections: [] },
    strengths: "真实双臂精细任务、OOD 条件、延迟与 query/视角消融构成较完整证据链。",
    limitations: "结构化 W²-CoT 需要离线 VLM 标注与规则校验；收益是否迁移到无腕部相机或不同手眼布局尚不明确。",
    transfer: "可把 task-conditioned query 当作连接 VLM 与局部未来预测器的固定带宽接口，并优先预测最接近动作发生处的传感器 latent。",
    figures: figure("2608.05369", "1", "W2-VLA 未来腕部建模总览", "Figure 1 · 当前多视图、任务 query、腕部历史和未来腕部 latent 如何共同约束动作。图片来自 arXiv HTML 原图。"),
  },
  {
    rank: 3,
    title: "Robust-WAM: Robustifying World Action Models via Semantic Foresight",
    arxivId: "2608.05903", url: "https://arxiv.org/abs/2608.05903",
    institutions: ["HKUST (Guangzhou)", "Beihang University", "Huawei Foundation Model Department"],
    signal: "用未来帧的稳定语义特征监督动作分支，让 WAM 在光照变化下保留对未来场景内容的判断，而不是只拟合像素外观。",
    tags: ["WAM", "Semantic Foresight", "Robustness"],
    classification: { research: "WAM", training: "Post-training", modalities: ["其他模态"], data: "数据增强", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://haodong-yan.github.io/robust-wam-project-page/" }],
    motivation: "WAM 的视频分支可预测未来像素，但动作分支仍可能依赖颜色和背景捷径；训练光照一变，控制性能会远快于干净集下降。",
    methodSummary: "在 Action DiT 的每个未来步加入 query，将其输出与冻结 DINOv3 对应未来真值帧的 CLS 特征对齐；query 与动作 token 共享时间位置编码。",
    architecture: "原视频 DiT 和 flow-matching 目标保持不变；语义 teacher、对齐头只在训练时存在，推理时移除，动作序列长度以少量 query 增加。",
    optimization: "在已有 WAM 上做 semantic alignment post-training，默认 K=16/24、权重 0.1；不改变视频生成支路的 VAE-space 预训练。",
    data: "LIBERO+ 光照与视觉扰动、RoboTwin Clean/Random；FR3 三项桌面任务在白光收集示范，紫色与青色光照只用于 OOD 测试。",
    experiments: "LIBERO+ 上 FastWAM 49.7%→58.9%、GE-Act 78.0%→80.9%；FR3 的 ID/OOD 平均为 82.7%/80.0%，基线 GE-Act 为 80.0%/57.3%。",
    novelty: "相对直接给动作分支未来像素或当前语义，按时间步对齐冻结语义 teacher 更稳定，并且 teacher 不增加部署成本。",
    experimentDetails: [{ title: "跨基准和真机光照迁移", setup: "LIBERO+、RoboTwin，以及 FR3 三任务；真机每任务 25 次 ID、紫光 25 次、青光 25 次。", comparisons: "FastWAM、GE-Act 与 DINO CLS/patch、Depth Anything、当前帧监督、无时间 PE 等变体。", results: ["LIBERO+ 的 GE-Act 由 78.0% 提至 80.9%，FastWAM 由 49.7% 提至 58.9%。", "真机 OOD 从 57.3% 提至 80.0%，ID 也由 80.0% 到 82.7%，性能差由 22.7 点缩至 2.7 点。", "DINO CLS 为 58.9%，patch 57.0%、Depth Anything 56.8%、当前帧 52.7%、无 temporal PE 55.0%。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、三套基准、真机光照协议和 teacher/query 消融可核验。"], implementation: ["冻结 DINOv3 ViT-B/16；语义损失权重 0.1；teacher 与 alignment head 推理时删除。"], missing: ["完整训练代码和权重尚需确认；OOD 主要是两种人工光照。"] },
    deepDive: { lead: "Robust-WAM 把‘未来应出现什么语义内容’直接写入动作 token 的训练目标，避免控制支路只从像素预测旁路间接获益。", sections: [{ title: "逐时间步语义对齐", paragraphs: ["每个未来步/视角的 query 与该步动作 token 共用位置编码，Action DiT 因而知道它要解释多远的未来。", "冻结 DINOv3 从真值未来帧提取 CLS；对齐损失只塑造 action hidden state，不要求动作头重建图像。"] }, { title: "推理成本边界", paragraphs: ["测试时仍保留 query token，但去掉 DINO teacher 和投影头，因此不会实时编码未来帧。", "真实光照 OOD 的提升说明语义约束确实降低了外观捷径，但尚不能外推到物体动力学或相机位姿变化。"] }], equations: [{ name: "训练目标", expression: "L = L_video-FM + L_action-FM + λ · Σ(1 - cos(q_t, stopgrad(z_t^DINO)))", explanation: "在原视频/动作 flow matching 上加入未来语义余弦对齐，teacher 不反传。" }], experimentReading: ["真机 225 个 OOD rollouts（3 任务×2 光照×25）比演示型证据更可靠。", "OOD 类型仍较窄，不能称为普适鲁棒性。"], reflections: [] },
    strengths: "改动小、部署开销低，且跨 backbone、仿真扰动和真机 OOD 都有对照。",
    limitations: "依赖冻结视觉 teacher 的语义偏好；只验证了外观型 shift，没有覆盖遮挡、相机、动力学或新物体组合。",
    transfer: "已有 WAM 可在 action stream 上加按未来步对齐的语义 query，而无需重训/部署大型未来帧 teacher。",
    figures: figure("2608.05903", "2", "Robust-WAM 语义预见对齐结构", "Figure 2 · 视频支路、未来语义 query 与共享时间位置编码。图片来自 arXiv HTML 原图。"),
  },
  {
    rank: 4,
    title: "GeniWorld: A Generalizable Interactive World Model for Robotic Manipulation via Visual Actions",
    arxivId: "2608.06332", url: "https://arxiv.org/abs/2608.06332",
    institutions: ["Tsinghua SIGS", "Tencent Robotics X", "HKUST", "Shenzhen Technology University"],
    signal: "先用 URDF 把数值动作渲染成像素对齐的机器人运动，再让 world model 只补全场景变化，从接口上减轻跨场景和跨外观的纠缠。",
    tags: ["Interactive World Model", "Visual Actions", "Synthetic Data"],
    classification: { research: "WM", training: "Post-training", modalities: ["Mask / Segmentation", "Point Cloud / 3D"], data: "合成 / 仿真数据", platforms: ["机械臂", "夹爪"], deployment: "Real2Sim2Real" },
    resources: [{ label: "项目页", url: "https://chenghaogu.github.io/GeniWorld/" }],
    motivation: "数值动作缺少空间落点，world model 又要同时生成机器人和环境，容易把本体外观、运动学与场景动力学混在一起。",
    methodSummary: "URDF renderer 把动作序列转成视觉动作；视频模型以场景帧和视觉动作生成未来，因果注意力与 KV cache 支持闭环滚动，并用于策略评估和合成 OOD 训练数据。",
    architecture: "预训练视频生成主干 + visual-action latent；训练时输入真实场景和机器人渲染，推理时在策略动作、运动学渲染与未来帧之间循环。",
    optimization: "Post-training world model；5 个采样步约 8 Hz。下游策略用少量真实示范加 world-model 合成的空间/视觉多样化轨迹再训练。",
    data: "RoboTwin 2,250 条训练、250 条测试，121 帧/24 fps；真机双臂四任务各 25 条示范，并各合成 65 条空间变化和 65 条视觉变化轨迹。",
    experiments: "RoboTwin Random FID/FVD 13.08/20.15，IRASim 为 174.52/191.26；真机四任务的 OOD 策略总体成功率从 40.8% 提到 69.0%。",
    novelty: "不同于直接以 joint/action vector 条件生成，视觉动作把本体运动显式交给渲染器，让生成模型更集中学习机器人引起的环境变化。",
    experimentDetails: [{ title: "生成质量、闭环评估与数据增广", setup: "RoboTwin Clean/Random；真机 Xtrainer 双臂四任务，真实示范各 25 条，四种 OOD 条件下评估。", comparisons: "IRASim 等 action-conditioned WM，以及仅真实数据训练的策略。", results: ["Random 条件 FID/FVD 为 13.08/20.15，IRASim 为 174.52/191.26。", "5 个采样步达到约 8 Hz，相比 50 步大幅提速，FVD 损失约 2%。", "加入合成数据后总体 OOD 成功率 40.8%→69.0%；空间变化 37.5%→70.0%。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、RoboTwin 切分、真机合成数量、速度和主结果可核验。"], implementation: ["视觉动作由 URDF/运动学渲染；因果注意力与 KV cache 维持自回归历史。"], missing: ["完整 world-model 权重和真机环境尚未确认开放；合成数据质量仍依赖 URDF/标定。"] },
    deepDive: { lead: "GeniWorld 的关键是把‘机器人在哪里、怎么动’从生成问题中显式分离，world model 负责补全交互后的场景变化。", sections: [{ title: "视觉动作接口", paragraphs: ["策略输出先经过本体运动学和 URDF renderer，得到与图像坐标严格对齐的 robot motion；生成模型无需从抽象关节数值猜机器人形状。", "这种接口保留本体特定运动学，却让场景动态模型更容易在未见背景和布局上复用。"] }, { title: "从评估到增广", paragraphs: ["同一交互模型可让策略在生成环境中闭环运行，比较候选策略；也可从少量真机示范采样新布局和干扰物轨迹。", "真实 OOD 增益说明合成数据不只改善 FID，但尚缺少对模型错误导致策略偏差的系统上界。"] }], experimentReading: ["论文同时检查生成指标、策略排序和再训练后的真机 OOD，证据层次较完整。", "世界模型仍没有替代真实闭环验证，最终 69% 表明困难场景剩余失败不少。"], reflections: [] },
    strengths: "动作空间接口清晰，且将 world model 用于评估与训练两条下游路径，并提供真机增广收益。",
    limitations: "依赖准确 URDF、相机和运动学；对柔性接触、未建模工具或渲染误差的稳定性仍未知。",
    transfer: "跨本体 world model 可优先把动作转换为像素/几何对齐的视觉动作，再共享环境动态，而不是强行统一原始关节向量。",
    figures: figure("2608.06332", "1", "GeniWorld 视觉动作训练与闭环交互", "Figure 1 · 视觉动作条件的 world-model 训练与策略闭环推理。图片来自 arXiv HTML 原图。"),
  },
  {
    rank: 5,
    title: "DyPES-VLA: Learning Shared Dynamics Priors and Embodiment-Specific Control",
    arxivId: "2608.06374", url: "https://arxiv.org/abs/2608.06374",
    institutions: ["HKUST (Guangzhou)", "COCO Matrix"],
    signal: "共享未来动力学 query，但让不同机器人用各自的 MoE 编解码器输出原生动作，从而避免手工把单臂、双臂和人形动作硬对齐。",
    tags: ["Cross-Embodiment VLA", "Dynamics Prior", "MoE"],
    classification: { research: "VLA", training: "Pre-training", modalities: ["其他模态"], data: "跨本体数据", platforms: ["机械臂", "Humanoid", "灵巧手", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://livfour.github.io/DyPES-VLA_RELEASE/" }],
    motivation: "跨本体策略既需要共享物体运动与接触规律，又不能忽略各机器人的自由度、动作语义和控制接口。",
    methodSummary: "Stage 1 用 action-free 视频预测未来帧形成共享 dynamics query；Stage 2 同时保留未来预测并训练 embodiment-specific MoE action head，按本体路由原生动作空间。",
    architecture: "Qwen3-VL-2B + 96 query；SANA-600M future head；16 层 flow-matching DiT，K=3，本体共享 attention、独立 encoder/FFN expert/decoder。未来生成头推理时移除。",
    optimization: "Stage 1 100k、Stage 2 200k steps，batch 512、16×H100；真机统一微调 1,800 条示范、5k steps，动作流用 4 个 Euler steps。",
    data: "Stage 1 混合完整 EgoDex 与三仿真集（50/20/20/10）；Stage 2 RoboTwin/RoboCasa/LIBERO 为 40/40/20；真机三本体×三任务×200 条。",
    experiments: "LIBERO 98.0%、RoboCasa-GR1 59.25%、RoboTwin 89.02%；三种真机、九个本体-任务组合各 25 次，统一模型平均 75.6%，GR00T-N1.6 为 59.6%。",
    novelty: "相对统一动作 token/手工投影，DyPES 只共享预测性 query 和 attention，把本体差异留给静态路由的专家层。",
    experimentDetails: [{ title: "三个仿真基准与三种真机", setup: "单 checkpoint 覆盖 Panda/FR3、ALOHA/COBOT Magic、GR-1/G1 三族；真机每本体每任务 25 trials。", comparisons: "Qwen-VLA、Fast-WAM、OpenVLA-OFT、ABot-M0；真机对 ACT 与 GR00T-N1.6。", results: ["RoboTwin 89.02%，比 Qwen-VLA 高 2.37 点；RoboCasa 59.25%，比 ABot-M0 高 0.95 点。", "真机平均 75.6%，GR00T-N1.6 为 59.6%，ACT 九个独立模型平均 32.4%。", "消融同时检查未来监督、query 接口和 embodiment-specific experts，并用 linear probe 测未来接触是否可解码。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、数据混合、网络规模、训练步数和九组合真机协议可核验。"], implementation: ["Qwen3-VL-2B、SANA-600M、16 层 DiT、96 queries、3 experts；无 proprioception。", "动作 horizon：单臂 8、人形 16、双臂 50。"], missing: ["训练开销高；完整代码/权重开放状态仍需确认。"] },
    deepDive: { lead: "它把‘可共享什么’限定为未来交互规律，把‘必须分开什么’限定为本体原生动作解码，这比统一全部动作维度更符合系统边界。", sections: [{ title: "共享 query 的监督来源", paragraphs: ["action-free 阶段只要求 query 支持未来帧生成，从人体和多本体视频中吸收物体运动、接触和场景变化。", "action-labeled 阶段未来头继续做正则，MoE 动作头读取同一 query 输出原生动作。"] }, { title: "静态路由而非竞争专家", paragraphs: ["本体 metadata 直接选择 encoder、FFN 与 decoder，attention 层共享时间动作结构；因此专家不是按 token 自由竞争。", "真机使用仿真同族专家继续微调，结果证明共享 checkpoint 可覆盖三种形态，但不等于零样本换机器人。"] }], equations: [{ name: "联合目标", expression: "L_stage2 = L_action-FM + λ_w · L_future", explanation: "未来预测约束共享 query；动作损失在本体特定原生空间计算。" }], experimentReading: ["225 个本体-任务真机 rollouts 且与统一 GR00T 对比，迁移证据较强。", "每种真实本体仍用了 600 条本体内示范，因此属于联合微调，不是零样本跨本体。"], reflections: [] },
    strengths: "仿真三基准、真机三形态和核心结构消融一致支持共享 dynamics/特定控制的拆分。",
    limitations: "16×H100 训练与 1,800 条真机示范成本高；静态专家需提前知道本体类型，未验证新本体快速接入。",
    transfer: "跨本体训练可共享未来交互 query 与时序 attention，但保留本体专属动作归一化、FFN 和 decoder。",
    figures: figure("2608.06374", "2", "DyPES-VLA 共享动力学与本体专家结构", "Figure 2 · 共享未来 query、SANA 未来头和本体特定 MoE 动作头。图片来自 arXiv HTML 原图。"),
  },
  {
    rank: 6,
    title: "SkillMemo: Skill-Level Memory for Compositional Generalization in Robot Manipulation",
    arxivId: "2608.05970", url: "https://arxiv.org/abs/2608.05970",
    institutions: ["Tsinghua SIGS", "Tsinghua University", "Nanyang Technological University", "Beijing Normal University"],
    signal: "把示范中的原子技能和 MoE 路由模式存成可检索 memory，在未见技能组合中复用，而不是只检索整段视觉或文本经验。",
    tags: ["Skill Memory", "Compositional Generalization", "VLA"],
    classification: { research: "Memory", training: "Post-training", modalities: ["State / Proprioception"], data: "其他数据方法", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    detailAttributes: { memoryImplementation: "Skill-level episodic memory", memoryHorizon: "跨任务组合" },
    resources: [{ label: "项目页", url: "https://changyuanwang17.github.io/SkillMemo/" }],
    motivation: "reactive policy 即使记住训练任务，也常在新技能顺序或组合中失败；整段经验 memory 难以重组可复用的原子动作。",
    methodSummary: "EGTS 用 MoE gating 隐式分段轨迹并学习原子技能；SLMA 存储、更新、裁剪 gating profile，按当前上下文检索并融合记忆。",
    architecture: "可挂接 Diffusion Policy、UniACT、UniVLA 与 π0.5；默认 5 experts，memory 保存 skill key/value 与使用状态，门控融合当前表征和检索结果。",
    optimization: "在原 BC/VLA 训练目标上联合学习 expert routing；记忆在训练中更新并裁剪低价值条目，不采用 RL。",
    data: "仿真组合任务和 LIBERO；UR5e 五项真机任务各 50 条示范，另有未见技能组合测试。",
    experiments: "DP 64.6% 对原版 61.2%；LIBERO 上 UniACT 67.2%→72.7%、UniVLA 93.9%→95.9%、π0.5 96.8%→98.0%；UR5e 共 200 次 rollout。",
    novelty: "相对 MemoryVLA 等非结构化视觉/语义 memory，SkillMemo 存的是由路由器发现的技能级动态模式，并能按组合顺序重用。",
    experimentDetails: [{ title: "多策略接入与真机组合", setup: "四类 backbone；UR5e 五任务各 50 demos、40 rollouts，未见组合另做 40 trials。", comparisons: "原 DP/UniACT/UniVLA/π0.5、IMLE 以及 expert 数量和 memory 模块消融。", results: ["LIBERO 的 UniACT 提高 5.5 点，强 π0.5 仍提高 1.2 点。", "真机草莓/玉米/黄油任务分别由 77.5/82.5/62.5% 提至 82.5/90.0/75.0%。", "未见组合如 lemon-in-pot 从 57.5% 到 72.5%；expert 5 的推理约 3.93 s，10 experts 约 7.94 s。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、跨 backbone 结果、真机协议、expert 数和延迟可核验。"], implementation: ["默认 5 experts；EGTS 分段与 SLMA 存储/裁剪分开实现。"], missing: ["代码和完整 memory 更新超参尚需确认；高延迟模型的部署频率未完全交代。"] },
    deepDive: { lead: "SkillMemo 不把 memory 当成额外上下文仓库，而把策略内部的技能路由模式当成可组合记忆单元。", sections: [{ title: "隐式技能分段", paragraphs: ["EGTS 让不同 expert 对轨迹片段形成责任分工，gating profile 随时间变化给出技能边界，不需要人工 subtask 标签。", "SLMA 把稳定的 gating 模式作为 key，保存相应技能表征并按使用价值清理。"] }, { title: "组合时的读取", paragraphs: ["当前观察和指令查询 memory，检索到的技能 value 经门控与当前策略特征融合；因此记忆不是直接回放旧动作。", "跨四类策略都能带来增益，但强 baseline 上幅度较小，说明 memory 的边际价值与 backbone 能力有关。"] }], experimentReading: ["跨 backbone 结果减少了只对单一架构调参的可能。", "未见组合试验数量有限，且部分延迟较高，仍需关注在线控制频率。"], reflections: [] },
    strengths: "技能粒度定义、存取机制、跨策略验证和真机未见组合相互对应。",
    limitations: "技能由 MoE 自发形成，语义可解释性与稳定性不保证；expert 增多会显著增加推理时间。",
    transfer: "长任务 memory 可存策略内部的 skill routing/profile，而不是整段帧或文本摘要，以支持不同顺序的技能复用。",
    figures: figure("2608.05970", "2", "SkillMemo 技能分段与记忆检索框架", "Figure 2 · Expert-guided trajectory segmentation 与 skill-level memory 的存储、裁剪和检索。图片来自 arXiv HTML 原图。"),
  },
  {
    rank: 7,
    title: "In-Context VLA: Endowing Vision-Language-Action Models with Language via In-Context Post-Training and Agentic Tool Use",
    arxivId: "2608.05738", url: "https://arxiv.org/abs/2608.05738",
    institutions: ["Tsinghua University", "Tencent Robotics X"],
    signal: "不让 VLA 在控制前生成长 CoT，而是用检测、深度和 VLM 工具取得结构化证据，再训练策略只读证据并输出动作。",
    tags: ["In-Context VLA", "Tool Use", "CoT"],
    classification: { research: "CoT", training: "Post-training", modalities: ["Depth / RGB-D", "Mask / Segmentation"], data: "数据增强", platforms: ["Humanoid", "夹爪"], deployment: "真机部署优化" },
    motivation: "自由文本 CoT 可能幻觉，语言 token 数远多于动作 token，还会引入数百毫秒到秒级延迟；这些问题对低层闭环尤其不利。",
    methodSummary: "工具链按需调用 GroundingDINO、Depth Anything 和 VLM，生成多样化空间描述并注入 prompt；VLA 只接受动作监督，随后用稀疏成功奖励做 GRPO。",
    architecture: "OpenVLA-OFT 主干 + agentic evidence acquisition；gripper 投影、目标检测和相对深度优先，低置信度才回退 VLM；测试时无需生成 CoT。",
    optimization: "先 in-context SFT，再 trajectory-level GRPO；结构化证据用不同坐标、相对关系和同义表述渲染，避免记住固定模板。",
    data: "LIBERO、RoboCasa-GR1、SimplerEnv，以及 AgiBot G1 八项桌面真机任务；关键帧生成结构化 evidence。",
    experiments: "LIBERO 97.4%、RoboCasa 59.5%、Simpler 72.4%；G1 八项任务单步/多步平均 58.1%/45.0%，BC 为 41.9%/28.1%。",
    novelty: "相对 generative CoT，把语言能力改成‘消费外部证据’，用更强工具取得信息并把语言生成移出实时控制通路。",
    experimentDetails: [{ title: "匹配证据、效率与真机", setup: "三仿真基准；G1 八任务，每个子任务 20 trials，区分 single- 与 multi-stage。", comparisons: "BC、生成式 CoT、inject+supervise、SFT-only、GRPO-only 和不同示范量。", results: ["LIBERO 97.4%；匹配证据的生成 CoT 为 81.5% 且延迟约 4.6 倍。", "SFT-only 95.6%、GRPO-only 87.8%、完整 97.4%；5/10/25/50 demos 为 71.4/84.6/92.8/97.4%。", "真机 single/multi 为 58.1/45.0%，BC 为 41.9/28.1%；动作约 78 ms、12.8 Hz。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["工具级联、证据格式、三基准与八任务真机协议可核验。"], implementation: ["GroundingDINO、Depth Anything、Qwen2.5-VL-7B fallback；SFT 后 GRPO。"], missing: ["工具 API/模型版本影响成本与结果；完整数据生成代码和真机集尚未确认开放。"] },
    deepDive: { lead: "文章的判断不是‘语言推理无用’，而是生成语言和消费已落地证据在控制中的成本与目标不同。", sections: [{ title: "Evidence acquisition", paragraphs: ["工具链先做确定性 gripper 投影，再尝试检测和深度，只有失败才调用 VLM；证据包含目标相对夹爪的位置、深度和可见性。", "训练数据把同一几何事实改写成多种表述，动作损失不要求模型复述这些文本。"] }, { title: "SFT 与 GRPO 分工", paragraphs: ["SFT 学会在证据条件下执行；GRPO 用轨迹成败调整何时依赖/调用工具。", "去掉任一阶段都下降，说明轨迹级后训练没有替代基于示范的低层动作学习。"] }], experimentReading: ["matched-evidence 对照把信息量和生成方式分开，能更直接支持延迟/目标冲突结论。", "真机提升明显，但绝对成功率仍不足一半到六成，工具错误仍会传播。"], reflections: [] },
    strengths: "对 CoT 的假设有匹配对照、延迟数字、数据量曲线和真机验证。",
    limitations: "外部工具增加系统复杂度和失效点；目标检测/深度/VLM 的域外误差未被统一校准。",
    transfer: "控制系统可把语言模型放在证据获取与结构化描述层，低层策略只读证据，避免实时自回归长文本。",
    figures: figure("2608.05738", "2", "In-Context VLA 工具取证与动作头", "Figure 2 · 工具链获取深度、检测和 VLM 证据，再以内上下文形式送入 VLA。图片来自 arXiv HTML 原图。"),
  },
  {
    rank: 8,
    title: "JoyAI-RA 0.5: A Vision-Language-World-Action Model for Generalist Robot Control",
    arxivId: "2608.05674", url: "https://arxiv.org/abs/2608.05674",
    institutions: ["JoyAI-RA Team", "Joy Future Academy, JD"],
    signal: "用隐式 latent alignment 和显式动作-语言监督把大规模人类视频、仿真与少量真机轨迹对齐到动作专家，并加入世界模型辅助恢复。",
    tags: ["Generalist VLA", "Human Video", "WAM"],
    classification: { research: "WAM", training: "Pre-training", modalities: ["其他模态"], data: "UMI / Ego / Human Video", platforms: ["Humanoid", "灵巧手"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://joyai-ra-05.github.io/" }],
    motivation: "人类视频规模大但没有机器人动作，真机数据又窄；仅做视觉预训练无法保证语义、未来动态和动作空间在同一模型中对齐。",
    methodSummary: "LAC-WM 学习人类/机器人视频动态，VLM 通过 implicit feature alignment 与 explicit language-action supervision 连接世界模型和 action expert。",
    architecture: "VLM、LAC-WM 与 flow/diffusion action expert 组成 vision-language-world-action model；世界模型 latent 既做预测监督也提供恢复线索。",
    optimization: "大规模异构视频预训练后，以真机/仿真动作数据做联合后训练；对齐损失与动作损失同时约束共享表征。",
    data: "约 72k+ 小时异构视频、8k+ 小时真机、11k+ 小时仿真、53k+ 小时人类数据；EgoLive 超过 20k 小时。",
    experiments: "AgiBot G1 六类场景，seen/unseen 平均 92.0%/75.5%；去掉两类 alignment 后 unseen 29.8%，只去 implicit 为 46.8%。",
    novelty: "相对只用机器人轨迹的 VLA，通过世界模型 latent 和显式语义两条路径利用人类视频，并把数据规模消融连接到真机泛化。",
    experimentDetails: [{ title: "G1 真机泛化与数据规模", setup: "六类场景，含 easy/hard/long-horizon；每任务 seen 20 次、unseen 10 次，以子任务百分制。", comparisons: "π0.5、去掉 implicit/explicit alignment、无 LAC-WM 和不同比例 Ego 数据。", results: ["Seen 92.0%，π0.5 为 74.0%；Unseen 75.5%。", "无两类 alignment 的 unseen 仅 29.8%，无 implicit 为 46.8%，说明收益不只是 backbone 规模。", "Ego 数据从 10% 扩到 100% 时 seen 约 47.8%→85.6%、unseen 37.6%→60.2%。"] }],
    reproducibilityDetails: { status: "信息不足", verifiedResources: ["项目页、数据量级、G1 任务和主要对齐/规模消融可核验。"], implementation: ["训练包含 VLM、LAC-WM、action expert 及两类 alignment。"], missing: ["大部分数据非公开；详细数据去重、任务分布、代码和权重尚未确认，官方规模数字难独立复核。"] },
    deepDive: { lead: "JoyAI-RA 0.5 的主要信息量来自‘人类视频如何进入动作模型’和数据规模曲线，而不是单一榜单数字。", sections: [{ title: "双重对齐", paragraphs: ["implicit alignment 让视频/世界模型 latent 与动作表征靠近；explicit alignment 用可读语义和动作监督约束 VLM。", "Action expert 仍依赖真机与仿真动作数据，人类视频不能直接替代机器人控制标签。"] }, { title: "世界模型的作用", paragraphs: ["LAC-WM 提供未来变化表征，并在失败恢复场景中作为辅助条件；论文也对是否加入 latent-conditioned WM 做消融。", "数据曲线显示更多 ego 视频有帮助，但这些结果来自同一私有数据管线，不能与公开数据量直接等价比较。"] }], experimentReading: ["真机包含 unseen 条件和对齐消融，支持方向性判断。", "数据与实现大多闭源，结果目前主要是官方自报，复现置信度低于前几篇。"], reflections: [] },
    strengths: "视频规模、两条对齐路径、真机 unseen 与规模消融相互呼应。",
    limitations: "私有数据占比高，训练和评测细节不够开放；官方百分制聚合可能掩盖终局失败。",
    transfer: "利用人类视频时可同时做 latent dynamics alignment 和显式语义/action alignment，并用数据比例曲线验证真实边际收益。",
    figures: figure("2608.05674", "1", "JoyAI-RA 0.5 数据与模型总览", "Figure 1 · 异构视频、LAC-WM、VLM alignment 与 action expert 的整体关系。图片来自 arXiv HTML 原图。"),
  },
  {
    rank: 9,
    title: "VLAff: Vision-Language-Affordance Model for Unified Actionable Affordances",
    arxivId: "2608.05215", url: "https://arxiv.org/abs/2608.05215",
    institutions: ["JSK Robotics Laboratory, The University of Tokyo"],
    signal: "把人类第一视角视频转成可执行的交互位置、MANO 抓取和 3D 运动轨迹，让机器人先得到对象中心 affordance，再做动作。",
    tags: ["Human Video", "Affordance", "Zero-shot Manipulation"],
    classification: { research: "VLA", training: "Pre-training", modalities: ["Point Cloud / 3D", "Mask / Segmentation"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    motivation: "人类视频难直接映射到机器人关节动作，但交互区域、抓取形态和物体相对轨迹可以作为跨本体中间表示。",
    methodSummary: "从 ego 视频重建场景和手部，生成 visual/grasp/trajectory 三类 affordance；统一 VLM 根据图像与指令分别解码 heatmap、96 维 MANO grasp 与轨迹。",
    architecture: "Qwen2.5-VL 负责多模态语义，DINOv2 编码视觉；三个专用 decoder 输出交互 heatmap、抓取和轨迹，再结合 3D 场景、方向引导与碰撞采样转成机器人动作。",
    optimization: "在 EgoAffordance 做统一多任务预训练；下游既可零样本执行，也可把 affordance 作为 RL/策略学习先验。",
    data: "EgoAffordance 204,025 episodes、5,782,431 heatmaps、11,612,524 grasp/trajectory affordances；还使用 HANDAL、SceneFun3D 等公开数据。",
    experiments: "10 个仿真任务各 10 次，VLAff 平均 83%、VidBot 85%；Fetch/PR2 五项厨房真机各 10 次，VLAff 68%、VidBot 52%。",
    novelty: "相对只预测 2D 区域或单一轨迹的工作，用一个模型联合学习 where/how-grasp/how-move 三类显式 affordance，并从人类 ego 数据迁移到不同机器人。",
    experimentDetails: [{ title: "零样本真机与 affordance 消融", setup: "仿真 10 任务×10 trials；Fetch/PR2 五项厨房任务×10 trials，并在开冰箱 RL 中去除不同 affordance。", comparisons: "VidBot、单任务 affordance 方法及去 heatmap/grasp/trajectory 变体。", results: ["真机平均 68%，VidBot 52%；仿真 83%，略低于 VidBot 85%。", "去掉 visual heatmap 后开冰箱 RL 完全失败，说明交互位置是关键先验。", "轨迹生成加入语言方向与碰撞采样，但论文也记录了不符合真实物理的轨迹失败。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["IROS 2026 论文、数据规模、三 decoder 结构与真机协议可核验。"], implementation: ["Qwen2.5-VL + DINOv2；grasp 为 96 维 MANO 表示；轨迹经 3D 场景过滤。"], missing: ["EgoAffordance 和完整训练代码的公开状态尚未确认；真机每项仅 10 次。"] },
    deepDive: { lead: "VLAff 选择的跨本体桥梁不是统一动作 token，而是对象中心、可解释且可转换的三类 affordance。", sections: [{ title: "EgoAffordance 构建", paragraphs: ["VLM 先从带语言标注的 ego 片段定位接触关键帧、对象与作用手，再用 3D SfM、手网格和跟踪恢复 heatmap、抓取姿态和轨迹。", "三类标签共享同一语言/视觉输入，允许模型同时回答在哪里接触、怎么抓以及沿什么路径移动。"] }, { title: "从预测到执行", paragraphs: ["heatmap 在 RGB/3D 中确定候选交互点，MANO grasp 被映射到机器人夹爪/手，轨迹由语言方向和碰撞检查约束。", "这条转换链透明但误差会累积，尤其是重建和物理不可行轨迹。"] }], experimentReading: ["真机跨 Fetch/PR2 支持中间表示可迁移，但样本数较少。", "仿真未超过 VidBot，说明统一输出的优势主要体现在跨机器人可执行性和功能完整性。"], reflections: [] },
    strengths: "数据规模、三类可解释输出、跨平台真机与关键 affordance 消融较完整。",
    limitations: "长转换链依赖 3D 重建与手网格质量；抓取/轨迹并不保证动力学可行，真机统计较小。",
    transfer: "从非机器人视频迁移时可先学习对象中心 affordance，再用平台特定几何模块转动作，降低直接动作对齐难度。",
    figures: figure("2608.05215", "2", "VLAff 三类 affordance 解码架构", "Figure 2 · 共享多模态主干与 visual、grasp、trajectory 三个 affordance decoder。图片来自 arXiv HTML 原图。"),
  },
  {
    rank: 10,
    title: "LAWM-3D: Learning 3D-Aware Latent Actions from Human Videos for Generalizable Robot World Models",
    arxivId: "2608.05706", url: "https://arxiv.org/abs/2608.05706",
    institutions: ["Tsinghua University", "Tencent Robotics X"],
    signal: "用多视图统一 token、VGGT 几何对齐和 RGB-D 非单射重建，阻止 latent action 偷看未来外观，逼它编码跨视角一致的 3D 运动。",
    tags: ["Latent Action", "3D World Model", "Human Video"],
    classification: { research: "WM", training: "Pre-training", modalities: ["Depth / RGB-D", "Point Cloud / 3D"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "Humanoid"] },
    motivation: "把多视图直接加入 LAM 并不会自动得到 3D 动作：未来 RGB 会泄漏外观，摄像机差异也会让 latent 记住视角而非运动。",
    methodSummary: "统一单/多视图 action token；在中间层对齐冻结 VGGT 几何特征；用非单射 RGB-D 联合预测削弱未来帧复制捷径，再用 latent action 预训练 world model。",
    architecture: "24 层 LAM encoder/decoder，32 维 latent；第 6/11 层与 VGGT ViT-L/384 对齐。world model 接收当前帧和 latent action 预测未来。",
    optimization: "LAM 600k steps、batch 128、lr 2.5e-5；WM 300k、batch 256、lr 1.6e-4。先人类视频预训练，再对机器人动作空间做后训练。",
    data: "Ego-Exo4D 1,286h、Assembly101 513h、EgoDex 829h；机器人阶段还用 AgiBot-World、RT-1、Language-Table、DROID，序列 13 帧、最多 7 视角。",
    experiments: "WorldArena 和 In-lab/EgoDex/DreamDojo-HV OOD；2B 模型在部分指标略超 DreamDojo 14B。LAM 完整模型 PSNR/SSIM 30.56/0.933，对照 29.31/0.886。",
    novelty: "相对单视角、像素型 LAM，论文明确把外观泄漏和跨视角几何不一致拆成两个问题，并用深度目标与 3D teacher 分别处理。",
    experimentDetails: [{ title: "世界模型、OOD 与组件消融", setup: "WorldArena 生成/动作可控指标，另在 In-lab、EgoDex、DreamDojo-HV 做 OOD；比较不同 LAM 和数据组合。", comparisons: "DreamDojo、基础 LAM、无 RGB-D、无 geometry alignment、仅单视图等。", results: ["LAM 基线 PSNR/SSIM 29.31/0.886，完整模型 30.56/0.933。", "WM 基线约 21.22/0.782，完整约 21.68/0.797；2B 在部分 OOD 指标可接近或超过 14B DreamDojo。", "人类+机器人预训练的归一化下游得分由 1.0 到约 1.0887，说明两类数据互补但幅度有限。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["数据集、网络层数、latent 维数、训练步数和对齐层可核验。"], implementation: ["LAM/WM 均 24 层；几何对齐在第 6/11 层；最多 7 视角、13 帧序列。"], missing: ["代码权重开放状态尚未确认；没有策略真机执行，world-model 指标不能直接等同控制收益。"] },
    deepDive: { lead: "LAWM-3D 的重点不是‘多视图更多’，而是消除多视图训练中的两个捷径，让 latent action 更接近运动而不是未来图像压缩。", sections: [{ title: "防止未来外观泄漏", paragraphs: ["如果 decoder 可从 latent 直接恢复未来 RGB，encoder 会把纹理和颜色塞进 action code。RGB-D 非单射目标降低逐像素复制的收益，迫使表示关注几何变化。", "单/多视图共享 tokenization，使同一运动在不同相机下映射到统一 latent。"] }, { title: "显式几何锚点", paragraphs: ["冻结 VGGT 提供跨视角对应，LAM 中间特征用对齐损失吸收 3D 结构；消融显示仅多视图而无对齐不足以形成稳定 3D latent。", "得到的 latent 用于 world-model rollout、规划和策略筛选，但文章主要证据仍是生成与表征评估。"] }], experimentReading: ["多数据、OOD 和结构消融支持表征方向。", "缺少真机策略闭环，不能把生成指标提升直接解释为操作成功率提升。"], reflections: [] },
    strengths: "问题拆分清晰，数据规模大，几何/深度/视图和数据组成均有消融。",
    limitations: "依赖同步多视图、离线深度与 3D foundation model；训练成本高且下游真机证据不足。",
    transfer: "训练 LAM 时要检查 future-frame leakage，并用跨视角几何 teacher 与非像素复制目标约束动作 latent。",
    figures: figure("2608.05706", "1", "LAWM-3D 多视图 latent action 与 world model", "Figure 1 · 单/多视图联合训练、3D-aware latent action 和 world model 的整体流程。图片来自 arXiv HTML 原图。"),
  },
  {
    rank: 11,
    title: "XEWorld: Can Action-Conditioned World Models Generalize to Unseen Robot Embodiments?",
    arxivId: "2608.05799", url: "https://arxiv.org/abs/2608.05799",
    institutions: ["机构信息未在 arXiv HTML 正文中展开"],
    signal: "在相同场景和任务中只替换机器人本体，测试 world model 到底学了物理动态，还是依赖训练机器人外观。",
    tags: ["World Model Benchmark", "Cross-Embodiment", "Generalization"],
    classification: { research: "WM", training: "Post-training", modalities: ["Mask / Segmentation"], data: "合成 / 仿真数据", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    motivation: "只在训练本体上评估，无法区分物理建模和外观记忆；需要把机器人形态作为唯一变化量。",
    methodSummary: "XEWorld 构造五种双臂机器人和相同 25 任务，以 Aloha/Arx/UR5 训练、Franka/Piper held-out，并分开测视觉、形态、运动学和物体动态。",
    architecture: "测试 FlowWAM 参考实现及 IRASim、Ctrl-World、EnerVerse-AC；改变动作表示、目标本体描述、静态/逐帧渲染和 few-shot 适配。",
    optimization: "不是新控制模型；通过 zero-shot、leave-one-embodiment-out 与每任务 1/2/3 条 few-shot demo 的受控干预定位瓶颈。",
    data: "25 任务、每任务 50 个训练 seed、20 个 held-out seed；Aloha-AgileX、Arx-X5、UR5 训练，Franka 与 Piper 测试，共 2,500 个计分单元，320×240。",
    experiments: "pixel-space optical-flow action 使 Franka/Piper LPIPS 下降约 29%/57%，shape IoU 提高 25%/116%；静态本体图提升不足 2%，逐帧对齐更有效。",
    novelty: "相对常规同本体 benchmark，XEWorld 把视觉相似度与运动学相似度分开，并验证模型误差主要随外观距离而非可达空间距离变化。",
    experimentDetails: [{ title: "动作接口、目标描述与 few-shot", setup: "五本体、25 同任务；Franka/Piper held-out，分别做零样本、LOEO、1/2/3 demos per task。", comparisons: "Numeric joint、pixel-flow action；单/九张静态图与逐帧渲染；四类 world model。", results: ["pixel-space action 对 Franka/Piper 的 LPIPS 分别降低约 29%/57%，shape IoU 提升约 25%/116%。", "单张或九张静态描述的 shape IoU 提升不足 2%，逐帧空间-时间对齐才明显改善。", "每任务一条 demo（25 episodes）可让 held-out LPIPS 下降约 30%/32%，但 UR5 见过本体的 LPIPS 反而增加约 69%，暴露灾难性遗忘。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["本体/任务切分、seed 数、指标、干预和 few-shot 协议可核验。"], implementation: ["评分分成 visual quality、robot morphology/kinematics 和 object dynamics。"], missing: ["未见项目页或代码链接；无真实机器人，结论限于受控仿真/视频 world model。"] },
    deepDive: { lead: "XEWorld 不是提出更强 world model，而是通过只换本体的干预证明现有模型对动态规律和机器人外观仍没有解耦。", sections: [{ title: "受控 held-out embodiment", paragraphs: ["训练和测试任务、场景、物体动力学保持一致，只替换机器人；这让跨本体误差不能轻易归因于任务难度。", "形态、运动学和视觉距离分别计算，结果显示生成误差与外观距离的关系更稳定。"] }, { title: "为什么静态参考不够", paragraphs: ["一张或多张目标机器人图片只告诉模型长什么样，不能持续绑定每个时间步的姿态；逐帧 render/flow 提供动态空间对齐。", "few-shot 能恢复新外观，但会损伤旧本体，说明参数内适配仍在覆盖已学表征。"] }], experimentReading: ["大量受控组合和多种模型复现让诊断结论较可信。", "仿真分辨率与固定任务限制了外推范围，不能直接代表真机交互物理。"], reflections: [] },
    strengths: "因果变量控制、度量拆分和干预实验扎实，能指出 cross-embodiment WM 的具体接口瓶颈。",
    limitations: "没有真机，任务和视觉分布受模拟器约束；few-shot 灾难性遗忘尚未给出解决方法。",
    transfer: "评估跨本体 WM 时应保持场景任务不变，并把 numeric action、pixel action、静态本体描述和动态对齐分别测试。",
    figures: figure("2608.05799", "1", "XEWorld 跨本体测试平台", "Figure 1 · XEWorld 的训练/held-out 本体、动作接口和多维评分设计。图片来自 arXiv HTML 原图。"),
  },
  {
    rank: 12,
    title: "Variable Impedance Diffusion Policy for Contact-Rich Manipulation from Diverse Demonstrations",
    arxivId: "2608.06210", url: "https://arxiv.org/abs/2608.06210",
    institutions: ["University of Waterloo", "McGill University"],
    signal: "仅从位置示范的跨布局变化中分离几何适配和有意顺应，再让 diffusion policy 同时输出位姿与动态刚度。",
    tags: ["Variable Impedance", "Diffusion Policy", "Contact-rich"],
    classification: { research: "其他", training: "BC", modalities: ["Force / Torque", "State / Proprioception"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "固定高刚度会产生力峰和卡死，固定低刚度又跟踪不准；多布局位置示范中的轨迹方差还混入了几何变化，不能直接当顺应性。",
    methodSummary: "TP-DAMM 在任务坐标系内聚类位置与运动方向，得到物理一致的协方差；协方差映射到笛卡尔刚度标签，VIDP 从视觉/状态联合预测位姿和刚度。",
    architecture: "UMI 收集 ego 视觉和位姿；TP-DAMM 离线生成 stiffness profile；Diffusion Policy 输出 pose chunk 与 6D stiffness，Franka 变阻抗控制器执行。",
    optimization: "纯模仿学习，AdamW + cosine schedule；用 trajectory editing 保证动作块与刚度时间连续，不需要训练时力传感器标签。",
    data: "Peg-in-Hole 333、Pulley Assembly 319、Cable Routing 307 条示范；GoPro Hero 11、Vicon/UMI 采集，Franka Panda 在 65×75 cm 空间执行。",
    experiments: "每任务每方法 20 次：插孔 80%（高刚度 80%、低刚度 15%），滑轮 70%（40%/35%），布线 75%（60%/0%）；另测力、误差和机械功。",
    novelty: "相对直接 inverse covariance 或固定参考系 TP-GMM，TP-DAMM 同时使用任务坐标与方向性，避免把不同布局产生的位置差错认成低刚度。",
    experimentDetails: [{ title: "三项接触真机与物理量", setup: "Franka 三任务，Compliant-DP、Stiff-DP、VIDP 各 20 rollouts，布局变化；成功 trial 再统计力、误差和绝对机械功。", comparisons: "400 N/m 固定低刚度、1200 N/m 固定高刚度，以及 GMM/DAMM/TP-GMM 聚类。", results: ["插孔 VIDP 80%，与高刚度相同但低刚度仅 15%；滑轮 70%，约为两固定基线的近两倍。", "Cable Routing 75%，低刚度 60%、高刚度 0%；高刚度在第三 hook 因拉力过大失败。", "成功布线的总跟踪误差 8.7±1.7 mm，低刚度为 10.4±2.3 mm；VIDP 同时压低刚性接触力峰与机械功。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["论文 PDF、任务帧、示范量、刚度基线、20-rollout 协议与物理指标可核验。"], implementation: ["Franka Panda；近临界阻尼 0.707；固定基线为 400/1200 N/m；RTX 4090 训练、RTX 3070 Ti laptop 部署。"], missing: ["代码和数据尚未确认开放；任务帧需人工预定义，旋转方差和非计划接触处理有限。"] },
    deepDive: { lead: "VIDP 的价值不只是给 Diffusion Policy 加一个 stiffness head，而是先把示范方差变成相对可信的顺应标签。", sections: [{ title: "TP-DAMM 的方差解释", paragraphs: ["每条轨迹同时投到起点、目标、滑轮或 hook 等任务坐标，方向敏感聚类避免把相反运动合并。", "局部高一致性对应高刚度，跨示范可变方向对应低刚度；融合后的协方差经逆映射形成笛卡尔 stiffness profile。"] }, { title: "位姿与刚度联合生成", paragraphs: ["VIDP 观察视觉和末端状态，联合去噪未来 pose 与 stiffness chunk；执行层按刚度设置阻抗增益。", "三任务表明最佳刚度随阶段变化：插入轴向应让步、自由空间要精确，柔性布线则在各 hook 间改变方向刚度。"] }], equations: [{ name: "刚度映射", expression: "K_t ∝ (Σ_t + εI)⁻¹", explanation: "示范分布方差低的方向赋予更高刚度；ε 用于数值稳定和增益限幅。" }, { name: "阻抗控制", expression: "τ = Jᵀ[K(x_d-x)+D(ẋ_d-ẋ)] + τ_null", explanation: "策略输出目标位姿与随时间变化的 K，D 按阻尼比联动。" }], experimentReading: ["成功率之外还测力、跟踪误差与机械功，较好覆盖安全/精度折衷。", "每方法每任务 20 次，且任务 frame 人工指定，跨更开放场景仍需验证。"], reflections: [] },
    strengths: "三类接触机理、固定刚度强基线、阶段成功率和物理量共同支持变阻抗收益。",
    limitations: "依赖预定义任务坐标与充分多样的示范；未处理复杂旋转协方差、突发接触和新任务零样本。",
    transfer: "从无力标签示范学顺应性时，先在任务坐标内分离布局变化，再把方向协方差映射为受限刚度。",
    figures: figure("2608.06210", "1", "VIDP 从多样示范到动态刚度的流程", "Figure 1 · TP-DAMM 提取方向一致分布并映射 stiffness，VIDP 联合输出位姿与刚度。图片精确裁自 arXiv PDF 原 Figure 1。"),
  },
  {
    rank: 13,
    title: "ARGUS: Aligning Robot Scene Geometry Under Shifting Views with Large 3D Vision Models",
    arxivId: "2608.05579", url: "https://arxiv.org/abs/2608.05579",
    institutions: ["University of Illinois Urbana-Champaign", "Harvard University"],
    signal: "用 VGGT 从任意 RGB 视角恢复场景点云并重渲染到统一相机，让下游策略不必自己从大量相机变化中学习视角不变性。",
    tags: ["Viewpoint Generalization", "VGGT", "Canonicalization"],
    classification: { research: "表征学习", training: "BC", modalities: ["Point Cloud / 3D"], data: "数据增强", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://rsathua.github.io/ARGUS/" }],
    motivation: "DROID 一类自由相机数据丰富但分布宽，RGB policy 容易记住像素位置；直接堆更多视角使学习变慢，也未必泛化到新相机。",
    methodSummary: "多视图 RGB 经 VGGT 得到点云和相机外参，用 AprilTag 标定恢复真实尺度，再渲染固定 canonical view 交给普通 Diffusion Policy。",
    architecture: "ARGUS 是策略前处理层，不改动作网络；可输出 canonical RGB，也可把 VGGT 点云直接送入 3D Diffuser Actor。",
    optimization: "下游仍做 BC/DP；把 D_fixed 与 D_diverse 的视觉空间先对齐，再用相同训练轮数比较收敛速度和新视角泛化。",
    data: "四项真机任务；固定视角集 100 demos，view-diverse 集 200 个独立相机位姿/任务；评估 5 相机×10 物体配置。",
    experiments: "ARGUS 达到 90% 成功率所需训练约比 KYC 快 6×、比普通 DP 快 4×；仅 40 demos/80 views 可到 70%。",
    novelty: "相对让策略内部学习 viewpoint invariance，ARGUS 用通用 3D foundation model 把观察先规范化，且不要求深度相机。",
    experimentDetails: [{ title: "新视角真机与学习效率", setup: "四任务、固定/高度变化两训练集；每个策略在 5 个新相机、每相机 10 个物体布局上测试。", comparisons: "普通 Diffusion Policy、KYC/VISTA、depth 版 3D Diffuser Actor。", results: ["在 view-diverse 数据上达到 90% 成功率，比 KYC 快 6×、比普通 DP 快 4×。", "40 demos（80 个独立视角）即可约 70%。", "VGGT 点云接入 3D Diffuser Actor 与真实 depth 点云表现接近，但细小物体和遮挡孔洞会降低精度。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、任务/相机 protocol、VGGT/标定流程、训练轮数和效率曲线可核验。"], implementation: ["VGGT 每次策略预测运行；RTX 3080 平均额外约 0.52 s；策略训练 1,500 epochs。"], missing: ["完整数据与代码开放状态尚需确认；论文表格主要以图/成功计数呈现。"] },
    deepDive: { lead: "ARGUS 把视角泛化从‘策略要学会忽略相机’改成‘感知层先把相机差异消掉’，因此收益首先体现在样本和训练效率。", sections: [{ title: "尺度和坐标恢复", paragraphs: ["VGGT 输出的点云尺度与参考相机坐标不保证等于机器人世界坐标；方法用至少两台已标定相机的真实基线估计尺度，并变换到 world frame。", "点云从固定 canonical camera 渲染为 RGB，策略看到的对象位置更稳定。"] }, { title: "精度与速度代价", paragraphs: ["canonicalization 会受 VGGT 外参抖动、遮挡孔洞和重渲染伪影影响，细小按钮类任务最明显。", "0.52 s 前处理适合准静态操作，不适合高频动态控制；缓存或增量 3D 模型是实际部署关键。"] }], experimentReading: ["五个新相机、不同物体配置的真机评估直接对应 viewpoint shift。", "效率提升清楚，但原图表中的绝对任务成功率差异不应被概括成所有任务统一大幅领先。"], reflections: [] },
    strengths: "不改策略即可接入，真机视角覆盖广，并同时报告数据效率、3D policy 兼容性和失败边界。",
    limitations: "VGGT 计算慢、尺度需标定；重建抖动和遮挡会伤害精细操作。",
    transfer: "大规模自由相机数据可在训练前 canonicalize，先降低视角熵，再让策略学习任务动态。",
    figures: figure("2608.05579", "1", "ARGUS RGB 到 canonical view 的流程", "Figure 1 · VGGT 点云恢复、尺度/外参对齐和 canonical rendering 后再输入策略。图片来自 arXiv HTML 原图。"),
  },
  {
    rank: 14,
    title: "Near-sensor Computing for Rapid Visuotactile Perception",
    arxivId: "2608.05725", url: "https://arxiv.org/abs/2608.05725",
    institutions: ["School of Information Science and Technology, ShanghaiTech University"],
    signal: "把触觉相机的光度立体和 Poisson 深度重建搬到传感器旁的固定流水线，先压低确定性延迟，再闭合机器人保护反射。",
    tags: ["Visuotactile", "Near-sensor Computing", "Reflex"],
    classification: { research: "其他", modalities: ["Tactile"], platforms: ["其他平台"], deployment: "真机部署优化" },
    motivation: "视觉触觉把表面梯度传回 CPU/GPU 求深度，会引入传输、调度长尾和功耗；保护性动作关心最坏情况延迟，而不只是平均吞吐。",
    methodSummary: "在 FPGA 上将光度立体、二维 DST、频域 Poisson 求解和逆变换做成无迭代流式数据通路，边接收像素边输出深度并触发本地阈值决策。",
    architecture: "128×128 触觉传感器最高 400 fps；Xilinx Zynq UltraScale+、166 MHz，一像素/周期；逻辑固定 schedule，不使用数据相关收敛。",
    optimization: "硬件/系统协同优化而非学习训练；通过 FFT-based DST 复用行列变换核心，以 on-chip memory 换确定性。",
    data: "15 种接触几何；1,000 连续帧延迟测试；近传感器与主机路径分别做 50/81 次机器人保护反射试验。",
    experiments: "128² 首个深度值固定 0.211 ms，FPGA 逻辑 347 mW、45 nm ASIC 估计 324 mW；深度误差为峰值的 0.17%；动作开始 28.3±4.9 ms，对主机 169.9±27.8 ms。",
    novelty: "相对主机软件或迭代 PDE accelerator，直接把精确谱 Poisson 解映射到固定周期流式电路，使 latency 不依赖接触形状。",
    experimentDetails: [{ title: "数值精度、硬件延迟与机器人反射", setup: "64²/128²/256² 多尺度，1,000 帧/平台；15 几何对双精度；同一 actuator 比较 near-sensor 与 host loop。", comparisons: "i7-13700、RTX 4090、Jetson Orin NX 软件实现及主机决策路径。", results: ["128² 每帧固定 35,107 cycles=0.211 ms；软件 99th percentile 分别约 0.93/0.43/5.3 ms。", "实测持续输出 10,106 fps，接近 10,133 fps 理论上限；15 几何平均误差约峰值深度 0.17%。", "contact-to-motion 28.3±4.9 ms，主机 169.9±27.8 ms；Mann–Whitney U=0，p=8.1×10⁻²²。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["电路频率、周期数、分辨率、功耗边界、统计样本和误差定义可核验。"], implementation: ["Zynq UltraScale+；166 MHz；128²；24-bit fixed-point；one pixel per cycle。"], missing: ["RTL/板级工程是否开放尚未确认；ASIC 功耗为估计而非流片测量。"] },
    deepDive: { lead: "这项工作提醒触觉系统：算法吞吐高不等于闭环快，必须把传输、操作系统调度和首次有效输出都计入。", sections: [{ title: "固定周期谱求解", paragraphs: ["Poisson 方程在 Dirichlet 边界下经二维 DST 变成逐频点除法；行列变换流水化后不需要迭代停止条件。", "固定 schedule 保证每个网格尺寸的周期数恒定，最坏延迟可直接验证。"] }, { title: "从深度到反射", paragraphs: ["本地深度流一达到接触阈值就触发控制命令，避免完整 RGB 帧传主机再排队。", "整体动作仍受相机、通信和 actuator 限制，所以 0.211 ms 计算只把 170 ms 闭环降到约 28 ms，而不是亚毫秒运动。"] }], equations: [{ name: "谱域 Poisson", expression: "∇²z = ∇·g  ⇒  Z_uv = G_uv / (λ_u + λ_v)", explanation: "DST 将离散 Laplacian 对角化，逐频点相除后做逆 DST 得到深度。" }], experimentReading: ["固定周期、功耗、几何误差与机器人时间链都被分别测量，工程证据完整。", "ASIC 数字来自综合估计，且 256² 主要受片上存储限制。"], reflections: [] },
    strengths: "延迟定义严谨，既有计算/功耗/误差又有真实机器人闭环与统计检验。",
    limitations: "专用硬件与固定分辨率降低通用性；更大网格受 on-chip memory 限制，ASIC 尚未流片验证。",
    transfer: "接触任务可把预处理和安全触发下沉到传感器边缘，并报告 99th percentile 与 contact-to-motion，而不只报模型 FPS。",
    figures: figure("2608.05725", "1", "近传感器触觉重建与机器人反射", "Figure 1 · 触觉相机、流式 Poisson 深度重建和本地保护反射。图片来自 arXiv HTML 原图。"),
  },
  {
    rank: 15,
    title: "GAUGE: A Measurement-Grounded Benchmark for Physical Fidelity in Simulation Engines and Video World Models",
    arxivId: "2608.05948", url: "https://arxiv.org/abs/2608.05948",
    institutions: ["Intern Robotics research team"],
    signal: "用同一套实测初始条件和参数同时校准物理引擎与视频 world model，分别检查物理定律形式和参数是否正确。",
    tags: ["Physical Fidelity", "Benchmark", "World Model"],
    classification: { research: "WM", modalities: ["Point Cloud / 3D"], data: "合成 / 仿真数据", platforms: ["其他平台"] },
    resources: [{ label: "项目页", url: "https://internrobotics.github.io/GAUGE/" }],
    motivation: "视频看起来真实或平均轨迹误差小，并不代表摩擦、周期、动量传递等物理参数正确；仿真器与生成模型也常用不同协议，难直接比较。",
    methodSummary: "GAUGE 在真实装置测质量、尺寸、摩擦和初始状态，用光学动捕获得统一轨迹；相同条件复现到 14 个物理引擎配置和多种 I2V 模型。",
    architecture: "基准分 simulation-engine track 与 video-world-model track；SAM/trackers 从生成视频提取轨迹，再在统一坐标与时间轴上拟合加速度、周期、能量损失和动量传递。",
    optimization: "不是训练方法；通过参数标定和物理量拟合，把视觉误差拆成定律形式正确但参数错误、接触失败、静止段异常等类别。",
    data: "真实 2 m 立方空间、16 台 NOKOV 180 Hz 相机、亚毫米动捕；22 类任务族，真实每任务 20 次，并覆盖刚体、布料、摆、碰撞和振荡。",
    experiments: "Isaac Sim、Genesis、Newton 等没有统一赢家；一个摆模型轨迹拟合 R² 可达 0.99，但周期 1.9 s 对真实 1.06 s；牛顿摆生成中 10 个有 6 个物理无效。",
    novelty: "相对 FID/FVD 或像素轨迹，GAUGE 用实测参数和可解释物理量区分 law form 与 parameter accuracy，并统一比较经典 simulator 和生成 world model。",
    experimentDetails: [{ title: "物理引擎与视频模型双轨评估", setup: "同一真实参数和初始状态；14 个 simulator 配置、6 个 I2V 模型；真实轨迹每任务 20 trials。", comparisons: "Isaac Sim、Genesis、Newton VBD 等，以及多种图生视频模型和 prompt 变体。", results: ["不同引擎在刚体、布料与碰撞指标上排序变化，没有单一引擎全胜。", "摆模型可给出 R²=0.99 的漂亮轨迹形状，但周期 1.9 s，真实为 1.06 s，显示视觉拟合会掩盖参数错误。", "Newton's cradle 的 10 个生成样本中 6 个违反基本交互；负向 prompt 对物理一致性的改善不稳定。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、动捕规模、参数映射、任务和双轨指标可核验。"], implementation: ["16-camera NOKOV 180 Hz；统一坐标/时间处理；视频轨迹由分割与跟踪提取。"], missing: ["部分生成模型为闭源服务；完整 benchmark 资产与所有引擎配置开放状态尚需确认。"] },
    deepDive: { lead: "GAUGE 关注的是‘物理为什么错’，而不是给模拟器或视频生成一个混合总分。", sections: [{ title: "测量接地", paragraphs: ["每个装置的质量、几何、摩擦与初始速度从实物测得，再映射到各引擎；真实动捕轨迹是统一参考。", "对视频模型，先跟踪物体，再恢复公共尺度和时间轴，避免只看主观画面。"] }, { title: "定律与参数分离", paragraphs: ["轨迹可能符合二次形式却加速度数值错误；摆可能正弦形状正确但周期错；碰撞可能看似发生却动量传递不守恒。", "这种拆分更适合判断 world model 能否做策略评估，而不是是否生成好看的视频。"] }], experimentReading: ["真实重复试验和多物理量提供比单一视觉指标更可信的基准。", "它仍不是机器人控制 benchmark，模型在这些装置上正确也不保证接触操作可用。"], reflections: [] },
    strengths: "统一真实测量、物理引擎和视频模型，失败类型可解释，能暴露高视觉拟合下的参数错误。",
    limitations: "任务是受控物理装置而非完整机器人策略闭环；视频跟踪误差和闭源模型版本会影响可复现性。",
    transfer: "评估 world model 时可同时报告 law form、参数误差和接触有效性，避免用 FVD 或单轨迹 R² 代表物理可信度。",
    figures: figure("2608.05948", "1", "GAUGE 双轨物理一致性评估", "Figure 1 · 真实测量、物理引擎与视频 world model 的统一评估管线。图片来自 arXiv HTML 原图。"),
  },
];
