import type { Paper, PaperEquation } from "./site-data";

type Entry = Omit<
  Paper,
  "rank" | "figures" | "optimization" | "experimentDetails" | "reproducibilityDetails" | "deepDive"
> & {
  figureFile: string;
  figureAlt: string;
  figureCaption: string;
  technique: string[];
  evaluation: string[];
  comparison: string;
  reproducibilityStatus: "资源较完整" | "部分可复现" | "信息不足";
  implementation: string[];
  missing: string[];
  equations?: PaperEquation[];
};

const makePaper = (entry: Entry, index: number): Paper => ({
  ...entry,
  rank: index + 1,
  optimization: entry.technique.join("；"),
  experimentDetails: [{
    title: "原文实验与消融",
    setup: entry.experiments,
    comparisons: entry.comparison,
    results: entry.evaluation,
  }],
  reproducibilityDetails: {
    status: entry.reproducibilityStatus,
    verifiedResources: entry.resources?.map((resource) => `${resource.label}: ${resource.url}`) ?? ["arXiv 论文正文"],
    implementation: entry.implementation,
    missing: entry.missing,
  },
  deepDive: {
    lead: entry.methodSummary ?? entry.signal,
    sections: [{ title: "方法与模型改进", paragraphs: entry.technique }],
    equations: entry.equations,
    experimentReading: entry.evaluation,
    reflections: [entry.transfer],
  },
  figures: [{
    src: `/report-assets/2026-09-04/${entry.figureFile}`,
    alt: entry.figureAlt,
    caption: entry.figureCaption,
  }],
});

const entries: Entry[] = [
  {
    title: "ZimaBlue: Evolving Generalizable World Action Models through Scalable Video Pre-training",
    arxivId: "2609.00188",
    url: "https://arxiv.org/abs/2609.00188",
    institutions: ["Joy Future Academy"],
    signal: "把 12 万小时第一视角视频、跨本体机器人轨迹和目标机器人示范串成三阶段 WAM 训练，并用 Slow–Fast 双系统把控制延迟降到 33 ms。",
    tags: ["WAM", "Egocentric Video", "Slow–Fast Control"],
    classification: { research: "WAM", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://zimablue-wam.github.io/" }, { label: "GitHub", url: "https://github.com/ZimaBlue-WAM/ZimaBlue" }],
    motivation: "VLA 的控制能力仍受动作标注机器人数据限制，而大量人类第一视角视频虽包含接触与工具使用，却没有可直接监督动作头的机器人动作。",
    methodSummary: "ZimaBlue 先做因果视频预训练，再用统一 100 维语义动作空间把异构机器人轨迹接到视频动态上，最后在目标本体做专门化；部署时由慢分支给出长时视觉指导，快分支高频修正动作。",
    architecture: "慢分支是高容量视频世界模型，快分支读取慢分支表征、当前观测与状态并生成闭环动作；异步推理、RTC 时间一致性和步数蒸馏共同压缩延迟。",
    data: "预训练混合 EPIC-KITCHENS、EgoDex、HOT3D-Aria、DreamDojo、DROID、AgiBot、Galaxea、RoboMIND2 等来源，规模扩至 120,000 小时；目标机器人统一用 DROID 后训练。",
    experiments: "在 Franka 的 12 项零样本真机任务上评估标准与视觉扰动场景，并补充 LIBERO-Plus、RoboTwin 2.0、RoboCasa365 和加速消融。",
    novelty: "真机宏平均成功率随数据从 300 小时目标本体的 36.1% 提升到 120,000 小时配置的 77.8%；完整加速后延迟 449.6→33.0 ms，成功率为 75.0%。",
    strengths: "数据扩展、跨本体动作接口和部署时延在同一实验链中验证；标准与扰动真机任务都有逐任务统计。",
    limitations: "所有真机任务仍在 Franka/DROID 接口上，120,000 小时数据包含专有视频；相机视角变化仍是 LIBERO-Plus 的主要瓶颈。",
    transfer: "大规模无动作视频更适合作为因果动态预训练，而不是直接混入动作监督；跨本体阶段需先统一物理语义，再做目标本体校准。",
    technique: [
      "统一动作表示把末端位姿、夹爪、关节、躯干、底盘和灵巧手映射到 100 维语义槽位，并用有效性 mask 屏蔽各本体不存在的维度。",
      "视频预训练使用三视图画布和视图有效性 mask；慢分支负责长时预测，快分支在当前观测下闭环修正，随后用分布匹配蒸馏减少去噪步数。",
    ],
    evaluation: [
      "四档训练数据在相同 DROID 后训练配方下比较，整体真机成功率 36.1%→46.1%→进一步随 60K/120K 小时第一视角视频增长至 77.8%。",
      "异步双系统将延迟降至 145.6 ms，蒸馏与编译再降至 33.0 ms；75.0% 成功率比未蒸馏双系统低 2.8 点，体现明确的速度—性能折中。",
    ],
    comparison: "π0.5、DreamZero、InternVLA-A1.5 等外部基线，以及数据规模、单慢分支/双系统、蒸馏和编译消融。",
    reproducibilityStatus: "资源较完整",
    implementation: ["已公开项目页与代码；正文披露数据配方、60k/160k 训练步数、8 步推理、视图 mask 和 RTX 4090 延迟协议。"],
    missing: ["完整 12 万小时专有视频和训练算力细目不能全部复现；跨本体真机仍需更多硬件验证。"],
    figureFile: "2609.00188-fig2.png",
    figureAlt: "ZimaBlue 视频预训练、跨本体中期训练、目标本体后训练和 Slow-Fast 部署架构",
    figureCaption: "Figure 2 · ZimaBlue 的三阶段训练与异步 Slow–Fast 世界动作模型。来源：arXiv 原图。",
  },
  {
    title: "Motus2: A Self-Evolving General World Model for Dexterous Manipulation",
    arxivId: "2608.30237",
    url: "https://arxiv.org/abs/2608.30237",
    institutions: ["GensPI", "Tsinghua University", "Beihang University", "Beijing Institute of Technology"],
    signal: "用同一组参数同时实现策略、动作条件模拟器和价值评估器，并把人类视频、失败轨迹、长时记忆与触觉纳入自改进闭环。",
    tags: ["World Model", "Dexterous Manipulation", "Model-based RL"],
    classification: { research: "WM", training: "Pre-training", modalities: ["Tactile"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "灵巧手"], deployment: "真机部署优化" },
    motivation: "只模仿专家动作无法利用失败与次优交互，也缺少对后果和价值的显式接口；长时遮挡与接触又要求历史和触觉反馈。",
    methodSummary: "Motus2 采用 action-first 因子化：策略提出动作块，模拟器预测视觉后果，评估器给出价值；预测和价值再用于 Best-of-N 规划与模型式强化学习。",
    architecture: "共享视频—动作 Transformer 暴露 policy/simulator/evaluator 三个接口，并提供全局自回归或混合工作记忆；轻量触觉专家对接触阶段做动作细化。",
    data: "约 130,000 小时单目/双目第一视角视频用于预训练；机器人阶段把专家成功轨迹用于动作学习，把失败和次优轨迹用于动态与价值监督。",
    experiments: "五项灵巧真机任务各 20 次，另在两项长时记忆任务做仿真 25 次/真机 20 次，并评估模型式后训练、规划和触觉组件。",
    novelty: "目标机器人 SFT 中，第一视角预训练把宏平均从 0% 提至 51%，机器人中期训练再到 84%；全局自回归记忆真机平均 57.5%，混合记忆为 25%。",
    strengths: "政策、世界预测与价值共享参数，真实测试同时覆盖灵巧手、记忆和触觉；数据角色按成功/失败轨迹明确拆分。",
    limitations: "130K 小时语料含商业采购数据；每个真机任务 20 次，长时记忆仅两项探针，闭环自改进仍未证明长期稳定。",
    transfer: "失败数据不必直接进入动作 BC，可用来监督后果和价值；长时任务中，全局因果历史可能比压缩记忆更可靠。",
    technique: [
      "action-first 链建立动作 A→未来视觉 Z→价值 U 的因果顺序，同一主干按查询类型切换策略、模拟和评价接口。",
      "MBRL 更新策略参数，Best-of-N 只改变推理；全局自回归保留完整历史，触觉专家则在共享检查点上注入局部接触校正。",
    ],
    evaluation: [
      "五项真机主实验中 Midtrain-SFT 达到 84% 宏平均：Place Ball/Attach Eraser 100%，Screw Bulb 90%，Multi-Finger 70%，Put Phone 60%。",
      "记忆对照在仿真为 78% vs. 52%，真机为 57.5% vs. 25%；触觉消融和 MBRL/规划使用同一中期训练检查点，减少初始化差异。",
    ],
    comparison: "WAN-SFT、仅第一视角预训练、机器人中期训练，模型式 RL/规划、两类记忆和有无触觉的成组消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文给出 130K 小时数据构成、动作优先因子化、各任务 rollout 数、记忆与触觉训练设置。"],
    missing: ["商业数据、完整权重与数据清洗管线未完全开放；多次独立 MBRL 训练方差未充分报告。"],
    figureFile: "2608.30237-fig1.png",
    figureAlt: "Motus2 策略、世界模拟器、价值评估器和自改进闭环",
    figureCaption: "Figure 1 · Motus2 的共享世界模型、价值引导自改进、记忆与触觉接口。来源：arXiv 原图。",
  },
  {
    title: "Facet-0: A Robotic Foundation Model for Contact-Rich Precise Manipulation",
    arxivId: "2609.01596",
    url: "https://arxiv.org/abs/2609.01596",
    institutions: ["PINE Lab, Nanyang Technological University"],
    signal: "把动作块与未来六轴腕力共同生成，再用分布式 action–wrench critic 和小型在机 actor 处理亚毫米装配。",
    tags: ["Force", "Precision Assembly", "RL Post-training"],
    classification: { research: "VLA", training: "RL", modalities: ["Force / Torque"], data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://pine-lab-ntu.github.io/facet-0/" }],
    motivation: "几何进度相同的装配动作可能分别对应顺利插入与卡死，仅靠视觉或成功标签难以给接触关键阶段分配信用。",
    methodSummary: "Facet-0 让 flow action expert 联合预测动作与其后续腕力，用分布式 critic 区分接触后果，再冻结大部分表示，以受限 actor 在新零件上做在机适配。",
    architecture: "视觉语言、运动状态和因果腕力历史进入共享表征；粗粒度 action–wrench expert 以 5–10 Hz 规划，精修 expert 以 20 Hz 更新，critic 读取动作与预测腕力分布。",
    data: "ManuFacet-1K 约 1,000 小时，覆盖三种本体、多制造单元和 CPU/RAM/硬盘/GPU 四类安装；每帧含三路 RGB、13 维状态和同步六轴腕力。",
    experiments: "五项计算机装配任务均按预注册协议各 20 次，容差 0.10–0.30 mm；另做语义—接触对齐、critic、局部 actor、人类干预和新模块少样本适配消融。",
    novelty: "五项任务平均 82%，强匹配基线 15%；0.5 mm 放置精度、50 ms 命令延迟，失败恢复 81% 对比 44%，人类干预 24% 对比 47%。",
    strengths: "真机任务难度、力同步数据和组件消融充分；把预测腕力保留为后果监督而非直接力命令，接口较清楚。",
    limitations: "任务集中在固定制造单元和四类计算机部件；数据与安全阈值高度依赖设备，跨工厂复现成本高。",
    transfer: "接触任务可让动作头预测将产生的力轨迹，再用分布 critic 识别几何相似但接触结果不同的动作。",
    technique: [
      "条件 flow matching 在 13 维联合目标上学习 7 维可执行动作与 6 维未来腕力；辅助腕力头只提供后果约束，最终仍执行笛卡尔动作。",
      "阶段感知奖励和 N-step 接触信用集中更新关键接触段；局部 actor 只训练 6.6% 参数，并受冻结策略与动作边界约束。",
    ],
    equations: [{ name: "联合动作—腕力流", expression: "Yₜ = [Aₜ:ₜ₊H₋₁, Wₜ₊₁:ₜ₊H]", explanation: "同一生成目标同时描述动作块和动作之后预期出现的腕力轨迹。" }],
    evaluation: [
      "完整系统 82%，仅语义—接触对齐 16%，加入价值引导 38%，再加入受限局部适配达到 82%，组件增益顺序清晰。",
      "对相同部署语料的 advantage-weighted BC，Facet-0 将干预从 47% 降至 24%，恢复率从 44% 提到 81%；新模块用 10 条示范、3 小时训练达到 45%。",
    ],
    comparison: "RECAP 式后训练、advantage-weighted BC、无接触对齐/无 critic/无局部适配及奖励结构消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页与正文披露数据比例、13 维联合目标、控制频率、每格 20 次试验和主要优化公式。"],
    missing: ["ManuFacet-1K 全量下载与训练权重开放范围尚不明确；安全包络和多中心硬件标定较难复现。"],
    figureFile: "2609.01596-fig3.png",
    figureAlt: "Facet-0 动作腕力联合生成、critic 后训练和局部适配架构",
    figureCaption: "Figure 3 · Facet-0 的 action–wrench 生成、价值学习与受限在机适配。来源：arXiv 原图。",
  },
  {
    title: "One Demonstration, Many Objects: Generalizing Manipulation via Local Contact Geometry",
    arxivId: "2609.01938",
    url: "https://arxiv.org/abs/2609.01938",
    institutions: ["Stanford University"],
    signal: "从一次人类演示提取局部接触几何，用表面对齐与持续接触奖励训练残差 RL，再蒸馏成仅依赖 RGB-D 的灵巧手策略。",
    tags: ["Dexterous Manipulation", "Human Demonstration", "Sim2Real"],
    classification: { research: "VLA", training: "RL", modalities: ["Depth / RGB-D"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "灵巧手"], deployment: "Sim2Real" },
    resources: [{ label: "项目页", url: "https://demomimic.github.io/" }],
    motivation: "人手轨迹可扩展，但直接重定向无法消除人体—机器人几何和接触动力学差异，现有 residual RL 又常只追物体位姿而忽略接触质量。",
    methodSummary: "DemoMimic 先重定向单次人类演示并做物体尺度/几何增强，再以接触对齐和持续接触奖励训练仿真 residual RL，最后把教师蒸馏到腕部深度闭环策略。",
    architecture: "高层策略从初始 RGB 预测腕部参考轨迹，低层策略读取腕部深度、参考轨迹和本体状态；部署不使用仿真特权状态和显式物体位姿。",
    data: "每个任务从一段人类动作参考出发，仿真 rollout 生成学生 imitation 数据；真实评测覆盖 4 项任务、16 个物体和 Tesollo/Sharpa 两种五指手。",
    experiments: "每个物体—任务组合 20 次真机，仿真消融跨 3 个种子共 300 次；比较 HERMES、DexMachina、去掉表面对齐或持续接触奖励。",
    novelty: "16 个物体、4 项任务、两种手的真机平均成功率 71%；Sharpa/Tesollo 分别 76%/65%，且比仿真表现更高的基线保留了更小的 sim-to-real 落差。",
    strengths: "真实物体在形状、尺寸、质量和摩擦上变化，消融直接落到真机接触与掉落；对局部接触几何的适用边界也有失败例。",
    limitations: "高层腕轨迹从单帧开环产生，任务固定；局部几何必须相似，弧形盒盖使成功率降到 39%，工作空间随机化也较有限。",
    transfer: "灵巧操作从人类视频迁移时，优先保留接触点附近的局部几何与持续接触，而不是要求整件物体外形一致。",
    technique: [
      "Alignment Reward 约束手指沿物体表面以正确方向接触；Sustained Contact Reward 对连续接触时长做二次增长，并设置最小接触力阈值。",
      "Residual RL 在仿真使用特权状态学习，随后 rollout 成无特权数据；低层深度策略闭环执行，高层 RGB 策略只给全局腕部引导。",
    ],
    evaluation: [
      "完整方法跨 16 物体达到 71%，两种不同灵巧手结果接近；唯一明显退化来自改变任务相关局部接触结构的弧形盒盖。",
      "HERMES/DexMachina 在仿真可得高分但真机接触位置、力与掉落显著变差；去除任一接触奖励都增加真机失败，二者作用互补。",
    ],
    comparison: "HERMES、DexMachina、仅任务奖励、去掉表面对齐、去掉持续接触奖励，以及仿真—真机成对结果。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页与正文给出人类轨迹重定向、奖励项、相机与双 Franka/两类灵巧手配置、rollout 数和域随机化。"],
    missing: ["尚未确认完整训练代码和仿真资产；高层策略闭环化与更大工作空间仍未验证。"],
    figureFile: "2609.01938-fig2.png",
    figureAlt: "DemoMimic 从人类示范到 residual RL、蒸馏和真机策略的完整流程",
    figureCaption: "Figure 2 · DemoMimic 的参考轨迹、接触奖励、仿真教师与 RGB-D 学生。来源：arXiv 原图。",
  },
  {
    title: "GIFT: Guided Intermediate Feature Training via Action-Oriented Structural Supervision for Robotic Manipulation",
    arxivId: "2609.04193",
    url: "https://arxiv.org/abs/2609.04193",
    institutions: ["Institute of Automation, Chinese Academy of Sciences", "National University of Singapore", "Tsinghua University", "Fudan University"],
    signal: "用几何、affordance 与目标区域监督训练中间特征，并在推理时移除辅助头；同一配方适配 VLA 与两种 WAM。",
    tags: ["Representation Learning", "Geometry", "Affordance"],
    classification: { research: "表征学习", training: "Post-training", modalities: ["Point Cloud / 3D", "Mask / Segmentation"], platforms: ["机械臂", "Humanoid", "夹爪", "灵巧手"] },
    resources: [{ label: "项目页", url: "https://openphoenix-team.github.io/GIFT-pages" }],
    motivation: "视觉语言预训练和视频预测会保留大量与控制无关的外观信息，却不保证中间特征含有运动可行性、操作对象和目标动作区域。",
    methodSummary: "GIFT 把几何、affordance 和 goal-region 三类结构转成训练期约束，分别接入 VLA、直接 WAM 和逆动力学 WAM；默认不把辅助预测回灌动作头。",
    architecture: "中间视觉 token 接三个轻量监督头，目标来自几何模型、实体/末端配置和目标区域重建；辅助头在部署时删除，动作接口保持不变。",
    data: "使用 LIBERO 原始轨迹、LIBERO-Plus 七类扰动和 RoboCasa GR1 的 24 任务×1,000 条示范；真机测试包含未见视觉与空间扰动。",
    experiments: "LIBERO 每任务 50 次，RoboCasa 每任务 50 次，并对三种结构监督、注入/不注入和不同策略主干做完整消融；另有真机扰动测试。",
    novelty: "在三种主干上 LIBERO-Plus 分别达到 79.6%、72.6%、87.8%，较匹配基线 +4.6/+12.6/+5.2；RoboCasa 三者提升 +12.6/+9.0/+8.4。",
    strengths: "不是只在单一 VLA 上验证，三种监督的互补和是否回灌动作头均有对照；跨仿真基准与真机扰动。",
    limitations: "结构标签依赖外部几何与标注流程；收益受中间层选择和目标质量影响，真机规模小于仿真评测。",
    transfer: "将辅助预测当作表征约束而非部署输入，可减少推理接口改变；同时应验证三类结构是否真正互补。",
    technique: [
      "Geometry 监督保留运动可行的空间结构，affordance 监督定位指令相关实体及末端配置，goal reconstruction 聚焦任务相关动作区域。",
      "默认 no-injection：训练期优化中间层，部署时丢弃辅助头；注入消融反而较弱，说明收益来自特征整形而非额外条件。",
    ],
    evaluation: [
      "三种 GIFT 实例在 LIBERO-Plus 七种分布偏移上都超过匹配基线；WAM 在 RoboCasa 关节物体任务的增益尤其明显。",
      "单项指导、组合指导和注入方式均被单独消融；注意力可视化显示任务对象与交互区域更集中，作为行为结果之外的机制证据。",
    ],
    comparison: "三类匹配 VLA/WAM 基线、单指导与全指导、同头无指导、injection/no-injection 以及真机扰动对照。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页和正文给出三个监督目标、接入层、基准任务数与 rollout 协议。"],
    missing: ["训练代码和全部目标生成管线的开放状态尚待确认；真机逐任务数量未如仿真部分详细。"],
    figureFile: "2609.04193-fig2.png",
    figureAlt: "GIFT 几何、affordance 和目标区域结构监督架构",
    figureCaption: "Figure 2 · GIFT 在 VLA/WAM 中间特征上的三类训练期结构监督。来源：arXiv 原图。",
  },
  {
    title: "ZETA: A Controlled Study of Zero-Shot Cross-Embodiment VLA Transfer for Tabletop Manipulation",
    arxivId: "2609.02546",
    url: "https://arxiv.org/abs/2609.02546",
    institutions: ["Galbot", "Peking University"],
    signal: "在 14 个留出本体上控制任务与场景，分别量化局部末端动作、预训练本体多样性、辅助目标和少量目标本体暴露的作用。",
    tags: ["Cross-Embodiment", "VLA", "Controlled Study"],
    classification: { research: "VLA", training: "Pre-training", data: "跨本体数据", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    motivation: "文献把“目标本体从未出现”和“只在预训练出现过”都称为零样本，且任务、场景、相机常同时变化，难以归因。",
    methodSummary: "ZETA 定义 strict 与 pretrain-exposed 两类协议，在同一 tabletop 任务中只改变本体，并控制比较动作坐标系、源本体数量、辅助训练目标和目标本体暴露比例。",
    architecture: "统一 VLA 主干读取腕部与第三视角；关键变量是 EEF-Delta 状态/动作表示，用当前末端坐标表达局部运动，减少对机器人基座和运动学的绑定。",
    data: "生成 512 个 Franka 风格源本体，固定 640K 轨迹预算或固定每本体预算；七个商业机器人仅作留出目标，三项仿真任务与两项真机任务共享协议。",
    experiments: "每模型仿真 3 任务×7 本体×100 次×3 run，共 6,300 rollout；真机 2 任务×7 本体×10 次，分 appearance/gripper/arm/full shift。",
    novelty: "EEF 局部表示约 +15 点，512 源本体约 +18 点，辅助目标约 +7 点；真机 EEF-Delta/EEF-Delta 平均进度 89.9%，其他表示为 56.0–61.6%。",
    strengths: "把零样本定义、数据预算和本体变化拆开；仿真有三次训练重复，真机覆盖七种目标硬件。",
    limitations: "只研究固定桌面、两指夹爪与准静态任务；移动底盘、灵巧手和长时任务尚未覆盖，真机每格 10 次。",
    transfer: "跨本体项目应明确目标硬件是否在预训练出现，并优先采用本体兼容的局部末端坐标；源本体数量需与每本体数据密度一起报告。",
    technique: [
      "EEF-Delta 用当前夹爪坐标表达下一步位姿变化，状态历史同样改写为局部相对变换；state-free 可视作历史长度为零的退化形式。",
      "辅助 co-training 在相同动作语义下学习语言—动作或相关目标；5% 目标本体预训练用于区分严格零样本和预训练见过本体的转移。",
    ],
    equations: [{ name: "局部末端动作", expression: "aₜ = V(Tₑₜ,ₑₜ₊₁)", explanation: "下一动作在当前末端坐标系中表达，以减少不同基座和臂几何带来的坐标差异。" }],
    evaluation: [
      "仿真中 EEF 表示对 arm-only 和 full-embodiment 变化最有效；固定总预算时源本体数量的真机曲线非单调，暴露出覆盖与密度折中。",
      "仅 5% 目标本体预训练使 UR5eUMI 69.3→78.6、Google Robot 51.4→68.9，但仍低于目标任务后训练 oracle。",
    ],
    comparison: "四种状态/动作坐标组合、1–512 源本体两种预算控制、不同辅助目标和 0–5% 目标本体暴露。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文公开协议定义、源/目标本体拆分、轨迹预算、任务、相机和每模型 rollout 规模。"],
    missing: ["程序化本体生成与完整训练代码开放状态未确认；真实移动与灵巧本体不在当前范围。"],
    figureFile: "2609.02546-fig1.png",
    figureAlt: "ZETA 严格零样本跨本体评测和四类本体变化",
    figureCaption: "Figure 1 · ZETA 的 strict/pretrain-exposed 协议与受控跨本体变量。来源：arXiv 原图。",
  },
  {
    title: "RoboTok: An Internet-Scale Data Engine for Human Demonstration Retrieval and Dexterous Manipulation Learning",
    arxivId: "2609.03199",
    url: "https://arxiv.org/abs/2609.03199",
    institutions: ["Rice University", "NVIDIA"],
    signal: "把互联网视频中的双手 3D 轨迹变换到人体中心坐标，以时空轨迹对齐监督检索编码器，再把检索结果用于灵巧操作 RL。",
    tags: ["Human Video", "Retrieval", "Dexterous Manipulation"],
    classification: { research: "表征学习", training: "Pre-training", modalities: ["Point Cloud / 3D"], data: "UMI / Ego / Human Video", platforms: ["灵巧手"] },
    motivation: "互联网视频量大但外观、相机和遮挡差异强；语言或图像相似不等于手部操作运动相似，直接全库 DTW 又无法扩展。",
    methodSummary: "RoboTok 过滤人类操作片段、重建 3D 手部关键点并转入 actor-relative 坐标，用 DTW 相似度训练轻量 embedding，支持向量检索和持续索引。",
    architecture: "离线数据引擎做视频过滤、手部重建、人体坐标标准化和 embedding 建库；查询时以演示视频找近邻，再将轨迹引导输入灵巧操作策略训练。",
    data: "检索模型使用持续扩展的互联网视频索引，并在 RoboTok 评测集与带真实 3D 手姿的 AssemblyHands 做跨域测试；下游使用 VTDexManip。",
    experiments: "比较视觉 flow、HAND、STRAP 等检索器的 mAP/Recall/Kendall τ/DTW，并在更难的灵巧仿真任务中训练 PPO 检查下游收益。",
    novelty: "RoboTok mAP@20 0.353、Recall@20 0.996，STRAP 为 0.007/0.12；AssemblyHands mAP@5 0.261，对比 0.133。",
    strengths: "既测检索排序也检查下游策略；actor-relative 轨迹降低视角和外观依赖，AssemblyHands 提供留出域验证。",
    limitations: "下游策略证据来自仿真而非真机；3D 手部估计误差、视频版权和接触力缺失会限制大规模索引质量。",
    transfer: "非机器人视频检索应以任务相关运动几何作监督，再用策略结果验证检索是否真有用，而不是只看语义相似。",
    technique: [
      "用人体/物体相对参考系规范化 3D 手部轨迹，DTW 作为昂贵的教师距离，轻量编码器学习可做近邻搜索的向量空间。",
      "检索结果保留手部姿态和时序结构，随后作为 PPO 的演示引导；新增视频只需通过离线索引管线，无需重建固定数据集。",
    ],
    evaluation: [
      "在伪真值 DTW 检索集上 Recall@20 接近 1，且 Kendall τ 0.487 表明近邻内部排序也更合理。",
      "AssemblyHands 留出域维持所有指标领先；下游 VTDexManip 说明运动检索能改善策略，但尚缺物理硬件闭环。",
    ],
    comparison: "FlowRetrieval、HAND、STRAP、随机与 DTW oracle，以及检索演示驱动的 VTDexManip PPO。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文给出 3D 手轨迹、actor-relative 变换、DTW 教师、向量检索与两套检索指标。"],
    missing: ["未确认完整互联网索引、过滤模型与训练代码开放；没有真机下游实验。"],
    figureFile: "2609.03199-fig4.png",
    figureAlt: "RoboTok 与基线对刀具切割示范的手轨迹检索对比",
    figureCaption: "Figure 4 · RoboTok 以人体中心手轨迹检索相似操作，而非只匹配外观。来源：arXiv 原图。",
  },
  {
    title: "Temporal Forcing: 4D Representation Alignment for Vision-Language-Action Models",
    arxivId: "2608.30643",
    url: "https://arxiv.org/abs/2608.30643",
    institutions: ["Institute of Automation, Chinese Academy of Sciences", "Nanjing University"],
    signal: "用预训练 4D 模型的因果几何特征监督 VLA 历史通道，使被遮挡的任务进度能进入动作表征，推理时不保留教师。",
    tags: ["4D Representation", "Memory", "VLA"],
    classification: { research: "Memory", training: "Post-training", modalities: ["Point Cloud / 3D"], platforms: ["机械臂", "夹爪"] },
    detailAttributes: { memoryImplementation: "Context / Sequence", memoryHorizon: "短时因果历史" },
    motivation: "逐帧 3D 对齐只能看见当前几何，无法知道物体此前被放入哪里或哪些步骤已完成；单纯加入历史通道又可能被模型忽略。",
    methodSummary: "Temporal Forcing 用 StreamVGGT 从更长因果上下文提取 4D 几何目标，分别对齐当前帧和历史 latent；教师与对齐头仅训练时存在。",
    architecture: "VLA 新增长度 7 的历史路径，当前特征接稠密几何对齐，历史轨迹接因果几何特征和变化量对齐；推理只保留历史路径。",
    data: "使用 LIBERO 全四套、RoboTwin 2.0 十二项双臂任务，以及一项包含遮挡、顺序依赖的真机三阶段任务。",
    experiments: "LIBERO 每套 500 次，RoboTwin 十二任务；真机单技能共 90 次、完整序列 30 次，并对无历史、3D/4D 教师、两类 loss 做控制消融。",
    novelty: "LIBERO 96.6→98.8%，RoboTwin 53.5→62.8%；真机完整三阶段成功由 6/30 提升到 13/30，而孤立技能 75/90 与 78/90 接近。",
    strengths: "真机把单技能能力和顺序记忆拆开，避免把更强操作误当记忆收益；3D 与 4D 教师在相同主干上直接对照。",
    limitations: "历史只有数秒，教师特征需离线预计算；真机仅一项受控多阶段任务，尚未覆盖长时开放环境。",
    transfer: "记忆模块需要训练目标迫使它编码状态变化；评价应固定单步技能能力，再观察遮挡后的顺序决策。",
    technique: [
      "历史窗口 K=7，在 LIBERO 跨 2.8 秒、RoboTwin 跨 3.7 秒；StreamVGGT 教师使用最长 12 秒或完整 episode prefix。",
      "当前帧 loss 锚定稠密几何，时序 loss 对齐历史特征及其相邻变化；教师、投影头在部署时全部移除。",
    ],
    evaluation: [
      "LIBERO-Long 从 93.8% 到 97.2%，RoboTwin handover block 0→44、handover mic 39→79，收益集中在当前画面缺历史证据的任务。",
      "仅加历史路径反而低于 base；用 framewise 3D 监督历史为 85.0%，4D 监督为 93.6%，表明信息通道与训练目标缺一不可。",
    ],
    comparison: "base VLA、仅历史、当前帧对齐、framewise 3D 与 causal 4D 教师、不同 loss 组合。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文披露 K=7、教师层、stride 4、训练 GPU、各基准 rollout 数与真机逐阶段计数。"],
    missing: ["未确认训练代码与教师特征缓存发布；更长时间跨度和跨场景历史尚未验证。"],
    figureFile: "2608.30643-fig2.png",
    figureAlt: "Temporal Forcing 历史路径与 4D 几何表示对齐",
    figureCaption: "Figure 2 · 4D 因果教师如何在训练期塑造 VLA 的历史表示。来源：arXiv 原图。",
  },
  {
    title: "Adaptive Vision-Language Grasping via Composable Foundation Priors and Generalizable Grasp Synthesis",
    arxivId: "2609.04096",
    url: "https://arxiv.org/abs/2609.04096",
    institutions: ["Huazhong University of Science and Technology", "Peking University", "KEENON Robotics", "ByteDance"],
    signal: "把物理可行的跨手型抓取生成器与空间、语义和动态先验解耦，无需重训底层策略即可改变任务相关抓法。",
    tags: ["Dexterous Grasping", "Composable Priors", "Cross-Hand"],
    classification: { research: "VLA", training: "BC", modalities: ["Point Cloud / 3D"], data: "跨本体数据", platforms: ["灵巧手"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://adarobovlg.github.io/" }],
    motivation: "端到端视觉语言抓取把物理抓取与任务理解绑在一起，遇到新手型、拥挤、功能部位或运动目标时往往需要重新训练。",
    methodSummary: "AdaRoboVLG 的底层策略用显式运动学映射和力闭合筛选通用抓取，上层分别提供空间、认知与时间先验，并在结构化抓取接口中组合。",
    architecture: "场景点云先产生候选接触—抓取表示，hand-agnostic 决策模型评分稳定性；RAG+CoT 推断功能部位与抓型，跟踪模块更新动态目标。",
    data: "底层使用 GraspClutter6D 与 DexGraspNet 2.0；功能推理采用开放集物体/指令，真机覆盖 102 个日常物体、6 类、510 次试验。",
    experiments: "仿真跨三种灵巧手和三类拥挤程度；真机包含拥挤功能抓取、移动传送带 5 Hz 更新和四种人为扰动。",
    novelty: "仿真平均成功率 88.4%；真机功能抓取 83.3%/510 次，四类扰动平均 89.7%，功能部位和抓型推理准确率 94.0%/87.0%。",
    strengths: "真实物体数量和试验次数较充足，并覆盖跨手型、动态目标和人为干扰；物理抓取与语义先验接口清晰。",
    limitations: "系统依赖多个外部 foundation 模块和点云质量，端到端延迟与各模块错误传播较复杂；大多任务停在抓起而非后续操作。",
    transfer: "将长期稳定的物理抓取生成与快速迭代的语义/动态先验分离，可降低新任务适配成本。",
    technique: [
      "跨手型基座通过显式运动学映射复用接触抓取表示，并以 force-closure 估计而非语言模型判断物理稳定性。",
      "空间先验处理拥挤碰撞，认知先验用 RAG+CoT 选功能部位和抓型，时间先验持续跟踪传送带目标；三者可组合。",
    ],
    evaluation: [
      "在 DexGraspNet 2.0 的 random/loose split，相比 AnyDexGrasp 平均 +3.0/+9.2 点；对相同候选的对照也显示评分器有独立贡献。",
      "510 次真机试验覆盖 102 件物体，动态和四类人扰实验进一步检查 5 Hz 更新与扰动恢复，不只报告静态抓取。",
    ],
    comparison: "AnyDexGrasp 及相同候选版本、不同手型/拥挤度、RAG/CoT 消融、静态与动态/扰动真机。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文给出接触抓取网络来源、噪声幅度、稳定阈值 0.5、评测手型与真实试验规模。"],
    missing: ["完整系统代码与全部外部模型提示/接口未确认开放；复杂任务的抓后操作未评估。"],
    figureFile: "2609.04096-fig1.png",
    figureAlt: "AdaRoboVLG 将任务先验与通用物理抓取合成解耦",
    figureCaption: "Figure 1 · 空间、认知与时间先验通过结构化接口组合到通用抓取器。来源：arXiv 原图。",
  },
  {
    title: "FWBC-VLA: Force-Aware Whole-Body Compensation for Contact-Rich Loco-Manipulation",
    arxivId: "2609.03889",
    url: "https://arxiv.org/abs/2609.03889",
    institutions: ["Zhejiang University", "Shanghai AI Laboratory", "Tsinghua University", "Deep Robotics"],
    signal: "不用腕部力传感器，从全身本体状态估计残余关节力矩，同时给 VLA 动作头和 whole-body compensation 提供接触反馈。",
    tags: ["Force Estimation", "Loco-Manipulation", "Whole-Body Control"],
    classification: { research: "VLA", training: "Post-training", modalities: ["Force / Torque", "State / Proprioception"], data: "其他数据方法", platforms: ["轮式底盘", "机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "移动操作中的末端外力会传到机身；仅给 VLA 运动学命令或只让 WBC 稳定身体，都无法区分任务接触和外部扰动。",
    methodSummary: "HSR-Force 用历史/当前状态双 LSTM 估计自由运动力矩并取残差，短时接触 token 注入 π0.5 动作专家；同一力估计再驱动有界机身补偿。",
    architecture: "200 Hz 力估计链输出残余力矩、接触强度和趋势，15 Hz VLA 跨注意力读取 13 帧力 token；补偿支路结合 IMU、body-frame load 与底盘命令。",
    data: "WL&Arm 超过 5,000 条遥操作 episode，含 200 Hz 关节数据和 15 Hz 多视角操作示范，主要为搬瓶、擦白板和开门。",
    experiments: "DeepRobotics M20S+CM1 在擦白板和带/不带 50 N 闭门器的开门任务各方法 25 次；力估计另用 25 条人工审查 episode 和 5 个种子。",
    novelty: "擦白板最终成功 64%、开门 52%，均比最强基线高 40 点；force interaction 后平均 12→35%，再加 body compensation 到 59.5%。",
    strengths: "估计器、动作反馈和机身补偿逐级消融；有真实载荷标定、接触 AUC 和长时阶段成功率，而非只看最终任务。",
    limitations: "两项任务和一种轮腿平台仍较窄；残差力不是标定后的直接外力，估计误差对策略性能的边界尚不明确。",
    transfer: "没有 F/T 传感器时，可把全身残余力矩作为共享物理接口，同时服务高层动作修正与低层稳定。",
    technique: [
      "历史专家降低自由运动噪声，当前状态专家保留接触敏感性；固定 gate 融合后形成因果残差，13 个 200 Hz 样本覆盖最近 60 ms。",
      "力 token 只在 action expert 最后隐层做跨注意力；补偿输出经死区、低通、slew-rate 与 headroom 裁剪后交给 WBC。",
    ],
    equations: [{ name: "力条件动作残差", expression: "Z̃_action = Z_action + α_f g_t CA(Z_action, Z_force)", explanation: "动作 token 查询短时力 token，并由可学习接触 gate 控制注入强度。" }],
    evaluation: [
      "相同 50k 步微调和 16 维动作接口下，与 OpenVLA、StarVLA、π0.5、GR00T、ACP、ForceVLA 及真实 F/T 版本比较。",
      "擦白板 Wiping/最终为 76%/64%，开门 Manipulate/Push/Cross 为 56%/52%/52%；补偿收益集中在持续高载荷阶段。",
    ],
    comparison: "多种 VLA、F/T 条件策略、真实力 FWBC-GT、双专家估计器和去除 force interaction/body compensation 消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["披露数据频率、K=13/60 ms、15 Hz 策略、200 Hz 估计、50k 微调与每任务 25 次协议；数据计划公开。"],
    missing: ["WL&Arm 与完整代码当前尚未确认上线；更广平台和力估计误差敏感性未报告。"],
    figureFile: "2609.03889-fig3.png",
    figureAlt: "FWBC-VLA 传感器无关力估计、动作条件和全身补偿双反馈",
    figureCaption: "Figure 3 · HSR-Force 同时连接 VLA action expert 与 whole-body compensation。来源：arXiv 原图。",
  },
  {
    title: "Scaling Bimanual Household Manipulation from 1,500 hours of Demonstrations to On-Policy Corrections",
    arxivId: "2609.03591",
    url: "https://arxiv.org/abs/2609.03591",
    institutions: ["PrimeBot Research Institute", "Peking University", "Crobotia"],
    signal: "公开 1,500 小时双臂家务数据，并展示专家数据在约 120 小时后趋于饱和，针对策略失败采集的 DAgger 修正继续把成功率推到 93%。",
    tags: ["Bimanual", "Data Scaling", "DAgger"],
    classification: { research: "VLA", training: "Post-training", data: "在线数据 / 人工纠正", platforms: ["轮式底盘", "机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "模型", url: "https://huggingface.co/datasets/challenge-2026/challenge_data" }],
    motivation: "大规模专家示范最终会在已覆盖状态上饱和，而部署失败出现在策略自己访问的分布；两类数据需要分阶段利用。",
    methodSummary: "XR-2 先用全量专家数据做 conditional flow BC，再让共享策略在真实机器人上运行，人在失败子任务短暂接管，按弱项分配 DAgger 预算后聚合训练。",
    architecture: "5B VLM+action expert 全参数训练，输出 50×25 动作块；异步推理 10 Hz、时序集成后 30 Hz 下发，全身控制器以 1,000 Hz 执行。",
    data: "531.7 小时、32,518 条真机轨迹、57.4M 帧，加约 1,000 小时双腕 UMI；超过 200 户、100 位采集者、5,000 件衣物，带任务/子步骤语言。",
    experiments: "衣物折叠从 10–160 小时扫描专家数据规模，再从 58% 检查点做三轮真机 DAgger；测试含材质尺寸、颜色和初始机器人位置变化。",
    novelty: "专家数据从 30 小时 34% 增长到 120 小时 84%，160 小时回落至 82%；三轮 DAgger 从 58%→74%→82%→93%。",
    strengths: "真实数据量和采集多样性大，并明确显示 expert scaling 饱和后 on-policy 修正的补充价值；含长时与子技能标注。",
    limitations: "主要深入实验集中在折衣服，未给全部 12+ 家务任务统一基线；DAgger 仍依赖人工实时接管。",
    transfer: "当继续堆专家数据不再改善时，应按当前策略失败率分配在线纠正，同时给已掌握子任务保留最低采样份额以防遗忘。",
    technique: [
      "每轮把 DAgger 与专家轨迹按条数 1:1 混合，避免不同 episode 长度让帧级采样扭曲技能比例。",
      "纠正预算按 (1−成功率) 分配并设置 5% 下限；弱项得到更多修正，强项仍保留数据以抑制遗忘。",
    ],
    equations: [{ name: "失败加权纠正预算", expression: "wᵢ ∝ (1 − sᵢ + ε)^α,  wᵢ ≥ 0.05", explanation: "成功率越低的子任务获得越多 DAgger 轨迹，同时保留最低覆盖。" }],
    evaluation: [
      "专家数据曲线在 120 小时达到 84% 后饱和，说明额外同分布演示无法覆盖策略诱发失败状态。",
      "三轮 DAgger 每轮 2.5 epoch，从 58% 连续升到 93%；测试带轻度物体与机器人初态变化，但论文未报告多 seed。",
    ],
    comparison: "不同专家数据时长、专家-only 检查点与三轮 DAgger，以及弱项加权的数据分配。",
    reproducibilityStatus: "资源较完整",
    implementation: ["数据入口已给出；正文披露真机/UMI 规模、频率、动作块、数据混合、预算公式和每轮训练 epoch。"],
    missing: ["完整 XR-2 权重和 DAgger 远程操作系统开放状态未确认；多任务统一评测和训练方差不足。"],
    figureFile: "2609.03591-fig4.png",
    figureAlt: "XR-2 专家示范训练和 DAgger 在线纠正两阶段流程",
    figureCaption: "Figure 4 · XR-2 从离线专家 BC 到策略访问状态上的在线人工纠正。来源：arXiv 原图。",
  },
  {
    title: "WISE: World-model-guided Imagination Scheduling for Efficient Post-training of Vision-Language-Action Models",
    arxivId: "2609.03681",
    url: "https://arxiv.org/abs/2609.03681",
    institutions: ["Tsinghua University", "Beijing Academy of Artificial Intelligence"],
    signal: "只在交互关键状态调用世界模型，用短程反事实后果排序候选动作，再以真实上下文做偏好式后训练。",
    tags: ["World Model", "Post-training", "Selective Imagination"],
    classification: { research: "WAM", training: "Post-training", data: "合成 / 仿真数据", platforms: ["机械臂", "夹爪"] },
    motivation: "全程、长时想象计算昂贵且误差累积；粗略运动状态往往已由 VLA 解决，真正需要预测的是接触与决策关键点。",
    methodSummary: "WISE 检测交互相关状态，只在这些位置采样候选动作和有界未来；世界模型只负责相对评价，策略更新仍监督真实状态的首个动作块。",
    architecture: "imagination–evaluation–optimization 三段环：调度器选状态，世界模型短程 rollout，进度/完成/置信度奖励排序，再形成偏好损失。",
    data: "MimicGen 的 Stack、Coffee、Square、Threading、Mug Cleanup 五项任务，两个基础策略 π0/π0.5，并补充真实机器人场景。",
    experiments: "比较 BC、DPO、full/uniform/random imagination；对 reward 组件、调度比例、GPU 时间做消融，并在两种 backbone 上复验。",
    novelty: "π0 平均 49.7→59.5%，π0.5 为 52.3→60.2%；相对 full imagination 少约 80% 状态、GPU 时间少 77%，成功率反高 7.9 点。",
    strengths: "把调用次数、GPU 小时和成功率一起比较；只让想象参与候选评价，避免直接训练在合成状态上。",
    limitations: "主要表格来自 MimicGen，真机规模有限；状态选择和 reward model 在更强分布偏移下可能同时失效。",
    transfer: "世界模型后训练应先回答“何时值得想象”，并把合成后果限制为相对反馈，动作监督仍锚定真实观测。",
    technique: [
      "调度器根据交互相关性筛选状态，候选 rollout 限制在可靠 horizon；进度、终局完成、置信度和后退惩罚组成反事实评分。",
      "优化只取真实上下文的第一个动作块，想象轨迹不直接成为 imitation target，降低模型错误写入策略的风险。",
    ],
    evaluation: [
      "两个 backbone 在五任务上全部高于各自 base；π0 还比最强 DPO 基线高 5.7 点。",
      "完整 reward 平均 68.3%，只用进度或完成均为 57.3%；WISE 以 2.61 GPU 小时胜过相近预算的 uniform/random 7.2/9.2 点。",
    ],
    comparison: "π0/π0.5 base、DPO 等后训练、full/uniform/random imagination，以及 reward 组件和调度消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文给出五项任务、两个 backbone、想象选择率、GPU 小时与 reward 消融。"],
    missing: ["未确认代码与 world/reward model 权重开放；真机任务、试验次数与独立训练重复有限。"],
    figureFile: "2609.03681-fig2.png",
    figureAlt: "WISE 交互关键状态选择、世界模型想象和策略优化流程",
    figureCaption: "Figure 2 · WISE 的选择性想象—评价—真实上下文优化闭环。来源：arXiv 原图。",
  },
  {
    title: "Sensing Which Modality Matters: Evidence-Gated Regularization for Robust VLA Policies",
    arxivId: "2609.03142",
    url: "https://arxiv.org/abs/2609.03142",
    institutions: ["University of North Carolina at Chapel Hill", "Mitsubishi Electric Research Laboratories"],
    signal: "为每帧每传感器构造任务证据分数，低证据模态学不变性、高证据模态学单传感器充分性，部署不增加网络。",
    tags: ["Multimodal", "Robustness", "Regularization"],
    classification: { research: "表征学习", training: "Post-training", modalities: ["Tactile", "State / Proprioception", "其他模态"], platforms: ["机械臂", "轮式底盘"], deployment: "真机部署优化" },
    motivation: "小而同质的机器人示范会让多模态策略记住传感器间偶然相关：无用相机被遮挡也会变动作，而只保留真正有用的传感器时又不会行动。",
    methodSummary: "EGR 以任务属性生成 evidence score，分别 gate 两个一致性 loss：扰动低证据传感器时动作保持不变，只保留高证据传感器时仍能输出正确动作。",
    architecture: "不改 π0.5 主干，仅训练 LoRA；视觉证据来自实例 mask，触觉按接触/任务特征构造，统一进入模态无关的 invariance 与 sufficiency 目标。",
    data: "BEHAVIOR-1K 11 项任务、118 个候选技能，经证据过滤保留 47 个 rollout 技能；同时有两种真实机器人与物理干扰测试。",
    experiments: "先做推理期 action deviation 诊断，再在 Clean/NoUseless/UsefulOnly/SingleUseful 条件每段 20 次 rollout，并报告 SR、接触率和目标距离。",
    novelty: "操作 SR 在 full/no-useless/useful-only 从 12.5/9.4/2.8 提至 16.4/16.5/6.1；导航 single-useful 15.5→37.3，而 clean 基本保持。",
    strengths: "同时测动作偏差和任务完成，并把两类 failure mode 分开；标准误、置信区间和显著性检验放在附录。",
    limitations: "evidence 构造仍需任务特定规则和 mask/接触信息；BEHAVIOR-1K 操作绝对成功率低，真实硬件覆盖有限。",
    transfer: "多模态创新应围绕信息何时有用，而不是默认所有传感器始终融合；训练时分别抑制无用依赖和强化单模态可用性。",
    technique: [
      "低证据模态经过随机矩形遮挡后，策略分布应与完整输入一致；高证据模态单独保留时，也应与完整动作保持一致。",
      "两个 loss 由连续 evidence gate 调节，部署删除所有训练期扰动和 gate，不增加推理参数与时延。",
    ],
    evaluation: [
      "原始 π0.5 在无用模态受损时操作动作偏差 +12.7%，只保留有用模态时 +158.5%，证明两种 entanglement 同时存在。",
      "EGR 在操作三种条件均提升，导航保留 clean 约 41% 同时把单有效传感器条件提高到 37.3%，优于随机 ModDrop。",
    ],
    comparison: "原始 π0.5、ModDrop、EGR，Clean/NoUseless/UsefulOnly/SingleUseful 四类条件及证据过滤消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文与附录列出 LoRA 训练、两项 loss 权重、证据阈值、遮挡算子、47 技能和每段 20 次协议。"],
    missing: ["任务 evidence 规则的自动生成与跨数据集迁移未解决；公开代码状态未确认。"],
    figureFile: "2609.03142-fig1.png",
    figureAlt: "Evidence-Gated Regularization 低证据不变性与高证据充分性训练",
    figureCaption: "Figure 1 · EGR 根据每帧模态证据选择两类一致性约束。来源：arXiv 原图。",
  },
  {
    title: "Spatially Aware World Action Model via Geometric Latent Diffusion",
    arxivId: "2609.02531",
    url: "https://arxiv.org/abs/2609.02531",
    institutions: ["Inria", "PSL Research University"],
    signal: "在预训练视频扩散主干中联合生成 RGB、深度与动作，用几何 latent 同时改善未来预测、失败检测和真实机器人控制。",
    tags: ["WAM", "Depth", "Geometric Latent"],
    classification: { research: "WAM", training: "Post-training", modalities: ["Depth / RGB-D", "Point Cloud / 3D"], platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://jlopetegui98.github.io/projects/sa_wam.html" }],
    motivation: "RGB WAM 可以生成看似合理的未来，却缺少度量几何，遇到相似干扰物、深度歧义或接触偏差时难以判定动作后果。",
    methodSummary: "SA-WAM 将无界深度非线性压到视频 VAE 的输入域，复用冻结 tokenizer，在同一 diffusion backbone 中联合建模 RGB、depth 和 action。",
    architecture: "RGB 与编码深度组成多通道视觉 latent，动作 token 与视频去噪共享 Transformer；对象中心 3D 误差还能作为 rollout 可靠性信号。",
    data: "在 RoboCasa、LIBERO-Plus 和真实 UR5 平台训练；真机 10 项任务每项 20 条示范，评测四类复合任务的 clean 与 randomized 条件。",
    experiments: "与 Cosmos-Policy、π0 和 RGB-only WAM 比较控制与视频质量，并分析 3D 预测误差对成功的 AUC；真机每类别 10 次。",
    novelty: "3D 预测误差检测失败 AUC 约 0.88，在 80% 检出率时误报 13%；随机化 UR5 场景中完成度高于 Cosmos-Policy 与 π0。",
    strengths: "几何预测不仅作为辅助 loss，还用于后果诊断；仿真扰动和真实 RGB-D 控制相互验证。",
    limitations: "真机动作是语义关键点而非高频连续控制，每类别仅 10 次；深度相机和冻结视频 VAE 的编码上限仍存在。",
    transfer: "世界模型加入几何时，应同时检查深度预测是否改善动作和能否识别失败，而不是只报告视觉质量。",
    technique: [
      "非线性深度编码把度量深度映射到冻结 VAE 可处理的有界范围，从而保留视频模型预训练先验。",
      "同一扩散网络联合预测 RGB、depth 与 action；对象中心点云误差作为成功相关指标，连接生成质量和闭环可靠性。",
    ],
    evaluation: [
      "RoboCasa/LIBERO-Plus 同时比较动作成功和未来状态预测，避免单独以 FID 类指标说明控制能力。",
      "UR5 使用 Orbbec RGB-D、20 示范/任务，在四类复合任务 clean/randomized 各 10 次；随机干扰下几何分支优势更明显。",
    ],
    comparison: "Cosmos-Policy、π0、RGB-only WAM，深度编码/几何预测消融，以及 clean/randomized 真机场景。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页与正文给出深度编码、RGB-D 设备、10 任务×20 示范和真机评价协议。"],
    missing: ["代码/权重开放状态未确认；关键点动作接口和较小真机试验限制外推。"],
    figureFile: "2609.02531-fig2.png",
    figureAlt: "SA-WAM RGB 深度动作联合几何 latent diffusion 架构",
    figureCaption: "Figure 2 · SA-WAM 在统一视频扩散主干中联合建模 RGB、深度与动作。来源：arXiv 原图。",
  },
  {
    title: "World-Coherent Decoding: Self-Verifying Test-Time Planning for World Action Models",
    arxivId: "2609.02159",
    url: "https://arxiv.org/abs/2609.02159",
    institutions: ["Institute of Science Tokyo", "DENSO IT Laboratory", "National Institute of Informatics"],
    signal: "把 WAM 的多个未来当作可证伪假设，用视频 surprisal、动作 path effort 与执行后 mismatch 选择更可靠的候选。",
    tags: ["WAM", "Test-time Planning", "Self-verification"],
    classification: { research: "WAM", training: "Test-time Adaptation", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "WAM 的采样未来质量差异大，单纯增加候选数不会自动带来更好控制；需要在执行前判断哪个想象可依赖。",
    methodSummary: "WCD 先以视频 flow surprisal 与动作路径 effort 排序冻结 WAM 候选，执行后用真实观测审计 imagination mismatch，再在线训练轻量可靠性预测器。",
    architecture: "视频与动作两支评分器给即时分，在线 predictor 把延迟获得的想象—现实误差转换成下一步的预执行可靠性；主干不更新。",
    data: "RoboTwin 2.0 50 项双臂任务，含标准和仅 30% 随机场景监督的困难配方；真机用 Franka hammering 做灯光、模糊和杂乱压力测试。",
    experiments: "比较随机 N 候选、单视频/单动作/在线 predictor 与完整评分；报告不同 horizon，真机每种视觉扰动使用固定重置协议。",
    novelty: "有限随机化 Hard 从 55.8% 到 60.9%，Horizon-3 +16.43 点；完整评分比 Random-N +7.4 点、比最强单分支 +5.5 点。",
    strengths: "明确证明“多采样”不足，并分解三类评分贡献；标准近饱和设置与更难设置同时报告。",
    limitations: "真机主要是定性压力测试，缺少大规模成功率表；每步多候选带来额外生成开销。",
    transfer: "test-time scaling 的核心应是候选可靠性而非候选数量，可用执行后的真实差异持续校准选择器。",
    technique: [
      "flow surprisal 衡量视觉未来是否落在 WAM 自身高概率区域，path effort 估计动作生成稳定性；二者处理不同失败。",
      "执行后观察与选中未来的 latent mismatch 作为延迟标签，轻量 predictor 在线学习并在下一步提前筛选。",
    ],
    evaluation: [
      "标准 LingBot-VA Hard 已 91.55%，WCD 仅到 92.28%；有限随机化提供更大不确定性后增益扩大到 5.1 点。",
      "Random-N 在 clean 91.1% 但 Hard 53.5%，完整 WCD Hard 60.9%；Horizon-3 的提升说明选择对长时误差累积更重要。",
    ],
    comparison: "冻结 base WAM、Random-N、视频/动作/online predictor 单分支和完整组合，两种随机化训练量。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文给出候选评分、30% 随机数据配方、18k+18k 步训练和 RoboTwin/Franka 协议。"],
    missing: ["未确认代码开放；真机只有压力测试，候选数与端到端延迟细节不足。"],
    figureFile: "2609.02159-fig3.png",
    figureAlt: "World-Coherent Decoding 多候选评分与执行后自验证流程",
    figureCaption: "Figure 3 · WCD 将视觉 plausibility、动作稳定性和在线可靠性组合为候选选择。来源：arXiv 原图。",
  },
  {
    title: "Knowing When to Stop: Adaptive Action Chunking via Internal Cross-Attention Dynamics in VLAs",
    arxivId: "2609.00908",
    url: "https://arxiv.org/abs/2609.00908",
    institutions: ["Tsinghua University"],
    signal: "监测 action query 对视觉语言 token 的注意力熵，在注意力进入高熵平台时截断动作块，实现无需训练的自适应闭环频率。",
    tags: ["VLA", "Action Chunking", "Training-free"],
    classification: { research: "VLA", training: "Test-time Adaptation", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "固定短块推理频繁且可能振荡，固定长块会逐渐脱离最新观测；不同任务和执行阶段的可靠 horizon 并不相同。",
    methodSummary: "方法读取 action expert 已产生的 cross-attention，计算随 horizon 变化的归一化熵；检测到持续高熵平台就停止执行后续动作并重新观测。",
    architecture: "不修改 π0.5/X-VLA 参数和动作头，仅在执行器侧聚合 action-to-VLM attention；候选序列仍一次生成，截断点动态变化。",
    data: "RoboTwin 2.0 十项任务、LIBERO 四套开放检查点，以及挂杯、叠杯、整理笔三项真机任务。",
    experiments: "π0.5 每任务 50 条 RoboTwin 示范训练 40k 步，三 seed、每配置 100 rollout；比较固定块、multi-sampling 和 self-attention adaptive。",
    novelty: "RoboTwin π0.5 平均 62.9%，LIBERO 由最强固定块 94.88% 提至 97.25%，Long 达 94.5%、比最佳固定设置高 4.5 点。",
    strengths: "两个结构不同的 VLA、三套基准与真机都检查，且不增加模型训练；多 seed 大规模 rollout。",
    limitations: "注意力熵是经验代理而非校准置信度；不同实现需暴露 cross-attention，平台阈值和异常模式可能变化。",
    transfer: "可先利用模型内部已有信号做执行 horizon 控制，并用真机误差验证它是否真的对应观测 grounding。",
    technique: [
      "对每个动作位置计算其到 VLM token 的交叉注意力熵，并在高值持续、增量趋平时判定当前观测不再充分支撑更远动作。",
      "若未形成平台则执行完整块；方法不需多次采样，额外成本只是读取和统计已有 attention。",
    ],
    evaluation: [
      "RoboTwin 十任务覆盖短/中/长 horizon，三 seed 每配置 100 次；单一固定块可在个别任务更好，但总体不如动态截断。",
      "LIBERO 四套全部超过固定 2/4/6/8/10，真机三任务也提高平均成功率；收益需结合平均执行块长理解效率折中。",
    ],
    comparison: "多种固定 action chunk、20 次 multi-sampling、self-attention adaptive、π0.5 与 X-VLA。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文给出熵归一化判据、两个主干的 attention 读取方式、40k 步/50 示范和三 seed 协议。"],
    missing: ["代码开放状态未确认；完整真机逐任务计数和跨控制频率阈值敏感性有限。"],
    figureFile: "2609.00908-fig2.png",
    figureAlt: "动作序列内部交叉注意力从集中到高熵平台的变化",
    figureCaption: "Figure 2 · 用 action-to-observation cross-attention 熵决定动作块何时停止。来源：arXiv 原图。",
  },
  {
    title: "MINERVA: How Small Can a Manipulation Policy Be and Still Solve LIBERO?",
    arxivId: "2609.03715",
    url: "https://arxiv.org/abs/2609.03715",
    institutions: ["Matsuo-Iwasawa Laboratory, The University of Tokyo"],
    signal: "把 LIBERO 策略压到 0.54M 参数仍获 95.1%，并用尺度、动作块、视觉容量、回归目标和指令置换揭示基准的容量下限。",
    tags: ["Efficient Policy", "LIBERO", "Capacity Study"],
    classification: { research: "VLA", training: "BC", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "大模型在 LIBERO 接近饱和，却不清楚成功来自通用能力还是记住固定任务；部署真正需要的是满足任务集的最小容量。",
    methodSummary: "MINERVA 系统缩放紧凑视觉编码器与动作 MLP，在相同 2,000 rollout 预算下找性能断点，并扫描 flow/L1、chunk、视觉分配和语言条件。",
    architecture: "0.54M 参数的轻量视觉—动作网络直接回归 action chunk，可在笔记本 CPU 每控制步重规划；没有大型 VLM 主干。",
    data: "标准 LIBERO 四套、LIBERO-90 的 89 项任务和 LIBERO-Plus 扰动；所有主表点各 2,000 rollout。",
    experiments: "参数从百万级向 0.25M 以下缩放，关键配置三 seed；比较 L1 与 flow matching、不同 chunk/视觉容量、任务 ID 置换和部署时延。",
    novelty: "0.54M 达 95.1%，比 LeRobot π0.5 低 2.4 点但参数少 7,700×；5–9 ms/块，CPU 比 π0.5 快约 1,400×。",
    strengths: "用三 seed band 区分真实增益与噪声，并揭示 LIBERO 语言条件更像任务选择器；对基准饱和有明确诊断价值。",
    limitations: "没有真机；LIBERO-Plus 仅 46–56%，光度变化近零，说明紧凑模型并不等于通用 VLA。",
    transfer: "在固定部署任务上先测容量下限，避免无条件使用十亿参数模型；但需用 OOD 与真实硬件防止把记忆任务当泛化。",
    technique: [
      "逐级缩放视觉和动作容量，性能在约 1M 参数饱和、低于 0.25M 崩溃；只有 chunk length 和 vision allocation 稳定超过 ±1 点 seed band。",
      "L1 直接回归与 flow matching 在三 seed 无显著差异，却最高快 3.8×；任务 ID 置换使成功接近随机，显示语言泛化有限。",
    ],
    evaluation: [
      "标准四套 2,000 rollout 平均 95.1%，LIBERO-90 为 94.6%；相同网络在 LIBERO-Plus 明显下降，构成重要反例。",
      "部署测量覆盖 RTX 5080 Laptop 与 8 线程 CPU；0.54M 模型每块 5–9 ms，适合每控制步重规划。",
    ],
    comparison: "π0.5、SmolVLA、不同参数规模、L1/flow、chunk、视觉容量、任务 ID 置换和 LIBERO-Plus。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文披露网络规模、2,000 rollout、三 seed 控制、CPU/GPU 延迟和完整 sweep 设计。"],
    missing: ["未确认代码开放；没有真实机器人、语言开放集或跨本体实验。"],
    figureFile: "2609.03715-fig3.png",
    figureAlt: "MINERVA 参数规模与 LIBERO 成功率的缩放曲线",
    figureCaption: "Figure 3 · 成功率在约 1M 参数饱和、0.25M 以下崩溃，长时套件最先下降。来源：arXiv 原图。",
  },
  {
    title: "SUN: Persistent Programs For Language-Grounded Control-to-Learning-to-Real Policies",
    arxivId: "2608.31167",
    url: "https://arxiv.org/abs/2608.31167",
    institutions: ["University of California, Los Angeles", "University of California, Santa Barbara", "Robotics and AI Institute"],
    signal: "把一次定义的几何/接触关系编译成 MPC 代价、阶段谓词、RL 奖励和监控条件，让任务语义从规划一直保留到真机策略。",
    tags: ["Program Synthesis", "MPC", "Sim2Real"],
    classification: { research: "Subtask", training: "RL", data: "合成 / 仿真数据", platforms: ["机械臂", "夹爪"], deployment: "Sim2Real" },
    motivation: "控制器验证过的任务目标在转成 BC/RL 数据时常被丢弃，后续又手写奖励和阶段逻辑，导致语义漂移。",
    methodSummary: "Kuafu 让 VLM 从语言与场景合成 typed SUN Program，经 MPC 物理筛选后，同一程序继续生成阶段条件、残差 RL 奖励、transition guard 和诊断。",
    architecture: "任务程序连接语言 grounding、MPC mentor、Stage-BC、受限 residual RL 与监控数据生成；下游视觉策略只读取生成的观测动作。",
    data: "九项多阶段操作，每任务生成 1,000 条 mentor 数据；固定 500 条成功轨迹训练 DP3，并在 Franka/Kinova 六项任务零样本 sim-to-real。",
    experiments: "比较稀疏奖励、Stage-BC、纯 RL、TD-MPC2、MimicGen/SkillMimic 数据与 VLM 控制；三条独立 pipeline lineage 并有 106 次真机。",
    novelty: "完整策略 82.03%，稀疏奖励 35.67%、Stage-BC 24.75%；500 条/任务训练 DP3 为 46.02%，最强替代 22.44%；真机 36/106。",
    strengths: "消融表明行为 prior、程序监督和 residual bound 都不可缺；数据生成质量通过固定下游 learner 与真机检验。",
    limitations: "依赖已注册场景 frame、有限 typed operator 和单向阶段监控；不支持未定义的柔性体/液体与开放世界组合。",
    transfer: "把验证过的任务关系保存成持久可执行对象，可减少从控制器到学习策略时的奖励和阶段定义漂移。",
    technique: [
      "每个几何/接触 relation 带满足边界，并编译为 MPC cost、completion predicate、RL reward、transition guard 和诊断视图。",
      "MPC 先筛除不可行程序并生成 mentor，Stage-BC 提供行为 prior，受限 residual RL 只在程序语义内改进；数据生成继续用程序过滤假完成。",
    ],
    evaluation: [
      "去掉 Stage-BC prior、程序监督或放宽 residual bound 都明显退化，完整 pipeline 三条 lineage 平均 79.43%。",
      "DP3 固定 learner 下 Kuafu 数据 46.02% 对 SkillMimic 22.44%；真机六任务、三种 robot-gripper 配置 34.72% 宏平均，主要失败是抓取。",
    ],
    comparison: "sparse reward、Stage-BC、pure RL、TD-MPC2、Eureka/VoxPoser、MimicGen/SkillMimic 及完整组件消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文给出 typed operator、MPC/残差 RL 流程、每任务 1,000/500 条数据、三 lineage 和 106 次真机。"],
    missing: ["程序合成工具链与全部场景资产开放状态未确认；新 operator 和开放场景需要额外工程。"],
    figureFile: "2608.31167-fig1.png",
    figureAlt: "Kuafu 中 SUN Program 从语言、MPC、RL 到真机数据生成的持久流程",
    figureCaption: "Figure 1 · 同一 SUN Program 跨越控制验证、策略学习和真实部署。来源：arXiv 原图。",
  },
  {
    title: "CometVLA: Co-Training on an Embodied Data Pyramid towards Physical Understanding",
    arxivId: "2608.30289",
    url: "https://arxiv.org/abs/2608.30289",
    institutions: ["JD Explore Academy", "The Chinese University of Hong Kong, Shenzhen", "Shenzhen Institute of Artificial Intelligence and Robotics for Society"],
    signal: "把与机器人动作域对齐的物理 VQA、第一视角视频、仿真和遥操作组成数据金字塔，用 GAP token 将物理常识接到动作头。",
    tags: ["VLA", "Physical VQA", "Co-training"],
    classification: { research: "VLA", training: "Pre-training", data: "其他数据方法", platforms: ["机械臂", "夹爪"] },
    motivation: "通用物理 VQA 多来自非机器人图像，VLM 分数提升未必转成动作；直接联合训练又可能破坏已有视觉语言表征。",
    methodSummary: "CometData/Bench 按目标机器人数据域构建物理问答；GAP token 作为低维瓶颈汇聚跨样本动作先验，action head 显式读取它，再做统一 co-training。",
    architecture: "Qwen3-VL-4B+FAST tokenizer+DiT-B flow action head；可学习 GAP token 连接 VLM 与动作专家，机器人动作统一填充为 32 维双臂格式。",
    data: "混合 AgiBot-World-Beta、InternData-A1、EgoLive、EgoDex、通用 VQA 与 CometData；后训练使用 RoboTwin 和 AgiBot G1 真机遥操作。",
    experiments: "RoboTwin easy/hard、CometBench 和 G1 梳妆台整理真机；比较通用 VQA 替换、去 GAP、不同训练混合，并做 VLM—VLA 相关性分析。",
    novelty: "RoboTwin easy/hard 89.24%/88.38%，超过 π0.5 等基线；GAP 仅用 VLM-mean 40% 的维度，gripper state/motion magnitude probe +7.0/+3.9 点。",
    strengths: "物理问答是否帮助动作通过匹配训练和消融检验；仿真 hard 与双臂真机都有闭环。",
    limitations: "VLM—VLA 相关点集中在约 85% 的窄区间，不能推出普遍因果；真机场景数量和任务广度有限。",
    transfer: "为动作学习增加 VQA 时，应匹配机器人视角、本体与任务分布，并提供受控 latent 接口，不能仅用通用物理问答分数替代策略评测。",
    technique: [
      "GAP token 在 VLM 内聚合任务无关运动规律，动作专家主动查询该 token；小瓶颈减少物理问答特征对主干的干扰。",
      "单阶段 co-training 覆盖 VQA、人类视频、仿真和真机数据，随后针对仿真/真实任务分别后训练。",
    ],
    evaluation: [
      "同配置下把 CometData 换成等量通用 VQA 带来最大下降，去掉 GAP 也持续退化，说明数据域和接口均有贡献。",
      "G1 每项任务 16 次，RoboTwin hard 88.38%；论文也承认真实任务只覆盖当前整理场景，泛化结论需谨慎。",
    ],
    comparison: "π0.5 等 token/diffusion/flow VLA、通用 VQA 替换、无 GAP、不同数据混合和 VLM-mean probe。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文披露 4B+DiT-B 架构、32 维动作、4 节点×8 H200 训练和真机每任务 16 次。"],
    missing: ["CometData/Bench、训练代码和权重的公开入口未确认；真机任务数及总试验量有限。"],
    figureFile: "2608.30289-fig1.png",
    figureAlt: "CometVLA 数据金字塔、GAP token 和动作联合训练概览",
    figureCaption: "Figure 1 · 物理 VQA、第一视角、仿真与遥操作共同训练 CometVLA。来源：arXiv 原图。",
  },
];

export const paperDaily20260904 = entries.map(makePaper);
