import type { Paper, PaperEquation } from "./site-data";

type Entry = Omit<
  Paper,
  "rank" | "figures" | "optimization" | "experimentDetails" | "reproducibilityDetails" | "deepDive"
> & {
  figureFile: string;
  figureAlt: string;
  figureCaption: string;
  technique: string[];
  evaluation: string[];
  comparison: string;
  reproducibilityStatus: "资源较完整" | "部分可复现" | "信息不足";
  implementation: string[];
  missing: string[];
  equations?: PaperEquation[];
};

const makePaper = (entry: Entry, index: number): Paper => ({
  ...entry,
  rank: index + 1,
  optimization: entry.technique.join("；"),
  experimentDetails: [{
    title: "原文实验与消融",
    setup: entry.experiments,
    comparisons: entry.comparison,
    results: entry.evaluation,
  }],
  reproducibilityDetails: {
    status: entry.reproducibilityStatus,
    verifiedResources: entry.resources?.map((resource) => `${resource.label}: ${resource.url}`) ?? ["arXiv 论文正文"],
    implementation: entry.implementation,
    missing: entry.missing,
  },
  deepDive: {
    lead: entry.methodSummary ?? entry.signal,
    sections: [{ title: "方法与模型改进", paragraphs: entry.technique }],
    equations: entry.equations,
    experimentReading: entry.evaluation,
    reflections: [entry.transfer],
  },
  figures: [{
    src: `/report-assets/2026-08-28/${entry.figureFile}`,
    alt: entry.figureAlt,
    caption: entry.figureCaption,
  }],
});

const entries: Entry[] = [
  {
    title: "Riemann-1.0: An Embodied World Action Model for Physical AI",
    arxivId: "2608.27033",
    url: "https://arxiv.org/abs/2608.27033",
    institutions: ["Riemann Dynamics"],
    signal: "把机器人策略与动作条件世界模拟器写成同一条因果自回归序列，并用人类视频、UMI 与多本体机器人轨迹做渐进式预训练。",
    tags: ["WAM", "Causal Autoregression", "Large-scale Pre-training"],
    classification: { research: "WAM", training: "Pre-training", data: "跨本体数据", platforms: ["机械臂", "Humanoid", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://riemann-dynamics.github.io/Riemann-1.0-Website" }],
    motivation: "现有 WAM 往往把视频生成、动作预测和策略执行拆开，且难以统一利用无动作人类视频、UMI 与不同机器人本体的数据。",
    methodSummary: "Riemann-1.0 将多视角图像、机器人状态与本体动作交错成因果 token 序列；同一模型既预测后续世界状态，也生成可执行动作。",
    architecture: "全因果 Transformer 配合视觉 tokenizer、状态/动作投影与 action-video 统一序列；预训练依次从人类视频的视觉动态，迁移到手持夹爪，再落到机器人动作监督。",
    data: "论文报告 20 万小时以上交互数据，覆盖 Ego 人类视频、手持夹爪示范和异构机器人轨迹，并在后训练阶段加入具体本体与任务数据。",
    experiments: "评估 RoboTwin2.0、LIBERO、RoboCasa-365 与长时真机操作；同时比较策略成功率、阶段完成度和动作条件视频模拟能力。",
    novelty: "RoboTwin2.0/LIBERO/RoboCasa-365 分别达到 94.3%/99.0%/62.6%；真机长时任务 SR 85.0%、PSR 94.4%，相对论文采用的最强开源基线 SR 高 15 个百分点。",
    strengths: "统一数据、训练阶段和 policy/simulator 两种用途；真机评价覆盖长时组合操作，而非只展示短动作片段。",
    limitations: "20 万小时数据的组成与质量控制无法由公开材料完全复核；大规模训练预算使独立复现困难，真机结论仍来自作者自有平台。",
    transfer: "跨来源预训练可按“视觉动态→可迁移动作空间→本体动作”分阶段推进，避免一开始就强行统一所有动作标签。",
    technique: [
      "序列按时间交错观测、状态和动作 token，使世界变化与控制命令处在同一因果分解中；生成动作时只读取历史，模拟未来时继续滚动视觉 token。",
      "渐进式预训练先从无动作视频学习物理变化，再用 UMI 类数据连接相机运动与末端运动，最后以机器人轨迹完成本体落地。",
    ],
    evaluation: [
      "三个仿真基准分别覆盖多任务、标准操作和长时组合任务，论文报告的提升并非只来自单一 benchmark。",
      "真机同时报告整段成功率和进度成功率，能区分完全完成与只完成部分阶段。",
      "消融比较不同预训练阶段与统一建模组件；但大数据配方和算力差异仍是与小规模基线比较时的重要混杂因素。",
    ],
    comparison: "LIBERO、RoboTwin2.0、RoboCasa-365 上的 VLA/WAM 基线，以及分阶段数据与统一因果建模消融。",
    reproducibilityStatus: "信息不足",
    implementation: ["正文给出因果序列组织、三阶段训练目标、主要数据源类型与仿真/真机评价协议。"],
    missing: ["未公开完整 20 万小时数据清单、训练代码、权重和全部真机重复次数。"],
    figureFile: "2608.27033-fig1.png",
    figureAlt: "Riemann-1.0 数据、渐进式预训练和统一世界动作模型总览",
    figureCaption: "Figure 1 · 数据基础设施、三阶段预训练、统一因果 WAM 与仿真/真机评价。来源：arXiv 原图。",
  },
  {
    title: "LM-X: Explainable Action Modeling with Progress, Event, and Uncertainty Prediction for Generalist Robot Manipulation",
    arxivId: "2608.25757",
    url: "https://arxiv.org/abs/2608.25757",
    institutions: ["Humanoid Robot (Shanghai) Co., Ltd.", "E-surfing Digital Life Technology / China Telecom"],
    signal: "把任务进度、下一事件和动作不确定性变成直接参与控制的监督变量，而不是在动作之后生成解释文本。",
    tags: ["VLA", "Progress Modeling", "Uncertainty"],
    classification: { research: "VLA", training: "Pre-training", data: "数据质量 / 筛选", platforms: ["机械臂", "Humanoid", "灵巧手", "夹爪"] },
    motivation: "一般 VLA 只监督短时动作块，任务进度、下一语义转移和局部可靠性都被压在同一 action loss 中，部署时也无法直接观察。",
    methodSummary: "LM-X 同时预测 return-to-go、event-to-go 和异方差动作流；三种信号逐级条件化动作专家，并在执行前在线输出。",
    architecture: "Cosmos-Reason2-2B/Qwen-VL 前端编码语言与多相机；RTG 头读取视觉语义，ETG 头结合 RTG 与本体状态，action expert 再结合两者并预测均值与方差。",
    data: "超过 2 万小时真机轨迹，含 1000 小时以上失败 rollout；另用五个隔离任务做低成本预训练门禁，再进行约 20 天、64 张 B200 的大规模训练。",
    experiments: "RoboTwin2.0 的 50 个 randomized-hard 任务，以及四种本体上的七个真机任务；每个真机任务 20 次，并保持后训练数据和成功标准一致。",
    novelty: "RoboTwin2.0 为 74.1%，GR00T N1.7 为 55.4%；七个真机任务平均 68.6% 对 50.7%。五任务门禁中完整模型比 action-only 高 16.0 点。",
    strengths: "模块在大训练前先做受控消融；失败数据用于监督进度回退和犹豫状态，真机任务包含精密插入与双臂长时操作。",
    limitations: "解释变量由人工定义的事件和 outcome 派生，不等同于因果解释；训练成本极高，方差目前只证明与失败相关，尚未形成校准过的失败检测器。",
    transfer: "可以先为现有 VLA 增加进度、事件边界和不确定性头，用低成本任务门禁判断这些辅助目标是否真正改善动作。",
    technique: [
      "RTG 估计可见任务进度，ETG 预测直到下一个语义事件的动作片段，异方差 flow head 对局部动作噪声建模；三者都位于控制计算图内。",
      "失败 rollout 提供回退、停滞和目标切换样本；事件标签由任务规则提议并人工核验，使事件监督跨不同机器人保持一致接口。",
    ],
    equations: [{ name: "异方差动作目标", expression: "L = Σₜ [‖vₜ − μθ‖² / (2σθ²) + log σθ]", explanation: "动作专家同时预测 flow 均值与尺度，较大的 σ 表示当前局部动作更不确定。" }],
    evaluation: [
      "五任务预训练门禁逐项移除 RTG、ETG 和 variance head，完整组合比最强单头仍高 10.8 点。",
      "七个真机任务各 20 次，覆盖物体整理、布料、双臂协同、电池与毫米级零件插入。",
      "作者展示 RTG 对错误抓取会下降、variance 在犹豫时升高；论文明确把它描述为时间对应关系，而非已完成校准的检测准确率。",
    ],
    comparison: "GR00T N1.7、action-only 主干、三个单头/组合消融，以及相同后训练数据下的七项真机对照。",
    reproducibilityStatus: "信息不足",
    implementation: ["披露 2B 视觉语言主干、标签流程、64×B200/20 天预算、五任务门禁和每项真机 20 次协议。"],
    missing: ["未公开完整训练代码、权重、2 万小时数据清单与标签工具。"],
    figureFile: "2608.25757-fig1.png",
    figureAlt: "LM-X 的任务、事件和动作三时间尺度预测架构",
    figureCaption: "Figure 1 · RTG、ETG 与异方差动作流在同一控制图中的信息传递。来源：arXiv 原图。",
  },
  {
    title: "One Policy, Many Embodiments: Unified Camera-Centric Action Geometry Pre-training for Heterogeneous Embodied Manipulation",
    arxivId: "2608.26058",
    url: "https://arxiv.org/abs/2608.26058",
    institutions: ["Xiaomi Embodied Intelligence Team", "University of Macau"],
    signal: "不在机器人关节空间硬做动作对齐，而是把人手、机械臂和 Humanoid 的动作统一为相机可见的几何锚点运动。",
    tags: ["Cross-Embodiment", "Action Representation", "VLA Pre-training"],
    classification: { research: "VLA", training: "Pre-training", data: "跨本体数据", platforms: ["机械臂", "Humanoid", "灵巧手", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://public-bots.github.io/UCAG-P" }],
    motivation: "不同机器人的关节、相机和低层控制空间不兼容，现有统一策略依赖手工 retargeting 或数据集专用分支。",
    methodSummary: "UCAG-P 在图像坐标与相机坐标中预测腕部/末端和抓取中心的统一轨迹，再由几何条件 translator 映射到目标本体动作。",
    architecture: "共享 VLA 只学习 camera-centric anchor motion；translator 使用相机外参、机器人状态、运动学 Jacobian 与抓取表示生成本体专用控制。",
    data: "4.03K 小时机器人与仿真数据，加 2.34K 小时人类示范；覆盖单臂、双臂、人手与 Humanoid 等异构来源。",
    experiments: "在 LIBERO、LIBERO-Plus、RoboTwin Easy/Hard 与 RoboCasa GR-1 上用单一 checkpoint 评价，重点测试零样本跨任务和跨本体迁移。",
    novelty: "单一模型在 LIBERO 98.3%、RoboTwin Easy/Hard 88.7%/89.2%、LIBERO-Plus zero-shot 82.0%、RoboCasa GR-1 62.0%，无需 benchmark 专用微调。",
    strengths: "动作统一建立在可观察几何上，translator 保留本体可执行性；数据规模和本体跨度较大。",
    limitations: "主结果集中在仿真/标准基准，没有与数据规模相匹配的大规模物理闭环报告；几何 translator 仍依赖标定和目标本体运动学。",
    transfer: "跨本体项目可先统一相机坐标中的末端轨迹，再用轻量本体层落到关节或控制器，减少共享 policy 学习硬件差异的负担。",
    technique: [
      "统一动作由 2D 图像锚点、相机系 3D 位移与抓取状态组成，使人手和机器人末端共享可比较的运动描述。",
      "translator 把共享几何动作与目标机器人的相机外参、Jacobian 和当前状态结合，输出可执行命令；共享主干不需要数据集专用 action head。",
    ],
    evaluation: [
      "使用同一 checkpoint 横跨四套基准与多种本体，避免每个 benchmark 单独后训练后再宣称统一。",
      "LIBERO-Plus 的 82.0% 是零样本结果，RoboCasa GR-1 为 62.0%，显示迁移难度提高时仍有明显下降。",
      "消融比较原生动作、仅图像轨迹、仅 3D 轨迹和完整 UCAG；当前证据不足以回答真实标定误差下的稳定性。",
    ],
    comparison: "原生动作空间、显式 retargeting/专用分支方案，以及 LIBERO、RoboTwin、RoboCasa 上的通用 VLA 基线。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页提供方法与代码入口；正文披露共享动作定义、translator 输入、训练数据小时数和主要 benchmark 协议。"],
    missing: ["完整大规模数据与预训练权重的公开状态需以项目页后续发布为准；缺少同规模真机闭环评价。"],
    figureFile: "2608.26058-fig3.png",
    figureAlt: "UCAG-P 的跨本体数据、统一动作表示与几何转换器",
    figureCaption: "Figure 3 · 异构本体动作映射为 camera-centric 几何，再由 translator 生成目标机器人控制。来源：arXiv 原图。",
  },
  {
    title: "Do Robotic World Models Really Follow Actions? Diagnosing and Aligning Action-Conditioned Generation for Policy Learning",
    arxivId: "2608.24885",
    url: "https://arxiv.org/abs/2608.24885",
    institutions: ["Peking University", "Beijing Innovation Center of Humanoid Robotics", "New York University", "UESTC", "Nanyang Technological University", "The Chinese University of Hong Kong"],
    signal: "不只看世界模型生成得像不像，而是检查它在专家分布之外是否真的按给定动作改变未来。",
    tags: ["World Model", "Action Following", "Policy Improvement"],
    classification: { research: "WM", training: "Post-training", data: "合成 / 仿真数据", platforms: ["机械臂", "夹爪"] },
    motivation: "把 action-conditioned world model 当模拟器的前提是它会忠实执行任意可行动作，但现有评测通常只覆盖专家示范。",
    methodSummary: "WorldEcho 用五类动作查询测视觉完整性和 SE(3) 末端轨迹对齐；WorldSync 再从动作覆盖、表示 grounding 和干预效应三方面修正模型。",
    architecture: "在视频世界模型中加入 Action-Forcing Expert，从中间表示回归未来机器人状态；Intervention-Effect 目标比较同一观测下不同动作导致的预测差异。",
    data: "RoboTwin 专家与 off-expert 轨迹，加少量目标域真机数据；查询包括示范、跨状态 replay、局部扰动、policy rollout 和可行空间采样。",
    experiments: "先诊断多种 action-conditioned 世界模型，再在 RoboTwin 与真机任务中把 WorldSync 用作迭代 policy improvement 的模拟器。",
    novelty: "论文显示专家动作上看似正常的模型在 off-expert 条件下会忽略动作或破坏视觉；WorldSync 同时改善动作轨迹一致性、视觉有效率和后续策略成功率。",
    strengths: "评测覆盖分布外动作而非只复现示范；诊断指标与 policy improvement 的下游收益连接起来，并有组件消融。",
    limitations: "SE(3) 轨迹提取依赖视觉估计器；真机范围仍有限，改进配方混合了更广数据支持与新损失，单独贡献需看消融。",
    transfer: "训练或使用机器人世界模型前，可先用跨状态动作、局部扰动和 policy rollout 做 action-following stress test。",
    technique: [
      "WorldEcho 同时判定生成视频是否视觉有效，并比较由生成视频恢复的末端轨迹与目标动作，避免只用 FVD 判断可控性。",
      "WorldSync 扩展动作后果覆盖；AFE 强迫中间表示编码动作诱导的机器人动力学；IE 对齐同起点不同动作之间的预测变化。",
    ],
    equations: [{ name: "干预效应对齐", expression: "LIE = ‖(ŷ(a₁) − ŷ(a₂)) − (y(a₁) − y(a₂))‖₁", explanation: "同一初始观测下，模型对动作变化的响应应与真实未来之间的变化一致。" }],
    evaluation: [
      "五类查询把 expert-support 与逐步远离专家分布的动作分开，能定位“画面正常但不听动作”和“画面直接崩坏”两类错误。",
      "RoboTwin 与真机 policy-improvement 采用同一模拟器闭环，WorldSync 生成的训练反馈带来更高真实策略成功率。",
      "覆盖扩展、AFE、IE 的逐项消融均被执行；结果仍不能证明模型在更大动作空间中具备普遍物理准确性。",
    ],
    comparison: "六类现有机器人世界模型、expert-only 训练、覆盖扩展、AFE/IE 消融，以及下游迭代策略改进。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文给出五类动作查询、SE(3) 对齐指标、WorldSync 三组件和仿真/真机下游评价流程。"],
    missing: ["未确认代码与模型权重公开；目标域真机数据规模和全部硬件重复细节需结合附录复现。"],
    figureFile: "2608.24885-fig1.png",
    figureAlt: "WorldEcho 诊断、WorldSync 改进和策略验证流程",
    figureCaption: "Figure 1 · 从 off-expert 动作诊断到 WorldSync 训练，再验证策略改进收益。来源：arXiv 原图。",
  },
  {
    title: "Learning to Act While Waiting: RL Finetuning of Generalist Robot Policies Under Inference Latency",
    arxivId: "2608.23831",
    url: "https://arxiv.org/abs/2608.23831",
    institutions: ["Siemens", "UC Berkeley", "Microsoft", "ETH Zurich"],
    signal: "把 VLA 推理期间已经承诺执行的动作与中途新观测重新写入 RL 状态，使异步部署重新接近 Markov。",
    tags: ["Online RL", "Inference Latency", "Asynchronous Control"],
    classification: { research: "VLA", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "大型 VLA 推理时延会让机器人停顿或基于旧观测继续执行，改变 RL 所见的环境动力学，使标准残差 RL 或异步 RL 失效。",
    methodSummary: "ARLI 在 VLM 推理等待期间运行低延迟 RL policy，用已承诺动作和中间新观测修正 action expert 的噪声输入与下一动作块。",
    architecture: "预训练 VLM/action expert 保留异步 chunk 生成；RL policy 读取初始状态、已执行中间动作及中途状态，输出对下一 chunk 的低延迟 steering。",
    data: "仿真高反应任务的在线 rollout，以及双臂 UR5e 上三个真机任务的在线 RL 数据；无需重新预训练 VLA。",
    experiments: "四个高反应仿真任务与三个双臂真机任务；对比同步推理、朴素异步 DSRL、RTC、残差 RL 和不同状态增强。",
    novelty: "朴素异步 RL 在高延迟下无法学习时，ARLI 仍能持续提升；多项设置达到或超过理想化无延迟标准 RL，真机也能在同步/朴素异步失败的区间改善。",
    strengths: "把时延造成的状态缺失明确建模；仿真、真机与状态增强消融完整，直接针对实际 VLA 控制延迟。",
    limitations: "需要额外低延迟 policy 与在线交互；当前真机只覆盖一套双臂 UR5e，增益依赖中途观测可及时获得。",
    transfer: "做 VLA 在线 RL 时，应把等待期间实际执行的动作和新观测加入 critic/policy 状态，而不是把一次慢推理当成原子动作。",
    technique: [
      "RL policy 在 action expert 完成前先运行，把已承诺的中间动作和中途新状态作为状态增强，修正下一 action chunk 的生成起点。",
      "RTC 负责连续执行，ARLI 负责恢复近似 Markov 的学习状态；两者可以组合，但论文消融显示只有 RTC 不足以稳定学习。",
    ],
    evaluation: [
      "四个仿真任务随训练时间比较最终成功率与样本效率，ARLI 在时延增大时仍优于直接异步 DSRL。",
      "三个真机任务验证同步停顿、朴素异步与 ARLI；ARLI 是能在所测时延区间持续改善的方案。",
      "逐项加入 intermediate action、intermediate state 和 RTC，证明主要收益来自等待期信息而非单纯提高执行频率。",
    ],
    comparison: "同步 RL、异步 DSRL、Residual RL、RTC 及 intermediate-action/state 的组合消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文公开状态增强定义、异步时间线、仿真任务、双臂 UR5e 设置和主要 RL 超参数。"],
    missing: ["未确认完整代码、真实系统数据与预训练 checkpoint 发布；部分真机成功次数需从附录表复核。"],
    figureFile: "2608.23831-fig2.png",
    figureAlt: "ARLI 在 VLA 推理等待期间使用中间动作和中间状态",
    figureCaption: "Figure 2 · 慢 VLA、低延迟 RL policy 与异步 action chunk 的时间关系。来源：arXiv 原图。",
  },
  {
    title: "UniMem: Unifying Multimodal Memory and Control for Vision-Language-Action Models",
    arxivId: "2608.22869",
    url: "https://arxiv.org/abs/2608.22869",
    institutions: ["Stanford University"],
    signal: "用事件触发的文本记忆与视觉关键帧缓存，让同一个 VLA 主干同时负责记忆更新和动作控制。",
    tags: ["Memory", "Event-driven", "VLA"],
    classification: { research: "Memory", training: "BC", data: "其他数据方法", platforms: ["机械臂", "夹爪"] },
    detailAttributes: { memoryImplementation: "事件分类器 + 文本事件 + 视觉关键帧缓存", memoryHorizon: "跨子任务的情节/空间历史；真机最多保留四个事件关键帧" },
    resources: [{ label: "项目页", url: "https://losterberg3.github.io/unimem-vla/" }],
    motivation: "固定间隔历史帧会引入无关相关性，外置 VLM 记忆又把高层记忆与低层控制割裂，并增加延迟。",
    methodSummary: "轻量事件分类器检测子任务里程碑，只在事件窗口结束后写入文本事件和视觉关键帧；缓存的视觉 hidden state 直接回流到 π0.5 主干。",
    architecture: "π0.5 最终层接事件 MLP；keyframe encoder 和 tokenizer 读取稀疏视觉/文本记忆，cached hidden states 与当前观测共同条件化 action expert。",
    data: "五个 robosuite 任务与四个 xArm6 硬件任务；事件脚本由代理根据动作签名生成，再由人检查部分标注。",
    experiments: "九个顺序/空间记忆任务；仿真保留三个、真机保留四个关键帧，真机约 10 Hz，并与固定采样和层级双系统基线比较。",
    novelty: "仿真平均 93.4% 对固定间隔 68.2%；硬件平均 80.0% 对层级基线 43.5%，同时通过 key/value caching 保持接近单帧推理速度。",
    strengths: "同时覆盖顺序与空间记忆、仿真和真机；事件、视觉、文本及缓存机制都有单独消融。",
    limitations: "事件词表和规则仍按任务定义，自动脚本需要人工抽查；最长只验证四个真机事件关键帧，尚未证明小时级记忆。",
    transfer: "对长任务可先以可验证事件触发记忆写入，并缓存视觉 hidden states，减少把每一帧都塞进上下文的成本。",
    technique: [
      "事件分类器从 VLA latent 预测 eₜ∈E∪{null}；事件完成后才更新记忆，避免把当前目标提前泄漏给策略。",
      "每个历史事件抽一个视觉关键帧并缓存其 KV/hidden state；文本事件与视觉记忆同时输入共享 VLA，而非再调用独立高层 VLM。",
    ],
    evaluation: [
      "仿真和硬件分别测试固定帧采样、文本-only、视觉-only、无事件门控和完整 UniMem。",
      "硬件使用 xArm6、腕部与外部相机，二元子任务成功由观察者判定；平均 80.0% 对层级基线 43.5%。",
      "延迟实验显示四相机、16 关键帧相对双相机单帧约增加 25 ms；这是一项离线速度压力测试，不代表已验证更长真机任务。",
    ],
    comparison: "π0.5 单帧、固定间隔多帧、MemER 类双系统记忆、文本/视觉与 caching 消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["披露 π0.5 主干、事件 MLP、关键帧上限、约 10 Hz 真机频率、标注脚本流程和任务设置。"],
    missing: ["代码与训练数据未在项目页明确标为已发布；任务专用事件规则仍需自行实现。"],
    figureFile: "2608.22869-fig1.png",
    figureAlt: "UniMem 的事件分类、文本记忆、视觉关键帧和动作控制架构",
    figureCaption: "Figure 1 · 事件触发多模态记忆更新，并通过缓存回流共享 VLA。来源：arXiv source 原图。",
  },
  {
    title: "FlashVLA: Streaming Action Decoding for Fast and Asynchronous VLA Inference",
    arxivId: "2608.27384",
    url: "https://arxiv.org/abs/2608.27384",
    institutions: ["University of California San Diego", "Massachusetts Institute of Technology"],
    signal: "把不同噪声层级的多个动作块放进流式 buffer，每次推理推进全部块并交付一个可执行块。",
    tags: ["VLA", "Streaming Decoding", "Low Latency"],
    classification: { research: "VLA", training: "Post-training", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "GitHub", url: "https://github.com/z-lab/flashvla" }],
    motivation: "同步 flow-matching VLA 会在 chunk 边界停顿；普通异步方法虽不断流，却基于越来越陈旧的观测预测远期动作。",
    methodSummary: "FlashVLA 维护多块、不同去噪进度的 action buffer，并用 chunk-wise causal attention 流式解码；每个推理步输出最成熟的一块。",
    architecture: "action expert 在一次 forward 中联合更新 buffer 内多块；因果 mask 让后块读取前块但不反向泄漏，天然保持动作连续性。",
    data: "沿用基础 VLA 的机器人示范与后训练数据，不额外要求 future-state 标签；在仿真与多项真机操作上比较。",
    experiments: "测成功率、控制频率、端到端 latency、异步动作平滑性，并与同步 flow decoding、RTC 和 future-state-conditioned async 方法比较。",
    novelty: "单 GPU 上达到至少 30 Hz 控制，同时保持真机异步执行平滑；相较同步方案不再在 chunk 边界等待，也不需要额外未来状态预测器。",
    strengths: "直接优化部署瓶颈，方法与 flow-VLA 解码过程耦合清楚；仿真和真机同时报告效率与任务表现。",
    limitations: "buffer 长度和噪声调度需要按模型/硬件选择；30 Hz 结论依赖所用 GPU、action chunk 与任务，不应视为所有 VLA 的固定速度。",
    transfer: "对 flow-based action expert，可把多个去噪阶段流水化，让一个 forward 同时推进未来 chunks，而不是每块从纯噪声重新开始。",
    technique: [
      "buffer 中第 k 个 chunk 处在不同 flow time；每轮联合更新后取出最接近 clean 的块执行，再插入一个新噪声块。",
      "chunk-wise causal attention 只允许未来块依赖更早块，使异步生成保持时间一致性，无需显式预测未来观测。",
    ],
    evaluation: [
      "效率实验同时报告 action frequency、sampling latency 与 GPU 设置，主结论是在单 GPU 上达到 ≥30 Hz。",
      "真机比较同步停顿、普通异步的高延迟错配和 FlashVLA 的低延迟错配，展示动作连续性与成功率。",
      "噪声层数、buffer/chunk 配置和 causal mask 均有消融；不同基础 VLA 的迁移范围仍需更多验证。",
    ],
    comparison: "同步 flow matching、RTC、future-state-conditioned asynchronous inference 与不同 streaming buffer 设置。",
    reproducibilityStatus: "资源较完整",
    implementation: ["GitHub 已公开；正文给出 buffer、因果 mask、flow time 调度、硬件和频率测试协议。"],
    missing: ["不同消费级 GPU 与更长 action horizon 的吞吐/显存曲线仍未完整覆盖。"],
    figureFile: "2608.27384-fig1.png",
    figureAlt: "同步、普通异步和 FlashVLA 流式动作解码对比",
    figureCaption: "Figure 1 · FlashVLA 以低时延错配持续输出动作块，避免同步停顿和高时延陈旧观测。来源：arXiv 原图。",
  },
  {
    title: "TacForcing: Streaming Action Generation with Execution-Time Tactile Feedback",
    arxivId: "2608.25798",
    url: "https://arxiv.org/abs/2608.25798",
    institutions: ["Shanghai Jiao Tong University", "South China University of Technology", "East China University of Science and Technology", "East China Normal University", "The Hong Kong Polytechnic University", "UESTC", "HUST"],
    signal: "不另加高频 tactile controller，而是在动作块执行期间把最新触觉重新注入仍未完成去噪的下一块。",
    tags: ["Tactile", "Streaming Action", "Contact-rich"],
    classification: { research: "VLA", training: "BC", modalities: ["Tactile"], platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://88runaway.github.io/tacforcing/" }],
    motivation: "标准 action chunk 在执行前一次性生成，触觉只反映生成时刻，接触状态在 chunk 内变化后无法及时修正。",
    methodSummary: "Streaming Action Expert 保留未完成块的中间去噪状态；每执行完一块就编码新触觉，再继续生成下一块。",
    architecture: "VLM 视觉/语言上下文只编码一次；EATA 让最新 tactile token 只影响即将执行的块，避免把同一触觉错误广播到远期动作。",
    data: "六个 UniVTAC 仿真接触任务和三个真实接触操作任务，使用视觉、状态、动作与执行时触觉序列。",
    experiments: "比较 chunk VLA、独立 tactile reactive controller、无 EATA 与完整 TacForcing；同时测试触觉时序错配和接触扰动。",
    novelty: "仿真六任务平均 65%、真机三任务平均 69%，均高于论文中的强基线；收益来自 streaming generation 与 execution-aware tactile conditioning 的组合。",
    strengths: "触觉确实进入执行闭环，且不引入另一套控制器；仿真与真机均有组件和时序消融。",
    limitations: "真机只覆盖三项接触任务；传感器、触觉编码和动作 expert 的同步实现较复杂，对高频网络抖动的鲁棒性尚不清楚。",
    transfer: "如果动作专家本身是迭代生成，可保留下一块的中间状态，在真实反馈到达后继续去噪，而非另训 residual controller。",
    technique: [
      "Streaming Action Expert 把 action horizon 分块，不一次性结束所有去噪；已 ready 的块执行时，其余块保留中间 flow state。",
      "EATA 依据执行顺序建立 tactile-to-action mask，使 t 时刻触觉只条件化最接近执行的块，降低 stale tactile 对远期块的污染。",
    ],
    evaluation: [
      "UniVTAC 六任务和三个真实任务均报告成功率，真机平均为 69%。",
      "比较标准 chunk VLA、外挂 reactive controller、streaming-only、无 EATA 和完整模型，验证两项组件都需要。",
      "论文展示接触状态突变时下一块会随新触觉改变；仍未覆盖大规模跨传感器和长时任务。",
    ],
    comparison: "标准 tactile VLA、独立高频触觉控制器、streaming/EATA 逐项消融及不同反馈延迟。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页提供视频；正文公开 streaming block、EATA mask、仿真/真机任务和主要训练设置。"],
    missing: ["代码、权重和真实触觉数据发布状态未明确；传感器标定细节仍依赖附录。"],
    figureFile: "2608.25798-fig1.png",
    figureAlt: "TacForcing 的流式动作专家和执行时触觉反馈",
    figureCaption: "Figure 1 · 已执行动作产生的新触觉只注入即将执行的下一 action block。来源：arXiv 原图。",
  },
  {
    title: "Zero-WAM: In-Context World-Action Modeling from Human Videos for Open-Ended Task Generalization",
    arxivId: "2608.26103",
    url: "https://arxiv.org/abs/2608.26103",
    institutions: ["Robbyant", "HKUST (Guangzhou)", "The Hong Kong University of Science and Technology"],
    signal: "把一段人类视频当成部署时任务上下文，让一个因果 video-action model 在不更新参数的情况下执行训练未见任务。",
    tags: ["WAM", "Human Video", "In-context Learning"],
    classification: { research: "WAM", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://robbyant-research.github.io/Zero-WAM/" }, { label: "GitHub", url: "https://github.com/robbyant-research/Zero-WAM" }],
    motivation: "语言难以完整描述空间关系和任务演化；真实人机配对视频稀缺，模型也容易忽略上下文、依赖训练任务捷径。",
    methodSummary: "Zero-WAM 同时接收语言或人类视频 prompt，因果预测未来机器人视频与动作；IFP 目标强迫模型从 in-context 视频提取任务变化。",
    architecture: "共享 causal video-action Transformer 对 prompt、机器人历史、future chunk 和 action chunk 建模；HumanGen 将机器人轨迹语义转换为匹配的人类视频。",
    data: "HumanGen 含 74.2K 人机 ICL 对、8.6K 任务；task-balanced 机器人 corpus 每个 epoch 约 40 万轨迹，来自五个公开与自有数据源。",
    experiments: "RoboTwin2.0 七个训练未见任务，以及多物体、长时操作与精细插入的真机配置；比较 WAN-Action、LingBot-VA 和数据/IFP 消融。",
    novelty: "七个未见仿真任务平均 46.95%，LingBot-VA 为 17.45%；真机展示无需新机器人数据或参数更新的 human-video-conditioned 执行。",
    strengths: "任务多样性和上下文使用有专门消融；不把人类动作直接 retarget，而把视频作为任务规范。",
    limitations: "47% 仍说明开放任务成功率有限；人类视频由生成流水线构造，可能保留机器人轨迹捷径，真机结果规模小于仿真。",
    transfer: "做人类视频迁移时，可把视频作为 task specification，并设计对照验证模型真的依赖 prompt，而非只靠语言或当前画面猜任务。",
    technique: [
      "HumanGen 先解析机器人轨迹的对象与状态变化，再编辑起始帧并生成语义匹配的人类操作视频，经过语义与物理合理性过滤后配回原动作。",
      "IFP 让模型根据 prompt 预测 future chunk；训练同时包含 language-conditioned 与 video-conditioned 样本，部署时保持同一因果 policy。",
    ],
    evaluation: [
      "RoboTwin 七项 zero-shot 任务报告均值与方差，平均 46.95±0.72%，最强 video-action 基线 17.45±1.40%。",
      "移除人类视频 prompt、task-balanced sampling 或 IFP 都会降低未见任务表现，说明不是只靠模型规模。",
      "真机主要证明可执行性和配置泛化；公开表格尚不足以支持对任意人类视频的普遍 zero-shot 结论。",
    ],
    comparison: "WAN-Action、LingBot-VA、无 ICL prompt、无 task balance、无 IFP，以及语言与人类视频两种任务接口。",
    reproducibilityStatus: "部分可复现",
    implementation: ["GitHub 给出论文与发布计划；正文披露 74.2K/8.6K 数据规模、生成过滤流程和七任务逐项结果。"],
    missing: ["代码、模型与数据计划于论文发布后陆续开放，当前尚不能完整复现 HumanGen 与训练。"],
    figureFile: "2608.26103-fig2.png",
    figureAlt: "Zero-WAM 的任务均衡机器人数据和 HumanGen 人类视频生成流程",
    figureCaption: "Figure 2 · Task-diverse 机器人语料、HumanGen 数据组成与人类视频生成管线。来源：arXiv 原图。",
  },
  {
    title: "V-Link: Recovering Lost Visual Representations in Action DiT for Vision-Language-Action Models",
    arxivId: "2608.25308",
    url: "https://arxiv.org/abs/2608.25308",
    institutions: ["Zhejiang University", "AGIBOT", "HKUST (Guangzhou)", "Simon Fraser University"],
    signal: "在 VLM 到 Action DiT 的接口处显式恢复语义与 3D 空间表示，避免动作专家只接到压缩后的通用 token。",
    tags: ["VLA", "Visual Grounding", "Action DiT"],
    classification: { research: "VLA", training: "Post-training", modalities: ["Depth / RGB-D"], platforms: ["Humanoid", "机械臂", "夹爪"] },
    motivation: "VLM 内部已有语义和几何信息，但传到 action expert 时访问受限，细粒度操作容易依赖语义捷径而丢失深度结构。",
    methodSummary: "V-Link 在 VLM 中学习 Semantic/Spatial Queries，以不同路径注入 Action DiT；训练期深度与语义头负责分离监督，推理时移除。",
    architecture: "因果 attention mask 让两类 query 从深层 VLM 特征独立抽取信息；语义 query 补充图像 token，空间 query 作为 Action DiT 的强制几何条件。",
    data: "沿用 GR00T N1.6 的预训练与后训练数据，在 LIBERO、LIBERO-Plus、RoboTwin2.0 和 AGIBOT A3 Ultra 真机任务上评估。",
    experiments: "三套仿真基准加两项 A3 Ultra 真机任务；比较 query 类型、注入路径、辅助监督和基础模型。",
    novelty: "相对 GR00T N1.6，LIBERO/LIBERO-Plus/RoboTwin2.0 分别提升 1.9/31.2/18.8 个百分点；两项真机 Humanoid 任务提升 20/24 点。",
    strengths: "大增益集中在分布变化更强的基准；空间/语义 query、监督头和注入路径有独立消融，并有 Humanoid 真机。",
    limitations: "只在 GR00T 系架构验证，绝对增益受基础实现影响；辅助深度教师的偏差和真机任务数量限制外推。",
    transfer: "在 VLM-action 接口上加入少量类型化 query，比把全部多尺度视觉特征直接拼给 action expert 更容易控制信息职责。",
    technique: [
      "Spatial/semantic queries 用受控 attention 从 VLM 深层取回几何与语义；训练期分别用 depth 和 semantic feature 监督。",
      "语义 query 走补充 cross-attention，空间 query 走强制几何路径，防止 Action DiT 忽略空间信息；辅助头推理时删除。",
    ],
    evaluation: [
      "LIBERO-Plus 与 RoboTwin2.0 的增益显著高于标准 LIBERO，说明主要改善分布变化和几何 grounding。",
      "AGIBOT A3 Ultra 两项真实任务分别提升 20 和 24 点，但任务总数较少。",
      "query 数、supervision、注入路径与 spatial/semantic 单独使用均有消融，完整不对称设计最好。",
    ],
    comparison: "GR00T N1.6、无 V-Link、semantic-only、spatial-only、不同注入路径与辅助监督消融。",
    reproducibilityStatus: "信息不足",
    implementation: ["正文给出 query 结构、attention mask、辅助目标和三基准/两真机任务设置。"],
    missing: ["未确认项目页、代码、权重与训练数据公开；A3 Ultra 硬件和真机重复次数需结合附录。"],
    figureFile: "2608.25308-fig3.png",
    figureAlt: "V-Link 的空间语义 query 和 Action DiT 注入结构",
    figureCaption: "Figure 3 · 两类 query 从 VLM 恢复空间/语义表示，并以不对称路径条件化 Action DiT。来源：arXiv 原图。",
  },
  {
    title: "Pointing-VLA: Typed Spatial Grounding Interfaces for Vision-Language-Action Manipulation",
    arxivId: "2608.23138",
    url: "https://arxiv.org/abs/2608.23138",
    institutions: ["作者机构未在 arXiv HTML 首页明确标注"],
    signal: "把 point、功能热图和视觉轨迹做成类型化 hidden-state readout，避免用自回归文本坐标连接推理与执行。",
    tags: ["VLA", "Spatial Grounding", "Typed Interface"],
    classification: { research: "VLA", training: "Post-training", modalities: ["Mask / Segmentation"], platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "文本坐标慢且易受格式影响，opaque action token 又难检查；不同操作阶段实际需要不同几何输出。",
    methodSummary: "在 Embodied-R1 hidden states 上训练 point、OFG/contact heatmap 和 visual trajectory heads；执行合约固定 PICK 用 OFG、PLACE 用 pointing。",
    architecture: "共享 VLM 后接三种几何专用头；wrapper 将图像点/热图映射到机器人坐标，并可把 readout 作为 π0.5 的空间 guidance。",
    data: "Bridge/WidowX 数据与外部 spatial grounding 套件，加三种视觉上下文的物理 pick-place 试验。",
    experiments: "四任务 Bridge/WidowX、跨数据 readout、NORA-1.5 移植、typed head 解码速度及 π0.5 真机 guidance。",
    novelty: "Bridge 四任务平均 72.9%，无需 Bridge 专用微调；typed head 比 Embodied-R1 文本解码快 6.68–6.90 倍，π0.5 真机从 52.7% 提至 80.7%。",
    strengths: "空间接口可检查、可组合且有速度实测；既做独立执行，也验证接到另一 VLA 的迁移。",
    limitations: "PICK/PLACE 合约是人工指定，复杂接触和多阶段任务可能需要更多类型；作者机构与公开资源信息不完整。",
    transfer: "在高层 VLM 与低层策略之间使用 typed spatial API，可分别选择点、功能区域或轨迹，而不是统一序列化成文本。",
    technique: [
      "point head 回归归一化坐标，OFG head 输出对象功能区域热图，VTG head 输出 waypoint；三者直接从 hidden states 解码。",
      "执行器按阶段读取特定类型，并通过 CuRobo 或 π0.5 guidance 执行；固定类型合约减少运行时自由文本解析。",
    ],
    evaluation: [
      "Bridge/WidowX 四任务与跨数据评测显示 point 和 OFG 各有优势，不能由单一 readout 完全替代。",
      "在同一外部套件上，typed head 相比文本坐标解码加速 6.68–6.90 倍；NORA-1.5 移植保持或提升成功率。",
      "π0.5 真机在三种视觉上下文由 52.7% 升至 80.7%；实验范围仍以 pick-place 为主。",
    ],
    comparison: "Embodied-R1 文本坐标、Pointing/OFG/VTG 单头、NORA-1.5 移植及 π0.5 无/有 spatial guidance。",
    reproducibilityStatus: "信息不足",
    implementation: ["正文披露 readout 类型、执行合约、CuRobo wrapper、速度测试和真机总体结果。"],
    missing: ["未找到已验证的项目页或代码；机构、训练超参数与逐任务真机次数公开不完整。"],
    figureFile: "2608.23138-fig2.png",
    figureAlt: "Pointing-VLA 的点、功能热图和轨迹类型化接口",
    figureCaption: "Figure 2 · Embodied-R1 hidden states 连接三种空间 head 与 PICK/PLACE 执行合约。来源：arXiv 原图。",
  },
  {
    title: "Memory Anchors for Continual Robot Learning",
    arxivId: "2608.26545",
    url: "https://arxiv.org/abs/2608.26545",
    institutions: ["Stanford University", "Toyota Research Institute"],
    signal: "持续学习时不随机回放全部旧数据，而是优先保留“视觉表示相近但新旧任务动作冲突”的关键旧样本。",
    tags: ["Continual Learning", "Replay", "Memory"],
    classification: { research: "Memory", training: "Post-training", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    detailAttributes: { memoryImplementation: "基于表示冲突的经验回放样本选择", memoryHorizon: "跨任务长期记忆" },
    resources: [{ label: "项目页", url: "https://robot-adaptation.github.io/MemoryAnchors" }],
    motivation: "随机经验回放浪费 buffer 容量；真正危险的是新旧观测在表示空间重合、却需要相反动作的冲突区域。",
    methodSummary: "用新旧任务表示相似度与动作冲突定位 Memory Anchors，并在固定大小 replay buffer 中提高这些旧样本比例。",
    architecture: "不改变 policy 主干；AnchorER 只修改旧数据选择和 batch 混合，兼容现有 continual fine-tuning。",
    data: "LIBERO 多任务序列与两条真实机器人持续学习序列，包含高冲突和低冲突任务配对。",
    experiments: "删除最关键 10% anchors、提高 anchor 比例、替换距离指标，并与随机 ER、herding 等 replay 选择比较。",
    novelty: "排除 10% anchors 会让灾难性遗忘增加 4.5 倍以上；AnchorER 在最高冲突配对中把遗忘降低 63%，真机总成功率为随机 ER 的 1.7 倍。",
    strengths: "样本重要性通过反事实删除和增补两种实验验证；保持相同 buffer 大小，并有真机持续学习。",
    limitations: "需要访问旧数据和动作标签；表示距离依赖当前 encoder，任务很多时 anchor 重算与存储仍会增长。",
    transfer: "回放数据筛选可关注“表征相似、动作相斥”的边界样本，而不是只按多样性或时间均匀采样。",
    technique: [
      "对新旧观测求表示邻域，在相近观测对应动作方向明显冲突的位置标记 anchor；这些样本最能阻止新任务覆盖旧策略。",
      "AnchorER 在固定 buffer 中预留一部分给 anchors，其余仍随机回放，因此改善不是由扩大内存得到。",
    ],
    evaluation: [
      "从随机 buffer 中只移除 10% 最强 anchors，遗忘增加超过 4.5 倍，构成样本重要性的删除检验。",
      "在高冲突任务中加入 anchors 使遗忘下降 63%；低冲突任务收益较小，符合方法假设。",
      "真实机器人两序列中总成功率为随机 ER 的 1.7 倍，但任务数量仍远少于长期部署规模。",
    ],
    comparison: "随机经验回放、常见代表样本选择、anchor 删除/增补和不同任务冲突程度。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文给出 anchor 定义、固定 buffer 协议、LIBERO 序列和真机 continual-learning 设置。"],
    missing: ["代码/数据发布状态需以项目页为准；大任务库下的重算成本与本体迁移尚未充分报告。"],
    figureFile: "2608.26545-fig1.png",
    figureAlt: "Memory Anchors 在冲突任务持续学习中的作用和选择方式",
    figureCaption: "Figure 1 · 表征相似但动作冲突的旧样本用于锚定过去任务性能。来源：arXiv 原图。",
  },
  {
    title: "Act with Intent: Distilling Behavior Intent for Vision-Language-Action Models",
    arxivId: "2608.23478",
    url: "https://arxiv.org/abs/2608.23478",
    institutions: ["POSTECH GSAI", "POSTECH IME"],
    signal: "训练期让冻结 VLM 从执行视频中提取“这段行为想达到什么”，再把 intent latent 蒸馏进动作 decoder。",
    tags: ["VLA", "Intent Distillation", "Future Supervision"],
    classification: { research: "VLA", training: "Post-training", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://leesangoh.github.io/indi-project-page/" }],
    motivation: "BC 只监督示范执行了什么动作，未来帧/轨迹监督又容易绑定某一种实现，缺少对局部行为共同目标的显式表示。",
    methodSummary: "INDI 用冻结 teacher VLM 读取当前观测、指令、粗动作摘要和执行视频，生成 intent target；VLA decoder 中层恢复该 latent。",
    architecture: "训练期 teacher intent、endpoint visual 和 textual-purpose 三类目标共同监督 decoder；部署时所有 teacher/目标生成模块删除，只保留原 VLA 路径。",
    data: "SimplerEnv-Bridge、RoboCasa Kitchen 和真实机器人任务的原示范与执行视频，不增加部署输入。",
    experiments: "在 GR00T N1.7 与 π0.5 两种 backbone 上评估仿真和真机，并比较 intent、视觉终点、文本 purpose 及注入层。",
    novelty: "GR00T N1.7 在 SimplerEnv-Bridge 从 64.3% 到 84.7%，RoboCasa 从 64.1% 到 70.3%；真机平均从 62.0% 到 68.7%，长时任务最高提升 12 点。",
    strengths: "teacher 只在训练期存在；跨两种 VLA 主干验证，并用 probe/干预检查 decoder 是否真的使用 intent。",
    limitations: "intent 仍由 teacher VLM 定义，可能混入语言偏差；真机平均增益小于部分仿真增益，执行视频监督也提高训练成本。",
    transfer: "可把 future video 先压成行为目的 latent，再监督 action decoder，减少直接重建像素对控制不相关细节的负担。",
    technique: [
      "teacher VLM 把当前状态、指令、粗动作与对应执行片段编码成 multimodal intent；student 在 decoder 中层对齐该表示。",
      "同时预测 endpoint visual 和 textual purpose，区分“行为目标”“如何展开”和“最终结果”；训练后删除所有 teacher 分支。",
    ],
    evaluation: [
      "GR00T N1.7 与 π0.5 在两个仿真基准上方向一致，说明收益不局限于单一 backbone。",
      "真机平均从 62.0% 到 68.7%，长时任务最高 +12 点；论文没有把仿真 20 点增益直接外推到真机。",
      "移除 intent、视觉/文本 grounding 与改变蒸馏层的消融表明 intent 是主要增益源，其他目标提供补充。",
    ],
    comparison: "原始 GR00T N1.7/π0.5、future visual/trajectory supervision、intent 与各 grounding 目标消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页提供 rollout；正文公开 teacher 输入、蒸馏位置、训练期目标和仿真/真机结果。"],
    missing: ["未确认训练代码、teacher prompt 与 checkpoint 公开；执行视频生成/对齐成本需自行复现。"],
    figureFile: "2608.23478-fig2.png",
    figureAlt: "INDI 的训练期行为意图蒸馏和部署时 VLA 路径",
    figureCaption: "Figure 2 · Teacher VLM 生成 intent/grounding 目标，部署时仅保留动作 decoder。来源：arXiv 原图。",
  },
  {
    title: "Think Only When Needed: Prompt-Authority Control for Selective Slow-Path Intervention in Vision-Language-Action Manipulation",
    arxivId: "2608.23224",
    url: "https://arxiv.org/abs/2608.23224",
    institutions: ["作者机构未在 arXiv HTML 首页明确标注"],
    signal: "把检索内容能否改写 VLA 指令当成权限问题：只有通过固定兼容规则的内容才能进入 canonical prompt。",
    tags: ["VLA", "Retrieval", "Prompt Authority"],
    classification: { research: "VLA", training: "Test-time Adaptation", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "冻结 VLA 对指令模板极敏感；检索到的文本即便语义正确，只要直接 append 也可能把控制成功率打到接近零。",
    methodSummary: "TOWN-VLA 分离候选检索与修改 prompt 的权限；不兼容时按 hash 精确恢复 Base，兼容时只渲染固定长度 canonical capsule。",
    architecture: "Task context 先经 ranking、compatibility 和 authority gate；执行侧只接 Base 或批准后的 compact prompt，action policy 始终冻结。",
    data: "LIBERO-Plus 的四套、七种扰动与 PiPER 真机；另构造 meaningful/meaningless 等长 append 做 prompt-form collapse 审计。",
    experiments: "每种方法 10,030 个 LIBERO-Plus episode；真机 Base 与 TOWN 各 150 次，并审计 900 条 route 的 hash、task signature 和 authorization。",
    novelty: "直接 append 将 92.47% 降至 3.00%，两种 append 在 500 paired states 均为 0；TOWN 在 LIBERO-Plus 从 69.5% 到 73.1%，真机从 52.7% 到 78.7%。",
    strengths: "样本量大、控制变量清楚；使用等长无意义文本证明失败主要来自 prompt form，而非检索语义。",
    limitations: "authority rule 仍是固定手工规则，论文也把无 oracle 的 admission calibration 留作下一步；机构和代码信息不完整。",
    transfer: "任何会写入机器人指令的检索/规划模块都应有显式 authority boundary，并支持精确回退到原 prompt。",
    technique: [
      "候选先按任务兼容性、动作阶段和格式契约过滤；授权成功只生成固定 schema 的短 capsule，否则恢复原 Base 字节序列。",
      "每条 route 记录 prompt hash、授权标志和 task signature，使检索干预可以回放和审计，而不改动 VLA 权重。",
    ],
    evaluation: [
      "10,030 episodes/方法的 matched LIBERO-Plus 评估给出 +3.6 点与 95% CI 1.89–5.45。",
      "PiPER 真机各 150 次，52.7% 提至 78.7%，p=3.16×10⁻⁶。",
      "900 routes 中 525 条精确恢复 Base、375 条授权 prompt 全部保持 task signature；但 admission 规则尚未学成。",
    ],
    comparison: "Base、raw append、meaningful/meaningless length-matched append、不同 gate 与 oracle-side routing。",
    reproducibilityStatus: "信息不足",
    implementation: ["正文披露 route contract、canonical prompt、样本量、置信区间、真机次数和审计字段。"],
    missing: ["未确认代码、prompt 模板和硬件配置公开；无 oracle 的自动准入仍未实现。"],
    figureFile: "2608.23224-fig2.png",
    figureAlt: "TOWN-VLA 的检索候选、权限检查和冻结策略执行流程",
    figureCaption: "Figure 2 · 只有通过兼容性与 authority gate 的检索内容才能改写执行 prompt。来源：arXiv 原图。",
  },
  {
    title: "TrAct: Bridging Robot Control and Visual Prediction with Visual Tracks",
    arxivId: "2608.24101",
    url: "https://arxiv.org/abs/2608.24101",
    institutions: ["University of Michigan", "Stanford University"],
    signal: "用视觉点轨迹作为动作与未来视频之间的共同接口，让世界模型更准确地比较候选动作后果。",
    tags: ["WAM", "Visual Tracks", "Planning"],
    classification: { research: "WAM", training: "Post-training", platforms: ["机械臂", "夹爪"] },
    motivation: "机器人动作依赖本体，且与像素变化对齐弱；直接 action-conditioned 视频预测容易忽略细粒度空间约束。",
    methodSummary: "VLAT 生成 action-track 候选，TWM 按 track 预测未来，VLAC 评估未来是否满足指令，再执行对应 action。",
    architecture: "三段式候选生成—track-conditioned world model—视觉语言 reward；visual track 同时约束预测和标识所配对的动作。",
    data: "大规模跨本体预训练后，在 LIBERO-INTEGRAL 与 Franka 真机操作上评价，包含更强组合和扰动设置。",
    experiments: "比较 π0.5、action-conditioned WM、track-conditioned WM、候选数与 reward model；仿真和真机均做闭环任务成功率。",
    novelty: "相对 π0.5，LIBERO-INTEGRAL 从 27% 到 55%，真机从 49% 到 76%；TWM 的视频预测也持续优于直接 action-conditioned WM。",
    strengths: "把表示改进落实到候选动作选择和真机成功率；视觉预测与控制共享同一 track，易于检查。",
    limitations: "多候选 world-model rollout 增加推理成本；track 对遮挡、接触与柔性物体的表达仍可能不足。",
    transfer: "如果 world model 不听低层动作，可先把候选动作转成图像空间轨迹，用同一轨迹条件化视频预测和 action pairing。",
    technique: [
      "VLAT 联合输出动作块与 task-relevant point tracks；TWM 只接收 tracks 生成未来，降低跨本体动作空间差异。",
      "VLAC 对每个 imagined future 打分，选择最高分 track 对应的原动作执行，闭环后重新采样候选。",
    ],
    evaluation: [
      "LIBERO-INTEGRAL 的 27%→55% 与 Franka 真机 49%→76% 都以 π0.5 为强基线。",
      "TWM 对比 action-conditioned WM 的预测质量和任务成功率均提升，支持 tracks 的中间接口作用。",
      "候选数、reward model、无 TWM 与不同 track 表示均有消融；在线计算成本是主要代价。",
    ],
    comparison: "π0.5、action-conditioned world model、无 track/TWM/VLAC 和不同候选规模。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文给出 VLAT/TWM/VLAC 信息流、候选执行过程、LIBERO-INTEGRAL 与 Franka 真机协议。"],
    missing: ["未确认代码、模型和跨本体预训练数据公开；实时控制频率与算力预算需结合附录。"],
    figureFile: "2608.24101-fig1.png",
    figureAlt: "TrAct 的动作轨迹候选、未来预测和奖励选择流程",
    figureCaption: "Figure 1 · action-track 候选经 track-conditioned 世界模型展开，再由 VLAC 选择执行。来源：arXiv 原图。",
  },
  {
    title: "Gripper-aware Vision Language Action Models",
    arxivId: "2608.24603",
    url: "https://arxiv.org/abs/2608.24603",
    institutions: ["University of Liverpool", "MBZUAI", "Indian Institute of Science", "The University of Tokyo", "ZHAW"],
    signal: "让 VLA 显式区分平行夹爪、吸盘等不同末端策略，而不是把 gripper 当成可忽略的本体差异。",
    tags: ["VLA", "Multi-gripper", "Cross-Embodiment"],
    classification: { research: "VLA", training: "Pre-training", data: "跨本体数据", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    motivation: "相同抓取目标在不同夹爪上需要不同接近与接触策略，但现有 VLA 数据主要来自平行夹爪。",
    methodSummary: "MiGA 数据集收集五类夹爪的 10.3 万条示范；GVLA 用多层 gripper token 和双级 mixture-of-adapters 路由策略。",
    architecture: "platform/type/instance 三级 soft prompt 编码夹爪；domain router 与 gripper router 从分层 adapter pools 选择 top-k residual adapters。",
    data: "MiGA 103K demonstrations，覆盖五种夹爪、多机器人、共享任务目标与策略差异，另包含新物体/新任务适配 split。",
    experiments: "仿真和真机比较通用 VLA、one-hot gripper id、单 adapter、双路由 GVLA，并测试未见物体、任务和新夹爪 few-shot。",
    novelty: "GVLA 在所测设置均优于论文基线，并提升新物体/未见任务 zero-shot 与新夹爪 few-shot 适配效率；主要证据来自同任务跨夹爪策略差异。",
    strengths: "数据和架构共同针对 gripper-aware 问题；有真实多夹爪和迁移实验，而非只把本体 id 当 metadata。",
    limitations: "五类夹爪仍未覆盖灵巧手连续接触；增益同时来自新数据与路由架构，跨完全不同动作空间的上限未明。",
    transfer: "跨末端数据可把共享能力与夹爪类型/实例差异分层编码，避免每个硬件单训一套 policy。",
    technique: [
      "三级 learnable tokens 分别表示平台、夹爪类型和具体实例，使共享知识与局部差异可分离。",
      "双级 router 先选 domain，再选 gripper adapters；top-k residual 只调整相关层，保留预训练 VLA 主干。",
    ],
    evaluation: [
      "同一任务在五种夹爪上比较，GVLA 相对共享 VLA 和单一 gripper id 更稳定。",
      "未见物体/任务看 zero-shot，新夹爪看 few-shot，分别检验语义泛化与硬件适配。",
      "token 层级、router 数量、adapter pool 和数据混合均有消融；摘要未给出统一总表绝对数，网站不补写。",
    ],
    comparison: "通用 VLA、gripper one-hot、单 adapter/router、三级 token 与双级 MoA 逐项消融。",
    reproducibilityStatus: "信息不足",
    implementation: ["正文给出五类夹爪、103K 数据量、token 层级、router/adapters 和仿真/真机 split。"],
    missing: ["未确认 MiGA、代码、权重和完整真机硬件配置公开。"],
    figureFile: "2608.24603-fig5.png",
    figureAlt: "GVLA 的多级夹爪 token 和双层 adapter 路由",
    figureCaption: "Figure 5 · 三级 gripper token 编码与 type-stratified mixture-of-adapters。来源：arXiv 原图。",
  },
  {
    title: "Rapid On-Robot Learning for Dynamic Manipulation Skills: Robot Juggling",
    arxivId: "2608.26800",
    url: "https://arxiv.org/abs/2608.26800",
    institutions: ["Robotics and AI Institute", "Carnegie Mellon University"],
    signal: "不丢弃不准确的先验模型，而是在真机上用局部经验修正它，并用互相可达集合约束每次抛接。",
    tags: ["Online Learning", "Dynamic Manipulation", "Safety"],
    classification: { research: "其他", training: "Test-time Adaptation", data: "在线数据 / 人工纠正", platforms: ["机械臂", "灵巧手"] },
    motivation: "纯仿真模型与真实三球杂耍差距大，盲目在线探索又不安全；动态技能必须在几分钟内从每次真实尝试中学习。",
    methodSummary: "Regularized Memory-Based Learner 在经验密集区域学习局部模型，在稀疏区域回退到全局先验；MRS 保证连续技能间存在满足关节/执行器约束的转移。",
    architecture: "Orchestrator 选择杂耍 pattern，skill executor 解码目标，memory learner 修正命令，model-based controller 生成关节轨迹，视觉异步跟踪球状态。",
    data: "完全来自机器人在线练习的抛接结果与初始先验模型；经验持续写入 memory，并用于下一次技能命令修正。",
    experiments: "双臂多指手机器人学习 cascade、tennis、half-shower、shower、box 五种三球模式；报告学习时间、连续成功与 MRS 回顾性消融。",
    novelty: "五种三球模式均在少于五分钟真实交互内学会；方法能安全组合投掷/接球技能，复杂 pattern 的瓶颈主要来自 open-loop catching。",
    strengths: "全部在线学习发生在真机，任务动态且复杂；先验/局部模型与安全可达集作用清晰，并做 MRS 消融。",
    limitations: "系统依赖精心设计的技能层、视觉追踪和模型控制；catching 仍是 open-loop，方法不是通用像素到动作 VLA。",
    transfer: "已有粗糙物理模型时，可让局部经验只修正高覆盖区域，并在未知区域保留先验，而非全量重学。",
    technique: [
      "局部 memory model 按与查询点的经验距离加权；正则项把稀疏区域拉回 global prior，降低少量噪声样本导致的外推失稳。",
      "MRS 预先求出相邻抛接目标间互相可达的状态集合，规划器只组合满足关节位置、速度和加速度限制的技能。",
    ],
    evaluation: [
      "五种三球模式均在真机小于五分钟内学习，包含从基础 cascade 到 box 等不同节奏和交叉关系。",
      "回顾性移除 MRS 后重新检查所有 planner query，量化额外安全约束何时实际阻止不可达转换。",
      "复杂模式性能出现平台期，正文把原因限定为 open-loop catching，而非宣称所有动态操作已解决。",
    ],
    comparison: "固定先验、仅局部模型、无正则记忆学习、移除 MRS 的回顾性消融和五种 pattern 难度。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文披露系统模块、memory regularization、MRS 约束、机器人平台、视觉频率与各 pattern 训练过程。"],
    missing: ["未确认代码、硬件控制栈和在线数据公开；迁移到非弹道动态任务需要重新定义技能与安全集合。"],
    figureFile: "2608.26800-fig1.png",
    figureAlt: "机器人杂耍在线学习的技能编排、记忆模型和安全控制系统",
    figureCaption: "Figure 1 · 经验记忆修正技能命令，MRS 约束可安全组合的抛接状态。来源：arXiv 原图。",
  },
  {
    title: "MA-VLA: Multi-Arm Vision-Language-Action Model for Collaboration and Compositional Generalization",
    arxivId: "2608.25864",
    url: "https://arxiv.org/abs/2608.25864",
    institutions: ["Dalian University of Technology", "University of Oxford", "Sun Yat-sen University", "Shanghai Jiao Tong University", "USTC", "CUHK Shenzhen", "Beihang University"],
    signal: "把高层任务拆成分配给各机械臂的 atomic prompts，并在训练时随机交换臂角色，专门测试未见协作组合。",
    tags: ["Multi-arm", "VLA", "Compositional Generalization"],
    classification: { research: "Subtask", training: "BC", data: "数据增强", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "GitHub", url: "https://github.com/zhangzaibin/future-robots" }],
    motivation: "多臂 VLA 通常把语言当成全局指令，训练时固定每只臂的角色，测试遇到新协作组合时难以重新分工。",
    methodSummary: "planner 产生逐阶段 atomic prompts 并分给各臂；Arm Shuffle 同步置换观测、状态与 prompt，迫使 policy 学习 role-agnostic 执行。",
    architecture: "高层分解器输出 per-arm prompts，统一 action model 接收每臂相机/状态；训练期 shuffle 保持 prompt 与对应本体通道成组交换。",
    data: "RoboFactory、RoboTwin2.0 与双 SO101 真机；测试 split 明确包含训练未出现的角色、空间状态和 atomic action 组合。",
    experiments: "仿真每配置 100 rollouts；真机四项双臂任务，比较 ACT/DP/RDT/VLA 基线、无 atomic prompt、无 shuffle 和独立臂模型。",
    novelty: "在 in-domain 与 compositional OOD 上均超过论文采用的 imitation/VLA 基线，优势在未见协作组合最明显；真机验证四类双臂协作。",
    strengths: "benchmark 的 OOD 定义直接针对协作组合；Arm Shuffle、prompt 分解与共享模型均有消融，代码/模型/数据入口已给出。",
    limitations: "atomic action 词表和 planner 仍需任务结构；双 SO101 规模较小，尚未覆盖异构臂或移动多臂系统。",
    transfer: "多机器人协作可以先把语言拆成 per-agent atomic prompt，并做角色置换增强，检查策略是否真正学到可重组技能。",
    technique: [
      "planner 将高层指令展开为阶段化 atomic prompts，明确每只臂当前应做什么，而非只给一个全局句子。",
      "Arm Shuffle 以一定概率同时交换各臂图像、状态和 prompt，阻止模型把“左臂/右臂”位置当成固定技能标签。",
    ],
    evaluation: [
      "RoboFactory 与 RoboTwin2.0 每个配置 100 rollouts，分别报告 in-domain 和训练未见协作组合。",
      "双 SO101 使用 12 DoF、全局相机和双腕相机，评估叠碗、放方块、传玩具和叠方块。",
      "移除 atomic assignment 或 Arm Shuffle 均明显伤害 OOD；独立双模型不能替代共享的角色可交换表示。",
    ],
    comparison: "ACT、Diffusion Policy、RDT/VLA、多臂独立模型及 atomic prompt/Arm Shuffle 概率消融。",
    reproducibilityStatus: "资源较完整",
    implementation: ["GitHub 声明提供代码、模型和数据；正文给出 benchmark split、100-rollout 协议与双 SO101 传感器。"],
    missing: ["真机每项具体重复次数和全部 checkpoint 需以仓库发布内容为准。"],
    figureFile: "2608.25864-fig2.jpg",
    figureAlt: "MA-VLA 的训练内协作组合与测试时未见组合示意",
    figureCaption: "Figure 2 · 角色、空间状态和 atomic action 的新组合构成 compositional OOD。来源：arXiv 原图。",
  },
  {
    title: "CLAP: Cross-Embodiment Video World Models are Zero-Shot Physical Simulators",
    arxivId: "2608.27406",
    url: "https://arxiv.org/abs/2608.27406",
    institutions: ["Princeton University"],
    signal: "先用 latent action 从无标签跨本体视频学物理，再用末端动作课程式 grounding，使视频世界模型能直接服务真实机器人。",
    tags: ["World Model", "Cross-Embodiment", "Video Pre-training"],
    classification: { research: "WM", training: "Pre-training", data: "跨本体数据", platforms: ["机械臂", "Humanoid", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://omni-clap.github.io" }, { label: "GitHub", url: "https://github.com/omni-CLAP/clap" }],
    motivation: "单本体 action-conditioned video model 无法利用大量人类与异构机器人视频；latent action 易扩数据，却不能直接控制机器人。",
    methodSummary: "CLAP 用末端姿态、语言和 latent action 三种接口统一视频；CLAP-CURR 先做 latent-action 预训练，再以 end-effector action grounding。",
    architecture: "视频模型学习跨本体未来生成；latent action 捕获未标注运动，后续 EE action 阶段把动态映射回几何控制，可用于 planning 或生成 policy-improvement 数据。",
    data: "互联网人类视频、OXE 混合、DROID、Bridge、双臂 YAM 与 G1 Humanoid 等多种本体视频。",
    experiments: "比较三种 action harmonization、单本体视频模型、DROID/Bridge 预测；并将 CLAP 用于跨 policy planning 和 RL policy finetuning 的真机验证。",
    novelty: "CLAP-CURR 在 DROID 接近或超过单本体模型，few-shot 适配优势继续扩大；真机中可提高 π0.5 与 MolmoAct-2 的策略成功率。",
    strengths: "跨本体视频覆盖广，开放代码和模型；不只看生成指标，还连接到真实策略选择和后训练。",
    limitations: "它是物理模拟器而非直接 VLA；生成质量到控制收益仍依赖 planner/reward，摘要未给一个统一真机绝对成功率。",
    transfer: "跨本体世界模型可先用 latent action 吸收无标签视频，再用少量统一末端动作完成可执行 grounding。",
    technique: [
      "CLAP-LAM 从视频内部学习 latent action，CLAP-EE 用连续末端动作，CLAP-LANG 用离散语言；课程训练组合前两者的规模与可执行性。",
      "部署时用 CLAP 对多个策略候选展开视频后果并选择，或把生成 rollout 作为 RL fine-tuning 的模拟经验。",
    ],
    evaluation: [
      "在 OXE-Mix、DROID、Bridge 和多本体设置比较预测 fidelity，latent action 更适合无标签规模化，EE action 更适合精细可控。",
      "few-shot target-embodiment adaptation 显示跨本体预训练优势可累积，而非只在 zero-shot 产生一次性收益。",
      "真实 YAM/G1 与 π0.5、MolmoAct-2 policy improvement 证明模拟器可用于控制，但仍需单独的候选策略或 RL。",
    ],
    comparison: "单本体视频模型、CLAP-LAM/EE/LANG/CURR、DROID/Bridge 预测和跨 policy planning/RL。",
    reproducibilityStatus: "资源较完整",
    implementation: ["GitHub 已提供代码/模型入口；正文披露 action interfaces、curriculum、数据本体和 planning/RL 用法。"],
    missing: ["跨来源数据的精确清单和部分真机试验次数需结合发布仓库；真实物理准确性仍局限于所测任务。"],
    figureFile: "2608.27406-fig1.png",
    figureAlt: "CLAP 的跨本体视频、动作统一和真实任务迁移总览",
    figureCaption: "Figure 1 · 跨本体 latent/EE action 预训练与少样本/零样本真实任务适配。来源：arXiv 原图。",
  },
  {
    title: "Latent Action as Intention Enables Efficient Future Imagination for World Action Models",
    arxivId: "2608.24882",
    url: "https://arxiv.org/abs/2608.24882",
    institutions: ["CollegeAI, Tsinghua University", "Institute for AI Industry Research, Tsinghua University", "CASIA", "TARS Robotics", "Southeast University"],
    signal: "不生成未来视频，而是联合去噪一个由 action-free 视频预训练得到的离散意图 latent 和可执行动作块。",
    tags: ["WAM", "Latent Action", "Efficient Inference"],
    classification: { research: "WAM", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://getterupper.github.io/LAWA" }],
    motivation: "同步 WAM 生成未来视频太慢，Fast-WAM 删除未来分支又会在小数据和 OOD 场景损失泛化。",
    methodSummary: "LAWA 用 action-free 预训练的离散 tokenizer 产生 manipulation-centric code；推理时联合去噪连续 intention latent 与动作，不渲染未来帧。",
    architecture: "训练含当前/未来视频 encoder、latent action tokenizer 与 action decoder；结构化 mask 控制三分支信息流，推理删除 future-video branch。",
    data: "action-free egocentric video 预训练、RoboCasa 机器人示范、LIBERO-Plus 和真实机器人任务数据。",
    experiments: "RoboCasa few-shot/full、LIBERO-Plus zero-shot、真机操作和延迟；匹配比较 Fast-WAM、Joint-WAM、无 tokenizer 预训练及 codebook 设计。",
    novelty: "RoboCasa few-shot/full 为 65.6%/80.8%，比匹配 Fast-WAM 高 9.6/4.5 点；保持 Joint-WAM 水平同时推理延迟低 42.9%。",
    strengths: "效率与泛化在匹配实现下比较；有 action-free 预训练、tokenizer、future branch 和 codebook 消融，并包含真机。",
    limitations: "latent intention 的可解释性低于显式未来视频；代码/模型尚处于将发布状态，真实任务规模有限。",
    transfer: "部署 WAM 太慢时，可把未来变化压成训练期学到的离散/连续 intention latent，而不是完全删除未来监督。",
    technique: [
      "离散 tokenizer 从无动作视频学习操作变化 codebook，作为连续 intention denoising 的锚点；action 与 intention 在同一 Transformer 中联合生成。",
      "结构化 attention mask 允许训练时读取未来监督，部署时移除未来视频 encoder/decoder，只保留 latent 与 action 路径。",
    ],
    evaluation: [
      "RoboCasa few-shot 中对 Fast-WAM 的 +9.6 点大于 full-data 的 +4.5 点，符合 future prior 在低机器人数据下更有用的假设。",
      "相对 Joint-WAM 延迟降低 42.9% 而成功率接近；对比是在匹配 backbone/训练协议下完成。",
      "LIBERO-Plus 与真机支持 OOD/部署结论，但真实任务数量不足以证明所有复杂操作都可由 compact latent 代替视频。",
    ],
    comparison: "Fast-WAM、Joint-WAM、无 action-free 预训练、不同 codebook/latent loss 与 future branch 消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页已给出；正文披露 tokenizer、mask、few-shot/full split、延迟测量和主要训练设置。"],
    missing: ["代码和模型标注为后续发布；action-free 数据清单与完整真机试验细节尚未全部开放。"],
    figureFile: "2608.24882-fig2.png",
    figureAlt: "LAWA 的未来视频、latent intention 和动作联合建模结构",
    figureCaption: "Figure 2 · 训练期 future branch 提供监督，推理只联合生成 compact intention 与动作。来源：arXiv 原图。",
  },
];

export const paperDaily20260828: Paper[] = entries.map(makePaper);
