import type { Paper } from "./site-data";
import { paperDaily20260724RerunAdditions } from "./paper-daily-2026-07-24-rerun";

const priorPaperDaily20260724: Paper[] = [
  {
    rank: 1,
    title: "Patch Policy: Efficient Embodied Control via Dense Visual Representations",
    arxivId: "2607.18236",
    url: "https://arxiv.org/abs/2607.18236",
    institutions: ["New York University", "Meta FAIR", "AMI Labs"],
    signal: "用冻结 ViT 的 dense patch features 构建轻量、高频且保留空间细节的机器人策略",
    tags: ["Dense Representation", "Imitation Learning", "Efficient Policy"],
    classification: { research: "表征学习", training: "BC", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://patch-policy.github.io/" }, { label: "GitHub", url: "https://github.com/gaoyuezhou/patch_policy" }],
    motivation: "把一帧压成单个 global token 会丢失精细几何，而端到端微调十亿参数 VLM 又难以满足高频控制。",
    methodSummary: "直接读取冻结视觉编码器的 dense patch tokens，并用 block-causal attention 让同一帧内 patch 充分交互、跨帧保持因果；观察 trunk 可连接 VQ-BeT、Diffusion Policy 等动作头。",
    architecture: "多视角图像分别编码为 patch sequence，可拼接 goal image 与 proprioception；Transformer 只训练轻量 observation trunk 和 action head，视觉 backbone 保持冻结。",
    optimization: "行为克隆，不使用 RL；系统比较五种视觉 backbone、patch/global pooling、token 压缩、attention mask、模型大小和推理延迟。",
    data: "仿真覆盖 Push-T、LIBERO-Goal、BlockPush、Cube；Franka 真机自采 Tool Hanging、Pen Collection、Cable Insertion，并用 CAP 数据测试十个训练未见物体抓取。",
    experiments: "三项真机最终阶段成功率为 70%、85%、90%，十个未见物体抓取为 87%；仿真平均相对 global feature 提升 40%，并以约 0.7% 参数量超过 OpenVLA-OFT 18%。",
    novelty: "相对 global pooling，它保留预训练 ViT 的局部 token；相对大型 VLA，它不携带完整 VLM。控制变量实验表明增益来自 dense representation 与帧级因果 mask。",
    strengths: "真机、未见物体、五种视觉表征、效率和结构消融都围绕同一假设展开。",
    limitations: "仍依赖行为克隆和固定数据分布；dense token 增加序列长度，真机结果没有置信区间。",
    transfer: "可作为 VLA 下游的轻量视觉基线，也可把 force/contact token 作为少量非视觉 token 与 patch features 融合。",
    experimentDetails: [{ title: "仿真、真机与效率对照", setup: "四类仿真套件、三项 Franka 任务及十个未见对象抓取；对视觉表征、动作头与模型规模逐项控制。", comparisons: "global-pooled WebSSL、从头视觉、OpenVLA-OFT、不同 patch backbone/压缩率/mask。", results: ["跨四个仿真环境，dense patch policy 相对 global representations 平均提升约 40%。", "三项真机最终阶段成功率为 70%、85%、90%，CAP 未见物体抓取为 87%。", "相对 OpenVLA-OFT 提升 18%，策略参数量约为其 0.7%；压缩 patch 可进一步交换精度与延迟。"] }],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["项目页与 GitHub 已公开。"], implementation: ["冻结 ViT；dense patch tokens；block-causal mask；支持 VQ-BeT/Diffusion Policy 类 action head；论文附超参、模型大小与延迟。"], missing: ["三项自采真机数据和全部训练 checkpoint 是否公开需以仓库发布状态为准。"] },
    deepDive: { lead: "Patch Policy 只改变视觉表征进入策略的方式：局部 patch 不先做全局池化，时间因果则由 attention mask 保证。", sections: [{ title: "帧内密集、帧间因果", paragraphs: ["同一时刻的多视角 patch 可以互相注意，从而组合对象边界、抓取点和相对位置；未来帧被 mask，动作 token 只能读取当前与历史观察。", "冻结 backbone 避免昂贵端到端视觉微调。若任务频率受限，可对 patch 做空间压缩；论文通过压缩率消融量化细节保真与速度的折中。"] }], equations: [{ name: "block-causal attention", expression: "A(i,j)=1 当 time(j)≤time(i)，且同帧 patch 可全连接；否则 A(i,j)=0", explanation: "mask 保留帧内空间交互，同时阻止当前动作读取未来观察。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-24/2607.18236-method.png", alt: "Patch Policy 的 dense patch observation trunk、帧级因果注意力与动作头", caption: "Figure 2 · Patch Policy architecture。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 2,
    title: "WorldScape Policy 2.0: Empowering Steerable World Action Modeling with Reasoning-Augmented Memory",
    arxivId: "2607.18840",
    url: "https://arxiv.org/abs/2607.18840",
    institutions: ["Manifold AI", "Tsinghua University", "Shanghai Jiao Tong University"],
    signal: "把事件级长期记忆与连续视觉短期记忆结合到可多模态提示的 WAM",
    tags: ["World Action Model", "Event Memory", "Visual Prompt"],
    classification: { research: "WAM", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂"] },
    detailAttributes: { memoryImplementation: "global-history / local-active / event-boundary + causal visual prefill", memoryHorizon: "事件级长期与连续帧短期并行" },
    resources: [{ label: "项目页", url: "https://manifoldai-research.github.io/WorldScape-Policy/" }, { label: "GitHub", url: "https://github.com/manifoldai-research/WorldScape-Policy" }],
    motivation: "短窗口 WAM 难以判断长任务进度，完整视觉历史又缺少事件组织；只用文本条件也无法直接利用目标图像或跨本体示范。",
    methodSummary: "VLM 把历史整理成全局、当前活动和事件边界记忆并生成 planning tokens；video-action DiT 用 causal prefill 保存近期动力学，同时接收文本、目标图像或示范视频。",
    architecture: "Wan2.2-5B 初始化共享 video-action DiT，约 4B VLM 负责事件记忆；semantic forcing 在训练中把 event caption 的控制能力迁移为高层任务下的隐式 subgoal planning。",
    optimization: "三阶段无 RL：ManipEvent-5M 事件级预训练；加入长期记忆与 semantic forcing 的 mid-training；面向 PiPER、RoboTwin 等下游本体后训练。",
    data: "ManipEvent-5M 近 500 万 segments、512M frames、2,983 小时、944K episodes，混合 PiPER、UMI、AgiBot World、RoboMIND、DROID、LIBERO 等。",
    experiments: "RoboTwin 2.0 50 任务平均 94.3%，更严格 clean-to-randomized 为 47.9%；PiPER 五类真机任务各 20 次，长程/视觉提示设置部分达到 60%–75%。",
    novelty: "相对 MemoryWAM 的视觉检索，它显式提取 event boundary 与 task progress；相对文本控制 WAM，它统一支持 goal image 和跨本体 video prompt。",
    strengths: "数据、三阶段训练、长短期记忆和 semantic forcing 都有相应消融，并包含严格 OOD 与真机。",
    limitations: "5B WAM + 4B VLM 和大规模混合数据复现成本高；主表 94.3% 与 clean-to-randomized 47.9% 差距说明 OOD 仍是难点。",
    transfer: "可把连续视觉缓存用于局部动力学，把事件边界、完成谓词和失败节点写入稀疏长期 memory。",
    experimentDetails: [{ title: "多基准、记忆与视觉提示", setup: "RoboTwin 2.0、LIBERO 类模拟任务与 PiPER 双臂真机；真机五类任务每类 20 次。", comparisons: "无长期记忆、无短期视觉 prefill、无 semantic forcing、不同提示形式与已有 WAM。", results: ["RoboTwin 2.0 50 任务平均 94.3%，但 clean-to-randomized 仅 47.9%。", "PiPER 长时和视觉提示任务中部分设置达到 60%–75%，说明目标图像/视频条件可传递到真机。", "移除事件记忆或 semantic forcing 会降低长任务进度判断，移除短期 prefill 更影响局部动作连续性。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页与 GitHub 已公开；数据规模、来源和三阶段训练在论文中披露。"], implementation: ["Wan2.2-5B video-action DiT；约 4B VLM；causal prefill；event memory；semantic forcing；三阶段 curriculum。"], missing: ["完整 ManipEvent-5M、全部训练配比和大模型 checkpoint 的开放范围需按仓库核验。"] },
    deepDive: { lead: "WorldScape Policy 2.0 将历史拆成两种时间尺度：连续帧回答‘刚发生了什么’，事件记忆回答‘任务进行到哪一步’。", sections: [{ title: "双层记忆与 semantic forcing", paragraphs: ["VLM 从历史 chunk 中生成 global-history、local-active 与 event-boundary 表征，并把检索结果转换为 planning tokens。DiT 侧的 causal prefill 保留近期图像与动作连续性，两条路径在 action/video generation 前汇合。", "预训练阶段模型按 event caption 学会细粒度控制；mid-training 用 semantic forcing 逐步减少显式 event caption，让模型根据高层任务和历史自动恢复下一事件。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-24/2607.18840-method.png", alt: "WorldScape Policy 2.0 的多模态提示、事件长期记忆、视觉短期记忆和 video-action DiT", caption: "Figure 2 · WorldScape Policy 2.0 方法总览。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 3,
    title: "FM-VLA: Force-based Memory for Vision-Language-Action Models in Contact-Rich Manipulation",
    arxivId: "2607.18231",
    url: "https://arxiv.org/abs/2607.18231",
    institutions: ["Tsinghua University", "Microsoft Research", "Fudan University", "University of Science and Technology of China"],
    signal: "将完整六轴力历史压成少量 tokens，为 VLA 提供低带宽 episodic memory",
    tags: ["Force Memory", "Contact-rich", "VLA"],
    classification: { research: "Memory", training: "Post-training", modalities: ["Force / Torque"], platforms: ["Humanoid", "夹爪"] },
    detailAttributes: { memoryImplementation: "Perceiver-IO Force-VAE 压缩六轴 wrench history", memoryHorizon: "单个 episode 内完整力历史" },
    resources: [{ label: "项目页", url: "https://qft-333.github.io/FM-VLA-Page/" }, { label: "GitHub", url: "https://github.com/qft-333/FM-VLA" }],
    motivation: "重复按压次数、擦拭进度和遮挡搜索状态在视觉上可能近似，瞬时力又无法表示已经发生过的接触历史。",
    methodSummary: "Force-VAE 用 Perceiver-IO 把长六轴 wrench 序列压成 8 个 latent tokens，另以一个 token 编码约 1 秒关节历史；这些 tokens 作为 suffix 注入 π0.5 action expert。",
    architecture: "第一阶段 Force-VAE 重建完整力历史；第二阶段冻结它，微调 VLM、flow-matching action expert 与两个 projector，视觉、语言、状态和力记忆共同条件化动作。",
    optimization: "两阶段后训练，无 RL：VAE 使用重建 + KL；VLA 阶段用 flow matching。",
    data: "AgiBot G1 双臂自采 750 条 VR 遥操作示范，覆盖杯下找物、重复按键和擦拭，并使用 Zhiyuan Challenge 数据补充。",
    experiments: "三任务每方法各 18 次，FM-VLA 平均成功率 83.3%，高于无记忆、短期力和视觉记忆；还消融 encoder、token 数和输入模态。",
    novelty: "相对瞬时 force conditioning，它保留 episode 级历史；相对视觉 memory，它只存低带宽接触信号，并把推理额外延迟控制在约 3.3 ms。",
    strengths: "对照直接、消融覆盖 memory 形式与 token 数，三任务都要求区分视觉相似但接触历史不同的状态。",
    limitations: "750 条示范与三项固定任务均为同平台同分布，跨传感器、跨物体和跨接触模式尚未验证。",
    transfer: "可将 force latent 同时监督为 contact count、slip、phase 或 failure risk，使 memory 更可诊断。",
    experimentDetails: [{ title: "力记忆对照与结构消融", setup: "AgiBot G1 上三项真机任务，每个方法—任务组合 18 次。", comparisons: "π0.5 无 memory、短期 force、视觉 history、不同 Force-VAE encoder 和 token 数。", results: ["完整 FM-VLA 三任务平均成功率 83.3%。", "短期力在需要计数或长期擦拭进度时不足，视觉历史则计算更重且易被遮挡。", "8 个 force tokens 在精度与约 3.3 ms 额外延迟间取得较好折中。"] }],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["项目页与 GitHub 已公开；论文披露 750 条示范和评测协议。"], implementation: ["Perceiver-IO Force-VAE；8 force latent tokens；约 1 秒 joint-history token；π0.5；VAE reconstruction+KL；VLA flow matching。"], missing: ["完整真机数据、传感器标定和训练 checkpoint 的开放范围需按仓库核验。"] },
    deepDive: { lead: "FM-VLA 不保存图像历史，而把 episode 内的接触过程压成固定数量的力 token。", sections: [{ title: "Force-VAE 与 action suffix", paragraphs: ["Perceiver-IO 用少量 latent query 读取任意长度 wrench history；decoder 只在预训练期重建信号，部署时保留 encoder。关节历史 token 用于区分相似力形状下的不同机器人运动。", "两个 projector 将 force/state memory 对齐到 action expert hidden dimension，作为 suffix 与视觉语言上下文共同参加 flow matching。"] }], equations: [{ name: "Force-VAE 目标", expression: "ℒ = ‖F − D(E(F))‖² + β KL(q(z|F) ‖ N(0,I))", explanation: "重建项保留接触序列，KL 约束固定维 latent；后续 VLA 只读取 E(F) 的 8 个 tokens。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-24/2607.18231-method.png", alt: "FM-VLA 的 Force-VAE 预训练与力记忆 token 注入 π0.5 的两阶段流程", caption: "Figure 2 · FM-VLA training pipeline。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 4,
    title: "RynnBrain 1.1: Towards More Capable and Generalizable Embodied Foundation Model",
    arxivId: "2607.17977",
    url: "https://arxiv.org/abs/2607.17977",
    institutions: ["DAMO Academy, Alibaba Group", "Lupan Lab"],
    signal: "用统一具身预训练连接 3D grounding、contact point 与跨本体 VLA action",
    tags: ["Embodied Foundation Model", "3D Grounding", "Cross-embodiment"],
    classification: { research: "VLA", training: "Pre-training", modalities: ["Point Cloud / 3D"], data: "跨本体数据", platforms: ["Humanoid"], deployment: "跨本体迁移" },
    resources: [{ label: "模型", url: "https://huggingface.co/Alibaba-DAMO-Academy/RynnBrain1.1-9B" }],
    motivation: "语言、视频、3D grounding、contact point 与机器人动作通常由分离模型处理，导致感知先验无法直接迁移到跨本体控制。",
    methodSummary: "先用统一自回归接口训练 embodied multimodal model，再以单流 DiT action expert 做 flow-matching VLA；81D shared action canvas 与 embodiment mask 对齐不同机器人。",
    architecture: "Qwen3.5 系列 backbone 支持多尺度模型；VLA 将语言、多视角图像、状态和噪声动作送入单流 DiT，mask 只激活目标本体可用的 action slots。",
    optimization: "embodied multimodal autoregressive pre-training 后接 VLA flow-matching post-training，不使用 RL。",
    data: "混合 LLaVA、视频、3D/具身认知、自采 reasoning/planning、AgiBotWorld 和 Open X-Embodiment；论文未披露完整 mixture 总量与真机示范数。",
    experiments: "三项主任务每项 20 次，generalist joint training 平均成功率 91.67%；在 Unitree G1、Astribot S1 与 Tianji-Wuji 上展示多平台任务。",
    novelty: "相对同 recipe 的通用 Qwen-VLA 初始化，RynnBrain 先接受 3D/contact 等具身监督；shared action canvas 让多本体共享模型而不混淆未使用维度。",
    strengths: "同训练 recipe 的初始化对照与多平台真机说明 embodied pretraining 可转移到动作学习。",
    limitations: "cross-embodiment 主要是已见本体联合训练，不是 held-out robot 零样本；数据配比和真机训练量缺失。",
    transfer: "可复用统一 action canvas + embodiment mask，并在动作训练前加入 3D grounding 与 contact point 监督。",
    experimentDetails: [{ title: "具身初始化与多平台真机", setup: "三项主任务各 20 次，并在三种 humanoid/双臂平台补充多任务展示。", comparisons: "相同训练 recipe 的 Qwen-VLA、single-task 与 generalist joint training。", results: ["generalist joint training 在三项主任务平均达到 91.67%。", "RynnBrain initialization 优于通用 Qwen 初始化，支持具身多模态预训练的迁移价值。", "多平台结果来自已见本体联合训练，不能等同于未见硬件零样本控制。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["9B 模型权重入口已公开。"], implementation: ["Qwen3.5 backbone；single-stream DiT；flow matching；81D action canvas；embodiment mask；多视角输入。"], missing: ["完整训练 mixture、各平台示范数量、训练算力和动作 checkpoint 开放范围未披露。"] },
    deepDive: { lead: "RynnBrain 1.1 试图让空间与接触理解成为 VLA 初始化的一部分，而不是控制阶段外接的工具。", sections: [{ title: "共享动作画布", paragraphs: ["不同机器人的状态和动作被放入固定 81D canvas；embodiment mask 指示每个平台实际使用的维度，避免对缺失关节计算损失。", "单流 DiT 同时处理语言、图像、机器人状态与带噪动作，flow matching 输出 action chunk；具身自回归预训练则先建立 3D、contact 与时序理解。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-24/2607.17977-architecture.png", alt: "RynnBrain-VLA 的多模态输入、单流 DiT 和统一跨本体动作空间", caption: "Figure 3 · RynnBrain-VLA architecture。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 5,
    title: "Closing the Loop in Humanoid VLA: Persistent 3D Object Tokens for Verifiable Loco-Manipulation",
    arxivId: "2607.18016",
    url: "https://arxiv.org/abs/2607.18016",
    institutions: ["Beihang University", "Beijing Zhongguancun Academy", "Tianjin University", "DeepCybo", "Zhongguancun Academy Institute"],
    signal: "让同一组持久 3D object records 同时条件化 humanoid 动作与执行验证",
    tags: ["Humanoid", "3D Object Tokens", "Execution Verification"],
    classification: { research: "VLA", training: "Post-training", modalities: ["Depth / RGB-D", "Point Cloud / 3D"], platforms: ["Humanoid", "灵巧手"], deployment: "真机部署优化" },
    motivation: "humanoid 行走、抓取和放置之间，对象会移动、遮挡或被误抓；若动作模型与任务 monitor 使用不同状态表示，就会提前切换子任务或重复失败。",
    methodSummary: "POT 从 RGB-D 和分割构建 role-indexed 3D object records，一路投影为 VLA action tokens，另一路计算几何 predicate；每个短 action chunk 后刷新记录并决定继续、重试或重规划。",
    architecture: "以 GR00T-N1.7 为基础，Persistent Object Tokenization 保存对象角色、3D pose、尺寸与关系；action expert 和 verifier 读取同一 records，failure handler 按 predicate 结果闭环。",
    optimization: "VLA imitation post-training 加 object-token sidecar 与执行监督，不使用 RL；predicate 阈值由任务和标定配置。",
    data: "Unitree G1 + 灵巧手真机示范，并为每条 demonstration 生成 object-token sidecar；原文未披露示范数量。",
    experiments: "八类任务各 10 次，direct GR00T-N1.7 为 39/80，POT-VLA 为 71/80；对 verifier、tokens 与完整闭环做消融，并测试未见物体、位置变化和执行中扰动。",
    novelty: "相对外部 task manager，POT 用同一物理对象状态驱动 action 与 verification，直接减少 object-state divergence。",
    strengths: "八类真机、模块消融和 controlled shift 都针对‘可执行且可验证的对象状态’。",
    limitations: "示范量缺失，依赖 RGB-D、分割、标定和人工 predicate；每项 10 次不足以精确估计小差异。",
    transfer: "可把 object record 作为 VLA 与 planner/verifier 的共享接口，并加入 force/contact predicate 覆盖视觉不可判别状态。",
    experimentDetails: [{ title: "八类 humanoid 真机与闭环消融", setup: "Unitree G1 上八个 task family，各 10 次；另有 Being-0-aligned 五任务参考。", comparisons: "matched direct GR00T-N1.7、仅 object tokens、仅 verifier 与完整 POT-VLA。", results: ["matched 主表由 39/80 提升到 71/80。", "在 Being-0-aligned 设置达到 44/50，论文引用的 Being-0 结果为 37/50。", "涉及持续 3D 关系、错误放置与恢复的任务增益最大；移除 verifier 后常能推进但会错误确认完成。"] }],
    reproducibilityDetails: { status: "信息不足", verifiedResources: ["论文披露 Unitree G1、八类任务、每类 10 次与系统消融。"], implementation: ["RGB-D + segmentation；role-indexed 3D records；GR00T-N1.7 action expert；geometric predicates；chunk-level re-observation。"], missing: ["示范数量、训练时长、代码、object-token sidecar 与 predicate 阈值未公开。"] },
    deepDive: { lead: "POT-VLA 将对象状态从一次性视觉 feature 变成跨动作 chunk 持续更新的显式 3D record。", sections: [{ title: "持久对象记录与验证", paragraphs: ["每个对象按 task role 建立记录，而不是只保留类别名称；RGB-D 更新位置、姿态、尺寸和对象间关系。role-aware projector 将记录变成 action expert token。", "执行短 chunk 后，系统重新观测并计算 inside、on-top、held-by 等几何 predicate。未满足时可以重试或重规划，满足时才推进 subtask。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-24/2607.18016-overview.jpg", alt: "POT-VLA 用持久三维对象记录连接动作预测、执行验证与恢复", caption: "Figure 1 · POT-VLA 闭环 humanoid loco-manipulation 总览。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 6,
    title: "RoboHarness: Memory-Driven Orchestration of Heterogeneous Robot Policies for Long-Horizon Planning",
    arxivId: "2607.18060",
    url: "https://arxiv.org/abs/2607.18060",
    institutions: ["Huawei Noah's Ark Lab", "University of British Columbia", "University of Toronto", "McGill University", "Huawei 2012 Labs"],
    signal: "用执行记忆学习不同 policy 的能力边界，并稳定 VLA、RL 与 TAMP 的交接",
    tags: ["Policy Orchestration", "Execution Memory", "Long-horizon"],
    classification: { research: "Subtask", training: "Test-time Adaptation", platforms: ["机械臂", "夹爪"] },
    detailAttributes: { memoryImplementation: "multimodal execution memory + Memory Bridge retrieval", memoryHorizon: "跨 episode 累积 policy capability evidence" },
    motivation: "单一 VLA、RL 或 TAMP 各自只在部分状态可靠；长任务不仅需要正确拆分，还要避免前一策略把机器人留在后一策略训练分布之外。",
    methodSummary: "把异构控制器封装为 agentic skills，依据执行记忆估计上下文相关能力边界并路由 subtask；Memory Bridge 检索下一策略的历史轨迹，先把当前状态引导回其 in-distribution 区域。",
    architecture: "理解模块完成场景/指令解释，memory 记录策略、状态、结果与多模态轨迹，自演化模块更新能力估计；底层可组合 π0.5、OpenVLA-OFT、RL 和 TAMP。",
    optimization: "不联合重训底层 policy；通过在线执行证据更新路由与 memory。Memory Bridge 在 handoff 前生成过渡动作。",
    data: "三个公开 benchmark、500 个自定义长时任务和 135 次真机实验；底层复用公开或已有 VLA/RL/TAMP。",
    experiments: "LIBERO-Plus 七类扰动平均成功率 93.2%，六类排名第一；500 任务消融显示理解、演化和 Memory Bridge 分别处理分解、路由与交接失败。",
    novelty: "相对固定 skill library，它在线学习 policy 的条件化能力边界；相对只做高层选择，它显式修复跨 policy 状态分布不匹配。",
    strengths: "三类异构 policy、500 自定义任务、OOD 扰动、组件消融与 135 次真机形成较广验证。",
    limitations: "系统依赖 agent/VLM 推理与已有底层策略，复杂度和调用成本高；memory 错误可能传播到路由。",
    transfer: "在组合多套 VLA/控制器时，可为每个 policy 维护可检索的成功状态分布，并把 handoff 当成独立控制问题。",
    experimentDetails: [{ title: "异构路由、OOD 与组件消融", setup: "三个公开 benchmark、LIBERO-Plus 七类扰动、500 个定制长任务与 135 次真实机器人执行。", comparisons: "单一 π0.5/OpenVLA-OFT、固定路由、移除 Understanding/Evolution/Memory Bridge 的系统。", results: ["LIBERO-Plus 七类扰动平均成功率 93.2%，在六类中排名第一。", "π0.5 在 lighting/background 更可靠时被更多调用；camera/robot-state/language shift 下系统转向 TAMP，调用比例与独立成功率正相关。", "移除 Memory Bridge 后进度仍较高但完整成功下降，说明它主要解决 policy handoff 而非高层分解。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["论文给出 500 任务、135 真机试验、底层 policy 与 memory 数据结构附录。"], implementation: ["multimodal execution memory；capability-aware routing；Memory Bridge trajectory retrieval；π0.5/OpenVLA-OFT/RL/TAMP wrappers。"], missing: ["完整代码、500 任务配置、所有 agent prompt 与真实轨迹未确认公开。"] },
    deepDive: { lead: "RoboHarness 将 policy 能力看成与状态和扰动相关的经验分布，而不是静态的技能名称。", sections: [{ title: "执行记忆与 Memory Bridge", paragraphs: ["每次执行把指令、观察、调用 policy、轨迹与结果写入 memory。后续规划检索相似上下文，估计某 policy 在当前扰动下是否可靠。", "若选择下一 policy，Memory Bridge 从其成功轨迹估计 in-distribution state region，并先生成一段过渡，使交接状态更像该 policy 的训练数据。Evolution skill 根据新结果持续修正能力边界。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-24/2607.18060-overview.png", alt: "RoboHarness 的理解、执行记忆、自演化、异构 policy 路由和 Memory Bridge", caption: "Figure 1 · RoboHarness memory-driven policy orchestration。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 7,
    title: "Test-Time Scaling for World Action Models via Zero-Shot Geometric Verification",
    arxivId: "2607.17454",
    url: "https://arxiv.org/abs/2607.17454",
    institutions: ["University of Michigan", "NVIDIA"],
    signal: "用跨视角深度重投影筛选 WAM 候选，只在 action–future 不一致时增加采样",
    tags: ["WAM", "Test-time Scaling", "Geometric Verification"],
    classification: { research: "WAM", training: "Test-time Adaptation", modalities: ["Depth / RGB-D"], platforms: ["机械臂", "夹爪"] },
    motivation: "WAM 可同时提出动作和未来图像，但固定 Best-of-N 每步都增加延迟，训练 value head 又绑定具体模型与任务。",
    methodSummary: "GeoBoN 用冻结深度 foundation model 计算候选未来的跨视角重投影一致性并选择最佳 rollout；Gated GeoBoN 先检查初始 action–future 一致性，只在可疑决策点触发额外采样。",
    architecture: "方法位于现有 WAM 外部，不改权重；对每个 candidate 的多视角 future 估深度并做 reprojection，gate 使用动作与预测变化的内部一致性信号。",
    optimization: "training-free test-time scaling；固定预算实验 N=8，门控版本动态选择是否调用 GeoBoN。",
    data: "RoboCasa、LIBERO Long、RoboTwin 2.0 的五个 benchmark–backbone 设置，覆盖 Cosmos Policy 与 X-WAM。",
    experiments: "N=8 在五个设置全部提升；RoboCasa 上 Cosmos 66.3%→68.4%、X-WAM 80.8%→82.5%。门控仅在 26.2% 决策点触发，保留平均 74.8% 的 always-on 增益。",
    novelty: "相对学习 value/reward model，它用零样本几何基础模型；相对固定 Best-of-N，它在执行前先决定该步是否值得增加计算。",
    strengths: "跨三个 benchmark、两个 WAM family，一致报告 selector、gate 和 N 的诊断。",
    limitations: "深度重投影偏好视觉几何一致，不一定识别力、触觉或语义错误；N 增大时错误低分选择会造成饱和甚至退化。",
    transfer: "可把几何 verifier 与 force/contact verifier 组合，仅在候选后果互相冲突时启用额外 rollout。",
    experimentDetails: [{ title: "固定与门控 Best-of-N", setup: "RoboCasa、LIBERO Long、RoboTwin 2.0 的五个 policy–benchmark 组合。", comparisons: "单样本 WAM、固定 N=8 GeoBoN、门控 GeoBoN、随机/模型内部 selector 与 model-specific value head。", results: ["N=8 在五个组合全部改善；Cosmos Policy 66.3%→68.4%，X-WAM 80.8%→82.5%。", "gate 只触发 26.2% 决策点，平均保留 always-on gain 的 74.8%。", "随着 N 增加并非单调提升；false low-score selection 是候选变多后退化的主要诊断之一。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["论文披露五个设置、N=8、selector/gate 消融与计算触发比例。"], implementation: ["frozen depth foundation model；cross-view reprojection score；action–future gate；training-free external selector。"], missing: ["当前未确认官方代码；不同相机标定误差下的阈值稳定性未充分披露。"] },
    deepDive: { lead: "WAM 提供了一个动作候选和它声称会产生的未来，GeoBoN 用跨视角几何检查这两者是否值得信任。", sections: [{ title: "几何候选选择与门控", paragraphs: ["对每条 future rollout 的多个相机视角估计深度，把一个视角的 3D 点重投影到另一视角；像素/深度不一致越小，候选得分越高。", "gate 先检查单次输出中的动作幅度与预测图像变化是否匹配。只有内部不一致时才采样剩余 N−1 条，降低平均计算。"] }], equations: [{ name: "跨视角重投影分数", expression: "sgeo = − mean ‖p₂ − Π₂(T₂←₁ Π₁⁻¹(p₁,d₁))‖", explanation: "用相机几何把视角 1 的深度点投影到视角 2；重投影误差更小的 imagined future 获得更高分。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-24/2607.17454-overview.png", alt: "Gated GeoBoN 先判断 action future 一致性，再用跨视角几何选择 WAM rollout", caption: "Figure 1 · Gated GeoBoN test-time scaling 流程。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 8,
    title: "RoboInter1.5: A Holistic Intermediate Representation Suite for Embodied World Modeling and Robotic Manipulation",
    arxivId: "2607.18709",
    url: "https://arxiv.org/abs/2607.18709",
    institutions: ["RoboInter1.5 Collaboration"],
    signal: "用十余类 manipulation intermediate representations 同时监督 planner、VLA 与 world model",
    tags: ["Intermediate Representation", "VLA", "World Model"],
    classification: { research: "表征学习", training: "Pre-training", modalities: ["Mask / Segmentation", "Point Cloud / 3D"], data: "数据增强", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://lihaohn.github.io/RoboInter1.5/" }, { label: "GitHub", url: "https://github.com/lihaohn/RoboInter1.5" }, { label: "模型", url: "https://huggingface.co/datasets/lihaohn/RoboInter-Data" }],
    motivation: "机器人数据通常只提供图像、语言和动作，缺少 subtask、对象 grounding、affordance、contact、motion trace 等能连接推理、执行和未来预测的结构。",
    methodSummary: "构建 RoboInter-Data/VQA/CV，并训练 Planner、plan-then-execute VLA 与 intermediate-conditioned world model；同一中间表征既约束动作，也作为 future generation 的控制信号。",
    architecture: "Planner 生成结构化 CoT/中间表征；VLA 比较 implicit conditioning、显式 CoT-action joint generation 和 modular planner→executor；World model 以 action 或 intermediate representation 控制 future video。",
    optimization: "预训练与后训练组合：VLM 在 embodied VQA 上学习空间/时间 reasoning，VLA 在机器人轨迹上做 action/CoT 联合训练，world model 以 LoRA 或 full fine-tuning 比较。",
    data: "超过 230K episodes、571 scenes、6 种机械臂、15 类技能；含 61M object-grounding frames、70M motion traces、190K affordance/placement、760K language，以及 DROID、RH20T、OXE 等。",
    experiments: "Franka 四任务中 IC-E2E 为 ID 77.3%/OOD 58.3%，Vanilla 为 65.0%/38.3%；EC-E2E 的 OOD 为 60.0%，ID→OOD 下降 8.3% 而 IC-E2E 为 19.0%。",
    novelty: "相对只给 subtask 文本，它把 grounding、轨迹、affordance、接触和时空 CoT 统一为双向接口，并同时用于 VLA 与 world model。",
    strengths: "数据、标注工具、模型、VQA、真机 ID/OOD 和 world-model 控制均形成可公开使用的套件。",
    limitations: "多种表征与数据源同时变化，难以分离单类标注的边际贡献；EC-E2E 联合 CoT 在 ID 上出现 modality interference。",
    transfer: "可优先挑选与目标问题相关的中间监督，例如 contact point、motion trace 或 subtask，而不必一次使用全部标签。",
    experimentDetails: [{ title: "Franka ID/OOD 与 world-model conditioning", setup: "Franka Research-3 四任务，ID/OOD 各 15 次；另评测 1.3B/14B world model 的 action/intermediate conditioning。", comparisons: "OpenVLA、Pi-0、Vanilla、Planner 初始化 IC-E2E、CoT-action 联合 EC-E2E；world model action-only 与 Inter control。", results: ["IC-E2E：ID 77.3%、OOD 58.3%；Vanilla：65.0%、38.3%。", "EC-E2E OOD 为 60.0%，ID→OOD 仅下降 8.3%，但 ID 为 68.3%，低于 IC-E2E 的 77.3%。", "14B LoRA world model 用 intermediate control 时 PSNR 21.05、LPIPS 0.102，优于 action-only 对照。"] }],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["代码、数据与项目页链接已在论文公开。"], implementation: ["230K+ episodes；10+ intermediate representations；Planner/IC-E2E/EC-E2E/Modular VLA；1.3B 与 14B world models；LoRA/full FT。"], missing: ["完整 230K 数据的下载与全部训练 checkpoint 需按发布页逐项确认。"] },
    deepDive: { lead: "RoboInter1.5 把中间表征定义为双向接口：从视频抽取结构，也用结构控制动作和未来生成。", sections: [{ title: "Planner、Executor 与 World Model", paragraphs: ["Planner 在 embodied VQA 上学习对象/夹爪 grounding、spatial/temporal relation 和 subtask。IC-E2E 只用 Planner 权重初始化动作模型；EC-E2E 以 1:1 混合标注数据与真机数据，同时生成 CoT 和动作。", "RoboInter-World 用同一中间结构控制未来视频。相对 action-only conditioning，contact、trace 和 grounding 提供更稠密的空间约束。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-24/2607.18709-overview.png", alt: "RoboInter1.5 的标注数据、VQA、VLA planner executor 与 world model 套件", caption: "Figure 1 · RoboInter1.5 manipulation intermediate representation suite。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 9,
    title: "Agentic Real2Sim: Physics-based World Modeling with Vision-Language Agents",
    arxivId: "2607.19190",
    url: "https://arxiv.org/abs/2607.19190",
    institutions: ["University of British Columbia", "Johns Hopkins University", "National University of Singapore", "Columbia University", "University of California, Los Angeles", "Style3D"],
    signal: "用多 VLM agents 把真实交互视频转换为可运行、带物理参数的 episodic digital twin",
    tags: ["Real2Sim", "VLM Agents", "Physics Simulation"],
    classification: { research: "WM", training: "Test-time Adaptation", modalities: ["Point Cloud / 3D", "Mask / Segmentation"], data: "合成 / 仿真数据", platforms: ["机械臂", "Humanoid"], deployment: "Real2Sim" },
    resources: [{ label: "项目页", url: "https://agentic-real2sim.github.io/" }],
    motivation: "交互视频转仿真不仅要重建外观，还要识别对象状态、物理参数、机器人、相机和轨迹；现有流程依赖大量手工清 mesh 与坐标对齐。",
    methodSummary: "Visual、Prior、Scene 与 Grasp agents 分工解析 episode、检索/生成资产、估计物理参数、装配场景并验证重放；失败反馈驱动 agent 修正配置。",
    architecture: "VLM 负责工具选择与结构化决策，几何/分割/重建模型作为 tools，最终输出带机器人、对象、相机、关节状态和物理属性的可执行 simulation episode。",
    optimization: "无需训练统一模型，属于 agentic inference workflow；支持多种闭源和 open-weight VLM backend。",
    data: "DROID-100 刚体操作 episodes，并补充可变形物体与 humanoid motion 的跨域定性转换。",
    experiments: "DROID-100 上 Gemma 4 31B 为 48 成功、8 部分、44 失败，单 episode 平均成本 2.62 美元；四种 backend 成功数为 48/45/43/37，open model 成本可低至 GPT-5.4 的约 1/31.4。",
    novelty: "相对单体 Real2Sim pipeline，它把视觉、先验、场景与抓取推理拆为可调用工具的 agents，并把整个交互 episode 而非静态资产作为输出。",
    strengths: "100 个真实机器人 episodes、多个 VLM backend、成本与失败统计使可扩展性更可判断。",
    limitations: "刚体 DROID 有定量结果，可变形与 humanoid 主要是定性；48% 完整成功说明仍需人工复核。",
    transfer: "可用于把失败真机 episode 自动转成仿真回放候选，但应保留物理验证和人工审核门槛。",
    experimentDetails: [{ title: "DROID-100 转换与多 VLM 成本", setup: "100 个 DROID 交互 episode，记录完整成功、部分成功、失败、运行成本；另展示 deformable 与 humanoid。", comparisons: "四种 VLM backend，包括 frontier API 与 open-weight Gemma 4 31B。", results: ["Gemma 4 31B：48 完整成功、8 部分成功、44 失败，平均成本 2.62 美元/episode。", "四个 backend 的完整成功数为 48、45、43、37，模型差异没有消除流程本身的失败。", "open-weight backend 的推理成本约为 GPT-5.4 的 1/31.4；可变形和 humanoid 尚无同规模定量成功率。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页公开；论文给出 agent 分工、DROID-100 协议、backend 与成本表。"], implementation: ["Visual/Prior/Scene/Grasp agents；VLM tool calls；asset retrieval/reconstruction；physics scene assembly；episode replay validation。"], missing: ["完整 workflow 代码、全部 DROID 转换产物和人工修复步骤未确认开放。"] },
    deepDive: { lead: "Agentic Real2Sim 把数字孪生构建表示为多轮工具调用：VLM 决定下一步，专用视觉/几何工具执行可验证操作。", sections: [{ title: "多 agent 物理场景装配", paragraphs: ["Visual agent 从视频识别对象、状态和相机；Prior agent 查找资产与物理先验；Scene agent 统一坐标并装配仿真；Grasp agent 恢复末端—对象关系。", "输出必须能在物理引擎中重放 episode。验证失败会反馈缺失资产、姿态或参数，再由对应 agent 迭代，而不是只追求渲染相似。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-24/2607.19190-overview.png", alt: "Agentic Real2Sim 的多 VLM agent、工具调用、场景装配与物理验证流程", caption: "Figure 1 · Agentic Real2Sim episodic twin generation pipeline。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 10,
    title: "World Translation: Minimizing Sim-to-Real Gap with Backward Dynamics Extraction and Unpaired Domain Translation",
    arxivId: "2607.18154",
    url: "https://arxiv.org/abs/2607.18154",
    institutions: ["Zhejiang University", "LimX Dynamics"],
    signal: "从已发生的 transition 反向抽取隐藏动力学，再做仿真—真实 latent 的无配对翻译",
    tags: ["Sim2Real", "Backward Dynamics", "Domain Translation"],
    classification: { research: "WM", training: "Post-training", modalities: ["State / Proprioception"], data: "合成 / 仿真数据", platforms: ["Humanoid", "机械臂", "其他平台"], deployment: "Sim2Real" },
    motivation: "部分可观测下，相同当前观察可能因未知载荷、摩擦或突发接触产生不同下一状态；只从历史向前预测不一定能恢复这些隐藏因素。",
    methodSummary: "VAE 从已经观察到的 (oₜ,aₜ,oₜ₊₁) 反向编码隐藏动力学 feature，再用 CycleGAN 在无配对 sim/real latent 间翻译 domain style，同时保持 transition content。",
    architecture: "backward encoder/decoder 学习 transition latent；sim→real 与 real→sim generators、两个 discriminators 和 cycle consistency 构成 latent translator；部署时用翻译后的 real-style dynamics 修正 simulator rollout。",
    optimization: "先分别训练 transition VAE，再用 unpaired sim/real transitions 训练 latent CycleGAN；下游 policy 仍主要在 simulation 中训练。",
    data: "G1 humanoid、Go2 quadruped 与 R5 manipulator 的仿真/真实 transition，任务包含不平地形、未知 payload、外力与接触；Go2 有真机 policy transfer。",
    experiments: "多平台单步/多步动力学误差均低于 direct、RSSM 等基线；例如 Go2 payload 为 0.148 对 RSSM 0.298，R5 external force 为 0.401 对 direct 0.741/RSSM 0.515，并在真实 Go2 改善策略迁移。",
    novelty: "相对从观察历史估计 latent dynamics，它利用结果 transition 反向识别不可观测因素；相对 paired system identification，它只要求无配对的 sim/real transition 集合。",
    strengths: "humanoid、quadruped、manipulator 三平台，单步/多步、latent 分析、组件消融与 Go2 真机下游均有覆盖。",
    limitations: "需要先获得真实 transition，严格说更适合离线 Real2Sim/适配而非首次零数据部署；突发因素只能在发生后被识别。",
    transfer: "可用失败 rollout 的前后状态反向估计隐藏接触或载荷，再把该 latent 注入仿真做针对性再训练。",
    experimentDetails: [{ title: "多平台动力学与 Go2 真机迁移", setup: "G1、Go2、R5 上评测单步/多步预测、隐藏变量与 domain latent，并将策略部署到真实 Go2。", comparisons: "direct forward model、history-based RSSM、不同 latent translation/循环一致性消融。", results: ["G1 uneven terrain 误差 0.035，对 direct 0.119。", "Go2 payload 误差 0.148，对 RSSM 0.298；R5 external force 为 0.401，对 direct 0.741、RSSM 0.515。", "移除 backward extraction 或 cycle/domain components 都会降低跨域动力学预测；真实 Go2 下游结果支持误差改善可传递到 policy。"] }],
    reproducibilityDetails: { status: "信息不足", verifiedResources: ["论文披露 VAE/CycleGAN 组件、三平台任务、误差表和 Go2 真机设置。"], implementation: ["transition VAE；backward encoder E(o,a,o′)；unpaired latent CycleGAN；cycle consistency；simulator rollout correction。"], missing: ["代码、真实 transition 数据、完整超参和 Go2 每条件 rollout 次数未确认公开。"] },
    deepDive: { lead: "World Translation 先从‘已经发生了什么’反推出隐藏动力学，再把这种动力学内容从仿真 latent 翻译到真实 latent 风格。", sections: [{ title: "反向动力学抽取与无配对翻译", paragraphs: ["encoder 输入完整 transition 而不是只看历史，因此能从突然受力后的 oₜ₊₁ 识别未知外力或载荷。VAE decoder 用 oₜ、aₜ 与 latent 重建 oₜ₊₁。", "CycleGAN 在没有一一对应 transition 的情况下学习 sim/real latent 映射；adversarial loss 对齐域分布，cycle loss 保持同一 transition 的动力学内容。"] }], equations: [{ name: "transition latent", expression: "hₜ = E(oₜ, aₜ, oₜ₊₁),   ôₜ₊₁ = D(oₜ, aₜ, hₜ)", explanation: "hₜ 从已发生的状态转移中反向提取不可观测动力学信息。" }, { name: "无配对循环约束", expression: "ℒcycle = ‖Greal→sim(Gsim→real(hsim)) − hsim‖₁ + ‖Gsim→real(Greal→sim(hreal)) − hreal‖₁", explanation: "双向映射后应回到原 latent，以减少 domain translation 对动力学内容的破坏。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-24/2607.18154-overview.png", alt: "World Translation 的 backward dynamics extraction、latent domain translation 与下游部署", caption: "Figure 1 · World Translation framework。图片截取自 arXiv 原论文。" }],
  },
];

const selectedOrder20260724 = [
  "2607.20033",
  "2607.18236",
  "2607.18231",
  "2607.18840",
  "2607.17977",
  "2607.18016",
  "2607.18060",
  "2607.21582",
  "2607.21588",
  "2607.21049",
  "2607.20683",
  "2607.20653",
  "2607.18709",
  "2607.19190",
  "2607.21670",
  "2607.20293",
  "2607.19876",
];

const rerunPool20260724 = [
  ...priorPaperDaily20260724,
  ...paperDaily20260724RerunAdditions,
];

export const paperDaily20260724: Paper[] = selectedOrder20260724.map(
  (arxivId, index) => {
    const paper = rerunPool20260724.find((item) => item.arxivId === arxivId);
    if (!paper) throw new Error(`Missing 2026-07-24 paper ${arxivId}`);
    return { ...paper, rank: index + 1 };
  },
);
