import type { Paper, PaperEquation } from "./site-data";

type Entry = Omit<
  Paper,
  "rank" | "figures" | "optimization" | "experimentDetails" | "reproducibilityDetails" | "deepDive"
> & {
  figureFile: string;
  figureAlt: string;
  figureCaption: string;
  technique: string[];
  evaluation: string[];
  comparison: string;
  reproducibilityStatus: "资源较完整" | "部分可复现" | "信息不足";
  implementation: string[];
  missing: string[];
  equations?: PaperEquation[];
};

const makePaper = (entry: Entry, index: number): Paper => ({
  ...entry,
  rank: index + 1,
  optimization: entry.technique.join("；"),
  experimentDetails: [{
    title: "原文实验与消融",
    setup: entry.experiments,
    comparisons: entry.comparison,
    results: entry.evaluation,
  }],
  reproducibilityDetails: {
    status: entry.reproducibilityStatus,
    verifiedResources: entry.resources?.map((resource) => `${resource.label}: ${resource.url}`) ?? ["arXiv 论文正文"],
    implementation: entry.implementation,
    missing: entry.missing,
  },
  deepDive: {
    lead: entry.methodSummary ?? entry.signal,
    sections: [{ title: "方法与模型改进", paragraphs: entry.technique }],
    equations: entry.equations,
    experimentReading: entry.evaluation,
    reflections: [entry.transfer],
  },
  figures: [{
    src: `/report-assets/2026-08-24/${entry.figureFile}`,
    alt: entry.figureAlt,
    caption: entry.figureCaption,
  }],
});

const entries: Entry[] = [
  {
    title: "Beyond Imitation: Self-Improving Robot Policies via Off-Policy Q-Planning",
    arxivId: "2608.21204",
    url: "https://arxiv.org/abs/2608.21204",
    institutions: ["Georgia Institute of Technology"],
    signal: "用一个可吸收成功与失败 rollout 的小型 Q 函数，为冻结的大型 BC 策略做动作选择和在线自改进。",
    tags: ["VLA", "Offline RL", "Q-Planning"],
    classification: { research: "VLA", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://varungiridhar.github.io/qplanning" }],
    motivation: "BC 策略只能模仿成功示范，部署失败无法直接变成训练信号；对数十亿参数策略做在线 RL 又昂贵且不稳定。",
    methodSummary: "冻结 BC policy，仅训练约 1B 参数的 off-policy Q；推理时从 BC 采样多个 action chunk，以 Q 值 softmax 加权后执行单个平均动作块。新 rollout 无论成败都进入 Q 的 replay buffer。",
    architecture: "BC policy 负责生成候选动作，独立 Q 网络复用视觉/语言编码并对候选 action chunk 估值；两者不共享优化器，在线阶段只更新 Q。",
    data: "离线阶段使用原 BC 成功示范；在线每轮每任务采集 100 个 episode（真机为 20 个），仅记录任务成败，无需新的人工动作标注。",
    experiments: "覆盖 LIBERO、双臂 RoboTwin 和两个接触型双臂真机任务；真实系统从 100 条基础示范开始，连续五轮自主采集与 Q-only 更新。",
    novelty: "LIBERO-10 从 93% 提至 99%，RoboTwin 从 83.8% 提至 91.4%；真机叠杯 40%→90%、插钱包 25%→80%，而只对成功 rollout 做 SFT 停在 55%/30%。",
    strengths: "失败样本真正进入更新，且保持大型 BC 主干冻结；同时对照 Best-of-N、SFT、IBRL、DSRL、DAWR，并报告规划延迟。",
    limitations: "需要可靠的二元成功判定和额外在线交互；Q 网络仍约十亿参数，候选分布受冻结 BC 的覆盖上限约束。",
    transfer: "适合已有强 BC/VLA、但不希望在线改动主干的项目；可先把失败回放用于 Q 估值，再决定是否需要策略级 RL。",
    technique: [
      "对 N 个 BC action chunks 计算 Q 值并做温度 softmax，执行加权平均而非反复 MPPI；视觉和语言编码每个规划步只计算一次。",
      "Q 使用 success/failure rollout 做 off-policy 更新；每轮部署后只训练 Q 200 个梯度步，BC 权重始终不变。",
      "同一 Q 下，单步加权与时序平滑 MPPI 在 LIBERO-10 同为 93%，但前者规划快 1.7 倍、超参更少。",
    ],
    equations: [{ name: "Q 加权动作选择", expression: "a = Σᵢ softmax(Q(o, aᵢ) / τ) · aᵢ", explanation: "候选动作块来自冻结 BC；温度 τ 控制更接近择优还是平滑平均。" }],
    evaluation: [
      "十轮自改进后，所有仿真套件均提升；近饱和的 LIBERO-Object/Goal 还把成功轨迹长度从 139/110 步降到 120/99 步。",
      "真机每轮 20 个在线 episode、共五轮；Q-Planning 利用失败稳定提升，而成功样本 SFT 在两个任务都较早停滞。",
      "LIBERO 的候选源和延迟消融表明增益并非来自增加采样本身，而来自 value-guided 组合与后续 Q 更新。",
    ],
    comparison: "冻结 BC、Best-of-N、MPPI、成功样本 SFT、IBRL、DSRL、DAWR，以及离线 Q-Planning 与多轮在线更新。",
    reproducibilityStatus: "部分可复现",
    implementation: ["论文给出 action chunk、候选数/规划预算、每轮 episode 数、Q 更新步数和 L40S 延迟测量协议。"],
    missing: ["项目页未标示公开代码或权重；真机硬件搭建与成功检测器需要自行复现。"],
    figureFile: "2608.21204-fig1.png",
    figureAlt: "Q-Planning 用冻结 BC 生成候选并以 Q 函数筛选和迭代更新",
    figureCaption: "Figure 1 · 冻结 BC、Q 加权在线规划，以及用成功/失败 rollout 单独更新 Q 的自改进闭环。来源：arXiv 原图。",
  },
  {
    title: "ViTacPhys: Physical Property-Aware Grasping from Human Visual-Tactile Demonstrations",
    arxivId: "2608.21355",
    url: "https://arxiv.org/abs/2608.21355",
    institutions: ["匿名评审稿（机构未公开）"],
    signal: "从人类视觉—触觉交互估计质量、刚度和摩擦，再把显式物性送给灵巧手策略调整抓力。",
    tags: ["Visuotactile", "Physical Properties", "Dexterous Grasping"],
    classification: { research: "表征学习", training: "Pre-training", modalities: ["Tactile"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "灵巧手"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://vitacphys.github.io/ViTacPhys/" }],
    motivation: "视觉相近的物体可能在重量、软硬和摩擦上完全不同，纯视觉策略容易用错握力；直接为机器人采集大规模触觉物性数据又很贵。",
    methodSummary: "时序视觉/触觉内容流与相邻帧 flow 分别编码，通过 cross-attention 融合，并加入接触前由 VLM 蒸馏的语义先验；输出质量与摩擦有序类别及连续刚度。",
    architecture: "人类数据预训练的 ViTacPhys 经少量遥操作、robot-style 视频增强和 matched-action 人类数据迁移；部署时 30 帧队列做累计投票，物性 token 输入 ACT-style 抓取策略。",
    data: "60 个刚性/柔性物体、1,800 条一秒人类抓握序列（30 Hz）；机器人端 50 个物体各 10 条遥操作示范，并构造 ID/OOD 物体对。",
    experiments: "先评估三种物性预测，再做 human-to-robot 消融和 7-DoF 机械臂+6-DoF 灵巧手自适应抓取；同时比较 ACT 与 ViTacFormer 的成功率和力曲线。",
    novelty: "held-out 物体质量/摩擦准确率 87.5%/97.5%、刚度 MAPE 9.08%；物性条件策略在 ID/OOD 上总抓取成功率为 95.0%/83.4%。",
    strengths: "把物性估计与真实闭环抓取联系起来，模态、flow、VLM prior、loss 和跨域数据组成均有消融；还报告过大夹力而非只算能否提起。",
    limitations: "匿名稿暂未公开机构、代码和数据；one-shot 设置明显下降，且物性类别边界与传感器标定可能限制跨硬件复用。",
    transfer: "可把质量/刚度/摩擦作为显式中间状态接入 VLA 或 force policy，尤其适合外观相似但接触参数差异大的物体。",
    technique: [
      "15 个视觉—触觉时刻及 14 个相邻 flow 构成时序窗口；GRU/Transformer 编码后以双向 cross-attention 融合，并用 GradNorm 平衡三任务。",
      "质量和摩擦使用有序回归，刚度在 log 空间回归；接触前 RGB 只用于生成一个离线 VLM semantic prior，不能替代实际交互信号。",
      "迁移阶段比较 scratch、human initialization、teleoperation、视频增强和 matched-action human data 的组合；ONNX 部署在 Jetson Orin 上两网络各约 9/10 ms。",
    ],
    evaluation: [
      "去掉视觉或触觉内容流，质量准确率最多下降 21.5 个百分点；仅用文本先验质量准确率 54.2%，说明主信号仍来自交互。",
      "把有序质量分类换成交叉熵，held-out 质量准确率由 87.5% 降到 63.5%；但摩擦并未从有序目标获益，论文如实报告该反例。",
      "OOD 迁移中 Tele.+Aug.+Human 的质量/摩擦准确率达到 78.0%/82.7%；最终抓取还按 clean、over-force 和失败拆分。",
    ],
    comparison: "ACT、ViTacFormer，视觉/触觉/flow/VLM-prior 模态消融，GradNorm/DWA/手工 loss 权重，以及多种 human-to-robot 数据组合。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页披露数据规模、采集协议、模型结构、ONNX/Jetson 时延和主要表格。"],
    missing: ["代码与数据在项目页标为 Coming Soon；作者机构、完整硬件标定与训练权重尚未公开。"],
    figureFile: "2608.21355-fig5.png",
    figureAlt: "ViTacPhys 视觉触觉物性预测和人到机器人迁移流程",
    figureCaption: "Figure 4 · 时序视觉触觉融合、VLM 先验、人到机器人迁移与在线累计投票。来源：arXiv 原图。",
  },
  {
    title: "VT-MUSE: Multimodal Unified Sequential Visuotactile Representation Learning for Manipulation",
    arxivId: "2608.21290",
    url: "https://arxiv.org/abs/2608.21290",
    institutions: ["Xense Robotics", "Shanghai Jiao Tong University", "Beijing University of Posts and Telecommunications"],
    signal: "先对齐视觉与触觉的时序表征，再用预测未来视觉和触觉形变的任务把表示接入控制。",
    tags: ["Visuotactile", "Representation Learning", "Contact-rich"],
    classification: { research: "表征学习", training: "Pre-training", modalities: ["Tactile"], platforms: ["机械臂", "夹爪"] },
    motivation: "当前视觉触觉策略多在单帧上直接拼接模态，难以捕捉接触建立、形变和滑移的先后关系。",
    methodSummary: "Stage I 做跨模态对齐、时间一致性与 masked-view consistency；Stage II 冻结编码器，用条件变分 latent 同时重建遮挡视觉和预测 tactile depth flow。",
    architecture: "交错的视觉/触觉 token 进入 temporal memory transformer，触觉 query 检索相关历史；冻结表示经 gated cross-attention 注入 ACT-style policy 的中间层。",
    data: "UniVTAC 四任务共 2,000 条表征轨迹，策略各用 50 条；真机 Flexiv Rizon 4s + XenseGripper 四任务各 50 条，共 200 条。",
    experiments: "仿真四任务每方法每任务 100 个相同初始条件；真机插管、擦板、拉抽屉、按烤面包机每方法每任务 20 次。",
    novelty: "UniVTAC 平均 55.25%，强完整基线 ACT+UniVTAC 为 39.00%；去掉 tactile-flow、视觉重建或整个 Stage II 分别降到 38.75%、37.00%、27.25%。",
    strengths: "把表征目标与 rollout 成功率直接联系，覆盖视触觉模块、时序 loss、窗口长度和真实接触任务。",
    limitations: "真机基线只使用同任务数据，未与更大的预训练 VLA 正面对比；每项 20 次且只在一种夹爪/触觉硬件评估。",
    transfer: "触觉辅助目标不必重建原始传感图，可优先预测 depth-flow、接触阶段或滑移等与控制更相关的变化量。",
    technique: [
      "Stage I 从预训练视觉/触觉 ViT 出发，用 cross-modal alignment、temporal coherence 和 mask consistency 调整局部表示。",
      "Stage II 遮住最新视觉 token，让 tactile query 从历史检索信息；共享 latent 同时解码 RGB 和下一段 tactile depth flow。",
      "下游 policy 冻结 VT-MUSE encoder，只通过中层 gated cross-attention 读取 memory tokens，减少任务训练参数。",
    ],
    evaluation: [
      "仿真平均 55.25%，在 FTP-π0.5 报告的三个任务上平均 63.33%，高 12 个百分点。",
      "去掉 temporal contrastive loss 降至 42.25%；窗口长度 L=5 最好，L=4/L=6 分别低 15.25/14.00 点。",
      "论文还指出视觉重建更清晰不等于控制更好：visual-only 目标成功率只有 38.75%。",
    ],
    comparison: "ACT、ACT+UniVTAC、FTP-π0.5、UniVTAC 表征，以及预测头、时序损失、窗口长度与真机模态基线。",
    reproducibilityStatus: "部分可复现",
    implementation: ["给出两阶段训练时长、GPU、每任务示范数、窗口和真机 20 次协议。"],
    missing: ["未给出公开代码/权重链接；真机传感器标定与成功判定细节仍依赖附录描述。"],
    figureFile: "2608.21290-fig2.png",
    figureAlt: "VT-MUSE 两阶段视觉触觉表征学习与策略融合架构",
    figureCaption: "Figure 2 · 跨模态时序预训练、视觉/触觉预测目标和 gated policy conditioning。来源：arXiv 原图。",
  },
  {
    title: "ForeTime-VLA: Causal Future-Token Distillation from a World Action Model for Conveyor-Belt Manipulation",
    arxivId: "2608.20735",
    url: "https://arxiv.org/abs/2608.20735",
    institutions: ["Tsinghua University", "Shanghai AI Laboratory", "Harbin Institute of Technology", "DEEP Robotics"],
    signal: "把 WAM 的未来信息蒸馏成可由历史观测预测的紧凑 token，部署时不运行视频世界模型。",
    tags: ["VLA", "WAM Distillation", "Dynamic Manipulation"],
    classification: { research: "VLA", training: "Post-training", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "运动目标需要提前判断接触位置与时刻，但在控制环中生成未来视频成本过高。",
    methodSummary: "离线 Fast-WAM teacher 把当前与未来视频压成 whitened 64-D action-equivalent target；因果 student 从八帧历史预测 future code、阶段和到转移时间。",
    architecture: "四个 future tokens 与一个 phase token 条件化 π0.5 的 VLM prefix，future code 与 transition horizon 同时进入 action expert；测试时移除 WAM 和未来帧。",
    data: "去重后的传送带机器人数据；离线比较在每个 split 抽取 768 个完全匹配窗口，真机覆盖静止、慢速和三档速度压力测试。",
    experiments: "离线看动作 MAE/L2、bootstrap CI 和延迟；真机主表各 90 次，三档速度各 30 次，与 π0.5、StarVLA 等同平台策略比较。",
    novelty: "测试 MAE/L2 降 2.63%/3.02%，延迟仅增 2.46%–2.93%；三档速度 44/90 对 π0.5 的 23/90，快速档 11/30 对 2/30。",
    strengths: "未来监督、阶段、时间、关系几何均有独立目标；离线使用 paired bootstrap，真机试验数量和速度分层清楚。",
    limitations: "只验证一个传送带本体和抓取任务，未来 teacher 固定；离线误差改善较小，不能直接外推到长时操作。",
    transfer: "若部署世界模型太慢，可把其 future latent 蒸馏为历史可预测 token，同时保留原 action-flow 训练目标。",
    technique: [
      "teacher 用冻结 video VAE 对当前/未来片段编码，再投影、白化为 64-D target，避免学生直接重建像素。",
      "student 只看八帧因果历史，预测 future code、manipulation phase 与 time-to-transition，并分别注入 VLM 和 action expert。",
      "总损失包含原 flow-matching action loss、cosine future alignment、关系几何、阶段、转移时间和辅助 action reconstruction。",
    ],
    evaluation: [
      "静止抓取 73/90（81.1%），慢速 53/90（58.9%），分别领先次强参考 12.2 和 22.2 个百分点。",
      "速度压力测试慢/中/快为 19/14/11 次成功，π0.5 为 13/8/2；速度越高优势越大。",
      "768 matched windows 上 MAE 相对改善的 95% CI 为 0.82%–4.48%，避免只报单点小增益。",
    ],
    comparison: "π0.5、StarVLA、其他传送带策略，以及 future/phase/transition 多目标和输入路径消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文给出 64-D target、八帧历史、768 matched windows、bootstrap 次数和各速度真机试验数。"],
    missing: ["未确认代码、数据或 checkpoint 公开；目前只给出单一传送带系统的硬件结果。"],
    figureFile: "2608.20735-fig1.png",
    figureAlt: "ForeTime-VLA 从离线 WAM teacher 蒸馏未来 token 的架构",
    figureCaption: "Figure 1 · 离线 future teacher、因果 student 双路径 conditioning 与多目标训练。来源：arXiv 原图。",
  },
  {
    title: "CounterAlign: Counterfactual Supervision for Vision-Language-Action Models",
    arxivId: "2608.21740",
    url: "https://arxiv.org/abs/2608.21740",
    institutions: ["作者机构未在 arXiv HTML 正文标注"],
    signal: "把同一示范改写成指令—动作不匹配的反事实样本，再用离线 RL 教 VLA 区分正确与错误行为。",
    tags: ["VLA", "Counterfactual", "Offline RL"],
    classification: { research: "VLA", training: "RL", data: "数据增强", platforms: ["机械臂", "夹爪"] },
    motivation: "BC 只告诉策略专家做了什么，没有告诉它同一场景下哪些动作与指令不匹配，容易在物体位置和措辞变化时失效。",
    methodSummary: "从正示范生成 instruction-relabel 和 action-relabel 样本，训练 observation–instruction–action discriminator；再把判别分数作为 reward，用 IQL critic 与 advantage-weighted flow matching 更新 VLA。",
    architecture: "判别器分别读取原样本、未标注反事实和负样本；policy 仍是 flow-based VLA，离线 RL 阶段交替更新 discriminator、critic 和 action expert。",
    data: "无需额外机器人采集；真机 TX-G2 四任务每项约 100–500 条示范，每任务拆成 4–6 个 primitive，并由重标注构造反事实。",
    experiments: "LIBERO/CALVIN 仿真和四个 TX-G2 真机长任务；真机每任务 10 次，8 次小物体位姿扰动、2 次明显超出训练分布。",
    novelty: "真机四任务平均 primitive success 为 0.20/0.53/0.93/0.85，整体优于 π0.5 与 xVLA；收益来自反事实 reward 与 offline policy improvement 的组合。",
    strengths: "不额外采失败轨迹即可从每条示范产生负监督；对反事实来源、reward、critic 和数据混合有消融，并测试 OOD 位姿扰动。",
    limitations: "判别器可能学习重标注伪影；训练需要 5–8 张 H200 级显存，真机每项只有 10 次且机构/公开资源信息不完整。",
    transfer: "对于多指令、多物体数据，可先构造保持观测但交换指令/动作的难负样本，再检查 discriminator 是否真的关注任务一致性。",
    technique: [
      "instruction-relabel 保持轨迹、替换任务语义；action-relabel 保持指令、扰动或替换动作，三类样本形成高/中/低 reward 排序。",
      "IQL critic 在离线数据上估值，policy 以 advantage-weighted flow-matching 更新，避免在线探索。",
      "训练交替刷新 discriminator 与 VLA；LIBERO 使用 15k policy steps、batch 256，额外网络显著增加显存但单步时间接近 BC。",
    ],
    evaluation: [
      "真机每项 10 次并显式包含 2 次 OOD 大扰动，报告 primitive-level mean success，而非把部分完成记作整段成功。",
      "完整方法在四任务分别达到 0.20、0.53、0.93、0.85；xVLA 对应 0.00、0.08、0.05、0.05。",
      "论文的仿真消融显示，只有负样本或只有 critic 都不足以稳定复现完整增益。",
    ],
    comparison: "π0.5、xVLA、BC、不同负样本重标注方式，以及移除 discriminator/critic/反事实数据的消融。",
    reproducibilityStatus: "信息不足",
    implementation: ["正文给出 LIBERO 训练步数、batch、GPU需求、真机任务数据量与扰动协议。"],
    missing: ["作者机构、代码、模型权重和完整反事实生成实现未在可访问页面公开。"],
    figureFile: "2608.21740-fig1.png",
    figureAlt: "CounterAlign 反事实重标注、判别奖励和离线 RL 流程",
    figureCaption: "Figure 1 · 正样本、指令/动作反事实及其 reward 排序，随后用于 VLA offline RL。来源：arXiv 原图。",
  },
  {
    title: "Robust Bimanual Vision-Language-Action Models via Embarrassingly Simple Modality Masking",
    arxivId: "2608.22419",
    url: "https://arxiv.org/abs/2608.22419",
    institutions: ["Shanghai Innovation Institute", "Wuhan University", "Zhejiang University", "Shanghai Jiao Tong University", "University of Science and Technology of China", "City University of Hong Kong", "Southeast University"],
    signal: "只在训练时随机遮蔽多视角、文本和部分 action queries，迫使双臂 VLA 减少模态捷径与 query 共适应。",
    tags: ["Bimanual VLA", "Modality Masking", "Robustness"],
    classification: { research: "VLA", training: "Post-training", data: "数据增强", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://m3vla.github.io" }],
    motivation: "多视角双臂策略常把注意力集中在少量视角或冗余 query 上，训练分布内有效，换视角、遮挡或杂乱背景后迅速退化。",
    methodSummary: "M3 在训练期对 ego/双腕视觉、语言 token 和随机 action-query 子集做结构化 masking；推理恢复全部模态，不增加参数与延迟。",
    architecture: "以 VLA-Adapter/RDT-style query action expert 为主干；对可见 token 数量做 query rescaling，避免不同 mask 比例改变激活尺度。",
    data: "RoboTwin 2.0 十项双臂任务与三项真实长时任务；同 baseline 使用相同示范、训练超参和 action chunk 25。",
    experiments: "比较 clean、视角/背景随机化和遮挡；真机三任务同时评估正常场景与 OOD clutter，并对每类 mask 和 rescaling 做消融。",
    novelty: "RoboTwin clean 相对 Adapter 提升 21.7 点、Clean-to-Random 提升 11.4 点；真机平均完整任务成功率在 clean/OOD clutter 提升 25.0/48.6 点。",
    strengths: "训练期改动极小、部署零开销；同时在仿真与真机验证 clean 和 OOD，并保持 backbone/data 预算一致。",
    limitations: "收益依赖多视角和 query-based 架构；论文没有证明随机 mask 学到的 query 专门化在不同本体仍成立。",
    transfer: "可优先把 masking 当作多视角 VLA 的正则化基线，分别测视角缺失、指令扰动和 action-query redundancy。",
    technique: [
      "视觉按整组视角 token 遮蔽，文本保持任务可解性，action queries 只随机删子集而不全删。",
      "query rescaling 按可见 token 比例校正 attention 输入，减少 mask pattern 改变表示幅值造成的训练偏差。",
      "M3 objective 与原 action loss 联合，不引入新 encoder、辅助标签或测试时分支。",
    ],
    evaluation: [
      "十项 RoboTwin 的 clean 和随机化设置均提升，且 VLA-Adapter 与 OpenVLA-OFT 两种 backbone 上方向一致。",
      "三项双臂真机把完整任务成功率与中间阶段分开统计；OOD clutter 的平均增益 48.6 点高于 clean 的 25.0 点。",
      "单一视角 mask、文本 mask、query mask 与 rescaling 的消融显示完整组合最稳，不是单纯更强 dropout。",
    ],
    comparison: "VLA-Adapter、OpenVLA-OFT、RDT-style 主干，以及逐项移除视觉/文本/query masking 和 query rescaling。",
    reproducibilityStatus: "部分可复现",
    implementation: ["论文给出 batch、4×H100、action chunk=25、相同 baseline 超参和主要 mask 设计。"],
    missing: ["项目页的代码/权重发布状态未明确；真机每项具体试验次数需结合附录表格复现。"],
    figureFile: "2608.22419-fig3.png",
    figureAlt: "M3 对多视角文本和动作 query 做训练期遮蔽",
    figureCaption: "Figure 3 · 训练期多模态与 action-query masking；推理时使用完整 token，不增加部署分支。来源：arXiv 原图。",
  },
  {
    title: "LD4WAM: Learning Latent Dynamics from Human Videos for World Action Models",
    arxivId: "2608.22403",
    url: "https://arxiv.org/abs/2608.22403",
    institutions: ["作者机构未在 arXiv HTML 正文标注"],
    signal: "以 motion-aligned latent dynamics 把人类视频中的运动先验桥接到机器人 WAM，而非只做像素预测。",
    tags: ["WAM", "Human Video", "Latent Dynamics"],
    classification: { research: "WAM", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "灵巧手", "夹爪"], deployment: "跨本体迁移" },
    motivation: "人类视频便宜但无机器人 action；直接生成未来像素不够 actionable，动作重定向又有明显本体视觉差距。",
    methodSummary: "Latent Dynamics Model 以语义重建和真实末端运动对齐学习 soft-VQ dynamics；WAM 通过 learnable queries 把生成未来中的 latent dynamics 蒸馏给 action expert。",
    architecture: "video、latent-dynamics、action 三个 expert 共享 self-attention 的 Mixture-of-Transformers；text 通过 cross-attention 条件化三路，action expert 另接 state。",
    data: "统一的 5,000+ 小时人类与机器人视频；真机三任务各 50 条示范，覆盖双臂夹爪与灵巧手，另在 RoboTwin 做规模化评估。",
    experiments: "RoboTwin 仿真、三项真实任务的已见/未见物体与背景；真机每任务每 setting 30 次，并做 pretraining、motion alignment、latent query 消融。",
    novelty: "真实任务综合平均 63.7%，π0.5 为 62.6%；优势主要在未见背景/物体而非简单 ID，pretraining 对背景泛化贡献约 23.3 点。",
    strengths: "5,000 小时预训练、三阶段训练和跨末端执行器真机闭环；明确区分 pixel generation 与 actionable latent 的作用。",
    limitations: "训练需 64 张 H20，成本很高；机构与公开资源状态不清晰，ID 平均并未大幅超过强 VLA baseline。",
    transfer: "human-video WAM 可加入少量真实 ΔEE 对齐，把视觉动态 latent 变成 action expert 可读的桥，而不必全量重定向人类动作。",
    technique: [
      "LDM 对随机时间间隔的帧用冻结 DINOv3 编码，经时空 Transformer 和 soft-VQ，联合语义重建与 camera-frame ΔEE 对齐。",
      "MoT 三 expert 共享 attention；learnable dynamics queries 从 video expert 读取未来，再把信息传给 action expert。",
      "Stage I 在全视频训练 video/LDM，Stage II 用机器人数据对齐三路，Stage III 在任务数据后训练；T5、VAE 和 LDM 按阶段冻结。",
    ],
    evaluation: [
      "RoboTwin 平均成功率 93.4%；真实 Tidy Desk、Fold Shirt、Handover Mug 每 setting 30 个 rollout。",
      "真实综合 63.7% 与 π0.5 的 62.6% 接近，但 unseen object/background 的分项更强，说明主要收益在泛化。",
      "消融显示仅做 semantic reconstruction 不够，真实 motion alignment 和 latent queries 都是动作收益的必要环节。",
    ],
    comparison: "π0.5、LingBot 等 VLA/WAM，以及移除人类预训练、motion alignment、latent dynamics query 的消融。",
    reproducibilityStatus: "信息不足",
    implementation: ["正文披露 AdamW、峰值学习率 1e-4、5% warmup、bf16、ZeRO-2、64×H20 和三阶段设置。"],
    missing: ["作者机构、训练代码、5,000 小时数据清单和 checkpoint 未在可访问页面明确公开。"],
    figureFile: "2608.22403-fig3.png",
    figureAlt: "LD4WAM 的 latent dynamics model 与 world dynamics action model",
    figureCaption: "Figure 3 · motion-aligned LDM、三 expert 共享 attention，以及 pretrain/align/post-train 三阶段。来源：arXiv 原图。",
  },
  {
    title: "The Imitator Game: Benchmarking Robot Imitative Ability Beyond Action Prediction",
    arxivId: "2608.22301",
    url: "https://arxiv.org/abs/2608.22301",
    institutions: ["The University of Hong Kong", "TranscEngram", "Fudan University", "Zhejiang University"],
    signal: "用 L0–L3 场景差异把动作复刻与意图模仿分开，并提供成对人类—机器人数据和盲评平台。",
    tags: ["Human Video", "Benchmark", "Imitation"],
    classification: { research: "其他", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://imitator-game.github.io" }],
    motivation: "从人类视频学机器人常被近似成轨迹复刻，现有 benchmark 很难判断模型是否理解了演示意图，尤其在可用物体发生替换时。",
    methodSummary: "L0 同物体同布局，L1 换布局，L2 换同类物体，L3 需要用不同 affordance 完成相同意图；Imitator Arena 盲评完成度、模仿质量和 A/B 偏好。",
    architecture: "不是单一模型，而是统一三类接口：caption-conditioned VLA、video-skill 检索和 frozen video encoder + visuomotor action head。",
    data: "IG-10K 含 20,000+ paired episodes、50+ base tasks、200+ variants、六领域；其中 11.7K 真实人机对、10K 仿真对，附多视角、深度、mask、MANO 与语言。",
    experiments: "九种模型、15 个训练变体，在仿真和双臂 Realman 上比较 seen、zero-shot、10-pair few-shot；Arena 汇总 15k 仿真和 5k 真机 A/B 屏。",
    novelty: "所有模型 unseen zero-shot 都低于 13%；真实 P+FT 下 L0–L2 平均约 0.4，L3 降到 0.29，定位 functional substitution 为主要瓶颈。",
    strengths: "成对数据、层级难度、自动与人评双通道、仿真/真机独立域都较完整；给出大量训练规模与表示选择对照。",
    limitations: "场景型任务中含 hospital/laboratory，但论文价值在 benchmark 设计而非这些应用系统；每个 task-level 当前只有一种替换模式，人评每屏单标注者。",
    transfer: "评估 human-video policy 时应拆分布局泛化、同类物体替换与跨 affordance 替代，避免把在相同场景复刻动作误当成意图理解。",
    technique: [
      "每个 human demonstration 对应 L0–L3 机器人场景；随着层级增加，可复制的轨迹细节减少，必须逐步转向任务语义。",
      "三类模型统一到 aₜ=π(V,oₜ) 接口，冻结各自 backbone，只在 IG-10K 训练 action head，以减少训练协议差异。",
      "Arena 只配对相同 domain/setting/task/level/episode 的匿名 rollout，随机左右顺序，分别收集 success、0–10 imitation score 和 pair preference。",
    ],
    evaluation: [
      "仿真 seen 最强 ACT/DINOv2 SR=0.81；真实 Arena 的 XSkill 在 seen/ZS/P+FT 为 0.63/0.29/0.49。",
      "从 15 到 45 个预训练任务，14/15 个仿真变体的 P+FT 提升；但直接 zero-shot 仍接近地板。",
      "L3 的不同 affordance 替代造成最清晰下降；项目同时发布 automated predicate 与盲评结果，避免用单一指标下结论。",
    ],
    comparison: "π0.5 等 VLA、XSkill/video-skill、DINOv2/SigLIP2/VideoMAE + ACT/DP/VQ-BeT，以及 15/30/45 任务规模。",
    reproducibilityStatus: "资源较完整",
    implementation: ["正文给出任务表、数据格式、传感器、30 Hz 控制、模型接口、试验桶和 Arena 聚合规则。"],
    missing: ["项目页的完整数据下载与训练代码发布状态需以作者后续版本为准；人评尚未报告显式标注者一致性。"],
    figureFile: "2608.22301-fig1.png",
    figureAlt: "Imitator Game 人类演示到机器人场景的任务设置与盲评平台",
    figureCaption: "Figure 1 · 人类 Demonstrator Scene、机器人 Imitator Scene 和匿名 A/B 评测平台。来源：arXiv 原图。",
  },
];

export const paperDaily20260824: Paper[] = entries.map(makePaper);
