import type { Paper } from "./site-data";

export const paperDaily20260803: Paper[] = [
  {
    rank: 1,
    title: "Cross-Embodiment Transfer via Behavior-Aligned Representations",
    arxivId: "2607.27549",
    url: "https://arxiv.org/abs/2607.27549",
    institutions: ["Stanford University", "Toyota Research Institute"],
    signal: "用跨本体稳定、又能预测动作的中间表征，把异构机器人数据转化为目标本体可利用的行为先验",
    tags: ["Cross-Embodiment", "Behavior-Aligned Representation", "VLA"],
    classification: { research: "表征学习", training: "BC", data: "跨本体数据", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://ajaysridhar.com/barx/" }],
    motivation: "不同机器人外观和运动学差异会让共享动作空间失效；仅混合异构示范通常不能稳定改善新本体策略。",
    methodSummary: "BARx 把目标框、语言运动描述和末端轨迹作为 behavior-aligned representations，与动作共同预测；这些表征跨本体更稳定，同时仍约束任务相关行为。",
    architecture: "MiniVLA 主干接收图像与语言，动作头之外增加表征预测头；目标框由 Grounding DINO 提供，末端轨迹由分割和检测得到，联合损失中辅助项权重设为 1。",
    optimization: "使用行为克隆联合优化动作与辅助表征；分别比较只用目标本体数据、直接混合跨本体数据及不同表征组合。",
    data: "RoboCasa-X 使用 IIWA、Kinova3、UR5e 作为源本体，每任务 900 或 3,000 条示范；Panda、Jaco 和 Panda-OG 每任务只有 50 条目标示范。真机 FR3 与 ViperX 两项任务各 50 条示范。",
    experiments: "仿真每个条件 100 次 rollout；真机每个本体-任务条件 10–30 次。跨本体数据直接加入只带来约 7% 的任务进度提升，联合表征后总体提升 28%。",
    novelty: "相对在原始视觉或动作空间直接对齐，BARx 显式选择兼具本体不变性与动作预测性的行为表征，并验证它们随源数据规模增大而更有价值。",
    experimentDetails: [
      { title: "跨本体仿真与消融", setup: "RoboCasa-X 四任务，三个源本体与三个低数据目标本体；每个评估条件 100 次 rollout。", comparisons: "相同 MiniVLA 下比较目标数据、直接加入跨本体动作数据，以及目标框、语言运动、末端轨迹和联合表征。", results: ["末端轨迹在多数组合中最稳定，联合表征在较大的 XP-3K 源数据上收益更明显。", "论文以三个 checkpoint 中最优者汇报仿真结果，这会带来选择偏差。"], evidenceNote: "结论支持表征辅助跨本体迁移，但仿真汇报采用 best-of-three checkpoint。" },
      { title: "FR3 与 ViperX 真机迁移", setup: "两个抓取放置任务，每个目标本体-任务 50 条示范，每格 10–30 次 rollout。", comparisons: "目标数据、直接混合仿真跨本体数据、以及联合 behavior-aligned representations。", results: ["直接加入跨本体数据的总体任务进度提升约 7%。", "联合表征后总体任务进度提升 28%；指标是阶段进度而非完整成功率。"], evidenceNote: "真机场景只覆盖一个厨房和较少对象，不能据此外推到开放环境。" },
    ],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、论文、RoboCasa-X 本体与评估设置可核验。"], implementation: ["辅助损失权重为 1；正文披露各本体示范量、rollout 数和表征构造方式。"], missing: ["完整训练代码和权重尚未确认公开；真机仅报告有限场景中的任务进度。"] },
    deepDive: { lead: "BARx 的关键不是寻找通用视觉特征，而是让表示既忽略本体外观，又保留与动作决策直接相关的行为结构。", sections: [{ title: "行为对齐的联合目标", paragraphs: ["目标框描述任务对象，语言运动描述动作语义，末端轨迹描述几何运动；三者的信息粒度互补。", "训练时辅助头与动作头共享主干，测试时仍由相同 VLA 产生动作，不需要目标机器人共享源机器人的关节空间。"] }, { title: "证据边界", paragraphs: ["XP-900 与 XP-3K 的差异表明，表征只有在跨本体先验足够大时才更容易显现。", "真机使用任务进度且场景受限，因此 28% 应理解为受控迁移增益，而非通用成功率提升。"] }], equations: [{ name: "联合行为克隆目标", expression: "L = L_action + λ L_rep,  λ = 1", explanation: "动作损失与表征预测损失共同更新共享主干；论文主实验把辅助权重设为 1。" }], experimentReading: ["仿真 100 次/格足以观察大差异，但 best-of-three checkpoint 会抬高结果。", "真机每格 10–30 次且采用任务进度，更适合判断方向而非精确成功率。"], reflections: [] },
    strengths: "仿真规模、低数据目标本体和两种真机本体形成了清晰的跨本体控制变量。",
    limitations: "真机环境与对象范围窄，部分评估次数较少，仿真采用最优 checkpoint，且 28% 对应任务进度而非完整成功。",
    transfer: "可把对象框、末端轨迹或语言动作当作跨机器人共享的辅助监督，在不统一关节空间的情况下吸收异构示范。",
    figures: [{ src: "/report-assets/2026-08-03/2607.27549-overview.png", alt: "BARx 使用行为对齐表征促进跨本体数据迁移的总体方法", caption: "Figure 1 · BARx 的跨本体训练与 behavior-aligned representation 设计。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 2,
    title: "RedFlow: Redirect Failure into Action-Level Corrections for Flow-matching VLA Policy",
    arxivId: "2607.27782",
    url: "https://arxiv.org/abs/2607.27782",
    institutions: ["The Hong Kong University of Science and Technology"],
    signal: "把失败 rollout 从轨迹级负样本拆成可恢复动作，并用相似成功片段提供局部修正方向",
    tags: ["Offline RL", "Flow Matching", "Failure Recovery"],
    classification: { research: "VLA", training: "Post-training", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    motivation: "部署中的失败通常只被丢弃或作为整条负轨迹处理，无法指出哪段动作造成错误，也不能告诉 flow policy 应该向哪个可行动作移动。",
    methodSummary: "RedFlow 用进度奖励模型和本体状态聚类定位失败片段，从相似上下文的成功轨迹检索替代动作，再分别强化成功、压制不可取动作并重定向可恢复失败。",
    architecture: "以 OpenPI 的 π0 为基座；上下文感知匹配由任务进度、状态与 HDBSCAN 聚类构造，adaptive redirection objective 直接调整 flow velocity field。",
    optimization: "先用专家示范训练基座，再用混合成功/失败部署 rollout 做离线后训练；不需要在线策略持续与环境交互。",
    data: "真机衣物折叠、物体清扫和桌面清洁分别用 600、200、100 条专家示范，并收集 200、100、100 条 rollout；LIBERO 每套使用 1,536 条混合质量轨迹。",
    experiments: "AgileX Cobot Magic 双臂真机每任务 100 次，平均成功率从 56.7% 提至 74.7%；LIBERO 四套共 40 个任务，每套 500 次评估。",
    novelty: "区别于只给成功轨迹加权或把失败整体降权，RedFlow 把可恢复失败对齐到同语境中的成功动作，形成细粒度纠偏监督。",
    experimentDetails: [{ title: "离线失败再利用", setup: "LIBERO 四套、每套 10 个任务；每套 1,536 条训练 rollout、500 次评估。", comparisons: "AWR、DPO 及去掉成功强化、失败抑制或纠正目标的变体。", results: ["RedFlow 四套平均约 68.2%，DPO 为 59.7%。", "三套消融中完整模型平均 72.5%，去掉失败信息为 68.0%，去掉成功强化为 62.4%。"], evidenceNote: "同一混合数据下的消融支持成功与失败信号互补。" }, { title: "双臂真机恢复", setup: "三项任务每方法各 100 次，前视与腕部相机共同观测。", comparisons: "基础 π0 与 RedFlow，专家数据和评估条件保持一致。", results: ["平均成功率 56.7%→74.7%。", "出现基座未展示的恢复行为，例如换另一只手取回超出原手范围的衣物后重试。"], evidenceNote: "论文还报告与在线 PPO、GRPO、DDPO 接近的结果，但离线方案使用的交互样本约少一个数量级。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["论文给出训练数据量、聚类构造、损失和逐任务评估协议。"], implementation: ["基座训练 50K steps；真机每任务 100 次，LIBERO 每套 500 次。"], missing: ["部署 rollout、奖励模型与完整训练代码尚未确认公开。"] },
    deepDive: { lead: "RedFlow 把失败看成局部偏航，而不是给整条轨迹贴上统一负标签。", sections: [{ title: "从失败片段到修正目标", paragraphs: ["进度奖励和本体状态先形成语境簇，再找出失败诱发的动作块。", "若同簇成功轨迹存在，就把其中动作作为局部替代目标；无法恢复的失败只做抑制。"] }, { title: "三类梯度", paragraphs: ["成功动作保持 flow 的高概率区域，失败动作被压低，而可恢复动作获得指向替代动作的重定向梯度。", "这种分解避免轨迹级偏好学习把失败前仍然正确的动作一并惩罚。"] }], equations: [{ name: "动作级重定向", expression: "v_redirect = v_success - α v_failure + β(v_corrective - v_failure)", explanation: "示意三类训练信号：强化成功、抑制失败，并将可恢复失败的速度场推向匹配的纠正动作。" }], experimentReading: ["100 次/真机条件与 500 次/LIBERO 套件使大幅差异较可信。", "恢复案例说明行为发生变化，但定性案例不能替代逐类失败统计。"], reflections: [] },
    strengths: "成功与失败的作用有独立消融，真机评估次数充足，并观察到具体恢复行为。",
    limitations: "依赖任务进度奖励和上下文聚类质量；失败类型与恢复行为仍缺少系统化分层统计。",
    transfer: "适合把现有部署日志切成局部错误片段，再用同状态成功片段生成 flow policy 的纠偏目标。",
    figures: [{ src: "/report-assets/2026-08-03/2607.27782-overview.png", alt: "RedFlow 将失败动作匹配到相似上下文成功动作的训练框架", caption: "Figure 2 · RedFlow 的上下文匹配与自适应重定向目标。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 3,
    title: "FA-RDP: A Frequency-Adaptive Reactive Diffusion Policy for Contact-Rich Manipulation",
    arxivId: "2607.28596",
    url: "https://arxiv.org/abs/2607.28596",
    institutions: ["Shanghai Jiao Tong University", "Shanghai Innovation Institute"],
    signal: "在接触前保留多模态轨迹、接触后切换高频单步反应，避免固定扩散频率的两难",
    tags: ["Diffusion Policy", "Force", "Contact-Rich"],
    classification: { research: "VLA", training: "BC", modalities: ["Force / Torque", "State / Proprioception"], platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://fa-rdp.github.io/" }],
    motivation: "低频多步扩散能保留接触前的多种有效路线，却无法快速响应力变化；高频单步预测更灵敏，但容易提前坍缩到单一路径。",
    methodSummary: "FA-RDP 用一个视觉-力觉 Transformer 同时支持低频多步与高频单步生成，再由 learned multimodality indicator 随动作歧义下降切换频率。",
    architecture: "共享多频视觉-力觉 Transformer、frequency-adaptive positional grid 和多模态指示器；MCD 教师-学生重参数化在动作流形上蒸馏，同时保留 DDPM residual supervision。",
    optimization: "接触前按低频多步扩散采样，接触后改为 30 Hz 单步预测；指示器由低频 N=8 样本的动作分散度监督。",
    data: "Flexiv Rizon 4R/4s 主从采集，腕部 iPhone、第三视角相机与末端六维力传感；双臂翻盒、拨动开关、按双按钮各 60 条示范。",
    experiments: "每方法-任务 20 次，FA-RDP 为 14/20、18/20、17/20，平均 81.7%；最强固定频率基线平均 51.7%。多模态轨迹统计每任务 80 次。",
    novelty: "相对固定控制频率，它把扩散采样步数和执行频率变成由当前动作多模态程度驱动的阶段变量。",
    experimentDetails: [{ title: "三项接触任务", setup: "双臂翻盒、双开关和双按钮，每任务 60 条示范、每格 20 次真机试验。", comparisons: "固定低频多步、固定高频单步、RDP 及蒸馏/频率切换消融。", results: ["FA-RDP 平均 81.7%，最强基线 51.7%，提升 30.0 个百分点。", "高频单步平均 61.7%，加入自适应切换后为 81.7%。", "推理在 Core Ultra 9 与 RTX 5090 上低于 30 ms；外部力补偿环为 100 Hz。"], evidenceNote: "试验数为 20/格，30 点差异明显；计算平台属于高端桌面 GPU。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页可核验；论文给出网络、频率、示范量和评估次数。"], implementation: ["低频指示器采样 N=8；高频模式 30 Hz，力补偿 100 Hz。"], missing: ["完整训练代码和数据尚未确认公开；尚未验证触觉或其他高频模态。"] },
    deepDive: { lead: "FA-RDP 的切换依据不是手工接触阈值，而是当前动作分布是否仍存在多个有效模式。", sections: [{ title: "频率与动作歧义", paragraphs: ["接触前不同靠近方向都可能成功，多步采样保留这些模式；进入接触后约束变强，单步高频响应更重要。", "同一 Transformer 通过频率位置网格共享两种模式，减少训练两个独立策略带来的分布断点。"] }, { title: "MCD 蒸馏", paragraphs: ["教师的多步扩散为学生提供动作流形目标，学生保留 residual supervision，避免一步预测只拟合均值。", "频率指示器根据低频候选的分散度决定何时切换。"] }], experimentReading: ["三个物理任务均要求接触后的快速力响应，和方法假设匹配。", "每格 20 次可支持大幅提升，但不足以精确比较小差异或失败类型。"], reflections: [] },
    strengths: "阶段假设、频率消融、真实力觉平台和多模态轨迹统计相互对应。",
    limitations: "只测试视觉与力觉、三项双臂任务，并依赖 RTX 5090；跨传感器和跨平台迁移未知。",
    transfer: "可在现有 diffusion policy 上用候选动作离散度作为频率门控，在接触后切换到高频快速头。",
    figures: [{ src: "/report-assets/2026-08-03/2607.28596-overview.png", alt: "FA-RDP 在接触前后自适应切换扩散采样频率的架构", caption: "Figure 2 · FA-RDP 的多频共享策略、指示器与 MCD。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 4,
    title: "Self-Evolving Learning for Embodied AI with Criticality Model",
    arxivId: "2607.28251",
    url: "https://arxiv.org/abs/2607.28251",
    institutions: ["Tsinghua University", "Dense-AI"],
    signal: "从策略自身失败中学习 criticality，再把有限采集预算集中到容易失败的状态",
    tags: ["Criticality", "Importance Sampling", "Self-Evolving"],
    classification: { research: "VLA", training: "Post-training", data: "数据质量 / 筛选", platforms: ["机械臂", "其他平台"] },
    motivation: "随机补采会被普通成功场景淹没，罕见失败既难发现，也难在固定预算内形成足够训练密度。",
    methodSummary: "先用当前策略 rollout 的成败训练 state-wise criticality model，再从大状态池重要性采样失败高风险场景；重采样权重保持训练目标，部署时按阈值在基座与专项策略间路由。",
    architecture: "criticality model 接收任务特定状态；真机用 8 维几何量和 8-32-1 两层 MLP。它输出未来失败概率，控制采样分布及部署路由。",
    optimization: "从 10,000 个候选状态中以 ε=0.1 的重要性采样选 100 个场景，与 100 个随机场景对照；专项策略从同一 checkpoint 训练 10K steps。",
    data: "覆盖 Go2、ManiSkill、LIBERO、RoboTwin 和 AgileX Piper 真机。真机 Banana-on-Plate 初始数据 240 episodes，后训练各 100 个随机或重要性采样场景。",
    experiments: "真机重要性测试分布上每方法 50 次：基座加权失败率 11.15%，随机后训练 18.05%，仅专项策略 6.05%，阈值路由 3.72%。",
    novelty: "区别于均匀难例挖掘，方法显式估计状态的未来失败风险，并在采集、重采样训练和部署路由三个阶段复用同一 criticality。",
    experimentDetails: [{ title: "真机香蕉放盘", setup: "AgileX Piper、三个 960×540 RGB 视角、7D 动作；240 条初始 episode，50 次重要性测试。", comparisons: "基座、随机场景后训练、重要性采样专项策略和阈值路由。", results: ["criticality model 在 99 个标注场景上 AUC 0.918、F1 0.821。", "加权失败率依次为 11.15%、18.05%、6.05%、3.72%。"], evidenceNote: "评估分布本身由重要性采样构造，结果不等同于自然部署频率。" }, { title: "多域验证", setup: "LIBERO 6,000 episodes、3 个随机种子；RoboTwin 1,000 episodes，并覆盖四足运动与 ManiSkill。", comparisons: "相同数据预算下的随机采样、仅微调与路由。", results: ["LIBERO 失败率 1.87%→1.40%。", "RoboTwin 14.4%→13.3%；路由 124/1,000 次，其中 19 次修复、8 次回退。"], evidenceNote: "绝对改善在高成功率基线上较小，论文以失败率相对下降表达。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["五个域、采样预算、真机状态定义、阈值和评估次数均在正文披露。"], implementation: ["真机 criticality MLP 为 8-32-1；候选池 10,000，ε=0.1。"], missing: ["状态表示需按任务人工设计；完整代码、场景池和权重尚未确认公开。"] },
    deepDive: { lead: "方法将“哪里会失败”变成一个可学习的采集控制器，而不是在策略训练后被动分析日志。", sections: [{ title: "重要性采样闭环", paragraphs: ["现有策略先产生成功/失败标签，criticality model 学习状态到未来失败概率。", "采集时优先选择高风险状态，训练时使用重要性权重减少分布偏差，部署时只在高风险区调用专项策略。"] }, { title: "路由为何有用", paragraphs: ["专项策略在难例上更强，却可能在普通状态回退；阈值路由保留基座的常规能力。", "RoboTwin 的 19 次修复与 8 次回退直接显示了路由的收益和代价。"] }], equations: [{ name: "重要性加权风险", expression: "E_p[L] = E_q[(p(s)/q(s)) L(s)]", explanation: "从强调高 criticality 的分布 q 采样后，用 p/q 权重近似原部署分布 p 下的目标。" }], experimentReading: ["真机 50 次且评估分布偏向难例，适合验证难例修复，不代表总体自然成功率。", "多个仿真域与三个种子减轻了单任务偶然性，但状态设计仍依赖人工先验。"], reflections: [] },
    strengths: "采集、训练和部署闭环完整，覆盖多个仿真域与真实 VLA，并报告路由的修复与回退。",
    limitations: "criticality 输入按任务设计，重要性测试分布不同于自然部署，真机仅 50 次。",
    transfer: "可先在现有策略日志上训练轻量失败预测器，用它分配新采集预算，并保留基座/专项策略门控。",
    figures: [{ src: "/report-assets/2026-08-03/2607.28251-overview.png", alt: "criticality model 驱动场景采样、训练和部署路由的闭环", caption: "Figure 1 · Self-Evolving Learning 的 criticality 闭环。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 5,
    title: "TacWAM: Anchor-Guided World Action Model with Mechanics-Aware Tactile Prediction",
    arxivId: "2607.28391",
    url: "https://arxiv.org/abs/2607.28391",
    institutions: ["Tsinghua University", "Manifold AI"],
    signal: "让未来触觉在训练期提供力学监督，同时阻止动作分支偷看部署时不存在的未来信息",
    tags: ["World Action Model", "Tactile", "Contact-Rich"],
    classification: { research: "WAM", training: "BC", modalities: ["Tactile", "Force / Torque"], platforms: ["机械臂", "夹爪"] },
    motivation: "视觉未来能描述物体运动，却难以监督力、形变、剪切和滑移；直接让动作读取未来触觉又会产生训练-部署信息泄漏。",
    methodSummary: "SAF 将触觉外观、稠密力场和网格形变对齐到统一 latent，并重建双侧 wrench；触觉历史提供动态上下文，AGT attention 限制动作只能读取当前视觉/触觉锚点。",
    architecture: "视觉、触觉历史与未来预测 token 构成三模态 WAM；anchor-guided mask 允许未来触觉监督共享表示，但切断 future-token 到 action-token 的直接路径。",
    optimization: "以行为克隆动作损失联合未来视觉/触觉预测和 wrench 重建训练；部署时未来触觉只作为训练监督，不是在线输入。",
    data: "AgileX Piper、双侧 Xense G1-WS 触觉、顶视与腕部相机，30 Hz；芯片抓取、樱桃抓取、擦拭和物体旋转各 300 episodes、约 500 帧/episode。",
    experiments: "每方法-任务 20 次；TacWAM 分别 90%、70%、75%、65%，平均 75.0%，最强 VT-WAM 为 37.5%。",
    novelty: "相对把触觉直接拼接到 WAM，TacWAM 同时解决力学表达、时间历史和未来目标泄漏三个问题。",
    experimentDetails: [{ title: "四项真机接触操作", setup: "脆弱抓取、持续表面接触和动态手内旋转，四任务每格 20 次。", comparisons: "π0.5、Fast-WAM、RDP 与重实现的 VT-WAM，保持数据、动作空间和 epoch 一致。", results: ["π0.5、Fast-WAM、RDP、VT-WAM 平均为 31.3%、20.0%、32.5%、37.5%，TacWAM 为 75.0%。", "TacWAM 四任务为 90%、70%、75%、65%。"], evidenceNote: "VT-WAM 为作者重实现版本，可能与原实现存在差异。" }, { title: "信息泄漏消融", setup: "芯片抓取与擦拭，各变体合计每任务 20 次。", comparisons: "完整模型、无触觉历史、允许动作读未来触觉、完全双向 attention。", results: ["两任务平均成功率依次为 82.5%、55.0%、37.5%、7.5%。"], evidenceNote: "逐步放松 mask 后持续下降，直接支持部署一致的信息约束。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["传感器、帧率、数据量、成功判据、基线和消融均由正文核验。"], implementation: ["每任务约 15 万帧；动作、未来预测与 wrench reconstruction 联合训练。"], missing: ["代码、数据和权重尚未确认公开；重实现基线的等价性有限。"] },
    deepDive: { lead: "TacWAM 的主要贡献不是简单增加触觉，而是规定触觉信息在时间和注意力图中何时可以被读取。", sections: [{ title: "力学触觉表示", paragraphs: ["SAF 同时编码外观、局部稠密力与表面网格形变，再以双侧 wrench 重建保存全局接触信息。", "历史编码器让未来触觉预测能够区分相同当前图像下不同的力变化趋势。"] }, { title: "部署一致的注意力", paragraphs: ["未来 token 可以接受当前锚点并承担预测损失，但动作 token 不能直接读取未来目标。", "完全双向 attention 的严重下降显示，训练时便利的信息通路会破坏部署时动作生成。"] }], experimentReading: ["四个任务都依赖触觉且每格 20 次，37.5 点平均差异具有明确方向。", "基线中 VT-WAM 为重实现，最公平的证据仍是同一模型内部的 mask 与历史消融。"], reflections: [] },
    strengths: "物理模态设计、信息流消融和四项真实接触任务构成一致证据链。",
    limitations: "单一机械臂和触觉硬件，基线部分重实现，尚未验证跨传感器泛化。",
    transfer: "在任何 future-prediction policy 中，都应把未来监督与在线可见条件分开，并用 attention mask 审计信息泄漏。",
    figures: [{ src: "/report-assets/2026-08-03/2607.28391-overview.png", alt: "TacWAM 的 SAF 触觉编码、历史和 anchor-guided attention", caption: "Figure 1 · TacWAM 的 mechanics-aware tactile prediction 与信息流约束。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 6,
    title: "SemAnCorr: Semantic Anchored Correspondence for Zero-Shot Manipulation Skill Transfer",
    arxivId: "2607.28382",
    url: "https://arxiv.org/abs/2607.28382",
    institutions: ["Carnegie Mellon University", "Vanderbilt University", "University of California, Berkeley", "The University of Sydney"],
    signal: "用语义锚点与 functional maps 把单次示范的接触坐标系迁移到几何差异很大的新物体",
    tags: ["Correspondence", "Zero-Shot Transfer", "3D"],
    classification: { research: "表征学习", training: "Test-time Adaptation", modalities: ["Point Cloud / 3D", "Mask / Segmentation"], platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://semancorr.github.io/" }],
    motivation: "视觉描述子的最近邻匹配可以语义相似，却在物体表面跳跃，无法恢复稳定接触所需的局部几何坐标系。",
    methodSummary: "SemAnCorr 在 3D 网格上聚类预训练语义特征，联合选择跨物体锚点，再用 functional maps 把稀疏语义约束平滑传播为稠密对应。",
    architecture: "SAM3D 生成对齐网格，预训练特征被 lift 到顶点；语义聚类、joint pose-correspondence anchor selection 与谱域 functional map 依次产生物体中心对应和接触关键帧。",
    optimization: "方法不训练策略；测试时根据一个 kinesthetic demonstration 的对象相对接触与运动，把关键帧转换到新物体。",
    data: "PartNet-Mobility 七类对象构建对应基准；真机用 RGB-D 标定、SAM3D 网格和单次示范，覆盖香蕉剥皮、笔盖、倒水、旋盖及工具功能迁移。",
    experiments: "PartNet 语义准确率 90.8%±2.5，D3Fields 为 84.6%；真机五任务各 10 次，SemAnCorr 成功 37/50，D3Fields 为 23/50。",
    novelty: "相对独立顶点最近邻，它先选语义一致锚点，再以表面几何平滑约束传播，因此能恢复可执行的局部接触框架。",
    experimentDetails: [{ title: "对应质量与消融", setup: "PartNet-Mobility 七类对象，评估语义准确率和几何连贯性。", comparisons: "D3Fields、无语义聚类、无 anchor selection、无 functional map。", results: ["SemAnCorr 语义准确率 90.8%±2.5，D3Fields 84.6%；几何连贯性 0.40 对 0.16。", "去掉语义聚类、锚点和 functional map 后，语义准确率分别为 66.0%、39.1%、72.9%。"], evidenceNote: "组件消融同时影响语义与几何指标，支持完整流水线。" }, { title: "单示范零样本真机迁移", setup: "五种功能等价但几何差异明显的对象配对，每任务 10 次、物体位姿和视角变化。", comparisons: "D3Fields 与 SemAnCorr 使用相同示范和执行后端。", results: ["D3Fields 五任务为 7/10、9/10、3/10、1/10、3/10。", "SemAnCorr 为 8/10、9/10、7/10、7/10、6/10。"], evidenceNote: "主要失败来自网格与真实工作空间对齐误差。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、数据类别、单示范协议和消融均可核验。"], implementation: ["流程需要 RGB-D 标定、SAM3D 网格对齐和 GPG 物理抓取。"], missing: ["完整代码尚未确认公开；真实执行依赖网格-工作空间配准质量。"] },
    deepDive: { lead: "SemAnCorr 把语义特征当作锚点来源，而不是最终逐点匹配答案。", sections: [{ title: "语义锚点与谱传播", paragraphs: ["语义聚类先找出功能一致的候选区域，联合姿态-对应优化再选跨对象稳定锚点。", "functional map 在网格谱基上平滑传播锚点约束，避免最近邻在表面产生不连续跳跃。"] }, { title: "从对应到动作", paragraphs: ["单次示范被分解为物体中心的接触关键帧与相对运动。", "新物体对应给出局部框架后，原技能无需策略再训练即可转换并执行。"] }], experimentReading: ["对应基准与真机结果方向一致，说明几何连贯性确实转化为执行收益。", "真机每任务 10 次，且对齐是主要失败源，因此系统级成功率仍受外部重建影响。"], reflections: [] },
    strengths: "表征指标、组件消融和五类功能迁移真机结果相互印证。",
    limitations: "依赖高质量 RGB-D 网格与配准，每任务只有 10 次，复杂柔性物体和动态接触未验证。",
    transfer: "可把基础模型语义特征降级为少量可靠 anchor，再用显式几何平滑恢复可执行的稠密对应。",
    figures: [{ src: "/report-assets/2026-08-03/2607.28382-overview.png", alt: "SemAnCorr 从语义锚点到 functional map 和技能迁移的完整流程", caption: "Figure 1 · SemAnCorr 的语义锚点对应与零样本技能迁移。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 7,
    title: "Static In, Dynamic Out: Counterfactual Action Augmentation for Moving Object Manipulation",
    arxivId: "2607.27890",
    url: "https://arxiv.org/abs/2607.27890",
    institutions: ["Georgia Institute of Technology"],
    signal: "不采移动物体示范，而是反事实平移静态对象与动作块，让策略在部署时追逐预测未来位姿",
    tags: ["Counterfactual Augmentation", "Moving Object", "Imitation Learning"],
    classification: { research: "VLA", training: "BC", data: "数据增强", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://sido-staticindynamicout.github.io/" }],
    motivation: "静态示范训练的策略会追向物体过去的位置；真实传送带、果树等场景需要预测未来位姿并保持手-物关系。",
    methodSummary: "SIDO 反事实移动训练中的对象，并形变动作 chunk，使重规划点和 chunk 终点的手-物相对位姿不变；部署时对象运动预测器给出未来目标。",
    architecture: "goal-conditioned Diffusion Policy 或 EquiDP 接收预测对象位姿；DynaSIDO 用动力学模型与 MPPI，真机 H-SIDO 使用轻量预测器。",
    optimization: "只用静态成功示范做行为克隆，通过对象位移和动作 morphing 合成移动目标训练对；部署时不在线微调。",
    data: "仿真 Mug/Square 各 1,000 条、Stack 200 条静态示范；真机 Gantry 分轴/随机各 30/22/64 条，Peachtree 25 条。",
    experiments: "仿真三任务、五种运动，每格 20 次；真机 Franka 每格 20 次。Gantry 动态条件 SIDO 为 55%/65%/25%，current-pose 为 35%/50%/20%。",
    novelty: "相对采集动态示范或只在测试时追当前位姿，SIDO 用几何不变量从静态数据合成未来目标条件。",
    experimentDetails: [{ title: "仿真运动模式", setup: "Mug、Square、Stack，五种目标运动，Diffusion Policy 与 EquiDP 两种 backbone，每格 20 次。", comparisons: "静态基线、current-pose conditioning、action correction 与 SIDO/DynaSIDO。", results: ["SIDO 在多数移动条件提高成功，同时大体保留静态任务能力。", "不同 backbone 和运动模式方向一致，支持增强方式而非特定网络。"], evidenceNote: "仿真结果不是入选依据的唯一证据，真机同样验证。" }, { title: "Gantry 与 Peachtree 真机", setup: "Franka/DROID 设置，对象约 1.5 cm/s；每格 20 次。", comparisons: "current pose、action correction、SIDO 与静态条件。", results: ["Gantry 三种动态方向：current pose 35%/50%/20%，action correction 0%/30%/0%，SIDO 55%/65%/25%。", "Peachtree 动态成功率 45%/30%/60%；静态时 current pose 90%、SIDO 75%。", "用 5 分钟运动数据训练 FERNN 预测器后成功率 40%，有限差分和 MLP 各 25%。"], evidenceNote: "SIDO 在 Peachtree 静态条件下降 15 点，说明动态增强并非无代价。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、示范量、运动速度、预测器对照和试验次数可核验。"], implementation: ["增强保持重规划时刻与 chunk 终点的手-物相对位姿。"], missing: ["依赖 6DoF 对象追踪及参考模型；真机主要验证平移运动。"] },
    deepDive: { lead: "SIDO 将移动物体操作拆成“预测去哪里”和“如何到那里”，让静态示范只负责后一部分。", sections: [{ title: "反事实动作形变", paragraphs: ["先把对象在训练观察中移动到假设未来位姿，再对专家 action chunk 做几何变换。", "变换保持关键时刻的手-物相对关系，使策略学习目标条件而不需要真实动态示范。"] }, { title: "部署预测器", paragraphs: ["预测器只负责未来对象位姿，策略负责从当前机器人状态到目标的动作。", "DynaSIDO 用模型预测控制，H-SIDO 则强调真实系统中的低成本实现。"] }], equations: [{ name: "相对位姿保持", expression: "T'_hand(t) = T'_obj · T_obj⁻¹ · T_hand(t)", explanation: "对象被反事实移动后，以同一刚体变换调整手轨迹，从而保持手-物相对位姿。" }], experimentReading: ["动态条件改善与静态条件退化都被报告，避免只展示有利一侧。", "每格 20 次且目标速度固定，仍需更宽速度和旋转运动验证。"], reflections: [] },
    strengths: "纯静态数据、两种策略 backbone、仿真与真机以及预测器对照共同支持方法。",
    limitations: "依赖对象位姿估计和参考模型，真实实验以平移为主，静态性能可能退化。",
    transfer: "适合把静态产线示范扩展为传送带任务：单独训练对象预测器，并用相对位姿不变量增强动作。",
    figures: [{ src: "/report-assets/2026-08-03/2607.27890-overview.png", alt: "SIDO 反事实移动对象并形变动作块的训练与部署流程", caption: "Figure 2 · SIDO 的反事实动作增强。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 8,
    title: "DexDirect: Direct Kinesthetic Arm Guidance for Efficient Dexterous Demonstration Collection",
    arxivId: "2607.27784",
    url: "https://arxiv.org/abs/2607.27784",
    institutions: ["University of California, Los Angeles"],
    signal: "用直接拖动重力补偿机械臂控制腕部，再以单摄像头重定向另一只手，提升灵巧示范的有效产出",
    tags: ["Teleoperation", "Dexterous Hand", "Demonstration Data"],
    classification: { research: "其他", training: "BC", data: "在线数据 / 人工纠正", platforms: ["机械臂", "灵巧手"] },
    motivation: "高保真灵巧遥操作通常设备昂贵、设置复杂；纯视觉方案虽轻量，却给操作者带来更高认知负担和较低成功率。",
    methodSummary: "操作者直接通过手柄拖动 6DoF 重力补偿机械臂，另一只手由单 webcam 追踪并重定向到 16 关节、13DoF 灵巧手。",
    architecture: "PIPER 机械臂提供腕部位姿与物理引导，MIDAS 灵巧手执行手部重定向；同步记录关节、触觉和腕部图像，频率 30 Hz。",
    optimization: "采集接口本身不训练；下游用 DexDirect 成功示范训练 diffusion policy，验证数据是否足以产生可部署策略。",
    data: "10 名参与者完成五项灵巧任务，在固定时间内比较 DexDirect、AnyTeleop 和 TeleDex；三方法分别得到 481、28、151 条成功示范。",
    experiments: "DexDirect 的成功示范数是 AnyTeleop 的 17.2 倍、TeleDex 的 3.2 倍；下游方块抓取放置 diffusion policy 达到 90% 真机成功率。",
    novelty: "把腕部的精确物理引导与手指的低成本视觉重定向拆分，避免让单一接口同时承担大范围 6DoF 和高维手部控制。",
    experimentDetails: [{ title: "十人遥操作研究", setup: "五项任务、10 名参与者、固定采集时间，记录成功示范数、任务成功率和 NASA-TLX。", comparisons: "DexDirect、纯视觉 AnyTeleop、姿态追踪 TeleDex。", results: ["成功示范总数 481 / 28 / 151，对应 17.2× 与 3.2×。", "DexDirect 五任务成功率为 94%、95%、96%、91%、71%，TeleDex 为 69%、81%、85%、56%、32%。", "心理需求、努力和挫折降低，但身体负担上升。"], evidenceNote: "参与者设计直接测量采集效率，物理负担是明确代价。" }, { title: "下游策略验证", setup: "用 DexDirect 示范训练 diffusion policy 完成方块抓取放置。", comparisons: "以真实闭环策略成功而非仅轨迹数量检验数据质量。", results: ["下游真机成功率为 90%。"], evidenceNote: "只验证一个下游任务，不能说明所有采集任务都能同样转化为策略性能。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["硬件、频率、参与者数、任务协议、成功示范数和 NASA-TLX 均在正文披露。"], implementation: ["直接引导腕部与单摄像头手部重定向分工；数据同步频率 30 Hz。"], missing: ["完整硬件装配、重定向代码和数据集尚未确认公开。"] },
    deepDive: { lead: "DexDirect 的效率来自按控制维度分工：手臂依赖人体的直接物理直觉，手指保留轻量视觉映射。", sections: [{ title: "混合控制接口", paragraphs: ["重力补偿让操作者直接给出腕部路径和接触姿态，降低通过屏幕推断 6DoF 的认知负担。", "另一只手的视觉关键点映射到灵巧手，避免穿戴式手套和外部追踪系统。"] }, { title: "从示范数量到可用性", paragraphs: ["用户研究同时报告成功轨迹数与负担，不把速度提升等同于数据质量。", "下游 diffusion policy 的 90% 成功率提供了一项闭环可用性检查。"] }], experimentReading: ["10 名参与者和五任务比单操作者实验更能分离接口学习成本。", "下游只覆盖方块抓放，数据质量的普遍性仍未充分验证。"], reflections: [] },
    strengths: "用户研究、任务成功、主观负担和下游真机策略形成多维证据。",
    limitations: "身体负担更高，直接引导限制工作空间与远程性；下游策略只测试一项任务。",
    transfer: "采集系统可将低维大范围手臂控制交给直接示教，把高维手指控制交给视觉重定向。",
    figures: [{ src: "/report-assets/2026-08-03/2607.27784-overview.png", alt: "DexDirect 的直接手臂引导、手部视觉重定向和数据记录流程", caption: "Figure 2 · DexDirect 的混合灵巧示范采集系统。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 9,
    title: "FasTac: A Curved Multispectral Vision-Based Tactile Sensor for High-Speed High-Precision 3D Shape and Force Perception",
    arxivId: "2607.28416",
    url: "https://arxiv.org/abs/2607.28416",
    institutions: ["Huazhong University of Science and Technology", "National Innovation Institute of Digital Design and Manufacturing"],
    signal: "在同一弧形指尖内联合多光谱形貌、三轴力估计与 FPGA 流水线，兼顾精度和千赫兹级处理",
    tags: ["Tactile Sensor", "Multispectral", "FPGA"],
    classification: { research: "表征学习", training: "BC", modalities: ["Tactile", "Force / Torque"], platforms: ["灵巧手", "夹爪"], deployment: "真机部署优化" },
    motivation: "弧形视觉触觉指尖需要同时感知微小三维形貌、法向/切向力与瞬态振动，但曲面光照和非均匀弹性响应让精度与速度难以兼得。",
    methodSummary: "FasTac 用单相机同步多光谱 photometric stereo 重建法向，加入边界先验的快速 Poisson 求深度；HyperForce 以位置感知动态卷积估计三轴力。",
    architecture: "RGB-NIR 多光谱照明与弧形弹性体共享成像链；法向/深度和 HyperForce 分支并行，完整 image-to-Fz 流水线部署到 FPGA。",
    optimization: "监督训练 HyperForce 的动态卷积核，并将图像预处理、网络推理与后处理做定点/流水线硬件映射。",
    data: "标定集覆盖不同曲面位置、压入深度与三轴载荷；另用多物体重建、闭环抓取和振动测量检验几何、力反馈与动态触觉。",
    experiments: "NIR 与边界先验把深度 MAE 从 0.2730 mm 降到 0.0415 mm；法向力与剪切力 NMAE 为 2.74% 和 2.39%；延迟从 GPU 3.26 ms 降到 FPGA 1.09 ms。",
    novelty: "相对只做形貌或低速力估计的弧形传感器，它在统一光学与硬件链中同时处理三维形状、三轴力和快速瞬态。",
    experimentDetails: [{ title: "形貌与力估计", setup: "曲面不同接触位置与载荷的标定测试，并进行未见物体重建。", comparisons: "可见光、加入 NIR、加入边界先验，以及静态卷积与 HyperForce。", results: ["深度 MAE 0.2730→0.0415 mm。", "法向与剪切 NMAE 分别 2.74% 和 2.39%。"], evidenceNote: "跨传感器、跨弹性体和长期漂移尚未验证。" }, { title: "硬件与闭环演示", setup: "FPGA image-to-Fz 流水线，并做反馈抓取和振动测量。", comparisons: "GPU 与 FPGA 延迟及吞吐。", results: ["延迟 3.26 ms→1.09 ms；论文报告 FPGA 流水线达到千赫兹级吞吐。", "闭环抓取和振动实验验证输出能进入控制与动态测量。"], evidenceNote: "不同传感器基线的硬件与设置并不完全一致，能力表不应视为严格排行榜。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["光学结构、重建算法、力模型、FPGA 延迟和闭环演示由正文核验。"], implementation: ["边界先验 Poisson reconstruction、位置感知动态卷积和完整 image-to-Fz FPGA pipeline。"], missing: ["标定数据、RTL/固件与跨器件一致性资料尚未确认公开。"] },
    deepDive: { lead: "FasTac 的系统价值在于把曲面触觉的光学、学习模型和实时硬件当作一个共同误差预算。", sections: [{ title: "多光谱曲面重建", paragraphs: ["NIR 与可见光在单相机上空间对齐，减少多传感器配准误差。", "曲面边界先验进入 Poisson 求解，抑制法向积分在边缘累积的深度漂移。"] }, { title: "非均匀力学与 FPGA", paragraphs: ["弧形弹性体在不同位置的响应不同，HyperForce 根据接触位置动态生成卷积权重。", "硬件流水线把推理延迟压到 1.09 ms，使输出可用于快速反馈，而不只是离线重建。"] }], experimentReading: ["NIR/边界和动态卷积均有对应消融，指标与设计直接匹配。", "闭环部分主要是能力展示，尚缺统一任务上的控制基线和长期稳定性。"], reflections: [] },
    strengths: "传感、算法、硬件和闭环演示完整，形貌、力和延迟指标均有明确对照。",
    limitations: "缺少跨器件标定、长期耐久和统一硬件条件的外部基线；闭环任务规模有限。",
    transfer: "设计弧形触觉时可把位置相关力学显式放入网络，并从一开始按 FPGA 数据流约束算法。",
    figures: [{ src: "/report-assets/2026-08-03/2607.28416-overview.png", alt: "FasTac 多光谱形貌、HyperForce 三轴力与 FPGA 流水线", caption: "Figure 4 · FasTac 的多光谱感知与硬件加速框架。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 10,
    title: "PAC-MAN: Perception-Aware CBF-RL for Whole-Body Safety in Humanoid Dodgeball",
    arxivId: "2607.28623",
    url: "https://arxiv.org/abs/2607.28623",
    institutions: ["California Institute of Technology"],
    signal: "训练时用全身 link-level barrier 引导，部署时只依赖头部相机的分割深度完成快速躲避",
    tags: ["Humanoid", "CBF-RL", "Whole-Body Safety"],
    classification: { research: "其他", training: "RL", modalities: ["Depth / RGB-D", "Mask / Segmentation", "State / Proprioception"], platforms: ["Humanoid"], deployment: "Sim2Real" },
    motivation: "人形机器人躲避高速物体既要保护所有身体 link，又必须使用固定头部相机下不完整、延迟且带噪的观测。",
    methodSummary: "PAC-MAN 在训练奖励中加入 link-level CBF 安全结构，并用 adversarial motion prior 保持可行人体动作；部署策略只接收分割遮罩后的低分辨率深度与本体状态。",
    architecture: "Unitree G1 29D 关节目标、50 Hz；视觉输入为 16×9 masked depth 的时间堆叠，头部 ZED Mini 经 EfficientTAM 分割，策略再与本体状态融合。",
    optimization: "仿真强化学习联合 Link-CBF reward 与 AMP；比较 Joint-CBF、Link-CBF、训练期 guidance、运行时 filter 及固定/云台/特权观测。",
    data: "训练与仿真测试使用可复现的 seeded throws；真实测试由人工投掷不同球，策略从仿真零样本迁移到 Unitree G1。",
    experiments: "固定相机仿真中 Link-CBF 单次/循环成功率 90%/89%，无 barrier 为 86%/86%；真机 20 次投掷成功 19 次、95%，且 0 次跌倒。",
    novelty: "相对只在特权球状态上设计 barrier，它把可观测性纳入 CBF 选择，使训练期安全结构与部署视觉条件一致。",
    experimentDetails: [{ title: "可观测性与 barrier 对照", setup: "单次投掷及每次返回站位的循环部署，两种 seeded throw 协议。", comparisons: "无 barrier、Link-CBF、Joint-CBF、固定相机、球跟踪云台与特权运行时 filter。", results: ["固定相机 Link-CBF 为 90%/89%，无 barrier 为 86%/86%，无引导 Joint-CBF 为 83%/76%。", "特权状态加运行时 filter 可到 97%/90%，但不满足真实部署观测条件。"], evidenceNote: "Joint-CBF 在精确球状态下更强，却在固定相机只作训练引导时退化，说明 barrier 与观测必须匹配。" }, { title: "Unitree G1 零样本部署", setup: "头部 ZED Mini、EfficientTAM 分割，人工投掷 20 次；成功定义为所有 link 无接触且机器人不跌倒。", comparisons: "部署轻量 Link-CBF policy，不使用运行时特权球状态。", results: ["19/20 次成功，即 95%。", "20 次均未跌倒，并能处理不同外观的球。"], evidenceNote: "样本仅 20 次，投掷主要来自正面，分割初始化需要人工点击前景。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["观测尺寸、控制频率、barrier 对照、成功定义和真机次数均由正文核验。"], implementation: ["29D joint target at 50 Hz；masked depth 16×9 temporal stack；EfficientTAM 约 60 Hz。"], missing: ["训练环境、策略权重与投掷数据尚未确认公开；前景初始化仍需人工。"] },
    deepDive: { lead: "PAC-MAN 说明安全约束不能只在完整状态空间中数学上更精确，还必须与部署时实际可见的信息相容。", sections: [{ title: "Link-CBF 与感知输入", paragraphs: ["Link-CBF 对每个身体 link 的球距离提供训练奖励，不要求运行时获得精确三维球状态。", "低分辨率 masked depth 保存来球的空间和时间变化，同时避免把背景纹理带入策略。"] }, { title: "为什么不部署 Joint-CBF", paragraphs: ["Joint-CBF 在准确球状态下可表达更强约束，但固定相机的部分观测不足以可靠恢复其所需状态。", "实验中使用云台或特权 filter 才能恢复性能，因此真实系统选择更鲁棒的 Link-CBF。"] }], equations: [{ name: "link 安全集", expression: "h_i(x) = d(link_i, ball) - d_safe ≥ 0", explanation: "每个身体 link 与球的距离形成一项 barrier；训练奖励鼓励所有 h_i 保持非负。" }], experimentReading: ["固定相机、云台和特权状态的对照把感知可观测性从控制器结构中分离。", "真机 19/20 很有说服力，但样本小、方向受限且人工初始化，仍需更开放来球测试。"], reflections: [] },
    strengths: "仿真控制变量明确，真实 Unitree G1 零样本部署同时报告任何 link 接触和跌倒。",
    limitations: "真机只有 20 次正面投掷，分割需人工初始化，尚未覆盖遮挡、多球和侧后方来球。",
    transfer: "安全 RL 中应先检查约束所需状态能否由部署传感器观测，再选择 barrier 粒度与运行时结构。",
    figures: [{ src: "/report-assets/2026-08-03/2607.28623-overview.png", alt: "PAC-MAN 从分割深度到 CBF-RL 全身躲避的训练与部署框架", caption: "Figure 2 · PAC-MAN 的感知输入、Link-CBF 训练与 Unitree G1 部署。图片来自 arXiv HTML 原图。" }],
  },
];
