import type { Paper } from "./site-data";
import { paperDaily20260717Additions } from "./paper-daily-2026-07-17-additions";

const paperCandidates20260717: Paper[] = [
  {
    rank: 1,
    title: "Towards Predictive, Aligned, and Scalable Robot Learning",
    arxivId: "2607.11270",
    url: "https://arxiv.org/abs/2607.11270",
    institutions: ["Astribot"],
    signal: "Lumo-2 将潜动作、未来视觉预测和 VLM 对齐放入三阶段训练，覆盖动态、记忆、长时与灵巧操作",
    tags: ["Lumo-2", "Latent World-Action Model", "Large-scale Pre-training"],
    classification: { research: "WAM", training: "Pre-training", data: "跨本体数据", platforms: ["Humanoid", "灵巧手"] },
    resources: [{ label: "项目页", url: "https://www.astribot.com/research/Lumo2" }],
    motivation: "机器人策略同时需要预测物理变化、理解语言语义并扩展到跨本体数据；单纯动作监督难以统一这三类能力。",
    methodSummary: "Lumo-2 先学习视觉逆/正向动力学与动作自编码器，再把语义动作 token 对齐到 Qwen3.5-4B，最后联合训练 VLM、视频和机器人数据。",
    architecture: "Qwen3.5-4B 提供视觉语言主干；双 VQ 模块离散化视觉变化与动作，视觉 latent 被送入 action decoder；动作 token 与 32 个视觉上下文 token 在第二阶段对齐。",
    optimization: "Stage 1 训练 30K steps、Stage 2 训练 12K steps，均使用 64 张 H100；Stage 3 将 VLM、视频和机器人目标联合训练。",
    data: "机器人数据混合 Astribot S1、AgiBot Genie1、Galaxea R1 Pro、RS-02、ARX/AgileX/YAM；人类视频含 EgoTaskQA、EPIC、Ego4D，VLM 数据约 5300 万条。",
    experiments: "22 项真机任务覆盖动态反应、运动理解、记忆、物理推理、长时和灵巧操作；论文以任务进度与分组指标比较 π0.5、Fast-WAM，并给出阶段、数据和对齐消融。",
    novelty: "相比只做动作预测的 VLA，Lumo-2 用视觉 forward dynamics 约束动作表征，再把离散动作与 VLM 语义对齐；跨多本体数据是训练主线而非附加微调。",
    strengths: "模型、数据和三阶段训练目标的规模完整，真机任务覆盖面广，且对视觉预测与语义对齐都做了消融。",
    limitations: "训练成本很高，数据与权重未确认公开；22 项测试主要由团队自建，缺少独立复现和统一成功率表。",
    transfer: "可借鉴视觉变化 token 与动作 token 的联合自编码，再将其作为 VLM 和连续控制之间的中间层。",
    experimentDetails: [{ title: "多能力真机评测与训练消融", setup: "Astribot S1 上 22 项真实任务，按动态、运动、记忆、物理、长时、灵巧六类汇总任务进度。", comparisons: "π0.5、Fast-WAM、去掉视觉预测/动作自编码/语义对齐的阶段消融，以及数据和模型缩放。", results: ["Lumo-2 在论文展示的六类任务中整体优于对照，长时和记忆任务的差异尤其明显；原文主要以图表给出 task progress，不宜改写成未报告的统一成功率。", "视觉 latent 融入动作解码、动作—语言对齐和后续联合训练均带来增量。", "跨本体与人类视频数据扩展后性能继续增长，但完整缩放曲线依赖内部数据。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["Qwen3.5-4B；5×224 图像；30 fps 每 8 帧采样；32-step action 压缩为 4 token；Stage1 30K、Stage2 12K；64×H100。"], verifiedResources: ["官方项目页提供论文、架构说明和 22 项真机视频。"], missing: ["训练代码、权重、完整数据配比与逐任务原始 trial 计数未确认公开。"] },
    deepDive: { lead: "Lumo-2 用潜在世界变化为动作 token 提供物理约束，再与语言语义对齐。", sections: [{ title: "三阶段预测与对齐", paragraphs: ["第一阶段同时训练 visual IDM/FDM 和 action autoencoder：前者从当前与未来图像提取可预测变化，后者把 32 步多组机器人动作压缩为 4 个离散 token；视觉 latent 进入动作解码器，迫使动作编码与可见物理结果一致。", "第二阶段把动作 token 接入 Qwen3.5-4B，并保留 32 个视觉上下文 token 完成语义对齐；第三阶段共同采样 VLM、视频与机器人数据，避免动作能力和通用视觉语言能力彼此覆盖。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-17/2607.11270-overview.png", alt: "Lumo-2 的潜在世界动作模型、语义动作 token 与多类真机能力", caption: "Figure 2 · Lumo-2 的预测、对齐与机器人执行框架。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 2,
    title: "Xiaomi-Robotics-1: A Scalable Vision-Language-Action Model with Wide Robot and Human Data",
    arxivId: "2607.15330",
    url: "https://arxiv.org/abs/2607.15330",
    institutions: ["Xiaomi Robotics"],
    signal: "用超过 10 万小时 UMI 人类操作视频做规模化预训练，再用约 1 万小时机器人数据对齐动作",
    tags: ["Xiaomi-Robotics-1", "UMI Scaling", "Mixture of Transformers"],
    classification: { research: "VLA", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "灵巧手", "夹爪"] },
    resources: [{ label: "项目页", url: "https://robotics.xiaomi.com/xiaomi-robotics-1.html" }],
    motivation: "机器人数据规模有限且成本高，而大量人类第一视角/UMI 数据包含可迁移的操作语义；关键是如何在大模型中把视觉语言知识与连续动作生成分开又协同。",
    methodSummary: "模型采用 Mixture of Transformers：Qwen3-VL 负责语义和选择，DiT action expert 以 flow matching 生成动作；预训练大比例使用 UMI，再以机器人数据后训练。",
    architecture: "提供 2.6B、5.1B、10.5B 三档模型；VLM token 条件化 DiT，但 action-query 的 KV 不回流到 VLM，避免语言头通过动作 token 学到捷径。",
    optimization: "预训练约两周，VLM:UMI 约 1:9；后训练数据比例约 0.5:0.5:0.5:8.5，动作生成使用 5 步 Euler flow integration。",
    data: "预训练含超过 100K 小时 UMI 与 VLM 数据，自动标签由 Qwen3.5-27B 生成；后训练约 10K 小时，含 7.2K 小时自采机器人及 BridgeV2、RT-1、DROID。",
    experiments: "四项 unseen 环境/物体 out-of-box 真机测试验证预训练泛化；四项灵巧下游任务每项少于 10 小时，平均成功率 75%，π0.5 为 40%；RoboCasa365 为 57.4%，RoboDojo 为 20.07。",
    novelty: "相比主要依赖机器人轨迹的 VLA，该工作把 10 万小时 UMI 作为主预训练信号，并在模型规模和数据规模上同时给出缩放结果。",
    strengths: "数据规模、模型缩放、零样本真机和少样本下游实验构成较完整的规模化证据。",
    limitations: "主要数据和训练资源未开放；UMI 自动标签质量与内部真机协议难以独立核验，代码/权重仅声明后续发布。",
    transfer: "可借鉴人类视频先学操作语义、机器人数据再校准本体动作的两阶段配比，以及隔离 action-query KV 的结构设计。",
    experimentDetails: [{ title: "规模化预训练与真机迁移", setup: "三档模型；四项零样本真机、四项少于 10 小时/任务的灵巧后训练；RoboCasa365 与 RoboDojo 公共评测。", comparisons: "不同模型/数据规模、π0.5 与公共基准模型。", results: ["四项灵巧任务平均 75%，π0.5 为 40%。", "RoboCasa365 57.4%，对照 46.6%；RoboDojo 20.07，对照 13.07。", "模型和 UMI 数据同时扩展时指标持续提高，但大规模点主要依赖内部算力与数据。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["2.6B/5.1B/10.5B；Qwen3-VL + DiT MoT；5-step Euler；预训练 VLM:UMI≈1:9；后训练总量约 10K 小时。"], verifiedResources: ["官方项目页和论文公开主要数据规模、混合比例、模型尺寸及真机视频。"], missing: ["代码和 checkpoint 尚处于 will be released 状态；100K 小时数据与完整训练配置未公开。"] },
    deepDive: { lead: "Xiaomi-Robotics-1 重点检验人类 UMI 数据是否能把 VLA 的规模曲线继续向上推。", sections: [{ title: "MoT 与两阶段数据配比", paragraphs: ["VLM 处理图像、语言与高层选择，action DiT 在共享条件下单独生成连续控制。切断 action query 对 VLM 的 KV 写入，防止语言分支偷看动作监督并损害通用表征。", "预训练阶段以 UMI 为绝对多数，让模型先吸收跨场景操作模式；后训练阶段把 7.2K 小时自采机器人数据置于高比例，再混入公开机器人集完成本体对齐。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-17/2607.15330-overview.png", alt: "Xiaomi-Robotics-1 的十万小时 UMI 预训练、模型缩放与真机泛化", caption: "Figure 1 · Xiaomi-Robotics-1 数据与模型规模化总览。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 3,
    title: "Xiaomi-Robotics-U0: An Auto-Regressive Vision-Language Model for Unified Robotics Understanding and Generation",
    arxivId: "2607.11643",
    url: "https://arxiv.org/abs/2607.11643",
    institutions: ["Xiaomi Robotics"],
    signal: "用 38B 自回归模型统一图像、场景与具身数据生成，并用合成数据提升真实机器人策略",
    tags: ["Unified Generation", "FlashAR+", "Synthetic Robot Data"],
    classification: { research: "WAM", training: "Pre-training", data: "合成 / 仿真数据", platforms: ["机械臂", "Humanoid", "夹爪"] },
    resources: [{ label: "项目页", url: "https://robotics.xiaomi.com/xiaomi-robotics-u0.html" }],
    motivation: "具身模型需要同时理解场景、预测未来并生成训练数据，但分离的 VLM、视频和图像生成器难以共享知识，标准自回归图像生成又过慢。",
    methodSummary: "U0 将文本、图像、视频和机器人场景编码到统一离散词表，以 next-token prediction 训练；FlashAR+ 在推理时沿反对角线并行生成视觉 token。",
    architecture: "38B 多模态 AR 主干源于 EMU3.5/Qwen3-32B，IBQ 提供统一视觉 tokenizer；FlashAR+ 加入水平/垂直门控融合，vLLM 执行并行解码。",
    optimization: "共同训练 T2I/X2I、场景生成、具身迁移和视频目标，同时保留通用视觉数据防止灾难性遗忘。",
    data: "机器人数据含 AgiBotWorld Beta、Open X-Embodiment、InternData-A1、GenieSim、RoboCOIN、RoboMIND 与自采数据，并混合通用图文/视频。",
    experiments: "300 样本具身迁移 benchmark（150 easy/150 hard）中优于 GPT-Image-2；1024 图像生成从标准 AR 的 450.77 秒降到 FlashAR+ 16.56 秒、vLLM 5.44 秒。合成数据使 π0.5 真机 OOD 从 36.9% 到 63.2%。",
    novelty: "相对只为机器人生成视频的 world model，U0 统一了通用视觉生成与具身场景迁移；FlashAR+ 直接缓解大 AR 模型生成训练样本的吞吐瓶颈。",
    strengths: "统一模型、推理加速、人工评测与合成数据下游真机收益形成闭环。",
    limitations: "38B 成本很高；300 样本评测和合成数据收益依赖内部协议，且对动作策略的提升是通过数据生成间接体现。",
    transfer: "适合将大生成模型作为离线数据引擎，批量改变物体、背景和布局，再用真实策略评测合成数据是否有效。",
    experimentDetails: [{ title: "生成效率与策略数据增强", setup: "300 条具身迁移样本；1024 分辨率速度测试；将生成数据加入 π0.5 后做真实 OOD 评测。", comparisons: "GPT-Image-2、标准 AR、FlashAR+、vLLM，以及不使用合成数据的 π0.5。", results: ["标准 AR 450.77 秒，FlashAR+ 16.56 秒，vLLM 5.44 秒。", "具身迁移 benchmark 中整体优于 GPT-Image-2，原文按 easy/hard 分组展示。", "π0.5 真机 OOD 从 36.9% 提升至 63.2%，说明生成质量至少在该协议下能转化为控制收益。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["38B AR；IBQ tokenizer；FlashAR+ 反对角并行；H/V gated fusion；vLLM。"], verifiedResources: ["官方项目页已提供代码/模型入口及论文演示。"], missing: ["完整训练数据、300 样本人工评测细则与机器人合成数据配比未完全披露。"] },
    deepDive: { lead: "U0 的直接产物不是动作，而是可用于机器人理解、模拟和策略训练的视觉 token。", sections: [{ title: "统一词表与并行解码", paragraphs: ["IBQ 把不同视觉任务映射到同一离散词表，模型因此可用标准 next-token prediction 学习条件图像、视频和场景变化。通用视觉样本持续混入训练，用于保留开放世界生成能力。", "FlashAR+ 不再逐 token 串行扫描二维网格，而是沿反对角线并行预测；水平与垂直门控汇合已生成上下文，vLLM 再将工程吞吐压到约 5.44 秒。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-17/2607.11643-overview.png", alt: "Xiaomi-Robotics-U0 的标准自回归与 FlashAR+ 并行视觉 token 解码", caption: "Figure 3 · U0 的 next-token prediction 与 FlashAR+ 推理。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 4,
    title: "Semantic Anchoring for Robotic Action Representations",
    arxivId: "2607.13597",
    url: "https://arxiv.org/abs/2607.13597",
    institutions: ["Peking University", "Eastern Institute of Technology, Ningbo", "Shanghai Jiao Tong University"],
    signal: "只在训练期将动作 token 对齐到人类手部语义，推理时不增加额外模块",
    tags: ["Semantic Action", "Disentanglement", "Ego Hand-Object"],
    classification: { research: "表征学习", training: "Post-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://xy02-05.github.io/SemanticMN" }],
    motivation: "VLA 中间动作 token 常被端到端损失塑造成难解释的本体相关表示，跨视角和跨场景时缺少稳定语义锚点。",
    methodSummary: "训练时把中层动作表示分为共享与私有分量，共享分量用 InfoNCE 对齐冻结的 EgoHOD 文本编码器，同时用重建与去相关约束避免信息丢失。",
    architecture: "辅助模块含 shared/private encoder、decoder 与冻结 VL encoder；只训练期使用，部署时丢弃，因此不改变原 VLA 推理图。",
    optimization: "总损失由 action、alignment、reconstruction 和 difference 四项组成；分别在 π0、SpatialVLA 等主干后训练。",
    data: "仿真覆盖 LIBERO 与 SIMPLER；真实使用 AgileX Cobot Magic V2，四类任务每类 200 demos，并评测 ID/OOD。",
    experiments: "LIBERO π0 从 89.3 到 92.4；SIMPLER π0 从 35.4 到 41.7，SpatialVLA 从 43.8 到 51.0。真机 20 trials/任务，ID 51.3→70.0、OOD 49.5→71.0。",
    novelty: "相对直接用文本监督动作输出，该方法只对中间共享子空间做语义对齐，并保留 private 子空间承载本体细节；推理成本不增加。",
    strengths: "多 backbone、仿真、真机 ID/OOD、目标层位置和共享/私有分解均有消融。",
    limitations: "收益依赖 EgoHOD 文本表征是否覆盖机器人动作；语义相似不一定意味着动力学可迁移。",
    transfer: "可用于把人类视频语义注入 VLA 中层表示，同时让低层本体差异留在 private branch。",
    experimentDetails: [{ title: "语义对齐与真机 OOD", setup: "LIBERO、SIMPLER；AgileX Cobot Magic V2 四类任务，每类 200 demos、20 次 ID/OOD 测试。", comparisons: "π0、SpatialVLA 原模型与 shared/private、encoder target、对齐层位置消融。", results: ["LIBERO 89.3→92.4；SIMPLER π0 35.4→41.7，SpatialVLA 43.8→51.0。", "真机 ID 51.3→70.0，OOD 49.5→71.0。", "仅 alignment 从 43.8 到 49.0，加入共享/私有分解后到 51.0，说明两部分均有贡献。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["mid-layer action token；shared/private encoder；frozen EgoHOD text encoder；InfoNCE + reconstruction + decorrelation。"], verifiedResources: ["项目页提供论文与视频；正文披露每任务 demos、trial 数和损失权重。"], missing: ["完整代码、EgoHOD 对齐数据与 checkpoint 尚未确认公开。"] },
    deepDive: { lead: "Semantic Anchoring 在训练时为动作表征增加一个语义坐标系。", sections: [{ title: "共享与私有动作空间", paragraphs: ["中层 action token 被编码成共享 zˢ 与私有 zᵖ。zˢ 对齐冻结的人类手部语义表示，zᵖ 保留机器人本体与控制细节；decoder 重建原 action token，去相关损失抑制两部分重复编码。", "辅助网络训练完成后全部移除，原 VLA 只保留已被塑形的中层表征，因此提升不来自更慢的推理或额外视觉输入。"] }], equations: [{ name: "联合训练目标", expression: "Ltotal = Laction + λalign Lalign + 0.01 Lrecon + 0.075 Ldiff", explanation: "动作损失维持控制能力，对齐损失注入语义，重建与差异损失约束共享/私有分解。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-17/2607.13597-overview.png", alt: "Semantic Anchoring 将 VLA 中层动作 token 分成共享与私有表示并做语义对齐", caption: "Figure 3 · Semantic Anchoring 训练期辅助结构。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 5,
    title: "EDAR: Environment-Dependent Action Representation for Vision-Language-Action Models",
    arxivId: "2607.11427",
    url: "https://arxiv.org/abs/2607.11427",
    institutions: ["Fudan University", "TeleAI, China Telecom"],
    signal: "用当前视觉上下文与未来视觉特征共同塑造动作 latent，让同一动作在不同环境中保留不同后果",
    tags: ["Action Representation", "Future Visual Features", "Latent Flow"],
    classification: { research: "表征学习", training: "Pre-training", modalities: ["State / Proprioception"], platforms: ["机械臂", "夹爪"] },
    motivation: "只从动作序列压缩 latent 会忽略环境：相同关节位移在不同物体、接触和遮挡下可能产生完全不同的结果。",
    methodSummary: "EDAR 把动作 chunk、当前多视角 DINOv3 特征和 register tokens 一起编码；decoder 同时重建动作与未来视觉特征，再在 latent 空间训练 flow-matching policy。",
    architecture: "8 层 encoder/decoder、hidden 512、8 heads、4 个 latent tokens；动作与视觉使用专用 FFN，但共享 self-attention 建模交互。",
    optimization: "先训练环境依赖 action autoencoder，再冻结/复用 latent 表示训练下游 VLA flow policy；真实策略 100K steps、batch 64、chunk 20。",
    data: "LIBERO、CALVIN、MetaWorld；真实预训练混合 10/15/20 Hz Open X-Embodiment 与自采遥操作数据，另评测四项长时任务。",
    experiments: "LIBERO SmolVLA 87.3→91.8、Long 71.0→80.6，π0 94.2→97.1；CALVIN 平均长度 3.34→3.80，MetaWorld 69.3→80.5，并有真实四任务增益。",
    novelty: "相对 action-only tokenizer，EDAR 让 latent 既能重建动作，也要预测对应环境变化；未来视觉目标是表征监督，不在部署时增加生成器。",
    strengths: "跨三基准、多个 VLA 主干、真实长时任务与组件消融均有一致提升。",
    limitations: "未来 DINO 特征仍可能偏向视觉可见变化，接触力等不可见后果未被显式建模；完整代码未确认。",
    transfer: "可把 action tokenizer 的训练目标从动作重建扩展为动作+未来交互特征联合重建。",
    experimentDetails: [{ title: "动作表征跨基准评测", setup: "LIBERO、CALVIN、MetaWorld；真实四项长时操作，策略统一训练 100K steps。", comparisons: "SmolVLA、π0 原模型，action-only autoencoder，以及去掉环境上下文/未来预测/专用 decoder 的消融。", results: ["LIBERO SmolVLA 87.3→91.8，Long 71.0→80.6；π0 94.2→97.1。", "CALVIN 平均长度 3.34→3.80，FLOWER 复现 4.58→4.75；MetaWorld 69.3→80.5。", "去掉环境上下文约 −0.9、去掉未来预测 −1.7、单 decoder −1.6，支持双目标结构。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["8-layer encoder/decoder；hidden 512；8 heads；K=4 latent tokens；DINOv3 visual tokens；100K policy steps；batch 64；chunk 20。"], verifiedResources: ["论文披露网络尺寸、频率混合、训练步数与主要消融。"], missing: ["代码、预训练权重、自采数据和真实逐任务计数尚未确认公开。"] },
    deepDive: { lead: "EDAR 让动作表示回答的不只是‘机器人怎么动’，还包括‘在当前场景会发生什么’。", sections: [{ title: "环境条件动作自编码", paragraphs: ["动作 chunk A、当前视觉 X 和 register R 经过共享 attention 得到少量 latent Z；decoder 一路重建动作，另一路预测未来视觉特征。专用 FFN 防止两个目标完全共享参数，attention 则保留动作—环境交互。", "下游策略不再直接回归高维动作，而是在 EDAR latent 上做 flow matching，最后由 action decoder 还原控制序列；未来特征只在训练期提供结构监督。"] }], equations: [{ name: "双目标表征学习", expression: "Z = f([A; R; X])；L = Lact + λ Leff", explanation: "Lact 重建动作，Leff 预测未来环境特征，两者共同约束环境依赖 latent。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-17/2607.11427-overview.png", alt: "EDAR 的环境依赖 action encoder、未来视觉目标和专用双解码器", caption: "Figure 2 · EDAR 环境依赖动作表征结构。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 6,
    title: "FlowWAM: Leveraging Optical Flow for World-Action Model Pre-training",
    arxivId: "2607.13017",
    url: "https://arxiv.org/abs/2607.13017",
    institutions: ["CAS NLPR", "University of Chinese Academy of Sciences", "FiveAges", "MBZUAI", "Alibaba Group"],
    signal: "把光流作为比 RGB 更直接的运动监督，用无动作视频预训练 world-action model",
    tags: ["Optical Flow", "Ego Video", "World-Action Model"],
    classification: { research: "WAM", training: "Pre-training", modalities: ["其他模态"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://flow-wam.github.io" }],
    motivation: "RGB 视频预测需要同时建模外观和运动，容易把容量耗在纹理；无动作人类视频中的光流则直接提供可迁移运动先验。",
    methodSummary: "FlowWAM 使用 RGB 与 optical-flow 双流 DiT，共享冻结 VAE/DiT 表征；先在 EgoDex 无动作视频上学 flow，再与机器人动作 expert 联合微调。",
    architecture: "RGB/flow patch 分支通过 joint self-attention 融合；action expert 读取隐藏状态并用 flow matching 生成动作。推理可选择 policy mode 或只生成 flow 的 world-model mode。",
    optimization: "Stage 1 在 action-unlabeled 视频上预训练双流；Stage 2 加入机器人数据与 action expert 联合训练，并用 motion reweighting 与噪声增强避免静态流主导。",
    data: "EgoDex 人类第一视角视频，加 RoboTwin、WorldArena 机器人数据；真实 Franka/ARX 七项任务每项 100 demos。",
    experiments: "RoboTwin 50 任务、每任务 100 rollouts：clean 92.94、random 92.14；WorldArena EWMScore 63.71、trajectory 64.26；真机七任务平均 75.7%，π0.5 61.4、Motus 57.1。",
    novelty: "相比纯 RGB world model，FlowWAM 把光流设为显式生成目标；flow error 与任务成功率相关系数 −0.81，提供了运动预测与控制性能关联的直接证据。",
    strengths: "50 任务仿真、世界模型指标、七项真机、光流形式与训练技巧消融都较完整。",
    limitations: "依赖外部光流估计质量；光流不表达接触力和被遮挡物体状态，相关性也不等同于因果贡献。",
    transfer: "可用 flow 作为人类视频到机器人动作的中间监督，并用 flow error 选择更值得保留的预训练片段。",
    experimentDetails: [{ title: "光流预训练与真实操作", setup: "RoboTwin 50 任务，每任务 clean/random 数据并各测试 100 次；WorldArena；Franka/ARX 七任务、100 demos/任务、10 trials/任务。", comparisons: "π0.5、Motus、纯 RGB/数值动作/原始 UV flow 以及 reweighting/noise 消融。", results: ["RoboTwin clean 92.94、random 92.14；WorldArena EWMScore 63.71、trajectory 64.26。", "真机平均 75.7%，π0.5 61.4、Motus 57.1。", "消融中 numeric action 69.8、raw UV 72.3、无 reweight 83.9、无 noise 82.1、full 89.8；flow error 与成功率 r=−0.81。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["RGB/flow 双流共享 VAE 与 DiT；joint self-attention；flow-matching action expert；两阶段训练。"], verifiedResources: ["项目页提供论文和视频；正文给出真机 demos/trials、RoboTwin rollout 数与关键消融。"], missing: ["完整代码、checkpoint 和各数据源采样权重尚未确认公开。"] },
    deepDive: { lead: "FlowWAM 将视频中的运动场作为世界模型与动作策略之间的共享语言。", sections: [{ title: "双流世界—动作模型", paragraphs: ["RGB 分支保留物体与场景语义，flow 分支强调相邻帧运动；两者在 joint self-attention 中交换信息。无动作视频阶段不启用 action expert，模型只学习可预测运动。", "加入机器人数据后，action expert 从同一隐藏状态生成连续动作。motion reweighting 降低大面积静态区域权重，噪声增强避免模型只复制外部 optical-flow estimator 的局部偏差。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-17/2607.13017-overview.png", alt: "FlowWAM 的 RGB 与光流双流 DiT、两阶段训练和双模式推理", caption: "Figure 2 · FlowWAM 双流 world-action model。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 7,
    title: "ExToken: Structured Exploration via Experience Tokens for Robot Reinforcement Learning",
    arxivId: "2607.12931",
    url: "https://arxiv.org/abs/2607.12931",
    institutions: ["Nanyang Technological University", "ACE Robotics", "Zhejiang University", "Sun Yat-sen University"],
    signal: "把示范行为聚类成 experience tokens，用 token 条件探索替代逐动作随机扰动",
    tags: ["Experience Token", "Structured Exploration", "Robot RL"],
    classification: { research: "VLA", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    motivation: "VLA 在线 RL 若直接在连续动作或噪声上探索，样本效率低且容易产生不可执行轨迹；示范中已经存在可复用的行为模式。",
    methodSummary: "先聚类示范视频嵌入得到 K 个 experience tokens，用 token-conditioned SFT 热启动；在线阶段均匀采样 token 探索，再用 SigLIP selector 根据 episode return 学会选 token。",
    architecture: "共享 VLA 接收视觉、语言和 token 条件；selector 是 SigLIP + MLP，训练用 REINFORCE，部署对 token 概率取 argmax。",
    optimization: "LIBERO 在 OpenVLA-OFT 上结合 GRPO；真实任务以 π0.5/EvoRL 初始化，采用人机协同 rollout，每任务每轮仅 20 条。",
    data: "示范视频先做 embedding clustering；LIBERO 每 RL step 最多 512 rollouts，真实四项任务包含原始与多种 OOD 条件。",
    experiments: "LIBERO 平均 98.2%，RLinf 96.8；Long 97.8% 对 95.2%。真实四任务原始设置为 95/95/90/90%，跨 OOD 平均比 EvoRL 高 6.25 个百分点。",
    novelty: "相对高斯动作噪声或无条件生成多轨迹，ExToken 在行为模式层面探索，并学习观察到 token 的选择器。",
    strengths: "仿真 rollout 预算、token 数量、样本数和真实 OOD 均有消融，能区分结构化探索与单纯增加采样。",
    limitations: "真实实验每格仅 20 次，selector 的回报方差较高；离线聚类得到的固定 token 难覆盖训练后出现的新策略模式。",
    transfer: "可把动作 chunk 或技能原型离散成条件 token，在在线阶段探索技能组合而非每个关节噪声。",
    experimentDetails: [{ title: "结构化探索的样本效率", setup: "LIBERO：K=6、512 rollouts/step、100 steps；真实四任务、原始与 OOD，每格 20 trials，每轮 20 rollouts/任务。", comparisons: "RLinf、EvoRL、不同 token 数 K 与 128/256/512 rollout 预算。", results: ["LIBERO 平均 98.2%，RLinf 96.8；Long 97.8% 对 95.2%。", "真实原始条件四任务 95%/95%/90%/90%，跨设置平均比 EvoRL 高 6.25 个百分点。", "256 rollouts 可达 93.4%，128 不稳定；K=3/6 较稳，K=10 下降。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["示范 embedding clustering；K=6 默认；token-conditioned SFT；SigLIP+MLP selector；REINFORCE；部署 argmax。"], verifiedResources: ["论文披露 rollout 预算、token 数、真实每格 trials 和主要训练流程。"], missing: ["代码、真实任务数据和 HIL 操作协议尚未确认公开。"] },
    deepDive: { lead: "ExToken 将探索单位从单个动作变化提升到示范中出现过的行为模式。", sections: [{ title: "Token 形成、探索与选择", paragraphs: ["示范视频特征先聚类为 c₁…cK，token-conditioned SFT 让一个 VLA 学会在相同任务下产生不同但可执行的轨迹模式。在线初期均匀采样 token，以保持模式覆盖。", "episode return 再训练 selector p(c|o,l)；部署时 selector 根据当前视觉与语言选择单个 token，VLA 不再需要大量并行采样。"] }], equations: [{ name: "Selector 策略梯度", expression: "∇φ J = E[(R−b) ∇φ log pφ(c|o,l)]", explanation: "完整 episode 回报 R 更新 token 选择概率，b 是降低方差的基线。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-17/2607.12931-overview.png", alt: "ExToken 从示范聚类、token 条件探索到在线 token selector 的流程", caption: "Figure 2 · ExToken 结构化探索与 token 选择。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 8,
    title: "DenseReward: Automated Dense Reward Learning from Robot Successes and Failures",
    arxivId: "2607.13033",
    url: "https://arxiv.org/abs/2607.13033",
    institutions: ["University of North Carolina at Chapel Hill", "Carnegie Mellon University", "Shanghai Jiao Tong University", "Amazon AWS AI"],
    signal: "用成功与六类失败轨迹训练逐帧奖励模型，并把稠密反馈用于仿真与少量真机强化学习",
    tags: ["Dense Reward", "Failure Data", "Vision-Language Reward Model"],
    classification: { research: "VLA", training: "RL", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://dense-reward.github.io" }],
    motivation: "机器人 RL 常只有 episode 成败，难定位哪一步开始偏离；只用成功视频训练的 reward model 又不认识碰撞、漏抓等失败模式。",
    methodSummary: "自动生成阶段标签与六类失败轨迹，微调 Qwen3-VL-4B 为每帧输出奖励；模型默认查看当前帧和两帧历史，再用于 PPO 或冻结策略的噪声引导。",
    architecture: "Qwen3-VL-4B 接收任务指令与短视觉历史，输出 [0,1] 标量；下游仿真直接作 dense reward，真机 DSRL 用该分数选择/调整 π0 采样噪声。",
    optimization: "先监督微调奖励模型，再在 LIBERO 用 PPO；真机只更新采样/搜索过程而冻结 π0 策略主体。",
    data: "约 27K episodes，含 DROID 真实成功/失败、RoboSuite、Isaac 与 60+ 物体；失败数据覆盖碰撞、漏抓、错误目标等六类模式。",
    experiments: "奖励预测 MAE 0.081，RoboReward-8B 为 0.230；去掉失败数据 MAE 退化到 0.1312。真机杯子堆叠 40%→80%，球入篮 30%→70%，但评测仅各 10 次。",
    novelty: "相对只看成功轨迹或整段二值标签，DenseReward 显式收集失败类型并输出逐时间步分数，让策略能获得偏离发生位置。",
    strengths: "失败数据消融、跨仿真来源、稠密分数误差和真机下游收益都直接对应设计目标。",
    limitations: "真机统计只有 10 次评测，奖励模型可能被视觉相似但因果不同的状态欺骗；未证明对开放世界语言任务稳定。",
    transfer: "可把失败模式数据单独建设为 reward-model 训练集，用短历史判断接触过程而非只对单帧打分。",
    experimentDetails: [{ title: "奖励准确性与下游 RL", setup: "27K episodes 奖励学习；LIBERO PPO；真实 DROID/Franka + Robotiq + ZED，杯子堆叠与球入篮，各 10 次评测。", comparisons: "RoboReward-8B、去掉失败数据、不同历史帧数，以及不使用 DSRL 的冻结 π0。", results: ["MAE 0.081，RoboReward-8B 0.230。", "移除失败数据后 MAE 从 0.0809 退化到 0.1312，说明负例不是可有可无。", "真机杯子堆叠 40%→80%，球入篮 30%→70%；但每项只有 10 trials，应谨慎看待幅度。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["Qwen3-VL-4B；当前帧 + 两帧历史；六类失败；逐帧 [0,1] 奖励；PPO 与 DSRL 两种下游。"], verifiedResources: ["项目页声明将发布数据、模型和评测套件；论文给出 27K 规模、MAE 与真机协议。"], missing: ["当前可下载资源完整度需以项目页发布状态为准；真机训练 rollout 总量较小。"] },
    deepDive: { lead: "DenseReward 关注的不是给成功轨迹更高分，而是让模型看懂失败从哪一帧开始。", sections: [{ title: "失败覆盖与短历史奖励", paragraphs: ["自动数据管线按任务阶段生成中间进度，并注入碰撞、漏抓、抓错目标等六类失败。真实 DROID 与仿真来源共同训练，使 reward model 同时见过自然失败和可控合成失败。", "两帧历史让模型区分静态外观相近但过程不同的状态，例如物体刚被碰落或正在稳定抓取。真机 DSRL 不改 π0 参数，而用分数引导采样，因此测试的是奖励是否能选出更好的动作候选。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-17/2607.13033-overview.png", alt: "DenseReward 的失败数据自动生成、逐帧奖励预测与下游强化学习", caption: "Figure 1 · DenseReward 数据与策略优化流程。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 9,
    title: "Mixture of Frames Policy for Multi-Frame Robot Manipulation",
    arxivId: "2607.11884",
    url: "https://arxiv.org/abs/2607.11884",
    institutions: ["Stanford University"],
    signal: "在扩散去噪每一步同步融合多个坐标系的动作专家，避免提前选错参考系",
    tags: ["Coordinate Frames", "Diffusion Policy", "Bimanual Manipulation"],
    classification: { research: "VLA", training: "BC", modalities: ["State / Proprioception"], platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://mofpo.github.io" }],
    motivation: "双臂和物体交互可能更适合左臂、右臂、基座或相对坐标；固定单一坐标系会让某些任务简单、另一些任务困难，先验选择又容易失误。",
    methodSummary: "MoF 在同一条 canonical noisy trajectory 上运行多个 frame expert，每个去噪步先将噪声和预测严格变换到各坐标系，再由 router 融合后返回 canonical frame。",
    architecture: "共享 observation encoder 与多个 frame-conditioned diffusion experts；router 输出逐步权重。动作旋转采用 column 6D 表示，以便对带噪旋转做精确坐标变换。",
    optimization: "行为克隆训练同步多 frame denoising；论文比较预先选 frame、输出后混合以及在去噪过程逐步融合。",
    data: "九项仿真双臂任务，每项 100 demos；真实 HoMMI 倒液体 257 demos、上菜 177 demos。",
    experiments: "仿真平均 66.8%，Oracle frame 63.8、MoE-DP 55.1、DP 50.3。真机倒液 85%，单 frame 为 15/70/5%；上菜 70%，单 frame 为 55/0/60%。",
    novelty: "相比训练多个策略再在最终动作处加权，MoF 在每个 diffusion step 将专家预测统一到同一 noisy trajectory，保持不同坐标系输出的概率一致性。",
    strengths: "九项任务、oracle frame、多个融合位置消融与两项真实双臂任务都直接检验坐标系假设。",
    limitations: "需要预定义候选坐标系和可靠位姿变换；专家数量随相关 frame 增长，遮挡或标定误差会破坏融合。",
    transfer: "适合多臂、工具或物体中心控制，将 reference frame 作为专家而不是硬编码为唯一动作表示。",
    experimentDetails: [{ title: "多坐标系仿真与双臂真机", setup: "九项仿真任务、100 demos/项、3 seeds、5 checkpoints×50 episodes；HoMMI 倒液 257 demos、上菜 177 demos，各 20 trials。", comparisons: "DP、MoE-DP、手工 Oracle frame、左/右/相对单 frame 与结构消融。", results: ["仿真 MoF 66.8%，Oracle 63.8、MoE-DP 55.1、DP 50.3。", "倒液 MoF 85%，Left 15%、Right 70%、Relative 5%。", "上菜 MoF 70%，Left 55%、Right 0%、Relative 60%；移除旋转正交化会使集成明显退化。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["canonical noisy trajectory；逐 diffusion step frame transform；column 6D rotation；router 加权专家噪声。"], verifiedResources: ["项目页提供论文和演示；正文披露 demos、seeds、checkpoint 与 trial 数。"], missing: ["代码、HoMMI 数据与完整标定配置尚未确认公开。"] },
    deepDive: { lead: "MoF 的关键是多个 frame expert 始终在同一随机变量上协作。", sections: [{ title: "同步多坐标系去噪", paragraphs: ["初始噪声轨迹定义在 canonical frame。对每个 denoising step，系统把同一 noisy action 变换到左臂、右臂、相对或基座坐标，让各 expert 预测对应噪声，再逆变换回 canonical frame 加权。", "如果只在最终动作处混合，各专家实际上沿不同噪声轨迹采样，平均结果不再对应合法 diffusion posterior。column 6D rotation 使带噪姿态也能在 frame 间精确变换。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-17/2607.11884-overview.jpg", alt: "Mixture of Frames 在扩散每一步变换多个坐标系专家并融合噪声预测", caption: "Figure 2 · Mixture of Frames Policy 架构。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 10,
    title: "See like a Robot: Robot-Centric Pointmaps for Robust Manipulation",
    arxivId: "2607.11498",
    url: "https://arxiv.org/abs/2607.11498",
    institutions: ["KAIST AI", "Holiday Robotics"],
    signal: "把 RGB-D 转成机器人坐标系 pointmap，用显式 3D 几何提升跨相机视角的操作稳定性",
    tags: ["Robot-centric Pointmap", "RGB-D", "Camera Generalization"],
    classification: { research: "表征学习", training: "Post-training", modalities: ["Depth / RGB-D", "Point Cloud / 3D"], platforms: ["机械臂", "夹爪"] },
    motivation: "RGB 策略容易把固定相机视角当作空间坐标；点云虽保留 3D，却常需更换成熟视觉 backbone 或稀疏化表示。",
    methodSummary: "将 RGB-D 每像素反投影到机器人基座坐标，并构成 XYZ 三通道 pointmap；单独的 SigLIP 分支编码 pointmap，再与 RGB token 逐元素相加。",
    architecture: "RGB 与 pointmap 使用两个同构 SigLIP encoder，pointmap encoder 从 RGB 权重初始化；无需点云采样器，保持 2D 网格以复用预训练视觉结构。",
    optimization: "在 π0.5 与 SmolVLA 上做后训练；真实 π0.5 训练 20K steps，20 Hz 执行 20-step chunk 中前 10 步。",
    data: "RoboCasa 24 任务、每项 50 demos；真实 Franka 四任务，在三个外部相机位置各 15 demos，共 180 demos，并测试 seen/unseen view。",
    experiments: "RoboCasa π0.5 55.3→62.9、SmolVLA 37.2→41.4；真实 seen 73.3→78.3，unseen 55.0→66.7，DP3 unseen 为 48.3。",
    novelty: "相对 RGB-only VLA 或独立点云网络，该方法把机器人中心 3D 坐标编码为图像网格，直接复用 2D foundation encoder 并保持像素对应。",
    strengths: "公共仿真、两种 VLA、相机视角 OOD 和真实 seen/unseen 计数都围绕几何表征展开。",
    limitations: "需要深度与外参标定；未测试相机数量、视野和标定误差大幅变化，PointVLA/KYC 对照为作者复现。",
    transfer: "可为现有 RGB VLA 增加轻量 pointmap 分支，在不改动作头的情况下显式注入 robot-frame 几何。",
    experimentDetails: [{ title: "跨视角几何泛化", setup: "RoboCasa 24 任务、50 demos/项、50 episodes；Franka 四任务、3 个训练相机位置、15 demos/任务/位置，共 180，seen/unseen 各 15 次。", comparisons: "π0.5、SmolVLA 原模型、DP3、KYC 与 PointVLA 作者复现。", results: ["RoboCasa：π0.5 55.3→62.9，SmolVLA 37.2→41.4。", "真机 seen 73.3→78.3，unseen 55.0→66.7；DP3 unseen 48.3。", "OOD 增益高于 seen 增益，支持 robot-centric 几何主要缓解相机视角变化。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["RGB-D 反投影到 robot frame；XYZ pointmap；独立 SigLIP、从 RGB 权重初始化；token element-wise add；20K steps；20 Hz。"], verifiedResources: ["论文披露 demos、相机位置、评测次数与训练/执行 chunk。"], missing: ["代码、真实数据、相机标定文件和官方项目页尚未确认。"] },
    deepDive: { lead: "Pointmap 在不放弃二维预训练 backbone 的情况下，给每个像素补上机器人坐标。", sections: [{ title: "二维网格中的三维位置", paragraphs: ["深度图与相机内外参将每个像素转换为机器人基座坐标 (x,y,z)，三通道仍按原图像网格排列，因此遮挡关系和 RGB 对应不会丢失。", "pointmap 走独立 SigLIP encoder，避免坐标数值直接污染 RGB 特征；两路 token 按位置相加后交给原 VLA，动作头和推理接口保持不变。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-17/2607.11498-overview.png", alt: "不同相机视角的 depth、point cloud 与机器人中心 pointmap 对比", caption: "Figure 1 · Robot-centric pointmap 保留视角变化下的统一几何。图片截取自 arXiv 原论文。" }],
  },
];

const selectedPaperIds20260717 = [
  "2607.11270", "2607.15330", "2607.11643", "2607.13597", "2607.11427", "2607.13017",
  "2607.12931", "2607.13033", "2607.11884", "2607.11498", "2607.15275", "2607.14236", "2607.14609",
];

const paperPool20260717 = [...paperCandidates20260717, ...paperDaily20260717Additions];

export const paperDaily20260717: Paper[] = selectedPaperIds20260717.map((paperId, index) => {
  const paper = paperPool20260717.find((candidate) => candidate.arxivId === paperId);
  if (!paper) throw new Error(`Missing selected paper: ${paperId}`);
  return { ...paper, rank: index + 1 };
});
