import type { Paper, PaperEquation } from "./site-data";

type Entry = Omit<
  Paper,
  "rank" | "figures" | "optimization" | "experimentDetails" | "reproducibilityDetails" | "deepDive"
> & {
  figureFile: string;
  figureAlt: string;
  figureCaption: string;
  technique: string[];
  evaluation: string[];
  comparison: string;
  reproducibilityStatus: "资源较完整" | "部分可复现" | "信息不足";
  implementation: string[];
  missing: string[];
  equations?: PaperEquation[];
};

const makePaper = (entry: Entry, index: number): Paper => ({
  ...entry,
  rank: index + 1,
  optimization: entry.technique.join("；"),
  experimentDetails: [{ title: "原文实验与消融", setup: entry.experiments, comparisons: entry.comparison, results: entry.evaluation }],
  reproducibilityDetails: {
    status: entry.reproducibilityStatus,
    verifiedResources: entry.resources?.map((resource) => `${resource.label}: ${resource.url}`) ?? ["arXiv 论文正文"],
    implementation: entry.implementation,
    missing: entry.missing,
  },
  deepDive: {
    lead: entry.methodSummary ?? entry.signal,
    sections: [{ title: "方法与模型改进", paragraphs: entry.technique }],
    equations: entry.equations,
    experimentReading: entry.evaluation,
    reflections: [entry.transfer],
  },
  figures: [{ src: `/report-assets/2026-09-07/${entry.figureFile}`, alt: entry.figureAlt, caption: entry.figureCaption }],
});

const entries: Entry[] = [
  {
    title: "TacPAC: Tactile Prediction and Real-Time Action Correction in World-Action Models for Contact-Rich Manipulation",
    arxivId: "2609.05266",
    url: "https://arxiv.org/abs/2609.05266",
    institutions: ["Fudan University", "Shanghai Innovation Institute", "NeoteAI"],
    signal: "把世界模型预测的未来触觉缓存为“预期接触”，执行中用新触觉与预期对照，只修正动作块尚未执行的后缀。",
    tags: ["Tactile", "WAM", "Real-time Correction"],
    classification: { research: "WAM", training: "Post-training", modalities: ["Tactile"], platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "GitHub", url: "https://github.com/LogosRoboticsGroup/TacPAC" }],
    motivation: "只预测未来触觉能告诉模型计划会产生什么接触，却不能利用执行中才到达的触觉反馈；每次重新生成完整动作块又太慢。",
    methodSummary: "TacPAC 在基础 WAM 规划后缓存触觉预测和计划表征，轻量 tactile expert 每次读取当前触觉与该 cache，对未执行动作计算替代式校正。",
    architecture: "视频专家联合生成视觉/触觉未来和动作块；触觉专家跨注意力读取层级 cache、当前双指触觉与已执行前缀，异步写回剩余动作。",
    data: "Flexiv Rizon 4、两枚 InTac S1、腕部 D405 与第三视角 D435i；五项真机任务覆盖插头/扩展卡插入、脆物搬运、重定向和长时多物体转移。",
    experiments: "每种方法每任务 20 次，共同比较视觉 VLA、视触觉策略、视觉 WAM、触觉 WAM 与 T-Rex；逐项去除触觉预测、expert 和 cache。",
    novelty: "平均成功率从视觉 WAM 的 22% 提至 64%，比最强基线 T-Rex 的 48% 高 16 点；单次校正 30.4 ms，比重规划低 20.7×。",
    strengths: "五项真机均领先，任务同时含精密、易碎和长时接触；组件消融直接回答预测、当前触觉和 cache 各自作用。",
    limitations: "单一机械臂与触觉传感器组合；base WAM 与 tactile expert 分两阶段训练，传感器标定和跨设备迁移尚未验证。",
    transfer: "接触闭环不只需要“看见触觉”，还要把实测反馈与计划中的预期接触对齐，并限制修正只作用于未执行动作。",
    technique: [
      "基础 WAM 规划时保存各层触觉预测和动作表征；执行中 tactile expert 以当前触觉为查询、cache 为参照，生成剩余动作增量。",
      "每轮修正都相对原始计划而非上一次修正累加，已执行前缀仅作为条件；这样可抑制一次异常触觉导致的误差传播。",
    ],
    equations: [],
    evaluation: [
      "TacPAC 在五任务平均 64%，T-Rex 48%、Dream-Tac 45%、π0.5 36%、LingBot-VA 28%、视觉 WAM 22%；插头插入为 80% 对最佳基线 65%。",
      "只加触觉预测为 37%，完整系统为 64%；堵住 cache 后也明显退化，说明执行期校正必须知道原计划预期了什么。",
      "30.4 ms 对应 32.9 Hz；仅 1.6% tactile-expert 调用期间机器人推进了控制步，论文未观察到校正引发的 jerk。",
    ],
    comparison: "π0.5、ACT、VITaL、LingBot-VA、Dream-Tac、T-Rex，以及无预测/无 expert/无 cache 的成组消融。",
    reproducibilityStatus: "资源较完整",
    implementation: ["代码已公开；附录给出模型、flow 时间表、两阶段训练、相机/触觉硬件、20 次/任务和严格 trial accounting。"],
    missing: ["训练数据与完整权重开放范围仍需核对；尚无跨触觉硬件或双臂验证。"],
    figureFile: "2609.05266-fig2.png",
    figureAlt: "TacPAC 缓存预期触觉并在执行中修正剩余动作的结构",
    figureCaption: "Figure 2 · 规划期 tactile cache 与异步 tactile expert 的完整信息流。来源：arXiv 原图。",
  },
  {
    title: "Same Trajectory, Contradictory Rewards (RoboRMBench): Paraphrase Fragility in Vision Language Reward Models",
    arxivId: "2609.05401",
    url: "https://arxiv.org/abs/2609.05401",
    institutions: ["Yonsei University", "Carnegie Mellon University", "Seoul National University"],
    signal: "固定同一条真机轨迹，只改写语义等价的目标指令，系统测量视觉语言 reward model 是否会把同一行为从失败翻成成功。",
    tags: ["Reward Model", "Language Robustness", "Real-Robot Dataset"],
    classification: { research: "其他", training: "Post-training", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    motivation: "VLM 被用作机器人 reward 时，语义等价指令应产生相同进度评分；现有评测混合了轨迹差异，无法隔离措辞敏感性。",
    methodSummary: "RoboRMBench 固定轨迹与任务意图，生成词汇替换、句法重写和 action-goal 视角转换三类 paraphrase，经模型 ensemble 与人工抽检保留语义等价项。",
    architecture: "这是评测框架而非新控制器：对每条轨迹的 paraphrase 集合计算分数跨度、失败/成功翻转和误差，再比较通用 VLM 与机器人专用 reward model。",
    data: "2,390 条真机轨迹、ground-truth 进度标签与 21,673 条验证后 paraphrase；人工检查 210 条候选。",
    experiments: "覆盖多种开源/闭源 VLM、不同模型规模和 reasoning 设置；比较三种改写强度，并把 RR-4B/RR-8B 作为轨迹监督专用基线。",
    novelty: "action-goal 视角改写下，部分通用 VLM 在超过一半轨迹上跨越失败—成功边界；规模增大或显式 reasoning 并不稳定改善。",
    strengths: "控制变量非常干净，轨迹完全不变；数据量大，语义过滤有人工验证，且把数值波动和决策翻转分开。",
    limitations: "只检验英文等价改写和离线 reward 预测，没有展示差异如何影响真实 RL 收敛与安全。",
    transfer: "在把 VLM 接入奖励或成功判定前，应加入语义等价指令一致性测试，且优先用轨迹监督校准而非盲目扩大通用模型。",
    technique: [
      "三档 paraphrase 从表层词汇到句法和 action-goal 视角逐渐增大表达距离；模型 ensemble 先排除真实语义变化。",
      "同一轨迹的 reward 集合用于计算 score inconsistency、failure flip 与误差；所有请求含解析失败都保留在分母。",
    ],
    evaluation: [
      "210 条人工抽检中，ensemble 找到 25 条人工判为不等价中的 24 条，召回 96%；同时额外保守过滤 17 条。",
      "通用 VLM 的不稳定随改写距离上升，显式推理和更大参数量不是可靠解；RR-4B/RR-8B 虽更小却明显更稳定。",
    ],
    comparison: "多种通用闭源/开源 VLM、不同规模/推理设置、RR-4B/RR-8B，以及三类 paraphrase。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文给出 2,390/21,673 数据规模、改写分类、语义过滤、人工抽检与三类稳定性指标。"],
    missing: ["数据与评测代码的公开入口未确认；未做 reward fragility 对下游机器人 RL 的闭环实验。"],
    figureFile: "2609.05401-fig2.png",
    figureAlt: "RoboRMBench 固定轨迹并改变等义指令的评测流程",
    figureCaption: "Figure 2 · 同一真机轨迹配多类等义改写，隔离 reward model 的措辞脆弱性。来源：arXiv 原图。",
  },
  {
    title: "What Matters, When? Diagnosing and Improving Conditional Visual Grounding in Visuomotor Imitation Policies",
    arxivId: "2609.05376",
    url: "https://arxiv.org/abs/2609.05376",
    institutions: ["Fraunhofer IPK", "Technische Universität Berlin"],
    signal: "把视觉干扰失效定位到抓取/放置阶段，并用干扰物增强、阶段注意力正则和外观视觉提示联合提升目标选择。",
    tags: ["Visual Grounding", "Imitation Learning", "Distractor Robustness"],
    classification: { research: "VLA", training: "BC", modalities: ["Mask / Segmentation"], data: "数据增强", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "策略在干净场景成功不代表理解当前阶段该关注物体还是容器；外观相似的无关对象会让正确操作技能被错误目标选择掩盖。",
    methodSummary: "基于 ACT 的改进版加入 copy-paste 干扰增强、按阶段约束的注意力正则和物体/容器视觉 prompt，由 phase predictor 在执行中切换条件。",
    architecture: "完整相机图像与阶段选中的视觉提示分别编码，phase predictor 选择 object/receptacle prompt，ACT decoder 融合视觉 memory、qpos 和 learned query 输出 action chunk。",
    data: "仿真采用受控颜色/形状干扰；UR3e 覆盖干净与混合干扰；探索性 π0.5 实验使用 231 条遥操作轨迹。",
    experiments: "仿真 3 个训练种子、4 个评价种子、每种子 50 次；UR3e 每单元 20 次；π0.5 探索评价共 75 次且条件不完全等价。",
    novelty: "混合干扰下标准 ACT 真机 0/20，联合改进达到 13/20 与 12/20，并维持干净场景性能；失效可按相似类型和操作阶段局部化。",
    strengths: "先诊断再干预，仿真和真机协议清楚；三种方法分别针对数据分布、注意力和显式目标条件。",
    limitations: "主结果基于较小的 ACT 任务和单一 UR3e；π0.5 试验每子条件仅 5 次且设置不对称，不能视为同等强度验证。",
    transfer: "视觉鲁棒性应按操作阶段拆分，并把对象相似性与容器相似性分别控制；提示只提供外观目标，避免泄漏位姿答案。",
    technique: [
      "copy-paste augmentation 扩展干扰分布；阶段注意力正则让 picking/placing 分别集中到对象/容器。",
      "appearance-only visual prompt 保留空间定位给现场图像完成，phase predictor 决定当前该使用哪个提示。",
    ],
    evaluation: [
      "仿真使用 3 个训练种子、4 个评价种子和每种子 50 rollouts，避免单一 checkpoint 偶然性。",
      "UR3e 混合干扰中原始 ACT 为 0/20，改进配置为 13/20 和 12/20，同时干净条件无明显退化。",
      "π0.5 的 231 条演示、75 次试验只作探索性佐证，论文明确其子条件不可直接横比。",
    ],
    comparison: "标准 ACT、单独/组合的干扰增强、阶段注意力正则和视觉提示，并以受控相似性与阶段失败率比较。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文披露 ACT 改造结构、随机种子、每条件 rollout 数、UR3e 试验次数与 π0.5 探索协议。"],
    missing: ["未确认训练代码和数据开放；更复杂长程任务、多摄像头与更强 VLA 的充分真机复验缺失。"],
    figureFile: "2609.05376-fig1.png",
    figureAlt: "带阶段视觉提示与注意力正则的 ACT 改进架构",
    figureCaption: "Figure 1 · 完整视觉、阶段视觉提示、phase predictor 与 ACT decoder 的条件 grounding。来源：arXiv 原图。",
  },
  {
    title: "Reasoning Without Inference Cost: Latent Semantic Scaffolding for Robot VLA Policies",
    arxivId: "2609.04893",
    url: "https://arxiv.org/abs/2609.04893",
    institutions: ["CLOVER Laboratory, The Chinese University of Hong Kong", "Hong Kong Centre for Logistics Robotics"],
    signal: "训练时将每个动作 token 对齐到所在操作阶段的因果解释 embedding，部署前删除 reasoning encoder 与投影头。",
    tags: ["Reasoning", "Representation Alignment", "VLA"],
    classification: { research: "CoT", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"] },
    motivation: "让 VLA 在线生成 CoT 或未来视频会把推理成本重复到每个控制步；单纯 BC 又只学“做什么”，没有明确物理因果监督。",
    methodSummary: "LSS 用小投影头把 action-token 隐状态对齐到物理 reasoning 文本；Dense LSS 按操作阶段为每个 token 匹配局部解释，Pooled LSS 则全 episode 共用一个目标。",
    architecture: "H-RDT/VLA 主干保持，训练期增加 text encoder 与 LSAHead 做 cosine alignment；Stage-3 机器人微调和部署完全移除两者。",
    data: "500 条 adjust_bottle 人类演示，Apple Vision Pro 采手腕动作、ZED 采 RGB，左右手×可乐/雪碧各 125 条；reasoning 由 Gemini 生成。",
    experiments: "RoboTwin adjust_bottle、shake_bottle、move_can_pot 各用 50 episode、22k 步微调和 100 rollout；比较输入 reasoning、预测 token、pooled/dense alignment。",
    novelty: "同域 Dense 90%、Pooled 85%、AVP-only 79%、reasoning 作为输入 71%、平凡文本目标 58%；Dense 在两项留出任务均最好。",
    strengths: "同一数据和微调预算隔离 alignment 形式，且有表示 probe；部署参数与延迟与 base 完全一致。",
    limitations: "只有一种人类预训练任务与 RoboTwin 仿真，无真机；阶段边界和 rationale 由 VLM 产生且没有正式质量控制。",
    transfer: "若用语言解释塑造动作表征，应按局部操作阶段对齐并在推理时丢弃教师；整段共享解释容易过拟合训练任务。",
    technique: [
      "Pooled LSS 将整段动作都对齐一个 episode embedding；Dense LSS 给每个 action token 分配其 phase rationale，保留时序结构。",
      "辅助权重 λ=0.1，alignment 只作弱正则；训练完删除 LSAHead 和 reasoning encoder，不增加在线 token 生成或视频 rollout。",
    ],
    evaluation: [
      "同域消融中平凡文本 58%→真实 reasoning pooled 85%，表明不是额外 loss 本身；Dense 再到 90%。",
      "Pooled 在 shake_bottle 39% 低于无 LSS 的 45%，move_can_pot 19% 近似 20%；Dense 每项最佳，且 phase silhouette 约为 pooled 的两倍。",
    ],
    comparison: "H-RDT、加入人类数据、reasoning 作为输入/token 预测、平凡文本、Pooled LSS、Dense LSS 和冻结主干。",
    reproducibilityStatus: "部分可复现",
    implementation: ["披露 500 条人类数据、2×2 平衡设计、50 episode/22k 步/100 rollout、λ=0.1 与各消融。"],
    missing: ["未确认代码和 rationale 标注开放；无真机、跨物体类别和更大人类数据验证。"],
    figureFile: "2609.04893-fig2.png",
    figureAlt: "Latent Semantic Scaffolding 的 pooled 与 phase-local dense 对齐",
    figureCaption: "Figure 2 · 训练期 reasoning embedding 对齐动作 token，部署时辅助模块被移除。来源：arXiv 原图。",
  },
  {
    title: "Temporal Tactile Encoding and Compliance for Intent-Aware Robot-to-Human Bimanual Handover",
    arxivId: "2609.05282",
    url: "https://arxiv.org/abs/2609.05282",
    institutions: ["Istituto Italiano di Tecnologia", "University of Genoa"],
    signal: "用因果触觉历史区分持续接取与短暂碰撞，再以顺应控制降低交接力；在 10 人×3 策略×10 情况的真机实验中验证。",
    tags: ["Tactile", "Human-Robot Handover", "Compliance"],
    classification: { research: "VLA", training: "BC", modalities: ["Tactile", "Force / Torque"], platforms: ["Humanoid", "灵巧手"] },
    motivation: "视觉无法可靠区分真正接取、轻触、错误方向拉力和短暂冲击；只有顺应控制也可能把被动运动误判为接取意图。",
    methodSummary: "方法先把约 70 Hz 指尖触觉编码成有时间因果的 TTE 表征，再与 RGB/本体输入 VLA；独立 compliance controller 在交接时降低相互作用力。",
    architecture: "ergoCub 双手 Xela 指尖触觉经过时间编码器，与相机和机器人状态共同条件动作策略；上肢控制器在接触阶段执行顺应。",
    data: "8 名示范者各 50 条：25 条无顺应、25 条有顺应，10 Hz 机器人/视觉和约 70 Hz 触觉，总计每种条件约 50k 帧。",
    experiments: "先在 3,776 帧挑战集比较瞬时力与 TTE，再由 10 位新参与者分别测试 compliance+TTE、仅 compliance、仅 TTE，每策略 100 次。",
    novelty: "完整系统成功率 93%，2.8 s 内及时成功 92%，对比仅 TTE 82%/80%、仅 compliance 45%；中位释放延迟 1.70 s。",
    strengths: "参与者与示范者分离，包含应释放/应保持两类和多种误导接触；主观舒适与客观成功/力/时延共同报告。",
    limitations: "单一盒子交接、单平台和 10 名测试者；TTE 与 compliance 分别训练的数据条件不同，跨物体和速度泛化未知。",
    transfer: "人机接触意图不能由瞬时力阈值决定，应编码持续证据并将识别与顺应控制同时纳入评测。",
    technique: [
      "TTE 以因果触觉窗口汇总双手指尖力，抑制短时敲击、抖动与错误方向拉力；策略仍以动作 BC 训练。",
      "compliance 不负责意图判定，只降低交接时峰值力和提高平滑性；与 TTE 组合形成感知—控制互补。",
    ],
    evaluation: [
      "挑战集上瞬时力策略越过错误释放阈值 51 次、4 次持续超过 1.5 s；TTE 仅 3 次且无持续误开。",
      "完整系统 300 个计分 trial 中对应单策略 100 次，成功 93%，峰值拉力 4.07 N；最难的短促强拉情况成功 60%。",
      "主观平滑/总体满意均为 6.2/7，明显高于两种消融，支持顺应控制主要改善交互质量而非替代触觉。",
    ],
    comparison: "瞬时力 vs. TTE 表征，以及 compliance+TTE、仅 compliance、仅 TTE 三策略的人体实验。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文披露参与者数、示范分配、传感频率、100k 步预算、2.8 s 阈值来源与每策略 100 次协议。"],
    missing: ["代码和数据仅承诺接收后发布，尚无公开入口；物体、重量和参与者规模有限。"],
    figureFile: "2609.05282-fig2.png",
    figureAlt: "ergoCub 双臂交接的视觉触觉策略与顺应控制架构",
    figureCaption: "Figure 2 · 时间触觉编码、VLA 策略和上肢顺应控制的整体系统。来源：arXiv 原图。",
  },
  {
    title: "LIBERO-RECOVER: Beyond Task Success Towards Failure Recovery in Robotic Manipulation Models",
    arxivId: "2609.05178",
    url: "https://arxiv.org/abs/2609.05178",
    institutions: ["Dalian University of Technology", "Beta Infinity", "Nanyang Technological University", "Beijing Jiaotong University"],
    signal: "从多种 VLA/WAM 的真实执行失败出发，构造四级恢复场景，单独测量动作重试、状态恢复和环境恢复能力。",
    tags: ["Failure Recovery", "Benchmark", "Temporal Context"],
    classification: { research: "其他", training: "Post-training", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://liulin815.github.io/LIBERO-Recovery/" }],
    motivation: "标准 LIBERO 从理想初态执行一次，接近满分并不说明模型能识别失败、恢复被破坏的物体状态并继续任务。",
    methodSummary: "让三种 embodied model 在 LIBERO 中实际执行并保留失败后状态，再由人工遥操作收集恢复轨迹；按 action retry、action adaptation、object-state recovery、environment recovery 四级组织。",
    architecture: "基准记录任务指令、初态、失败轨迹、失败后状态和恢复行为，并用 16 个维度分别诊断空间、物体结构、交互与拓扑推理。",
    data: "2,178 个恢复场景、130 个子任务、四类 LIBERO 套件与四个恢复级别；四名遥操者又在 413 个失败场景中收集 3,184 条恢复轨迹。",
    experiments: "比较 π0、π0-FAST、GR00T-N1.5、OpenVLA-OFT、Wan2-Policy 与 Cosmos-Predict2-Policy，并测试动作块长度、恢复数据混训和初始帧上下文。",
    novelty: "所有模型面对真实执行失败时都下降超过 50%；平均 LIBERO-100 从标准场景的 26.2% 降到恢复场景的 0.3%，现有排序不能代表恢复能力。",
    strengths: "失败由模型实际 rollout 产生，不是手工摆放扰动；场景、困难等级、模型族和人工恢复轨迹规模都足以支持细分诊断。",
    limitations: "全部实验仍在 LIBERO 仿真生态，失败分布受三种采集模型影响；恢复数据带来的提升对标准执行错误几乎不迁移。",
    transfer: "评测部署鲁棒性时，应保存失败后的状态与历史，而不是只重置后重跑；动作块粒度和初始状态参照本身就是恢复变量。",
    technique: [
      "每个场景由模型真实失败轨迹及其后果构成；四级难度从重复局部动作递进到恢复任务相关物体或环境状态，避免把一般分布偏移误称为失败恢复。",
      "人工恢复数据用于混合微调；评测除 recovery success rate 外还按任务统计一致性，并把 16 个标签用于定位具体推理缺口。",
    ],
    evaluation: [
      "平均来看，LIBERO-Spatial 从 15.0% 降到 6.7%、Goal 从 35.5% 降到 4.0%、Object 从 38.3% 降到 5.0%、LIBERO-100 从 26.2% 降到 0.3%。",
      "恢复成功随动作块从 4 增至 32 持续下降；L3/L4 明显难于 L1/L2，说明状态恢复比局部动作纠错更薄弱。",
      "混合恢复数据使 GR00T 恢复率 17.8→21.2%、OpenVLA-OFT 20.8→25.4%，但标准任务分别仅 86.5→87.2% 和 97.1→96.6%。加入初始帧后 OpenVLA-OFT 恢复率升至 26.8%。",
    ],
    comparison: "六类 VLA/WAM、标准初态与真实失败状态、四级恢复难度、动作块长度、是否混入恢复数据以及是否提供初始帧。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文披露场景构建、四级 taxonomy、130 个子任务、16 个评价维度、人工恢复规模、动作块和 temporal-context 对照。"],
    missing: ["项目页尚未确认开放完整 benchmark、轨迹与评测代码；尚无真机失败恢复验证。"],
    figureFile: "2609.05178-fig1.png",
    figureAlt: "LIBERO-Recover 从真实模型失败收集多级恢复场景的概览",
    figureCaption: "Figure 1 · 模型真实失败、人工恢复轨迹与多维恢复评价构成完整基准。来源：arXiv 原图。",
  },
];

export const paperDaily20260907 = entries.map(makePaper);
