import type { Paper } from "./site-data";

type Entry = Omit<Paper, "rank" | "figures" | "optimization" | "experimentDetails" | "reproducibilityDetails" | "deepDive"> & {
  figureFile: string; figureAlt: string; figureCaption: string;
  technique: string[]; evaluation: string[]; comparison: string;
  reproducibilityStatus: "资源较完整" | "部分可复现" | "信息不足";
  implementation: string[]; missing: string[];
};

const makePaper = (entry: Entry, index: number): Paper => ({
  ...entry,
  rank: index + 1,
  optimization: entry.technique.join("；"),
  experimentDetails: [{ title: "原文实验与消融", setup: entry.experiments, comparisons: entry.comparison, results: entry.evaluation }],
  reproducibilityDetails: {
    status: entry.reproducibilityStatus,
    verifiedResources: entry.resources?.map((x) => `${x.label}: ${x.url}`) ?? ["arXiv 论文正文"],
    implementation: entry.implementation,
    missing: entry.missing,
  },
  deepDive: {
    lead: entry.methodSummary ?? entry.signal,
    sections: [{ title: "技术细节", paragraphs: entry.technique }],
    experimentReading: entry.evaluation,
    reflections: [entry.transfer],
  },
  figures: [{ src: `/report-assets/2026-09-21/${entry.figureFile}`, alt: entry.figureAlt, caption: entry.figureCaption }],
});

const entries: Entry[] = [
  {
    title: "SeeQ: Training Generalist Value Functions for Long-Horizon Robotic Manipulation", arxivId: "2609.22085", url: "https://arxiv.org/abs/2609.22085",
    resources: [{"label":"模型","url":"https://huggingface.co/CMU-AIRe/SeeQ-3B/"},{"label":"项目页","url":"https://saksham002.github.io/seeq/"}],
    institutions: ["Carnegie Mellon University"], signal: "把长程任务的价值预测缩短到当前子任务，并让价值模型自行预测正在执行的子任务。",
    tags: ["Value Function", "Subtask", "Policy Steering"], classification: { research: "Subtask", training: "RL", platforms: ["机械臂", "夹爪"] },
    motivation: "稀疏的整任务奖励让长程操作的价值学习承担过长的信用分配链，失败动作难以定位到具体步骤。",
    methodSummary: "SeeQ 在价值估计前先自回归预测当前子任务文本，再用子任务边界内的 TD 目标训练 Q 值；测试时从固定 π0.5 提议的八个动作块中选最高值。",
    architecture: "PaliGemma 3B 视觉语言骨干接子任务文本解码与标量价值头，价值条件包含状态、候选动作和当前子任务。",
    data: "用 RoboCOIN 双臂数据预训练，覆盖 131 项任务和约 4 万段轨迹；目标任务还需带子任务标注的数据微调。",
    experiments: "xArm-7 与 YAM 双臂平台的四项真机任务，每项每方法 24 次；比较相同底座的 Monte Carlo、整任务 TD 和子任务 SARSA critic，并做预训练及子任务预测消融。",
    novelty: "shirt-hang 从基础策略 10/24 提至 22/24；grocery-packing 从 9/24 提至 17/24，四项任务均按完整完成判定。",
    strengths: "同一候选动作池与真实双臂任务下比较价值目标，消融显示机器人预训练和显式子任务预测都关键。",
    limitations: "训练仍需子任务边界标注与任务微调；当前价值模型只能重排基础策略提出的动作块，受候选动作质量限制。",
    transfer: "长程策略的 critic 可在子任务边界处截断自举，把局部进展估计直接用于动作块重排。",
    technique: ["训练时在子任务边界停止 TD 自举，避免后续步骤的奖励噪声污染当前价值目标。", "先解码当前子任务，再估计候选动作价值；测试不依赖外部子任务分类器。"],
    evaluation: ["shirt-hang 的同骨干整任务 TD 为 12/24、子任务 SARSA 为 13/24，而 SeeQ 为 22/24。", "移除机器人预训练或子任务预测后，shirt-hang 均降至 8/24；每任务 24 次仍不足以精确估计小幅差异。"],
    comparison: "π0.5 原策略、同底座多种 critic，以及无预训练和无子任务预测消融。",
    reproducibilityStatus: "部分可复现", implementation: ["披露子任务 TD 目标、预训练数据规模、动作候选数和四任务 24 次协议。"], missing: ["完整任务标注数据和目标任务微调权重未确认公开。"],
    figureFile: "2609.22085-fig2.png", figureAlt: "SeeQ 子任务预测与动作价值估计结构", figureCaption: "Figure 2 · 价值模型先生成当前子任务文本，再为候选动作块估计 Q 值。来源：arXiv HTML 原图。",
  },
  {
    title: "PSR: Predictive Sensorimotor Representation Learning for Contact-Rich Manipulation", arxivId: "2609.21753", url: "https://arxiv.org/abs/2609.21753",
    institutions: ["Samsung R&D Institute China-Beijing"], signal: "从力矩、关节状态与视觉历史预测未来接触信号，再把分层表征注入 VLA 动作专家。",
    tags: ["Force / Torque", "Sensorimotor", "Contact-rich"], classification: { research: "表征学习", training: "Pre-training", modalities: ["Force / Torque", "State / Proprioception"], platforms: ["机械臂", "夹爪"] },
    motivation: "仅靠视觉和瞬时状态难以区分插接、旋拧等任务中的接触阶段，直接拼接传感器又缺少未来变化监督。",
    methodSummary: "PSR 预训练六层传感运动层级来预测未来力/力矩、关节 effort 与末端位移，再经门控 cross-attention 接入 π0.5 动作专家。",
    architecture: "多模态编码和跨模态瓶颈形成浅、中、深三层表征；动作专家在第 3、6、9、12、15、18 层读取 PSR。",
    data: "六项 RB-Y1 接触任务共 1210 条示范，任务示范量分别为 300、300、200、200、150、60。",
    experiments: "六项真机任务，每方法每任务 20 次，以完整完成为成功；另有两任务的表示和注入位置消融及 PSR 单模型扰动测试。",
    novelty: "六任务 PSR 合计 110/120 次成功（91.7%），π0.5 为 74/120（61.7%）。",
    strengths: "同数据的接触任务对照、多个注入位置消融和四次 PSR 训练重复共同支持未来传感预测的价值。",
    limitations: "基线与 PSR 的传感输入和预训练预算并非全部严格匹配；新物体、长程接触泛化尚未系统验证。",
    transfer: "接触表示可用未来传感读数作训练目标，再以门控方式逐层介入动作生成。",
    technique: ["分别预测未来 12 路力/力矩、20 路关节 effort 和末端关节位移，保留接触的时间方向。", "门控 cross-attention 在动作专家六个深度位置注入层级表征，而非只在输入或末层拼接。"],
    evaluation: ["ForceVLA 为 83/120，适配的 ForceVLA2 为 87/120；输入、参数和预训练预算差异限制横向归因。", "两任务真机消融中，完整 PSR 均为 19/20；去预训练后分别为 14/20 和 11/20，末层单点注入为 10/20 和 11/20。"],
    comparison: "π0.5、ForceVLA 系列，以及无预训练、反向层级、共享深层和末层单点注入消融。",
    reproducibilityStatus: "部分可复现", implementation: ["披露传感目标、注入层、示范分布、每任务 20 次协议与四次训练重复。"], missing: ["完整传感数据、权重及跨硬件复现实验未确认公开。"],
    figureFile: "2609.21753-fig2.png", figureAlt: "PSR 预测力觉与关节状态的分层表示学习", figureCaption: "Figure 2 · 传感运动编码器预测未来力觉、关节 effort 和末端位移，再供动作策略读取。来源：arXiv HTML 原图。",
  },
  {
    title: "From Pretraining to Proficiency: Real-World Subtask RL for Long-Horizon Manipulation with Minimal Human Intervention", arxivId: "2609.21788", url: "https://arxiv.org/abs/2609.21788",
    institutions: ["The University of Texas at Austin", "Autel US", "University of California, Berkeley"], signal: "把真机 RL 集中到基础策略反复失败的子任务，局部验证与复位使稀疏长程奖励更可训练。",
    tags: ["Subtask RL", "Residual Policy", "Real Robot"], classification: { research: "Subtask", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://destiny000621.github.io/PARTS/" }],
    motivation: "完整任务上的 RL 在瓶颈前反复浪费 rollout，后段步骤很少得到局部成功反馈。",
    methodSummary: "PARTS 保持预训练 π0.5 不变，为人工识别的瓶颈训练有界 residual TD3+BC 策略，并用选择器、验证器及复位程序组织局部练习。",
    architecture: "基础策略生成名义动作；子任务选择器在指定状态启用残差；验证器给局部奖励，成功重加权再训练后重新部署。",
    data: "真机在线数据来自 YAM 双臂耳机插入、LEGO 分拣和 Franka 线缆任务；还需操作员设置瓶颈和复位。",
    experiments: "三项真机长程任务，每方法完整任务评测 20 次，并在相同机器人 rollout 时间下对比全任务 RL 方法。",
    novelty: "论文报告双臂任务完整成功率合计由 32% 升至 61%，Franka 任务由 50% 升至 95%；训练用数十分钟级真机交互。",
    strengths: "局部奖励、残差策略和失败重试共同针对长程瓶颈，并用完整任务而非仅局部成功验证。",
    limitations: "瓶颈选择、合约和部分复位仍需要人；成功率受任务设置及基础策略已有能力限制。",
    transfer: "先保留基础策略已稳定的步骤，再对少数失效环节做局部残差 RL，可提高真机数据利用率。",
    technique: ["人指定瓶颈与可验证的子任务合约，代码代理实现选择、成功判定和自动复位程序。", "有界 TD3+BC 残差只在瓶颈启用，成功轨迹重加权再训练后继续在线收集。"],
    evaluation: ["完整任务按每方法每任务 20 次评测；相同 rollout 时间下与 DSRL、EXPO-FT 和 RLT 比较。", "耳机任务的成功重加权消融支持后续迭代收益，但局部人工判定与复位成本未完全自动化。"],
    comparison: "冻结基础策略、全任务 RL 方法以及成功重加权再训练消融。",
    reproducibilityStatus: "部分可复现", implementation: ["项目页、三种真机任务、20 次完整任务协议和训练流程披露。"], missing: ["各任务的人工介入总时长、完整设备/代码和数据状态未确认公开。"],
    figureFile: "2609.21788-fig2.png", figureAlt: "PARTS 子任务合约与残差强化学习流程", figureCaption: "Figure 2 · 选择器、验证器和复位程序把基础策略的瓶颈接入局部 residual RL。来源：arXiv HTML 原图。",
  },
  {
    title: "GALA: Geometry-Aware Latent Action Modeling for Vision-Language-Action Model Pretraining across Embodiments", arxivId: "2609.21948", url: "https://arxiv.org/abs/2609.21948",
    institutions: ["Tsinghua University", "Shanghai Qi Zhi Institute"], signal: "用视觉与末端点云共同编码 latent action，使人类手和异构夹爪的细粒度运动能共享训练信号。",
    tags: ["Latent Action", "Geometry", "Cross-embodiment"], classification: { research: "表征学习", training: "Pre-training", modalities: ["Point Cloud / 3D"], data: "跨本体数据", platforms: ["机械臂", "灵巧手"], deployment: "跨本体迁移" },
    motivation: "纯图像 latent action 容易混淆外观变化与手指运动，异构末端的几何变化又难直接放入同一动作接口。",
    methodSummary: "GALA 联合学习视觉与点云几何 latent，通过 UEMR 的双向转移和成对一致性约束保留跨本体末端运动，再监督 VLA 桥接 token。",
    architecture: "冻结视觉和点云编码器提取状态；视觉与几何 latent 共享时空建模；冻结 latent 监督 VLM bridge token，动作 expert 使用本体专属输出头。",
    data: "组合 EgoDex、HOI4D、DROID、RoboCasa GR1 与自采 XHand/人手交互数据。",
    experiments: "细粒度运动探针、跨本体检索、RoboCasa 与 XHand 四项真机任务；真机每任务 50 次。",
    novelty: "相同数据和底座的 RoboCasa 对照中，GALA 为 55.7%，UniVLA 为 48.0%；XHand 真机四任务均值 75.5%。",
    strengths: "从 latent 诊断、仿真控制到真机灵巧操作的多层证据，并单独消融点云与 UEMR。",
    limitations: "跨团队真机基线骨干和训练设置不完全一致；点云质量与末端几何标定仍影响迁移。",
    transfer: "跨本体动作可先比较末端几何转移，再由各本体动作头映射到原生命令。",
    technique: ["视觉 latent 与点云几何 latent 并行学习，UEMR 以共享末端运动表征约束双向状态转移。", "冻结 GALA 表征给 VLM bridge token 提供监督，动作 expert 通过本体专属 head 输出原生动作。"],
    evaluation: ["RoboCasa 同设置消融：去点云为 50.9%，去 UEMR 为 54.4%，完整模型 55.7%。", "真机均值 75.5%，HARP-VLA 71.5%、π0.5 68.0%；跨方法骨干差异使该差值不能单独归因于 latent。"],
    comparison: "RoboCasa 的 UniVLA 和组件消融，XHand 上的 HARP-VLA、π0.5 与去 UEMR 消融。",
    reproducibilityStatus: "部分可复现", implementation: ["披露多源数据、UEMR、同底座消融和四任务 50 次真机协议。"], missing: ["全部自采数据、权重和独立跨本体复现未确认公开。"],
    figureFile: "2609.21948-fig2.png", figureAlt: "GALA 视觉与点云几何 latent action 联合学习", figureCaption: "Figure 2 · 图像与末端点云转移分别形成 latent，UEMR 约束跨本体几何一致性。来源：arXiv HTML 原图。",
  },
  {
    title: "MT-WAM: Reorienting the One-Pass Predictive Representation Toward Action Generation", arxivId: "2609.21474", url: "https://arxiv.org/abs/2609.21474",
    resources: [{"label":"GitHub","url":"https://github.com/Alexi1984/MT-WAM"}],
    institutions: ["Aerospace Information Research Institute, Chinese Academy of Sciences", "University of Chinese Academy of Sciences"], signal: "在不推理未来视频的 WAM 中，用未来点轨迹和视觉特征监督改善一次前向的动作条件表示。",
    tags: ["World-Action Model", "Motion Prediction", "One-pass"], classification: { research: "WAM", training: "Pre-training", modalities: ["其他模态"], platforms: ["机械臂", "夹爪"] },
    motivation: "仅靠未来画面重建会把大量外观细节压进单次 video backbone 表征，动作专家难以直接获取关键运动信息。",
    methodSummary: "MT-WAM 复制 video DiT 尾部形成双流动态分支：点轨迹流直接给动作专家 KV，未来 DINOv2 特征流只训练视觉骨干。",
    architecture: "视频主干与前段共享，尾部 10 层复制为 motion/feature 双流；两流独立 FFN 和注意力掩码，推理只复用 video 与 motion KV cache。",
    data: "RoboTwin 50 任务、LIBERO/LIBERO-Plus，以及四项 UR5 真机任务各 100 条示范，共 400 条。",
    experiments: "LIBERO、LIBERO-Plus、RoboTwin 2.0 与四项真机任务；真机每任务每方法 100 次，共 400 次，同样初始配置。",
    novelty: "四项真机平均成功率 77.8%，Fast-WAM 为 67.0%；LIBERO-Plus 为 73.66%，Fast-WAM 为 49.86%。",
    strengths: "相同真机数据和试验配置、跨三个仿真协议及流连接消融，清楚隔离预测监督与推理接口。",
    limitations: "二维轨迹没有显式三维接触几何；目前只验证一个视频骨干和 UR5 单/双臂配置。",
    transfer: "未来预测分支可以只在训练时提供语义监督，推理时仅保留与控制直接相关的运动缓存。",
    technique: ["CoTracker3 产生未来二维点位移目标，冻结 DINOv2 提供未来 patch 特征目标，两者与视频/动作流匹配目标联合训练。", "动作查询读取 motion 流而不读取 feature 流；推理跳过未来视频生成，每次重规划只构建一次缓存。"],
    evaluation: ["LIBERO-Plus 去掉 feature 流后由 73.7% 降到 68.8%；让动作直接读取 feature 流则降至 70.9%。", "相同 GPU 下延迟为 313.5 ms，Fast-WAM 为 296.3 ms；RoboTwin Clean2Rand Random 为 19.4%，仍低于有额外预训练的 HALO 26.4%。"],
    comparison: "Fast-WAM、Fast-WAM-Joint、其他 WAM/VLA，以及视觉流连接和分支深度消融。",
    reproducibilityStatus: "部分可复现", implementation: ["公开训练目标、attention 规则、分支深度、400 次真机协议和推理成本。"], missing: ["完整训练权重、全部训练数据与跨骨干验证未确认公开。"],
    figureFile: "2609.21474-fig2.png", figureAlt: "MT-WAM 双流动态分支与单次缓存推理", figureCaption: "Figure 2 · 未来点轨迹与视觉特征分流训练，动作专家在推理时读取运动缓存。来源：arXiv HTML 原图。",
  },
  {
    title: "Skel-WAM: A Hand-Skeleton-Conditioned World Action Model for Human-to-Robot Manipulation Transfer", arxivId: "2609.21514", url: "https://arxiv.org/abs/2609.21514",
    resources: [{"label":"项目页","url":"https://HealorCai.github.io/Skel-WAM/"}],
    institutions: ["The Chinese University of Hong Kong", "Shanghai AI Laboratory", "Joy Future Academy"], signal: "把人手与机器人灵巧手映射到双手 21 点骨架，用人类视频补足机器人示范缺少的任务变化。",
    tags: ["Human Video", "Hand Skeleton", "World-Action Model"], classification: { research: "WAM", training: "Pre-training", modalities: ["其他模态"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "灵巧手"], deployment: "跨本体迁移" },
    motivation: "人类视频缺机器人动作，外观与手部关节又不一致，直接共训难把人类任务变化稳定迁移到灵巧手。",
    methodSummary: "Skel-WAM 用场景骨架叠图和结构化 2.5D 手部关键点共同预测未来；共享 Video-Keypoint MoT 学人/机动态，Action Expert 只用机器人动作训练。",
    architecture: "双手各 21 个关键点映射到相同拓扑；Video Expert 与 Keypoint Expert 预测未来，因果 Action Expert 将视频和骨架条件解码为本体动作。",
    data: "每项真机任务平均约 50 条机器人示范和 25 条人类示范；人类片段提供位置、旋转、干扰物与高度变化。",
    experiments: "双 Franka FR3 加 XHand1 的四项双臂真机任务，另有七项仿真任务；机器人设定每任务 24 次、缺失变化每项 9 次、新背景每项 6 次，Stack Cups 机器人设定 18 次。",
    novelty: "四项真机机器人设定平均完整成功率 79.86%，EgoVLA 为 57.64%；人类覆盖的缺失变化从 38.89% 提到 86.11%。",
    strengths: "固定任务语言、明确分离机器人缺失变化，叠图与关键点独立消融能解释迁移来源。",
    limitations: "人手关键点估计、相机标定和人机示范匹配成本较高；缺失变化每条件只有 9 次。",
    transfer: "人类视频可监督共享的未来手部运动，而机器人原生控制头仍只从有动作标签的机器人数据学习。",
    technique: ["手骨架同时保留叠图的场景位置和结构化 2.5D 关键点的手指身份、深度及轨迹。", "人机数据共训 Video-Keypoint MoT；Action Expert 只读机器人动作标签，避免伪造人手对应的机器人命令。"],
    evaluation: ["缺失变化上，去叠图为 50.0%，去关键点为 13.89%，完整模型为 86.11%。", "七项仿真平均成功率 63.29%，EgoVLA 为 55.01%；新背景真机平均成功率 58.33%。"],
    comparison: "ACT、Fast-WAM、LDA、EgoVLA；有无人机共训及两种骨架表示消融。",
    reproducibilityStatus: "部分可复现", implementation: ["披露关键点拓扑、训练目标、示范数量、控制频率和分条件成功定义。"], missing: ["完整人类/机器人示范、关键点处理代码和权重未确认公开。"],
    figureFile: "2609.21514-fig2.png", figureAlt: "Skel-WAM 视频骨架联合预测与机器人动作解码", figureCaption: "Figure 2 · 人机视频共训 Video-Keypoint MoT，机器人示范单独训练 Action Expert。来源：arXiv HTML 原图。",
  },
  {
    title: "VT-Bridge: Bridging Pretrained Foundation VLAs to VTLAs via Lightweight Residual Adaptation", arxivId: "2609.22606", url: "https://arxiv.org/abs/2609.22606",
    resources: [{"label":"项目页","url":"https://hoxnocha.github.io/vt-bridge-web/"}],
    institutions: ["Technical University of Munich", "Mohamed bin Zayed University of Artificial Intelligence", "Shanghai University"],
    signal: "冻结 VLA，用最新力觉历史修正正在执行的动作块，并区分接触发生与任务真正完成。",
    tags: ["Force Feedback", "Residual Adapter", "Contact-rich"], classification: { research: "VLA", training: "Post-training", modalities: ["Force / Torque"], platforms: ["机械臂", "夹爪"] },
    motivation: "视觉 VLA 的动作块在接触中可能滞后；执行器实际位姿又不一定等于完成按压、插入所需的控制目标。",
    methodSummary: "VT-Bridge 为冻结策略训练小型残差适配器，把名义动作块与最新力/力矩历史融合，逐步修正动作；监督目标使用期望控制指令，而非受接触约束后的实测位姿。",
    architecture: "约 0.98M 参数的双 Transformer 分别编码动作块和力觉历史，MLP 输出残差。动作块特征可缓存，力觉分支随执行更新；不同 VLA 使用分别训练的适配权重。",
    data: "按压泵瓶、擦白板、插插头和拨动开关四项真机任务，各 50 条示范，共 200 条；比较 π0、π0.5 和 SmolVLA 三类底座。",
    experiments: "每个底座、方法、任务评测 20 次，限时 90 秒。严格任务完成平均由 11.7% 升至 62.9%；另比较视觉目标与执行位姿两种残差监督。",
    novelty: "区别于仅拼接触觉的条件策略，残差在动作块执行期间读取新接触信息；期望指令监督相对实测位姿监督的严格完成率为 62.9% 对 12.1%。",
    strengths: "同时检验多个 VLA 底座与真实接触任务，且把“碰到物体”和“完成任务”的指标分开。",
    limitations: "四项任务范围较窄，适配器不是跨底座共享权重；这里的触觉主要是力/力矩信号，并非分布式指尖触觉图像。",
    transfer: "已有动作块策略可用高频力觉残差补足接触反馈；训练标签应保留操作者希望施加的控制目标。",
    technique: ["执行动作写作 a_exec = a_VLA + δa。动作分支对整块只编码一次，接触分支持续读取最近 50 步的力觉序列，融合后给出当前步残差，因此不必在每次反馈后重新运行完整 VLA。", "残差标签为 δa* = a_desired − a_VLA，而不是 a_measured − a_VLA。受到刚性环境约束时，测量位姿可能几乎不动，期望目标却仍在表达按压或插入的控制意图；自由空间使用零残差约束。", "笛卡尔控制使用末端力/力矩，关节空间使用外部关节力矩。VLA 先完成示范微调，再冻结并训练适配器；这不是在线 RL，也不是一个适配器直接迁移到所有底座。"],
    evaluation: ["四任务各 50 条示范；每方法、底座和任务均测试 20 次。严格标准要求真正泵出液体、完成擦拭或插接等功能，宽松标准只反映接近或形成接触，二者不能互换。", "跨设置的严格成功均值由底座 11.7% 提高到 62.9%。监督目标消融中，使用执行位姿仅为 12.1%，使用期望指令为 62.9%，说明标签定义对这一残差方案有实质影响。", "RTX 3090 上残差预测约 0.7 ms，动作特征编码约 0.4 ms；这是适配模块开销，不是整套 VLA 的端到端推理延迟。"],
    comparison: "π0、π0.5、SmolVLA 底座、VLA-Touch，以及期望控制目标/执行位姿监督消融。",
    reproducibilityStatus: "部分可复现", implementation: ["动作块长度 50、执行 30 Hz、力觉历史 50 步；底座 LoRA 微调 30k 步、batch 32，随后冻结。论文给出适配器结构和每任务示范/评测数量。"], missing: ["完整训练数据与可直接部署权重的公开状态尚未确认。"],
    figureFile: "2609.22606-fig1.png", figureAlt: "VT-Bridge 动作块与在线力觉残差适配结构", figureCaption: "VT-Bridge 原论文方法图：名义动作和实时接触反馈共同生成控制修正。来源：arXiv 原图。",
  },
  {
    title: "ForceTwin: Physics-informed Digital Twins for Robotic Manipulation from Instrumented Human Interaction", arxivId: "2609.21751", url: "https://arxiv.org/abs/2609.21751",
    resources: [{"label":"项目页","url":"https://timengelbracht.github.io/forcetwin-website/"}],
    institutions: ["ETH Zürich", "NVIDIA", "Microsoft", "University of Bonn"], signal: "用手持设备实际探测物体阻力，把运动学数字孪生补成可预测力学响应的模型。",
    tags: ["Articulated Objects", "Force Identification", "Digital Twin"], classification: { research: "WM", modalities: ["Force / Torque"], data: "UMI / Ego / Human Video", deployment: "Real2Sim2Real", platforms: ["机械臂", "夹爪", "其他平台"] },
    motivation: "门和抽屉的形状、关节轴正确，并不意味着模拟中的惯性、阻尼和摩擦足以指导真实接触控制。",
    methodSummary: "手持设备收集位姿与受力轨迹，先识别关节类型和轴，再拟合惯性、摩擦及结构化神经残差；将所得力学模型导入数字资产和机器人控制流程。",
    architecture: "解析惯性、库仑摩擦、黏性阻尼项叠加位置相关项与非负耗散残差；几何注册和关节模型组成可执行孪生。",
    data: "逐物体主动探测的位姿/力矩序列；评估覆盖 12 根关节轴、9 组物体—机器人配对，以及有惯性参考值的 4 个物体。",
    experiments: "Spot 和 Franka FR3 上，9 组配对的平均目标完成度为 87.3%，VLM 参数估计为 59.7%，纯运动学为 56.9%；这是连续完成度，不是成功试验比例。",
    novelty: "相较只恢复几何或让 VLM 猜测物理参数，ForceTwin 使用真实力学探测约束模型，并把辨识结果用于后续控制与 sim-to-real。",
    strengths: "物理辨识、轨迹误差、控制完成度和真机迁移分开评估，能看到力学建模在哪些环节有效。",
    limitations: "每个物体需主动探测；模型不能完整表达迟滞、锁扣及历史依赖，参数分解也不保证唯一。",
    transfer: "对门、抽屉等交互对象，可先建立可预测的阻力模型，再训练控制器，而不只追求视觉上逼真的孪生。",
    technique: ["基本广义力模型为 τ = Iq̈ + μsign(q̇) + bq̇ + gθ(q) + cφ(q, |q̇|)q̇。前半部分对应惯性与摩擦，后半部分学习位置依赖阻力和额外耗散；cφ 通过非负约束避免任意注入能量。", "系统从同步的 RGB-D、位姿和力矩数据估计旋转或平移关节，利用模型选择确定关节类型，再用非负最小二乘拟合解析参数。结构化神经残差补偿纯解析模型无法覆盖的弹簧、阻尼等效果。", "辨识结果与几何资产绑定并导出 USD。实验既使用模型前馈补偿，也将物体模型接入 Isaac Lab 的机器人训练；预测准确不等同于每个物理参数都被唯一恢复。"],
    evaluation: ["12 根关节轴的类型识别正确率为 100%；平移/旋转轴平均角误差约 1.4°/1.5°。4 个有参考惯性的物体中，平均相对误差 29.5%，VLM 估计为 53.0%。", "9 组物体—机器人配对使用固定控制器和 6 秒执行窗口。目标完成度 87.3% 对 VLM 的 59.7% 和运动学的 56.9%；轨迹跟踪误差为 22.2% 对 49.8% 和 51.5%，不同对象的收益并不一致。", "残差项在复杂机构上的拟合 RMSE 进一步降低 67–73%，这一数字来自拟合分析，不能当作未见物体泛化。ANYmal 操作木门的迁移演示为 5/5 次完成，样本量和对照范围有限。"],
    comparison: "VLM 推断物理参数、纯运动学模型、无黏性阻尼/无残差变体，以及关节轴估计对照。",
    reproducibilityStatus: "部分可复现", implementation: ["残差全批量 AdamW，学习率与权重衰减均为 1e-3，75/25 训练/验证划分，最多 1200 epoch，早停耐心 120。文中给出 USD/Isaac Lab 接入方式。"], missing: ["实际探测装置的标定、逐物体资产与全部实验日志的公开完整性需按项目资源核实。"],
    figureFile: "2609.21751-fig1.png", figureAlt: "ForceTwin 力觉数据采集、系统辨识与数字孪生构建", figureCaption: "ForceTwin 原论文方法图：从物体探测、关节辨识到力学孪生及机器人使用。来源：arXiv 原图。",
  },
  {
    title: "AtomEgo: Exploring Ego-Robot Integration for Embodied Foundation Model Pretraining", arxivId: "2609.21461", url: "https://arxiv.org/abs/2609.21461",
    resources: [{"label":"GitHub","url":"https://github.com/Agentic-Intelligence-Lab/Atom-0"}],
    institutions: ["INFIFORCE", "Lionrock Artificial Intelligence Laboratory", "The University of Hong Kong", "Tongji University", "Huazhong University of Science and Technology"], signal: "对比双头共训、渐进对齐和世界—动作共训：人类视频是否有用，取决于接入方式。",
    tags: ["Ego–Robot Co-training", "Alignment", "Pre-training"], classification: { research: "VLA", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"] },
    motivation: "人类视频丰富，但人机动作和视角不一致；增加数据量未必能稳定提高真实机器人的任务完成能力。",
    methodSummary: "在统一处理的数据上比较三条路线：人机独立输出头 Atom-DH、分阶段对齐 Atom-CL，以及联合预测视频和动作的 Atom-WAM。",
    architecture: "VLA 路线采用 π0.5 式视觉语言骨干和动作专家；WAM 路线采用视频/动作 MoT。各路线分别与自身 robot-only 基线比较。",
    data: "清洗后共 2659.5 小时、334054 段，含 DROID、RoboCOIN、RoboMIND、AGIBOT、Piper 与 EgoVerse，以及约 20 小时人机对齐数据；统一为 80 维状态/动作接口。",
    experiments: "双臂 Piper 七任务，每方法每任务各 10 次 ID 与 10 次 OOD。Atom-CL 合计成功率 53.57%，VLA robot-only 为 32.86%；Atom-WAM 则低于其 WAM 基线。",
    novelty: "不是只报告“加入人类数据有提升”，而是分开比较接入路径，并给出共训失败的反例。",
    strengths: "报告逐任务 ID/OOD 结果、独立架构基线及负面结果，对预训练数据配方有直接参考价值。",
    limitations: "只有七任务、单一双臂平台；VLA/WAM 不能直接作为同架构消融，不同阶段训练预算也需结合明细理解。",
    transfer: "评估人类数据时，应同时检查动作对齐和任务区分能力，不能只看人机特征相似度或视频预测质量。",
    technique: ["数据处理把不同本体映射到 80 维公共接口，保留缺失维度掩码，采用 50 步动作块；质量过滤涉及突变、状态—动作滞后和异常值。统一接口不意味着所有身体关节具有同一种物理含义。", "Atom-DH 共享主干但分开人类和机器人输出头；Atom-CL 依次进行人类预训练、以相对末端动作连接两域的对齐训练、机器人训练。Atom-WAM 则让视频和动作专家共同学习未来，部署时不生成完整未来视频。", "VLA 从基础 PaliGemma 初始化，而非直接继承完成机器人预训练的 π0.5。两种架构分别设置 robot-only 基线，并对七任务使用相同后训练流程，避免把两个不同骨干的差异误记为人类数据收益。"],
    evaluation: ["七任务各 10 次 ID 和 10 次 OOD，总计每方法 140 次。Atom-CL 为 ID 45/70、OOD 30/70；VLA baseline 为 30/70、16/70；Atom-DH 为 32/70、29/70。", "WAM robot-only 为 21/70、19/70，Atom-WAM 降至 15/70、14/70。人类数据在当前 WAM 配方中没有产生正收益，不能将 VLA 路线的结论泛化到所有世界—动作模型。", "逐任务差异明显：Atom-CL 的 Hang Cup 达 10/10 ID 和 10/10 OOD，但 Push Box 从 ID 10/10 降到 OOD 0/10。表征实验还发现更高的人机相似度不一定对应更高的真机成功率。"],
    comparison: "同架构 robot-only、Atom-DH、Atom-CL；另在 WAM 架构内比较有无人类共训。",
    reproducibilityStatus: "部分可复现", implementation: ["列出数据源、清洗、80 维接口、50 步动作块与课程阶段。Atom-CL 阶段步数分别列为 100k、50k 和 97728；复现时应依表核对，不把阶段预算合并成单次 100k。"], missing: ["自采对齐集及全量处理结果的公开状态未确认。"],
    figureFile: "2609.21461-fig3.png", figureAlt: "AtomEgo 渐进式人机对齐训练流程", figureCaption: "AtomEgo 原论文方法图：人类预训练、跨本体对齐与机器人训练的组合。来源：arXiv 原图。",
  },
  {
    title: "Stable and Efficient Real-World Online VLA Post-Training via Asynchronous Replay-Anchored Policy Improvement", arxivId: "2609.22888", url: "https://arxiv.org/abs/2609.22888",
    institutions: ["Fudan University", "Shanghai Key Laboratory of Multimodal Embodied Intelligence", "Singapore Management University"], signal: "保留真实执行动作与其生成噪声，用 replay 内的价值估计更新一步 VLA，边采集边学习。",
    tags: ["Online RL", "Replay", "One-step Flow"], classification: { research: "VLA", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    motivation: "在线 VLA 更新昂贵，当前策略生成的新动作又可能超出 replay 覆盖，造成价值外推误差。",
    methodSummary: "异步运行 rollout 和训练；critic 只用记录动作估值，一步 flow actor 使用保存的初始噪声，对高优势动作进行加权似然学习。",
    architecture: "π0.5 actor 加冻结 VLM 状态编码、动作块 GRU、双 Q 头与 V 头；在线池和示范/纠正池混合采样。",
    data: "四个单任务各 10 条示范初始化后在线学习；五任务联合设置各 30 条示范，共 150 条，并加入在线成功轨迹与人工纠正。",
    experiments: "Franka FR3 四单任务各 20 次最终评测，成功率为 100%、95%、70%、80%。五任务联合每项 10 次，总成功由 26/50 提至 44/50，HG-DAgger 为 35/50。",
    novelty: "与需要当前 actor 重新采样下一动作的 critic 不同，RAPolicy 用 replay 支持的 V(s′) 自举，并复用生成噪声对齐 actor 更新。",
    strengths: "区分训练中 rollout 成功率和最终独立试验，包含同在线时间预算的基线及一步/多步更新消融。",
    limitations: "需要任务奖励和人工纠正；多任务只比较 HG-DAgger，单任务消融主要集中于插充电器，不能推断对所有 VLA 都同样有效。",
    transfer: "当机器人持续产生经验时，可把状态价值和已执行动作绑定，减少高成本动作重采样与 critic 外推。",
    technique: ["Replay 保存 (s, a_behavior, R, done, s′, z)，其中 z 是实际 rollout 使用的初始高斯噪声，人工纠正后的动作也记入 a_behavior。在线池与示范池按 50:50 采样，示范池保留纠正样本和目前最快的 20 条成功轨迹。", "价值目标为 y = R + (1 − done)γV′(s′)，V 以 τ = 0.7 的 expectile 拟合 replay 动作的 Q 值。Actor 权重为 w = exp(clip((Q − V)/0.5, −3, 3))，然后优化记录动作在固定 z 下的条件似然。", "每组进行 20 次 critic 与 5 次 actor 更新，再向 rollout 同步权重；critic 先预热 2560 次。一步 flow 不增加多步 teacher，也不对 critic 的动作梯度做反传，避免优化方向依赖 replay 外的动作。"],
    evaluation: ["最终四单任务共 80 次试验，RAPolicy 为 69/80；相同 SFT 起点分别只有 1/20、3/20、0/20、2/20。插充电器与 HIL-SERL 同为 20/20，其他三项相对最强已测基线分别提升 15、40、30 个百分点。", "五任务联合训练 120 分钟，最终为 44/50 对初始 26/50、HG-DAgger 35/50；两种堆叠合计由 3/20 提至 15/20。训练曲线约 90% 的 rollout 成功率与这组最终试验是不同指标。", "插充电器消融中，一步更新约 30 分钟收敛；两步、三步在 40 分钟的 rollout 成功率为 63.6%、42.8%。改用预测动作自举的版本，每组更新时间超过三倍，40 分钟约 10%；这些是特定任务下的在线曲线。"],
    comparison: "异步 ALOE、EXPO-FT、插接任务 HIL-SERL；联合任务 HG-DAgger；flow 步数、critic 目标和 actor 损失消融。",
    reproducibilityStatus: "部分可复现", implementation: ["batch 112；8 张 RTX 3090 中 1 张 rollout、7 张学习；双 RGB 视角。插接动作块 H=5，其他 H=10，终点成功奖励 10，其余 0。"], missing: ["完整在线轨迹、人工介入日志和可部署检查点未确认公开。"],
    figureFile: "2609.22888-fig2.png", figureAlt: "RAPolicy 异步采集、replay 价值学习和一步策略更新", figureCaption: "Figure 2 · Replay 保存真实执行动作及生成噪声，连接异步采集与策略更新。来源：arXiv 原图。",
  },
  {
    title: "EgoWild2Dex: Learning Dexterous Robotic Manipulation from In-the-Wild Human Experience", arxivId: "2609.23755", url: "https://arxiv.org/abs/2609.23755",
    institutions: ["The University of Hong Kong", "Kinetix AI"], signal: "用几何视角对齐和三阶段人机训练，把自然场景人类数据接入双臂灵巧操作。",
    tags: ["Human-to-Robot", "View Alignment", "Dexterous Manipulation"], classification: { research: "VLA", training: "Pre-training", data: "UMI / Ego / Human Video", deployment: "跨本体迁移", platforms: ["机械臂", "灵巧手"] },
    motivation: "第一人称人类视频与固定机器人相机存在视角、动作和接触差异，少量真机示范直接微调不易完成长程灵巧任务。",
    methodSummary: "GeoFormer 学习人机图像间的投影变换；先用野外人类数据学习，再做任务相关人机共训，最后以机器人专家与 DAgger 恢复数据细化执行。",
    architecture: "视觉语言骨干与 flow-matching 动作专家预测双臂关节/手部命令；GeoFormer 用级联 CNN+MLP 更新八维单应变换参数。",
    data: "EgoWild 538.9 小时、179049 段；每项下游任务另有 1000 条 ego、1000 条 glove、100 条机器人专家示范及 10 段 DAgger 恢复数据。",
    experiments: "开箱、粘模型、冰水制作三个真机长程任务，各方法每任务 10 次。完整系统成功率 90%、100%、100%；未见包装内容的零样本成功均值为 33.3%。",
    novelty: "既保持机器人原生动作空间，又显式对齐人类视角；其提升来自多阶段数据与恢复训练的整体方案，而非只加一个图像变换。",
    strengths: "有训练阶段、视角对齐、数据量和未见物体实验；将完成分数与整任务成功分开报告。",
    limitations: "仍需任务相关的大量人类数据及真机纠正；每条件仅 10 次，未见物体成功率明显低于训练设置。",
    transfer: "可以先用人类数据学动作先验，再通过视角对齐和少量真实恢复样本处理本体与接触差异。",
    technique: ["GeoFormer 用八维参数构造无迹矩阵 P，再令 T = exp(P) 得到投影变换。级联模块逐次修正 T，并以对抗和几何约束训练；部署于共训输入时用逆变换把 ego 图像对齐到机器人视角，而不是逐帧重建 3D 后补画背景。", "所有数据经标定、手部重定向和 IK 转为同一双臂关节/手部命令，三个阶段持续使用相同 flow-matching 目标。第一阶段学习广泛人类操作，第二阶段混合对齐 ego、glove 和机器人示范，第三阶段专门学习真实执行和失败恢复。", "GeoFormer 在后续策略共训中冻结。最终阶段的 10 段 DAgger 恢复来自策略访问的失败状态，不能将这部分在线纠正能力归因于纯离线人类视频预训练。"],
    evaluation: ["三任务各 10 次，完整系统共 29/30 成功；直接对 100 条机器人示范微调的 π0.5 为 2/30。两者使用的人类数据和恢复经验不同，因此这一差距描述完整流程，不是等数据模型结构比较。", "开箱阶段消融：只有机器人细化为 0%，加广泛人类预训练为 20%，仅加任务相关共训为 40%，两阶段都保留为 70%，再加 DAgger 达 90%。同任务用原始 ego、投影补画和 GeoFormer 分别为 60%、80%、90%。", "未见包装内容的电缆、纸巾、可乐为 30%、30%、40%；少量适配过的三种内容均值 70%。GeoFormer 单帧对齐 7.43 ms，投影+补画 162.58 ms，计时不含图像解码和模型加载。"],
    comparison: "机器人数据直接微调 π0/π0.5/GR00T-N1.7，以及阶段删除、视角变换和 DAgger 消融。",
    reproducibilityStatus: "部分可复现", implementation: ["公开正文给出单应参数化、损失、动作重定向、分阶段数据组成与 10 次试验协议；机器人数据包括 100 条专家示范及另收的 10 段恢复。"], missing: ["全量 EgoWild、任务数据和可直接复现权重的开放状态未确认。"],
    figureFile: "2609.23755-fig2.png", figureAlt: "EgoWild2Dex 的 GeoFormer 人机视角对齐与策略共训", figureCaption: "Figure 2 · GeoFormer 学习投影对齐，并将对齐的人类图像用于人机共训。来源：arXiv 原图。",
  },
  {
    title: "CompVLA: A Variable Compliance Vision-Language-Action Model for Contact-rich Manipulation", arxivId: "2609.23614", url: "https://arxiv.org/abs/2609.23614",
    institutions: ["Seoul National University", "Microsoft Research Asia"], signal: "让 VLA 同时给出运动、刚度与虚拟位移，在执行时不读取力传感器也能表达接触顺应性。",
    tags: ["Compliance", "Impedance", "Contact-rich"], classification: { research: "VLA", training: "Post-training", modalities: ["Force / Torque"], platforms: ["机械臂", "夹爪"] },
    motivation: "固定刚度的位姿策略难同时处理主动施力与受约束运动；只输出运动轨迹容易在擦拭或绕轴接触时失效。",
    methodSummary: "由示范中的力/力矩构造顺应标签，联合训练运动与顺应专家，输出六维刚度和虚拟位移；后者改变平衡点，使阻抗控制器产生主动接触力。",
    architecture: "π0 的 PaliGemma/Gemma 动作分支外增加顺应专家，读取共享视觉语言特征与参考 TCP 位姿；控制器组合运动、各向异性刚度及平衡点偏移。",
    data: "Franka FR3 四任务各 100 条示范；训练记录三视角 RGB、机器人状态与 ATI 力/力矩，部署时不需要将 F/T 读数送入策略。",
    experiments: "三接触任务每项 20 次、重复三轮，平均任务指标 67.1±7.2，对 π0 的 29.2±9.2、ForceVLA 的 54.4±4.3；擦除使用擦除比例，不能把该均值解释为统一成功率。",
    novelty: "不仅预测刚度，还学习虚拟位移以产生主动接触力；擦除消融中去掉虚拟位移后指标由 96% 降至 7%。",
    strengths: "用运动/刚度/虚拟位移消融说明各部分作用，并报告不占优的杯子任务及常规拾放结果。",
    limitations: "四任务单平台；杯子任务低于 ForceVLA，接触表示主要依赖单个方向，不能自动修复严重错误的参考轨迹。",
    transfer: "对于接触操作，动作接口可包含控制器参数，而不只包含目标位姿；训练时的力标签可以与部署传感输入解耦。",
    technique: ["模型保留参考运动专家，并另设同类顺应专家，输出六维刚度与六维虚拟位移。两分支共同做 flow matching：L = L_motion + L_compliance。顺应分支还读取参考 TCP 的位姿与夹爪信息，使力学输出与当前运动意图对应。", "控制器将刚度按接触方向旋转：K = R_c diag(k) R_cᵀ，并基于偏移后的平衡点产生 F = −KX_e − CV_e。调小某方向刚度允许被动顺应，移动虚拟平衡点则可主动推压物体，两者不是同一种作用。", "训练标签通过示范 F/T 和期望控制轨迹构造，部署仅由图像与本体状态预测。它移除了策略对实时 F/T 输入的依赖，不意味着机器人不需要阻抗控制、标定或训练阶段的测力设备。"],
    evaluation: ["擦除、绕物体 pivot、杯子接触三任务各 20 次、三轮。CompVLA 分别为 92.9±3.7、73.3±10.4、35.0±10.0；前一项为擦除比例，后两项为任务成功率。ForceVLA 对应 68.1、45.0、50.0，杯子任务更好。", "常规 Pick-and-Place 中 CompVLA 为 76.7±5.8%，π0 为 80±10%，没有显示全面优势。十次试验的控制消融中，擦除完整版本为 96%，去虚拟位移 7%；pivot 固定刚度为 40%，完整版本为 70%。", "杯子任务中，CompVLA 的 35.0% 低于 ForceVLA 的 50.0%；常规拾放同样未超过 π0。"],
    comparison: "π0、ForceVLA、TAVLA；去虚拟位移、固定刚度，以及常规拾放对照。",
    reproducibilityStatus: "部分可复现", implementation: ["动作块 25、去噪 10 步；传感同步为 10 Hz；平移刚度范围 200–500 N/m、转动刚度 10–30 N·m/rad。三视角 D435i、ATI Axia F/T 与 FR3 控制器设置在正文披露。"], missing: ["完整控制实现、数据和检查点的可下载状态尚未确认。"],
    figureFile: "2609.23614-fig1.png", figureAlt: "CompVLA 运动专家、顺应专家与阻抗控制结构", figureCaption: "CompVLA 原论文结构图：运动与顺应分支联合预测，再由阻抗控制器执行。来源：arXiv 原图。",
  },
];

export const paperDaily20260921 = entries.map(makePaper);
