import type { Paper } from "./site-data";

// Independently selected from the 2026-07-20—2026-07-23 daily candidate pools.
// These records do not read or reuse either report's previous selected-paper list.
export const paperDaily20260724RerunAdditions: Paper[] = [
  {
    rank: 1,
    title: "Robots Acquire Manipulation Skills in Seconds from a Single Human Video",
    arxivId: "2607.20033",
    url: "https://arxiv.org/abs/2607.20033",
    institutions: ["Beijing Institute of Technology", "X Square Robot", "Tsinghua University"],
    signal: "HOST 在推理时读取一段人类视频，把任务进度翻译成机器人未来观察，再由未来观察生成动作",
    tags: ["Human Video", "One-shot Skill Acquisition", "Cross-embodiment"],
    classification: {
      research: "VLA",
      data: "UMI / Ego / Human Video",
      platforms: ["机械臂", "夹爪"],
    },
    resources: [
      { label: "项目页", url: "https://host-site.host-robotics.workers.dev/" },
      { label: "GitHub", url: "https://github.com/CGuangyan-BIT/HOST" },
    ],
    motivation: "让机器人学新技能通常要采集机器人示范并重新训练，既慢又可能遗忘旧技能。HOST 尝试把一次人类演示直接变成推理时条件。",
    methodSummary: "先估计机器人当前执行进度，再预测与人类演示下一阶段对齐的机器人未来观察，最后由 observation-conditioned action model 输出动作。训练目标通过共享任务进度流形，把机器人轨迹与人类视频对齐。",
    architecture: "三段级联分别完成 progress estimation、future observation translation 和 action prediction；人类视频只提供任务过程，模型在自身本体视角中生成将要到达的状态。",
    optimization: "主模型离线训练；新技能获取发生在 inference time，不对模型做梯度更新。共享进度表征和 future target 均在训练期由机器人轨迹—人类视频配对构造。",
    data: "Stage 1 使用 193,462 条机器人轨迹、覆盖 229 个任务；Stage 2 使用 5,847 对人类视频—机器人轨迹。评测含 50 个新任务，每个任务只给一段人类演示。",
    experiments: "50 个新任务、每任务 20 次真实机器人试验；平均 29 秒完成技能获取，平均成功率 62%，相对 zero-shot baseline 提高 45 个百分点，并超过每任务用 50 条机器人示范微调的基线。",
    novelty: "相较直接模仿跨本体视频或为每个任务微调，HOST 把跨本体差异放到未来观察翻译中，并通过共享进度流形把‘人做到哪一步’转成‘机器人下一步应看到什么’。",
    strengths: "任务数量、真实试验次数和基线覆盖较充分；一次视频、无需梯度更新与 29 秒获取时间直接支撑快速学习主张。",
    limitations: "62% 仍意味着大量失败，表现依赖人类演示可被训练期进度表征覆盖；开放环境、长程恢复和强接触任务的适用范围仍有限。",
    transfer: "可把人类视频作为任务级条件接到现有 VLA，尤其适合先预测机器人可实现的中间未来，再做动作解码，而非直接把人类像素动作映射到机器人关节。",
    experimentDetails: [
      {
        title: "单视频技能获取与保留测试",
        setup: "50 个新操作任务，每项只给一条人类视频；真实机器人每任务执行 20 次，共 1,000 次 rollout，并同时检查已掌握技能是否遗忘。",
        comparisons: "zero-shot 基线、每任务使用 50 条机器人示范的 fine-tuning 基线，以及去除 progress/future translation 等组件的版本。",
        results: [
          "HOST 平均成功率为 62%，相对 zero-shot baseline 提高 45 个百分点。",
          "相较每任务 50 条机器人示范的微调基线，HOST 使用的任务示范数量少 50 倍，技能获取速度快 507 倍。",
          "一次人类视频平均约 29 秒即可成为推理条件；结果还显示新技能加入后旧技能整体保持。",
        ],
      },
    ],
    reproducibilityDetails: {
      status: "资源较完整",
      verifiedResources: ["项目页公开完整演示；GitHub 已发布 alignment、target coupling、数据预处理和 policy training 模块。"],
      implementation: ["Qwen3-VL-Embedding-8B + TCC/Smooth-DTW alignment；Wan2.2-TI2V-5B video expert；dual-expert autoregressive diffusion；Stage 1 500K steps、Stage 2 100K steps；论文规模为 64 GPUs。"],
      missing: ["仓库不直接提供完整论文规模数据与真机闭环控制入口；发布的 recorded-data evaluation 不会直接驱动机器人。"],
    },
    deepDive: {
      lead: "HOST 的关键中介不是人类动作，而是任务进度与机器人未来观察。这样可以把本体差异隔离在‘人类过程到机器人状态’的翻译里。",
      sections: [
        {
          title: "自对齐的三级预测",
          paragraphs: [
            "第一阶段比较当前机器人观察与演示过程，估计任务已经推进到哪里；第二阶段在演示中找到下一段进度，并把它翻译为机器人自身视角下应出现的未来；第三阶段再根据当前观察和该未来目标生成动作。",
            "训练时，机器人轨迹和人类视频被映射到共享进度坐标，监督目标跟随视频未来而不是固定时间偏移。因而不同执行速度下，模型仍可对齐语义阶段。",
          ],
        },
      ],
      equations: [
        {
          name: "进度条件动作链",
          expression: "pₜ = P(oₜ, vʰ),   ôₜ₊ = F(oₜ, vʰ, pₜ),   aₜ = π(oₜ, ôₜ₊)",
          explanation: "先定位演示进度，再生成机器人可实现的未来观察，最后用该未来条件化动作。",
        },
      ],
      experimentReading: [],
      reflections: [],
    },
    figures: [
      {
        src: "/report-assets/2026-07-24/2607.20033-method.png",
        alt: "HOST 从单段人类视频估计任务进度、预测机器人未来观察并生成动作的三级框架",
        caption: "HOST 方法总览：progress estimation、robot future prediction 与 action prediction。图片取自 arXiv 原论文。",
      },
    ],
  },
  {
    rank: 2,
    title: "FELT: Generating Tactile Signals from Vision for Visuo-Tactile Manipulation",
    arxivId: "2607.20683",
    url: "https://arxiv.org/abs/2607.20683",
    institutions: ["University of Southern California", "Columbia University", "Starpilot"],
    signal: "从腕部 RGB 生成双指压力图或 latent，在训练和部署时都不要求真实触觉传感器",
    tags: ["Tactile Generation", "Diffusion Policy", "Contact-rich"],
    classification: { research: "表征学习", modalities: ["Tactile"], data: "数据增强", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://felt-tactile.github.io/" }],
    motivation: "真实触觉数据昂贵、易损且难标准化，视觉策略又难处理接触歧义。",
    methodSummary: "冻结视觉编码器，双分支 query decoder 分别预测左右指面压力，并把生成图像或中间 latent 接入 Diffusion Policy。",
    architecture: "DINOv2 patch features 连接两个 per-finger query decoder，跨指 gated exchange 保留非对称接触关系，panel-aware head 输出压力。",
    optimization: "先训练视觉到触觉生成器，再以 imitation learning 训练任务策略，不使用 RL。",
    data: "2,700+ 条 UMI-style 示范、约 2.6M RGB—触觉对；四项 xArm 任务各 60 条策略示范。",
    experiments: "四项真机任务每方法各 20 次；FELT latent 在所有最终任务指标上超过视觉-only，Triangle Peg 从 50% 提升到 90%。",
    novelty: "显式保留双指触觉拓扑，并验证生成触觉不只像真实信号，也能改善下游控制。",
    strengths: "生成质量、结构消融、真实控制和延迟形成完整证据链。",
    limitations: "接触区域需要在 RGB 中可见，严重遮挡和跨传感器迁移尚未覆盖。",
    transfer: "可将压力图换成 contact phase、slip 或 failure-risk latent，为视觉数据补充接触监督。",
    figures: [{ src: "/report-assets/2026-07-24/2607.20683-architecture.png", alt: "FELT 从腕部 RGB 生成双指触觉表征的结构", caption: "Figure 2 · FELT 触觉生成框架。图片取自 arXiv 原论文。" }],
  },
  {
    rank: 3,
    title: "PhysCoRe: Physics-Corrected Residual World Models for Material-Aware Deformable Dynamics",
    arxivId: "2607.20653",
    url: "https://arxiv.org/abs/2607.20653",
    institutions: ["Georgia Institute of Technology"],
    signal: "保留 MPM 的物理结构，同时学习材料参数、动力学残差与逐粒子置信度",
    tags: ["World Model", "Deformable Object", "Uncertainty"],
    classification: { research: "WM", training: "Pre-training", modalities: ["Depth / RGB-D", "Point Cloud / 3D"], platforms: ["机械臂", "夹爪"], deployment: "Real2Sim" },
    motivation: "解析模型需要逐对象优化，纯学习模型又容易在分布外违背物理。",
    methodSummary: "Material-from-Motion 从 RGB-D 运动估计粒子材料和置信度，Residual-from-Dynamics 学习 MPM 未建模的动力学误差。",
    architecture: "观测编码器、逐粒子材料头、可微 MPM rollout 与残差校正器串联，置信度同时用于分析主动探测。",
    optimization: "两个学习模块离线训练，新物体只用前半段运动做 feed-forward 材料识别。",
    data: "12 个真实 episode，覆盖 rope、towel、plush bear 与 Play-Doh；另有 KUKA + Robotiq 主动探测。",
    experiments: "相对 PhysTwin，弹性/弹塑性对象 Chamfer 距离下降 43.7%/30.5%；材料识别耗时 11.4 秒，对比 930 秒。",
    novelty: "用学习模块校正而非替代物理，并显式输出逐粒子材料不确定性。",
    strengths: "真实 RGB-D、物理/残差消融和速度比较均围绕同一建模假设。",
    limitations: "只有 12 个 episode，主动探索尚未与策略闭环。",
    transfer: "可按材料不确定性选择触碰区域，并用接触事件门控残差模型。",
    figures: [{ src: "/report-assets/2026-07-24/2607.20653-overview.png", alt: "PhysCoRe 的材料估计、MPM rollout 与残差校正", caption: "Figure 1 · PhysCoRe 方法总览。图片取自 arXiv 原论文。" }],
  },
  {
    rank: 4,
    title: "Evolving Cache Schedules for Fast Diffusion Policy Inference",
    arxivId: "2607.20293",
    url: "https://arxiv.org/abs/2607.20293",
    institutions: ["Xidian University", "Tsinghua University"],
    signal: "EVO 用离线进化搜索决定每个 diffusion block 在每个去噪步是否刷新缓存",
    tags: ["Diffusion Policy", "Inference Acceleration", "Caching"],
    classification: { research: "其他", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "GitHub", url: "https://github.com/pillom/EVO" }],
    motivation: "固定间隔缓存忽略不同网络块与去噪时刻的冗余差异，容易在速度和闭环成功率之间做出次优折中。",
    methodSummary: "把完整 block—timestep 刷新表编码为个体，以闭环任务表现和计算量为适应度做进化搜索；冗余感知初始化与目标条件 early stop 减少搜索成本。",
    architecture: "不修改预训练 diffusion policy；运行时按照二值 schedule 选择重算当前 block，或复用上一去噪步的中间特征。",
    optimization: "training-free schedule search。搜索使用 population 30、elite 10、最多 30 generations，候选先以 20 次 rollout 粗评，达标后以 50 次复核。",
    data: "在 RoboMimic 与 Push-T 等 manipulation benchmark 的既有 diffusion policies 上搜索和评测；不额外采集示范数据。",
    experiments: "在接近原策略成功率时，动作生成最高加速 8.05 倍，FLOPs 从 15.77G 降至最低 1.96G；最终策略以 3 个种子、每种子 50 次 rollout 复核。",
    novelty: "相较逐层固定或局部贪心缓存，EVO 联合优化整个 block—timestep lattice，并直接把闭环 rollout 性能作为约束。",
    strengths: "训练免费、可插拔，报告 FLOPs、延迟、闭环成功率和搜索消融，代码已公开。",
    limitations: "schedule 依赖目标 policy 与评测任务，迁移到新分布可能要重新搜索；搜索本身消耗大量 rollout，真机收益未直接验证。",
    transfer: "可先在仿真或 replay 环境搜索安全 schedule，再在真机以小规模 rollout 校准，适合已有 diffusion policy 的部署加速。",
    experimentDetails: [{ title: "闭环性能约束下的缓存搜索", setup: "对多个预训练 diffusion policy 搜索 block—timestep schedule，最终配置以 3 seeds × 50 rollouts 复核，并在 RTX 4090D 上测计算。", comparisons: "原始全计算、固定间隔缓存、block-wise adaptive caching，以及无冗余初始化/无 early stop 的 EVO。", results: ["最高动作生成加速为 8.05×，FLOPs 从 15.77G 降到 1.96G。", "不同任务得到不同的非均匀 schedule，说明固定刷新间隔不能覆盖所有 block 和 timestep。", "最终候选用更多 rollout 复核，减少 20-rollout 粗评中的偶然高分，但没有真实机器人部署结果。"] }],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["GitHub 已公开；论文给出搜索空间、主要超参、硬件和闭环评测协议。"], implementation: ["population=30；elite=10；最多 30 generations；20-rollout search；50-rollout confirmation；RTX 4090D。"], missing: ["真实机器人 latency、跨任务直接复用 schedule 的稳定性尚未验证。"] },
    deepDive: { lead: "EVO 把缓存策略当作一个全局离散优化问题，而不是为所有层设定同一刷新周期。", sections: [{ title: "block—timestep 联合调度", paragraphs: ["一个候选 schedule 覆盖每个 transformer block 和每个 denoising timestep。若该位置不刷新，就复用最近一次特征，从而跳过重复计算。", "进化搜索先用块间冗余统计生成较合理的初始种群，再通过任务回报与计算预算选择、交叉和变异。达到目标性能后用更大 rollout 数复核并提前停止。"] }], equations: [{ name: "受约束调度目标", expression: "S* = argminₛ FLOPs(S)  s.t.  J(πS) ≥ Jtarget", explanation: "在闭环表现不低于目标阈值的前提下寻找计算量最小的缓存刷新表。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-24/2607.20293-method.png", alt: "EVO 在 diffusion policy 的 block 与 timestep 网格上进化缓存刷新计划", caption: "EVO 的 schedule 编码、进化搜索与缓存推理流程。图片取自 arXiv 原论文。" }],
  },
  {
    rank: 5,
    title: "KineBench: Benchmarking Embodied World Models via IDM-Free Kinematic Grounding",
    arxivId: "2607.19876",
    url: "https://arxiv.org/abs/2607.19876",
    institutions: ["TeleAI", "National University of Singapore", "Fudan University", "Tsinghua University", "Northwestern Polytechnical University Shenzhen Research Institute"],
    signal: "不用学习式 inverse dynamics，从生成视频逐帧恢复 6D 末端轨迹并在物理仿真中闭环验证 world model",
    tags: ["World Model Evaluation", "Kinematic Grounding", "Benchmark"],
    classification: { research: "WM", modalities: ["Point Cloud / 3D"], data: "合成 / 仿真数据", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "GitHub", url: "https://github.com/Tele-AI/KineBench" }],
    motivation: "用 learned inverse dynamics 从生成视频抽动作时，world model 错误与动作提取器 OOD 错误混在一起，难以判断失败来源。",
    methodSummary: "级联检测、单目深度、6D pose 与跟踪模型，从每帧恢复末端位姿；轨迹直接送入 ManiSkill3 执行，并用成功率、SPARC 平滑度和 manipulability 评估。",
    architecture: "显式管线由 YOLO、MoGe v2、FoundationPose 和坐标变换组成，不训练任务专用 IDM；仿真器负责检查恢复轨迹是否真正完成任务。",
    optimization: "这是评测基准，不训练新 world model；各生成模型在统一输入和轨迹提取流程下比较。",
    data: "ManiSkill3 的 20 个 manipulation tasks，分为 basic execution、task transfer、visual OOD 与 complexity-conditioned scaling 四组。",
    experiments: "对多种 frontier video/world models 做闭环评测，发现性能随任务复杂度呈非线性饱和；论文同时报告轨迹平滑度与运动学可行性，而非只看视频相似度。",
    novelty: "相较依赖 IDM 的闭环评测，KineBench 用显式视觉几何恢复 6D 轨迹，减少未见对象和场景下动作提取模型的归因歧义。",
    strengths: "任务覆盖和指标层次清晰，公开代码；显式管线使失败更容易定位。",
    limitations: "没有真机，性能依赖检测、深度和姿态 foundation models；显式管线失败仍可能被误归因给 world model。",
    transfer: "可作为 WAM/视频模型的执行前评测层，并将 pose 置信度纳入结果，避免把抽取器低置信样本当作模型失败。",
    experimentDetails: [{ title: "四级 world-model 闭环评测", setup: "20 个 ManiSkill3 任务覆盖基础执行、任务迁移、视觉 OOD 和复杂度扩展；生成视频转 6D 轨迹后在仿真中执行。", comparisons: "多种 frontier world/video models；同时分析 IDM-based 评测与显式 grounding 的误差来源。", results: ["闭环成功率与像素/感知视频质量并不完全一致。", "SPARC 和 Maruyama manipulability 能区分看似完成任务但轨迹抖动或接近奇异位形的结果。", "规模增大带来的收益受任务复杂度约束，论文观察到非线性饱和而非稳定线性增长。"] }],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["GitHub 与 benchmark 说明已公开。"], implementation: ["YOLO + MoGe v2 + FoundationPose；20 ManiSkill3 tasks；SPARC；Maruyama Manipulability Index。"], missing: ["各外部生成模型权重与推理成本不一定全部开放；没有真实相机和真实机器人误差测试。"] },
    deepDive: { lead: "KineBench 把‘视频是否物理正确’落到一条可执行的 6D 末端轨迹上，但同时承认显式视觉模块也会带来自己的误差。", sections: [{ title: "从像素到可执行轨迹", paragraphs: ["检测器先定位机器人和目标，单目深度恢复尺度，6D pose 模块逐帧估计末端姿态；坐标变换把视觉轨迹转到仿真机器人坐标。", "仿真执行给出任务成功，SPARC 衡量运动平滑度，manipulability 衡量轨迹是否逼近运动学退化区域。这三个指标分别覆盖结果、过程和机器人可行性。"] }], equations: [{ name: "谱弧长平滑度", expression: "SPARC = −∫₀^{ωc} √((1/ωc)² + (dV̂(ω)/dω)²) dω", explanation: "由速度谱形状量化轨迹平滑度，避免只根据终点成功判断动作质量。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-24/2607.19876-pipeline.png", alt: "KineBench 从生成视频提取 6D 末端轨迹并在 ManiSkill3 闭环执行的显式管线", caption: "KineBench 的 IDM-free kinematic grounding 与闭环评测流程。图片取自 arXiv 原论文。" }],
  },
  {
    rank: 6,
    title: "AXIS: A Growable Community-Driven Data Engine for Scalable Robot Manipulation",
    arxivId: "2607.21588",
    url: "https://arxiv.org/abs/2607.21588",
    institutions: ["Axis Robotics", "University of California, Berkeley", "Georgia Institute of Technology"],
    signal: "把浏览器遥操作、任务生成、自动验收、轨迹清洗和仿真增强连成可持续扩展的数据引擎",
    tags: ["Robot Data", "Data Quality", "Continual Pre-training"],
    classification: { research: "VLA", training: "Pre-training", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    motivation: "机器人数据平台往往依赖专用硬件、集中操作员和固定任务集，规模扩大后成功标签、轨迹噪声与任务覆盖难以共同维护。",
    methodSummary: "用户通过浏览器遥操作采集，系统生成并验证新任务；数据进入训练前经过成功检测、质量过滤、轨迹平滑，以及视觉和物理增强，并按 task snapshot 做时间一致的 held-out 评测。",
    architecture: "数据引擎连接 web teleoperation、task proposal/validation、quality pipeline、simulation augmentation 与 benchmark registry；策略侧以 π0.5 continual pretraining 验证数据价值。",
    optimization: "对 π0.5 做持续预训练，并按数据规模、过滤组件和 augmentation 分别对照；重点是数据系统而非新 action head。",
    data: "207 个任务、50K+ 示范轨迹，并经增强得到约 60K variants；数据以任务快照组织，避免持续增长时训练/测试定义漂移。",
    experiments: "π0.5 在 AXIS 上持续预训练后总成功率提高 5.8 个百分点，并比 RoboCasa365 预训练高 37.3 个百分点；LIBERO-Plus overall 达 88.8%，vanilla 为 83.9%。",
    novelty: "相较一次性数据集，AXIS 把社区采集、自动任务扩展、质量控制和版本化评测作为同一 growable engine。",
    strengths: "数据规模、held-out 协议、过滤与增强消融、跨分布 benchmark 和 scaling 分析较完整。",
    limitations: "社区数据的一致性仍依赖自动验收准确率；真机主要用于采集与定性展示，核心大规模结果来自仿真 benchmark。",
    transfer: "可借鉴 task snapshot、自动成功检查和轨迹平滑，将日报关注的数据质量维度落实为可测的清洗收益。",
    experimentDetails: [{ title: "数据规模、质量管线与 VLA 预训练", setup: "207 个任务、50K+ demonstrations，按 task snapshot 划分；用 π0.5 在 LIBERO-Plus 等协议上评测规模与扰动泛化。", comparisons: "vanilla π0.5、RoboCasa365 continual pretraining、不同 AXIS 数据规模，以及移除过滤/平滑/增强的版本。", results: ["AXIS continual pretraining 将 π0.5 overall success 提高 5.8 个百分点。", "相对 RoboCasa365 预训练模型高 37.3 个百分点，最大收益出现在布局、传感器噪声和相机扰动。", "LIBERO-Plus overall 为 88.8%，vanilla 为 83.9%；结果支持数据量和质量流程共同作用。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["论文公开数据规模、任务快照、评测协议和主要 pipeline 组件；项目页可访问。"], implementation: ["browser teleoperation；success checking；quality filtering；trajectory smoothing；visual/physics augmentation；π0.5 continual pretraining。"], missing: ["全部社区数据、后端基础设施和自动验收模型是否完整开源，需以项目 release 为准。"] },
    deepDive: { lead: "AXIS 的贡献不是单次扩大数据，而是设计增长后仍能追踪质量和泛化的数据生命周期。", sections: [{ title: "从采集到版本化评测", paragraphs: ["浏览器降低采集门槛，自动任务生成扩展覆盖，但数据不会直接进入训练：成功检测先去掉失败轨迹，平滑器处理遥操作抖动，视觉和物理扰动再生成受控变体。", "task snapshot 固定某个时间点的任务和数据版本，使后续新增任务不污染历史 held-out 测试。策略 scaling 因而能够区分数据更多与测试集合变化。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-24/2607.21588-overview.png", alt: "AXIS 从浏览器遥操作、任务增长、自动清洗到策略训练和评测的数据引擎", caption: "AXIS growable data engine 总览。图片取自 arXiv 原论文。" }],
  },
  {
    rank: 7,
    title: "Scale Up Strategically: Learning Compositional Generalization via Bias-Aware Evaluation and Data Collection for Robotic Manipulation",
    arxivId: "2607.21582",
    url: "https://arxiv.org/abs/2607.21582",
    institutions: ["Northeastern University", "NVIDIA"],
    signal: "诊断语言 factor bias，并把固定采集预算投向 verb、size 等 grounding 弱项",
    tags: ["Compositional Generalization", "Data Selection", "Language Grounding"],
    classification: { research: "VLA", training: "Post-training", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    motivation: "增加数据不保证策略真正 grounding 指令，模型可能只依赖颜色等显著因素。",
    methodSummary: "Factor Dominance Rate 衡量因素两两偏置，Factor Dominance Hierarchy 汇总优先级，再按弱项重分配固定示范预算。",
    architecture: "模型无关的诊断与采样层，不改 VLA backbone。",
    optimization: "依据因素偏置做后训练数据选择，不使用 RL。",
    data: "六种 foundation policies；UR5 + GELLO 三类真机任务，每任务 16 种语言组合，并比较 100/200 条示范预算。",
    experiments: "每个真机 checkpoint 48 次 rollout；偏置感知采样达到 54.2%–66.7%，随机采样为 37.5%–50.0%。",
    novelty: "把语言因素偏置从诊断指标转成下一批示范的预算分配。",
    strengths: "固定预算对照清楚，仿真与真机结果方向一致。",
    limitations: "因素空间需要人工离散，开放词汇和长程任务仍未验证。",
    transfer: "可先测试 verb、object、spatial、force-level 等弱项，再定向采集失败组合。",
    figures: [{ src: "/report-assets/2026-07-24/2607.21582-overview.png", alt: "从 instruction factor 偏置诊断到定向数据采集的流程", caption: "Scale Up Strategically 的 bias-aware evaluation 与 data collection。图片取自 arXiv 原论文。" }],
  },
  {
    rank: 8,
    title: "GuidedAttention: Interpretable and Correctable Visual Attention for OOD-Robust Robot Manipulation via Imitation Learning",
    arxivId: "2607.21049",
    url: "https://arxiv.org/abs/2607.21049",
    institutions: ["CNRS-AIST Joint Robotics Laboratory", "AIST"],
    signal: "用户只在首帧纠正注意关键点，跟踪器随后传播纠正以恢复 OOD 操作",
    tags: ["Guided Attention", "Human Correction", "OOD"],
    classification: { research: "表征学习", training: "BC", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://mmurooka.github.io/guided-attention-project-page" }],
    motivation: "端到端策略的注意位置不可见也难纠正，位置或外观变化时容易继续关注训练背景。",
    methodSummary: "attention encoder 预测任务关键点，用户可在 rollout 首帧覆盖一次，跟踪模块传播关键点，Diffusion Policy 以纠正后的表征为条件。",
    architecture: "多视角 attention/keypoint encoder、人工 override 路径、视觉 tracker 与 diffusion action head。",
    optimization: "imitation learning；训练时随机路由预测关键点与人工 override 路径。",
    data: "三项仿真任务；UR5e 三项真机任务，每项 32 条遥操作示范。",
    experiments: "真机每条件 3 seeds × 10 rollouts；三任务 positional OOD 平均 71.1%，普通 DP 为 30%。",
    novelty: "把可解释注意变成一次性可编辑接口，而不是只展示 heatmap。",
    strengths: "干预成本、OOD 条件与性能收益直接关联。",
    limitations: "二维少量关键点难覆盖深度、重遮挡和复杂可变形状态。",
    transfer: "可扩展到 3D object/contact tokens，只在不确定性高时请求纠正。",
    figures: [{ src: "/report-assets/2026-07-24/2607.21049-architecture.jpg", alt: "GuidedAttention 的关键点注意编码器、人工纠正与扩散动作策略", caption: "Figure 2 · GuidedAttention 策略结构。图片取自 arXiv 原论文。" }],
  },
  {
    rank: 9,
    title: "Ordered Action Tokens for Visuomotor Policy Learning",
    arxivId: "2607.21670",
    url: "https://arxiv.org/abs/2607.21670",
    institutions: ["Harvard University", "Stanford University"],
    signal: "让 action token 前缀先表达粗动作，后续 token 逐步补充残差细节，从而按时延动态截断",
    tags: ["Action Tokenization", "Autoregressive Policy", "Anytime Inference"],
    classification: { research: "表征学习", training: "Pre-training", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [
      { label: "项目页", url: "https://ordered-action-tokenization.github.io/" },
      { label: "GitHub", url: "https://github.com/Chaoqi-Liu/OAT" },
    ],
    motivation: "逐维离散动作序列太长，普通 learned tokenizer 的 token 又没有顺序，截断前缀时无法保证仍能解码有效动作。",
    methodSummary: "Transformer registers 压缩 action chunk，经 finite scalar quantization 得到离散 token；每个 token prefix 都被监督重建完整动作，后续 token 只需细化剩余误差。",
    architecture: "action encoder、ordered registers、FSQ quantizer 与 prefix decoder 组成 tokenizer；它既可接 autoregressive controller，也可把 token loss 用于 flow action expert 的 VLM context co-training。",
    optimization: "先预训练 action tokenizer，再训练下游 autoregressive policy 或 token-co-training policy；ordering loss 和 prefix reconstruction 共同约束 token 顺序。",
    data: "覆盖五个仿真 benchmark、60+ manipulation tasks 和两项真实机器人任务；在三种 policy backbone 上评测。",
    experiments: "真实任务中使用 8 个 token 时两项各成功 16/20；仿真中 OAT 在三种 backbone 上持续优于或匹配其他 tokenizer，并允许按 token 数交换时延与精度。",
    novelty: "同时追求高压缩、任意前缀可解码和有序 token 空间；相较 unordered VQ tokenizer，前缀不只是 latent 子集，而是有效的粗到细动作。",
    strengths: "backbone、benchmark 与 token 数消融较充分，项目和代码已公开，并有真实机器人测试。",
    limitations: "token 顺序由训练目标诱导，不保证对应可解释控制语义；两项真机任务不足以证明任意负载下都能安全截断。",
    transfer: "适合需要动态算力预算的 VLA：低时延先解码短前缀，复杂接触或高置信需求再生成更多 token。",
    experimentDetails: [{ title: "三类策略接口与粗到细解码", setup: "三种 policy backbone、五个 simulation benchmarks、60+ tasks 与两项真实任务；系统改变 token 数量检查 anytime trade-off。", comparisons: "逐维 binning、VQ/VAE 类 learned tokenizer、不同 ordering/prefix loss，以及 diffusion/flow policy baselines。", results: ["使用 8 个 token 时，两项真实机器人任务均为 16/20 成功。", "每个前缀都可解码完整 action chunk，增加 token 后重建和控制表现总体改善。", "OAT 在 autoregressive generation 与 flow-expert token co-training 两种用法中均保持收益，说明改进不绑定单一 action head。"] }],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["项目页和 GitHub 已公开；论文给出 tokenizer 结构、训练目标、任务和 token 数消融。"], implementation: ["Transformer registers；finite scalar quantization；prefix reconstruction；ordering-inducing loss；8-token real-robot evaluation。"], missing: ["部分大规模预训练数据与所有 policy checkpoint 是否齐备需以仓库 release 为准。"] },
    deepDive: { lead: "OAT 让动作 token 的位置带有计算含义：越靠前越负责可执行的粗轨迹，越靠后越负责残差细节。", sections: [{ title: "前缀可解码的动作码本", paragraphs: ["encoder 用 registers 汇聚整段连续动作，再逐个量化为离散 token。训练时不只用完整序列重建，而是对每个前缀都调用 decoder，使第一个 token 必须覆盖最大尺度信息。", "下游自回归策略可以在预算紧时提前停止；token co-training 则把有序动作预测当作 VLM context 的辅助目标，最终动作仍由 flow expert 生成。"] }], equations: [{ name: "前缀重建目标", expression: "ℒprefix = Σₖ λₖ ‖a₁:H − D(z₁:k)‖₁", explanation: "所有 token 前缀都要重建完整 action chunk，迫使早期 token 表达粗动作、后期 token 补充细节。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-24/2607.21670-method.png", alt: "OAT 的 action encoder、ordered registers、FSQ 和 prefix decoder", caption: "Ordered Action Tokenization 的粗到细动作编码与下游策略接口。图片取自官方项目页对应论文图。" }],
  },
];
