import type { Paper } from "./site-data";

export const paperDaily20260803Fresh: Paper[] = [
  {
    rank: 1,
    title: "WCM: A World Critic Model for Vision-Language-Action Reinforcement Learning",
    arxivId: "2607.29613",
    url: "https://arxiv.org/abs/2607.29613",
    institutions: ["Tongji University", "Shanghai Innovation Institute", "Fudan University"],
    signal: "给 VLA-RL 的 critic 加入未来 latent 预测，让价值估计真正利用历史而不是只回归单帧 return",
    tags: ["VLA-RL", "World Critic", "Post-training"],
    classification: { research: "VLA", training: "RL", modalities: ["State / Proprioception"], data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "GitHub", url: "https://github.com/sylvestf/WCM" }, { label: "项目页", url: "https://sylvestf.github.io/wcm-homepage/" }],
    motivation: "单帧 critic 与机器人部分可观测控制不匹配；简单堆叠多帧仍只收到稀疏标量回报，难以学到跨时刻动力学。",
    methodSummary: "WCM 用轻量 LeJEPA 同时预测下一 latent state 和 value；未来预测为历史编码器提供稠密动力学监督，再把同一 critic 接到 on-policy PPO/Flow-SDE 或 off-policy AWR/RECAP。",
    architecture: "过去 K 帧经共享观察编码器得到 latent sequence；predictor 有 world-prediction 与 value 两个 head。价值分支读历史表征，预测分支用真实下一帧 latent 作为目标。",
    optimization: "兼容 OpenVLA-OFT、π0 与 π0.5；on-policy 计算 GAE 后更新策略，off-policy 混合 SFT 数据与 rollout buffer，用 WCM 的 value/advantage 做 AWR 或 RECAP。",
    data: "仿真覆盖 ManiSkill、MetaWorld、CALVIN、LIBERO-Plus 共 149 个任务；真机为 WidowX-250S 的 7 项动态、长时、柔性物体和 pick-and-place 任务。",
    experiments: "跨 4 个 benchmark 的 IND/OOD 评估均报告稳定增益；7 项真机用数百到数千条轨迹、不到一小时训练，比较 Gemma-270M 单帧 VLM critic 与 WCM。",
    novelty: "相对把历史直接拼给 value regressor，WCM 用未来 latent 预测约束 state approximation，因而把 critic 的改进来源落在可消融的 world objective 上。",
    experimentDetails: [{ title: "149 个仿真任务与真机 RL", setup: "四套仿真 benchmark，三类 VLA backbone；WidowX-250S 七任务采用 off-policy RL。", comparisons: "单帧 VLM critic、naive multi-frame critic、移除 world loss，以及不同 history length。", results: ["WCM 在 IND 与 OOD 设置中持续优于比较 critic，弱 SFT 初始化的收益尤其明显。", "去掉 world-prediction objective 后，历史信息的收益显著减弱。", "真机只需数百至数千条轨迹、不到一小时训练即可迭代，前 50 条测试轨迹用于主表统计。"], evidenceNote: "论文给出多 benchmark 与真机结果，但百分比提升在极弱初始成功率下会被放大，应同时看绝对成功率。" }],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["GitHub、项目页、训练管线和 benchmark 配置已给出。"], implementation: ["LeJEPA predictor 共享历史表示，两个 head 分别做 future latent 与 value。", "on-policy 接 PPO/Flow-SDE，off-policy 接 AWR/RECAP。"], missing: ["七项真机的完整 rollout 数据与全部硬件配置是否开放需以后续仓库为准。"] },
    deepDive: { lead: "WCM 解决的不是‘critic 参数不够多’，而是 value supervision 无法迫使历史编码器学到状态转移。", sections: [{ title: "world loss 如何帮助 critic", paragraphs: ["下一时刻 latent 提供比单一 return 更密集的监督，迫使历史表示保留动作后果和对象变化。", "value head 与 predictor 共享表示，因此优势估计能使用更接近 Markov state 的 latent。"] }, { title: "接入两类 RL", paragraphs: ["on-policy 中 WCM 产生 value 与 GAE；off-policy 中它为 SFT/rollout 混合 buffer 计算 return 和 advantage。", "同一结构覆盖 autoregressive 与 flow-matching VLA，说明它是 critic 层改动而非特定 policy trick。"] }], equations: [{ name: "联合 critic 目标", expression: "L_WCM = L_value + λ_world · ||z_(t+1) - ẑ_(t+1)||²", explanation: "价值回归与下一 latent 预测共同训练历史表征；λ_world 控制动力学监督权重。" }], experimentReading: ["四套 benchmark、三类 VLA 与七项真机提供了广覆盖证据。", "极低 baseline 下的相对百分比不宜单独解读，消融与绝对成功率更重要。"], reflections: [] },
    strengths: "仿真规模大，兼容多 backbone 与两类 RL，并有七项真机和 world-loss/history 消融。",
    limitations: "critic 仍依赖视觉 latent 是否保留控制状态；真机主要在单一 WidowX 平台。",
    transfer: "已有 VLA-RL 管线可先把单帧 critic 换成未来 latent + value 双头结构，不必修改 policy backbone。",
    figures: [{ src: "/report-assets/2026-08-03/2607.29613-fig2.png", alt: "WCM 的世界预测价值双头与 on-policy off-policy 管线", caption: "Figure 2 · WCM 架构和两类 RL 接入方式。图片来自 arXiv v1 HTML 原图。" }],
  },
  {
    rank: 2,
    title: "SelfWAM: A Self-Grounded Unified World Action Model for Fast Robot Control",
    arxivId: "2608.00725",
    url: "https://arxiv.org/abs/2608.00725",
    institutions: ["ShanghaiTech University"],
    signal: "让未来视频只对执行动作分支开放 clean action，并用 robot self-mask 把预测目标集中到可控的自身运动",
    tags: ["WAM", "Self-Mask", "Fast Inference"],
    classification: { research: "WAM", training: "Pre-training", modalities: ["Mask / Segmentation", "State / Proprioception"], data: "其他数据方法", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "只根据当前图像和指令预测未来，模型可能学到任务的平均进程，而不是给定动作真正造成的变化；完整 RGB 又把大量纹理背景纳入损失。",
    methodSummary: "SelfWAM 联合预测 action、action-conditioned future RGB 和 robot self-mask。训练时 clean demonstrated action 只能被未来视觉 query 读取，动作预测 query 看不到它，避免标签泄漏。",
    architecture: "延续 FastWAM 的两流 Mixture-of-Transformers：预训练 video backbone 与轻量 action expert 通过 mixed attention 交互；prompt 决定输出 RGB future 或 self-mask future。",
    optimization: "联合 action diffusion、future RGB 与 future mask 目标；推理时删去 clean-action 条件和视频去噪，只保留当前上下文与 action expert，因此 action-only latency 基本不变。",
    data: "RoboTwin 2.0；真机 AgileX ALOHA 数据约 17K episodes、9.5M transitions，self-mask 由 RoboSeg 离线生成。",
    experiments: "RoboTwin clean/randomized 设置对比 FastWAM、π0.5 等；真机四项 pick-and-place/插入任务，每方法每任务 10 次，并做 clean-action 与 self-mask 逐项消融。",
    novelty: "相对 FastWAM 的无动作未来视频辅助目标，SelfWAM 把未来明确绑定到执行动作，并用 robot mask 提供外观无关的自身运动监督。",
    experimentDetails: [{ title: "仿真、真机与组件消融", setup: "RoboTwin 2.0 clean/randomized；ALOHA 四任务，每方法/任务 10 次。", comparisons: "π0.5、FastWAM、仅 action-conditioned RGB、再加入 self-mask 的完整模型。", results: ["SelfWAM 在 RoboTwin clean 与 randomized 中达到不低于主要基线的表现。", "四项真机上与强基线相当或更好，同时保持 action-only 推理路径。", "action-conditioned RGB 基本保持策略性能，加入 self-mask 后在 clean 与 randomized 均进一步改善。"], evidenceNote: "真机每格 10 次，适合验证明显趋势，不宜放大小差异。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["数据规模、任务、推理信息流和消融结构可核验。"], implementation: ["真实数据约 17K episodes/9.5M transitions；RoboSeg 离线生成 mask。", "clean action 仅供 future visual query，policy query 不访问未来 token。"], missing: ["论文 v1 未确认完整代码、权重及真实训练集开放。"] },
    deepDive: { lead: "SelfWAM 的主要设计是信息流隔离：训练世界模型时使用 clean action，但不让动作头偷看答案。", sections: [{ title: "非对称 attention", paragraphs: ["future video query 可以关注 demonstrated action，学习‘执行这段动作会发生什么’。", "noisy action query 只看当前观测、语言、本体与自身噪声，从结构上避免未来视觉或 clean action 泄漏。"] }, { title: "self-mask 监督", paragraphs: ["mask 去掉颜色、纹理和背景，把损失聚焦在机器人身体随动作的空间变化。", "测试时不生成视频和 mask，它们只是训练期 world objective。"] }], experimentReading: ["组件消融能把 clean-action 与 mask 的贡献分开。", "17K episode 真实数据很大，因此性能不能解读为低数据学习。"], reflections: [] },
    strengths: "信息泄漏边界清楚，兼顾 action-conditioned world modeling、mask 消融与快速真机推理。",
    limitations: "需要大量真实轨迹和离线 robot segmentation；四项真机任务仍偏标准桌面操作。",
    transfer: "WAM 可把 robot mask 作为训练期辅助目标，并把 clean action 严格限制在 future branch。",
    figures: [{ src: "/report-assets/2026-08-03/2608.00725-fig2.png", alt: "SelfWAM 两流 MoT 与训练推理 attention 隔离", caption: "Figure 2 · SelfWAM 的 MoT、训练 attention 与快速推理路径。图片来自 arXiv v1 HTML 原图。" }],
  },
  {
    rank: 3,
    title: "CLIFT: Turning Gemini Robotics On-Device into Humanoid Specialists via Non-Invasive Closed-Loop Iterative Fine-Tuning",
    arxivId: "2607.29172",
    url: "https://arxiv.org/abs/2607.29172",
    institutions: ["University of California, Berkeley", "Google DeepMind"],
    signal: "把真实部署的 dense reward 与 advantage 转成托管 SFT API 可接收的数据，不访问闭源模型梯度也能做闭环改进",
    tags: ["Humanoid", "Closed-Loop SFT", "Gemini Robotics"],
    classification: { research: "VLA", training: "Post-training", data: "在线数据 / 人工纠正", platforms: ["Humanoid", "灵巧手"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://thomaschen98.github.io/clift" }],
    motivation: "managed SFT API 能适配强闭源 robot foundation model，却不能暴露 log-prob、梯度或 loss，常规 RL 无法直接使用；人形接触任务又强烈需要部署反馈。",
    methodSummary: "CLIFT 用偏好校准的视觉奖励给 rollout chunk 打 dense score，从相似初始状态检索对照片段计算 advantage，再把正负 advantage token 写入普通 SFT 样本，循环提交 API。",
    architecture: "部署 policy 是 Gemini Robotics On-Device；外部 reward generator 产生逐步质量曲线，DINOv3 检索相似状态，chunk-level 标签随 task prompt 和 action 一起提交 managed SFT。",
    optimization: "从 teleoperation SFT 开始，部署采样—奖励/advantage 标注—API fine-tune 构成 flywheel；推理时用 positive advantage token 条件化，不修改闭源权重接口。",
    data: "Unitree G1 的 Box Packing、Cup Insertion、Bimanual Plate Handover；比较同示范的 GROD 与开源 π0.5，并运行两轮 closed-loop rollout。",
    experiments: "成功率以固定初始配置、总计 100 trials 统计；两轮 flywheel 后 GROD 接近满成功率，并出现示范中没有的重抓与失败后再插入行为。",
    novelty: "它不是把 RL 硬塞进闭源 API，而是把 reward feedback 编译成 SFT tuple，使闭环改进兼容只允许上传监督数据的接口。",
    experimentDetails: [{ title: "三项 G1 接触任务", setup: "固定配置覆盖装箱、精密插入和双臂交接；两轮 flywheel，总计 100 trials 的主图统计。", comparisons: "GROD 初始 SFT、CLIFT 两轮、同示范 π0.5，以及给 π0.5 注入 FiLM advantage 的 invasive 变体。", results: ["GROD 的直接 managed SFT 已显著强于同数据 π0.5，但仍未达到任务 mastery。", "CLIFT 每轮继续提高，第二轮达到接近满成功率。", "最终策略出现重新调整抓取和首次插入失败后重试等示范外闭环行为。"], evidenceNote: "结果证明 API-only flywheel 可行，但模型先验、API 版本与真实机器人控制栈都是强依赖。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、任务、固定配置、reward/retrieval/label 机制和 100-trial 评估可核验。"], implementation: ["DINOv3 observation embedding 检索相似状态；chunk return 经比较转为 advantage token。", "Unitree G1 使用 whole-body controller 与 VR/IMU teleoperation。"], missing: ["Gemini Robotics 权重与 managed SFT 内部不可见；完整 rollout 数据和 API 成本未开放。"] },
    deepDive: { lead: "CLIFT 的关键是把闭环信用分配放在模型外部完成，再把结果压缩成闭源训练接口能理解的监督条件。", sections: [{ title: "从 dense reward 到 advantage token", paragraphs: ["视觉奖励先为 rollout 每一步产生质量分数，再聚合到 action chunk。", "当前 chunk 与相似初始状态的历史 chunk 比较；相对更好或更差被编码成正负 advantage token。"] }, { title: "flywheel 而非一次 SFT", paragraphs: ["新 policy 的 rollout 会产生新状态和新失败，下一轮数据因此覆盖当前模型真正访问的分布。", "推理使用正 advantage token，让策略倾向于训练中被标为相对优的行为。"] }], equations: [{ name: "检索相对优势", expression: "Â(chunk) = sign(R_chunk - median{R_neighbor})", explanation: "用相似状态下 chunk return 的相对位置生成离散 advantage 条件；表达的是论文机制而非内部 API 梯度。" }], experimentReading: ["100-trial、三项接触任务与两轮曲线支持闭环收益。", "闭源 foundation prior 贡献很大，不能把结果全部归因于数据编码技巧。"], reflections: [] },
    strengths: "真实人形、接触任务、固定评估、两轮曲线和开/闭源对照完整。",
    limitations: "依赖闭源 GROD 与 managed API；外部团队难以完全复现模型、成本和接口版本。",
    transfer: "只有 SFT 接口时，可在外部完成 reward、state retrieval 与 advantage labeling，再将部署反馈转成条件监督数据。",
    figures: [{ src: "/report-assets/2026-08-03/2607.29172-fig1.png", alt: "CLIFT 从人类示范到部署 rollout 和 advantage SFT 的闭环", caption: "Figure 1 · CLIFT 的 managed-API flywheel。图片来自 arXiv v1 HTML 原图。" }],
  },
  {
    rank: 4,
    title: "ActFovea: Runtime Safeguarding for VLA Policies via Spatiotemporal Visual-Action Consistency",
    arxivId: "2607.29169",
    url: "https://arxiv.org/abs/2607.29169",
    institutions: ["论文 v1 未标注作者机构"],
    signal: "不重训 VLA，在运行时用运动学、视觉新鲜度和动作一致性发现覆盖、延迟、漂移与冻结观测",
    tags: ["VLA Safety", "Runtime Guard", "Consistency"],
    classification: { research: "VLA", modalities: ["Mask / Segmentation", "State / Proprioception"], platforms: ["机械臂", "夹爪"] },
    motivation: "action chunk 依赖观测、机器人状态和执行动作持续对齐；局部遮挡、视觉延迟、动作漂移或冻结帧会破坏这种对齐，而 base VLA 不一定自知。",
    methodSummary: "ActFovea 根据运动学与近期 action 构造交互区域和运动走廊，只保留相关视觉；监测空间、时间与动作一致性，生成候选恢复观测并验证新 action chunk。",
    architecture: "外置 runtime wrapper 包含 foveation、spatiotemporal consistency assessment、候选恢复与 risk-aware execution；冻结观测无法恢复时进入 bounded safe failure。",
    optimization: "不更新 π0 权重；在每个闭环 step 估计 visual/proprio/action consistency，只有候选动作通过验证才执行。",
    data: "LIBERO 多套任务的 clean 环境，以及 localized overlay、visual delay、action drift、frozen-observation replay 四类受控扰动。",
    experiments: "overlay 下成功率 49.3%→90.3%，恢复 clean gap 的 93.7%；action drift 与 visual delay 分别提高 7.0、9.8 点；冻结回放全部及时 safe-fail。",
    novelty: "相对只做视觉去噪或几何 safety layer，ActFovea 用视觉—动作—本体的共同时间一致性决定恢复或拒绝执行。",
    experimentDetails: [{ title: "四类运行时扰动", setup: "π0 在 LIBERO 闭环执行，分别注入局部视觉覆盖、反馈延迟、chunk drift 和冻结观测。", comparisons: "无防护、单一 observation intervention 与完整 ActFovea；同时检查 clean performance。", results: ["局部覆盖成功率从 49.3% 恢复到 90.3%。", "动作漂移与视觉延迟提高 7.0 和 9.8 个百分点，clean 性能基本保持。", "冻结观测下所有 trial 触发及时 safe failure，没有 unprotected failure。"], evidenceNote: "实验在 LIBERO 仿真闭环完成，尚未证明真实相机延迟和机械故障下的同等效果。" }],
    reproducibilityDetails: { status: "信息不足", verifiedResources: ["四类 threat、主要指标和 runtime 组件可核验。"], implementation: ["fovea 来自 robot kinematics、proprioception 与 recent actions；恢复后再验证 action chunk。"], missing: ["未确认公开代码；没有真机时延、误检率与额外计算成本的完整测试。"] },
    deepDive: { lead: "ActFovea 把 VLA 防护定义为‘当前观测是否仍支持这段动作’，而不是单纯判断图像看起来是否异常。", sections: [{ title: "动作条件 foveation", paragraphs: ["依据当前末端位置、预测运动走廊和交互区域保留局部视觉，压低背景覆盖的影响。", "visual motion、observation freshness 与本体/动作转移共同形成一致性证据。"] }, { title: "恢复与拒绝", paragraphs: ["对可恢复扰动构造多个候选观测，再让 base VLA 产生 action，并进行二次一致性验证。", "冻结帧没有新视觉证据，系统不伪造恢复，而是执行 bounded safe failure。"] }], experimentReading: ["扰动类型覆盖视觉和动作两侧，且 clean 对照避免防护器只靠保守停止取胜。", "没有真机是重要证据边界。"], reflections: [] },
    strengths: "不改 base policy，四类扰动、clean 对照和 safe-failure 指标定义清楚。",
    limitations: "仅仿真；运行时计算、候选误拒和真实故障分布尚未充分验证。",
    transfer: "VLA wrapper 可将观测新鲜度、运动学支持与候选 action 验证组合成执行前门槛。",
    figures: [{ src: "/report-assets/2026-08-03/2607.29169-fig2.png", alt: "ActFovea 动作条件视觉区域、一致性检测与风险执行", caption: "Figure 2 · ActFovea 的运行时防护流程。图片来自 arXiv v1 HTML 原图。" }],
  },
  {
    rank: 5,
    title: "Temporal Policy: History-Initialized Action Generation for Robotic Learning from Demonstration",
    arxivId: "2607.29482",
    url: "https://arxiv.org/abs/2607.29482",
    institutions: ["University of Alberta"],
    signal: "不用独立高斯噪声启动生成，而从机器人最近历史出发运输到未来动作，把 vector field 拉直并降低推理步数",
    tags: ["Stochastic Interpolant", "History", "Fast Control"],
    classification: { research: "Memory", training: "BC", modalities: ["State / Proprioception"], platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    detailAttributes: { memoryImplementation: "Recent robot-state sequence initializes the generative path", memoryHorizon: "Short-term action history" },
    resources: [{ label: "GitHub", url: "https://github.com/dmiller12/TemporalPolicy" }],
    motivation: "diffusion/flow policy 从与数据无关的高斯噪声出发，要学习跨越很远的高曲率 transport；机器人未来动作本来就与近期状态强相关。",
    methodSummary: "Temporal Policy 以最近机器人状态作为 stochastic interpolant 的起点，U-Net 学习从 history-initialized state 到目标 action chunk 的 drift，再由 ODE/SDE solver 积分。",
    architecture: "observation encoder 产生条件 c，history 提供 x0，U-Net 预测 bθ(xλ,x0,λ,c)，solver 从 λ=0 积分到 1 得到未来动作。",
    optimization: "同一数据上比较高斯初始化 diffusion/flow 与 temporal coupling；batch 128、1500 epochs、单 A100 训练，RTX 4080 测 latency。",
    data: "多项 visuomotor 仿真任务与物理 Barrett WAM 双 7-DoF teleoperation 平台。",
    experiments: "transport cost 接近降低一个数量级，RTX 4080 单次推理 19.1 ms，同时成功率与主要生成式基线相当；真机验证高频闭环可行。",
    novelty: "它改变生成过程的 coupling，而不是只蒸馏更少 denoising steps：起点包含可用的时间先验，减少无意义运输。",
    experimentDetails: [{ title: "几何效率与真机控制", setup: "仿真 success/transport/solver steps，对 Barrett WAM 2×7DoF 做真实 teleoperation policy 部署。", comparisons: "Gaussian-initialized diffusion、flow matching 和相同观察编码器下的 Temporal Policy。", results: ["transport cost 近一个数量级下降，vector field 更接近直线。", "RTX 4080 latency 为 19.1 ms。", "成功率保持与主要 baseline 相当，并在真实 Barrett WAM 上闭环运行。"], evidenceNote: "效率数值依赖 RTX 4080 与实现；真机任务覆盖范围需结合正文视频理解。" }],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["GitHub 已公开；训练 batch/epoch/GPU 与 latency 平台已给出。"], implementation: ["batch 128、1500 epochs、单张 A100；推理用 RTX 4080 16GB。", "起点 x0 来自近期 robot state，而非独立 Gaussian。"], missing: ["真机原始数据与全部 checkpoint 是否开放需查看仓库版本。"] },
    deepDive: { lead: "Temporal Policy 的短时 memory 直接进入生成初值，而不是只作为 attention context。", sections: [{ title: "历史耦合 transport", paragraphs: ["过去状态已经落在机器人可达流形附近，把它作为起点会缩短到未来动作的路径。", "更直的 vector field 允许更少积分步骤，因此同时降低训练难度与推理延迟。"] }, { title: "与普通 history conditioning 的差别", paragraphs: ["普通方法仍从噪声出发，只在网络条件中加入 history。", "本文让 history 决定 x0，直接改变 probability path 的几何。"] }], equations: [{ name: "历史初始化 drift", expression: "dxλ / dλ = bθ(xλ, x0, λ, c),  x0 = recent history", explanation: "solver 从近期状态初始化，积分到 λ=1 得到目标 action sequence。" }], experimentReading: ["transport、latency 与 success 同时报告，避免只追求速度。", "还需更多高维触觉/VLA backbone 才能判断普适性。"], reflections: [] },
    strengths: "理论动机、transport 测量、推理速度和真机部署相互对应，代码公开。",
    limitations: "主要验证在特定 LfD 架构与平台；历史异常或策略切换时的误导风险未充分分析。",
    transfer: "高频 diffusion policy 可尝试把 recent action/state 作为生成初值，而不是只做条件 token。",
    figures: [{ src: "/report-assets/2026-08-03/2607.29482-fig2.png", alt: "Temporal Policy 从近期状态经 ODE SDE 生成未来动作", caption: "Figure 2 · history-initialized stochastic-interpolant policy。图片来自 arXiv v1 HTML 原图。" }],
  },
  {
    rank: 6,
    title: "RayViT: Ray-Conditioned Visual Representations for Viewpoint-Robust Imitation Learning",
    arxivId: "2607.29622",
    url: "https://arxiv.org/abs/2607.29622",
    institutions: ["Karlsruhe Institute of Technology", "University of Leeds"],
    signal: "把相机内外参变成每个像素的 Plücker ray token，让视觉策略知道‘同一物体在不同视角下对应哪条空间射线’",
    tags: ["Camera Geometry", "Viewpoint Robustness", "Imitation Learning"],
    classification: { research: "表征学习", training: "BC", modalities: ["Point Cloud / 3D"], platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "RGB ViT 没有显式相机几何，训练相机稍有移动就会把像素位置变化误当成场景变化。",
    methodSummary: "RayViT 将每个像素的 Plücker ray patchify，既作为 dense positional embedding，又经 gated cross-attention 生成 geometry-aware CLS token，并加入跨视角 cosine consistency loss。",
    architecture: "DINOv3 ViT-Small 处理图像；ray map 分支产生 patch-aligned embedding 与 ray-conditioned CLS；视觉、CLIP 语言和 noisy action token 进入 decoder-only xLSTM policy。",
    optimization: "仿真 50 epochs、batch 256、单 A100；同时扫描 ray token 注入位置、gating 与 consistency loss。",
    data: "RoboCasa multi-task 仿真，训练/测试相机扰动；真实多阶段 manipulation 使用标定相机并比较视角变化下完成阶段数。",
    experiments: "RoboCasa 相机扰动下平均提高约 13 个百分点；真机相对基线多完成 1.78 个阶段，并给出 ray/gating/consistency 组件消融。",
    novelty: "相对只加相机 pose 向量或数据增强，RayViT 把几何对齐到每个 patch，同时保留全局 ray-conditioned summary token。",
    experimentDetails: [{ title: "视角扰动与真实多阶段任务", setup: "RoboCasa 多任务相机位置/姿态扰动；真实机器人按完成阶段数计分。", comparisons: "普通 DINOv3 ViT、相机 pose 条件、dense ray embedding、gated CLS 与 consistency loss 组合。", results: ["仿真 camera perturbation 下约提升 13 个百分点。", "真机平均多完成 1.78 个任务阶段。", "dense ray、gated CLS 和跨视角 consistency 共同构成最强变体。"], evidenceNote: "真机指标是平均完成阶段数，不应改写成 1.78 个百分点成功率。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["backbone、训练 epoch/batch/GPU、ray 表示和评估指标可核验。"], implementation: ["DINOv3 ViT-Small；仿真 batch 256、50 epochs、单 A100 约 8 小时。", "ray map 使用 Plücker coordinates，并按图像 patch 对齐。"], missing: ["未确认完整代码/真实数据开放；依赖准确内外参。"] },
    deepDive: { lead: "RayViT 不从 RGB 猜相机移动，而是把每个视觉 token 对应的空间射线直接交给 backbone。", sections: [{ title: "局部与全局几何", paragraphs: ["patch ray embedding 修正局部位置编码，告诉网络像素观察的是哪条三维射线。", "gated ray CLS 通过 cross-attention 汇总当前相机几何，替换普通 CLS。"] }, { title: "跨视角约束", paragraphs: ["同一场景的 geometry-aware token 用 cosine loss 对齐，减少相机扰动对策略表征的影响。", "它增强的是 camera robustness，不等同于完整三维重建。"] }], experimentReading: ["仿真约 13 点和真机阶段数改善方向一致。", "标定误差和移动相机在线更新仍是实际部署风险。"], reflections: [] },
    strengths: "几何注入位置明确，有仿真扰动、组件消融和真机多阶段验证。",
    limitations: "需要相机标定；真实提升按阶段数而非完整成功率，动态相机与多相机异步尚未充分测试。",
    transfer: "现有 ViT policy 可在不改 action decoder 的前提下加入 patch ray map 与 geometry-aware CLS。",
    figures: [{ src: "/report-assets/2026-08-03/2607.29622-fig1.png", alt: "RayViT ray map gated attention 和 xLSTM action decoder", caption: "Figure 1 · RayViT 的相机几何注入与策略结构。图片来自 arXiv v1 HTML 原图。" }],
  },
  {
    rank: 7,
    title: "Safe Vision Language Action Models via Barrier Enhanced Flow Matching",
    arxivId: "2607.29569",
    url: "https://arxiv.org/abs/2607.29569",
    institutions: ["The Pennsylvania State University"],
    signal: "把 Control Barrier Function 直接放进 flow denoising 的每一步，使生成的整段 action chunk 满足安全约束",
    tags: ["Safe VLA", "Control Barrier Function", "Flow Matching"],
    classification: { research: "VLA", modalities: ["State / Proprioception"], platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://kassra-sinaei.github.io/safe-vla-webpage/" }],
    motivation: "在 VLA 输出后再加 safety filter 可能大幅改变整段动作语义；flow policy 的中间 denoising trajectory 提供了更早、更连续的干预位置。",
    methodSummary: "每个 flow step 解一个 CBF 约束修正，把 smooth Log-Sum-Exp aggregate barrier 作用到整段 action chunk；无需安全专用数据或重新训练 base VLA。",
    architecture: "base VLA 的 VLM backbone 与 action expert 不变；CBF block 在 flow velocity 上求最小修正，得到满足状态/动作约束的 safe chunk。",
    optimization: "纯推理期算法；论文分析修正后分布到目标分布的 2-Wasserstein 距离有界，并比较 barrier 权重、QP 与外置 filter。",
    data: "Maze2D 100-trial 导航测试，以及两种真实 manipulation 平台；包含速度限制、障碍区域和桌面清理等约束。",
    experiments: "两平台真机同时报告 safety 与 task success，并展示不进入 collision zone、保持 wall barrier；Maze2D 与超参消融验证约束和分布偏移。",
    novelty: "相对只修最终动作，它在 flow 生成路径内连续施加 CBF，使安全约束影响整段 chunk 的形成。",
    experimentDetails: [{ title: "导航与两平台真机安全", setup: "Maze2D 每方法 100 trials；SO-101 等两种机械臂执行受限抓取/清理。", comparisons: "原始 flow policy、final-output safety filter、Safe Diffuser/Safe Flow Matcher 与 barrier-enhanced flow。", results: ["CBF-enhanced flow 能在动作 chunk 内满足速度与障碍约束。", "真机在障碍球/墙约束下保持安全区，同时完成可行目标。", "超参消融展示 safety margin 与行为保守度的权衡。"], evidenceNote: "论文结论支持可靠安全约束，但硬件主表规模与不同约束的泛化仍有限。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目视频、算法、barrier 形式、Maze2D 与硬件协议可核验。"], implementation: ["基于开源 π0/LeRobot 修改；smooth aggregate barrier 约束整段 action。", "每个 flow step 通过 QP/可微 solver 修正 velocity。"], missing: ["完整实现仓库和硬件数据未确认公开；solver latency 与高维复杂约束扩展不足。"] },
    deepDive: { lead: "这项方法把安全看成生成分布的约束，而不是 action 输出后的补丁。", sections: [{ title: "barrier-enhanced denoising", paragraphs: ["当前中间 action state 先由 flow 给出 velocity，再投影到满足 CBF 条件的可行方向。", "Log-Sum-Exp 把 action chunk 中多个时间点的 barrier 平滑聚合，避免只保证第一步。"] }, { title: "语义与安全权衡", paragraphs: ["修正取最小范数，目标是在满足约束时尽量保留 base VLA 的任务意图。", "Wasserstein bound 说明干预后分布偏移受控，但不能替代对所有未知障碍的感知保证。"] }], equations: [{ name: "CBF flow 修正", expression: "v_safe = argmin_v ||v - v_base||²  s.t.  d h(x) / dt + α(h(x)) ≥ 0", explanation: "在每个 flow step 选择最接近原始 velocity 的安全修正。" }], experimentReading: ["有真机和导航对照，但任务与约束仍较简化。", "安全率必须与成功率一起看，避免只靠停止动作得到安全。"], reflections: [] },
    strengths: "形式化约束、分布偏移分析、导航和两平台真机形成较完整链条。",
    limitations: "依赖可计算 barrier 与可靠状态估计；复杂接触、动态障碍和 solver latency 仍是扩展瓶颈。",
    transfer: "flow-matching VLA 可在 denoising velocity 层加入最小 CBF 投影，而不是只过滤最终 chunk。",
    figures: [{ src: "/report-assets/2026-08-03/2607.29569-fig1.png", alt: "Barrier Enhanced VLA 在 flow action expert 中加入 CBF", caption: "Figure 1 · barrier-enhanced flow-matching VLA。图片来自 arXiv v1 HTML 原图。" }],
  },
  {
    rank: 8,
    title: "DynamicManip: Enabling Dynamic Manipulation from a Single Static Demonstration",
    arxivId: "2608.01452",
    url: "https://arxiv.org/abs/2608.01452",
    institutions: ["Sun Yat-sen University", "Stanford University", "Southeast University", "Jiangxing Intelligence"],
    signal: "从一条静态示范重建对象、切出交互片段并编辑动态轨迹，再按任务阶段自适应调整 diffusion policy 推理频率",
    tags: ["Dynamic Manipulation", "Data Augmentation", "Adaptive Inference"],
    classification: { research: "其他", training: "BC", modalities: ["Depth / RGB-D", "Point Cloud / 3D", "State / Proprioception"], data: "数据增强", platforms: ["机械臂", "夹爪"], deployment: "Real2Sim2Real" },
    resources: [{ label: "项目页", url: "https://liaohr9.github.io/DynamicManip/" }],
    motivation: "动态目标状态组合多，逐一遥操作成本高；固定频率 policy 又不能同时兼顾静态阶段的计算效率和接触瞬间的快速反应。",
    methodSummary: "从单条静态示范定位目标并重建几何，按 start/grasp/interact/recover 切分可复用片段，编辑目标运动后用 motion planning 与局部 replay 自动生成动态轨迹。",
    architecture: "diffusion policy 加 stage classifier；训练用自动 stage label 辅助监督，部署按 predicted stage 调节 denoising recomputation interval 与每次执行步数。",
    optimization: "数据侧逐步加入动态对齐、局部交互 replay 等组件；推理侧比较固定频率、oracle stage 与 predicted-stage schedule。",
    data: "一条真实静态示范扩展出多种动态 trajectory；自建仿真 benchmark 和四项真实动态任务，真实每任务/设置 30 trials。",
    experiments: "平均成功率比比较方法高 18.4 个百分点、policy-query latency 低 32.9%；真实表、数据流水线和 inference schedule 都有独立消融。",
    novelty: "它把数据效率和运行时延迟一起处理：一条示范负责生成动态覆盖，stage-aware schedule 负责把计算放到高动态阶段。",
    experimentDetails: [{ title: "静态到动态数据与真实任务", setup: "仿真 benchmark 加四项真实动态任务；真实每任务/设置 30 trials，Dynamic Tapping 另按 90 次击打事件统计。", comparisons: "人类动态示范、不同数据生成阶段、固定推理 schedule、oracle/predicted stage。", results: ["总体平均成功率提高 18.4 个百分点。", "policy-query latency 降低 32.9%。", "逐项消融显示局部 interaction replay 与 predicted-stage scheduling 都有贡献。"], evidenceNote: "任务与生成器由作者自建，跨物体动力学与跨平台泛化仍需外部复现。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、任务、30-trial 协议、各流水线阶段和 schedule 超参表可核验。"], implementation: ["RGB-D/点云重建，经 OBB/ICP 对齐 mesh；keyframe 切分后做 motion planning。", "stage classifier 训练期辅助监督，部署决定 TaylorSeer interval 与执行步数。"], missing: ["完整代码、对象 mesh 与真机轨迹是否全部开放需以后续项目页为准。"] },
    deepDive: { lead: "DynamicManip 没有把静态示范直接时间缩放，而是把自由空间运动与局部接触片段分开处理。", sections: [{ title: "轨迹编辑", paragraphs: ["对象和目标几何先重建，动态目标对齐改变自由空间段；接触片段在局部对象坐标中 replay。", "motion planner 连接编辑后的关键状态，使生成轨迹仍满足机器人运动学。"] }, { title: "阶段自适应推理", paragraphs: ["approach 等慢阶段可以复用 denoising 结果并一次执行更多步。", "interact/recover 阶段提高重计算频率、缩短 action horizon，以响应动态变化。"] }], experimentReading: ["真实 30 trials/格和 schedule 消融比单纯 demo 视频更可靠。", "收益仍与自动生成轨迹的碰撞、标定和对象模型质量强相关。"], reflections: [] },
    strengths: "数据生成、实时策略、仿真 benchmark、真机与逐组件消融闭环完整。",
    limitations: "需要几何重建、标定和 motion planner；柔性/不可建模对象与复杂接触的可扩展性有限。",
    transfer: "可以把动态操作拆成可编辑自由空间段与可复用接触段，并让 policy query frequency 随阶段变化。",
    figures: [{ src: "/report-assets/2026-08-03/2608.01452-fig3.png", alt: "DynamicManip stage-aware policy 训练与动态推理调度", caption: "Figure 3 · DynamicManip 的阶段监督和自适应推理。图片来自 arXiv v1 HTML 原图。" }],
  },
  {
    rank: 9,
    title: "CAAT: Contact-Aware Attention Scaling and Tactile Masking for Data-Efficient Contact-Rich Manipulation",
    arxivId: "2608.01102",
    url: "https://arxiv.org/abs/2608.01102",
    institutions: ["ShanghaiTech University", "Beihang University", "Beijing Institute for General Artificial Intelligence", "Zhejiang University", "BUPT"],
    signal: "把‘接触前看视觉、接触后看触觉’写成 attention prior，并用非接触参考图屏蔽触觉背景 token",
    tags: ["Tactile", "Contact-Aware Attention", "UMI"],
    classification: { research: "表征学习", training: "BC", modalities: ["Tactile", "State / Proprioception"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://mrjiangjm.github.io/caat/" }],
    motivation: "直接拼接或学习 gating 需要从有限示范中自己发现接触阶段；高分辨触觉里大量静态背景 token 还会稀释真正的形变信号。",
    methodSummary: "Dynamic Tactile Masking 用当前触觉与无接触参考的差异筛掉未变化 patch；Contact-Aware Attention Scaling 在接触前提高视觉权重、接触后提高触觉权重。",
    architecture: "视觉、masked tactile 与 robot state 分别 token 化后进入 Transformer；modality-specific readout 按接触状态缩放，再交给原 action decoder，兼容 ACT、DP 和 π0。",
    optimization: "比较 direct concatenation、learnable gate、binary/learnable/fixed scaling；所有方法都使用相同 tactile mask，确保 attention scaling 对照公平。",
    data: "UniVTAC 仿真与 tactile UMI 真机；Lift Bottle、Open Box、Powerbank Extraction，每任务 150 条示范。",
    experiments: "仿真 ACT 比直接融合高 18 点、比 gated fusion 高 10 点；真机三 backbone 平均成功率 60.0%，比各自最强 baseline 平均高 21.1 点。",
    novelty: "相对端到端学 gate，CAAT 把已知接触阶段先验显式放进 attention，并把动态 tactile mask 与 modality scaling 分开消融。",
    experimentDetails: [{ title: "UniVTAC 与 tactile UMI 真机", setup: "仿真和真实均每任务 150 demos；真机三任务，ACT/DP/π0 三种 backbone。", comparisons: "direct concatenation、learnable gating 与 CAAT；binary、learnable、fixed scaling。", results: ["仿真平均较 direct fusion +18.0 点、较 gated fusion +10.0 点。", "真机 ACT 25.0%→55.0%，DP 36.7%→58.3%，π0 36.7%→66.7%。", "Open Box 达 50%–60%，Powerbank Extraction 的 π0+CAAT 达 90%。"], evidenceNote: "各方法共享 dynamic mask，主差异更能归因于 contact-aware scaling；任务仍只有三项。" }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、150 demos/任务、三 backbone 和主要对照数值可核验。"], implementation: ["π0 用 LoRA、两张 A100 80GB、global batch 64；ACT/DP 各单张 A100。", "触觉 token 与 non-contact reference 比较后动态 mask；fixed scaling 使用接触前后预设权重。"], missing: ["完整代码、触觉 UMI 硬件文件和数据是否全部开放需查看项目页后续。"] },
    deepDive: { lead: "CAAT 的归纳偏置很直接：自由空间主要靠视觉定位，接触建立后才让触觉形变主导 action readout。", sections: [{ title: "动态触觉 mask", paragraphs: ["当前 tactile patch 与无接触参考近似不变时被抑制，接触形变明显的 patch 被保留。", "这一步减少传感器固定纹理、照明与边框对 attention 的干扰。"] }, { title: "接触阶段缩放", paragraphs: ["不同 modality 先独立汇聚，再按估计 contact state 缩放 visual/tactile contribution。", "action decoder 不变，因此同一模块可以接到 ACT、Diffusion Policy 和 π0。"] }], equations: [{ name: "接触条件融合", expression: "h = γ_v(contact) · h_visual + γ_t(contact) · h_tactile", explanation: "接触前 γ_v 较大，接触后 γ_t 较大；tactile token 在融合前先经过动态 mask。" }], experimentReading: ["仿真、三种真机 backbone 和固定数据量形成扎实对照。", "明确先验也可能在接触估计错误或持续视觉关键任务中造成错误抑制。"], reflections: [] },
    strengths: "三 backbone 真机、统一示范量、融合基线和 scaling 消融充分。",
    limitations: "只验证单一触觉 UMI/三任务；contact-state 错误与跨传感器迁移仍未解决。",
    transfer: "现有 visuo-tactile Transformer 可先加入 reference-based tactile mask，再在 readout 层做接触条件 scaling。",
    figures: [{ src: "/report-assets/2026-08-03/2608.01102-fig1.png", alt: "CAAT 动态触觉 mask 与接触感知视觉触觉 attention", caption: "Figure 1 · CAAT 的 tactile preprocessing、mask 与 attention scaling。图片来自 arXiv v1 HTML 原图。" }],
  },
];
