import { formatDaily, type DailyEntry } from "./paper-daily-format";

const entries: DailyEntry[] = [
  {
    title: "DexRoam: Learning Mobile Bimanual Dexterous Manipulation from Egocentric Whole-Body Human Demonstrations",
    arxivId: "2609.35761",
    url: "https://arxiv.org/abs/2609.35761",
    institutions: ["香港科技大学", "北京通用人工智能研究院", "北京大学", "北京航空航天大学", "中国科学院自动化研究所"],
    resources: [{ label: "项目页", url: "https://dexroam.github.io/" }],
    signal: "把无外部追踪器的人类第一视角全身示范对齐到轮式双臂灵巧机器人。",
    tags: ["Whole-body VLA", "Human Demonstrations", "Bimanual Dexterity"],
    classification: { research: "VLA", training: "BC", data: "UMI / Ego / Human Video", platforms: ["轮式底盘", "灵巧手"], deployment: "跨本体迁移" },
    motivation: "移动双臂任务需要底盘、躯干、双臂和双手协同，但逐关节机器人遥操作成本高，人类示范又存在形态、动作语义与节奏差异。",
    methodSummary: "用头戴相机和头显采集全身人类轨迹，经形态、局部相对动作和任务进度三阶段对齐后，与较少机器人示范共同训练一套全身 VLA。",
    architecture: "GR00T N1.7 或 π0.5 主干读取双目 RGB、53 维本体状态与语言，一次预测底盘、头、躯干、双臂和双手组成的 56 维连续动作。",
    data: "五项任务混合人类与机器人轨迹；人类侧记录头部 6DoF、33 个身体关节、每手 25 个关节和双目 RGB，人类示范量约为机器人示范的一半。",
    experiments: "Astribot-XHand 上五项真机任务各 20 次；GR00T 平均成功率由 29% 提至 56%，π0.5 由 32% 提至 57%。",
    novelty: "相对纯机器人数据，增加无需外部相机或标记的人类全身采集，并把人机轨迹在形态、动作语义和时间进度上显式对齐。",
    strengths: "覆盖移动、双臂与灵巧手的长程任务，并报告分布对齐、轨迹回放、数据配比和多种泛化条件。",
    limitations: "灵巧手采用位置控制且没有力觉或触觉，抓取稳定性仍受限；长程任务中的早期偏差会向后传播。",
    transfer: "跨本体数据进入策略前，应分别处理参考坐标、动作语义和任务进度，而不只做关节重定向。",
    technique: [
      "采集端使用 Meta Quest 3、头戴 ZED Mini 和 MANUS 手套，记录与机器人策略相同视角的双目视频。形态对齐在以骨盆为中心的地面坐标中重定向全身姿态；动作对齐改用局部相对变换，避免把人和机器人的绝对位姿直接混合。",
      "时间对齐按任务进度把人类轨迹重采样到机器人 episode 的平均长度。对齐后 MMD 平均下降 41.7%，SWD 下降 31.1%；15/15 条回放轨迹没有出现 IK 失败。",
      "策略输入为 640×480 双目图像、53 维本体状态和语言，输出 56 维全身动作：双手各 12 维、双臂各 9 维、躯干 9 维、头部 2 维、底盘 3 维。",
    ],
    evaluation: [
      "五项真机任务为取薯片罐、倒水、扔垃圾、递送水果以及推椅关电脑；每任务 20 次。加入人类数据后，GR00T N1.7 平均成功率为 56%（机器人数据 29%），π0.5 为 57%（32%）。",
      "时间对齐消融把平均成功率从 68.3% 降到 44.2%，改用绝对动作后为 0%；仅用人类数据同样为 0%，说明对齐不能替代少量机器人动作锚点。",
      "背景变化下，机器人数据模型从 50% 降到 20%，人类预训练再共同训练的配置从 90% 降到 55%。指令泛化中最佳配置相对降幅为 6%，但任务数和每项 20 次试验限制了统计精度。",
    ],
    comparison: "机器人数据单独训练、人类数据单独训练、预训练/共同训练配方，以及去掉时间对齐或改用绝对动作的消融。",
    implementation: [
      "π0.5 使用 2 张 GPU、30k 步、batch 4、AdamW 学习率 2.5e-5；GR00T 使用 4 张 GPU、40k 步、batch 24、学习率 1e-4。机器人为全向底盘、躯干、双 7DoF 手臂、2DoF 头和双 12DoF XHand。",
      "项目页已公开；论文给出采集设备、动作维度、训练步数和真实评测协议，当前未确认完整代码、数据和模型权重全部发布。",
    ],
    figureFile: "2609.35761-fig2.png",
    figureAlt: "DexRoam 跟随式遥操作与无外部追踪器的人体全身采集系统",
    figureCaption: "Figure 2 · 跟随式全身遥操作与第一视角人类数据采集。来源：arXiv 原图。",
  },
  {
    title: "ReCAT: Remember, Count, and Time: Structured Recurrent Memory for Robot Manipulation",
    arxivId: "2609.35200",
    url: "https://arxiv.org/abs/2609.35200",
    institutions: ["University of Edinburgh", "Karlsruhe Institute of Technology", "NVIDIA", "Robotics Institute Germany"],
    resources: [{ label: "项目页", url: "https://intuitive-robots.github.io/ReCAT" }],
    signal: "让策略跨整个 episode 保存紧凑递归状态，用于记忆、计数和计时。",
    tags: ["Memory", "Mamba-2", "Flow Matching"],
    classification: { research: "Memory", training: "BC", platforms: ["机械臂", "夹爪"] },
    motivation: "长程操作中的物体位置、事件次数和等待时长不一定能从当前图像恢复，短窗口策略会丢失完成进度。",
    methodSummary: "每帧先压缩多模态观测，再用 Mamba-2 与因果注意力更新贯穿 episode 的递归状态；动作解码器分别读取当前表征和记忆。",
    architecture: "冻结 DynaFLIP、LoRA 适配的 T5、六层帧编码器、六层递归记忆和四层 flow-matching 动作解码器；动作块长度 16。",
    data: "LIBERO、RMBench，以及 Franka Panda 上三项真实记忆任务；真机每项 45–48 条示范、约 480–1,200 步。",
    experiments: "LIBERO 为 95.3%，RMBench 为 62.4%；三项真机每项 20 次，ReCAT 平均 66.7%，最强短历史基线为 8.3%。",
    novelty: "把帧内混合、跨时递归和动作生成分开，并在每个动作解码块中独立读取当前观测与历史状态。",
    strengths: "同时验证空间记忆、事件计数和时间估计，并对递归单元、注入位置、状态宽度与延迟做匹配消融。",
    limitations: "每类记忆需求只有一项真机任务且每项 20 次；主记忆消融同时移除递归和注意力，不能完全分离二者贡献。",
    transfer: "对长程控制，显式区分当前高分辨率观测和紧凑历史状态，通常比不断扩张图像上下文更可控。",
    technique: [
      "视觉压缩器根据语言生成全局和局部 query；五个 Mamba-2 块加一个双向注意力块把 RGB、语言和本体编码为 768 维 zₜ。递归记忆同样由五个 Mamba-2 块和一个因果注意力块组成。",
      "状态更新写作 (mₜ,hₜ)=R(zₜ,hₜ₋₁)：固定大小的 Mamba 状态跨步传递，因果注意力则每步追加一个 K/V。四层 flow decoder 在每层分别 cross-attend 当前 zₜ 与记忆 mₜ。",
      "真实系统以 15 Hz 运行，ReCAT 推理延迟 59 ms（16.9 Hz）；总参数 374M、可训练参数 142M。长期 K/V 会随 episode 线性增长，因此并非严格常数内存。",
    ],
    evaluation: [
      "真机任务为海绵空间回忆、植物计数和锅具计时，成功判据分别包含 2–4 cm 空间容差、正确计数和 29–31 秒计时窗。Mamba-2 版本为 20%/85%/95%，平均 66.7%。",
      "将帧编码器改为全 Transformer 后均值为 25%；不使用记忆为 0%。记忆在每个解码块注入为 66.7%，晚期注入 38.3%，AdaLN 31.7%，缩放 28.3%，dropout 20%，门控 8.3%。",
      "不同递归单元中 Mamba-2 平均 66.7%，Mamba-3 为 63.3%，Gated Delta 为 50%。论文报告 Wilson 置信区间，但训练只使用一个 seed，状态宽度结果也呈非单调。",
    ],
    comparison: "短历史 VLA、无记忆/全 Transformer、三种递归单元、记忆宽度与多种解码器注入方式。",
    implementation: [
      "真实平台为 Franka Panda DROID 配置，固定相机与腕部相机输入 224×224，15 Hz，8 维末端动作。论文公开项目页并披露网络宽度、层数、动作块和实时延迟。",
      "当前未确认完整训练代码、真机数据和全部权重发布；真机只有一个训练 seed，复现时还需补足初始化和数据划分。",
    ],
    figureFile: "2609.35200-fig2.png",
    figureAlt: "ReCAT 多模态帧编码、递归记忆与动作解码架构",
    figureCaption: "Figure 2 · 当前观测编码、跨 episode 递归记忆与 flow-matching 动作头。来源：arXiv 原图。",
  },
  {
    title: "Direct Experience World-Model Optimization: Learning the World Beyond Action Imitation",
    arxivId: "2609.37398",
    url: "https://arxiv.org/abs/2609.37398",
    institutions: ["哈尔滨工业大学", "大连理工大学", "南方科技大学"],
    signal: "把部署中成功与失败的视觉后果作为世界模型监督，失败动作不进入模仿目标。",
    tags: ["WAM", "Post-deployment", "Outcome Conditioning"],
    classification: { research: "WAM", training: "Post-training", data: "在线数据 / 人工纠正", platforms: ["灵巧手"] },
    motivation: "只模仿成功动作会丢掉失败交互揭示的世界动态，而直接模仿失败动作会把错误写回策略。",
    methodSummary: "从可恢复性下降的位置采集匹配的成功与失败续轨；两类轨迹都监督视觉未来，只有成功轨迹监督动作，再以成功条件和价值门控引导执行。",
    architecture: "视频 DiT、动作 DiT 与进度价值头共享上下文；成功条件 classifier-free guidance 只在价值头判断需要时启用。",
    data: "五项 DexJoCo 仿真任务与四项双手真机抓取放置；真实部署进行三轮、每轮 720 次、合计 2,160 次。",
    experiments: "FACT 从 64.5% 提至 81.2%，FastWAM 从 80.7% 提至 82.3%；真机全网格由 148/720 提至 208/720。",
    novelty: "失败续轨只贡献视觉未来损失，避免错误动作监督；部署时将成功条件的引导强度与在线进度价值绑定。",
    strengths: "同时比较多种 WAM 动作参数化、完整轨迹与关键片段、成功/失败视觉监督及三种引导策略。",
    limitations: "真机提升只发生在初始已有成功的 29 个网格位置；43 个初始零成功位置在三轮后仍全部为零，方法没有扩展空间覆盖。",
    transfer: "部署失败可以作为动力学监督，但动作目标应与结果监督解耦，并用可恢复性定位最有信息量的片段。",
    technique: [
      "对上下文 h 的 K 次续轨用平均成功 Y 估计可恢复性 ρ̂K(h)；当前缀可恢复而下一步不可恢复时标记交互转折点，并从匹配上下文采集成功与失败续轨。",
      "成功样本优化视觉、动作和价值损失，失败样本只优化视觉与价值损失。部署引导为 f_guided=f_base+gⱼw(f_success−f_base)，其中 gⱼ 由价值头对任务进度的判断开关。",
      "DEWO 既适配直接动作建模，也适配逆动力学或 FastWAM 结构；训练期保留失败的视觉未来，但不把失败动作作为模仿标签。",
    ],
    evaluation: [
      "仿真五任务每任务使用三组 50 场景测试。FACT 基线 64.5%，SFT 70.1%，DEWO 81.2%；FastWAM 基线 80.7%，DEWO 82.3%。DEWO-S 报告 89.9%，但使用额外成功条件。",
      "真机使用 Wuji 与 Sharpa 手，在 3×3 网格每格 10 次、两只手合计每轮 720 次，三轮共 2,160 次。全网格成功率由 20.6%（148/720）升到 28.9%（208/720）。",
      "成功视觉监督与失败视觉监督依次加入后，Water Plant 为 86.7→88.7→90.7，Fold Glasses 为 72.0→74.0→77.3；关键片段优于等量完整轨迹，价值门控也优于无引导和连续引导。",
    ],
    comparison: "SFT、RECAP、DSRL，多种 WAM 参数化，以及动作/成功视觉/失败视觉、关键片段和引导方式消融。",
    implementation: [
      "真实评测覆盖两种灵巧手、四种物体和固定 3×3 空间网格；论文给出分子/分母而不只报告百分比。源码与训练权重当前未确认公开。",
      "复现需要记录每轮匹配上下文、转折点阈值、成功条件与价值门控；论文没有单列局限章节，空间覆盖边界由真机表格直接核对。",
    ],
    figureFile: "2609.37398-fig2.png",
    figureAlt: "DEWO 成败续轨的选择性监督和价值门控成功条件引导",
    figureCaption: "Figure 2 · 交互转折点采集、选择性世界模型监督与价值门控引导。来源：arXiv 原图。",
  },
  {
    title: "ECoMEM: Explicit Concept Memory for Memory-Dependent Robot Control",
    arxivId: "2610.00801",
    url: "https://arxiv.org/abs/2610.00801",
    institutions: ["Stanford University"],
    resources: [{ label: "项目页", url: "https://ecomem.github.io/" }],
    signal: "用可解释概念记录替代长视频缓存，显式保存实体、事件、顺序与时间。",
    tags: ["Explicit Memory", "Concept Library", "Long-horizon Control"],
    classification: { research: "Memory", training: "BC", platforms: ["机械臂", "夹爪"] },
    motivation: "长时视频上下文昂贵且会混入无关信息，而纯语言摘要容易遗漏计数、顺序和状态变化。",
    methodSummary: "冻结的 Writer 从视觉和机器人状态中维护结构化概念记录；可训练 Reader 把相关记录编码成 memory token，与 VLA 的图像和语言 token 一起驱动动作。",
    architecture: "11 个离散字段各映射到 256 维，两层 4-head Transformer 编码记录，再投影成每条 2,048 维 memory token 接入 π0.5。",
    data: "RoboMME 16 项任务训练 200k 步；YAM 真机的 ScoopPour 与 CupSwitch 各 59 条示范。",
    experiments: "RoboMME 平均 82.42%，最强对照为 44.51%；真机合计 68/79（86.08%），无记忆为 5/58（8.62%）。",
    novelty: "概念 Writer 用证据累积、事件去重和先决关系维护可审计记录；Reader 只读取当前任务需要的记录。",
    strengths: "概念族、选择、grounding 与直接 VLM 提取均有消融，并给出真实任务逐条件计数、Wilson 区间与 Fisher 检验。",
    limitations: "Writer 依赖人工设计的概念库、检测器和标定；真机有无记忆试验分母不同且不是配对试验。",
    transfer: "当任务依赖明确事件或顺序时，可把感知状态转成带证据和先决关系的记录，再让策略学习如何读取。",
    technique: [
      "Writer 根据任务先选择概念，再用 OWLv2、SAM2、机器人状态和标定更新四类记录：实体/空间、状态/关系、事件/进度、时间/流程。漏检不作为否定证据，事件只计一次，顺序记录显式先决条件。",
      "每条记录含 kind、predicate、subject/object、truth、status、confidence、age、flags 和 row/column 等 11 个字段；字段嵌入求和后经两层 Transformer 和线性层变成 2,048 维 token。",
      "Reader 与语言主干和 action expert 共同训练，Writer 与视觉模块冻结；记录无位置编码，时间年龄和依赖关系承担顺序信息。",
    ],
    evaluation: [
      "RoboMME 的 16 个任务每项 50 个验证 episode、三个采样 seed；ECoMEM 平均 82.42%，FrameSamp+Modul 为 44.51%，人类为 90.50%，并在 15/16 项领先。",
      "移除空间、事件/进度或时间概念后，相应任务分别出现 84→18、62→14、60→12 的下降。去掉任务选择后两项代表任务从 84→42、64→8，延迟增加 12–18.1 倍。",
      "真机合计 ECoMEM 为 68/79（86.08%），无记忆为 5/58（8.62%），Fisher 精确检验 p=4.90e-21。论文给出 Wilson 区间，但两组样本数不同且未做逐场景配对。",
    ],
    comparison: "视频帧采样/摘要记忆、无记忆、不同概念族、无任务选择、通用语言 grounding，以及 Qwen3-VL-8B 直接抽取。",
    implementation: [
      "真实平台为 7DoF YAM 与 GELLO，顶部和腕部 640×480 RGB、30 Hz；图像送入模型前缩放到 224，20 步动作块执行 16 步再规划，memory 以 5 或 10 Hz 更新。",
      "项目页已公开；论文给出字段、网络宽度、训练步数和真机数据量，当前未确认完整 Writer 配置、代码、数据和权重全部发布。",
    ],
    figureFile: "2610.00801-fig2.png",
    figureAlt: "ECoMEM 概念写入器、概念库、记忆读取器与 VLA 控制通路",
    figureCaption: "Figure 2 · 显式概念记忆的构建、筛选与 VLA 条件化。来源：arXiv 原图。",
  },
  {
    title: "Reconstruct, Practice, Go Real: Guided Self-Improvement for Embodied Agents",
    arxivId: "2610.02204",
    url: "https://arxiv.org/abs/2610.02204",
    institutions: ["UC Berkeley", "MIT", "Amazon Frontier AI & Robotics", "University of Chicago"],
    resources: [{ label: "项目页", url: "https://rpg-robot.github.io/" }],
    signal: "在仿真中反复诊断和回归测试共享技能库，再冻结系统迁移到真机。",
    tags: ["Agentic Robotics", "Skill Library", "Simulation Practice"],
    classification: { research: "Subtask", data: "合成 / 仿真数据", platforms: ["机械臂", "夹爪"], deployment: "Sim2Real" },
    motivation: "机器人技能代码、奖励和感知接口通常依赖人工维护；单任务修补还可能破坏共享技能的其他调用者。",
    methodSummary: "从离线数据重建练习任务，比较普通与特权代理的执行，再由视频分析器诊断失败、修改技能和系统提示，并通过跨任务回归门禁决定是否保留。",
    architecture: "Constructor、Runtime、Privileged、Video Analyzer、Implementor、Merger 六个角色围绕同一套 15 项起始工具/技能迭代，底层模型权重不更新。",
    data: "ABC 数据集提供视频和任务描述；固定 22 个仿真练习任务，15 轮实践；最终在 YAM 真机三项任务各测试 10 次。",
    experiments: "22×10 个留出仿真 episode 上从首轮 28.6% 提至第 15 轮 95.0%；ASPIRE 为 75.5%，最强 CaP-Agent0 为 60.0%；真机 30/30。",
    novelty: "候选技能修改先在全部任务的相同开发 seed 上比较，再合并重测；平均收益和单任务退化门槛共同阻止局部修复回归。",
    strengths: "留出评测、共享技能回归门禁和组件消融完整，并把人类参与限制在任务构建、评价器检查、停止决策和硬件适配。",
    limitations: "真机只有三项、每项 10 次，且经过共同坐标与夹爪适配；毛巾折叠占最终 11 次仿真失败中的 7 次。",
    transfer: "对共享机器人技能库，修改应在依赖它的任务集合上做固定种子回归，而不是只验证触发失败的单一任务。",
    technique: [
      "Reconstruct 从 ABC 中识别能力并创建固定仿真任务与二元 evaluator；起始库由 CaP-X 的 9 个低层工具和 6 个高层技能组成。任务定义和评判在 Practice 前冻结。",
      "每轮中普通代理与可读取模拟器状态的特权代理执行相同任务，Video Analyzer 对照轨迹和源视频生成诊断。每个失败开发任务最多产生一个候选修改，可新增/修改技能或更改系统提示。",
      "候选在 22×5 个固定开发 episode 上与当前系统比较：平均成功率必须上升，且任何任务不得少于基线超过 1/5。通过者合并后再用同一规则重测；模型权重与任务 evaluator 始终不变。",
    ],
    evaluation: [
      "15 轮完成后，逐轮冻结系统在 22 个任务各 10 个独立留出 seed 上回溯评估；最终 209/220（95.0%），ASPIRE 166/220，最强 CaP-Agent0 132/220，RATs 92/220。",
      "五轮组件消融中完整 RPG 为 172/220；无 Video Analyzer 为 114/220，无 Privileged Agent 为 112/220，同时移除两者也是 112/220，表明两类诊断信息互补。",
      "相同的特权脚本调用者只替换技能库时，成功从 19/40 升到 39/40。最终系统在 YAM 三项真机任务各 10 次均成功，但上线前接受坐标、垫片偏移和空夹爪开度适配。",
    ],
    comparison: "CaP-Agent0、ASPIRE、RATs，以及去掉视频分析、特权代理、技能修改和提示修改的诊断消融。",
    implementation: [
      "仿真每个系统每轮需 110 个开发 episode，最终留出评测每个检查点 220 个 episode。候选、合并和 evaluator 均有固定门禁，最终真机使用低推理强度。",
      "项目页已公开；论文给出完整实践协议和任务定义。复现仍依赖模型 API、ABC 数据、模拟器构建细节和硬件适配，成本明显高于单次策略评测。",
    ],
    figureFile: "2610.02204-fig2.png",
    figureAlt: "RPG 从离线示范重建任务并由多代理诊断、修改和回归测试技能库",
    figureCaption: "Figure 2 · 普通/特权执行、视频诊断、技能修改与合并回归门禁。来源：arXiv 原图。",
  },
  {
    title: "Recova: Agent-Guided Failure Recovery for Autonomous Robotic Manipulation",
    arxivId: "2610.01178",
    url: "https://arxiv.org/abs/2610.01178",
    institutions: ["University of California, San Diego", "University of Texas at Austin", "NVIDIA"],
    resources: [{ label: "项目页", url: "https://www.liuisabella.com/Recova" }],
    signal: "把任务执行与场景恢复拆成两套策略，让失败变成可复用的恢复技能和后续示范。",
    tags: ["Failure Recovery", "Digital Twin", "Online Data"],
    classification: { research: "Subtask", training: "BC", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"], deployment: "Real2Sim2Real" },
    motivation: "任务策略训练多来自标准初态的成功轨迹，失败后物体进入长尾状态时，简单重试往往无法恢复可继续执行的场景。",
    methodSummary: "编码代理在数字孪生中开发任务与恢复轨迹及程序；真机监控器触发、验证恢复，无已知技能时请求人类示范，并把不同经验送入对应策略。",
    architecture: "π0.5 任务策略与恢复策略分开微调，Gemini 3.8 Flash 监控完成、介入、恢复和需求；程序式恢复与 learned recovery 共用技能注册表。",
    data: "LIBERO-Pro、MolmoSpaces，以及四台双臂 YAM 工作站；四项真机任务分别开发 6–7 个恢复技能，共 25 个。",
    experiments: "真机四任务每配置各 20 次：基础策略均值 23.8%，DAgger 后 77.5%，启用恢复技能后 87.5%。",
    novelty: "把 task success、人工任务示范、人工恢复示范和验证成功的自主恢复分别路由到任务或恢复数据集，失败前缀只留审计、不作监督。",
    strengths: "两套仿真基准和四项真机都给出直接对照，真实收集还记录了人工介入率、并行吞吐与监控延迟。",
    limitations: "介入率降至 0% 只来自一个任务第四轮的 7 个 episode；监控器延迟约 4.5–5.5 秒，且仍需操作员监督四台设备。",
    transfer: "恢复不必塞进单一任务策略；独立的恢复指令、验证条件和数据流更容易跨任务积累。",
    technique: [
      "数字孪生由相机观测、标定和机器人轨迹重建。编码代理在 MuJoCo 中探索失败，形成任务轨迹、恢复轨迹和可组合的恢复程序；恢复指令 z 与原任务指令 g 分开。",
      "真机循环每 600 步检查完成、每 300 步检查介入，最长任务 5,400 步、恢复 1,500 步。监控器判断场景是否完整并复用已有恢复指令；恢复后用初始和当前图像确认场景可继续。",
      "第 k 轮把成功任务与人工任务示范并入任务数据，把人工恢复与验证通过的自主恢复并入恢复数据。两套 π0.5 分别以 50 步动作块训练；失败策略前缀不作为示范。",
    ],
    evaluation: [
      "LIBERO-Pro 六种设置均值 78.8%，最强对照 ASPIRE 为 71.7%；MolmoSpaces 四类均值 64.9%，最强平均对照 RATs 为 38.0%。基线来自其公开结果，不能视作全部同算力复训。",
      "四项双臂真机任务每种配置各 20 次。基础策略为 20/35/25/15%，DAgger 后为 70/75/85/80%，再启用恢复为 85/90/90/85%，平均 23.8→77.5→87.5%。",
      "麻将绘制任务四轮收集中，人工接管从首轮 7/8（87.5%）降到第四轮 0/7；一段 14 分钟四站并行会话中任务策略完成 22/31 个 episode，人工控制占总工作站时间 11%。",
    ],
    comparison: "CaP-Agent0、RATs、ASPIRE、多种 VLA，以及真机基础策略、DAgger 微调和增加恢复技能三阶段。",
    implementation: [
      "每站两台 I2RT YAM、双平行夹爪、顶视/前视/双腕四台 RealSense，30 Hz。任务策略使用顶视与双腕 224×224 图像，14 维关节目标，50 步动作块；每阶段用 8 张 L40 训练 1–3 小时。",
      "项目页已公开。论文披露监控提示、数据路由、动作维度和完整成功判据；自动技能注册与跨任务共享仍被列为后续工作。",
    ],
    figureFile: "2610.01178-fig1.png",
    figureAlt: "Recova 数字孪生、四站并行 DAgger 和真实机器人恢复技能",
    figureCaption: "Figure 1 · 数字孪生开发、并行真机收集与恢复技能。来源：arXiv PDF 原图裁切。",
  },
  {
    title: "Uni-VLaT: Whole-Body Tactile Adaptation of VLA Policies for Humanoid Loco-Manipulation",
    arxivId: "2609.35450",
    url: "https://arxiv.org/abs/2609.35450",
    institutions: ["清华大学", "北京航空航天大学", "中国传媒大学", "香港大学"],
    resources: [{ label: "项目页", url: "https://uni-vlat.github.io/" }],
    signal: "用全身分布式触觉预测未来触觉、本体与视觉表征，适配预训练人形 VLA。",
    tags: ["Whole-body Tactile", "Humanoid", "VLA Adaptation"],
    classification: { research: "VLA", training: "Post-training", modalities: ["Tactile"], platforms: ["Humanoid"] },
    motivation: "人形机器人持续接触时，遮挡和载荷变化难以仅由视觉与本体状态判断；简单拼接触觉也未必能学到接触与动作的因果联系。",
    methodSummary: "在冻结视觉语言主干上增加触觉通路，用动作专家中的上下文触觉状态同时预测未来触觉、本体和视觉 latent。",
    architecture: "Isaac-GR00T 或 π0.5 主干、触觉与状态编码器、动作专家，以及只在训练期启用的三路未来表征预测头。",
    data: "Unitree G1 上五项接触丰富任务的 50 Hz 轨迹；训练集按 episode 保持边界，未单设验证集。",
    experiments: "主表每任务每方法 20 次，Uni-VLaT 平均 75%，无触觉为 32%，仅触觉无预测为 68%。",
    novelty: "触觉不只是额外输入，而是预测身体响应和场景变化的物理锚点；预测头在部署时移除。",
    strengths: "五项全真机任务、两个 VLA backbone、动作目标相同的触觉/预测消融，并明确把跌倒、急停或额外人工介入计为失败。",
    limitations: "传感阵列对噪声和安装偏差敏感；触觉仿真不足，五项实验也不足以覆盖更细粒度的接触调节。",
    transfer: "新传感模态接入预训练策略时，可用跨模态未来预测迫使其与既有语义和动作空间对齐。",
    technique: [
      "触觉编码先与视觉、语言、本体和动作表征交互，再池化成 tactile-anchored context。三个预测器分别匹配 EMA 目标编码器产生的未来触觉、本体和视觉表征。",
      "预测目标使用未来 4 步的绝对 latent，而不是只预测差分；推理时删除预测头，触觉状态仍作为动作专家条件，因此没有增加未来模型 rollout。",
      "两种预训练 VLA 使用相同触觉接入方式；训练动作损失保持不变，比较项逐步加入触觉输入、未来触觉预测和完整跨模态预测。",
    ],
    evaluation: [
      "五项任务覆盖桌面清扫、背部触碰后行走、篮筐载荷、拥抱和多阶段清扫搬运。主表 20 次/任务，完整模型平均 75%，无触觉 32%，仅触觉无预测 68%，仅预测未来触觉 69%。",
      "在 Isaac-GR00T 上，桌面清扫由 45% 升至 75%，篮筐搬运由 30% 升至 80%，背触行走由 0% 升至 85%；π0.5 对应为 30→60、30→60、0→90%，后者每配置 10 次。",
      "消融显示上下文化触觉预测和绝对未来目标最关键；各消融除完整模型外多为每任务 10 次，且 checkpoint 由真机 rollout 表现选择，需注意选择偏差。",
    ],
    comparison: "无触觉、触觉无预测、仅未来触觉预测、完整三模态预测、从头训练 Diffusion Policy，以及两个 VLA backbone。",
    implementation: [
      "Unitree G1 配全身分布式触觉阵列；观测保存在 50 Hz 网格。论文给出逐任务成功判据与安全失败规则，项目页已公开。",
      "当前未确认完整触觉硬件标定、数据、代码和权重全部开放；没有独立验证集且以真机表现选 checkpoint，复现需预先固定选择协议。",
    ],
    figureFile: "2609.35450-fig2.png",
    figureAlt: "Uni-VLaT 全身触觉接入动作专家及训练期跨模态未来预测",
    figureCaption: "Figure 2 · 触觉条件动作生成与训练期未来触觉、本体、视觉预测。来源：arXiv 原图。",
  },
  {
    title: "Spatial Grafting: Grounding 3D Features for Flow-Matching Robot Policies",
    arxivId: "2609.35249",
    url: "https://arxiv.org/abs/2609.35249",
    institutions: ["University of Toronto", "Huawei Noah's Ark Lab", "Huawei 2012 Labs"],
    signal: "把冻结重建模型的特征绑定到机器人相对度量坐标，再嫁接到 flow action expert。",
    tags: ["3D Geometry", "Flow Matching", "Policy Adaptation"],
    classification: { research: "表征学习", training: "Post-training", modalities: ["Point Cloud / 3D"], platforms: ["机械臂", "Humanoid", "轮式底盘", "夹爪"] },
    motivation: "VLA/WAM 能识别目标和动作语义，却常在接触处缺少度量几何；重建特征本身又不说明表面相对末端的位置。",
    methodSummary: "冻结几何基础模型，把多层特征与深度、相机射线和末端锚点绑定成 spatial bank，只在动作专家后层用 cross-attention 注入。",
    architecture: "DA3 或 VGGT-Ω 特征、每视角空间 bank、主视角与辅助视角两级 cross-attention，以及无 bias 线性融合；宿主感知通路保持不变。",
    data: "同一 graft 适配两种 VLA 与两种 WAM，在 LIBERO、RoboTwin 2.0、RoboPRO、BEHAVIOR-1K 和三种真机平台评测。",
    experiments: "RoboTwin 上 grafted π0.5 为 94.0%/92.4%，比自身基线高 11.3/15.6 点；六项真机任务均提升 20–50 点。",
    novelty: "不是把点云作为新主干，而是让 action token 查询带末端相对坐标的冻结重建 latent，因此同一接口可跨 VLA 与 WAM。",
    strengths: "四个宿主、四套仿真基准和三类真机，逐宿主 base/graft 为主要受控比较，并做 bank 内容、注入层和训练稳定性消融。",
    limitations: "需要深度和相机标定；真实任务每条件仅 10 次，跨论文的 3D 方法行也不是同宿主同协议。",
    transfer: "几何基础模型的 latent 需绑定到机器人参考系，并在动作专家靠后层注入，才能保留原主干语义能力。",
    technique: [
      "每个 RGB 视角经冻结重建模型提取浅层和深层特征；深度、标定射线以及每个末端执行器的相对位移为每个网格位置附加度量 3D 信息，形成 spatial bank。",
      "动作 token 先查询主视角 bank，再查询多个辅助视角 bank；辅助注意力由无 bias 线性层融合后作为残差写回。graft 只进入 flow-matching action expert 的后部 block。",
      "模块只增加 3–5B 宿主约 4–5% 参数，不维护跨帧地图。论文用内容替换、层位移动、warmup/dropout 和 LoRA 对照验证收益来自 grounded geometry。",
    ],
    evaluation: [
      "RoboTwin 2.0 有 50 项任务、clean/random 各 20 个 seed；grafted π0.5 达 94.0%/92.4%，比同宿主基线高 11.3/15.6 点，四个宿主都提高。",
      "BEHAVIOR-1K 六项长程任务各 20 个公开实例，五项提升，平均 Q-score 增加 0.216、最高 0.471；鞋架任务从 0.720 降到 0.590，未隐去负例。",
      "UR5e、双 AgileX Piper 和 Galaxea R1Pro 的六项任务每条件 10 次，成功要求所有子任务完成；六项均提高 20–50 点，茶罐开盖仍只有 10→40%。",
    ],
    comparison: "四个宿主的匹配 base/graft、WAM4D 等公开 3D 方法、B1K challenge 方法，以及空间 bank 内容、注入深度和训练稳定性消融。",
    implementation: [
      "输入仅需 RGB、相机标定与测量或预测深度；不使用实例分割、物体状态或持久地图。论文列出各宿主配置、数据来源和逐任务表。",
      "当前未确认训练代码和权重公开；跨论文对照只作参考，复现应以每个宿主自身 base/graft 为主。",
    ],
    figureFile: "2609.35249-fig1.png",
    figureAlt: "Spatial Grafting 将重建特征绑定到末端相对三维位置并注入动作专家",
    figureCaption: "Figure 1 · 机器人相对空间 bank 与后层 action-expert graft。来源：arXiv 原图。",
  },
  {
    title: "eRLT: Efficient VLA Reinforcement Learning via Action-Relevant Token Routing",
    arxivId: "2610.00913",
    url: "https://arxiv.org/abs/2610.00913",
    institutions: ["南方科技大学", "北京中关村学院", "Samsung Robotics eXperience", "武汉大学", "中山大学"],
    signal: "从冻结 VLA 的不同层和 token 动态路由一个面向动作价值的 RL 状态。",
    tags: ["Online RL", "Token Routing", "VLA Adaptation"],
    classification: { research: "表征学习", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    motivation: "冻结 VLA 的在线 RL 样本效率取决于 actor/critic 状态；固定取最后层或独立视觉编码器都可能漏掉任务相关动作线索。",
    methodSummary: "routing token 从多个 VLA 层聚合视觉语言前缀，再由 layer router 合成固定维度状态；先用专家动作初始化，在线由 critic 误差继续适配。",
    architecture: "冻结 π0.5、一个或多个 routing token、层权重路由器，以及轻量 RL actor/critic；在线不更新原 VLA。",
    data: "四项 LIBERO、三项 RoboTwin，以及 RB-Y1 上 USB 与主板排线插入；真机预算分别 80 与 90 条轨迹。",
    experiments: "七项仿真平均 AUC 比固定 VLA 压缩高 23.7%；USB 真机 AUC 比最强对照高 108.9%，末十次成功率 50→90%。",
    novelty: "层和 token 两级路由不是静态压缩：离线动作预测提供初始状态，在线 Bellman 目标让表示暴露影响价值的细小对齐误差。",
    strengths: "同 VLA、同 actor-critic、同预算只改变状态表示；给出轨迹组成、人工介入规则、最终窗口与 AUC 公式。",
    limitations: "真机只覆盖两项预抓持精密插入；连续五次失败会追加五条人工成功轨迹，因此人类数据量随方法表现变化。",
    transfer: "在线适配应保留 VLA 内部多层动作相关信息，并用离线示范预热路由器，减少 critic 从零发现表示的负担。",
    technique: [
      "routing token 在若干 VLA 深度分别查询视觉语言前缀，得到 uₜ⁽ⁱ⁾；layer router 产生 αᵢ，最终 zₜ=Σᵢαᵢuₜ⁽ⁱ⁾。默认只用一个 routing token，避免有限反馈下多 token 协调成本。",
      "离线阶段用 MLP action probe 从 zₜ 预测专家动作；在线阶段把 critic 的 Bellman 损失反传到路由参数。原 VLA 始终冻结，actor/critic 使用相同的动作残差与奖励流程。",
      "真实训练每项任务固定交互预算；五连败触发五条 SpaceMouse 人工成功轨迹。USB 中 eRLT 66 条自主轨迹有 46 条成功，只需 14 条辅助轨迹。",
    ],
    evaluation: [
      "四项 LIBERO 与三项 RoboTwin 的仿真每项初始成功率以 50 次评估，在线曲线 AUC 跨三 seed；eRLT 对固定压缩 RLT 平均高 23.7%，对独立 DSRL 编码器高 7.1%。",
      "USB 使用 99 条 SFT 示范和 80 条在线预算：eRLT AUC 0.562，RLT 0.269，相对提高 108.9%；末 10 次成功率 90% 对 50%。",
      "排线使用 800 条 SFT 示范和 90 条在线预算：AUC 0.710 对 0.484，提高 46.7%；两者末 10 次都达 100%，因此主要收益是更快学习而非更高终点。",
    ],
    comparison: "RLT 固定 VLA 压缩、DSRL 独立状态编码器、不同层/token 选择，以及去掉 token 路由、层路由、离线初始化或在线适配的消融。",
    implementation: [
      "RB-Y1 左臂、两台腕部 D405、30 Hz；图像 224×224。成功需完全插入，超出常规完成时间约 1.5 倍由操作员判超时，奖励只在成功终止时为 1。",
      "论文给出 AUC 原始积分公式、硬件、拆分 seed 和轨迹组成；当前未确认代码、数据与训练权重开放。",
    ],
    figureFile: "2610.00913-fig3.png",
    figureAlt: "eRLT 多层多 token 路由、离线动作初始化与在线 critic 适配",
    figureCaption: "Figure 3 · 动作相关多层 token 路由与两阶段 RL 适配。来源：arXiv 原图。",
  },
  {
    title: "TOAST: Stochastic Robot Action Tokenization for Autoregressive Vision-Language-Action Models",
    arxivId: "2610.00899",
    url: "https://arxiv.org/abs/2610.00899",
    institutions: ["AIST"],
    resources: [{ label: "项目页", url: "https://kskshr.github.io/toast" }],
    signal: "训练时随机采样可解码为同一动作的 token 序列，提升低数据下的自回归 VLA。",
    tags: ["Action Tokenization", "Autoregressive VLA", "Data Efficiency"],
    classification: { research: "VLA", training: "BC", data: "数据增强", platforms: ["机械臂", "夹爪"] },
    motivation: "FAST 等确定性分词只监督一种切分，但多个 token 序列可还原同一连续动作；有限示范下会过拟合任意的切分边界。",
    methodSummary: "对 DCT 量化后的动作序列用 unigram 模型枚举 n-best 等价切分，训练时按温度采样，推理仍贪心解码。",
    architecture: "保持自回归 VLA 不变，只替换训练期动作 tokenizer；默认 512 词表、64 个候选切分和 dimension-major flattening。",
    data: "词表来自 100 万 DROID 动作块；LIBERO 做全量到 1/16 数据缩放，Franka FR3 上四项真机任务。",
    experiments: "LIBERO 仅 1/16 数据时比确定性版本高 6.8 点；真机四任务平均 50.8%，比确定性版本高 15.8 点、比 FAST+ 高 20.0 点。",
    novelty: "增加的是同一动作的离散监督多样性，不增加示范，也不改变解码后的机器人轨迹。",
    strengths: "三独立 seed、真机每任务每 seed 30 次，并用 episode 与 seed 分层 bootstrap 检查成对差异。",
    limitations: "真实策略开环执行 20 步动作块；实机采样温度由初步试验选择，四项任务仍不足以说明所有动作分布都受益。",
    transfer: "当离散动作存在多种等价分解时，可把分词随机性当作不改变物理标签的数据增强。",
    technique: [
      "动作块先做 DCT、缩放和取整，再按动作维度优先展开。unigram 词表中的 token 可覆盖一个或多个量化值，任意合法切分都经查表和逆 DCT 还原同一动作块。",
      "训练时从 64 个 n-best token 序列按概率采样，LIBERO 温度 α=0.1、真机 α=0.5；推理仍用确定性贪心 token 预测，因此没有采样带来的执行随机性。",
      "主对照 TOAST deterministic 使用完全相同的 DCT、展开顺序、词表与策略，只选择单一切分；因此差异隔离到分词采样。",
    ],
    evaluation: [
      "LIBERO 每 suite 每 seed 500 次、四 suite 共 2,000 次，三独立策略 seed。全数据时收益很小，缩到 1/16 后 dimension-major 成功率比确定性版本高 6.8 点，符合低数据假设。",
      "Franka 四项真机每任务每 seed 30 次，每次覆盖六种物体姿态/颜色/位置配置，三 seed。TOAST 平均 50.8%，比自身确定性版本高 15.8 点，比 FAST+ 高 20.0 点；95% 分层 bootstrap 区间排除 0。",
      "flattening 与词表语料消融显示收益并不依赖默认展开方式；timestep-major 在低数据也有显著收益。确定性重建 FAST 与主对照在各数据规模差距不超过 1.6 点。",
    ],
    comparison: "TOAST deterministic、FAST+、重建 FAST、uniform binning、VQ-VLA、BEAST，以及词表语料、展开顺序、候选数与温度消融。",
    implementation: [
      "Franka Research 3、D405 腕部相机、两台 D435 场景相机与 Robotiq 2F-85；20 Hz 关节目标、20 步动作块、1 kHz 阻抗控制。RTX 4090 生成一秒动作块需 168 ms。",
      "项目页声明代码与视频已开放；论文给出 tokenizer、训练与 bootstrap 协议。未完整核验所有真机示范数据与模型权重是否下载可用。",
    ],
    figureFile: "2610.00899-fig1.png",
    figureAlt: "TOAST 从同一离散动作曲线采样多种等价 token 切分",
    figureCaption: "Figure 1 · 保持连续动作不变的随机动作分词监督。来源：arXiv SVG 原图高分辨率渲染。",
  },
];

export const paperDaily20261002 = formatDaily(entries, "2026-10-02");
