import { formatDaily, type DailyEntry } from "./paper-daily-format";

const entries: DailyEntry[] = [
  {
    title: "InternW0-Δ: A World Action Model Bridging Predictive Dynamics and Actions with 20K+ Hours of Open Data", arxivId: "2609.31394", url: "https://arxiv.org/abs/2609.31394",
    institutions: ["上海人工智能实验室 · Physical Intelligence Team"], signal: "用未来变化监督动作表示，部署时不必先生成未来视频。",
    tags: ["WAM", "Causal Imprint", "Open Data"], classification: { research: "WAM", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪", "灵巧手"] },
    resources: [{ label: "项目页", url: "https://internrobotics.github.io/InternW0-Delta/" }],
    motivation: "视频、语言及三维运动先验能补充动作学习，但直接在线生成未来视频会增加闭环延迟。",
    methodSummary: "视频与动作专家联合训练；Causal Imprint 从可见历史预测未来潜表示的变化，动作分支直接读取这些预测表示。",
    architecture: "Wan2.2-TI2V-5B 视频专家、随机初始化动作 DiT、冻结 RynnBrain1.1-2B，以及仅训练时使用的 4D 教师蒸馏。",
    data: "处理后超过 20,000 小时开放数据，混合机器人示范、UMI、人类第一视角与 Ego2Robot，统一为带有效位掩码的 80 维状态/动作表示。",
    experiments: "LIBERO-Plus 92.8%；RoboTwin clean-only 训练下 Clean2Clean / Clean2Random 为 90.0% / 71.9%。烤面包真机预训练消融从 4/20 提升到 19/20。",
    novelty: "相对仅动作学习，增加稀疏历史、预测变化表示和 4D 蒸馏；推理只走动作路径，不使用真实未来观测。",
    strengths: "公开列出异构数据来源、累积消融和包含通信/预处理的部署延迟。",
    limitations: "四种平台的十一项真机任务并非都有完整成功率统计；水位泛化是成功片段展示，不能等同于系统性泛化评测。",
    transfer: "将未来监督压缩到当前可计算的表示，再与动作生成解耦，适用于受延迟限制的 WAM。",
    technique: ["模型用 30 层双流 MoT 联结视频与动作；视频隐藏维 3,072，动作隐藏维 1,024。动作侧还读取语言、VLM 当前场景表示和本体状态。稀疏历史由 episode 锚点、近期帧和当前帧组成，不维护密集视频缓存。", "Causal Imprint 接受训练期未来 latent 的时间差及语义对齐监督，但其输入不能读取实际未来。Track4World 提供几何和运动蒸馏，学生分支训练后可移除；在线动作不需要运行未来视频 rollout。", "统一动作空间为 80 维，各数据集按有效位计算损失。预训练包含 AgiBot World、RoboMIND、Galaxea、RoboCOIN、RH20T、EgoDex、EgoVerse 和 HyUMI 等；下游再按机器人本体做动作适配。"],
    evaluation: ["LIBERO-Plus 总成功率 92.8%，论文对照的 Qwen-RobotManip-Context 为 91.4%。RoboTwin 在只用 clean 示范训练后测试随机环境：71.9% 对 69.4%；这些数字不能与使用随机示范训练的协议直接比较。", "同配方独立训练的组件消融从 49.59 开始，加入稀疏历史达到 53.47，换入 RynnBrain 条件达到 69.08，加入 Causal Imprint、对齐和 4D 蒸馏依次达到 70.80、76.45、78.37。这组缩小配置的分数不是完整模型的 92.8%。", "四平台十一项真机任务包括夹爪操作与灵巧手操作；明确量化的预训练对照中，烤面包为 4/20 对 19/20，另一实验任务为 0/20 对 19/20。推理累计优化将控制端往返延迟从 780.5 降至 152.8 ms，统计为去掉三次预热后的 50 次请求；水位变化展示没有给出完整试验分母。"],
    comparison: "Qwen-RobotManip-Context、π0.5、OpenWAM-α；稀疏历史、语义条件、Causal Imprint、4D 教师和运行时累积消融。",
    implementation: ["预训练配置为 384×256 视频、33 帧、32 步动作，batch 16，AdamW 学习率 5e-5、weight decay 0.01、5% warmup、BF16。动作损失按机器人/UMI/Ego2Robot/Ego 分别加权 1/0.5/0.1/0.1。", "真机用单张 RTX 5090 32 GiB，30 Hz 控制；32 步预测每执行 16 步重规划，已承诺执行的前缀作为干净条件。原文承诺发布代码、权重和许可允许的数据；项目页入口不等于所有资源已完整开源。"],
    figureFile: "2609.31394-fig1.png", figureAlt: "InternW0 Delta 世界动作模型架构与因果预测表示", figureCaption: "Figure 1 · 视频、动作、语义条件和训练期未来监督。来源：arXiv 原图。",
  },
  {
    title: "Find Something You Can't Do: Agentic Real-World Reinforcement Learning for Self-Improving VLA Models", arxivId: "2609.32069", url: "https://arxiv.org/abs/2609.32069",
    resources: [{"label":"项目页","url":"https://fangyzzz.github.io/FIND.github.io/"}],
    institutions: ["TU Darmstadt / Hessian.AI", "University of Augsburg", "同济大学", "上海智能自主系统研究院"], signal: "根据当前场景和近期失败率选择下一项练习，减少人工复位。",
    tags: ["Real-world RL", "Residual Policy", "Autonomous Practice"], classification: { research: "VLA", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    motivation: "真实机器人继续学习通常需要人工指定练习、判断成功并恢复场景，导致交互难以持续。",
    methodSummary: "视觉语言代理在预定义任务库中选择当前可执行且较弱的任务，用前后图像判断结果，更新冻结 VLA 上的残差策略。",
    architecture: "冻结 π0.5 加离策略残差 RL；critic 仅在残差动作价值高于原策略动作时允许执行修正。",
    data: "八项互相可逆的操作，每项 50 条离线示范，共 400 条；之后在持久工作台上持续采集交互。",
    experiments: "五个 seed、每检查点每任务 20 次人工独立判定，平均成功率由 55% 升至 71.9%。代表性六小时运行有 456 个 episode 和 30 次人工场景恢复。",
    novelty: "把下一项任务的选择与学习弱项绑定，并通过 critic 门控限制破坏性残差，而不是每轮回到固定初态。",
    strengths: "同时检查自动判定与人工判定，公开人工恢复次数，没有把连续运行描述成完全无人干预。",
    limitations: "只在预定义可逆任务库和固定工作空间验证，任务选择不等于自主发现新技能；VLM 判定仍可能出错。",
    transfer: "在有互逆操作的桌面场景中，上一任务的终态可成为下一任务的起点。",
    technique: ["任务库包含放入/取出、堆叠/拆堆、开/关抽屉和挂杯/取杯。代理先判断当前场景允许执行哪些任务，再按近期成功率分配练习权重：wᵢ = max(ε, 1 − p̂ᵢ)，p̂ᵢ 使用最近 20 次记录。", "执行动作是冻结 VLA 的动作加缩放残差，但只有 Q(s, a_base + αa_residual) > Q(s, a_base) + δ 时才采用修正。否则回退到基础动作；价值学习与 actor 更新使用离线示范和新交互。", "结果评估同时读取执行前后的图像，用变化而不是单张结束图像给出训练奖励。任务选择与结果判断是 episode 间的高层环节，不在每个低层控制步调用。"],
    evaluation: ["人工评估覆盖五个训练 seed，八任务各 20 次测试。平均成功率从基础 VLA 的 55% 提高到 71.9%；原文另外比较自动评估与人类评估的一致性。", "代表性六小时轨迹有 456 次练习，其中 426 次不需要场景恢复、30 次需要人工介入，介入比例为 6.58%；最长连续无人恢复约 48 分钟。该统计并不支持完全自主连续六小时的表述。", "移除能力导向的任务选择或 critic 残差门控会降低学习曲线表现。VLM 单独评测各有 100 对任务选择和结果判定样本，所用配置分别达到 96% 和 100%；这一小样本准确率不代表所有部署场景。"],
    comparison: "冻结 π0.5、任务选择策略消融、critic 门控消融、VLM 判定与人工判定。",
    implementation: ["平台为 Franka Panda，8 维动作、两路 224×224 RGB；计算机使用 RTX 4090、i9-14900K 和 64 GB 内存。论文描述了代理提示、回放和恢复规则，实验仍需人工处理无法继续练习的场景。"],
    figureFile: "2609.32069-fig1.png", figureAlt: "FIND 自主选择任务、评估结果和残差强化学习闭环", figureCaption: "Figure 1 · 任务选择、结果判定与残差学习闭环。来源：arXiv 原图。",
  },
  {
    title: "TACTIC: Understanding Tactile Encoders and Conditioning for Contact-rich Robot Manipulation Policies", arxivId: "2609.30969", url: "https://arxiv.org/abs/2609.30969",
    institutions: ["University of Technology Nuremberg", "LMU Munich / MCML", "Karlsruhe Institute of Technology", "Deggendorf Institute of Technology", "UiT / DLR"], signal: "在统一真机协议下比较五种触觉编码器和五种融合方式。",
    resources: [{ label: "项目页", url: "https://utn-air.github.io/TACTIC" }],
    tags: ["Tactile", "Fusion", "Controlled Evaluation"], classification: { research: "表征学习", training: "BC", modalities: ["Tactile"], platforms: ["机械臂", "夹爪"] },
    motivation: "触觉表示常在不同数据与任务上各自评估，难以判断预训练编码器或复杂融合究竟在哪些任务有用。",
    methodSummary: "固定 ACT 策略和采集设置，交叉比较 ResNet18、SARL、T3、Sparsh、UniT 与拼接、FiLM、交叉注意力和两类对比融合。",
    architecture: "两枚 DIGIT 配腕部/侧面相机；触觉编码与融合后的 token 输入 ACT，预测 120 步动作块。",
    data: "四项接触任务各约 100 条、30 Hz 真机示范，测试累计超过 2,000 次真实机器人 rollout。",
    experiments: "USB 任务的 ResNet18+拼接终止成功率为 80%，视觉基线为 55%；拧螺丝中 Sparsh 或 T3 配时序对比融合达到 90%。没有跨任务统一最优组合。",
    novelty: "贡献是控制变量下的设计比较，揭示表示和融合的收益随接触任务改变，而非提出一个普遍替代全部编码器的网络。",
    strengths: "比较覆盖编码器、融合、真实闭环以及光照/干扰物变化，任务之间保留了反例。",
    limitations: "OOD 测试只使用各任务选出的较优变体，且每项十次；不同预训练模型的冻结/微调设置不完全相同。",
    transfer: "先用简单拼接作为任务基线，再判断是否需要预训练触觉或时序对齐。",
    technique: ["五种融合包括直接拼接、以夹爪状态调制特征的 FiLM、触觉 query 查询视觉 K/V 的交叉注意力，以及随机采样和时间采样两种 CLIP 式对齐。时序版本在同一 episode 内抽取 32 帧，间隔至少 30 帧，避免只匹配几乎重复的瞬时图像。", "ResNet18 是通用基线，SARL 在任务数据训练；T3 使用原始触觉输入并冻结，Sparsh 与 UniT 则微调。全部方法接入同一 ACT 控制链，但不能把预训练来源与调参差异解释成单纯网络结构差异。"],
    evaluation: ["四项任务包含 USB 插入、螺丝操作及其他接触操作。USB 中 ResNet18+Concat 的终止成功率 80% 高于视觉基线 55%；T3+FiLM 的阶段完成率可达 75%，但终止成功率为 55%，两者是不同指标。", "螺丝任务的 Sparsh+CLIP-T 和 T3+CLIP-T 终止成功率均为 90%。跨任务平均没有一种预训练编码器与融合组合稳定获胜；使用对比融合的某些组合在其他任务表现较弱。", "OOD 使用干扰物和变化灯光，每个入选变体测试十次。论文同时区分 completion 与 termination；USB 判定要求到达插接位置，并不等价于所有测试都完成施力插到底。"],
    comparison: "五编码器×五融合方法、视觉基线、选定模型的环境扰动测试。",
    implementation: ["Franka FR3，双 DIGIT，D405 腕部与 D435 侧面相机；示范通过带触觉反馈的主从遥操作采集。ACT 动作块 120；论文和项目页列出传感器、预处理及各编码器训练设置。"],
    figureFile: "2609.30969-fig1.png", figureAlt: "TACTIC 触觉编码和多模态融合方法比较", figureCaption: "Figure 1 · 触觉编码器、融合方式与评测任务。来源：arXiv 原图。",
  },
  {
    title: "VisTacAlign: Co-Training Dexterous Policies on Tactile Human and Robot Demonstrations", arxivId: "2609.30959", url: "https://arxiv.org/abs/2609.30959",
    resources: [{"label":"项目页","url":"https://vis-tac-align.github.io"}],
    institutions: ["Stanford University", "ETH Zurich"], signal: "同时对齐人机手型、点云外观和每指接触力，让人类触觉示范参与策略训练。",
    tags: ["Human Demonstrations", "Tactile Alignment", "3D Policy"], classification: { research: "表征学习", training: "BC", modalities: ["Tactile", "Point Cloud / 3D", "Force / Torque"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "灵巧手"] },
    motivation: "把人类与机器人数据简单混合，会同时引入手型、遮挡以及不同触觉传感器量纲的偏差。",
    methodSummary: "手套姿态校正后重定向；在人类双目图像中替换机器人手并重建点云；最优传输把人类每指力映射到机器人传感范围。",
    architecture: "23.5M 参数的 3D-触觉 DiT；点云、本体与逐指接触作为独立 token，六层动作 cross-attention。",
    data: "三项自采任务；电钻最多 26 人类+26 机器人示范，草莓 124+84，乐高最多 50+30。",
    experiments: "电钻 20 次测试中，机器人 26 条示范为 50%，加入 26 条带对齐触觉的人类示范达 70%；乐高 30R 为 10%，50H+30R 为 80%。",
    novelty: "不仅映射运动轨迹，还对齐接触信号的分布和点云的测量噪声，而非向真实点云直接添加干净手模型。",
    strengths: "分别移除视觉对齐和触觉，测试不同机器人示范预算，并报告传感分布匹配指标。",
    limitations: "触觉映射按任务拟合，仍需要机器人接触样本；每指标量丢失剪切力与 taxel 空间分布。",
    transfer: "人类数据迁移可按策略真正消费的模态逐一对齐，而非只处理人体到机器人动作映射。",
    technique: ["Rokoko 手套先以 AVP 指尖位置做一次校准，约束每关节旋转修正不超过 20°；重定向保留掌心—指尖、拇指—指尖及相邻手指的几何向量。人类图像经分割后用机器人纹理手替换，再重跑双目匹配，使噪声和遮挡更接近机器人观测。", "触觉先聚合为五指法向力。对共同参与接触的手指，熵正则最优传输给出 T(x)=Σⱼwⱼ(x)yⱼ，输出是机器人样本的加权平均；ε=0.3，无接触帧保持为零。机器人数据与部署信号不进行这一变换。", "两帧各 4,096 个 XYZ+RGB 点，经 PointNet 产生 8,192 个 128 维视觉 token；逐指力和接触位进入共享触觉编码器，低于 0.05 TU 的 token 丢弃。六层 DiT 预测 64 步动作，执行前 32 步再规划。"],
    evaluation: ["电钻每配置 20 次：26R 点云基线 50%，26H26R 达 70%；10R 为 35%，26H10R 有触觉为 55%、无触觉为 30%。仅加入触觉未对齐的人类运动不能复现完整收益。", "乐高每配置 20 次：50H10R、50H20R、50H30R 分别为 40%、60%、80%；相同前两种预算去掉视觉对齐后为 10%、25%，最高预算去掉触觉后为 70%。", "草莓按三种尺寸各测试十次，机器人视觉基线为 60/70/0%，联合人机带触觉为 90/80/70%。该对照同时改变人类数据和触觉，不能把全部差值单独归因于力对齐；果实损伤尚未系统量化。"],
    comparison: "机器人单独训练、RGB/点云、移除人类触觉、移除重投影对齐、不同示范预算。",
    implementation: ["xArm 7 + ORCA Hand v2，Rokoko 电容触觉手套、VIVE 和 ZED 2i；训练 batch 64、学习率 1e-4，单 RTX 4090 耗时 5–25 GPU 小时。10 步 flow 推理在 RTX 4080 为 269 ms；接触值是传感器 TU，不是经过统一标定的牛顿。"],
    figureFile: "2609.30959-fig2.png", figureAlt: "VisTacAlign 人机运动视觉触觉三路对齐与策略训练", figureCaption: "Figure 2 · 人机多模态对齐与共同策略训练。来源：arXiv 原图。",
  },
  {
    title: "AnyStep-WAM: Budget-Aligned Distillation and Adaptive Inference for World Action Models", arxivId: "2609.33748", url: "https://arxiv.org/abs/2609.33748",
    institutions: ["南方科技大学", "香港大学", "Shenzhen Loop Area Institute"], signal: "同一个蒸馏模型按当前动作难度选择去噪步数，而非一直使用固定预算。",
    tags: ["WAM Distillation", "Adaptive Inference", "Real-time"], classification: { research: "WAM", deployment: "真机部署优化", training: "Post-training", platforms: ["Humanoid", "夹爪"] },
    motivation: "固定多步去噪把同样计算花在简单移动和精细接触上；直接跳步又会降低动作质量。",
    methodSummary: "从冻结教师轨迹监督不同时间区间的平均速度，用共享 LoRA 学习任意预算，再用一次预览预测难度和预算收益。",
    architecture: "适配 Motus、FastWAM 和 LingBotVA；轻量调度器选择步数，首次预览作为正式推理的第一步复用。",
    data: "RoboTwin 50 项双臂任务；六项 G1D 真机任务各 50 条示范，用原模型产生离线教师监督。",
    experiments: "RoboTwin 上三个模型分别平均使用 3.98、5.03、3.68 步，与原多步模型成功率差不超过 0.24 个百分点；真机 FastWAM 延迟 280→122 ms，平均成功率 70.00→71.67%。",
    novelty: "显式教师区间目标替代随学生变化的导数监督，同时训练从复用预览状态继续生成的恢复项。",
    strengths: "三个 backbone、六项真机任务，并报告实际延迟而不只报告减少的网络调用次数。",
    limitations: "调度器的 risk 指教师轨迹变化，不是物理失败概率或安全证书；真机每任务平均二十次，较小成功率差需谨慎解释。",
    transfer: "训练时覆盖部署会遇到的时间区间，并把调度预览计入总预算，能减少隐藏的额外推理成本。",
    technique: ["教师区间平均速度为 v̄ᵀₜ,ᵣ=(xᵀₜ−xᵀᵣ)/(t−r)。学生以共享 LoRA 预测有限时间跳转；训练同时包含区间、局部 flow、直达端点及预览后恢复四个损失，教师权重固定。", "调度器从一步预览的隐藏表示和速度摘要预测教师曲率难度以及各预算下的学生—教师一致性。选择满足预测阈值的最小预算 K；若选 K>1，将预览重新加噪到第一个中间时刻，再执行 K−1 步，总调用仍为 K。", "原文的 risk 是去噪速度方向与大小变化的训练集相对排序，benefit 也是教师一致性代理。部署既不调用教师，也不对所有候选预算分别 rollout。"],
    evaluation: ["RoboTwin 每任务每方法 100 次。Motus / FastWAM / LingBotVA 的原模型平均成功率为 87.84/91.83/92.24%，自适应版为 87.96/91.59/92.22%；A100 延迟分别由 1.932/0.496/9.732 秒降至 0.859/0.295/3.247 秒。", "G1D 六任务平均每任务二十次测试。三个模型成功率由 65.83/70.00/68.33% 变为 69.17/71.67/70.00%，RTX 5090 实测加速分别为 1.67×、2.30×、6.14×。各任务并非都改善，例如 FastWAM 擦桌与放方块下降。", "Motus 移除区间监督后，自适应成功率从 87.96 降至 78.09%，平均步数由 3.98 增至 5.27；移除端点项主要损伤一步性能。阈值上下移动五个百分位可改变计算量，但测试范围内成功率差不超过 0.36 个百分点。"],
    comparison: "原始多步/一步模型、Flash-WAM、训练后启发式门控、区间/端点/恢复项消融。",
    implementation: ["每个 backbone 用四张 H100、global batch 32 训练 8,000 步。教师冻结，只训练 LoRA 和调度器；真实平台为 Unitree G1D 与 Dex1-1 夹爪。附录给出损失、预算集合和难度阈值定义。"],
    figureFile: "2609.33748-fig2.png", figureAlt: "AnyStep WAM 教师区间蒸馏和自适应去噪预算", figureCaption: "Figure 2 · 教师区间监督、预算预测与预览复用。来源：arXiv 原图。",
  },
  {
    title: "RecastVLA: From Past Interaction to Future Control with Adaptive Policy States", arxivId: "2609.32155", url: "https://arxiv.org/abs/2609.32155",
    institutions: ["华南理工大学", "Yuanwu Technology"], signal: "把动作生成过程写入共享快权重，为下一次决策保存执行进度。",
    tags: ["Memory", "Fast Weights", "Sequential Manipulation"], classification: { research: "Memory", training: "BC", platforms: ["机械臂", "夹爪"] },
    motivation: "按钮顺序和重复操作的历史不总能从当前图像看出，单帧策略难以判断任务已进行到哪一步。",
    methodSummary: "每次生成动作时读取同一个共享快权重，生成结束后汇总各层特征做一次写入更新，再服务下一次策略调用。",
    architecture: "Qwen3-VL-4B-Instruct、GR00T 风格动作专家、八处记忆读取接口，以及 256→512→256 的共享快权重 MLP。",
    data: "LIBERO、RoboTwin clean 示范和 RoboDojo；真机 55 项训练任务各十条示范，测试十二项保留变体。",
    experiments: "真机每项二十次，RecastVLA 131/240（54.58%），同结构无记忆基线 74/240，π0.5 为 102/240。相对 π0.5 的 29 次净增成功中，26 次来自三个按钮任务。",
    novelty: "跨层共享的是可更新函数，而非各层独立缓存；通过后续动作损失学习如何写入记忆。",
    strengths: "提供匹配训练基线、状态连续性和跨层共享消融，并明确收益集中在哪些任务。",
    limitations: "训练四帧间隔与部署动作块间隔不同；它在动作执行前更新，不能把该写入称为基于实际执行结果的在线纠错。",
    transfer: "在当前画面几乎不变的操作序列中，小型可适应状态可补充视觉上下文。",
    technique: ["每次策略调用内 Wₜ 固定，八个深度位置各用 32 个 768 维 slot 查询同一个快权重 MLP。动作 token 本身不直接读记忆，而通过后续 self-attention 接收已适配的 slot。", "各层、各 flow 时刻生成键值对，拟合内部写入目标；边界更新为 Wₜ₊₁ = Wₜ − η∇L_write(Wₜ)。只做一次联合梯度更新，不在去噪中途修改状态；新 episode 从学得的 W₀ 开始。", "训练展开四个连续观测，后续动作误差经过状态更新回传，学习初始化、读取投影和更新规则。部署仅更新快权重，不需要专家动作标签，也不跨调用保留完整反向图。"],
    evaluation: ["RoboTwin Clean2Clean 为 72.38%，匹配基线 61.70%；随机环境为 19.24% 对 10.50%，仍低于论文表中若干大规模预训练策略。每次调用重置状态会降低成绩；共享设计比独立层内 TTT 高 2.58 个百分点。", "双 SOARM101 的十二项测试每项二十次，三方法使用相同 550 条微调示范。整体为 131/240 对 74/240 和 102/240；按钮顺序 75% 对匹配基线 20%，重复按键 60% 对 5%。", "对比 π0.5，除三个按钮任务外的九项任务均值仅为 50.56% 对 48.89%，牙刷摆放、杯盖和擦拭仍有退步。扰动后的恢复视频未计入主表成功率，不能作为额外量化测试。"],
    comparison: "Matched Base、π0.5、状态重置/导入、独立层内 TTT。",
    implementation: ["基于 StarVLA/VLAct，记忆 MLP 使用 GELU，初始更新步长 η₀=0.1；学习层权重和 flow 时间门控。LIBERO 配置预测八步动作、四次 Euler 求解；真机训练/测试组成和完整计数在附录 B。"],
    figureFile: "2609.32155-fig2.png", figureAlt: "RecastVLA 共享快权重读取写入与跨步学习", figureCaption: "Figure 2 · 一次动作生成内共享状态，调用之间更新记忆。来源：arXiv 原图。",
  },
  {
    title: "Copper-Policy: Focus on the Representation for Robust Robot Manipulation", arxivId: "2609.32779", url: "https://arxiv.org/abs/2609.32779",
    institutions: ["香港大学", "悉尼大学", "清华大学", "DenseAI"], signal: "用紧凑未来表示训练控制先验，同时保留当前帧的精细空间信息。",
    tags: ["WAM", "JEPA", "Representation"], classification: { research: "WAM", training: "BC", platforms: ["机械臂", "夹爪"] },
    motivation: "预测密集未来特征开销大，但只保留高度压缩表示又可能丢失精确抓取所需的当前细节。",
    methodSummary: "语言条件压缩器生成紧凑世界 token，EMA 分支提供未来目标；动作专家另接当前视觉细节，未来预测分支只在训练时生成目标。",
    architecture: "冻结 V-JEPA 编码器、可训练在线/EMA 压缩器、Future/Action 两个专家与非对称注意力掩码。",
    data: "不使用机器人预训练；LIBERO 与 RoboTwin 示范，以及三项双臂真机任务各 300 条、合计约 4.3 小时遥操作。",
    experiments: "LIBERO-Plus 80.85%；RoboTwin clean/random 为 70.84/12.98%。三项真机各五十次，混合完成分 96.3，对 π0.5 的 94.3 与 Fast-WAM 的 84.0。",
    novelty: "让未来目标保持紧凑，而动作仍直接读取当前空间细节；动作损失同时约束压缩空间。",
    strengths: "分别移除未来预测与当前视觉通路，并报告训练吞吐和随机环境中的不足。",
    limitations: "随机环境泛化明显弱于部分机器人预训练模型；训练速度优势不等于推理速度优势，真机指标含半完成分。",
    transfer: "未来预测通路与精确控制通路可以采用不同信息瓶颈，而不要求同一套紧凑 token 承担全部功能。",
    technique: ["压缩器根据语言读取冻结视觉特征，得到 zₜ=Cφ(f(oₜ),eₛ)，LIBERO 为 28 个 token，真机与 RoboTwin 为 36 个。未来目标来自停止梯度的 EMA 压缩器，使目标空间随训练缓慢变化。", "Future Expert 用 flow matching 预测未来压缩特征；Action Expert 读取当前世界 token、直接视觉 token 和状态，但不读取生成的未来 token。非对称注意力让未来监督塑造表示，同时避免精细控制完全依赖压缩目标。", "部署时只生成当前条件缓存和动作，十步 flow 解码不实例化未来视频 token。训练样本 token 从 Fast-WAM 的 392 个减为 244 个；这主要减少训练端未来预测开销。"],
    evaluation: ["LIBERO 40 任务各五十次，总成功率 97.25%；LIBERO-Plus 80.85%，低于对照 π0.5 的 85.7%。RoboTwin 每任务每设置一百次，Clean2Random 只有 12.98%，不能由 clean 的 70.84% 推断普遍稳健。", "三项真机是叠碗、香蕉放置和毛巾折叠，每任务 300 条示范、五十组初始化。评分按完全/部分/失败计 1/0.5/0，因此 96.3 是完成分而非二元成功率；π0.5 为 94.3，折毛巾单项仍由 Fast-WAM 更高。", "去掉未来联合嵌入预测，真机均分降到 43.3；去掉当前视觉细节降到 20.7。论文训练速度比较同时涉及 DDP/FSDP 配置差异；RTX 5090 的 85 ms 推理并不优于表中 Fast-WAM 的 80 ms 或 π0.5 的 75 ms。"],
    comparison: "Fast-WAM、π0.5、Cosmos-Policy；未来联合预测、当前视觉和世界输入消融。",
    implementation: ["双六自由度机械臂、夹爪、三路 RGB，14 维绝对关节动作，无深度输入；示范 30 Hz。真实评测使用相同初始化随机种子与实时动作分块。在线和 EMA 压缩器共享冻结视觉编码器，EMA 分支不接收梯度。"],
    figureFile: "2609.32779-fig2.png", figureAlt: "Copper Policy 在线与EMA表示及双专家动作架构", figureCaption: "Figure 2 · 紧凑世界表示、未来预测与当前视觉动作通路。来源：arXiv 原图。",
  },
];

export const paperDaily20260928 = formatDaily(entries, "2026-09-28");
