import type { Paper } from "./site-data";

export const paperDaily20260717Additions: Paper[] = [
  {
    rank: 11,
    title: "RoboTTT: Context Scaling for Robot Policies",
    arxivId: "2607.15275",
    url: "https://arxiv.org/abs/2607.15275",
    institutions: ["NVIDIA", "Stanford University", "The University of Texas at Austin"],
    signal: "用测试时更新的 fast weights 压缩连续观测—动作历史，使机器人策略在固定状态大小下利用最长 8K timesteps 的上下文",
    tags: ["Long Context", "Test-time Training", "Robot Memory"],
    classification: { research: "Memory", training: "Test-time Adaptation", platforms: ["机械臂", "夹爪"] },
    detailAttributes: { memoryImplementation: "TTT fast weights 压缩连续观测与动作历史", memoryHorizon: "最高 8K timesteps" },
    resources: [{ label: "项目页", url: "https://research.nvidia.com/labs/gear/robottt/" }],
    motivation: "长时装配中的阶段、失败和纠正会跨越数千步；直接拼接历史帧的显存与计算量随序列增长，固定窗口又会遗忘早期状态。",
    methodSummary: "在 GR00T N1.7 的 DiT 动作头中插入 TTT 层，以小型 MLP 的 fast weights 作为序列状态；每个时间步依据当前 token 做一次自监督更新，再用更新后的状态生成动作。",
    architecture: "帧内 token 仍由注意力交互，跨时间信息由 TTT-MLP 写入固定大小 fast weights；训练使用 sequence action forcing，部署时随 rollout 持续更新状态。",
    optimization: "采用 truncated BPTT 控制反向传播长度，并比较 1K 与 8K 上下文；主干从 GR00T N1.7 初始化，TTT 层和动作预测一起训练。",
    data: "YAM 双臂平台三项长时装配任务，真实数据量分别约 8、6、5 小时，任务包含多阶段取放、对齐、装配和错误恢复。",
    experiments: "三项真机任务平均完成度 79%，单步基线为 42%；8K 上下文整体高于 1K，说明增益并非只来自新增层参数。",
    novelty: "相比缓存所有历史 token 或固定窗口注意力，RoboTTT 把历史压入可在线更新的模型参数，并把 TTT 层直接嵌入机器人动作 DiT。",
    strengths: "用复杂双臂真机任务直接检验长上下文，报告 1K/8K 对照和失败案例，项目页提供任务视频。",
    limitations: "训练使用 16 张 GB200，成本高；三项任务和单一平台不足以证明跨本体泛化，fast weights 也不能保证保留所有关键事件。",
    transfer: "适合将阶段完成、失败恢复和动作块历史压缩为固定大小策略状态，尤其适用于上下文远长于普通 VLA 窗口的任务。",
    experimentDetails: [{
      title: "长时双臂装配与上下文长度",
      setup: "YAM 双臂真实系统上的三项多阶段装配任务，分别约 8、6、5 小时训练数据；按任务进度而非只按最终成功评估。",
      comparisons: "单步 GR00T N1.7、有限历史基线、RoboTTT-1K 与 RoboTTT-8K，并检查不同序列训练设置。",
      results: ["RoboTTT 平均任务完成度为 79%，单步基线为 42%。", "8K 上下文版本整体高于 1K，长任务后段差距更明显。", "失败案例显示 fast weights 能记录部分纠正历史，但遇到训练分布外的物体状态仍会失效。"],
    }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["GR00T N1.7 DiT + TTT-MLP；sequence action forcing；truncated BPTT；1K/8K context。", "论文报告 16×GB200 的训练配置和三项任务数据时长。"], verifiedResources: ["官方项目页、论文和真机视频可核验。"], missing: ["训练代码、模型权重、YAM 数据与完整超参数尚未确认公开。"] },
    deepDive: {
      lead: "RoboTTT 的核心不是把更多图片塞进上下文，而是把跨时间历史写进一组随序列更新的 fast weights。",
      sections: [{ title: "帧内注意力与跨帧 TTT", paragraphs: ["普通注意力继续处理同一时刻的视觉、语言和本体 token；TTT 层把每一时刻的表示视为一条训练样本，对内部 MLP 做一次轻量更新。更新后的参数成为下一时刻的固定大小状态。", "sequence action forcing 让训练时的序列输入更接近真实执行，truncated BPTT 则限制跨步梯度范围，避免 8K 序列的完整反向传播成本。"] }],
      equations: [{ name: "fast-weight 更新", expression: "W_t = W_{t-1} - eta * grad_W L_TTT(W_{t-1}; x_t)", explanation: "每个时间步用当前 token 的自监督目标更新内部权重 W；后续动作预测读取 W_t，而不必保留全部历史 token。" }],
      experimentReading: ["1K/8K 对照把上下文长度与新增结构区分开；79% 是跨阶段任务进度汇总，不应等同为三项任务的统一最终成功率。"],
      reflections: [],
    },
    figures: [{ src: "/report-assets/2026-07-17/2607.15275-architecture.png", alt: "RoboTTT 在 DiT 动作头中插入跨时间 TTT 层并维护 fast weights 的训练与推理结构", caption: "Figure 2 · RoboTTT 模型、训练与推理：注意力处理帧内信息，TTT 层以 fast weights 压缩跨帧历史。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 12,
    title: "Never Too Late for Force: Accelerating VLA Post-Training with Reactive Force Injection",
    arxivId: "2607.14236",
    url: "https://arxiv.org/abs/2607.14236",
    institutions: ["Shanghai Jiao Tong University", "Shanghai Innovation Institute", "Southern University of Science and Technology", "Noematrix Ltd."],
    signal: "保留预训练 VLA 的语义主干，增加读取短期六维力历史的 reactive action expert，并用在线纠正数据快速补齐接触反应",
    tags: ["Force / Torque", "Post-training", "Online Correction"],
    classification: { research: "VLA", training: "Post-training", modalities: ["Force / Torque"], data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://lift-policy.github.io/" }],
    motivation: "大规模视觉语言预训练能理解任务，却很难从图像及时识别插入、压合和摩擦中的微小接触偏差；从头训练多模态模型又会丢失原有能力。",
    methodSummary: "LIFT 复制一个 reactive action expert，通过零初始化 cross-attention 读取短期 6D 力/力矩记忆；在原策略失败区域由人工在线纠正，并把新轨迹与离线数据混合后训练。",
    architecture: "视觉语言主干和原 action expert 保持原有路径，新增专家专门建模快速物理反馈；zero-init 接口使初始策略等价于原 VLA，随后逐步学习力觉残差。",
    optimization: "先从预训练 VLA 初始化，再执行多轮 online rollout、人工接管与 DAgger 式聚合；论文分别消融力输入、reactive expert 与在线纠正。",
    data: "Flexiv Rizon 4S 上毛巾折叠、书本插入和汉诺塔放环三项接触任务，混合原离线示范与多轮在线人工纠正轨迹。",
    experiments: "三项真机任务中完整 LIFT 均优于视觉-only、只加力输入和无在线纠正变体；结果表明结构与在线数据二者缺一都会降低接触阶段成功率。",
    novelty: "相对把 force 直接拼接到 VLA 输入，LIFT 用独立快速专家隔离接触反应，并通过零初始化接口避免破坏预训练行为。",
    strengths: "三类真实接触任务、结构消融和在线纠正消融围绕同一主张展开，部署链路清楚。",
    limitations: "依赖人工接管与多轮采集，只验证单臂平台；论文未证明力传感器变化或更长任务下仍能直接迁移。",
    transfer: "可将 force、tactile 或高频 proprioception 作为旁路快速专家输入，保留慢速语义策略并只在接触阶段修正动作。",
    experimentDetails: [{ title: "接触任务与在线纠正消融", setup: "Flexiv Rizon 4S 的毛巾折叠、书本插入、汉诺塔放环；多轮在线 rollout 由人工在失败前后接管。", comparisons: "原 VLA、直接拼接 force、无 reactive expert、无 online correction 与完整 LIFT。", results: ["完整方法在三项任务上均取得最高成功率，提升集中在对齐、插入和放环等接触阶段。", "移除力记忆后策略更容易在视觉变化很小的卡住状态持续输出错误动作。", "只增加结构而不聚合在线失败分布，仍明显弱于完整方法。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["6D force/torque 短期记忆；reactive action expert；zero-initialized cross-attention；offline + online correction 混合训练。"], verifiedResources: ["项目页、三项真机视频、论文中的结构与对照可核验。"], missing: ["代码、数据、权重与逐轮在线样本数尚未确认公开；项目页仅承诺后续发布。"] },
    deepDive: { lead: "LIFT 将语义动作与接触反应拆成两条时间尺度不同的路径。", sections: [{ title: "零初始化的力觉旁路", paragraphs: ["新增专家读取最近一段力/力矩序列，再通过 cross-attention 影响动作表示。接口从零开始，使第一次初始化不会改变原 VLA 输出，训练后才逐渐放大可靠的接触修正。", "在线阶段收集的不是随机新轨迹，而是原策略真正进入失败分布时的人类纠正；这些样本与离线示范混合，减少只在干净专家轨迹上学习造成的 covariate shift。"] }], equations: [{ name: "混合动作专家", expression: "h_action' = h_action + CrossAttn(h_action, h_force)", explanation: "力觉分支作为对原动作表示的增量；交叉注意力输出采用零初始化，开始训练时不会扰动预训练策略。" }], experimentReading: ["论文的关键证据来自同一平台上的组件消融；公开页面没有足够信息支持跨传感器或跨本体结论。"], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-17/2607.14236-architecture.png", alt: "LIFT 在预训练 VLA 旁加入 reactive action expert 并通过交叉注意力注入力记忆", caption: "Figure 2 · LIFT 保留视觉语言主干，并以 reactive action expert 注入短期力记忆。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 13,
    title: "Representation-Aligned Tactile Grounding for Contact-Rich Robotic Manipulation",
    arxivId: "2607.14609",
    url: "https://arxiv.org/abs/2607.14609",
    institutions: ["Fudan University", "Lenovo CTO Organization", "Nanyang Technological University", "TeleAI, China Telecom"],
    signal: "先探测 action expert 各层对未来触觉的可预测性，再把训练期触觉监督放到物理信息最集中的中间层",
    tags: ["Tactile", "Representation Grounding", "Contact-rich Manipulation"],
    classification: { research: "表征学习", training: "Post-training", modalities: ["Tactile"], platforms: ["机械臂", "夹爪"] },
    motivation: "给 VLA 增加触觉 loss 并不等于动作表征真正学到接触动力学；如果监督位置与物理信息所在层不一致，额外模态可能只增加训练负担。",
    methodSummary: "先对 action expert 的不同中间层训练 linear probe，定位最能预测未来触觉的层；再接入 Latent Tactile Predictor，以未来触觉为训练期辅助目标。",
    architecture: "视觉语言与动作主干保持不变，LTP 只读取选定的 action-expert latent；部署时移除触觉预测头，因此不增加在线推理模块或传感输入。",
    optimization: "在 SmolVLA 与 π0 两个 backbone 上后训练，比较层位置、无对齐的触觉接口和基础模型；触觉目标用于整形动作 latent。",
    data: "ARX R5 配 PaXini 触觉传感器，五项接触任务，每项 50 条专家示范；每种方法每项执行 20 次真机试验。",
    experiments: "两个 VLA backbone 上均高于各自基础模型和未对齐触觉接口；不同层消融显示，linear probe 选出的中间层也是后训练收益最大的监督位置。",
    novelty: "相对统一在末层加辅助 loss，论文把‘哪一层包含可用物理信息’变成可测问题，再依据诊断结果放置触觉目标。",
    strengths: "层级 probe、监督位置消融、两个 backbone 和五项真机任务形成闭环证据。",
    limitations: "单一机器人与触觉硬件、每项 20 次；尚未证明所选层在更大模型或不同传感器上保持一致。",
    transfer: "同样的 probe-first 流程可用于 future force、contact phase 或 failure risk，先定位可预测层再施加训练期辅助监督。",
    experimentDetails: [{ title: "表征层选择与真机验证", setup: "ARX R5 + PaXini，五项接触操作，每任务 50 条示范；每个 backbone、方法和任务 20 次真机试验。", comparisons: "SmolVLA/π0 基础模型、未对齐触觉接口、不同 action-expert 层与完整 LTP。", results: ["完整方法在 SmolVLA 与 π0 上均高于基础模型。", "把触觉监督接在 probe 可预测性较低的层会削弱收益。", "推理时移除 LTP，结果改善来自训练后的动作表征而非新增在线触觉闭环。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["逐层 linear probe；future tactile target；Latent Tactile Predictor；training-only auxiliary head。"], verifiedResources: ["ARX R5、PaXini、五任务×50 demos、每方法×20 trials 和两个 backbone 均由论文核验。"], missing: ["代码、数据、权重和触觉标定参数尚未确认公开。"] },
    deepDive: { lead: "这项工作先回答‘动作模型的哪一层已经包含接触信息’，再决定把触觉监督接在哪里。", sections: [{ title: "从诊断到后训练", paragraphs: ["linear probe 冻结主干，只测各层 latent 对未来触觉的线性可预测性；最高的层被视为语义与动作动力学较好交汇的位置。", "LTP 在该位置预测未来触觉，使动作 latent 对即将发生的接触变化更敏感。测试时预测头被删除，控制接口保持原样。"] }], equations: [{ name: "触觉辅助目标", expression: "L = L_action + lambda_tac * ||g(h_l) - z_tac_future||", explanation: "g 从选定层 h_l 预测未来触觉表示；lambda_tac 控制辅助目标对动作训练的权重。" }], experimentReading: ["两个 backbone 的一致方向支持方法不只依赖单一架构，但单平台规模仍不足以断言最佳层具有普遍性。"], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-17/2607.14609-overview.png", alt: "在训练阶段从动作专家中间表征预测未来触觉并对齐接触动力学", caption: "Figure 3 · 在最具接触可预测性的 action-expert 中间层施加触觉监督，推理时移除预测头。图片来自 arXiv 原论文。" }],
  },
];
