import type { Paper, PaperEquation } from "./site-data";

type Entry = Omit<
  Paper,
  "rank" | "figures" | "optimization" | "experimentDetails" | "reproducibilityDetails" | "deepDive"
> & {
  figureFile: string;
  figureAlt: string;
  figureCaption: string;
  technique: string[];
  evaluation: string[];
  comparison: string;
  reproducibilityStatus: "资源较完整" | "部分可复现" | "信息不足";
  implementation: string[];
  missing: string[];
  equations?: PaperEquation[];
};

const makePaper = (entry: Entry, index: number): Paper => ({
  ...entry,
  rank: index + 1,
  optimization: entry.technique.join("；"),
  experimentDetails: [{
    title: "原文实验与消融",
    setup: entry.experiments,
    comparisons: entry.comparison,
    results: entry.evaluation,
  }],
  reproducibilityDetails: {
    status: entry.reproducibilityStatus,
    verifiedResources: entry.resources?.map((resource) => `${resource.label}: ${resource.url}`) ?? ["arXiv 论文正文"],
    implementation: entry.implementation,
    missing: entry.missing,
  },
  deepDive: {
    lead: entry.methodSummary ?? entry.signal,
    sections: [{ title: "方法与模型改进", paragraphs: entry.technique }],
    equations: entry.equations,
    experimentReading: entry.evaluation,
    reflections: [entry.transfer],
  },
  figures: [{
    src: `/report-assets/2026-08-31/${entry.figureFile}`,
    alt: entry.figureAlt,
    caption: entry.figureCaption,
  }],
});

const entries: Entry[] = [
  {
    title: "𝒩₀-Foundation: Towards the Age of Tactile Intelligence",
    arxivId: "2608.29601",
    url: "https://arxiv.org/abs/2608.29601",
    institutions: ["NeoteAI Team", "Fudan University TEAI Team"],
    signal: "公开 3 万小时跨本体视觉—触觉数据，并把稠密三轴力场作为视觉表征的预训练目标和策略条件。",
    tags: ["Visuo-Tactile", "Foundation Model", "Cross-Embodiment"],
    classification: { research: "表征学习", training: "Pre-training", modalities: ["Tactile", "Force / Torque"], data: "跨本体数据", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    resources: [
      { label: "项目页", url: "http://research.neoteai.com/n0-foundation" },
      { label: "模型", url: "https://huggingface.co/datasets/NeoteAIEmbodied/OpenNeoData" },
    ],
    motivation: "现有机器人基础模型的数据以 RGB 与动作轨迹为主，接触状态通常被压缩成低维力读数，难以支撑跨任务的接触推理。",
    methodSummary: "N0-Foundation 以共享 ViT 编码 RGB 和稠密三轴力场，通过力场重建与 EMA 潜变量预测学习 NeoForce 表征，再把该表征接入通用操作策略。",
    architecture: "RGB 与触觉图像进入 DINOv2 初始化的 ViT-B；触觉分支预测稠密力场，联合重建目标和教师—学生潜变量目标训练，策略端按动作块读取视觉、触觉与语言条件。",
    data: "NeoData 超过 30,000 小时、140 万条 episode、33 亿时间步、80 亿 RGB 帧与 100 亿触觉帧，覆盖 6 种本体和 450 余项任务；公开子集约 5,000 小时。",
    experiments: "NeoSim 在 12 个任务各跑 100 次；NeoReal 在 10 个任务各跑 20 次，并另做 30 个任务的触觉预训练与表征消融。",
    novelty: "NeoSim 中 π0.5 平均成功率 45.8%，高于 LingBot-VA 的 32.1%；NeoReal 中加入 NeoForce 后平均阶段成功率从 38.1% 提升到 47.5%。",
    strengths: "数据规模、任务跨度和触觉密度均较少见；既报告仿真与真机结果，也将触觉表征本身单独消融。",
    limitations: "当前触觉主要来自平行夹爪上的视触觉相机；灵巧手等本体尚未覆盖，仿真到真机的触觉差异仍未解决。",
    transfer: "视觉预训练管线可以加入稠密力场重建与潜变量一致性目标，让触觉先作为可迁移表征学习问题处理，再进入下游策略。",
    technique: [
      "NeoForce 将触觉图像转换为像素级三轴接触力场；RGB 与触觉使用共享 ViT-B 表征空间，避免把接触信息只压成一个合力向量。",
      "预训练同时最小化力场重建误差和 EMA 教师提供的潜变量预测误差；下游策略使用长度为 4 的动作块，使触觉反馈与短时控制对齐。",
      "表征实验使用 20,000 条示范、30 个任务和 2,500 条留出轨迹，训练 100k 步、8 张 A100、学习率 2e-5。",
    ],
    evaluation: [
      "NeoReal 的十项任务每项 20 次随机化试验；π0.5 的平均 SR/PSR 为 26.5%/38.1%，NeoForce 条件主要提高阶段完成度而非只改变视觉质量。",
      "NeoSim 每项任务 100 次，π0.5 为 45.8%，LingBot-VA 为 32.1%，Fast-WAM 在这套动作接口下为 0；跨框架适配差异仍可能影响比较。",
      "触觉预训练消融显示仅重建或仅潜变量预测都弱于联合目标，说明收益不只是增加一个触觉输入通道。",
    ],
    comparison: "π0.5、LingBot-VA、Fast-WAM，以及无触觉、仅重建、仅潜变量预测和完整 NeoForce 的消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["公开 5,000 小时子集入口，并披露 ViT-B 初始化、动作块长度、训练步数、学习率和硬件规模。"],
    missing: ["完整 30,000 小时数据与全部训练权重的开放范围仍有限；灵巧手触觉标定和跨设备复现尚未覆盖。"],
    figureFile: "2608.29601-fig1.png",
    figureAlt: "N0-Foundation 数据、触觉表征预训练和下游策略总览",
    figureCaption: "Figure 1 · NeoData、NeoForce 表征预训练与跨本体操作评价。来源：arXiv 原图。",
  },
  {
    title: "AnyWorld: Factorized Egocentric World Models for Cross-Embodiment Generalization",
    arxivId: "2608.29242",
    url: "https://arxiv.org/abs/2608.29242",
    institutions: ["Nanyang Technological University", "A*STAR Institute for Infocomm Research", "XPENG Robotics", "Zhejiang University", "The Chinese University of Hong Kong"],
    signal: "把人类第一视角视频与机器人视频解耦为动作、相机和本体三个条件，让世界模型在没有成对人机数据时学习可迁移动态。",
    tags: ["World Model", "Human Video", "Cross-Embodiment"],
    classification: { research: "WM", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"], deployment: "Real2Sim2Real" },
    resources: [{ label: "项目页", url: "https://xpeng-robotics.github.io/anyworld/" }],
    motivation: "机器人视频昂贵且本体单一，而直接混合人类视频又会把相机运动和人体外观错误地当成机器人动力学。",
    methodSummary: "AnyWorld 在 WAN Fun-Control 14B 上分别编码动作、Plücker 相机轨迹和本体标签；先用 EgoDex 学人类动态，再用少量人类与机器人视频混合适配目标任务。",
    architecture: "首帧和语言指定场景，动作条件描述手部或末端运动，相机分支显式表示视角变化，本体 token 区分人手与机器人；三个因素在视频生成主干中分别注入。",
    data: "从 20 万条 EgoDex 视频中抽取 3 万条预训练；每个目标域以 5,000 条 EgoDex 和 5,000 条机器人视频混合微调 5,000 步，不要求一一对应。",
    experiments: "比较视频生成质量与动作一致性，并把生成视频用于 UniT VLA 数据增强；仿真使用 RoboCasa 18 项任务，真机使用 IRON 机械臂抓香蕉。",
    novelty: "RoboCasa 平均成功率从 49.8% 提升到 54.6%；真机香蕉抓取 20 次试验从 20% 提升到 55%。",
    strengths: "显式拆分相机、本体和动作条件；下游同时有仿真与真机闭环，而非只报告视频指标。",
    limitations: "真机只覆盖一个抓取任务、20 次试验；14B 视频主干开销高，生成数据对不同任务的收益尚不稳定。",
    transfer: "在人类视频迁移到机器人时，可优先解耦视角运动和本体外观，再检查生成视频是否真的遵循动作，而不是只看画面逼真度。",
    technique: [
      "Plücker 射线编码相机轨迹，本体标签控制执行主体，动作分支单独注入局部运动，使模型不必从像素变化中同时猜测三种因素。",
      "两阶段配方先从 EgoDex 获得动作先验，再用等量人类与机器人视频适配；动作与视觉联合条件对语言 grounding 至关重要。",
    ],
    evaluation: [
      "与 Cosmos-Predict2.5 和 WAN 系基线比较 60 条生成视频，除感知质量外还检查动作条件一致性。",
      "RoboCasa GR1 的 18 项任务从 49.8% 到 54.6%，说明生成视频能带来平均增益，但不同任务收益并不等同。",
      "真机香蕉抓取从 4/20 提升到 11/20；样本量仍不足以推断更广物体、视角或控制器上的泛化。",
    ],
    comparison: "Cosmos-Predict2.5、WAN 视频模型，action-only 与联合条件消融，以及不使用生成数据的 UniT VLA。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页和正文给出 WAN Fun-Control 14B 主干、Plücker 相机条件、预训练/混合微调样本量与步数。"],
    missing: ["未确认完整训练代码与权重开放；真机仅一个任务，生成视频筛选细节不足。"],
    figureFile: "2608.29242-fig2.png",
    figureAlt: "AnyWorld 动作、相机和本体因子化世界模型",
    figureCaption: "Figure 2 · 人类视频预训练、三类条件解耦与目标机器人数据适配。来源：arXiv 原图。",
  },
  {
    title: "SmoothRL: Online Reinforcement Learning During Asynchronous Execution",
    arxivId: "2608.29768",
    url: "https://arxiv.org/abs/2608.29768",
    institutions: ["Astribot Team"],
    signal: "在冻结 π0.5 上训练小型残差 actor/critic，并按真实异步执行边界切分动作块，使在线 RL 不把未执行动作误算进更新。",
    tags: ["Online RL", "Asynchronous Control", "Real Robot"],
    classification: { research: "VLA", training: "RL", data: "在线数据 / 人工纠正", platforms: ["Humanoid", "灵巧手"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://www.astribot.com/research/SmoothRL" }],
    motivation: "通用 VLA 能完成任务但动作常不平滑，直接对异步动作块做 RL 又会把已承诺、实际执行和被丢弃的动作混在同一 credit assignment 中。",
    methodSummary: "SmoothRL 冻结 π0.5，只训练三层残差 actor/critic；critic 读取完整动作块，actor 只对实际执行片段反传，并以操作员给出的稀疏二值结果奖励更新。",
    architecture: "动作块按 committed、executed、discarded 三段记账；残差网络为 3 层、宽度 512，直接在原始动作空间修正基础策略。",
    data: "动态抛掷、笔帽装配和开盒分别使用 500/1,500/1,500 条预训练示范；每项任务以 50 条在线 episode 初始化 replay，并继续采集至 250 条。",
    experiments: "三个 Astribot 真机任务在 150/200/250 条在线 episode 检查点评价，并统计成功率、加速度和 jerk；每任务只训练一个 RL run。",
    novelty: "250 条在线 episode 后，抛掷 39%→94%、笔帽 8%→83%、开盒 30%→90%；抛掷的加速度和 jerk 分别下降 52% 与 47%。",
    strengths: "把异步动作块的 credit assignment 写得清楚；高动态、接触和长时任务均有真机提升与平滑性指标。",
    limitations: "每个任务仅一个 RL 训练 run，检查点评价规模为 10–18 次；二值奖励来自操作员，尚未证明可自动扩展。",
    transfer: "异步 VLA 做在线 RL 时，应记录动作块哪些部分真正执行，并只让 actor 为这些动作负责；平滑性需和成功率同时评估。",
    technique: [
      "critic 使用完整计划动作评估价值，actor 的梯度掩码只覆盖 executed segment，避免被替换或未落地动作污染更新。",
      "残差策略不改动 π0.5 的视觉语言主干，以较少在线数据学习原始动作空间校正；replay 先以 50 条 episode 启动。",
    ],
    evaluation: [
      "三项任务分别在 18、12、10 次评价中检查各 checkpoint，250 条在线轨迹后均显著高于起点。",
      "抛掷任务同时统计成功率、加速度和 jerk，说明收益并非以更激进的动作换取。",
      "论文未报告多随机种子 RL 方差，因而 55–75 点的成功率提升仍需更多独立训练重复确认。",
    ],
    comparison: "冻结 π0.5 起点、不同在线 episode 检查点，以及动作平滑性指标；核心异步分段通过算法设计和组件对照验证。",
    reproducibilityStatus: "部分可复现",
    implementation: ["披露残差网络层数与宽度、示范数量、replay 启动规模、检查点和每次评价 episode 数。"],
    missing: ["未公开完整训练代码、操作员奖励接口和多随机种子结果。"],
    figureFile: "2608.29768-fig3.png",
    figureAlt: "SmoothRL 异步动作块与残差强化学习流程",
    figureCaption: "Figure 3 · committed、executed、discarded 动作分段及 actor/critic 更新。来源：arXiv 原图。",
  },
  {
    title: "DriftingVLA: Native One-Step Vision-Language-Action Generation via Per-Dimension Temporal Drifting",
    arxivId: "2608.29749",
    url: "https://arxiv.org/abs/2608.29749",
    institutions: ["University of Science and Technology of China", "LYNSENSE"],
    signal: "把扩散式动作专家改成直接噪声到动作的分布漂移，并按动作维度分配时间步，在降低推理时延时保留细粒度控制。",
    tags: ["VLA", "Flow Matching", "Latency"],
    classification: { research: "VLA", training: "Post-training", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "VLA 动作专家的多步去噪带来数百毫秒延迟，统一时间调度又忽略平移、旋转和夹爪维度的不同难度。",
    methodSummary: "DriftingVLA 保留 π0.5 的视觉语言主干，新增直接 noise-to-action expert，并用 Per-Dimension Temporal Drifting 为每个动作维度设置独立漂移进度。",
    architecture: "VLM 条件保持不变；动作专家学习从高斯噪声一次跨越到动作分布，PDTD 对各维度的速度场和时间权重分别调度。",
    data: "使用 LIBERO、RoboTwin 和六项 UR5 真机任务的示范数据；真机每项任务 100 条示范，包含两项单臂与四项双臂任务。",
    experiments: "LIBERO 与 RoboTwin 比较 π0.5、SnapFlow 和调度消融；真机每任务 50 次、3 个种子，并测端到端推理时延。",
    novelty: "LIBERO 98.32%、RoboTwin 81.09%；真机平均 77.67%，高于 π0.5 的 74.22%；推理从 227.61 ms 降到 67.67 ms。",
    strengths: "效率、仿真成功率和真机成功率三者同时评价；真机包含双臂任务与三个种子。",
    limitations: "仍依赖 π0.5 主干和同类示范后训练；3.36× 时延提升未包含所有机器人控制链路，跨硬件结论有限。",
    transfer: "若动作维度的动态差异明显，可把统一 flow 时间改成逐维调度，并用端到端时延和真机成功率共同约束优化。",
    technique: [
      "distribution drifting 直接学习噪声分布到动作分布的映射，减少常规 flow matching 的迭代求解。",
      "PDTD 根据不同动作维度分配漂移时间，避免夹爪等离散/突变维度与平滑位姿共享同一速度曲线。",
      "模型以 8 张 A800 训练 50k 步，默认漂移组数 G=8。",
    ],
    evaluation: [
      "PDTD 相比 chunk-wise 调度在 LIBERO/RoboTwin 分别增加 3.04/6.92 点，相比 step-wise 增加 5.22/10.66 点。",
      "六项真机任务共按每任务 50 次、3 个种子评价，DriftingVLA 在五项上最佳，平均提升 3.45 点。",
      "67.67 ms 是模型推理测量，不能直接等同于完整控制回路频率。",
    ],
    comparison: "π0.5、SnapFlow、step-wise/chunk-wise/PDTD 时间调度，以及直接动作专家的组件消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文给出训练步数、8×A800、G=8、真机示范量和三种时间调度设置。"],
    missing: ["未确认代码与权重开放；完整传感、通信和控制链路时延未分项报告。"],
    figureFile: "2608.29749-fig1.png",
    figureAlt: "DriftingVLA 分布漂移动作专家与逐维时间调度",
    figureCaption: "Figure 1 · π0.5 条件主干、直接动作生成与 Per-Dimension Temporal Drifting。来源：arXiv 原图。",
  },
  {
    title: "SMILE: Smooth Motion for Improved Long-Horizon VLA Execution",
    arxivId: "2608.29432",
    url: "https://arxiv.org/abs/2608.29432",
    institutions: ["Stony Brook University", "Salesforce AI Research"],
    signal: "让 VLA 预测少量 B-spline 控制系数而非逐步动作，以连续曲线同时减少输出长度、边界抖动和推理开销。",
    tags: ["VLA", "B-spline", "Smooth Control"],
    classification: { research: "VLA", training: "Post-training", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://jongwoopark7978.github.io/smilevla" }],
    motivation: "离散 action chunk 在块内和块边界都会产生速度不连续；增大 chunk 又增加解码负担和过度平滑风险。",
    methodSummary: "SMILE 用 8 个三次 B-spline 控制点表示整段动作，VLA 只预测系数，执行端按基函数重建连续轨迹。",
    architecture: "视觉语言主干不变，action head 输出每个自由度的 spline 系数；固定 knot 与三次基函数将系数映射成任意长度的平滑动作序列。",
    data: "LIBERO 2,000 条 episode、CALVIN 标准数据，以及 xArm7 上 12 个真机任务共 1,000 条 episode。",
    experiments: "在 Evo1、SmolVLA、VPP 等主干上比较成功率、有效 horizon、延迟、加速度和速度符号变化；真机每项任务 20 次。",
    novelty: "真机普通场景 Evo1 从 26.7% 到 78.3%，拥挤场景从 8.3% 到 56.7%；与 VPP 结合后分别达到 98.3% 和 88.3%。",
    strengths: "动作表示可插到不同 VLA；有 degree/控制点消融，并把轨迹平滑性与任务成功率一起报告。",
    limitations: "固定 horizon 和同步执行对突发接触仍不灵活；过强 spline 约束可能抹去必要的快速动作。",
    transfer: "对连续控制任务，可先减少 action token 数并用可微曲线重建，再以边界加速度和任务成功率选择控制点数量。",
    technique: [
      "每个动作维度写成 a(t)=Σᵢ cᵢBᵢ,₃(t)，模型预测控制系数 cᵢ；K=8、degree=3 在消融中表现最佳。",
      "同一组系数可在执行端密集采样，降低解码长度，同时保证二阶连续性；无需修改视觉语言编码器。",
    ],
    equations: [{ name: "B-spline 动作曲线", expression: "a(t) = Σᵢ cᵢ Bᵢ,₃(t)", explanation: "cᵢ 为模型预测的控制系数，Bᵢ,₃ 为三次 B-spline 基函数。" }],
    evaluation: [
      "LIBERO 上 Evo1 从 92.7% 到 98.0%，SmolVLA 从 74.0% 到 82.6%；后者的有效 horizon 从 1 增至 10。",
      "xArm7 的 12 项任务每项 20 次；普通和拥挤场景都有大幅提升，并与 VPP 形成互补。",
      "匹配 H=10 时，非边界加速度下降 78.6%、速度符号变化下降 42.3%、边界加速度下降 20.5%。",
    ],
    comparison: "原始逐步动作、不同 B-spline 控制点/degree、Evo1、SmolVLA、VPP，以及相同 horizon 的平滑性对照。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页和正文披露 K=8、三次基函数、各数据集 episode 数、12 项真机任务及每项 20 次协议。"],
    missing: ["未确认完整代码与权重开放；异步 action replacement 和强接触任务仍缺少评价。"],
    figureFile: "2608.29432-fig1.png",
    figureAlt: "SMILE 的 B-spline 动作表示与 VLA 接入方式",
    figureCaption: "Figure 1 · 从逐步动作预测切换到少量曲线控制系数。来源：arXiv 原图。",
  },
  {
    title: "Training-Free Action Correction for VLA Model Failures via Language Feedback",
    arxivId: "2608.29967",
    url: "https://arxiv.org/abs/2608.29967",
    institutions: ["Carnegie Mellon University Department of Biomedical Engineering", "Carnegie Mellon University Robotics Institute"],
    signal: "把任务级语言纠错解析成动作维度、方向、幅度和时间窗，在不更新基础策略的情况下对动作块做结构化修正。",
    tags: ["VLA", "Language Correction", "Test-time Adaptation"],
    classification: { research: "VLA", training: "Test-time Adaptation", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://correctvla.github.io" }],
    motivation: "部署中的 VLA 常因相机、基座或物体位置偏差产生系统性执行错误，重新采数微调代价高，而自然语言反馈缺乏稳定的动作接口。",
    methodSummary: "CorrectVLA 将一句纠错转换为结构化 JSON，映射到平移、旋转或夹爪维度，再用三角时间包络把修正量叠加到冻结策略输出。",
    architecture: "语言解析器输出 dimension/direction/magnitude/timing；规则层将离散幅度落入预设数值范围，时间包络避免整段动作突然偏移。",
    data: "使用 LIBERO 的 2,000 次域内 rollout、450 次 OOD rollout，以及 xArm7 基座偏移后的 20 次真机评价；无需新增训练数据。",
    experiments: "先统计 133 个 OOD 任务—模型组合的失败类型，再在 LIBERO 和 xArm7 上测试一次代表性语言纠错能否恢复执行偏差。",
    novelty: "LIBERO 域内从 93.0% 到 96.3%，OOD 成功数从 122/450 到 155/450；xArm7 基座偏移后从 10% 恢复到 95%。",
    strengths: "修正接口透明且不改模型参数；同时给出失败分类、仿真和真机恢复结果。",
    limitations: "主要处理执行层几何偏差，不能解决理解、感知和规划失败；数值范围需预先设定，语言解析依赖外部闭源模型。",
    transfer: "自然语言纠错应先被约束成可审计的低维动作编辑，再设置有限持续时间，而不是把整句反馈直接拼进 VLA prompt。",
    technique: [
      "Claude Sonnet 4.5 将纠错语句解析为结构化字段，数值层把“稍微/明显”等幅度映射到预设范围；VLM 基线使用 GPT-5 mini。",
      "修正量乘三角包络后叠加到冻结 policy 的动作块，使修正平滑进入和退出，不需要梯度更新。",
    ],
    evaluation: [
      "133 个 OOD 任务—模型组合中，执行错误约占 22–23%，低于理解和感知错误；CorrectVLA 只瞄准这一子集。",
      "LIBERO 域内 2,000 次中恢复 65/139 个失败；OOD 450 次中额外恢复 33 个。",
      "真机同位置、异位置、异物体与位置三组分别为 10/10、5/5、4/5，总计 19/20；样本规模和偏差类型仍有限。",
    ],
    comparison: "冻结基础策略、VLM 直接纠错基线、结构化解析与时间包络组件，以及域内/OOD/真机三类设置。",
    reproducibilityStatus: "部分可复现",
    implementation: ["公开结构化字段、幅度范围、时间包络和 LIBERO/真机评价协议；实验使用 RTX 4090。"],
    missing: ["闭源语言解析器会影响可复现性；未覆盖连续多轮纠错和非执行类失败。"],
    figureFile: "2608.29967-fig1.png",
    figureAlt: "CorrectVLA 从自然语言反馈到动作空间校正的流程",
    figureCaption: "Figure 1 · 结构化语言解析、时间包络和冻结 VLA 动作修正。来源：arXiv 原图。",
  },
  {
    title: "AGM: Achievement-Grounded Memory for Closed-Loop Agents with Frozen VLA Policies",
    arxivId: "2608.29537",
    url: "https://arxiv.org/abs/2608.29537",
    institutions: ["Harbin Institute of Technology", "The University of Sydney", "StellarEdge AI"],
    signal: "用可验证的抓取和放置事件维护子任务指针，让冻结 VLA 在计数和重复操作中知道已经完成到哪一步。",
    tags: ["Memory", "Subtask Progress", "Long Horizon"],
    classification: { research: "Memory", training: "Test-time Adaptation", modalities: ["State / Proprioception"], platforms: ["机械臂", "夹爪"] },
    detailAttributes: { memoryImplementation: "基于抓取/放置事件的 achievement-grounded 进度指针", memoryHorizon: "单个长时 episode 内持续维护" },
    motivation: "长时重复任务中的视觉状态常相似，冻结 VLA 容易重复已完成动作；单纯堆叠历史帧又无法确认一次子任务是否真的完成。",
    methodSummary: "AGM 预先生成有类型的子目标序列，以夹爪负载、点轨迹和跨视角视觉验证器确认完成事件，并据此推进、保持或回滚指针。",
    architecture: "抓取由夹爪状态机和 CoTracker3 检测一致抬升；放置由冻结 SigLIP 特征和 2.43M 参数分类头验证；进度指针选择下一条语言子目标。",
    data: "放置验证器使用 788 个事件，训练/测试仿真 seed 隔离；RoboMME 使用计数任务，真机 PickXTimes 与 BinFill 分别覆盖 N=1–5。",
    experiments: "RoboMME 每任务 50 条 episode、2 次运行；真机每个 N 做 10 次，共 50 次/任务，并消融视觉验证器和阈值。",
    novelty: "RoboMME 平均 55.96%，高于 MemER 48.83% 和冻结策略 28.78%；真机 PickXTimes 100%，BinFill 总体 82%。",
    strengths: "记忆更新由物理事件触发而非语言自报；冻结大模型，只训练小验证器，并包含真机多次重复任务。",
    limitations: "事件词表围绕夹爪交互，扩展到工具、灵巧手或不可见状态需重新设计；真机任务类型较窄。",
    transfer: "Memory 模块可先维护经传感器验证的 achievement pointer，只有在完成事件成立时才推进子任务。",
    technique: [
      "静态子目标序列把“抓 N 次/放 N 次”展开；每步执行后，有限状态机决定指针 advance、retain 或 rollback。",
      "CoTracker3 用多个点的一致抬升识别抓取；放置验证器读取冻结 SigLIP 的跨视角特征，分类头为 4626→512→128→2。",
      "验证器用 AdamW、学习率 1e-3、权重衰减 1e-4、dropout 0.3、300 个 full-batch epoch；仅 2.43M 参数可训练。",
    ],
    evaluation: [
      "RoboMME Counting 每任务 50 条 episode、两次运行；AGM 在 PickXTimes 和 BinFill 上分别达到 100% 和 84%。",
      "真机 PickXTimes 在 N=1–5 均为 10/10；BinFill 随 N 增大下降，N=5 为 6/10，暴露长链误差累积。",
      "仅本体状态版本为 98%/78%，加入视觉放置验证后为 100%/84%；阈值压平也会降低 BinFill。",
    ],
    comparison: "冻结策略、MemER、本体状态 FSM、视觉验证器、不同阈值与完整 AGM。",
    reproducibilityStatus: "部分可复现",
    implementation: ["披露 CoTracker3/SigLIP 参数规模、分类头结构、优化器超参、数据量和真机重复次数。"],
    missing: ["未确认代码公开；事件词表和阈值对新硬件的迁移成本尚未量化。"],
    figureFile: "2608.29537-fig1.png",
    figureAlt: "AGM 长时操作的子任务序列、事件验证和进度记忆",
    figureCaption: "Figure 1 · 冻结 VLA、achievement verifier 与可回滚进度指针。来源：arXiv 原 PDF 图。",
  },
  {
    title: "Aero Hand Open: A Simulation-Ready Tendon-Driven Hand for Dexterous Manipulation Learning",
    arxivId: "2608.28578",
    url: "https://arxiv.org/abs/2608.28578",
    institutions: ["Chestnut Robotics", "California Institute of Technology"],
    signal: "提供 16 关节、7 电机的开源腱驱灵巧手，并用可辨识 MuJoCo 模型完成无微调的在手旋转 sim-to-real。",
    tags: ["Dexterous Hand", "Open Hardware", "Sim2Real"],
    classification: { research: "其他", training: "RL", modalities: ["State / Proprioception"], platforms: ["灵巧手"], deployment: "Sim2Real" },
    resources: [{ label: "项目页", url: "https://tetheria.github.io/aero-hand-open/" }],
    motivation: "灵巧手研究常被昂贵硬件、封闭设计和不准确仿真模型限制，难以比较算法或复现 sim-to-real。",
    methodSummary: "Aero Hand Open 以腱差动和 3D 打印结构实现 16 关节/7 电机，通过实测拟合驱动映射和拇指耦合，提供 MuJoCo/Brax 训练与部署链路。",
    architecture: "硬件重 374 g、物料成本约 314 美元；仿真含 16 个铰链、20 条空间腱和 7 个执行器，控制策略为纯本体状态 MLP PPO。",
    data: "动力学与驱动参数来自硬件标定；PPO 在 8,192 个 Brax 环境训练 3e8 步，无真机示范和真机微调。",
    experiments: "验证 33 类 GRASP 抓型、40 万次以上耐久循环、约 12 N 指尖力、仿真—硬件轨迹误差和零样本在手旋转。",
    novelty: "仿真 15 秒旋转 7.64 rad；同一策略以 20 Hz 直接部署，真机约 55 秒完成一周旋转，无状态估计或微调。",
    strengths: "硬件、仿真、训练和部署链路均以复现为中心；除任务演示外还给出耐久、力和几何误差。",
    limitations: "零样本旋转速度明显低于仿真；拇指模型误差较大，策略只验证单一物体与纯本体输入。",
    transfer: "在做灵巧手 RL 前先标定 tendon-to-joint 映射和仿真残差，可比单纯扩大域随机化更直接地提高零样本落地概率。",
    technique: [
      "腱差动减少电机数量，同时保留 16 个关节；MuJoCo 模型显式表示空间腱和三向拇指耦合。",
      "PPO actor/critic MLP 为 512/256/128，学习率 3e-4、γ=0.97、entropy 1e-2、unroll 40、clip 0.3。",
    ],
    evaluation: [
      "指尖轨迹的仿真—硬件 RMS 残差约 0.29–0.45 mm，但作者同时指出拇指耦合仍是主要误差源。",
      "真机不使用视觉、外部状态估计或微调，证明模型足以支撑基础零样本迁移；速度差距说明 dynamics gap 仍明显。",
      "40 万次以上循环和 33 类抓型更接近平台能力验证，不能替代多任务策略泛化实验。",
    ],
    comparison: "实测与 MuJoCo 指尖轨迹、仿真与真机旋转速度，以及开源灵巧手的关节、电机、重量和成本指标。",
    reproducibilityStatus: "资源较完整",
    implementation: ["项目页提供机械设计、MuJoCo 模型、Brax/PPO 训练与部署入口；正文给出网络和主要超参。"],
    missing: ["单物体旋转之外的策略评测不足；长期腱松弛、维护频率和多手一致性仍待验证。"],
    figureFile: "2608.28578-fig3.png",
    figureAlt: "Aero Hand Open 硬件、仿真和强化学习部署链路",
    figureCaption: "Figure 3 · 开源灵巧手平台与 sim-to-real 训练栈。来源：arXiv 原 PDF 图。",
  },
  {
    title: "ChainSplat: A Physics-Inspired Screw-Theoretic Model for Learning Deformable Linear Object Dynamics from Multi-View RGB Videos",
    arxivId: "2608.28570",
    url: "https://arxiv.org/abs/2608.28570",
    institutions: ["KTH Royal Institute of Technology"],
    signal: "把绳线类物体写成开放运动链，并将 Gaussian 按链节绑定，让多视角 RGB 同时支持几何重建、动力学辨识和目标击打。",
    tags: ["Deformable Object", "Gaussian Splatting", "System Identification"],
    classification: { research: "WM", training: "Post-training", modalities: ["Point Cloud / 3D"], platforms: ["机械臂", "夹爪"], deployment: "Real2Sim" },
    resources: [{ label: "项目页", url: "https://chainsplat.github.io" }],
    motivation: "可变形线性物体的像素模型难以提供可控状态，有限元或粒子模型又需要昂贵标定，难以从普通视频快速构建。",
    methodSummary: "ChainSplat 用刚性链节、转动螺旋轴和链节局部 Gaussian 表示 DLO；先做可微运动学几何识别，再做动力学参数辨识。",
    architecture: "多视角 RGB 优化链节长度、关节轴和 Gaussian 外观；辨识后的链模型在 MuJoCo 中滚动，视觉状态估计把实物形状反投到链坐标。",
    data: "三条 20/30/40 cm DLO 的多视角交互视频，覆盖桌面和自由空间；训练为对象级，不依赖大规模数据集。",
    experiments: "与 PGND、PhysTwin 比较训练和推理效率、几何/动力学预测；随后用机械臂完成目标击打，每条 DLO、每种场景 3 次。",
    novelty: "训练约 17.6 分钟，基线为 27–332 分钟；单次总推理 2.41 秒，基线为 4.31–8.44 秒；目标击打平均误差低于 1 cm。",
    strengths: "表示兼顾可视化和可控制状态；真实 DLO 上有系统辨识消融和闭环前的任务验证。",
    limitations: "每个对象仍需交互视频和单独优化；状态估计仅 2–3 Hz，控制实验为开环，尚不足以处理高速扰动。",
    transfer: "对绳、线缆等结构明确的物体，可先把几何先验写进可微表示，再让 Gaussian 负责外观，而不是从像素直接学习任意形变。",
    technique: [
      "开放运动链用局部刚性链节和 revolute screw axis 约束形变；每个 Gaussian 绑定链节坐标，渲染时随前向运动学变换。",
      "两阶段优化先识别几何与关节，再拟合动力学参数，避免外观、几何和材料参数在同一目标中互相补偿。",
    ],
    evaluation: [
      "A100 上对象级训练 17.6 分钟，明显快于对照；4090 上状态估计 2–3 Hz、RGB 渲染 5–6 Hz。",
      "动力学辨识消融会显著增加轨迹误差，表明几何重建本身不足以支持交互预测。",
      "每种 DLO/场景仅 3 次目标击打，虽然平均误差低于 1 cm，但无法衡量复杂接触和在线扰动鲁棒性。",
    ],
    comparison: "PGND、PhysTwin、去除动力学辨识的模型，以及三种长度 DLO 在桌面/自由空间的目标击打。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页和正文给出链式表示、两阶段优化、硬件、运行速度与任务协议。"],
    missing: ["未确认完整代码开放；对象级优化、低频状态估计和开环控制限制在线复现。"],
    figureFile: "2608.28570-fig4.png",
    figureAlt: "ChainSplat 链式运动学、Gaussian 表示和动力学辨识组件",
    figureCaption: "Figure 4 · 运动链参数化、链节 Gaussian 与两阶段辨识。来源：arXiv 原图。",
  },
  {
    title: "DeicticVLA: Unifying Instruction Modes Based on Language and Deictic Gestures in a Single VLA",
    arxivId: "2608.28108",
    url: "https://arxiv.org/abs/2608.28108",
    institutions: ["The University of Osaka", "The University of Tokyo"],
    signal: "把“这个/那里”等指示信息变成图像 mask 或视觉标记，让 VLA 在语言无法唯一指代物体时获得显式空间 grounding。",
    tags: ["VLA", "Deictic Prompt", "Segmentation"],
    classification: { research: "VLA", training: "Post-training", modalities: ["Mask / Segmentation"], platforms: ["机械臂", "夹爪"] },
    motivation: "自然语言在多个相似物体或空间关系中常有歧义；仅把点击位置写成坐标文本不能充分利用预训练视觉特征。",
    methodSummary: "DeicticVLA 用 SAM2 将用户指示转成 mask，并比较边框、淡化、早/晚 mask prompt 等编码；先训练语言任务，再联合训练指示任务。",
    architecture: "指示位置可作为 visual prompt 或 mask prompt 注入 π0；两阶段训练先保留语言操作能力，再学习跨模态指示 grounding。",
    data: "仿真包含 10 个 Object、9 个 Spatial、6 个 Goal 任务，每任务 50 条示范；另在 UR5e+Robotiq 上做三项真机任务。",
    experiments: "比较 LI/VLI/VI 三种提示、四种视觉编码和一阶段/两阶段训练，重点测试未见物体类别和空间关系。",
    novelty: "仿真域内平均 94.1–95.6%；Object-ZS 中 mask 方法比语言提示高 27.8–29.2 点，Spatial-ZS 高 11.1–16.0 点；真机未见类别 VLI/VI 为 100%，LI 为 16.7%。",
    strengths: "把指示 grounding 单独设计并做编码/训练顺序消融；零样本类别与真机结果支持实际交互价值。",
    limitations: "仿真使用真值 mask，真机规模较小；SAM2 分割错误和用户点击误差会直接传到控制。",
    transfer: "若任务语言本身难以唯一指代目标，可以用 mask 作为视觉条件，并先保护原有语言策略再学习新交互接口。",
    technique: [
      "VP-BBox/VP-Fade 直接改写输入图像，MP-Early/MP-Late 在特征层注入 mask；后者更少破坏原始视觉内容。",
      "两阶段训练前 30k 步只用 LI，后 30k 步混合全部模式；batch 32、AdamW 学习率 2.5e-5 衰减到 2.5e-6、2 张 A100。",
    ],
    evaluation: [
      "域内结果接近饱和，VP-BBox 平均 95.6%；关键差异来自未见类别与未见空间关系。",
      "一阶段联合训练在零样本指示上的增益明显变小；第二阶段去掉 LI 会让语言能力下降 21.9–28.4 点。",
      "真机三项任务支持指示输入，但论文公开材料不足以支撑更广场景和用户误差下的鲁棒性判断。",
    ],
    comparison: "语言提示 LI、视觉+语言 VLI、纯视觉 VI，四种 mask/视觉编码，一阶段与两阶段训练。",
    reproducibilityStatus: "部分可复现",
    implementation: ["披露任务数、每任务示范量、训练步数、batch、学习率、GPU 和 SAM2 指示生成流程。"],
    missing: ["未确认代码与权重开放；真机总试验数和人工指示误差分布需进一步核对。"],
    figureFile: "2608.28108-fig1.png",
    figureAlt: "DeicticVLA 的点击、分割和指示条件策略流程",
    figureCaption: "Figure 1 · 指示输入、SAM2 mask、视觉提示编码与两阶段 VLA 训练。来源：arXiv 原图。",
  },
  {
    title: "RoboPhys-3D: A Comprehensive Embodied World Model Evaluation via 3D Reconstruction",
    arxivId: "2608.28718",
    url: "https://arxiv.org/abs/2608.28718",
    institutions: ["The University of Texas at Austin", "Purdue University", "Futurewei Technologies"],
    signal: "用多视角 3D 重建和物理分层指标检查机器人世界模型的几何与动力学，而不是只用视频感知质量打分。",
    tags: ["World Model", "3D Benchmark", "Physics Evaluation"],
    classification: { research: "WM", modalities: ["Point Cloud / 3D"], data: "合成 / 仿真数据", platforms: ["机械臂", "夹爪"] },
    motivation: "FVD 等视频指标不能区分视觉逼真和物理正确，也难以定位机器人、物体、接触和长时动力学中的具体错误。",
    methodSummary: "RoboPhys-3D 从 RoboTwin2 生成多视角真值视频，使用四种 3D 重建方法恢复动态场景，再以 50 个指标、18 个子维度组成 RoboPhyscore。",
    architecture: "评测管线把视频世界模型输出重建为 3D/4D 表示，逐层检查外观、几何、运动、接触和任务状态；分数再与人类判断和下游任务关联。",
    data: "50 个 RoboTwin2 任务×100 条 episode×5 个视角，共 25,000 条真值视频；场景文本由 Qwen3-VL 辅助标注。",
    experiments: "评估 Wan、CogVideoX、Cosmos、RoboDreamer，以及 VGGT、VGGT-Omega、4DGS、4C4D 重建；另做逆动力学、规划和数据引擎下游实验。",
    novelty: "Cosmos RoboPhyscore 0.633，为真值的 92.7%；VGGT-Omega 保留 96.1% 物理分数；指标与人类 Pearson/Spearman 相关为 0.9761/0.8962。",
    strengths: "评测维度细、含人类一致性和三类下游任务；可区分生成模型错误与 3D 重建损失。",
    limitations: "数据来自单一仿真平台和有限本体；没有真实传感器/接触噪声，不能替代真机世界模型评价。",
    transfer: "评估 action-conditioned 视频模型时，可将物理误差拆成可定位的 3D 子指标，并验证这些指标是否预测策略或规划收益。",
    technique: [
      "四级物理评测从场景外观逐步进入对象几何、时序动力学和交互结果，50 个指标汇总成统一 RoboPhyscore。",
      "重建保持率把世界模型误差和 3D 后处理误差分开；下游逆动力学、规划、数据生成测试分数是否具有任务意义。",
    ],
    evaluation: [
      "Cosmos 得分 0.633，Wan 0.5359，RoboDreamer 0.3492，CogVideoX 0.3363；双臂目标类仍是最难子集。",
      "VGGT-Omega/VGGT/4C4D/4DGS 的物理保持率为 96.1%/94.7%/85.4%/78.2%，说明重建器选择会改变结论。",
      "70 名标注者给出较高相关性；DreamGen 逆动力学 MAE 0.0112，并在规划和数据引擎评价中优于 MIDM。",
    ],
    comparison: "四种视频世界模型、四种 3D/4D 重建方法、50 项物理指标与人类判断，以及三个下游任务。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文披露任务、episode、视角、模型、重建器、50 个指标和人类评价规模。"],
    missing: ["未覆盖真实相机、接触传感与 sim-to-real；完整 benchmark 代码和数据开放状态需以项目发布为准。"],
    figureFile: "2608.28718-fig1.png",
    figureAlt: "RoboPhys-3D 多视角世界模型和分层物理评测框架",
    figureCaption: "Figure 1 · 从视频预测、3D 重建到物理分层指标和下游验证。来源：arXiv 原图。",
  },
  {
    title: "DREAM: Deployment-Time Demonstration Generation via Real-to-Sim for Scalable Policy Adaptation",
    arxivId: "2608.29078",
    url: "https://arxiv.org/abs/2608.29078",
    institutions: ["The University of Tokyo"],
    signal: "从少量实拍构建可执行数字副本，用 TAMP 生成种子轨迹、MimicGen 扩增并回到真机训练 VLA。",
    tags: ["Real2Sim2Real", "Synthetic Data", "VLA"],
    classification: { research: "VLA", training: "Post-training", data: "合成 / 仿真数据", platforms: ["机械臂", "夹爪"], deployment: "Real2Sim2Real" },
    motivation: "真机遥操作数据昂贵，而通用仿真资产与真实场景存在外观、几何和任务定义差异，难以直接生成可用策略数据。",
    methodSummary: "DREAM 用 COLMAP/gsplat 和 TRELLIS/SAM3 构建度量场景，LLM 生成类型化目标，再由 cuTAMP+GraspGen 和 MimicGen 产生通过物理过滤的 LeRobot 轨迹。",
    architecture: "真实视频进入数字副本重建；TAMP 求可执行子任务与抓取；轨迹经 MimicGen 扩增、碰撞/任务过滤后训练 SmolVLA 或 π0.5。",
    data: "xArm7 上 BlockIntoBowl 与 FruitPacking 两项任务；分别比较 10/50/100 条遥操作数据和 100/500/1,000 条 DREAM 数据。",
    experiments: "每个 policy/任务真机 15 次；比较仿真—真机相关性、数据量扩展、固定建模成本和不同 VLA 主干。",
    novelty: "π0.5 在 BlockIntoBowl 上 DREAM-1000 为 93.3%、teleop-100 为 86.7%；FruitPacking 分别 86.7% 和 80.0%。",
    strengths: "把构建成本、轨迹接受率、仿真—真机相关性和真实成功率连成完整闭环；并非只展示合成画面。",
    limitations: "仅静态刚体桌面场景；同样样本数下合成轨迹信息密度较低，SmolVLA 在 FruitPacking 上仍明显弱于遥操作。",
    transfer: "做 Real2Sim2Real 数据工厂时，应单独统计建模固定成本、规划成功率、轨迹接受率和最终真机收益。",
    technique: [
      "COLMAP/gsplat 恢复场景尺度与外观，TRELLIS/SAM3 生成可交互对象；类型化目标和 rubric 约束 LLM 输出。",
      "cuTAMP+GraspGen 产生种子计划，MimicGen 扩增后以物理约束过滤，最终导出标准 LeRobot 数据。",
    ],
    evaluation: [
      "仿真与真机成功率 Pearson r=0.98/0.99，仿真通常低估真机 7–14 点，说明数字副本可用于相对筛选。",
      "BlockIntoBowl 中 π0.5/SmolVLA 的 DREAM-1000 为 93.3%/80.0%；FruitPacking 为 86.7%/6.7%，后者暴露小模型对合成分布的敏感性。",
      "数字副本固定成本约 36/95 分钟，超过约 73/168 条示范后比遥操作更省时；TAMP 成功率 100%/62%，扩增接受率约 33%。",
    ],
    comparison: "不同数量的遥操作与 DREAM 数据、SmolVLA 与 π0.5、仿真与真机成功率，以及建模/规划/扩增成本。",
    reproducibilityStatus: "部分可复现",
    implementation: ["披露重建、规划、扩增和 LeRobot 导出组件，并给出每任务真机 15 次、时间成本和接受率。"],
    missing: ["未确认完整场景与代码开放；软体、铰接物体、动态障碍和更多任务尚未评价。"],
    figureFile: "2608.29078-fig2.png",
    figureAlt: "DREAM 从实拍数字副本到合成轨迹和真机策略的完整管线",
    figureCaption: "Figure 2 · Real2Sim 场景重建、TAMP/MimicGen 数据生成与 Sim2Real 策略训练。来源：arXiv 原图。",
  },
  {
    title: "AdaVLA: Adaptive Step Flow Matching for Training-free Acceleration of Vision-Language-Action Models",
    arxivId: "2608.29208",
    url: "https://arxiv.org/abs/2608.29208",
    institutions: ["Sogang University"],
    signal: "运行时根据动作轨迹曲率决定直接跳步或补一步，并按参与率裁剪 VLM 的低重要性 MLP 通道，无需重新训练。",
    tags: ["VLA", "Training-Free", "Edge Deployment"],
    classification: { research: "VLA", training: "Test-time Adaptation", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "固定 flow 求解步数和均匀通道剪枝忽略样本难度与层间冗余，在边缘设备上要么慢，要么损失动作质量。",
    methodSummary: "AdaVLA 用中间动作点估计曲率：低曲率直接跳到终点，高曲率增加一次修正；再用 participation ratio 估计各层重要性并动态重排/裁剪 MLP 通道。",
    architecture: "动作专家只改推理积分路径；VLM 主干保持冻结，在一次初始前向中统计激活/权重重要性，后续按层分配剪枝率。",
    data: "LIBERO 上评估 π0.5 与 X-VLA；真机使用 SO-ARM101、SmolVLA，每项任务 50 条示范，四项任务各评价 30 次。",
    experiments: "A10 测成功率，Jetson 测端到端延迟和能耗；比较 SVD/participation ratio、不同曲率阈值、步数和无自适应版本。",
    novelty: "Jetson 上 π0.5 从 958.54 ms 降至 513.35 ms，成功率 98.65%→99.45%；X-VLA 从 387.52 ms 降至 173.09 ms，能耗下降 3.06×。",
    strengths: "无需训练；成功率、延迟、TTFA、能耗和真机结果均有对照，适合部署取舍。",
    limitations: "加速来自特定硬件和实现；曲率阈值仍需设定，LIBERO 高成功率接近饱和，复杂接触任务中的风险不明确。",
    transfer: "部署加速应按样本轨迹曲率和层重要性自适应分配计算，而不是对所有动作和层使用同一压缩率。",
    technique: [
      "低曲率时从当前点直接跳至最终动作，高曲率时在中点增加一次求解；阈值控制精度—延迟折中。",
      "participation ratio 比全量 SVD 更便宜地估计层内有效维度，再据此重排和裁剪 MLP 激活与权重。",
    ],
    evaluation: [
      "π0.5 在 Jetson 上 1.87× 加速、能耗 19.83→13.17 J；X-VLA 2.24× 加速、能耗 10.73→3.51 J。",
      "SVD 版本成功率 99.65% 但延迟 894.78 ms、能耗 23.6 J；participation ratio 为 513.35 ms/13.17 J。",
      "SO-ARM101 四项真机任务共 120 次，平均成功率 87.5%→90.0%，延迟 806.73→488.49 ms。",
    ],
    comparison: "原始 π0.5/X-VLA/SmolVLA、SVD 与 participation ratio、不同曲率阈值、固定一步和无自适应推理。",
    reproducibilityStatus: "部分可复现",
    implementation: ["披露曲率阈值消融、A10/Jetson 测试、SO-ARM101 数据量与每任务 30 次协议。"],
    missing: ["未确认代码公开；硬件内核优化、功耗测量方法和复杂动态任务仍需复现。"],
    figureFile: "2608.29208-fig2.png",
    figureAlt: "AdaVLA 的曲率自适应求解和 VLM 通道剪枝",
    figureCaption: "Figure 2 · 动作专家自适应步进与 importance-based MLP 通道裁剪。来源：arXiv 原图。",
  },
  {
    title: "Blind Dexterity: Whole-Body Humanoid Manipulation via Pure Proprioception",
    arxivId: "2608.29487",
    url: "https://arxiv.org/abs/2608.29487",
    institutions: ["TU Darmstadt IAS", "hessian.AI", "DFKI", "Tongji University", "Robotics Institute Germany"],
    signal: "仅靠关节、本体和接触反馈，让 Unitree G1 完成足球、滑板和行李箱等全身操作，用动作本身主动探测物体状态。",
    tags: ["Humanoid", "Proprioception", "Sim2Real"],
    classification: { research: "其他", training: "RL", modalities: ["State / Proprioception"], platforms: ["Humanoid", "灵巧手"], deployment: "Sim2Real" },
    resources: [{ label: "项目页", url: "https://aditya.bhatts.org/BlindDexterity/" }],
    motivation: "Humanoid 操作高度依赖视觉和外部定位；遮挡、标定漂移或弱光会直接破坏策略，且外感知并非所有接触阶段都必要。",
    methodSummary: "Blind Dexterity 训练纯本体 PPO 策略，以历史关节和接触信息完成行走、足球、滑板和行李箱；碰触与搜索动作同时承担状态估计。",
    architecture: "actor/critic 为 1024/512/256 ELU MLP；诊断用状态估计器为 256/256/256/128，但不向策略提供外部视觉。",
    data: "4096 个并行仿真环境，任务训练 5k/6k/8k iteration；仿真定量每项 4096 episode、5 个种子，真实 Unitree G1 做定性部署。",
    experiments: "四类全身任务检查无外感知控制、状态可观测性和 sim-to-real；足球接触定位误差、行李箱/滑板种子敏感性均单独分析。",
    novelty: "球体接触后位置估计误差低于 2 cm；行李箱最佳种子成功率 90.3%，滑板 privileged 版本均值 28.1±39.1%、最佳 95.9%。",
    strengths: "展示触碰本身可以形成主动感知；任务覆盖腿、手和全身协调，并直接报告高方差失败。",
    limitations: "真机主要是定性演示，缺少重复次数和统计；没有物体类别泛化，部分任务仍保留机载 IMU。",
    transfer: "在视觉不可用或接触遮挡阶段，可把安全探索动作设计成可观测性来源，但应把真机成功统计与演示视频分开报告。",
    technique: [
      "PPO 策略读取本体历史和接触反馈，不使用相机、外部 marker 或力/触觉阵列；触碰桌面、箱体或球体后更新隐式状态。",
      "训练使用 rollout 24、epochs 5、minibatch 4、γ=0.99、λ=0.95、clip=0.2、entropy=0.001、学习率 3e-4。",
    ],
    evaluation: [
      "仿真定量使用 4096 条 episode 和 5 个种子，足球接触可把球位置定位到 2 cm 内。",
      "行李箱任务最佳种子 90.3%；滑板即使有 privileged 信息也呈现 28.1±39.1% 的大方差，说明策略稳定性不足。",
      "真机图示证明能够迁移，但论文没有给出可用于置信区间的真机成功次数，不能据演示推断稳定成功率。",
    ],
    comparison: "纯本体与 privileged 状态、不同随机种子、诊断状态估计器，以及四种全身任务的 sim-to-real 表现。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页与正文给出网络、PPO 超参、并行环境数、训练迭代和仿真评价规模。"],
    missing: ["真机试验次数和统计未给出；训练代码、资产和全部权重的开放状态需确认。"],
    figureFile: "2608.29487-fig5.png",
    figureAlt: "Blind Dexterity 通过接触桌面和箱体定位把手的动作序列",
    figureCaption: "Figure 5 · 行李箱任务中以桌面/侧面接触和把手搜索形成主动本体感知。来源：arXiv 原图。",
  },
  {
    title: "Contact-Guided Exploration for Non-Prehensile Locomanipulation with Multi-Critic RL",
    arxivId: "2608.28140",
    url: "https://arxiv.org/abs/2608.28140",
    institutions: ["University of Pisa", "ETH Zurich", "NVIDIA"],
    signal: "从候选抓取接触中构造独立探索奖励和 critic，让全身移动操作策略先学会建立有效接触，再优化任务完成。",
    tags: ["Reinforcement Learning", "Contact Exploration", "Mobile Manipulation"],
    classification: { research: "其他", training: "RL", modalities: ["State / Proprioception"], platforms: ["机械臂", "其他平台"], deployment: "Sim2Real" },
    resources: [{ label: "项目页", url: "https://tolomeis.github.io/contact-guided-exp/" }],
    motivation: "全身移动操作的稀疏任务奖励很难探索到抓取接触，单一 critic 又会混淆“靠近可抓位置”和“最终完成任务”。",
    methodSummary: "方法从抓取算法产生 25 个候选接触，单独训练 exploration critic，并与 task、regularization critic 按计划权重组合。",
    architecture: "高层策略为 LSTM-256 加 256/128/64 MLP，调用预训练 locomotion；三 critic 分别处理任务、接触探索和动作正则。",
    data: "IsaacLab 4096 环境，使用 15 把 IKEA 椅子和 100 把程序化椅子，并随机化质量、摩擦等参数；真机测试 4 个未见 IKEA 物体。",
    experiments: "仿真 5 个种子，比较无探索、稠密接触和多 critic 权重调度；真机在 ALMA 四足移动操作平台做 58 次试验。",
    novelty: "无探索奖励为 0%，完整方法仿真成功率 94.1%、倾倒率 4.4%、完成时间 9.2 s；真机未见物体为 40/58=69%。",
    strengths: "探索目标来自可执行接触而非任意状态覆盖；有多种子消融和未见物体真机测试。",
    limitations: "真机依赖外部 motion capture；仿真 94.1% 到真机 69% 有明显落差，权重日程针对椅子任务调节。",
    transfer: "稀疏接触任务可把“建立可执行接触”设成独立价值函数，再逐步把权重交还给任务目标。",
    technique: [
      "抓取模块提供 25 个接触候选，探索奖励衡量末端接近这些接触的进展；独立 critic 避免它压过任务回报。",
      "探索权重从 0.1 衰减到 0.01，正则权重在 5k–10k iteration 从 0.15 升至 0.24，task 权重保持 0.75。",
      "仿真时间步 0.005 s、控制周期 0.02 s；预训练 locomotion 负责低层全身稳定。",
    ],
    evaluation: [
      "5 个种子下，无接触探索策略为 0%，完整方法达到 94.1%，证明难点首先是探索到可用接触。",
      "真机在 4 个未见 IKEA 对象上 40/58 成功，并搬运最高 6.5 kg 负载；外部 motion capture 降低了感知难度。",
      "对洗碗机等关节任务，方法使靠近 joint limit 的时间比例下降 59%，表明接触引导不只提升最终成功率。",
    ],
    comparison: "无探索、单 critic/多 critic、权重调度和接触候选消融，以及 15+100 把仿真椅子到 4 个未见真机物体。",
    reproducibilityStatus: "部分可复现",
    implementation: ["公开 4096 环境、控制频率、网络、25 个接触候选、权重日程和 5 种子/58 次真机协议。"],
    missing: ["未确认训练代码和资产开放；真机依赖 motion capture，机载感知条件尚未验证。"],
    figureFile: "2608.28140-fig2.png",
    figureAlt: "Contact-Guided Exploration 的多 critic 全身移动操作架构",
    figureCaption: "Figure 2 · 接触候选、探索/任务/正则 critic 与预训练 locomotion。来源：arXiv 原图。",
  },
];

export const paperDaily20260831: Paper[] = entries.map(makePaper);
