import type { Paper } from "./site-data";

export const paperDaily20260713: Paper[] = [
  {
    rank: 1,
    title: "VINE: Taming Generative Control Policies for Reinforcement Learning",
    arxivId: "2607.10369",
    url: "https://arxiv.org/abs/2607.10369",
    institutions: ["AgiBot", "HKUST", "Peking University"],
    signal: "用可反传的流策略采样器把生成式行为策略接入在线 RL，并在真机插接中减少交互成本",
    tags: ["Generative Policy", "Online RL", "Flow Matching"],
    classification: { research: "VLA", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://agibottech.github.io/vine" }],
    motivation: "生成式行为策略能覆盖多峰动作分布，但常用采样过程不便于把价值梯度稳定地传回策略，限制了从模仿学习继续做在线强化学习。",
    methodSummary: "VINE 在每个去噪步重建插值状态，并对整条生成轨迹做 BPTT；价值梯度由此可以直接修正流策略，同时保留行为克隆初始化的动作先验。",
    architecture: "条件流策略接收机器人状态与任务条件，经过 10 个去噪步生成动作；价值网络对生成动作评估，策略更新沿采样轨迹反传。",
    optimization: "以行为克隆策略初始化，再进行 actor-critic 式在线 RL；策略侧对采样过程做 BPTT，价值侧使用真实 rollout 更新。",
    data: "仿真使用 OGBench 40 个任务；真机为插头—插座插接，通过自主 rollout 与少量人工干预收集在线数据。",
    experiments: "OGBench 以 12 个随机种子报告 95% bootstrap 置信区间，综合分约 60；真机 20 次测试全部成功，训练约 20 分钟，人工干预占 19.2%。",
    novelty: "相比把生成策略当作不可导采样器或只在最终动作上做价值引导，VINE 让梯度穿过完整去噪轨迹；相同真机任务中达到 20/20，Hil-SERL 为 16/20，EXPO 为 19/20但耗时约 50 分钟。",
    strengths: "仿真规模、随机种子、真机对照、训练时间和人工干预量均有量化，证据链较完整。",
    limitations: "真机只验证单一插接任务；对价值误差和长去噪链梯度稳定性的依赖仍在。",
    transfer: "适合把已训练的 flow/diffusion VLA 继续做在线强化学习，尤其用于需要少量交互快速纠正的接触任务。",
    experimentDetails: [{ title: "仿真与真机在线强化学习", setup: "OGBench 40 个任务、12 个随机种子并报告 95% bootstrap CI；真机插头插座任务测试 20 次，同时记录训练时间与人工干预比例。", comparisons: "QAM 等生成策略 RL 基线，以及 BC 初始化、Hil-SERL、EXPO、SAC-Flow。", results: ["OGBench 综合分约 60，对照 QAM 约 55。", "真机 VINE 为 20/20；BC 初始化 10/20、Hil-SERL 16/20、EXPO 19/20、SAC-Flow 12/20。", "VINE 训练约 20 分钟、人工干预 19.2%；EXPO 约 50 分钟、人工干预 74.6%。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["10 步流采样；每步重建插值状态；价值梯度沿完整采样器 BPTT；12 seeds 与 bootstrap CI。"], verifiedResources: ["项目页提供论文与实验视频。"], missing: ["完整训练代码、真机数据和全部超参数尚未确认公开。"] },
    deepDive: { lead: "VINE 把生成策略的采样轨迹变成可优化的计算图。", sections: [{ title: "可微生成式策略", paragraphs: ["普通 flow policy 从噪声逐步积分到动作。VINE 在第 k 步先用当前速度预测动作，再重建对应插值状态，下一步从这一状态继续，因此动作价值的梯度可以跨越所有去噪步。", "这种做法没有另起一个离散策略头，而是直接更新原生成分布；行为克隆初始化仍负责约束动作落在可执行区域。"] }], equations: [{ name: "VINE 采样递推", expression: "x̂ₖ = tₖ âₖ + (1−tₖ)zₖ；âₖ₊₁ = x̂ₖ + (1−tₖ)vθ(x̂ₖ,tₖ;s)", explanation: "每一步重建插值点 x̂ₖ，再由条件速度场 vθ 推进动作估计 â；整条递推保留梯度。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-13/2607.10369-overview.png", alt: "VINE 与普通行为流策略和 BPTT 价值优化的路径对比", caption: "Figure 1 · VINE 通过可微流采样把价值梯度传回生成策略。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 2,
    title: "Causally Debiased Latent Action Model for Embodied Action Conditioned World Models",
    arxivId: "2607.09185",
    url: "https://arxiv.org/abs/2607.09185",
    institutions: ["Aether AI", "UC San Diego"],
    signal: "从潜动作表征中分离背景变化与机器人动作，降低 world model 学到伪相关的风险",
    tags: ["Latent Action", "World Model", "Causal Debiasing"],
    classification: { research: "WM", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"] },
    motivation: "无动作标注视频中的相机运动、背景变化和物体自运动会被 latent action model 当作控制信号，导致 action-conditioned world model 在零动作或跨场景时产生错误变化。",
    methodSummary: "CD-LAM 联合使用本体中心重建、动作中心对比学习和零转移校准，让潜动作保留机器人可控变化并压制与动作无关的视觉扰动。",
    architecture: "latent action encoder/decoder 先从相邻帧提取潜动作；去偏微调后，潜动作作为条件输入 2B/14B action-conditioned world model，再迁移到机器人动作适配。",
    optimization: "先训练 LAM，再用三项去偏目标微调；随后分别进行 2B 与 14B 世界模型对齐实验，并比较 1、10、100、1000 小时去偏数据的缩放。",
    data: "去偏主实验使用 100 小时数据；EgoDex 与 AgiBot 各留出 300 段视频评测，世界模型微调约 2K steps，对齐实验覆盖 3K/6K steps。",
    experiments: "2B 模型 FDCE 从 12.63 降到 8.24，14B 从 11.11 降到 7.73；零动作残差分别从 10.71 降到 5.03、9.36 降到 2.18，并提供三项训练目标消融。",
    novelty: "相较只做重建的 LAM，CD-LAM 明确用零转移与动作对比约束不可控变化；约 1 小时数据已经获得 1000 小时去偏收益的约 80%。",
    strengths: "两种模型规模、两类 held-out 视频、零动作诊断和目标函数消融共同验证了去偏是否真正作用于动作条件。",
    limitations: "因果分离依赖构造的训练对与零转移假设；对复杂接触和长时闭环控制的收益仍是间接证据。",
    transfer: "可作为 WAM/VLA 使用人类视频预训练前的潜动作清洗层，特别适合相机运动明显的数据。",
    experimentDetails: [{ title: "潜动作去偏与世界模型对齐", setup: "EgoDex、AgiBot 各 300 段 held-out 视频；比较 2B/14B action-conditioned world model，并改变去偏数据小时数。", comparisons: "原始 LAM、去掉三项损失中任一项的消融，以及不同数据规模。", results: ["2B FDCE 12.63→8.24，14B 11.11→7.73。", "零动作残差在 2B 上 10.71→5.03、14B 上 9.36→2.18。", "1 小时数据已捕获约 80% 的 1000 小时收益，说明目标设计比简单堆数据更关键。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["三项去偏损失：本体中心重建、动作中心对比、零转移校准；2B/14B 模型与多档小时数实验。"], verifiedResources: ["论文披露训练层级、held-out 数量及完整目标消融。"], missing: ["代码、模型权重和训练样本构造工具尚未确认公开。"] },
    deepDive: { lead: "核心是把‘画面发生变化’与‘机器人做了动作’分开。", sections: [{ title: "三路去偏约束", paragraphs: ["本体中心重建要求 latent action 能解释机器人主体附近的可控变化；动作中心对比把动作相近、背景不同的样本拉近；零转移校准则要求静止动作对应接近零的潜变化。", "微调后的潜动作再进入世界模型条件支路。FDCE 与 zero-action residual 同时下降，说明收益不是单纯提高视频重建质量，而是改善动作条件的可辨识性。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-13/2607.09185-overview.png", alt: "CD-LAM 从潜动作模型去偏微调到动作条件世界模型适配的整体流程", caption: "Figure 2 · CD-LAM 的三项去偏目标与下游 world model 对齐。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 3,
    title: "Artificial Foveated Perception for Mitigating Shortcut Learning in Robotic Foundation Models",
    arxivId: "2607.10655",
    url: "https://arxiv.org/abs/2607.10655",
    institutions: ["Yale University", "University of Connecticut", "Peking University", "Imperial College London", "Digients"],
    signal: "用任务条件显著区域掩码抑制背景捷径，在不改动作策略主体的情况下提升视觉 OOD",
    tags: ["Visual Robustness", "Task Mask", "OOD Generalization"],
    classification: { research: "表征学习", training: "Post-training", modalities: ["Mask / Segmentation"], data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    motivation: "机器人基础模型容易把训练场景的背景、桌面纹理或固定物体位置当作捷径，部署到新背景时即使任务目标未变也会失效。",
    methodSummary: "AFP 从图像与语言指令预测任务相关区域，将原图和 foveated 结果共同交给策略，使视觉主干更集中于目标物、交互部位和必要上下文。",
    architecture: "mask predictor 采用 deformable Transformer encoder/decoder、冻结 CLIP 文本编码器与 FiLM 条件调制；输出掩码经自适应融合后接入不同机器人策略主干。",
    optimization: "先用像素级任务相关标注训练 mask predictor，再把 AFP 作为前端接入现有策略训练；论文跨四种 backbone 验证，而非只针对单一 VLA。",
    data: "掩码数据共 380,574 张，混合仿真与真实图像；MimicGen 8 个任务每个 500 demos，真实五项任务每项 300 demos。",
    experiments: "仿真和真机均测 ID/OOD。π0.5 在 Stack OOD 0.61→0.88、Threading 0.46→0.77、Kitchen 0.22→0.59；真机 Drawer OOD 0.30→0.67、Lamp 0.20→0.53。",
    novelty: "与通用裁剪或显著性增强相比，AFP 的掩码由任务语言条件化且保留必要上下文；四种 backbone 的一致提升说明它不是某一策略结构的特例。",
    strengths: "数据量、跨模型、仿真与真机 OOD 以及前端结构消融较完整。",
    limitations: "依赖任务相关区域标注；mask predictor 自身遇到未见物体或指令时可能成为新的单点失效源。",
    transfer: "可作为 VLA 的可插拔视觉前端，也可用于构造关注区域标注和检查模型是否依赖背景捷径。",
    experimentDetails: [{ title: "仿真与真实场景 OOD", setup: "MimicGen 8 任务、500 demos/任务、20K steps；真实五任务、300 demos/任务、50K steps，每项 ID/OOD 各 30 次 rollout。", comparisons: "四种策略 backbone 的原始输入与 AFP 输入，并消融掩码和融合模块。", results: ["π0.5 的三项仿真 OOD 分别从 0.61/0.46/0.22 提升到 0.88/0.77/0.59。", "真机 Drawer OOD 0.30→0.67，Lamp OOD 0.20→0.53。", "提升主要集中在背景和干扰物变化，符合减少视觉捷径的设计目标。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["deformable Transformer、冻结 CLIP、FiLM 条件、任务掩码融合；仿真 20K、真机 50K steps。"], verifiedResources: ["论文给出 380,574 张标注图、训练协议与多 backbone 结果。"], missing: ["完整代码、掩码数据下载地址与标注流程尚未确认公开。"] },
    deepDive: { lead: "AFP 不是把图像简单裁小，而是学习任务条件下应该保留什么。", sections: [{ title: "任务条件 foveation", paragraphs: ["语言指令先经冻结 CLIP 编码，再通过 FiLM 调制图像特征；deformable attention 用稀疏采样聚焦交互区域，mask head 输出软掩码。", "原始视觉和 foveated 视觉共同进入策略，避免只保留目标物却丢失机械臂、容器或接触上下文。跨 backbone 的实验用于检验收益是否来自前端而非特定动作头。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-13/2607.10655-overview.png", alt: "AFP 用语言条件掩码突出任务相关视觉区域并接入机器人策略", caption: "Figure 2 · Artificial Foveated Perception 结构。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 4,
    title: "Action Map Policy: Learning 3D Closed-loop Manipulation via Pixel Classification",
    arxivId: "2607.10706",
    url: "https://arxiv.org/abs/2607.10706",
    institutions: ["Northeastern University", "Stanford University", "Brown University"],
    signal: "把连续 3D 动作预测改写为多视角像素分类，获得快速闭环与较强空间泛化",
    tags: ["Action Map", "Pixel Classification", "Closed-loop Control"],
    classification: { research: "VLA", training: "BC", modalities: ["Point Cloud / 3D"], platforms: ["机械臂", "夹爪"] },
    motivation: "连续坐标回归在多峰动作和精确空间定位上容易平均化；点云策略又常有较高算力与标定成本。",
    methodSummary: "AMP 将未来关键点投影到多个相机平面，对每个动作时刻预测像素热图，再从跨视角分类结果恢复 3D 关键点轨迹。",
    architecture: "三个 224×224 视角分别经 4 个 ResBlock 编码；6 层 multi-view Transformer 做同视角与跨视角注意力，解码 5 个关键点、12 步动作并执行前 8 步。",
    optimization: "使用行为克隆训练像素分类损失；闭环执行后滚动重规划，不依赖生成式采样。",
    data: "MimicGen 六任务每项 100 demos；真实三项长时任务约 70 demos/项，另有两项激光指向任务各 40 demos。",
    experiments: "仿真六任务平均 64.7%，Diffusion Policy 约 44.0%；真实咖啡/吐司/鸡蛋任务分别 80%/90%/85%，明显高于 DP 与 ACT，并以 13.8 ms 完成一次推理。",
    novelty: "相对连续动作回归，AMP 用离散空间证据表达多峰目标；相对 3D 点云策略，它只需多视角 RGB 与相机几何即可恢复 3D 动作。",
    strengths: "长时真机、精确指向、速度、跨基线和多视角结构均有直接对照。",
    limitations: "依赖相机标定与视野覆盖；热图抖动和并联夹爪假设限制了精细姿态与灵巧手任务。",
    transfer: "适合把动作位置从连续回归改为视角内分类，尤其可用于需要快速闭环的桌面操作。",
    experimentDetails: [{ title: "多视角闭环操作", setup: "MimicGen 六任务每项 100 demos、50 次测试；真机三项长时任务约 70 demos、每项 20 次，激光目标任务各 40 demos、20 次。", comparisons: "Diffusion Policy、ACT 与连续坐标动作基线。", results: ["仿真六任务 AMP 平均 64.7%，Diffusion Policy 44.0%。", "真机咖啡 80%、吐司 90%、鸡蛋 85%；对应 DP 为 25%/40%/25%，ACT 为 15%/35%/15%。", "两项激光指向均为 100%；推理 13.8 ms，而 DP 约 93.5 ms。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["3×224×224 相机；4 ResBlocks；6 层 multi-view Transformer；5 keypoints；12-step chunk、执行前 8 步。"], verifiedResources: ["论文披露每项 demos、测试次数、网络层数和推理延迟。"], missing: ["代码、相机标定工具和真实数据尚未确认公开。"] },
    deepDive: { lead: "AMP 把机器人动作变成相机平面上的分类问题。", sections: [{ title: "从热图到 3D 动作", paragraphs: ["每个视角的 decoder 为未来关键点生成热图，argmax 得到像素坐标；跨视角对应关系再恢复三维位置。分类分布可以同时保留多个候选区域，避免回归损失把两个可行动作平均到不可行位置。", "模型每次生成 12 步但只执行前 8 步，以较低推理延迟持续重规划；因此性能同时取决于空间分类精度和相机几何一致性。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-13/2607.10706-overview.png", alt: "AMP 的多视角编码、交叉注意力和动作热图解码架构", caption: "Figure 2 · Action Map Policy 多视角像素分类结构。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 5,
    title: "Robo-ValueRL: Reliable Value Estimation for Offline-to-Online Reinforcement Learning",
    arxivId: "2607.09866",
    url: "https://arxiv.org/abs/2607.09866",
    institutions: ["Renmin University of China", "Beijing Forestry University", "Peking University", "Microsoft Research"],
    signal: "用短历史价值模型与受限残差适配器，将大规模离线人形机器人数据安全地转入在线强化学习",
    tags: ["Value Estimation", "Offline-to-Online RL", "Humanoid Manipulation"],
    classification: { research: "VLA", training: "RL", data: "在线数据 / 人工纠正", platforms: ["Humanoid", "灵巧手"] },
    motivation: "离线人形操作数据能训练出基础策略，但进入真实在线 RL 后，价值高估与分布漂移会让策略迅速退化。",
    methodSummary: "先用五帧历史训练可靠价值模型并用多项诊断筛选，再冻结基础策略，只让在线 adapter 生成有界残差与门控幅度。",
    architecture: "历史视觉经 Perceiver 汇总，Transformer value head 估值；在线 adapter 由残差头和 sigmoid gate 组成，在基础动作上添加 tanh 有界修正。",
    optimization: "240 小时离线数据预训练，随后在真实机器人上三轮迭代；每轮约 500 rollouts，累计超过 3000 次在线交互。",
    data: "真实 humanoid 芯片插接与积木拆卸，离线数据 240 小时，在线 rollout 超过 3000 条。",
    experiments: "离线阶段两任务成功率分别提升 26 与 34 个百分点；在线三轮后芯片插接从 46% 到 86%，并用 MOR、bump ratio/magnitude、error sensitivity/slope 检查价值可靠性。",
    novelty: "相对直接全量微调或 DAgger，Robo-ValueRL 把风险限制在有界残差支路，并在上线前以专门指标审计价值模型。",
    strengths: "真实 humanoid、大规模在线交互、价值诊断、迭代曲线和 DAgger 对照均较充分。",
    limitations: "在线数据成本仍高；价值诊断阈值和残差上限可能随本体、任务改变。",
    transfer: "可借鉴为冻结 VLA 增加小型在线 residual adapter，并先用行为扰动测试价值函数是否可信。",
    resources: [{ label: "项目页", url: "https://gewu-lab.github.io/Robo-ValueRL/" }, { label: "GitHub", url: "https://github.com/Open-X-Humanoid/Robo-ValueRL" }],
    experimentDetails: [{ title: "离线到在线真机迭代", setup: "芯片插接与积木拆卸；240 小时离线训练，三轮在线迭代、每轮约 500 rollouts，累计超过 3000。", comparisons: "冻结基础策略、软/硬残差配置与 DAgger。", results: ["离线策略在芯片与积木任务分别提升 26、34 个百分点。", "芯片插接由 46% 提升到 86%；一次在线迭代的严格设置为芯片 56%、积木 70%。", "DAgger 一轮后芯片仅 20%，显示直接模仿纠正不能替代可靠价值引导。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["5-frame value history；Perceiver context + Transformer；tanh residual 与 sigmoid gate；每轮约 500 rollouts。"], verifiedResources: ["项目页和 GitHub 已公开；论文给出价值诊断指标、离线小时数与在线迭代规模。"], missing: ["全部真实数据与硬件标定文件是否完整开放需以仓库为准。"] },
    deepDive: { lead: "这项工作的重点是先判断价值模型能否安全地指导真机探索。", sections: [{ title: "价值诊断与受限适配", paragraphs: ["五帧历史为价值头提供接近、接触和纠正的短时线索。MOR、bump ratio、误差敏感度等指标分别检查排序、局部平滑与错误动作响应，避免只看离线回归损失。", "在线阶段冻结基础策略，adapter 只输出门控后的有界残差；即使价值估计暂时不准，也不会立即把动作推离示范分布太远。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-13/2607.09866-overview.png", alt: "Robo-ValueRL 的历史价值估计、质量诊断和在线残差动作适配器", caption: "Figure 2 · Robo-ValueRL 的价值模型与在线 adapter。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 6,
    title: "TACTIC: Tactile and Vision Conditioned Contact-Centric Control for Whole-Arm Manipulation",
    arxivId: "2607.09218",
    url: "https://arxiv.org/abs/2607.09218",
    institutions: ["Cornell University", "Carnegie Mellon University", "Toyota Research Institute"],
    signal: "把全臂触觉压缩成接触中心状态，并在 MPPI 中显式建模接触雅可比与力约束",
    tags: ["Whole-arm Tactile", "Contact-aware MPPI", "Hybrid Dynamics"],
    classification: { research: "表征学习", training: "BC", modalities: ["Tactile", "Depth / RGB-D", "State / Proprioception"], platforms: ["机械臂", "夹爪"] },
    motivation: "全臂操作中接触可能发生在任意连杆，末端位姿和单点力传感无法描述接触位置、法向与滑动趋势。",
    methodSummary: "TACTIC 从视觉、深度、接近、关节状态和 22 个触觉传感器学习接触中心表示，再在 MPPI 中用触觉估计的接触雅可比筛选安全动作。",
    architecture: "感知模块输出接触位置、法向和隐状态；混合预测模型结合解析运动学与学习残差，contact-aware action sampler 根据力有效方向生成候选控制。",
    optimization: "从遥操作数据学习潜接触动力学，控制时以约 12 Hz 运行 MPPI，底层柔顺控制器以 1 kHz 执行。",
    data: "Kinova Gen3 7-DoF、22 个全臂触觉传感器、RealSense D455 与外骨骼遥操作数据，覆盖迷宫、侧翻和肢体重定位。",
    experiments: "真实 Maze 为 3/5、平均完成时间 71.4 秒，对照策略 2/5且达到 300 秒上限；Side Rollover 12/20 对 3/20，Limb Reposition 14/20 对 5/20。",
    novelty: "相对只用视觉或末端力，TACTIC 把分布式全臂接触变成规划器可使用的接触状态与控制方向。",
    strengths: "三类真实全臂任务、成功率、完成时间、力违规与混合模型消融互相支撑。",
    limitations: "依赖密集触觉硬件与标定；MPPI 频率和接触表示能否扩展到高速动态操作尚未验证。",
    transfer: "适合把分布式皮肤信息转成接触事件、法向与可行动方向，而不是直接把全部触觉序列拼进策略。",
    experimentDetails: [{ title: "全臂接触真机控制", setup: "Kinova Gen3 + 22 tactile sensors + RGB-D；Maze 5 次，Side Rollover 与 Limb Reposition 各 20 次。", comparisons: "视觉/本体状态控制与不使用完整 contact-centric 模型的变体。", results: ["Maze 成功 3/5，对照 2/5；平均完成 71.4 秒，对照触及 300 秒上限。", "Side Rollover 为 12/20 对 3/20；Limb Reposition 为 14/20 对 5/20。", "部分任务的力违规低于专家遥操作，说明提升并非以更大碰撞力换取。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["Kinova Gen3 7-DoF；22 tactile sensors；RealSense D455；MPPI≈12 Hz；compliant controller 1 kHz。"], verifiedResources: ["论文给出传感器布局、控制频率、任务协议和计数结果。"], missing: ["完整控制代码、传感器标定和遥操作数据尚未确认公开。"] },
    deepDive: { lead: "TACTIC 将全臂接触从高维传感器读数压缩成控制器可以推演的物理状态。", sections: [{ title: "接触中心表示与混合预测", paragraphs: ["多模态编码器先估计接触位置、法向、接近程度和潜接触状态；解析运动学负责机器人几何，学习模型只补充接触动力学残差。", "采样器根据接触雅可比把候选动作投影到力有效方向，并过滤可能造成过大接触力的控制，因此 MPPI 优化的是可执行接触行为而非纯末端轨迹。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-13/2607.09218-overview.png", alt: "TACTIC 的接触中心感知、接触感知动作采样与混合预测模型", caption: "Figure 2 · TACTIC 全臂接触控制框架。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 7,
    title: "GenVid2Robot: From Video Generation to Robot Manipulation via Rigid-Geometric Consistency",
    arxivId: "2607.09191",
    url: "https://arxiv.org/abs/2607.09191",
    institutions: ["Guangdong University of Technology", "University of Liverpool", "The Hong Kong Polytechnic University", "Shanghai Jiao Tong University"],
    signal: "把生成视频视为不确定运动假设，用刚体几何一致性筛出可执行的稀疏 3D 轨迹",
    tags: ["Generated Video", "Rigid Geometry", "Zero-shot Manipulation"],
    classification: { research: "WAM", training: "Pre-training", modalities: ["Depth / RGB-D", "Mask / Segmentation"], data: "合成 / 仿真数据", platforms: ["机械臂", "夹爪"] },
    motivation: "视频生成模型能展示任务过程，但生成帧中的纹理漂移、形变和深度不一致不能直接当作机器人轨迹。",
    methodSummary: "系统先用部件提示与 SAM 建立语义锚点，利用深度聚类与 CoTracker 跟踪，再以 PnP/RANSAC 检查刚体几何并恢复稀疏 SE(3) 轨迹。",
    architecture: "三阶段管线依次完成语义锚点、刚体几何过滤和抓取条件控制；AnyGrasp 提供初始抓取，IK 执行轨迹，并只允许单轴有界深度修正。",
    optimization: "不训练端到端机器人策略，主要复用视频生成、分割、跟踪、抓取和几何求解器；几何一致性是关键过滤环节。",
    data: "在 RM75 + RGB-D 真机上评测四项操作，每项 20 次；输入来自任务条件生成视频与当前真实场景。",
    experiments: "四任务成功率为 90%/90%/85%/80%，共 69/80；去掉几何过滤后为 75%/80%/70%/60%。11 次失败中 8 次来自工作空间限制。",
    novelty: "相比直接模仿生成视频像素运动，该方法只保留跨帧满足刚体约束的语义锚点并恢复相对 SE(3)，把生成误差挡在执行前。",
    strengths: "完整真机计数、过滤消融、失败归因和端到端延迟均有披露。",
    limitations: "单次规划约 420.5 秒，其中视频生成与 VLM 锚点占绝大部分；大图像位移需重新初始化，尚非实时闭环。",
    transfer: "可把视频模型当作离线任务草图生成器，再用几何验证和低层闭环将其约束为可执行轨迹。",
    experimentDetails: [{ title: "生成视频到真机执行", setup: "RM75 + RGB-D，四项任务各 20 次；统计成功、过滤消融、失败类型与各模块延迟。", comparisons: "完整几何一致性管线与去掉 filtering 的版本。", results: ["完整方法四任务为 90%/90%/85%/80%，合计 69/80。", "无过滤版本为 75%/80%/70%/60%，说明刚体几何筛选贡献稳定。", "总延迟 420.5 秒：视频生成 185.5 秒、锚点 VLM 224.8 秒；11 次失败中 8 次是工作空间越界。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["SAM + depth KMeans；CoTracker；PnP/RANSAC；AnyGrasp；IK；单轴有界深度修正。"], verifiedResources: ["论文披露 80 次真机协议、失败计数与模块级 latency。"], missing: ["完整系统代码、提示模板与生成模型配置尚未确认公开。"] },
    deepDive: { lead: "GenVid2Robot 不相信每个生成像素，而是寻找跨帧可由刚体运动解释的少量锚点。", sections: [{ title: "三阶段几何约束", paragraphs: ["先由 VLM 给出应跟踪的物体部件，SAM 与深度聚类把语义区域变成空间锚点；CoTracker 提供跨帧对应。", "PnP/RANSAC 从候选对应中剔除非刚体漂移并估计相对 SE(3)。抓取与 IK 再把这条稀疏轨迹映射到真实机械臂，深度方向只做受限修正，避免跟随生成视频的任意形变。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-13/2607.09191-overview.jpg", alt: "GenVid2Robot 从语义锚点、刚体几何一致性到抓取条件控制的三阶段流程", caption: "Figure 1 · GenVid2Robot 从生成视频到真机轨迹的完整管线。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 8,
    title: "SUREFlow: State-space Uncertainty-aware Residual Flow Matching for Robust Robot Manipulation",
    arxivId: "2607.10504",
    url: "https://arxiv.org/abs/2607.10504",
    institutions: ["Kyungpook National University"],
    signal: "在流匹配动作上显式估计状态空间不确定性，并用受掩码的残差流迭代修正动作",
    tags: ["Uncertainty", "Residual Flow", "Mamba"],
    classification: { research: "VLA", training: "BC", modalities: ["State / Proprioception"], platforms: ["机械臂", "夹爪"] },
    motivation: "单次 flow matching 在观测模糊或长时任务中容易把不确定动作直接执行，且标准损失没有区分高、低置信维度。",
    methodSummary: "SUREFlow 用 MGAD 产生多粒度动作查询，再由 URFlow 预测残差和异方差不确定性；只有低置信动作维度进入多步残差细化。",
    architecture: "双视角 ResNet-18、CLIP ViT-B/32 与 5 层 Mamba 主干；MGAD 使用 10 个 action queries，URFlow 由速度头、uncertainty head 和闭环 residual update 组成。",
    optimization: "300 epochs、batch 256、单张 RTX 4090，70 个 flow integration steps；不确定性阈值 0.9，默认 3 次 refinement。",
    data: "LIBERO、MetaWorld、LIBERO-Pro，并在 Franka 真实颜色杯匹配/插入任务上测试。",
    experiments: "LIBERO 平均 92.5%、MetaWorld 88.32%；LIBERO-Pro 为 0.49，接近 OpenVLA 0.52 与 π0.5 0.53。真实任务平均 88.5%，但只覆盖一个任务族。",
    novelty: "相比只预测单一速度场，URFlow 同时预测状态相关方差并仅细化不确定维度；消融中 full 0.92、去掉部分残差模块 0.91、仅 UR 为 0.81。",
    strengths: "仿真多基准、模块消融、refinement 次数和不确定性权重均有检查，并补充了真机验证。",
    limitations: "真实实验范围较窄；LIBERO-Pro 跨论文结果可能受训练设置差异影响，尚不能据此断言超过大型 VLA。",
    transfer: "可把 uncertainty head 用作 action chunk 的维度级重采样门控，而非对整段动作统一重复去噪。",
    resources: [{ label: "GitHub", url: "https://github.com/tanvirnwu/SUREFlow" }],
    experimentDetails: [{ title: "多基准与残差细化消融", setup: "LIBERO、MetaWorld、LIBERO-Pro；Franka 颜色杯匹配/插入真机任务；默认三次 residual refinement。", comparisons: "OpenVLA、π0.5、常规 flow policy，以及 MGAD/URFlow 组合消融。", results: ["LIBERO 92.5%，MetaWorld 88.32%；LIBERO-Pro 0.49。", "模块消融 full 0.92，MGAD+UR 0.91，仅 UR 0.81；三次细化最好。", "真机平均成功率 88.5%，但实验只覆盖单一颜色杯任务族。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["ResNet-18 双视角；CLIP ViT-B/32；5-layer Mamba hidden 256；10 action queries；300 epochs；batch 256；70 flow steps；3 refinements。"], verifiedResources: ["GitHub 已公开；论文提供主要架构、训练轮次和模块超参数。"], missing: ["真机数据与跨基准完整训练配方是否全部开放需以仓库为准。"] },
    deepDive: { lead: "SUREFlow 把动作生成拆成初始速度预测与不确定维度的闭环残差修正。", sections: [{ title: "异方差残差流", paragraphs: ["MGAD 从视觉、语言和状态中生成多组动作查询，Mamba 负责长序列状态建模。URFlow 同时输出速度均值与逐维不确定性，构造 mask 只让高不确定动作参与后续 refinement。", "残差更新仍受 flow-matching 目标监督；迭代次数消融显示三次之后收益不再增加，因此部署成本可以固定。"] }], equations: [{ name: "不确定性加权流损失", expression: "L = Σᵢ [(vᵢ−v*ᵢ)² / (2σᵢ²) + log σᵢ] + λLres", explanation: "速度误差按预测方差缩放，同时以 log σ 防止模型无限放大不确定性；Lres 监督残差细化。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-13/2607.10504-overview.jpg", alt: "SUREFlow 的 Mamba 主干、多粒度动作查询和不确定性感知残差流", caption: "Figure 2 · SUREFlow 模型与 URFlow 闭环细化。图片截取自 arXiv 原论文。" }],
  },
];
