import type { Paper, PaperEquation } from "./site-data";

type Entry = Omit<
  Paper,
  "rank" | "figures" | "optimization" | "experimentDetails" | "reproducibilityDetails" | "deepDive"
> & {
  figureFile: string;
  figureAlt: string;
  figureCaption: string;
  technique: string[];
  evaluation: string[];
  comparison: string;
  reproducibilityStatus: "资源较完整" | "部分可复现" | "信息不足";
  implementation: string[];
  missing: string[];
  equations?: PaperEquation[];
};

const makePaper = (entry: Entry, index: number): Paper => ({
  ...entry,
  rank: index + 1,
  optimization: entry.technique.join("；"),
  experimentDetails: [{ title: "原文实验与消融", setup: entry.experiments, comparisons: entry.comparison, results: entry.evaluation }],
  reproducibilityDetails: {
    status: entry.reproducibilityStatus,
    verifiedResources: entry.resources?.map((resource) => `${resource.label}: ${resource.url}`) ?? ["arXiv 论文正文"],
    implementation: entry.implementation,
    missing: entry.missing,
  },
  deepDive: {
    lead: entry.methodSummary ?? entry.signal,
    sections: [{ title: "方法与模型改进", paragraphs: entry.technique }],
    equations: entry.equations,
    experimentReading: entry.evaluation,
    reflections: [entry.transfer],
  },
  figures: [{ src: `/report-assets/2026-08-17/${entry.figureFile}`, alt: entry.figureAlt, caption: entry.figureCaption }],
});

const entries: Entry[] = [
  {
    title: "GigaBrain-0.7: Scaling Embodied Foundation Models to Emergent Capabilities with a Three-System Architecture",
    arxivId: "2608.15875",
    url: "https://arxiv.org/abs/2608.15875",
    institutions: ["GigaBrain Team"],
    signal: "把理解与规划、未来预测与价值评估、连续动作控制组织成三个相互通信的系统，并在 3.73 万小时异构具身数据上做一次性联合预训练。",
    tags: ["Embodied Foundation Model", "Multi-Embodiment", "World Model"],
    classification: { research: "VLA", training: "Pre-training", data: "跨本体数据", platforms: ["机械臂", "Humanoid", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://gigaai.cc/blog/gigabrain07" }, { label: "GitHub", url: "https://github.com/open-gigaai/giga-brain-0" }],
    motivation: "跨本体数据继续扩张后，简单扩大动作模型容易产生数据干扰；长时任务还需要把理解、未来预测、进度判断和执行连接起来。",
    methodSummary: "System 1 以 flow matching 生成不同本体的连续动作块；System 2 用历史视觉与层级提示跟踪进度、拆解子任务；System 3 预测未来视觉状态并估计价值，再以图像或价值条件回馈动作系统。",
    architecture: "预训练 VLM 与 embodiment-aware action expert 在同一阶段联合优化，Soft Knowledge Insulation 只衰减动作梯度而非完全冻结 VLM；三系统通过语义、视觉 subgoal 和 value 接口通信。",
    data: "清洗后含 37,256.98 小时具身轨迹：20,535.65 小时真机、8,251.83 小时 UMI、Ego 人类示范、1,453.92 小时仿真和 4,153.22 小时世界模型生成数据；另有 271,976,674 条 VLM 样本，真机部分覆盖 16 种机器人。",
    experiments: "覆盖 VLM 理解、RoboTwin 2.0、EBench、RoboColiseum，以及 AgileX PiPER/PiPER-X 和 Maker H01 真机；同时检查数据/模型规模、VLA 耦合、System 3、语言跟随、长时操作与 SFT→离线 RL→在线 RL。",
    novelty: "Maker H01 六项语言跟随均值由前代的 69.6% 提至 84.2%；四项真机复杂任务平均成功率由 SFT 30.0% 经离线 RL 提至 57.5%，再经在线 RL 达到 100%。",
    strengths: "数据组成、清洗链、跨本体接口和训练阶段披露较完整；证据同时覆盖仿真、不同真机本体、语言泛化、复杂接触任务和经验驱动改进。",
    limitations: "主要结果来自团队自建数据与平台，外部尚难独立复核 3.73 万小时语料和真机协议；代码与权重在论文中仍表述为将发布。",
    transfer: "对多数据源 VLA，先统一本体元数据、动作掩码和指令粒度，再考虑规模；规划、未来图像与价值最好保持显式接口，便于逐项消融。",
    technique: [
      "System 1 接收视觉、语言、本体状态与高层条件，以连续 flow-matching action expert 输出动作块；本体描述控制有效自由度和控制方式。",
      "System 2 从当前与历史视觉中形成任务进度和层级 subtask；System 3 的 world model 同时提供未来视觉 subgoal 与状态价值，两种信号可单独或联合条件化 System 1。",
      "训练数据统一转为 LeRobot v3.0，并经过状态/动作归一、LLM 指令重写、子任务标注、轨迹平滑与可执行性检查；Soft KI 控制动作损失进入 VLM 的梯度强度。",
    ],
    equations: [{ name: "连续动作流目标", expression: "xₜ = (1−t)·ε + t·a，L_FM = ‖vθ(xₜ, t, c) − (a−ε)‖²", explanation: "由高斯噪声 ε 插值到真实动作块 a；条件 c 可包含语言、历史、视觉 subgoal 与价值信息。" }],
    evaluation: [
      "真机语言跟随覆盖颜色、目标和方向区分，并在 PiPER 与 H01 两种本体上比较 π0.5、Xiaomi-Robotics-1 和前代 GigaBrain；H01 完整均值为 84.2%。",
      "复杂任务包括橡皮泥、扫料、整理、装配、线缆扎带等多阶段或持续接触任务；经验强化的四项任务在相同定义下逐阶段比较，平均 30.0%→57.5%→100%。",
      "System 3、数据规模、来源配比、VLM 容量和耦合方式均有受控分析；部分真机表格通常每设置仅约 10–20 次，满分结果仍需更大规模独立重复。",
    ],
    comparison: "π0.5、Xiaomi-Robotics-1、GigaBrain-0/0.1/0.5M*，以及 RoboTwin、EBench、RoboColiseum 的公开 VLA；另含数据规模、耦合方式和 System 3 信号消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["论文给出数据源小时数、16 类本体、统一数据处理链、三系统接口、Soft KI、后训练阶段和主要真机协议。"],
    missing: ["完整 37K 小时语料、训练代码和 0.7 权重尚未在论文发布时完成公开；自建平台结果需依赖团队环境复现。"],
    figureFile: "2608.15875-fig1.png",
    figureAlt: "GigaBrain-0.7 三系统架构与数据和经验学习闭环",
    figureCaption: "Figure 1 · 理解与规划、预测与评估、动作与控制三个系统，以及异构预训练数据和经验强化接口。来源：arXiv 原图。",
  },
  {
    title: "AdvDex: Learning Dexterous Manipulation from Human Demonstrations via Joint-Aligned Actions and Adversarial Learning",
    arxivId: "2608.14028",
    url: "https://arxiv.org/abs/2608.14028",
    institutions: ["Zhejiang University", "Shanghai Innovation Institute", "Shanghai Jiao Tong University", "Fudan University", "Paxini Tech"],
    signal: "把人手、灵巧手和夹爪映射到同一关节语义空间，并用域对抗减少策略对硬件外观的依赖。",
    tags: ["Dexterous Manipulation", "Human-to-Robot", "Cross-Embodiment"],
    classification: { research: "VLA", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "灵巧手", "夹爪"], deployment: "跨本体迁移" },
    motivation: "人类示范便于扩张，但人手、不同灵巧手和夹爪的自由度与外观不一致；直接混训容易记住本体身份，而不是共享任务结构。",
    methodSummary: "JAAS 用 SE(3) 腕位姿与 15 个功能对齐手指关节统一动作；训练期域判别器经 Gradient Reversal 压低 cognition/state token 中的本体身份信息。",
    architecture: "SigLIP/VLM 产生认知 token，Diffusion Transformer action expert 在 JAAS 中去噪动作块；域判别器只在训练期参与，推理时移除。",
    data: "OmniShare 含 168k 轨迹、500 余项任务和 721 个物体；预训练按 OmniShare、VITRA-1M、Open X-Embodiment 以 5:4:1 混合，五项真机后训练共使用 1,000 条示范。",
    experiments: "Paxini Tora + 19-DoF DexH13；五项已见任务、未见物体、未见环境均为每方法每任务 20 次，另用任务互斥的人类/机器人各 1,000 条轨迹测试人类技能零样本迁移。",
    novelty: "未见物体/环境成功率为 50%/60%，π0.5 为 35%/45%；四项只在人类数据中出现的任务仍获得 30%–70% 真机成功率。",
    strengths: "数据、动作对齐和域对抗有独立消融；测试对象、指令与机器人后训练数据做了非重叠检查，真机重复次数固定。",
    limitations: "物理评测只覆盖一种灵巧手平台；JAAS 没有显式统一动力学、触觉带宽和接触约束，精细技能仍需目标机器人数据。",
    transfer: "跨本体数据可先拆成稳定共享的功能关节和本体专用维度，对缺失维度做 loss mask，再用域对抗检查视觉是否走硬件捷径。",
    technique: [
      "JAAS 以 SE(3) 腕位姿加 15 个手指关节为共享接口；MANO 人手、19-DoF 灵巧手与 1-DoF 夹爪分别映射到可用槽位。",
      "域判别器读取 cognition 与 state token，GRL 反转其梯度；动作 expert 仍由 diffusion denoising loss 保留完成任务所需的信息。",
      "OmniShare 的手部运动、触觉和多视图信号同步后，经 canonical hand retargeting 形成预训练监督，再与 VITRA-1M 和 OXE 混合。",
    ],
    evaluation: [
      "五项已见任务中完整模型成功率为 55%–90%；去掉预训练后降为 10%–50%，移除 OmniShare 或域对抗也会削弱未见设置。",
      "未见物体/环境分别为 50%/60%，VITRA 为 40%/35%；每个表格单元来自 20 次随机初始配置。",
      "任务互斥的人类技能迁移在 Box Doll、Press Button、Move Bottle、Tool Use 上分别为 60%、70%、45%、30%。",
    ],
    comparison: "π0.5、VITRA、无预训练、无 OmniShare、无域对抗，以及只在预训练或后训练阶段启用域对抗的变体。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文给出 JAAS 映射、损失、数据混合比例、真机示范数量和每项 20 次评测协议。"],
    missing: ["论文未提供 OmniShare 完整数据、训练代码、模型权重和硬件标定工具的公开链接。"],
    figureFile: "2608.14028-fig1.png",
    figureAlt: "AdvDex 跨人手灵巧手夹爪的统一训练概览",
    figureCaption: "Figure 1 · 人手、灵巧手与夹爪数据如何经 joint-aligned actions 和 adversarial learning 汇入统一策略。来源：arXiv 原图。",
  },
  {
    title: "Tactile Sim2Real without Tactile Simulation via Bottlenecked Latent Reconstruction",
    arxivId: "2608.15897",
    url: "https://arxiv.org/abs/2608.15897",
    institutions: ["University of Michigan"],
    signal: "不用为每种触觉传感器建立仿真，而是用点云与指尖力构造仿真 oracle，再把真实触觉映射到 oracle latent。",
    tags: ["Tactile", "Sim2Real", "Representation Alignment"],
    classification: { research: "表征学习", training: "RL", modalities: ["Tactile", "Point Cloud / 3D", "Force / Torque"], data: "合成 / 仿真数据", platforms: ["机械臂", "夹爪"], deployment: "Sim2Real" },
    motivation: "触觉硬件形态变化快，为每个传感器校准形变、光照和 marker 的物理仿真成本高，而且近似误差会直接进入策略。",
    methodSummary: "先在仿真中用 Point Force Composition 训练 RL 策略；再以无配对 random-play 数据训练双向 rectified-flow latent 转换，并用瓶颈重构做第二阶段 RL，主动适配真实传感器的信息损失。",
    architecture: "Point-MAE 编码物体/指尖点云，力自编码器组成 PFC latent；MAE 编码 GelSight/DIGIT 图像；双向 RF 网络连接两域，部署时仅用 real tactile→PFC 映射和策略。",
    data: "仿真分析每任务用 512 条 PFC 与 4,096 条 proxy-real 触觉轨迹；真机每任务/传感器自动采集 256 条触觉 random-play 与 4,096 条仿真 PFC，真机采集约 40 分钟，不含目标任务示范。",
    experiments: "Factory 三项任务每设置 3 个种子、每项 256 episodes；真机在 Peg Insertion 和 Gear Meshing 上分别使用 GelSight Mini 与 DIGIT，每个设置 40 次零样本部署。",
    novelty: "真机成功率为 85%–97.5%，比需要传感器校准与渲染的 TacSL 物理触觉仿真高 7.5–15 个百分点。",
    strengths: "把传感模态差距与动力学差距分开验证；覆盖两种触觉硬件、明确 random-play 数量、40 次真机重复，并包含 second-stage bottleneck 消融。",
    limitations: "方法只解决传感模态映射，不处理 sim-to-real 动力学差距；nut threading 等精密接触可能超出随机交互数据覆盖。",
    transfer: "先寻找易于在仿真中精确获得、信息量高于真实传感器的 oracle，再显式训练信息瓶颈，可能比追求像素级触觉仿真更稳健。",
    technique: [
      "PFC 由物体/指尖点云与各指尖接触力组成；Point-MAE 和力自编码器把它压成 oracle latent，真实触觉图像由 MAE 编码。",
      "从无配对随机交互中做 nearest-neighbor pseudo pairing，双向 rectified flow 学习 PFC↔触觉 latent 的连续转换。",
      "第一阶段策略只看 PFC；第二阶段把 PFC 先转换到估计触觉 latent、再重构回 PFC，让策略在训练时经历部署时必然出现的信息损失。",
    ],
    equations: [{ name: "Rectified-flow 路径", expression: "zₜ = (1−t)·z₀ + t·z₁，L_RF = ‖vθ(zₜ,t) − (z₁−z₀)‖²", explanation: "z₀、z₁ 分别来自 pseudo-paired 的两种传感 latent；转换网络学习沿直线路径的速度场。" }],
    evaluation: [
      "仿真 proxy-real 每方法/任务评测 256 episodes，并报告三种子均值和最大值；SBLR 接近直接使用真实触觉模拟的 image oracle。",
      "真机四个传感器—任务组合各 40 次，SBLR 为 85%–97.5%，对 TacSL 的优势为 7.5–15 点。",
      "PFC+RF 去掉第二阶段 RL 后稳定下降，DIGIT 上差距更大；DCP 离散接触位置不足以支持精密装配，OT 对齐与 nearest-neighbor+RF 接近。",
    ],
    comparison: "无触觉、离散接触位置 DCP、Optimal Transport 对齐、PFC+RF 消融、PFC/Image oracle，以及物理触觉仿真 TacSL。",
    reproducibilityStatus: "部分可复现",
    implementation: ["给出 PFC 定义、编码器、RF 转换、两阶段 RL、每域数据量、传感器和每项 40 次真机协议。"],
    missing: ["正文未提供公开代码或训练权重链接；真实动力学随机化和硬件控制栈仍需自行搭建。"],
    figureFile: "2608.15897-fig2.png",
    figureAlt: "SBLR 无传感器仿真的触觉 Sim2Real 流程",
    figureCaption: "Figure 2 · 无配对 PFC/真实触觉对齐、两阶段 RL 和部署时 real-tactile→oracle-latent 映射。来源：arXiv 原图。",
  },
  {
    title: "Reflex: Enabling Fast and Predictive Vision-Language-Action Models for Reaction-Critical Manipulation",
    arxivId: "2608.14379",
    url: "https://arxiv.org/abs/2608.14379",
    institutions: ["Shanghai Jiao Tong University"],
    signal: "把未来语义预测、视觉中层时序融合和部署时延优化放进同一个动态操作 VLA。",
    tags: ["Reaction-Critical", "VLA", "Latency"],
    classification: { research: "VLA", training: "Post-training", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://reflexvla.github.io" }],
    motivation: "静态操作基准常在模型推理时暂停环境，不能反映传送带、接球和移动目标中感知—动作时延造成的真实失效。",
    methodSummary: "训练期用冻结 DINOv3 未来 latent 约束动作表征，并在 ViT 中层融合两个时间点；部署再以多视图批量编码和 CUDA Graph 缩短首动作延迟。",
    architecture: "约 1B 的 VLA-Adapter 主干接收双时刻多视图，中层 temporal attention 只把当前融合 token 送入语言模型；action head 与训练期 future-prediction head 并行。",
    data: "ReflexBench 六项动态任务每项 200 条示范；真机三项任务使用遥操作数据训练，但论文未披露真机示范数量。",
    experiments: "ReflexBench 每任务 150 episodes、三个随机种子；另测 LIBERO；AgileX Piper 真机完成传送带抓放、按键和接球，每策略每项 20 次。",
    novelty: "相较同规模 VLA-Adapter，动态基准均值从 30.3% 提至 50.4%；渐进消融把成功率推至 73.8%，并将延迟从 125.1 ms 降到 65.0 ms。",
    strengths: "基准明确让环境在推理期间继续演化；未来目标、融合层位、批处理和 CUDA Graph 均有消融，真机重复次数固定。",
    limitations: "未来预测和时序模块依赖任务微调，真机示范数量未报告；没有与 RTC 等连续动作生成系统做完整延迟对比。",
    transfer: "动态策略评测需要把真实推理时间映射到环境步进；未来 latent 可只作训练监督，中层短历史通常比把全部历史图像塞进 VLM 更可控。",
    technique: [
      "冻结 DINOv3 从未来帧提取语义 target，以 cosine loss 训练 future head；teacher 若同时更新，动态成功率会明显崩溃。",
      "两个时间点的 ViT 中层特征做多头 temporal fusion，避免让语言模型直接承担所有高分辨率历史 token。",
      "多视图和多时刻图像一次批量编码，并用 CUDA Graph 固化部署计算图；动作目标和主干语义路径保持不变。",
    ],
    evaluation: [
      "ReflexBench 六任务均值 50.4%，PUMA 为 50.2%，VLA-Adapter 为 30.3%；本文约 1B 参数，PUMA 为 4B。",
      "渐进消融为 36.8% 基线→62.8% 冻结未来目标→71.7% 中层融合→73.8% 加时延优化；最后一步延迟 125.1→65.0 ms。",
      "真机每项 20 次：传送带抓放 16/20，按键 30 秒平均 22.5 个，10 球平均接到 6.7 个；PUMA 对应 13/20、20.8、5.4。",
    ],
    comparison: "OpenVLA-OFT、π0.5、PUMA、DynamicVLA、SmolVLA、VLA-Adapter，以及未来 teacher、融合层位、视觉批处理和 CUDA Graph 消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["给出仿真示范数、动作块与执行时域、种子数、硬件、时延协议和主要 loss 权重。"],
    missing: ["论文项目页未提供 ReflexBench 代码、模型权重或真机训练数据；真机示范数量未披露。"],
    figureFile: "2608.14379-fig1.png",
    figureAlt: "ReflexVLA 的动态操作问题、未来预测和 ReflexBench 概览",
    figureCaption: "Figure 1 · reaction-critical manipulation 的三类瓶颈、ReflexVLA 设计和六项 ReflexBench 任务。来源：arXiv 原图。",
  },
  {
    title: "StructRL: Structured Action-Space Exploration for Flow-Based VLAs",
    arxivId: "2608.15139",
    url: "https://arxiv.org/abs/2608.15139",
    institutions: ["Fudan University", "Singapore Management University", "Shanghai AI Laboratory"],
    signal: "把探索噪声从 flow denoising 链移到最终动作空间，以时间相关和动作组尺度保持机器人探索结构。",
    tags: ["VLA-RL", "Structured Exploration", "Flow Matching"],
    classification: { research: "VLA", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://flyfaerss.github.io/structrl/" }],
    motivation: "位置、旋转和夹爪需要不同噪声尺度，动作块还要时间平滑；在 denoising 中间注入结构噪声会被后续 flow 重新拉回 SFT 分布。",
    methodSummary: "保持 ODE decoder 确定性，在解码完成后加入 AR(1) 时间相关、分动作组缩放的噪声；last-step replay 从保存的末端 latent 重算动作并建立可训练 likelihood。",
    architecture: "可接 π0、π0.5、GR00T N1.5；仿真用 PPO，真机以单步 ODE 和异步 AWAC 重用 rollout/人工纠正，VLM 特征缓存后只更新 critic 与 action expert。",
    data: "仿真在 LIBERO、ManiSkill、CALVIN 在线采样；两项真机任务各从 10 条 SFT 示范开始，随后收集稀疏成功奖励、策略 rollout 和少量 SpaceMouse 纠正。",
    experiments: "三种 VLA、三套仿真基准，含 200 轮长时消融；Franka 真机 pick-banana 与 plug-charger-in 先各评测 25 次 SFT，再在线学习 30–60 分钟并做 25 次成功率评测。",
    novelty: "仅把注入位置移到动作末端就在 ManiSkill OOD 上提高 16.6–28.0 点；结构化协方差主要加速学习，真机香蕉抓取 60 分钟后为 21/25，对高斯末端噪声的 14/25。",
    strengths: "把注入位置和噪声结构拆开对照；覆盖三个 flow VLA、OOD/长时任务、四组消融和两项真机在线 RL。",
    limitations: "最终饱和后结构噪声未必始终高于末端高斯；真机只覆盖两项任务，噪声尺度和相关系数仍需按机器人安全范围调节。",
    transfer: "先验证 denoising 是否稀释既定噪声，再决定探索分布；动作空间噪声必须按平移、旋转和夹爪分别限幅，并保留人工覆盖和陈旧动作块清理。",
    technique: [
      "deterministic ODE 先输出 clean action chunk，再采样 AR(1) 时间相关噪声；位置、旋转、夹爪各自拥有尺度参数。",
      "last-step replay 保存接近终点的 flow latent 和实际执行动作，更新时只重放最后跳步，从动作空间残差计算 log-probability。",
      "真机将该 likelihood 接入 AWAC：online/demo buffer 各占一半 batch，人工中断后丢弃原动作块尾部，critic 与 action expert 异步更新。",
    ],
    equations: [{ name: "结构化动作探索", expression: "a = a_clean + Δ，Δₖ = ρ·Δₖ₋₁ + √(1−ρ²)·Σ_group·εₖ", explanation: "ρ 控制动作块时间相关性；Σ_group 分别约束平移、旋转和夹爪的探索尺度。" }],
    evaluation: [
      "GR00T N1.5 在 LIBERO 四套件由 few-shot SFT 52.5% 提至 99.0%；论文把该近饱和结果只作为 ID sanity check。",
      "ManiSkill 中，从 in-chain Flow-SDE 改为末端高斯使 π0/π0.5 的 OOD 均值分别提高 28.0/16.6 点；StructRL 主要把达到 90% 的训练步数从约 80 降到约 40。",
      "真机 pick-banana 在 60 分钟后为 84%（21/25）对高斯 56%（14/25）；插充电器约 30 分钟进入稳定全成功，高斯约需 35 分钟。",
    ],
    comparison: "SFT、Flow-SDE+PPO、π-StepNFT、动作末端高斯，以及噪声幅度、相关系数、replay 匹配和 last-step jump 消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页与正文给出三种 backbone、PPO/AWAC 训练方式、真机 buffer、安全限幅、AR 参数和在线时长。"],
    missing: ["论文未提供训练代码与完整真机数据链接；不同机器人上的安全噪声尺度仍需重新标定。"],
    figureFile: "2608.15139-fig1.png",
    figureAlt: "StructRL 动作空间结构噪声与 denoising 稀释现象",
    figureCaption: "Figure 1 · in-chain 噪声被后续 flow 稀释，以及在最终动作空间保留时间和动作组结构的做法。来源：arXiv 原图。",
  },
  {
    title: "Pre-training Visual Dexterity in Simulation",
    arxivId: "2608.15917",
    url: "https://arxiv.org/abs/2608.15917",
    institutions: ["Stanford University", "MIT", "Scale AI"],
    signal: "让人直接在目标双手本体的仿真中遥操作，获得可执行 action label，再用少量真机数据适配五项灵巧任务。",
    tags: ["Dexterous Pre-training", "Simulation Teleoperation", "Bimanual"],
    classification: { research: "表征学习", training: "Pre-training", data: "合成 / 仿真数据", platforms: ["机械臂", "灵巧手"], deployment: "Sim2Real" },
    motivation: "多指手真机遥操作昂贵，人类视频又要经过遮挡严重的姿态恢复和 retargeting；仿真遥操作可直接在目标 56-DoF 本体上产出动作。",
    methodSummary: "五名操作者一周采集 75 小时 spd-75h；causal diffusion transformer 以历史多视图、状态和动作 token 预测短动作块，再按任务用 1–2 小时真机示范全量微调。",
    architecture: "视觉 patch 经冻结 ViT 和 query pooling，状态、历史动作和 noised action chunks 交错进入共享 causal transformer；32 步 sliding-window attention 与 rolling KV cache 保持部署上下文。",
    data: "spd-75h 含 1,930 条、约 75 小时仿真轨迹，覆盖六个场景、数百对象和不同策略；五项真机任务各使用约 1–2 小时（30 Hz）示范。",
    experiments: "56-DoF 双臂灵巧手完成挂杯、盘子上架、Jenga、叠杯和投瓶；每 checkpoint 每任务 20 次随机初态，并对 history window 与 action chunk 做 2×2 消融。",
    novelty: "在相同真机数据和模型下，仿真预训练在五项任务的阶段进度上均优于从零 BC；32 步历史+8 步短动作块比对应从零训练平均高 18 点。",
    strengths: "仿真数据与真机目标本体一致，五项长时接触任务均做 20 次；历史长度、动作块和有无预训练以相同结构/训练时间比较。",
    limitations: "仿真只有六个手工调参场景，真机对象与仿真相似；没有验证对明显 OOD 对象、场景或不同灵巧手的迁移。",
    transfer: "对高维手，仿真数据的价值可能来自本体内 action 和多种策略，而不是逼真的单条最优轨迹；短动作块需要历史状态保证连续性。",
    technique: [
      "VR 系统在 MuJoCo 中把操作者腕部和手指直接映射到一对 6-DoF 手臂与灵巧手，随机化对象、物性和初态，并保留 segmentation 支持外观增强。",
      "约 222M 参数的 causal diffusion transformer 交错建模多视图、56-D proprioception、历史 56-D 动作和未来 noised chunks；视觉每 8 步采样一次。",
      "所有层采用 32 时间步滑窗，推理用匹配的 rolling KV cache；Muon 学习率固定为 10⁻³，并用 EMA checkpoint。",
    ],
    evaluation: [
      "五项真机任务每 checkpoint 20 次，按多阶段 rubric 报告完成进度；SPD 预训练在所有阶段和任务上总体高于相同结构的从零 BC。",
      "window∈{1,32}、chunk∈{8,32} 的消融显示：单帧+短块会抖动崩溃，32 步历史+8 步块在预训练和从零设置中都最好。",
      "最佳配置从预训练获得 18 点平均进度增益，其余配置增益不超过约 3 点，说明历史条件是预训练收益能否释放的关键变量。",
    ],
    comparison: "相同 diffusion-transformer 从零 BC，以及 history window 1/32 × action chunk 8/32 的四种结构；五项真机均使用一致微调数据。",
    reproducibilityStatus: "部分可复现",
    implementation: ["论文给出 1,930 episodes、采集频率、策略 token 化、滑窗/KV cache、优化器和逐任务真机数据量。"],
    missing: ["论文承诺发布 spd-75h、VR 软件和六个场景，但正文未给出可下载的官方仓库链接。"],
    figureFile: "2608.15917-fig3.png",
    figureAlt: "SPD causal diffusion transformer 训练与 rolling KV cache 推理架构",
    figureCaption: "Figure 3 · 交错视觉、状态、历史动作和 noised action chunk 的 causal transformer，以及部署时 rolling KV cache。来源：arXiv 原图。",
  },
  {
    title: "Imagining Recovery: Inference-Time Counterfactual Realignment for Vision-Language-Action Models",
    arxivId: "2608.14822",
    url: "https://arxiv.org/abs/2608.14822",
    institutions: ["Case Western Reserve University"],
    signal: "冻结 VLA 遇到目标切换或物理扰动时，先在合成观测中虚拟继续执行，再只恢复重返可行轨迹所需的最小物理状态。",
    tags: ["VLA Recovery", "Counterfactual", "Test-time Adaptation"],
    classification: { research: "VLA", training: "Test-time Adaptation", data: "合成 / 仿真数据", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "只用成功示范训练的 VLA 一旦被扰动就进入分布外状态；收集失败数据重训或外挂纠错 agent 都增加成本和新失效面。",
    methodSummary: "suffix OOD detector 触发后，从最近可行 anchor 合成反事实观测，让同一冻结策略虚拟 rollout；随后搜索 rejoin state 和最小 restoration subset，实际只执行一次物理 realignment 再交还原策略。",
    architecture: "第三视角/腕部图像由背景、对象存储和机器人前向运动学重渲染；候选恢复状态以策略 continuation 和可达性筛选，恢复本身使用同一机械臂的运动规划。",
    data: "不使用失败训练集；仿真在 LangSwitch、LIBERO-Long 的任务切换和多类扰动上生成配对评测，真机覆盖五种目标/场景/机器人状态扰动，共 100 个布局配对 episodes。",
    experiments: "横跨 π0、π0.5、GR00T、X-VLA 和多个模拟器；主仿真单元通常 100–200 episodes，另对合成 rollout fidelity、anchor、restoration subset 和阈值做独立消融；真机每种条件 20 次。",
    novelty: "同一冻结真机策略在 100 个扰动 episode 中由 21 次成功提高到 90 次；碰撞或急停由 21 次降到 5 次，恢复中位规划/执行时间为 9.7/8.8 秒。",
    strengths: "与裸策略按初态和扰动配对；仿真规模大、阈值使用独立验证 seeds，真机记录碰撞、规划时间、物理恢复成本和无扰动控制组。",
    limitations: "依赖标定相机、对象分割/深度存储和可执行的物体恢复；复杂可变形物、移动相机误差与多人场景会让合成观测和重排成本迅速增加。",
    transfer: "恢复模块应保留已完成进度，并把虚拟规划与真实动作严格分开；部署时需把恢复对象数、碰撞和耗时列为一等指标。",
    technique: [
      "后缀 OOD detector 识别当前状态已偏离可继续执行的分布，从最近 viable state 选择 recovery anchor。",
      "冻结 VLA 在重渲染的 counterfactual observations 上闭环 rollout，搜索不会重新进入失效区的 rejoin state。",
      "subset probe 逐步判断哪些对象必须恢复；物理阶段只移动必要对象并 realign 机械臂，随后将未执行动作尾部交回原策略。",
    ],
    evaluation: [
      "LangSwitch 每 cell 100 episodes，LIBERO 扰动条目每项 200 episodes；合成与真值 rollout 还以三次独立 rollout 比较末端位置偏差。",
      "真机五种条件各 20 次，裸策略 21/100，CoRe 90/100；碰撞/急停 21→5，且无扰动对照没有虚假触发。",
      "anchor 阈值在独立验证种子上扫描：成功率峰值 91.1%，过晚 anchor 降到 36.7%；subset 阈值展示恢复更少对象与失败风险的折衷。",
    ],
    comparison: "冻结 VLA 裸执行、预设 rewind/reset、不同 anchor 和 restoration subset 策略，以及合成观测与 ground-truth rollout fidelity。",
    reproducibilityStatus: "部分可复现",
    implementation: ["正文和附录给出扰动注入、验证/测试种子、相机标定残差、阈值扫描、安全 rail、真机成对协议与耗时。"],
    missing: ["论文未提供代码和真机系统资产链接；对象模型、深度存储、运动规划和恢复抓取仍是较重的系统依赖。"],
    figureFile: "2608.14822-fig2.png",
    figureAlt: "CoRe 反事实恢复和最小物理 realignment 流程",
    figureCaption: "Figure 2 · OOD 触发、虚拟 continuation、rejoin state 与最小 restoration subset，再到唯一的物理恢复阶段。来源：arXiv 原图。",
  },
  {
    title: "Remember Smarter: Visual History Compressor and Hyperbolic Experience Space for Robotic Memory",
    arxivId: "2608.15269",
    url: "https://arxiv.org/abs/2608.15269",
    institutions: ["Xidian University"],
    signal: "把近期多视图历史压入固定大小 Mamba 状态，并把成功经验组织成双曲层级，分别解决短期状态变化与可复用经验检索。",
    tags: ["Robotic Memory", "Mamba", "Hyperbolic Retrieval"],
    classification: { research: "Memory", training: "Post-training", data: "其他数据方法", platforms: ["机械臂", "夹爪"] },
    detailAttributes: { memoryImplementation: "Context/Sequence + Episodic", memoryHorizon: "历史最多 64 帧；成功经验长期存储" },
    motivation: "直接增加历史帧会扩大 VLA context 并淹没稀疏变化；扁平经验库又难表示任务层级，检索开销随数据增长。",
    methodSummary: "视觉分支用双向 spatial Mamba 与 causal temporal Mamba 递推历史；经验分支把成功 episode 的最终 VLM hidden state 编入 Poincaré VAE，构造二叉层级并异步生成 geodesic prompt tokens。",
    architecture: "视觉历史作为 K/V 供 action-facing hidden states 残差 cross-attention；经验检索最多 8 个 leaves，取最低共同祖先 prototype，解码为 4 个 prompt tokens，后台 worker 不阻塞当前动作。",
    data: "在官方 π0-LIBERO checkpoint 上只用原 LIBERO 示范适配 RS；经验库仅存成功记录。LIBERO-Plus 完整测试含 10,030 个实例；真机用七种记忆条件训练/评测。",
    experiments: "LIBERO-Plus 七类扰动、标准 LIBERO 四套件、历史长度和 TBPTT 扫描，以及重复计数、顺序事件、对象命名、遮挡和组合长时真机任务。",
    novelty: "LIBERO-Plus 总成功率由 53.6% 提至 70.6%；未训练的真机 Chen.-H 组合任务由 20% 提至 80%，视觉压缩器把 LIBERO-Long 从 85.2% 提至 92.6%。",
    strengths: "把近期 history 与 episodic retrieval 分开消融；完整跑 10,030 个扰动实例，真机专门构造当前画面不足以判断进度的记忆任务。",
    limitations: "只验证 π0，一些真机格子为 10 或 25 次；双曲树是检索索引而非可解释任务树，beam 最坏复杂度仍为 O(N)。",
    transfer: "记忆模块应先区分固定形状的近期状态和可增长的成功经验；检索结果异步用于下一控制步，可避免把数据库延迟放进动作关键路径。",
    technique: [
      "每帧 patch 先做双向 spatial Mamba 和 query pooling，再由两层 causal temporal Mamba 对各视角递推；默认历史 64 帧、TBPTT=16。",
      "成功 episode 的 final action-facing hidden state 进入 P-VAE；独立等半径坐标学习层级，内部节点用 Karcher mean 和 entailment cone 校准。",
      "后台 beam 最多检索 8 个 leaves，取最低共同祖先并沿双曲测地线形成 4 个经验 token；当前步的 query 最早在下一步生效。",
    ],
    equations: [{ name: "残差历史读取", expression: "h′ = h + gate·CrossAttention(Q=h, K=M_history, V=M_history)", explanation: "VLM 原始视觉 token 不变，只有动作侧 hidden state 读取压缩后的有序历史。" }],
    evaluation: [
      "10,030 个 LIBERO-Plus 实例各评测一次，π0 53.6%，π0+RS 70.6%，仍低于论文引用的 MemoryVLA++ 73.1%。",
      "真机七种条件中六种提高；未见过的 Chen.-H 为 20%→80%，短时 Chen.-S 反而从 64% 降到 60%。",
      "标准 LIBERO 中 VMC 将 Long 85.2%→92.6%，加入经验空间后为 94.2%；VMC/RS 用五次运行并给标准差，base 只有单次。",
    ],
    comparison: "π0、MemoryVLA 系列、仅视觉 Mamba 的 VMC、完整 RS，以及 history 8/16/32/64/128 和 TBPTT 4/8/16/24/32 扫描。",
    reproducibilityStatus: "部分可复现",
    implementation: ["给出 Mamba 宽度 256、state 16、卷积宽度 4、两层 temporal block、历史/TBPTT、top-8 与四个 prompt tokens。"],
    missing: ["未给出官方代码或 RS checkpoint 链接；真机任务数据、控制栈和完整经验库构建工具未公开。"],
    figureFile: "2608.15269-fig2.png",
    figureAlt: "Remember Smarter 的 Mamba 视觉历史压缩架构",
    figureCaption: "Figure 2 · 多视图 patch 的空间/时间 Mamba 压缩，以及动作 hidden state 通过残差 cross-attention 读取历史。来源：arXiv 原图。",
  },
  {
    title: "Robo-Dopamine 2.0: History-Conditioned and OOD-Aware Process Reward Modeling for Robotic Manipulation",
    arxivId: "2608.15680",
    url: "https://arxiv.org/abs/2608.15680",
    institutions: ["Peking University", "EvoPhys AI", "Beijing University of Posts and Telecommunications", "Tencent", "Renmin University of China", "Sun Yat-sen University"],
    signal: "让过程奖励同时读取执行历史，并把正常进度、外观鲁棒变化和真实失败放进带符号的统一进度空间。",
    tags: ["Process Reward Model", "OOD", "History"],
    classification: { research: "Memory", training: "RL", data: "数据增强", platforms: ["机械臂", "夹爪"] },
    detailAttributes: { memoryImplementation: "Context/Sequence", memoryHorizon: "观测 rollout 历史面板" },
    motivation: "静态前后帧会把相似画面对应的不同接触阶段混在一起，也难区分无害背景变化和错抓、未释放等真正失败。",
    methodSummary: "标准样本读取同 episode 历史，在线奖励读取实际 rollout 前缀，合成 OOD 查询读取与源成功轨迹对齐的 reference panels；signed progress space 再统一建模正进度、鲁棒分支和负进度。",
    architecture: "保留 pairwise reward 接口，视觉面板和任务文本进入通用 reward model；Signed-Hop curriculum 先学跨分支大步排序，再在 25% transition replay 下校准细粒度进度。",
    data: "从 RoboCasa、LIBERO、RoboTwin 2.0 和 AgiBot World 成功轨迹生成带来源记录的 OOD 编辑；reward model 使用两阶段共 400K signed pairs，另混合固定 QA200K。",
    experiments: "五类离线 VOC benchmark、面板布局与 replay 扫描；RoboTwin 三项 RL；真机双 Franka 的 Insert Square 每 trial 连续插入 4 次，每条件 200 在线 episodes、最终 20 trials。",
    novelty: "reference panels 将平均 VOC 0.967→0.986、OOD-robust VOC 0.906→0.958；下游 RoboTwin 平均 86.8%，真机 80 次插入中成功 71 次。",
    strengths: "历史、OOD 类型、signed curriculum 和 panel 布局均有消融；真机专门用重复插入制造视觉相似但累计进度不同的时间混淆。",
    limitations: "OOD 图像依赖 Gemini 编辑和严格来源校验；reward model 每配置只训练一次，8×H100 约 20 小时，跨相机/新物体的编辑伪影仍可能形成捷径。",
    transfer: "奖励模型的数据管线应保留源 episode、相机、frame 与编辑操作；在线时只能读真实 rollout 历史，不能把成功参考偷渡给部署模型。",
    technique: [
      "负向编辑包含错物体、空抓、未释放和目标替换；鲁棒编辑只改背景、干扰物或非目标颜色，并用源成功轨迹的同相机参考维持对象/阶段一致。",
      "signed progress 把成功路径、robust OOD 和 causal failure 分为共享坐标中的不同分支，pairwise loss 同时学习前进、回退与恢复。",
      "Signed-Hop 先采大跨度排序，再转向细粒度/零跨度样本；第二阶段保留 25% 大跳 replay，避免精调破坏全局顺序。",
    ],
    evaluation: [
      "reference panels 把平均 VOC 由 0.967 提至 0.986，OOD-robust 由 0.906 提至 0.958；历史对重复阶段尤其有效。",
      "相同 400K pair 预算下，25% replay 的 Signed-Hop 为 0.9872，matched-pool 随机训练为 0.9858；replay 比例 0.25 附近是浅峰值。",
      "RoboTwin 平均成功率 86.8%；真机每条件评测 20 trials×4 次插入，完整模型得到 71/80 次插入成功，并比较完整四连成功数。",
    ],
    comparison: "Robo-Dopamine 静态/历史版本、不同 OOD 分支、matched-pool shuffled、replay 比例、面板分辨率/数量，以及 event-sparse 与多种 reward shaping 条件。",
    reproducibilityStatus: "部分可复现",
    implementation: ["给出 400K+QA200K 数据预算、OOD 生成来源契约、8×H100 训练时间、RoboTwin 超参和真机 200 episodes/20 trials 协议。"],
    missing: ["未给出完整 OOD 数据、训练代码或 reward checkpoint 链接；图像编辑后端和 AgiBot World 数据访问会影响复现。"],
    figureFile: "2608.15680-fig1.png",
    figureAlt: "Robo-Dopamine 2.0 历史条件与带符号 OOD 进度空间",
    figureCaption: "Figure 1 · 成功、鲁棒 OOD、失败和通用视觉分支如何映射到 signed progress，并进入历史条件 GRM。来源：arXiv 原图。",
  },
  {
    title: "ViTaR: Visuo-Tactile Residual Adaptation for Foundation VLA Manipulation",
    arxivId: "2608.15816",
    url: "https://arxiv.org/abs/2608.15816",
    institutions: ["Beijing Institute of Technology"],
    signal: "不让触觉直接重写 VLA 动作，而是用局部效果证据选择并缩放有界 residual correction。",
    tags: ["Visuotactile", "Residual Adaptation", "VLA"],
    classification: { research: "VLA", training: "Post-training", modalities: ["Tactile"], platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://icr-lab.github.io/ViTaR" }],
    motivation: "基础 VLA 有语义动作先验，却无法感知接触建立、滑移和丢失；直接融合触觉或在线 RL 会让局部传感器无界改变全部动作维度。",
    methodSummary: "Effect-Guided Modeling 在恢复到同一接触状态的分支 rollout 中学习 residual 相对效果；Residual Action Modulation 决定保留 base action 或选 residual，并由实时触觉连续缩放。",
    architecture: "冻结 OpenVLA-OFT；marker motion 与 tactile image chunks 经 EGM 产生 adaptability/effect scores，RAM 输出离散 residual 选项和 gain，最终动作始终限制在 base action 附近。",
    data: "UniVTAC 每任务用 50 条轨迹微调 base VLA；ViTaR 每任务仅使用 20 组 restored decision branches。真机以 ExUMI 采集视觉、状态和 9DTact 触觉示范。",
    experiments: "UniVTAC 七项接触任务每方法/任务 100 episodes；RealMan RM-65B 真机做插孔、擦板和提瓶，每项每方法 20 次；另有 residual RL、EGM、RAM、触觉信息和 gain 消融。",
    novelty: "UniVTAC 平均 30.7%→61.3%；真机平均为 48.3%，比 frozen base 高 30.0 点、比 Tactile-VLA 高 15.0 点。",
    strengths: "分支数据从相同恢复状态比较，能隔离局部 correction 效果；模拟 700 次/方法和真机固定 20 次，组件与安全终止率消融完整。",
    limitations: "真机绝对成功率仍低于一半到六成，只有三项任务和一种触觉夹爪；性能上限受冻结 VLA 的语义动作方向约束。",
    transfer: "已有 VLA 可先冻结主干，把触觉限制为可审计的 residual selector/gain；必须同时统计恢复、保持正确动作和 unsafe termination。",
    technique: [
      "EGM 对同一 restored contact state 的 base/positive/negative residual branch 做 pairwise preference，避免跨接触状态比较不可校准的绝对 reward。",
      "RAM 结合 EGM 排序和 branch outcome evidence 选择 base 或 residual；marker motion 决定是否纠正，触觉摘要决定 residual 的连续幅值。",
      "base VLA 权重与动作方向保持冻结，residual 选项和 gain 均受边界限制；没有足够接触证据时直接执行 base action。",
    ],
    equations: [{ name: "有界残差动作", expression: "a_exec = a_VLA + g(z_tactile)·rₖ，0 ≤ g ≤ g_max", explanation: "rₖ 是离散 residual 选项；触觉只控制受限增益，不能生成任意新动作方向。" }],
    evaluation: [
      "UniVTAC 七项各 100 episodes，ViTaR 平均 61.3%，frozen OpenVLA-OFT 30.7%；所有任务都有提升，但 Lift Can 仍低于 π0.5。",
      "真机三项各 20 次：插孔 40%、擦板 40%、提瓶 65%，平均 48.3%；作者将其限定为有限 transfer evidence。",
      "固定 gain 使 61.3% 降至 45.0%，去 marker 状态使 paired recovery 0.79→0.46；完整 EGM 将 end-to-end 38.0%→61.3%。",
    ],
    comparison: "ACT、VITaL、ACT+UniVTAC、Tactile-VLA、π0.5、frozen OpenVLA-OFT，PPO-option/SAC-residual，以及 EGM、RAM、触觉和 gain 消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页和正文给出 50 条 base 轨迹、20 个 decision groups、真实硬件、每项 20 次和各 residual ablation 定义。"],
    missing: ["项目页未提供代码、分支数据和 checkpoint；ExUMI 恢复状态与 9DTact 标定细节仍需项目资源。"],
    figureFile: "2608.15816-fig2.png",
    figureAlt: "ViTaR 触觉效果建模与 residual action modulation 架构",
    figureCaption: "Figure 2 · 冻结 VLA、触觉特征、Effect-Guided Modeling、Residual Action Modulation 和有界 residual 输出。来源：arXiv 原图。",
  },
  {
    title: "Scaling Manual-Grounded Appliance Manipulation with Data Synthesis and Unified Planning",
    arxivId: "2608.15863",
    url: "https://arxiv.org/abs/2608.15863",
    institutions: ["Peking University", "Beihang University", "JD Technology"],
    signal: "把家电说明书变成层级状态图，系统生成部件定位、长时计划和受扰后的闭环调整数据，再训练统一规划模型。",
    tags: ["Manual Grounding", "Subtask Planning", "Data Synthesis"],
    classification: { research: "Subtask", training: "Post-training", data: "合成 / 仿真数据", platforms: ["机械臂", "夹爪"], deployment: "Sim2Real" },
    motivation: "家电操作依赖部件、参数和状态转移，通用 MLLM 即使能读说明书，也缺少覆盖多步骤计划和错误恢复的训练数据。",
    methodSummary: "MAGE 从说明书构建四层 Hierarchical Appliance Graph，再通过图遍历合成 task-plan 和 disturbance-recovery；AppliancePlan 在 Qwen2.5-VL-7B 上联合训练定位、规划、调整与三个辅助目标。",
    architecture: "视觉编码器冻结，手册页面、观察图和指令投影到 LLM token space，自回归输出 fully parameterized atomic actions；状态历史用于闭环修改后续计划。",
    data: "UseAppliance 覆盖 22 类家电，含 89K+ 部件框、53K+ 操作任务、33K+ 闭环调整步；任务平均 8.15 个 open-loop steps，核心标注人工双重验证。",
    experiments: "RealAppliance-Bench 的 grounding、open-loop、closed-loop 和 sequential 四轨；辅助目标逐项消融；Franka+双 RealSense 在微波炉等六类实物家电上每类 10 个任务。",
    novelty: "open-loop task success 为 31.36%，最佳 baseline 2.68%；sequential setting 为 28.07% 对 4.08%；真机平均 task success 40.00%，GPT-5 为 3.33%。",
    strengths: "数据生成结构、人工验证和三类监督一一对应；仿真基准之外还有六种实物家电、共 60 个任务，以及辅助目标消融。",
    limitations: "真机仍依赖每台家电的 CAD/URDF、FoundationPose、AnyGrasp 和预定义 atomic actions；40% 成功率说明低层执行与感知仍是主要瓶颈。",
    transfer: "长时 planner 的数据可从显式状态图生成，但应把 part grounding、参数关键步和 state judgment 分开监督，避免只学自然语言计划。",
    technique: [
      "HAG 从文档、页面、部件到状态转移逐层组织说明书；图遍历组合初末状态生成多步计划，并在执行序列中注入闭环中断。",
      "AppliancePlan 基于 Qwen2.5-VL-7B，主目标对应部件定位、open-loop planning 和 closed-loop adjustment。",
      "三个辅助目标分别做 manual-part 双向对齐、关键步骤动作预测和部件状态判断，直接加强定位、参数精度和恢复。",
    ],
    evaluation: [
      "RealAppliance-Bench open-loop completion/success 为 47.86%/31.36%，最佳 baseline 为 4.36%/2.68%；sequential 为 44.59%/28.07%。",
      "去掉 manual-part alignment 最伤定位，去掉 key-step prediction 最伤长时 sequential，去掉 state judgment 主要降低闭环调整。",
      "真机六类家电×10 任务，AppliancePlan completion/success 为 49.87%/40.00%，GPT-5 为 19.35%/3.33%，ApBot 为 9.12%/3.33%。",
    ],
    comparison: "GPT-5、Gemini 2.5 Pro、Qwen3-VL、RoboBrain 2.0、CheckManual/ApBot 等 MLLM/embodied planner，以及三个辅助目标消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["给出数据统计、HAG 生成流程、H200 训练 96 GPU-hours、batch 512、lr 10⁻⁵、冻结视觉编码器和真机系统。"],
    missing: ["未给出 UseAppliance 下载、代码或模型权重链接；真实部署需为每个家电准备 CAD/URDF 和 atomic-action executor。"],
    figureFile: "2608.15863-fig2.png",
    figureAlt: "MAGE 层级家电图与三类数据合成流程",
    figureCaption: "Figure 2 · 说明书收集与 HAG 标注，以及部件框、长时计划和中断恢复数据的生成链。来源：arXiv 原图。",
  },
  {
    title: "Tac4Loco: Learning Spatiotemporal Plantar Pressure Representations for Humanoid Locomotion",
    arxivId: "2608.15766",
    url: "https://arxiv.org/abs/2608.15766",
    institutions: ["The Hong Kong University of Science and Technology (Guangzhou)", "The University of Hong Kong", "Nanyang Technological University"],
    signal: "把足底阵列的空间压力形状和时间载荷转移直接送入人形 locomotion policy，补足视觉预判和本体感觉无法确认的真实支撑。",
    tags: ["Humanoid Locomotion", "Plantar Pressure", "Sim2Real"],
    classification: { research: "表征学习", training: "RL", modalities: ["Tactile", "State / Proprioception"], data: "合成 / 仿真数据", platforms: ["Humanoid"], deployment: "Sim2Real" },
    motivation: "深度/地形图只能在落脚前预测接触，本体感觉又只能间接推断；总力或压力中心会丢失边缘支撑、局部峰值和左右不对称。",
    methodSummary: "仿真与实物压力统一量化为保持拓扑的 ordinal bins；双分支 encoder 分别提取当前空间压力和压力—本体历史，并加入接触置信度条件的地面方向估计。",
    architecture: "actor 只看可部署的 IMU、关节、命令、足底矩阵、历史和地形方向；critic 额外读仿真 privileged state。PPO 输出 Unitree G1 的 29-D residual joint targets。",
    data: "MJLab 中每脚以 60 个接触球对应真实 taxel，训练随机化传感频率、灵敏度、噪声和 dropout；地形覆盖平地、起伏、15°/20°坡、随机高差和 V 型沟。",
    experiments: "仿真报告 survival、速度/方向跟踪和支撑指标，并消融 pressure encoder 与 terrain estimate；真机覆盖坡面、沟、边缘和刚性切换，另零样本测试泡沫与碎石。",
    novelty: "仿真随机高差 survival 71.7%→96.5%，坡面 22.0%→77.9%；未训练的泡沫和碎石上也能部署，碎石连续测试约五分钟。",
    strengths: "sim-to-real 传感表示明确，对比同 reward 的开源 proprio-only baseline；空间/时间压力与地形方向分别消融，并测试未见柔性/颗粒地形。",
    limitations: "真机表中部分场景重复次数较少，碎石主要是连续演示；没有视觉预瞄，陡峭地形仍只能在接触后反应。",
    transfer: "足底触觉不应只压成总力；保持税点拓扑、同时记录载荷转移，并让接触置信度决定何时相信运动学估计。",
    technique: [
      "把仿真接触力和真实阵列读数映射到相同 ordinal load bins，避免要求两域绝对压力精确标定。",
      "空间分支以当前本体状态 query 压力 patch；时间分支读取 21-D 压力描述符与 16-D 运动上下文的历史。",
      "足底活跃点数量和分布形成支撑置信度，只在可靠接触时更新局部地面方向；actor-critic 再融合该 cue 与压力 latent。",
    ],
    evaluation: [
      "Tac4Loco 在平地、起伏和 V 沟仿真中保持 100% survival；随机高差 96.5% 对 71.7%，坡面 77.9% 对 22.0%。",
      "去 terrain estimate 主要损伤连续坡面速度与推进，去 pressure encoder 主要损伤 V 沟、边缘和不对称支撑，验证两者职责不同。",
      "真机在坡、沟、边缘和泡沫上优于 proprio-only；泡沫与碎石未出现在训练中，但部分真机场景没有大样本统计。",
    ],
    comparison: "Unitree 官方 proprio-only policy、去 pressure encoder、去 terrain estimate；所有策略共享 reward、curriculum 和非视觉观察。",
    reproducibilityStatus: "部分可复现",
    implementation: ["给出 Unitree G1/MJLab、每脚 60 taxels、50 Hz policy/200 Hz PD、29-D 动作、地形范围、传感随机化和指标。"],
    missing: ["论文表示将公开代码与配置，但正文未给项目仓库；真实鞋垫结构、标定和完整逐场景次数仍不足。"],
    figureFile: "2608.15766-fig2.png",
    figureAlt: "Tac4Loco 足底压力时空编码与 Sim2Real 策略架构",
    figureCaption: "Figure 2 · 仿真训练、压力矩阵/历史/地形估计、双分支 encoder 和实物鞋垫部署流程。来源：arXiv 原图。",
  },
  {
    title: "GAINS: Leveraging Inconsistent Human Intervention Signals in Reinforcement Learning",
    arxivId: "2608.15707",
    url: "https://arxiv.org/abs/2608.15707",
    institutions: ["Beijing Institute of Technology", "Beijing Innovation Center of Humanoid Robotics", "City University of Hong Kong", "Nankai University"],
    signal: "把人工介入的时间抖动视为 return distribution，而不是精确二元标签，再用下尾分位数选择更稳妥的在线动作。",
    tags: ["Human-in-the-loop", "Distributional RL", "Pessimistic Exploration"],
    classification: { research: "其他", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://gains-hil.github.io/" }],
    motivation: "30 Hz 控制下，人对同一失败视频的介入时刻可相差几十帧；标量 Q 把这种多峰回报压成均值，容易继续尝试可能触发介入的动作。",
    methodSummary: "多 critic quantile network 学习稀疏成功、介入惩罚和安全事件构成的回报分布；截去高估目标，用 reward-scaled quantile Huber 传播稀疏成功，再从候选动作的低分位均值做 pessimistic selection。",
    architecture: "连续 6-DoF 末端由 distributional actor-critic 控制，夹爪由独立 Double DQN；异步收集策略动作和人类遥操作，所有 transition 进入统一 replay。",
    data: "先用 100 个失败视频×两名操作者×五次标注量化介入不一致；HIL-RM 四项仿真任务在线收集，两个真机任务各从 20 条离线示范开始。",
    experiments: "仿真三种子、每 checkpoint 100 次自主评测，另做外扰 recovery 和四项组件消融；UR5 Pick-Spoon、Franka Insert-USB 真机三种子在线训练 35–60 分钟。",
    novelty: "GAINS 相对 RLIF 平均成功率高约 22%，外扰 recovery 比 HIL-SERL 高最多 43%；两项真机均在 35–60 分钟内超过 90% 近期成功率。",
    strengths: "先实测介入时序噪声，再以统一仿真/真机管线对照五类方法；报告成功、安全违规、介入比例、episode 长度和恢复。",
    limitations: "真机成功率按最近 10 个训练 episode 计算而非独立大规模测试；介入决定仍由人给出，分位阈值需要按任务调节。",
    transfer: "若人工信号只有介入时刻而动作质量不稳定，可把它作为不确定回报的一部分；部署应同时跟踪 lower-tail value、人工负担和安全违规。",
    technique: [
      "TQC 风格 critic 预测一组 return quantiles 并截去最大的 target atoms，降低真机低吞吐、高更新比造成的 Q 过估计。",
      "quantile Huber 的阈值 κ 设为成功奖励 R，使稀疏大正回报在合理区间保持二次梯度，不被 κ=1 过早削弱。",
      "每步从 actor 采样 N 个候选，只用低于 τ_th 的 quantile 均值估值，执行下尾回报最好的动作。",
    ],
    equations: [{ name: "悲观动作选择", expression: "a* = argmaxₐ Mean{Zτ(s,a) | τ ≤ τ_th}", explanation: "不是最大化期望 Q，而是比较每个候选动作回报分布的下尾均值。" }],
    evaluation: [
      "Arrange-Boxes 成功率 94%，较 RLIF/HIL-SERL/AWAC/Sirius 分别高 44/67/63/75 点，并在该实验中没有安全违规。",
      "外扰评测对最终 checkpoint 各做 100 trials，GAINS 平均 recovery 80.3%，比 HIL-SERL 高 43 点。",
      "去 pessimistic exploration 成功率降 13.4 点并多 28 次安全违规；去 reward-scaled Huber 降 30.7 点；真机两任务三种子在 35–60 分钟超过 90%。",
    ],
    comparison: "RLIF、HIL-SERL、AWAC、IBRL、Sirius，以及去 distributional Q、去 pessimistic exploration、去 reward-scaled Huber 和 quantile threshold 扫描。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页与附录给出 HIL-RM、Python/PyTorch/LeRobot 版本、奖励、critic/actor、真实硬件、20 demos 和主要超参。"],
    missing: ["项目页未提供训练代码与 HIL-RM 环境链接；真机独立评测样本和跨操作者泛化仍有限。"],
    figureFile: "2608.15707-fig2.png",
    figureAlt: "GAINS 分布式 Q 学习与悲观探索框架",
    figureCaption: "Figure 2 · 不一致人工介入、quantile return distribution、截断 critic 与 lower-tail action selection。来源：arXiv 原图。",
  },
  {
    title: "ReForce: Learning Force-aware Retargeting for Dexterous Manipulation",
    arxivId: "2608.15560",
    url: "https://arxiv.org/abs/2608.15560",
    institutions: ["University of California San Diego"],
    signal: "在人手运动 retargeting 之后再学习一个闭环 residual，用机器人指尖实测力去追踪人类示范的接触意图。",
    tags: ["Force-aware Retargeting", "Dexterous Hand", "Human Demonstration"],
    classification: { research: "表征学习", training: "BC", modalities: ["Force / Torque", "Tactile"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "灵巧手"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://wuyuhang-eai.github.io/reforce/" }],
    motivation: "只匹配关节或指尖位置不能保证机器人建立相同接触；物体几何、手指顺应性和动力学差异会让重放出现漏接触、挤压或滑脱。",
    methodSummary: "通用 force tracker 在大规模仿真手—物交互上学习：给定参考关节和未来指尖力、当前关节和实测力，输出受限 joint residual；它可在线接入遥操作，也可修正离线人类轨迹。",
    architecture: "人类手套/腕部 motion 先映射为 XHand joint reference，FSR 力映射到对应机器人指尖；ACT 预测 motion+force chunks，ReForce 作为闭环执行层累计 residual 并裁剪到硬件关节限位。",
    data: "仿真以 Dex1B 物体/抓取生成交互并加入 joint/force noise、dropout、pose drift 和 force residual；真机每任务约 30–40 条人类示范，另用固定轨迹做五次重放对照。",
    experiments: "xArm+12-DoF XHand 完成纸杯侧/顶抓和夹钳操作；比较 replay、手工 admittance、ACT reference 与 ReForce；仿真消融三种子、14,605 个 held-out episodes。",
    novelty: "ReForce 在纸杯重放上取得最低力误差，在学习参考的纸杯任务上同时提高 force-safe success、减少严重漏接触；夹钳上接触更完整，但不如 admittance 的安全成功率。",
    strengths: "不只报任务成败，还给指尖力误差、过力、严重漏接触和活跃手指数；真实结果保留方法失利的夹钳反例，仿真消融规模大。",
    limitations: "ACT reference 不看视觉，只看 joint history 和 task phase；ReForce 只建模法向力，没有剪切、滑移和接触分布，真机任务数量小。",
    transfer: "human-to-robot 数据管线可把运动 retargeting 与接触 retargeting 分开；对纸杯、工具等任务，force-safe success 比单纯抓起率更能发现策略问题。",
    technique: [
      "仿真轨迹构造未来窗口 motion/contact targets，force tracker 读取当前关节与指尖力，对 kinematic reference 预测受限 residual。",
      "人类 FSR 与 XHand tactile 都校准到牛顿，ACT 从约 30–40 条示范预测 joint+force reference chunks；真实力只进入 ReForce 闭环。",
      "pose-drift augmentation 从低力状态生成恢复样本，force-residual augmentation 改变期望接触；执行命令累积后按 joint limits 裁剪。",
    ],
    equations: [{ name: "力感知重定向", expression: "q_cmd,t+1 = Clip(q_ref,t+1 + Δqθ(q_t,F_t,q_ref,F_ref), q_min, q_max)", explanation: "学习 residual Δq 使机器人当前实测力 F_t 追踪示范接触目标 F_ref，同时保持关节可执行。" }],
    evaluation: [
      "固定纸杯轨迹的 replay/admittance/ReForce 各做五次，ReForce 在侧抓和顶抓均有最低平均绝对力误差。",
      "学习参考下，纸杯 ReForce 的安全成功、力误差、严重漏接触和活跃手指数均最好；夹钳则由 admittance 获得最高安全成功，ReForce 有 4 次过力。",
      "仿真三种子在相同 14,605 episodes 上比较数据增强和输入；正文给出均值与 sample std，验证 pose drift、force residual 和历史输入作用。",
    ],
    comparison: "直接 joint replay、手工 admittance controller、ACT reference policy、ReForce，以及仿真训练数据组成和输入表示消融。",
    reproducibilityStatus: "部分可复现",
    implementation: ["项目页与附录给出 xArm/XHand/FSR、ACT 数据量、AdamW lr 10⁻³、batch 1024、20 epochs、力阈值和评测指标。"],
    missing: ["项目页未提供完整训练代码、Dex1B 派生数据和 checkpoint；真实力标定与 XHand 低层接口需自行复现。"],
    figureFile: "2608.15560-fig1.png",
    figureAlt: "ReForce 人类运动接触参考到机器人力感知 residual 的流程",
    figureCaption: "Figure 1 · 人类运动/触觉参考、基础 retargeting、ReForce residual 和机器人纸杯/夹钳执行。来源：arXiv 原图。",
  },
];

export const paperDaily20260817: Paper[] = entries.map(makePaper);
