import type { Paper } from "./site-data";

export const paperDaily20260629: Paper[] = [
  {
    rank: 1,
    title: "TAP-VLA: Tactile Annotation Prompting for Vision Language Action Models",
    arxivId: "2606.29089",
    url: "https://arxiv.org/abs/2606.29089",
    institutions: ["University of Michigan Robotics", "University of Michigan CSE"],
    signal: "把触觉剪切场直接画进 VLA 已经使用的多视角 RGB，不增加触觉编码器也能改善接触操作",
    tags: ["Tactile Prompting", "VLA", "Contact-rich"],
    classification: { research: "VLA", training: "Post-training", modalities: ["Tactile"], data: "数据增强", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://tap-vla.github.io/" }],
    motivation: "预训练 VLA 缺少力觉，但另加触觉分支会改变输入分布并削弱视觉语言预训练；作者希望在不改主干结构的前提下引入接触信息。",
    methodSummary: "从两侧视触觉图像估计 marker optical flow，将剪切向量变换到指尖坐标系、投影到各相机视角，再把彩色向量叠加到 RGB 后交给原 VLA。",
    architecture: "底座保持原多视角 RGB、语言、关节状态到动作块的映射；唯一新增的是确定性的 tactile-to-visual annotation 前处理，VLA 内部没有额外触觉 encoder。",
    optimization: "以标注后的图像微调预训练 VLA，使用示范学习；没有触觉预训练或 RL。",
    data: "四项真实接触任务，每项 100 条示范，约 10 Hz 采集；任务涉及质量判断、质心平衡、齿轮装配和插头插接。",
    experiments: "四项任务每种方法共 120 次测试，TAP-VLA 总成功率 78%，视觉-only、原始触觉拼接和学习式触觉 encoder 均低于 50%。",
    novelty: "相对新增触觉 token 或独立编码器，TAP-VLA 把力觉转换为预训练视觉主干熟悉的空间标注，代价小且可解释。",
    strengths: "真机任务覆盖质量、质心和接触对齐，且同时比较视觉-only、原始触觉与学习式融合，能较直接判断收益来自哪种接口。",
    limitations: "需要相机与指尖传感器标定；二维箭头只能表达选定的剪切信息，跨触觉硬件、软材料与更长任务的泛化尚未验证。",
    transfer: "适合已有 VLA 不便改结构、但可以增加 GelSight/视触觉传感器的场景；也可把力矩、接触点或滑移估计渲染为视觉提示。",
    experimentDetails: [{ title: "四项真机接触任务", setup: "双指视触觉夹爪、多视角相机；每项 100 条示范并独立测试 30 次。", comparisons: "视觉-only VLA、原始触觉输入、学习式触觉 encoder 与 TAP-VLA。", results: ["总体成功率 78%，其余对照均低于 50%。", "在基线接近随机猜测的质量/质心任务上仍保持可用表现。", "接口不改变主干，因此新增推理开销主要来自剪切场计算和绘制。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["marker optical flow → 指尖 3D 剪切向量 → 多视角投影 → RGB overlay", "预训练 VLA 上的示范微调"], verifiedResources: ["项目页提供视频；正文给出投影公式、任务定义、示范量和对照。"], missing: ["完整训练代码、标定脚本和真机数据未在正文中确认公开。"] },
    deepDive: { lead: "这篇工作把‘新增模态’改写成‘视觉提示’，重点不是更大的融合网络，而是避免破坏预训练输入接口。", sections: [{ title: "技术细节", paragraphs: ["左右触觉图像先计算 marker 位移场，再按指尖姿态变换为三维剪切方向。相机投影矩阵把这些向量映射到每个 RGB 视角，颜色区分左右指和方向，VLA 因而能在原图上同时看到物体、夹爪和接触载荷。", "其策略形式仍是 VLA({Î_t^i}, θ_t, l)→a_t:t+H，只是 Î 是带触觉箭头的图像。这种设计保留了预训练网络的 token 类型和 action head，减少小规模触觉微调造成的分布跳变。"] }], experimentReading: ["78% 是四任务汇总结果；它说明这种接口优于所测融合方式，但不能等同于对任意传感器或任意 VLA 都成立。"], reflections: ["如果现有策略接近目标但在接触阶段失败，先尝试可视化物理提示，可能比重做多模态 backbone 更容易验证。"] },
    figures: [{ src: "/report-assets/2026-06-29/2606.29089-overview.png", alt: "TAP-VLA 将触觉剪切场投影到多视角 RGB 后输入预训练 VLA 的流程", caption: "Figure 1 · TAP-VLA 的触觉视觉标注流程。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 2,
    title: "Event-VLA: Action-Conditioned Event Fusion for Robust Vision-Language-Action Model",
    arxivId: "2606.29384",
    url: "https://arxiv.org/abs/2606.29384",
    institutions: ["ShanghaiTech University", "HKUST (Guangzhou)", "University of Michigan", "Shanghai Jiao Tong University"],
    signal: "用动作 query 选择性读取事件相机 token，在低照与近暗环境中补足 RGB VLA 的运动信息",
    tags: ["Event Camera", "Robust VLA", "Low-light"],
    classification: { research: "VLA", training: "Post-training", modalities: ["其他模态"], platforms: ["机械臂", "夹爪"] },
    motivation: "RGB-centric VLA 在低照、近暗和运动模糊下容易失去对象与动作线索，直接把事件特征并入全局 token 又可能干扰预训练语义。",
    methodSummary: "将事件流编码为 PREI 表征，由可学习 action queries 从 VLA 语义中提取任务信息，再通过 gated cross-attention 只把与动作有关的事件 token 路由到 action representation。",
    architecture: "RGB/语言路径保持原 VLA；事件编码器形成稀疏时空 token，query routing 位于动作分支，future-event 辅助目标约束其学习。",
    optimization: "在 LIBERO 与合成低可见度 LIBERO-Cross 上后训练；真实 Franka 四任务收集 80 条示范并微调。",
    data: "LIBERO 四套基准及 LIBERO-Cross 三档照度；真机使用 Franka、ZED、Orbbec 与 DAVIS 事件相机，四任务共 80 条示范。",
    experiments: "正常 LIBERO 平均 96.5%；严重低照下 95.6%，而 π0、OpenVLA-OFT、MM-ACT 为 61.9%、61.2%、69.6%。真机正常/低照/近暗平均 65.0%。",
    novelty: "不是把事件 token 与 RGB 全量拼接，而是让动作 query 决定何时、从哪里读取事件残差。",
    strengths: "500 次/子基准的仿真评测、表示与接口消融、延迟统计和三档真机照度形成较完整证据链。",
    limitations: "真机每任务每照度仅 10 次，近暗成功率仍为 52.5%；新增事件相机、标定和同步提高部署复杂度。",
    transfer: "适合光照不可控、快速运动或 RGB 暂时失真的操作；action-query 路由也可迁移到力觉、深度或音频残差。",
    experimentDetails: [{ title: "低可见度与真机部署", setup: "LIBERO-Cross 每任务 50 次、每子基准 500 次；Franka 四任务在正常、低照和近暗下各 10 次。", comparisons: "π0、OpenVLA-OFT、MM-ACT，以及事件表示、统一编码、adapter 与 query routing 消融。", results: ["LL-Severe 平均 95.6%，no-event 为 60.6%。", "query routing 延迟增量约 2.16 ms，统一事件编码增量约 62.87 ms。", "真机平均 65.0%，其中近暗 52.5%，高于两项 RGB 基线的 15.0% 与 12.5%。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["PREI 事件表征", "action-query gated cross-attention", "future-event 辅助监督"], verifiedResources: ["正文给出评测次数、硬件、主要表格和接口消融。"], missing: ["项目代码/权重与真机数据公开状态未在首版正文中确认。"] },
    deepDive: { lead: "Event-VLA 把事件相机定位为 RGB 失效时的动作残差信号，而不是第二套全局语义视觉。", sections: [{ title: "技术细节", paragraphs: ["action queries 先从 RGB-language VLA 中取得当前任务语义，再跨注意力读取事件 token；门控控制事件对动作表示的贡献。这样事件流主要回答‘哪里正在变化、接触相关运动是否发生’，不会取代 RGB 的对象语义。", "future-event 监督迫使接口保留对接下来动作有用的动态线索；消融显示 PREI 与 query routing 都比简单 time surface 或统一事件编码更有效。"] }], experimentReading: ["仿真严重低照收益很大，真机近暗仍明显更难，说明事件信息能补强但不能完全代替可见光语义。"], reflections: ["部署前应把相机同步、事件噪声和静止阶段的无事件输入作为独立失效模式测试。"] },
    figures: [{ src: "/report-assets/2026-06-29/2606.29384-overview.png", alt: "Event-VLA 的 RGB 语言主干与 action-query 事件路由结构", caption: "Figure 1 · Event-VLA 的动作条件事件融合框架。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 3,
    title: "WARP-RM: A Warp-Augmented Relative Progress Reward Model for Data Curation",
    arxivId: "2606.28320",
    url: "https://arxiv.org/abs/2606.28320",
    institutions: ["University of California, Berkeley", "Stanford University", "XDOF"],
    signal: "用时间扭曲自监督学习带符号的相对进度，再按局部 advantage 加权行为克隆，保留恢复动作同时压低停顿和倒退",
    tags: ["Data Quality", "Reward Model", "Imitation Learning"],
    classification: { research: "表征学习", training: "BC", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://uynitsuj.github.io/warp-rm/" }],
    motivation: "遥操作数据包含停顿、回退和恢复；整条轨迹过滤会丢掉有价值片段，绝对进度标签又容易把执行速度误当成质量。",
    methodSummary: "对成功示范做变速和反向 time warp，训练 WARP-RM 预测帧间有符号相对进度；重叠窗口聚合成稠密信号，再由 WARP-BC 提高高 advantage 动作块权重。",
    architecture: "视觉相对进度模型接收帧对/窗口，输出归一化时间差；策略端无需增加推理模块，只在 BC loss 中使用离线计算的 chunk 权重。",
    optimization: "奖励模型完全自监督；策略仍是行为克隆，只改变样本/动作块权重，不做在线 RL。",
    data: "真实双臂随机皱褶 T 恤折叠数据，并按 episode length 构造不同质量训练集；另有真实与可复现仿真的 bottle-in-bin。",
    experiments: "低质量数据比例上升时 WARP-BC 仍为 19/20，vanilla BC 降至 2/20，吞吐最高提升约 18 倍；瓶子任务采用配对显著性检验。",
    novelty: "把进度建模从绝对时间位置改为可正可负的相对变化，并把信号用于动作块级加权而非整条轨迹丢弃。",
    strengths: "长时形变物操作、混合质量曲线、真实+仿真复核和统计检验都与数据筛选主张直接对应。",
    limitations: "只从成功示范构造监督，时间变化仍不一定等价于任务价值；跨任务 reward model 泛化尚不清楚。",
    transfer: "可先给现有日志离线打进度/倒退标签，再用于采样、加权或诊断，而不必修改部署策略。",
    experimentDetails: [{ title: "混合质量长时操作", setup: "双臂从随机皱褶初态折叠 T 恤，并逐步放宽 episode-length 筛选阈值。", comparisons: "vanilla BC、绝对进度 reward、轨迹级筛选与 WARP-BC。", results: ["最宽松数据设置下 WARP-BC 19/20，vanilla BC 2/20。", "通过减少停顿与失败恢复后的重复动作，任务吞吐最高约 18×。", "bottle-in-bin 的真实与仿真结果在成功率、速度和吞吐上方向一致。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["time-warp augmentation", "signed relative progress aggregation", "chunk-level advantage-weighted BC"], verifiedResources: ["项目页存在；作者承诺/提供仿真代码和评测 artifacts。"], missing: ["真实双臂数据与硬件复刻仍有成本。"] },
    deepDive: { lead: "WARP-RM 的关键是区分‘慢但仍前进’和‘真正倒退/停滞’，再把局部判断用于训练权重。", sections: [{ title: "技术细节", paragraphs: ["时间扭曲产生不同播放速度和反向片段，模型学习两帧之间的归一化有符号时间差。多个重叠窗口的预测被聚合，形成每帧进度变化 v̂_t；动作块 advantage 则由窗口内 v̂_t 累加。", "WARP-BC 不删除整个低质量 episode，而是上调有效推进与恢复片段、下调犹豫和回退。这对形变物长任务尤其重要，因为一次失误后的恢复可能仍是部署时需要的行为。"] }], experimentReading: ["19/20 对 2/20 发生在特定质量扩展协议中；最有价值的是随数据质量下降的稳定性，而不是单一最高成功率。"], reflections: ["数据筛选系统最好同时保存原始轨迹、局部权重和失败阶段，便于检查 reward 是否误杀必要的探索或恢复。"] },
    figures: [{ src: "/report-assets/2026-06-29/2606.28320-overview.png", alt: "WARP-RM 在 T 恤折叠轨迹上预测带符号相对进度并用于数据加权", caption: "Figure 1 · WARP-RM 的稠密进度信号示例。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 4,
    title: "Learning Transferable Dynamics Priors from Action to World Modeling",
    arxivId: "2606.29501",
    url: "https://arxiv.org/abs/2606.29501",
    institutions: ["Fudan University", "Shanghai Innovation Institute", "Shanghai Jiao Tong University", "McGill University"],
    signal: "在 210 万+轨迹和 20+本体上预训练动作条件多视角世界模型，再分别迁移到策略评测和视频—动作联合策略",
    tags: ["World Model", "Pre-training", "Cross-Embodiment"],
    classification: { research: "WM", training: "Pre-training", data: "跨本体数据", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "GitHub", url: "https://github.com/LogosRoboticsGroup/A2World" }],
    motivation: "机器人 world model 常按单任务训练，难判断其动力学知识能否像视觉预训练一样迁移到新的模拟评测或策略。",
    methodSummary: "A2World 先学习初始多视角图像+未来动作块到未来多视角视频，再把同一权重适配为长时自回归 A2World-sim 和视频—动作联合 A2World-policy。",
    architecture: "DiT 在多视角 latent 中注入动作条件并维持跨视角时空一致；sim 版本接收连续动作滚动预测，policy 版本在语言条件下同时生成未来视频和动作。",
    optimization: "大规模动作条件 world-model 预训练后进行两条任务特定迁移；policy 分支使用视频预测与动作预测联合目标。",
    data: "210 万+机器人操作轨迹、20+本体；论文还收集五项真实任务数据用于策略与世界模型适配。",
    experiments: "从生成质量、长时 rollout 的策略排序，以及真实任务中的联合视频—动作策略和数据增强三个层面评估迁移。",
    novelty: "强调一个 action-conditioned world model checkpoint 可同时服务模拟器与策略，而不是为每个下游用途从头训练。",
    strengths: "数据规模、跨本体覆盖、两类下游适配和真实任务使‘可迁移动力学先验’比单一视频指标更可信。",
    limitations: "210 万轨迹的数据组成与计算成本很高；生成视频更好不必然保证策略排序或闭环控制可靠。",
    transfer: "可借鉴统一 base world model + 轻量下游适配的组织方式，并优先验证 rollout 对策略相对优劣的保持能力。",
    experimentDetails: [{ title: "动力学先验的两条迁移路径", setup: "多视角动作条件预训练后，分别适配长时模拟器与视频—动作联合策略，并在五项真实任务中检查。", comparisons: "从头训练/普通视频预训练、不同 world-model 初始化与不使用视频联合目标的策略。", results: ["A2World-sim 用长时 rollout 支持策略评测与 what-if 分析。", "A2World-policy 复用同一权重，在真实任务中联合预测视觉未来和动作。", "论文同时检查生成、策略排序和下游成功，避免只报告视觉分数。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["multi-view action-conditioned DiT", "A2World-sim autoregressive adaptation", "A2World-policy joint video-action head"], verifiedResources: ["GitHub 已公开；正文列出数据规模、迁移分支和主要实验。"], missing: ["完整 210 万轨迹和同等预训练算力不易复刻。"] },
    deepDive: { lead: "A2World 把动作条件视频预训练视为机器人动力学的公共底座，再问同一先验能否支持评测与控制。", sections: [{ title: "技术细节", paragraphs: ["base 模型从初始多视角帧和未来 action chunk 预测下一段多视角视频，跨视角一致性要求模型学习机器人—物体交互而非单视角外观。A2World-sim 增加历史帧并自回归延长 horizon；A2World-policy 则把语言、视觉生成和动作生成接在同一表示上。", "这种迁移设计的价值在于对照：若只有视频分数提高而策略排序或真实控制没有同步改善，就不能把生成模型当作可靠 dynamics prior。"] }], experimentReading: ["论文的证据面较广，但公开复现最现实的路径是使用权重做下游适配，而不是重建 210 万轨迹预训练。"], reflections: ["world model 评测应单列 action fidelity、长时漂移和 policy ranking，而不只看 FID/PSNR。"] },
    figures: [{ src: "/report-assets/2026-06-29/2606.29501-overview.png", alt: "A2World 大规模预训练并迁移到 A2World-sim 和 A2World-policy 的框架", caption: "Figure 1 · A2World 的预训练与两条先验迁移路径。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 5,
    title: "Human2Any: Human-to-Robot Transfer via Constraint-Aware Compositional Planning",
    arxivId: "2606.28813",
    url: "https://arxiv.org/abs/2606.28813",
    institutions: ["Georgia Institute of Technology", "NVIDIA"],
    signal: "从人类视频学习物体—物体交互运动，再用抓取、碰撞和运动学约束适配不同机器人",
    tags: ["Human Video", "Compositional Planning", "Cross-Embodiment"],
    classification: { research: "Subtask", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "Humanoid", "轮式底盘", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://human2any.github.io/" }],
    motivation: "人类视频包含丰富交互，但手臂形态、场景几何和可达性与机器人不同，直接模仿人体轨迹容易得到不可执行动作。",
    methodSummary: "学习与本体无关的 object-object interaction motion；测试时把该先验与抓取可行性、碰撞、运动学和运动规划约束组合，得到机器人轨迹。",
    architecture: "交互先验生成工具物体相对目标物体的运动；约束推理选择抓取和可行路径，传统 motion planner 将对象运动实现为 Franka 或 RBY-1 的关节轨迹。",
    optimization: "交互先验从人类视频学习，部署时通过采样/引导与约束组合，不需要在目标任务环境中收集真实机器人训练示范。",
    data: "人类物体交互视频；真实评测覆盖 Franka 桌面与 RBY-1 移动 humanoid，多种任务和场景变化。",
    experiments: "在两类真实本体上与机器人示范策略及无约束交互先验比较，重点检查新场景、不同机器人和目标任务无真实训练数据。",
    novelty: "转移的是对象间期望变化而非人体手轨迹，并在推理时显式加入机器人可行性。",
    strengths: "同一先验跨固定机械臂和移动 humanoid，且不依赖目标任务真实机器人训练数据，直接检验跨本体主张。",
    limitations: "依赖对象感知、抓取候选与运动规划模块；感知或几何约束错误会成为瓶颈，端到端接触反馈有限。",
    transfer: "适合工具使用、搬运和对象关系明确的任务；可把对象交互先验作为 VLA 的高层 subgoal，而非直接替换低层控制。",
    experimentDetails: [{ title: "跨本体真实操作", setup: "Franka 桌面与 RBY-1 移动 humanoid，在目标任务环境不使用真实机器人训练示范。", comparisons: "无约束生成、机器人示范策略与不同可行性约束组合。", results: ["对象交互先验可在两种本体上复用。", "抓取、碰撞与运动学约束对把人类动作变成可执行机器人轨迹是必要组件。", "实验强调新场景和上下文变化，而不是单一固定初始化。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["object-object interaction prior", "constraint-aware sampling/steering", "grasp and motion planning"], verifiedResources: ["项目页提供任务视频；正文描述两套真实平台与对照。"], missing: ["完整人类数据、感知/规划栈和机器人配置公开程度仍有限。"] },
    deepDive: { lead: "Human2Any 把‘模仿人’改成‘复现对象关系’，再让机器人约束决定具体怎么动。", sections: [{ title: "技术细节", paragraphs: ["先验只描述工具对象相对目标对象的运动，因此不绑定人的关节或手指。测试时，候选对象运动被抓取稳定性、逆运动学和碰撞检测筛选，再由规划器生成本体特定轨迹。", "这种分层让同一个人类知识能迁移到 Franka 和 RBY-1，但也把性能上限交给对象追踪、抓取生成和几何模型；它更像可组合操作系统而不是单个端到端 policy。"] }], experimentReading: ["无目标任务机器人示范是强约束，但真实任务数量和模块依赖决定了结论应理解为‘可行的迁移路径’，而非通用零样本操作。"], reflections: ["对长任务可把 interaction prior 产出的对象轨迹离散成 subgoal，再交给现有 VLA 执行并用视觉/触觉闭环修正。"] },
    figures: [{ src: "/report-assets/2026-06-29/2606.28813-overview.png", alt: "Human2Any 从人类视频学习对象交互先验并与机器人可行性约束组合", caption: "Figure 1 · Human2Any 的对象中心人到机器人迁移。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 6,
    title: "S²-VLA: State-Space Guided Vision-Language-Action Models for Long-Horizon Manipulation",
    arxivId: "2606.27872",
    url: "https://arxiv.org/abs/2606.27872",
    institutions: ["East China Normal University", "Shanghai Jiao Tong University"],
    signal: "用状态空间 belief 跟踪任务阶段，动态调节视觉、任务意图和动作历史的融合权重",
    tags: ["State Space", "Long-Horizon", "Adaptive Attention"],
    classification: { research: "Memory", training: "Post-training", modalities: ["State / Proprioception"], platforms: ["机械臂", "夹爪"] },
    detailAttributes: { memoryImplementation: "Context/Sequence：状态空间 belief state", memoryHorizon: "随控制步递推的任务阶段状态" },
    motivation: "长任务各阶段需要的信息不同，静态融合会在抓取、搬运和放置之间使用相同权重，误差随阶段累积。",
    methodSummary: "SSGAA 递推维护 belief state，并为视觉特征、任务意图和动作序列生成动态 gate，使 policy 随任务进度切换关注点。",
    architecture: "2B VLA 主干中在选定中层插入 state-space guided adaptive attention；状态递推提供历史，gate 调制三路特征。",
    optimization: "在 LIBERO 后训练并对 gating 层位置、全层 gating 和去除 state guidance 做消融；另在 SimplerEnv 与真实 ALOHA 评测。",
    data: "LIBERO、SimplerEnv-Bridge；真实 ALOHA 双臂四任务，包括 pick-place、stacking、桌面整理和筷子双臂交接。",
    experiments: "LIBERO 四套平均 98.2%，Long 为 96.4%；SimplerEnv 四任务平均 78.1%。真实 ALOHA 报告优于 ACT 和 π0-FAST，但正文图示未给出完整试验次数。",
    novelty: "把历史压缩成可递推 belief，并只在合适层动态融合，而不是无差别增加视觉帧或全层 gate。",
    strengths: "仿真覆盖长任务与近真实桥接环境，且 state/gate 位置消融显示中层单点注入比全层更好。",
    limitations: "真机协议和置信区间披露不足；LIBERO 高分接近饱和，难单独证明对开放场景长时泛化。",
    transfer: "可将 belief state 替换为接触阶段、subtask 或失败恢复状态，用于控制已有 VLA 的多源特征权重。",
    experimentDetails: [{ title: "长时基准与状态消融", setup: "LIBERO、SimplerEnv-Bridge 与 ALOHA 双臂四任务；推理约 7 GB VRAM。", comparisons: "主流 VLA、MemoryVLA，以及无 gate、全层 gate、不同层 gate、无 state guidance。", results: ["LIBERO 平均 98.2%，Long 96.4%。", "SimplerEnv-Bridge 四任务平均 78.1%。", "第 12 层 gate 为 96.4%，无 gate 为 95.0%，全层 gate 反而为 94.4%。"] }],
    reproducibilityDetails: { status: "信息不足", implementation: ["state-space belief recursion", "three-source adaptive gate", "mid-layer SSGAA"], verifiedResources: ["正文给出主要结构、4×H100 训练和 7 GB 推理显存。"], missing: ["代码/权重、完整真机次数与统计误差未确认。"] },
    deepDive: { lead: "S²-VLA 的价值在于用小状态决定当前阶段该信任哪路信息，而不是持续扩展上下文。", sections: [{ title: "技术细节", paragraphs: ["belief state 随时间递推，汇总此前动作与当前观测；门控网络把它映射为视觉、语言意图和动作序列的权重。抓取前更依赖视觉定位，执行中更多依赖动作连续性，任务切换时再提高意图权重。", "层位消融很重要：全层 gate 并没有继续提高分数，中层单点最好，说明过度调制可能破坏预训练表示。"] }], experimentReading: ["仿真结果强，但真实 ALOHA 缺少完整表格和统计细节，因此不应把真机泛化描述得过满。"], reflections: ["部署时可记录 gate 随任务阶段的曲线，检查它是否真的对应抓取、搬运、放置，而不是仅学习数据集时间位置。"] },
    figures: [{ src: "/report-assets/2026-06-29/2606.27872-overview.png", alt: "S2-VLA 使用状态空间 belief 调节视觉语言动作融合的结构", caption: "Figure 1 · S²-VLA 的状态空间引导自适应注意力。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 7,
    title: "Drop-Then-Recovery: How Redundant Are Vision-Language-Action Models?",
    arxivId: "2606.27755",
    url: "https://arxiv.org/abs/2606.27755",
    institutions: ["University of Maryland, College Park", "Cisco Research"],
    signal: "先用虚拟 gate 评估 Transformer block 敏感度，再删块并恢复微调，验证 VLA 语言主干的实际冗余",
    tags: ["Model Pruning", "VLA Efficiency", "Real Deployment"],
    classification: { research: "VLA", training: "Post-training", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "GitHub", url: "https://github.com/s1ghhh/VLADrop" }],
    motivation: "VLA 继承大语言主干，但机器人指令通常短；若直接剪枝却不恢复训练，无法区分真正必要容量与暂时受损。",
    methodSummary: "DTR 把删块当受控干预，GateProbe 用一次虚拟 gate 梯度按 action loss 敏感度排序，再对删减模型按相同预算微调恢复。",
    architecture: "不新增部署模块；在语言、视觉和动作路径分别尝试 block removal，比较哪些部分可恢复。",
    optimization: "GateProbe 选块后做下游恢复微调；对 OpenVLA-OFT、π0.5、多种删减比例和 FLOPs-matched 训练做比较。",
    data: "LIBERO；真实 xArm 850 包裹分拣约 110K 帧/600 次抓取，10 Hz 遥操作，Jetson Thor 部署。",
    experiments: "LIBERO 中 OpenVLA-OFT 删除一半 LLM blocks 从 95.0% 到 98.3%；真机两环境各 3×20 抓取，Drop-9 与完整模型接近，强 OOD 下更深剪枝明显退化。",
    novelty: "不是只报告剪枝后速度，而是用‘删除—恢复’分离结构冗余，并检查视觉/动作路径与语言路径的不对称。",
    strengths: "多架构、FLOPs 对齐、Jetson 真机和 OOD 扰动揭示‘任务性能保留但鲁棒性先下降’。",
    limitations: "标准短指令任务可能低估语言深度价值；删减模型在颜色、容器和新物体扰动下更脆弱。",
    transfer: "可用于部署前逐块审计和小模型设计，但不能只按 ID 成功率决定删块，还要单列 OOD 鲁棒性。",
    experimentDetails: [{ title: "删块恢复与边缘部署", setup: "LIBERO 多 VLA；xArm 850 + Jetson Thor 包裹抓取，约 600 训练抓取。", comparisons: "完整模型、GateProbe 选块、随机/结构剪枝、不同删减比例和 FLOPs-matched 训练。", results: ["OpenVLA-OFT 删除一半 LLM blocks 后 98.3%，基线 95.0%。", "Env1 完整/Drop-9/Drop-16 为 63.3/65.0/55.0%；Env2 为 75.0/71.7/66.7%。", "强 OOD 下深剪枝差距扩大，例如绿光 35% 对完整模型 50%。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["virtual-gate sensitivity", "block removal", "recovery fine-tuning"], verifiedResources: ["GitHub 已公开；正文给出删块索引、训练预算、真实平台与 OOD 协议。"], missing: ["复刻真机数据仍需同类硬件与遥操作。"] },
    deepDive: { lead: "这篇论文证明的不是‘语言主干没用’，而是标准操作任务对深语言容量施加的压力有限。", sections: [{ title: "技术细节", paragraphs: ["GateProbe 在不真正删除 block 的情况下给每层加虚拟 gate，利用 action loss 对 gate 的敏感度估计层的重要性。随后 DTR 真正移除选定层并按统一预算恢复，避免把一次性破坏当作不可替代性。", "视觉和动作路径对删除更敏感；语言层大量可恢复，但 OOD 扰动下鲁棒性比平均成功率更早下降，提示冗余与安全余量并非同一概念。"] }], experimentReading: ["真机结果支持适度删除，但样本量和任务语义都有限；对复杂语言、长时子任务或开放对象仍需重新审计。"], reflections: ["模型压缩验收应同时包含延迟、显存、ID 成功率和 OOD 退化斜率。"] },
    figures: [{ src: "/report-assets/2026-06-29/2606.27755-overview.png", alt: "Drop-Then-Recovery 对 VLA 不同模块删块并恢复微调的分析流程", caption: "Figure 1 · DTR 的删块—恢复冗余分析。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 8,
    title: "Behavior Uncloning: Distilling Mode Redirection into Policy Weights without Inference-Time Steering",
    arxivId: "2606.29201",
    url: "https://arxiv.org/abs/2606.29201",
    institutions: ["Texas A&M University", "University of Wisconsin", "Northwestern University", "Stanford University"],
    signal: "用临时模式分类器把安全/期望行为方向蒸馏进策略权重，部署时不再运行外部 steering",
    tags: ["Behavior Editing", "Post-training", "Mode Control"],
    classification: { research: "VLA", training: "Post-training", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "GitHub", url: "https://github.com/phai-lab/behavior-uncloning" }, { label: "项目页", url: "https://behavior-uncloning.github.io/" }],
    motivation: "混合示范会让 BC 同时学到可完成但不安全/不合偏好的模式；全量过滤重训昂贵，推理时 verifier 又增加开销。",
    methodSummary: "MoRE 在短暂 uncloning 阶段用 mode classifier 提供重定向梯度，并以 retain loss 保持期望模式能力；完成后丢弃分类器。",
    architecture: "适配 Diffusion Policy 与 π0.5，不改变最终推理图；临时分类器只在权重编辑阶段评估 rollout mode。",
    optimization: "后训练同时最小化模式重定向目标和 retain loss，不需要重新访问全部原始混合数据做完整训练。",
    data: "八项仿真与真实任务，覆盖刀具交接、放置、绕障等多模式操作。",
    experiments: "平均部署成功率相对混合模式策略提高 44 个百分点，接近过滤数据重训参考，并保持原推理速度；在 DP 与 π0.5 上均验证。",
    novelty: "把推理时 steering 蒸馏成参数编辑，并显式用 retain loss 抑制灾难性遗忘。",
    strengths: "多任务、两类策略 backbone、真机和过滤重训上限对照较完整。",
    limitations: "需要可靠的模式标签/分类器；新的未标注危险模式不会自动被发现，参数编辑也可能影响边界状态。",
    transfer: "适合把‘刀柄朝人外、避开脆弱区、从指定一侧交接’等部署偏好写入已有策略。",
    experimentDetails: [{ title: "多模式策略重定向", setup: "八项仿真/真机任务，在同一数据中混合期望与不期望行为模式。", comparisons: "原 mixed-mode policy、推理时 steering、数据过滤重训和不同 retain 设置。", results: ["平均部署成功率提升 44 个百分点。", "总体接近过滤数据完整重训，同时不增加部署推理开销。", "Diffusion Policy 与 π0.5 都能通过相同思路编辑。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["temporary mode classifier", "redirection distillation", "retain loss"], verifiedResources: ["GitHub 与项目页已公开；正文覆盖多任务和 backbone。"], missing: ["自定义危险模式仍需收集标签和验证分类器。"] },
    deepDive: { lead: "MoRE 把行为偏好当作一次短后训练，而不是永久挂在策略外部的打分器。", sections: [{ title: "技术细节", paragraphs: ["临时 classifier 判断候选/rollout 属于哪个行为 mode，其梯度推动策略远离不期望模式；retain loss 则在期望样本上约束新旧策略，避免为了安全模式而丢失基本任务能力。", "后训练结束后分类器被移除，因此延迟与基础策略相同。代价是 mode 定义必须足够准确，且编辑后的局部变化需要重新做闭环回归测试。"] }], experimentReading: ["44 点是跨任务平均增益，具体任务难度与原始危险模式占比不同；应看每任务 retain 与安全行为是否同时保持。"], reflections: ["可以把失败日志按行为模式聚类，再优先编辑高风险且可明确定义的模式。"] },
    figures: [{ src: "/report-assets/2026-06-29/2606.29201-overview.png", alt: "MoRE 将临时模式分类器的重定向信号蒸馏进策略权重", caption: "Figure 1 · Behavior Uncloning / MoRE 的模式重定向。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 9,
    title: "Translation as a Bridging Action: Transferring Manipulation Skills from Humans to Robots",
    arxivId: "2606.28133",
    url: "https://arxiv.org/abs/2606.28133",
    institutions: ["HKU MMLab", "ByteDance Seed"],
    signal: "只用初始头戴相机坐标系下的相对腕部平移作为人—机器人共享 action，避开人手旋转与夹爪接触差异",
    tags: ["Human Data", "Action Representation", "Bimanual"],
    classification: { research: "表征学习", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://translation-as-a-bridging-action.github.io/" }],
    motivation: "人体 wrist 6DoF 估计噪声大，手指接触也与平行夹爪不同；把全部旋转直接当机器人 action 可能把本体差异写进监督。",
    methodSummary: "提取初始 head-camera frame 下左右腕相对平移作为 bridging action；π0-like 模型用交错 action token 与 attention mask 处理不同本体缺失的动作分量。",
    architecture: "视觉语言 backbone 接收人/机器人观测，action expert 生成共享平移与本体特定分量；mask 阻断在人类数据中不存在的机器人监督。",
    optimization: "先在人类动作数据上预训练共享平移能力，再用机器人数据后训练完整双臂 action；不使用 RL。",
    data: "大规模头戴视角人类双手数据与目标双臂平行夹爪数据；评测为多项新双臂操作并分析人类数据规模。",
    experiments: "相对腕平移显著优于噪声 6DoF 人体 action，并随人类数据量增加持续获益；真实双臂任务验证新能力迁移。",
    novelty: "主动丢弃跨本体不可靠的 rotation，只保留更稳定且任务相关的 translation 作为桥接监督。",
    strengths: "动作表示消融和人类数据 scaling 曲线直接回答‘什么人类监督可迁移’。",
    limitations: "需要显著旋转、工具姿态或灵巧手指控制的任务可能无法只靠平移；头戴相机坐标估计仍会漂移。",
    transfer: "可用于预训练对象接近、搬运和双臂协同的粗运动，再在少量机器人数据中学习旋转、夹爪和接触细节。",
    experimentDetails: [{ title: "人类 action 表示迁移", setup: "人类头戴视角动作预训练，目标为双臂平行夹爪新任务。", comparisons: "相对腕平移、包含旋转的 6DoF 人体 action、无人体预训练及不同人类数据规模。", results: ["平移桥接优于噪声 6DoF 表示。", "更多人类数据带来持续提升，说明共享 action 能吸收规模收益。", "真实双臂实验覆盖未在机器人数据中充分出现的新操作。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["head-frame relative wrist translation", "interleaved action tokens", "missing-component attention masks"], verifiedResources: ["项目页存在；正文给出 action 定义和 scaling 对照。"], missing: ["完整人类/机器人数据与训练代码公开状态未确认。"] },
    deepDive: { lead: "这项工作通过删掉不可靠维度获得更可迁移的监督，提醒跨本体 action 并非越完整越好。", sections: [{ title: "技术细节", paragraphs: ["每段示范以初始头戴相机为参考，计算左右 wrist 的相对平移；它描述‘手应该往哪里移动’，不强迫人手旋转与机器人夹爪旋转一一对应。机器人数据再补充旋转、夹爪等本体特定维度。", "交错 action token 允许共享与专用分量共存，attention mask 保证缺失维度不被错误监督。这比先估计完整人手姿态再硬 retarget 更保守。"] }], experimentReading: ["收益集中在适合平移抽象的任务；对旋拧、工具方向和灵巧手任务应单独验证。"], reflections: ["跨本体数据设计时可先按‘稳定共享维度’和‘本体专用维度’拆分，而不是强求统一全 action space。"] },
    figures: [{ src: "/report-assets/2026-06-29/2606.28133-overview.png", alt: "以相对腕部平移连接人类动作数据与双臂机器人策略的流程", caption: "Figure 1 · Translation as a Bridging Action 的共享动作表示。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 10,
    title: "CORE: Common Outcome Regularities from Action-Free Visual Demonstrations for Robot Manipulation",
    arxivId: "2606.29517",
    url: "https://arxiv.org/abs/2606.29517",
    institutions: ["Peking University Shenzhen Graduate School"],
    signal: "不转移人类动作，而从成功视频终态提取稳定对象关系，聚合成 visual goal prototype 注入策略",
    tags: ["Action-free Video", "Goal Representation", "Outcome Prototype"],
    classification: { research: "表征学习", training: "Post-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    motivation: "action-free 视频缺机器人控制标签，但成功轨迹终态往往共享对象布局、空间关系和接触约束，语言又常不足以描述这些物理细节。",
    methodSummary: "用对比与时间辅助目标训练 terminal outcome encoder，把同任务成功终态 embedding 聚合为 prototype，再作为全局 goal condition 注入机器人 policy。",
    architecture: "视觉终态 encoder 生成 goal prototype；策略 backbone 读取当前观测、语言/任务和 prototype，通过条件层影响动作生成。",
    optimization: "先在 action-free 成功视频上训练 outcome 表征，再用机器人示范后训练策略；与文本条件及不使用 prototype 的版本比较。",
    data: "Meta-World、RoboTwin 2.0 和真实机械臂；仿真设置组合少量机器人示范与更多 action-free visual demonstrations。",
    experiments: "对应 policy backbone 平均提高最多 +3.9、+11.1 和 +17.0 个百分点，并在所测设置中优于文本条件版本。",
    novelty: "转移的是跨本体稳定终态约束，而不是动作、奖励或逐帧 imitation。",
    strengths: "从仿真到真机的同方向收益和文本条件对照支持 visual goal 的几何信息确实有用。",
    limitations: "依赖成功终态聚类；多解任务、需要中间顺序或动态接触的长任务不能只靠终态 prototype 描述。",
    transfer: "可作为 VLA 的 goal image/goal token，尤其适合放置、堆叠和装配等终态关系明确的任务。",
    experimentDetails: [{ title: "跨域终态监督", setup: "Meta-World、RoboTwin 2.0 与真实机械臂，组合机器人示范和 action-free 成功视频。", comparisons: "原 policy、文本条件、单帧/无聚合视觉目标与 CORE prototype。", results: ["Meta-World 平均最高 +3.9 点。", "RoboTwin 2.0 最高 +11.1 点。", "真实任务最高 +17.0 点，并优于所测文本条件。"] }],
    reproducibilityDetails: { status: "信息不足", implementation: ["terminal outcome encoder", "contrastive + temporal objectives", "prototype-conditioned policy"], verifiedResources: ["正文说明数据配比和跨基准增益。"], missing: ["代码、终态抽取规则和真实数据公开状态未确认。"] },
    deepDive: { lead: "CORE 用‘任务结束后世界应是什么样’绕开人和机器人动作不一致的问题。", sections: [{ title: "技术细节", paragraphs: ["同任务成功视频的末端帧经 encoder 映射到 embedding，contrastive objective 拉近共同结果、分离不同任务；时间辅助目标帮助模型识别真正终态而非任意静态帧。多个成功 embedding 聚合后形成 prototype。", "策略在生成动作时读取 prototype，因此获得比文本更具体的目标几何。它不提供完整路径，仍需机器人示范学习如何从当前状态到达该终态。"] }], experimentReading: ["真实 +17 点说明终态条件有价值，但未证明对多阶段、可逆或路径约束任务同样有效。"], reflections: ["可把终态 prototype 与 subtask sequence 结合：前者定义每阶段目标，后者保留顺序。"] },
    figures: [{ src: "/report-assets/2026-06-29/2606.29517-overview.png", alt: "CORE 从 action-free 成功视频终态聚合视觉目标原型并条件化机器人策略", caption: "Figure 1 · CORE 的终态规律提取与策略条件化。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 11,
    title: "PhysisForcing: Physics Reinforced World Simulator for Robotic Manipulation",
    arxivId: "2606.28128",
    url: "https://arxiv.org/abs/2606.28128",
    institutions: ["Peking University", "NVIDIA"],
    signal: "用像素轨迹与语义关系两级对齐，专门约束视频世界模型中的局部运动和机器人—物体物理关系",
    tags: ["World Simulator", "Physics Alignment", "Video Generation"],
    classification: { research: "WM", training: "Post-training", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://dagroup-pku.github.io/PhysisForcing.github.io/" }],
    motivation: "通用或机器人视频模型会产生穿透、反重力、物体漂移和接触关系错误；普通重建 loss 对背景与物理关键区域一视同仁。",
    methodSummary: "pixel-level trajectory alignment 用参考点轨迹监督 DiT feature；semantic relational alignment 用冻结视频理解 encoder 的区域关系约束交互实体。",
    architecture: "在 Wan2.2/Cosmos3-Nano 视频生成 backbone 上增加两类训练损失，不改变基本生成器；局部轨迹与全局对象关系共同对齐。",
    optimization: "从大规模机器人视频筛选约 4M RoVid-X 样本后微调，并分别消融像素轨迹、语义关系和数据过滤。",
    data: "约 4M 筛选机器人视频；R-Bench、PAI-Bench、EZS-Bench，另在 WorldArena 和 RoboTwin 2.0 做下游策略检查。",
    experiments: "R-Bench 上 Wan2.2/Cosmos3 基座提高 22.3%/9.2%；WorldArena 闭环成功率 16%→24%，RoboTwin 2.0 策略约 68.2%→72.8%。",
    novelty: "把物理一致性分成点轨迹和对象关系两层，并在特征空间直接施加监督，而非只用像素重建或稀疏偏好分。",
    strengths: "生成基准、两种 backbone、逐项消融和下游闭环/策略增益共同验证物理对齐。",
    limitations: "WorldArena 绝对成功率仍低；视频评分与真实物理仍有差距，且 4M 数据和大模型训练成本高。",
    transfer: "可把轨迹和关系 loss 作为现有 robot video/WAM 的后训练目标，优先约束接触区域而非扩大所有像素容量。",
    experimentDetails: [{ title: "物理视频与下游控制", setup: "Wan2.2 与 Cosmos3-Nano，三套生成基准；WorldArena 规划和 RoboTwin 2.0 policy。", comparisons: "vanilla fine-tuning、单独 trajectory/relationship loss、不同数据过滤与两种基础模型。", results: ["R-Bench 相对基座提升 22.3% 与 9.2%。", "WorldArena 闭环 16.0% 提升到 24.0%。", "RoboTwin 2.0 下游成功率约 68.2% 提升到 72.8%。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["pixel trajectory alignment", "semantic relational alignment", "physics-informative data filtering"], verifiedResources: ["项目页提供更多结果；正文给出 backbone、数据规模和消融。"], missing: ["4M 训练数据和大模型算力限制完整复刻。"] },
    deepDive: { lead: "PhysisForcing 不要求模型重建更多细节，而是要求被动作影响的像素和对象关系沿时间保持物理一致。", sections: [{ title: "技术细节", paragraphs: ["轨迹 loss 把参考 point tracks 与 DiT 中间特征对齐，减少抓取点、物体边缘和末端执行器的跳变；关系 loss 则从冻结理解模型提取‘夹爪接触物体、物体随夹爪移动’等区域关系，并约束生成特征。", "两层分别处理局部连续性和全局交互逻辑。下游检查显示视觉改善能带来一定控制收益，但 WorldArena 24% 也表明视频世界模型距可靠模拟器仍远。"] }], experimentReading: ["生成分数、WorldArena 和 policy 都上升比单一视觉分数更可信，但真实机器人闭环仍未充分验证。"], reflections: ["world model 的失败集应按穿透、静止物未动、抓取后漂移等关系错误分桶，以对应训练约束。"] },
    figures: [{ src: "/report-assets/2026-06-29/2606.28128-overview.png", alt: "PhysisForcing 的像素轨迹和语义关系双层物理对齐", caption: "Figure 1 · PhysisForcing 对视频生成与策略学习的双层物理监督。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 12,
    title: "Fast Enough to Act: Spatio-Temporal Visual Token Merging for Low-Latency Robotic VLMs and VLAs",
    arxivId: "2606.29350",
    url: "https://arxiv.org/abs/2606.29350",
    institutions: ["William & Mary"],
    signal: "训练-free 合并跨帧冗余视觉 token，并重算旋转位置编码，在高分辨率下显著降低 VLA 延迟",
    tags: ["Token Merging", "Inference Acceleration", "VLA Deployment"],
    classification: { research: "VLA", training: "Test-time Adaptation", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "GitHub", url: "https://github.com/Junzhou-Chen/ST_Merge" }],
    motivation: "高分辨率与多帧输入产生大量静态背景 token，视觉编码延迟让闭环动作依据过时观测。",
    methodSummary: "ST-Merge 为 token 建立 3D 时空坐标，多队列并行匹配相似 token、加权聚合，并按聚合质心重算 RoPE 位置以减少空间偏移。",
    architecture: "作为视觉 encoder 内的 plug-in，在昂贵 attention/decoder 前压缩 token；不改 π0.5 权重也不需要重新训练。",
    optimization: "完全 training-free；通过 merge ratio、匹配方式、位置修正和分辨率消融选择部署配置。",
    data: "VQA 视频基准、LIBERO 闭环；真实 SO-ARM101 三任务（Place、Put、Move），每任务每方法 20 次。",
    experiments: "1024² 的 π0.5 从约 2.6 s 降至 300 ms、8.3×，LIBERO 仍为 97.5%；真机 thinking time 582→191 ms，三任务成功率不降。",
    novelty: "同时利用跨帧时间冗余和空间位置，并在合并后校正位置编码，避免通用 token merge 破坏精细操作几何。",
    strengths: "既报告 FLOPs/延迟，又做闭环 LIBERO 与真实 SO-ARM101 成功率，能验证加速没有只停留在离线吞吐。",
    limitations: "低分辨率下有小幅精度下降；相似外观但动作相关的小物体可能被误合并，动态相机也会降低冗余假设。",
    transfer: "适合视觉 encoder 占主要延迟的 VLA；上线前应按小物体、遮挡和相机运动单独调 merge ratio。",
    experimentDetails: [{ title: "高分辨率闭环加速", setup: "π0.5 + LIBERO；SO-ARM101 三项真实任务，每项 20 次。", comparisons: "无合并、基础 ToMe、无时空坐标/位置修正的变体和不同分辨率。", results: ["1024² 延迟约 2.6 s→300 ms，8.3×，LIBERO 成功率同为 97.5%。", "真机 thinking time 582.14→191.22 ms。", "Place 80%→80%、Put 70%→75%、Move 50%→55%。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["3D spatio-temporal coordinates", "multi-queue token matching", "weighted centroid RoPE correction"], verifiedResources: ["GitHub 已公开；正文给出分辨率、延迟、任务次数和消融。"], missing: ["不同视觉 backbone 的最佳 merge ratio 仍需重新标定。"] },
    deepDive: { lead: "ST-Merge 处理的是控制环中的‘观测过期’：保留更高分辨率的同时，让视觉决策及时刷新。", sections: [{ title: "技术细节", paragraphs: ["token 先附带帧序号和二维空间坐标，多个队列并行寻找时空邻近且特征相似的候选；被合并 token 按权重计算质心。随后不沿用任一原位置，而是用质心重算旋转位置编码。", "这一修正对插入、抓取等毫米级任务很关键，因为普通合并即使特征相似，也可能把物体边缘的空间位置平均错。训练-free 使它易接入，但 merge ratio 必须用闭环任务而非离线准确率调节。"] }], experimentReading: ["真机提升与加速方向一致，但三任务成功率每项仅 20 次，不能据此断言所有 VLA 都能无损压缩。"], reflections: ["部署监控应记录 token 数、首动作延迟和视觉失败帧，遇到小物体/高速运动时动态降低 merge ratio。"] },
    figures: [{ src: "/report-assets/2026-06-29/2606.29350-overview.png", alt: "ST-Merge 在视觉编码阶段进行时空 token 匹配聚合与位置修正", caption: "Figure 1 · ST-Merge 的训练-free 时空视觉 token 合并。图片来自 arXiv 原论文。" }],
  },
];
