import type { Paper } from "./site-data";

export const paperDaily20260720: Paper[] = [
  {
    rank: 1,
    title: "RoboTTT: Context Scaling for Robot Policies",
    arxivId: "2607.15275",
    url: "https://arxiv.org/abs/2607.15275",
    institutions: ["NVIDIA", "Stanford University", "The University of Texas at Austin"],
    signal: "用测试时更新的 fast weights 将机器人策略的有效历史扩展到 8K timesteps",
    tags: ["Long Context", "Fast Weights", "Test-time Training"],
    classification: { research: "Memory", training: "Test-time Adaptation", platforms: ["机械臂", "夹爪"] },
    detailAttributes: { memoryImplementation: "TTT 两层 MLP fast weights", memoryHorizon: "最高 8K timesteps" },
    resources: [{ label: "项目页", url: "https://research.nvidia.com/labs/gear/robottt/" }],
    motivation: "长时装配需要记住阶段、失败与纠正关系；把更多历史帧直接拼接到注意力中会让计算和显存随序列长度增长。",
    methodSummary: "在 GR00T N1.7 的动作 DiT 中插入 TTT 层：每个时刻用当前 token 更新一组 fast weights，再用这组状态读取压缩后的历史。训练采用 sequence action forcing 和 truncated BPTT。",
    architecture: "视觉语言主干保持 GR00T N1.7 结构，动作专家包含 16 个 DiT block；跨帧 TTT 模块是两层 MLP，并用 16 个 register tokens 承载序列状态，tanh gate 以 0.001 初始化以稳定接入预训练模型。",
    optimization: "先从 GR00T N1.7 初始化并进行 30K steps 预训练，再在 YAM 任务上 20K steps 后训练；动作生成使用 flow matching，序列训练通过 TBPTT 控制反向传播长度。",
    data: "预训练混合桌面双臂机器人数据与第一人称人类视频；后训练为 YAM 三项双臂装配任务，约 8、6、5 小时真实数据。",
    experiments: "三项 YAM 长时装配的平均任务完成度为 79%，对照 GR00T N1.7 为 42%、GDN 为 56%；8K 上下文为 71.5%，明显高于 1K 的 43.9%。",
    novelty: "相对固定窗口 attention 或拼接历史，RoboTTT 用固定大小、可在线更新的参数状态压缩历史；1K/8K 与移除 TTT 的对照直接检验了上下文长度，而不是只比较模型容量。",
    strengths: "在多阶段双臂真机装配上验证长上下文，并同时给出上下文长度、训练方式和模块位置消融。",
    limitations: "预训练使用 16 张 GB200，完整代码和权重未确认公开；fast weights 仍可能遗忘早期事件，三项任务也不足以证明开放环境泛化。",
    transfer: "可把接触事件、失败恢复和阶段切换显式写入 fast-weight 更新信号，用固定状态容量替代不断增长的视觉帧缓存。",
    experimentDetails: [
      { title: "长时双臂装配", setup: "YAM 平台上的 Adapt Sander、Assemble Gear 与 GearBot；前两项每个方法 20 次，GearBot 10 次，并记录完整成功与阶段完成度。", comparisons: "GR00T N1.7 单步基线、GDN 长上下文基线、不同 TTT 上下文长度及训练消融。", results: ["三任务平均完成度：RoboTTT 79%，GDN 56%，GR00T N1.7 42%。", "完整成功分别为 9/20、13/20 和 2/10；说明完成度提升并不等于所有长任务都已稳定完成。", "上下文从 1K 扩展到 8K 后平均完成度由 43.9% 提升至 71.5%。"] },
    ],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["NVIDIA GEAR 项目页提供论文、视频和任务展示。"], implementation: ["GR00T N1.7；16 个 DiT block；两层 MLP TTT；16 register tokens；tanh gate 初值 0.001；flow matching；TBPTT；30K + 20K steps；16×GB200。"], missing: ["完整训练代码、权重、预训练数据配比与真机数据尚未确认公开。"] },
    deepDive: { lead: "RoboTTT 的核心不是把更多图像送入模型，而是把逐步到来的观测—动作历史写入一组可更新的内部参数。", sections: [
      { title: "跨时间 fast weights", paragraphs: ["当前帧仍由 attention 处理空间与模态内交互；TTT 层在时间维度上根据新 token 更新两层 MLP，使过去信息不再以完整 KV 序列保存。register tokens 为更新提供稳定载体，门控让新模块从近似恒等映射开始接入。", "训练时 sequence action forcing 保持历史动作与部署条件一致，TBPTT 只跨有限段回传梯度；推理时状态随 episode 递推，单步存储不随历史长度线性增加。"] },
    ], equations: [{ name: "fast-weight 递推", expression: "Wₜ = Wₜ₋₁ − η ∇W ℒ(Wₜ₋₁; xₜ),   yₜ = f(xₜ; Wₜ)", explanation: "每个时刻先用当前 token 的自监督目标更新 fast weights，再由更新后的状态生成跨时间表征；Wₜ 因而是历史的参数化压缩。" }, { name: "动作 flow matching", expression: "ℒFM = E ‖vθ(aτ, τ, c) − (a₁ − a₀)‖²", explanation: "动作专家学习从噪声动作 a₀ 到真实动作 a₁ 的速度场，c 包含当前多模态观察与 TTT 历史状态。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.15275-architecture.png", alt: "RoboTTT 在动作 DiT 中加入跨时间 TTT 层并维护 fast weights 的训练与推理结构", caption: "Figure 2 · RoboTTT 模型、序列训练与递推推理结构。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 2,
    title: "Never Too Late for Force: Accelerating VLA Post-Training with Reactive Force Injection",
    arxivId: "2607.14236",
    url: "https://arxiv.org/abs/2607.14236",
    institutions: ["Shanghai Jiao Tong University", "Shanghai Innovation Institute", "Southern University of Science and Technology", "Noematrix Ltd."],
    signal: "为预训练 VLA 增加力觉反应旁路，并用在线纠正覆盖接触失败状态",
    tags: ["Force / Torque", "Online Correction", "VLA Post-training"],
    classification: { research: "VLA", training: "Post-training", modalities: ["Force / Torque"], data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://lift-policy.github.io/" }],
    motivation: "预训练 VLA 能理解任务语义，但视觉帧率与大模型推理不足以在插入、折叠等接触阶段快速响应力变化。",
    methodSummary: "LIFT 复制一个 reactive action expert，用因果 GRU 编码短期 6D wrench，并通过零初始化 cross-attention 注入动作层；部署中收集失败状态的人工纠正，再与离线数据混合做 DAgger 式后训练。",
    architecture: "主干为 π0.5 的 PaliGemma VLM 与 flow-matching action expert；力分支用隐藏维 512 的 causal GRU 输出 1024 维表征，预测 10 步 action horizon，并用 latency offset=3 对齐传感与执行。",
    optimization: "AdamW、batch size 32、学习率 5e-5、30K steps；每个 checkpoint 执行 10 次自主 rollout，再按失败分布追加纠正，在线数据与离线数据用自适应比例混合。",
    data: "Flexiv Rizon 4S 上的毛巾折叠、书本插入和汉诺塔放环；训练包含离线任务示范与多轮在线人工纠正轨迹。",
    experiments: "三项真机接触任务中，完整 LIFT 均优于视觉-only、只加力输入和无在线纠正版本；消融显示 reactive expert 与 DAgger 数据闭环缺一不可。",
    novelty: "与把 wrench 直接拼到 VLA 输入不同，LIFT 把快速力响应放到独立动作旁路，并专门采集当前策略会访问的失败状态；主要增益来自结构与数据分布两部分。",
    strengths: "结构、力输入和在线纠正均有对应消融，实验直接针对视觉 VLA 在接触阶段的失败。",
    limitations: "依赖人工纠正和真实设备迭代，只验证单臂三任务；在线采集成本与跨力传感器迁移尚未解决。",
    transfer: "适合把低频 VLA 作为语义主干，把 force、slip 或 collision event 放入独立高速旁路，并只在失败区域收集纠正。",
    experimentDetails: [{ title: "三项接触任务与在线迭代", setup: "Flexiv Rizon 4S 执行毛巾折叠、书本插入和汉诺塔放环；每个训练 checkpoint 进行 10 次自主 rollout，并对失败状态追加人工纠正。", comparisons: "π0.5 视觉基线、直接力输入、reactive expert、离线-only 与完整 online correction。", results: ["完整方法在三项任务的最终成功率均最高，尤其改善插入与放环时的接触恢复。", "移除 force memory 或 reactive expert 会在接触阶段明显退化；只用离线数据则难以覆盖策略自身造成的偏移状态。", "在线数据混合比例按最近 rollout 表现自适应调整，避免后期纠正数据完全淹没原始示范。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["官方项目页提供论文、视频与实验展示。"], implementation: ["π0.5；causal GRU hidden=512、output=1024；action horizon=10；latency offset=3；batch=32；AdamW；lr=5e-5；30K steps。"], missing: ["代码、权重、完整纠正轨迹与每轮样本数量未确认公开。"] },
    deepDive: { lead: "LIFT 把接触控制看成“慢语义主干 + 快物理旁路”的后训练问题。", sections: [{ title: "力记忆与动作注入", paragraphs: ["连续 6D wrench 先经 causal GRU 压缩为短时力记忆，再由零初始化 cross-attention 写入 reactive action expert。零初始化使初始输出接近原 π0.5，后训练只需逐步学会在接触阶段偏离主策略。", "在线 rollout 暴露预训练策略在真实闭环中访问的错误状态，人工纠正将这些状态补回训练集；混合权重按近期性能裁剪在 0.2–0.8 之间。"] }], equations: [{ name: "在线数据混合", expression: "Dtrain = (1 − α)Doffline + αDonline,   α = clip(g(success), 0.2, 0.8)", explanation: "随着自主成功率变化调整纠正数据占比；低成功阶段更重视 Donline，同时保留离线示范防止遗忘。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.14236-architecture.png", alt: "LIFT 在预训练 VLA 旁加入 reactive action expert 并通过交叉注意力注入力记忆", caption: "Figure 2 · LIFT 的力觉编码、reactive action expert 与在线纠正流程。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 3,
    title: "Scaling Behavior Foundation Model for Humanoid Robots",
    arxivId: "2607.15163",
    url: "https://arxiv.org/abs/2607.15163",
    institutions: ["The Chinese University of Hong Kong", "Shanghai Jiao Tong University", "Zhejiang University", "Peking University", "Tsinghua University", "Galbot", "Shanghai AI Laboratory"],
    signal: "用 1.02 亿帧跨来源运动数据训练可扩展 humanoid 行为基础模型",
    tags: ["Humanoid", "Motion Foundation Model", "Large-scale Data"],
    classification: { research: "其他", training: "Pre-training", data: "跨本体数据", platforms: ["Humanoid"], deployment: "Sim2Real" },
    resources: [{ label: "项目页", url: "https://bfm.cs.cuhk.edu.hk/" }],
    motivation: "humanoid 控制器常按动作或平台分别训练，难以利用分散的 mocap、视频重建与机器人运动数据形成统一行为先验。",
    methodSummary: "将不同来源运动统一重定向到 humanoid 状态—动作接口，以 PPO 训练 motion tracking teacher，再把大规模轨迹蒸馏进 Humanoid Transformer，形成可按目标运动条件控制的行为基础模型。",
    architecture: "Humanoid Transformer 读取历史本体状态与目标运动 token，输出低层关节目标；训练管线先完成跨骨架 retargeting，再用并行仿真强化学习建立稳定跟踪行为。",
    optimization: "核心是大规模 RL motion tracking 与数据扩展，不是 VLA 后训练；模型随数据与参数规模扩展，并在真实 humanoid 上部署。",
    data: "约 1.02 亿帧、50 Hz 的运动序列，混合 AMASS 等公开 mocap、视频恢复动作及机器人运动数据，覆盖全身、上肢与移动行为。",
    experiments: "在多个 humanoid 平台和多类动作上比较专用控制器与通用基础模型；局部关节误差降低超过 10%，全局关键点误差最高降低 82%，并展示真实机器人复杂动作跟踪。",
    novelty: "相对单数据集、单机器人 motion policy，该工作把数据规模、来源多样性和模型容量同时作为变量，并验证统一行为模型可替代多套专用控制器。",
    strengths: "数据规模、跨来源重定向、扩展规律与真机验证构成完整系统证据。",
    limitations: "重点是参考运动跟踪而非语言条件任务执行；完整数据清洗与训练成本高，部分源数据许可也限制端到端复现。",
    transfer: "可把该类行为基础模型作为 humanoid VLA 的低层动作先验，让高层只预测运动目标或稀疏控制条件。",
    experimentDetails: [{ title: "规模扩展与真机动作跟踪", setup: "在统一评测集上比较不同数据规模、模型规模和专用/通用控制器，并将模型部署到真实 humanoid。", comparisons: "逐任务专用策略、较小数据/模型版本与统一 Behavior Foundation Model。", results: ["论文报告局部 MPKPE 相对既有控制器降低超过 10%，全局 MPKPE 最高降低 82%。", "增加运动数据的覆盖度比只增加相近轨迹更有效，支持跨来源数据的互补性。", "真机展示包含全身动态动作，但不是开放语言任务的成功率评测。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["官方项目页提供模型说明、真机视频与论文。"], implementation: ["统一 retargeting；50 Hz 运动序列；PPO motion tracking；Transformer policy；本体历史与目标运动条件。"], missing: ["完整 1.02 亿帧训练集、清洗配比、全部训练超参与权重开放状态需以项目页后续发布为准。"] },
    deepDive: { lead: "这项工作把 humanoid 低层控制从“每个动作训练一套策略”推进到共享运动分布上的基础模型。", sections: [{ title: "统一运动接口", paragraphs: ["不同人体骨架与机器人轨迹先被重定向到统一 humanoid 关节和根节点表示；仿真中的 tracking reward 同时约束局部关节、全局关键点、速度和稳定性。", "Humanoid Transformer 使用历史本体状态保持动力学连续性，并用目标运动窗口决定未来姿态。其泛化边界主要由运动覆盖而非语言理解决定。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.15163-architecture.png", alt: "Behavior Foundation Model 从大规模运动数据、重定向到 Humanoid Transformer 控制的整体架构", caption: "官方模型图 · 大规模运动数据到 Humanoid Transformer 行为策略的训练管线。图片来自论文官方项目页。" }],
  },
  {
    rank: 4,
    title: "Data and Learning Where it Matters for Contact-Rich Manipulation",
    arxivId: "2607.15982",
    url: "https://arxiv.org/abs/2607.15982",
    institutions: ["Technical University of Munich", "Siemens"],
    signal: "在接触区域定向采样并学习残差动作，以少量真机数据解决高精度插装",
    tags: ["Contact-rich", "Targeted Data", "Residual Policy"],
    classification: { research: "表征学习", training: "BC", modalities: ["Force / Torque", "State / Proprioception"], data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    motivation: "接触任务的大部分自由空间轨迹易由规划器解决，真正决定成功的是狭小接触区域；均匀收集整段示范会把预算浪费在低信息状态。",
    methodSummary: "用规划器把机器人带到接触邻域，在该区域以 0.8 概率执行随机探索并记录力、控制误差和状态；策略只学习相对规划动作的残差，因此数据与模型容量集中在接触修正。",
    architecture: "DINOv2 视觉特征投影到 16 维，与力/力矩、controller error、笛卡尔速度、上一动作拼接；轻量策略输出残差控制量，名义轨迹仍由 motion planner 提供。",
    optimization: "每轮 150 steps，数据仅训练 5 epochs；论文比较 flow/diffusion policy、π0.5、HIL-SERL 与纯规划，并对随机采样概率和输入状态做消融。",
    data: "四项真实接触任务，每项约 300–500 个短 episode、2–2.5 小时采集；OOD 测试改变部件位置、几何或接触条件。",
    experiments: "四任务每种方法 50 次，完整方法平均成功率 96%，最强纯规划对照约 55%；OOD 每格 20 次，四任务为 90%、85%、90%、95%，峰值接触力最多降低 49%。",
    novelty: "相对整轨迹 imitation learning 或纯 RL，该方法只在规划器不可靠的接触邻域采集数据，并学习 residual 而非完整动作；直接对照显示收益来自数据位置与残差结构。",
    strengths: "四任务、每格 50 次、OOD 与力峰值指标充分支撑“数据采在哪里”这一核心命题。",
    limitations: "需要可用的规划器、接触区域定义和控制器误差信号；复杂可变形物体或无几何先验任务不一定能分离自由空间与接触阶段。",
    transfer: "可用于 VLA 后端：高层负责到达，接触触发后切换为小型 residual controller，并把采集预算集中在失败邻域。",
    experimentDetails: [{ title: "四项接触任务与 OOD", setup: "真实机器人完成精密插装、表面接触等四项任务；主表每方法每任务 50 次，OOD 每格 20 次。", comparisons: "DiTFlow、Diffusion Policy、π0.5、HIL-SERL、纯 motion planning 及输入/采样消融。", results: ["完整方法四任务平均成功率 96%，显著高于最强规划对照约 55%。", "OOD 条件下四任务成功率为 90%、85%、90%、95%。", "定向学习的残差降低碰撞与过载，报告的峰值接触力最多下降 49%。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["论文完整披露四任务、数据时长、episode 数、对照和 rollout 次数。"], implementation: ["DINOv2 feature→16D；force/torque、controller error、Cartesian velocity、previous action；random action probability=0.8；episode=150 steps；5 epochs。"], missing: ["当前未确认代码、真实数据与标定配置公开。"] },
    deepDive: { lead: "论文把接触策略视为规划器的局部误差修正器，而不是从像素重新学习整条轨迹。", sections: [{ title: "接触邻域残差学习", paragraphs: ["motion planner 先提供名义动作 aplan；机器人进入接触邻域后，策略根据视觉、力和控制误差输出小残差 δa。随机探索也只发生在这一局部区域，因此每条样本都更接近失败边界。", "DINOv2 提供对象与几何语义，force 和 controller error 则描述实际约束。上一动作帮助网络保持短期连续性，避免接触中的高频抖动。"] }], equations: [{ name: "残差控制", expression: "aₜ = aplan,ₜ + δaθ(oₜ, fₜ, eₜ, vₜ, aₜ₋₁)", explanation: "规划器负责全局可达性，学习策略只修正接触阶段由摩擦、装配公差和模型误差造成的偏差。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.15982-method.png", alt: "面向接触区域的数据采集、名义规划与残差策略学习流程", caption: "Figure 1 · 在接触邻域定向收集数据并学习 planner residual 的方法总览。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 5,
    title: "Open-AoE: A Large-Scale Open Dataset for Action-oriented Embodied Intelligence",
    arxivId: "2607.14183",
    url: "https://arxiv.org/abs/2607.14183",
    institutions: ["Ant Group"],
    signal: "以手机众包构建面向动作理解的人类第一视角大规模开放数据",
    tags: ["Ego Data", "Action Annotation", "Open Dataset"],
    classification: { research: "表征学习", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["其他平台"] },
    resources: [{ label: "GitHub", url: "https://github.com/Open-AoE/Open-AoE" }, { label: "模型", url: "https://huggingface.co/datasets/Open-AoE/Open-AoE" }],
    motivation: "具身预训练需要大量以手部交互和任务阶段为中心的视频，但机器人采集昂贵，普通互联网视频又缺少动作、轨迹和对象级结构。",
    methodSummary: "通过手机端标准化众包采集第一视角任务视频，自动恢复相机与 MANO 手部轨迹，再用多阶段模型与人工审核生成 atomic action、对象、场景和语言标注。",
    architecture: "数据管线包含移动端采集、质量检测、手/相机几何恢复、时序动作切分和语义标注；其产物可分别用于 VLM/VLA 的视频预训练、动作分段和空间轨迹监督。",
    optimization: "论文贡献是数据生产与清洗，不提出新的 policy 优化算法；下游实验用相同模型对比加入或不加入 Open-AoE 预训练。",
    data: "超过 2,000 小时、500+ 贡献者、400+ 手机、400+ 场景和 8,000+ 任务；100 小时审计子集含 32,407 条动作描述、175 个动词、8,030 个对象和 135 类场景。",
    experiments: "下游动作理解、具身视频表征和机器人迁移实验显示 Open-AoE 预训练带来一致改善；人工审计同时量化切分、轨迹与语义标签质量。",
    novelty: "相对只提供视频—文本对的数据集，Open-AoE 同时开放相机轨迹、手部轨迹、atomic action 与对象语义；与机器人数据相比，它用消费级设备显著扩展采集规模。",
    strengths: "规模、采集规范、自动处理与人工审计均较完整，数据和工具链有公开入口。",
    limitations: "人手与机器人末端执行器仍有本体差异；手机视角、任务分布和自动标签错误会形成系统偏置。",
    transfer: "适合为 VLA 预训练增加动作边界、手—物轨迹和任务阶段监督，再用少量机器人数据学习本体映射。",
    experimentDetails: [{ title: "数据审计与下游迁移", setup: "对 100 小时子集做细粒度人工审计，并在动作理解、视频表征和机器人相关任务上比较预训练数据组成。", comparisons: "不使用 Open-AoE、使用普通视频数据与加入 Open-AoE 的相同下游模型。", results: ["审计子集覆盖 32,407 条动作描述、175 个动词和 8,030 个对象，说明不是少数脚本任务的重复录制。", "加入动作导向预训练后多个下游指标一致提升，但收益不能单独归因于某一种标注。", "论文公开数据与处理入口，便于后续检验跨本体迁移。"] }],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["GitHub、Hugging Face 与 ModelScope 数据入口已公开。"], implementation: ["手机众包；相机轨迹与 MANO 手轨迹恢复；atomic action segmentation；多阶段自动标注与人工审计。"], missing: ["完整 2,000 小时数据的所有授权与部分处理模型权重需按发布页逐项核验。"] },
    deepDive: { lead: "Open-AoE 的主要价值是把人类视频从“看见任务”变成带有动作边界和几何轨迹的训练样本。", sections: [{ title: "从原始视频到动作样本", paragraphs: ["采集端约束相机姿态、任务说明与视频质量；处理端先恢复相机和双手运动，再按原子动作切分，最后为动作、对象和场景生成语言标签。", "相机/手轨迹可给 world model 或 action tokenizer 提供连续几何监督，atomic action 则可用于 subtask 边界和长时视频采样。机器人使用时仍需要把人手空间映射到末端执行器空间。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.14183-overview.png", alt: "Open-AoE 从手机众包采集到手部轨迹、动作切分与多层标注的数据流程", caption: "Figure 1 · Open-AoE 采集规模、处理管线与标注层次。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 6,
    title: "Active Real-World Factor-Based Evaluation for Generalist Robot Policies",
    arxivId: "2607.14439",
    url: "https://arxiv.org/abs/2607.14439",
    institutions: ["University of Minnesota Twin Cities"],
    signal: "用主动测试在真实机器人上更少次数地估计策略在因素空间中的表现",
    tags: ["Active Testing", "Evaluation", "Generalization"],
    classification: { research: "其他", training: "Test-time Adaptation", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    motivation: "几十次随机 rollout 既无法覆盖物体位置、台面高度与相机视角的组合，也可能偶然高估或低估策略。",
    methodSummary: "把评测配置视为设计空间，用概率 surrogate 预测连续任务得分及不确定性，再由 acquisition function 选择下一次最有信息量的真实机器人试验。",
    architecture: "框架比较 Gaussian Process、Mixture Density Network 和 Deep Ensemble，并配合 posterior uncertainty、NIPV、BALD、EPIG 等 acquisition；主方法采用带 ARD RBF kernel 的 GP。",
    optimization: "这不是 policy 训练方法；surrogate 仅用已经执行的评测结果在线拟合，30 个随机点 warm start，之后逐步选择新配置直到预算耗尽。",
    data: "UR5e 上三项 π0 manipulation 任务，共 2,331 个真实配置；因素为 11×11 物体位置网格、3 个台面高度和 3 个相机视角。",
    experiments: "以完整 2,331 次评测作为 ground truth，主动测试在相同预测误差下通常比随机测试少 20%–40% 试验，并能更快定位相机/位置等失败区域。",
    novelty: "相对随机抽样成功率，它估计的是整个因素空间的连续表现分布，并显式使用 epistemic uncertainty 选择下一次真实试验。",
    strengths: "2,331 次真实机器人评测提供少见的完整 ground truth，可检验主动选择是否真的节省试验。",
    limitations: "主动过程是在已收集的全量结果上离线回放，假设固定配置下 policy 随机性可忽略；只有三任务和三个因素。",
    transfer: "可把日报关注的泛化维度转成结构化因素，用更少 rollout 构建 failure map，而不是只报告单一平均成功率。",
    experimentDetails: [{ title: "主动测试与随机评测", setup: "UR5e 上 Pick blue block、Upright cup、Put green block in pot；2,331 个有效配置，每次约 1 分钟。", comparisons: "随机无放回采样，以及 GP/MDN/Deep Ensemble 与多种 acquisition function 组合。", results: ["在 100 次预算下，最佳主动策略通常节省 20–40 次试验即可达到随机测试的估计精度。", "完整因素图揭示相机视角、台面高度和对象位置的非均匀失败区域，单一成功率会掩盖这些结构。", "不同 surrogate/acquisition 的优劣随任务变化，论文没有把一个组合宣称为普遍最优。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["论文给出 2,331 个配置、任务打分、surrogate 和 acquisition 细节。"], implementation: ["GP with ARD-RBF；30-point random warm start；100-trial budget；连续 progress score；π0 policy；UR5e。"], missing: ["当前未确认全量真实评测结果、代码和 π0 后训练数据公开。"] },
    deepDive: { lead: "方法把“做多少次 rollout”改写为序贯实验设计：每一次真实执行都应最大限度降低对未测配置的未知。", sections: [{ title: "因素空间与概率代理", paragraphs: ["配置 x 由对象位置、台面高度和相机视角组成，真实策略得分 f(x) 只在执行后可见。GP 用已测点拟合均值和方差，ARD lengthscale 还能反映不同因素对表现变化的敏感度。", "acquisition 并非寻找最高成功率，而是寻找能最大程度减少全空间不确定性的下一点；因此它更接近评测资源分配而不是训练时的主动学习。"] }], equations: [{ name: "因素化评测空间", expression: "x = (xposition, xheight, xcamera) ∈ Fposition × Fheight × Fcamera", explanation: "每次真实 rollout 对应因素组合 x，目标是用有限观测恢复整个 f(x) 表现分布。" }, { name: "GP 选择信号", expression: "xnext = arg maxx α(μt(x), σt(x))", explanation: "acquisition α 根据 surrogate 的预测均值与 epistemic uncertainty 选择下一次评测配置。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.14439-overview.jpg", alt: "主动因素评测用概率代理和采集函数选择下一次真实机器人配置", caption: "Figure 1 · Factor-based active evaluation 整体流程。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 7,
    title: "Representation-Aligned Tactile Grounding for Contact-Rich Robotic Manipulation",
    arxivId: "2607.14609",
    url: "https://arxiv.org/abs/2607.14609",
    institutions: ["Fudan University", "Lenovo CTO Organization", "Nanyang Technological University", "TeleAI, China Telecom"],
    signal: "先定位最具物理可预测性的动作层，再用未来触觉监督整形该层表征",
    tags: ["Tactile", "Representation Alignment", "Contact-rich"],
    classification: { research: "表征学习", training: "Post-training", modalities: ["Tactile"], platforms: ["机械臂", "夹爪"] },
    motivation: "给 VLA 增加触觉辅助损失并不保证监督落在真正决定动作的层，错误注入位置可能只增加训练负担。",
    methodSummary: "先冻结模型并用 linear probe 测量各 action-expert 层对未来触觉的可预测性，再在最佳层接入 Latent Tactile Predictor；触觉只在训练期提供监督，部署时移除预测头。",
    architecture: "视觉语言 backbone 与 action expert 保持不变；中间 hidden state 通过轻量 projector 预测未来 tactile latent，loss 反向塑造最接近接触动力学的层。",
    optimization: "在 SmolVLA 和 π0 两个 backbone 上做后训练；比较不同注入层、无触觉监督、直接触觉接口和 latent predictor。",
    data: "ARX R5 配 PaXini 触觉传感器，五项接触任务，每项 50 条专家示范。",
    experiments: "每任务每方法 20 次真机试验；两个 backbone 上均优于原模型和未对齐触觉接口，层选择消融显示中间动作层比任意末层监督更有效。",
    novelty: "相对“有触觉就加 loss”，论文先用 probe 建立表征层与未来接触信号的对应，再决定监督位置；推理时不依赖触觉传感器。",
    strengths: "层级诊断、两个 backbone 和五任务真机对照让表征对齐结论较清楚。",
    limitations: "单平台、单触觉传感器与有限任务，尚未证明最佳层在更大 VLA 或跨传感器时保持一致。",
    transfer: "同样的 probe→alignment 流程可用于未来力、contact phase、slip 或 failure-risk 表征。",
    experimentDetails: [{ title: "层选择与双 backbone 验证", setup: "ARX R5 上五项接触任务，每项 50 条示范、每种方法 20 次真机 rollout。", comparisons: "SmolVLA/π0 原模型、不同 action-expert 层、直接触觉输入与 latent tactile grounding。", results: ["两个 backbone 上，选择高 tactile-predictability 层的版本均取得最高或并列最高成功率。", "在不可预测层强加触觉目标的收益较小甚至退化，支持‘监督位置’而非单纯额外 loss 的解释。", "触觉预测头部署时移除，因此控制延迟不因触觉生成增加。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["论文披露平台、传感器、示范量、任务数和 rollout 协议。"], implementation: ["linear probe layer selection；future latent tactile predictor；SmolVLA 与 π0；training-only auxiliary head。"], missing: ["代码、数据、触觉 encoder 权重和完整训练超参未确认公开。"] },
    deepDive: { lead: "这项工作关心的不是触觉是否有用，而是动作模型内部哪一层最适合接收物理监督。", sections: [{ title: "可预测性驱动的监督位置", paragraphs: ["对各中间层训练只读 linear probe，预测未来触觉 latent。probe 表现用于定位已经包含接触前兆、又尚未完全压缩成动作输出的层。", "随后 Latent Tactile Predictor 在该层施加训练目标；部署时模型只用原有视觉、语言和状态输入，触觉传感器及预测头都不进入在线路径。"] }], equations: [{ name: "触觉对齐目标", expression: "ℒtactile = ‖P(hℓ,t) − ztactile,t+Δ‖²", explanation: "P 从选定动作层 hℓ,t 预测未来触觉 latent；通过 Δ 步预测迫使表征编码接触演化而非只重建当前读数。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.14609-overview.png", alt: "从动作专家中间表征预测未来触觉并选择最佳监督层的框架", caption: "Figure 3 · Future latent tactile grounding 与层级选择。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 8,
    title: "Beyond Implicit Force: Evaluating Explicit Force-Torque Proxies in Action Chunking with Transformers",
    arxivId: "2607.14578",
    url: "https://arxiv.org/abs/2607.14578",
    institutions: ["Australian Institute for Machine Learning, Adelaide University"],
    signal: "揭示 leader–follower 遥操作误差中的隐式力线索，并用电机电流/关节力矩显式恢复",
    tags: ["Force Proxy", "ACT", "Contact Dynamics"],
    classification: { research: "表征学习", training: "BC", modalities: ["Force / Torque", "State / Proprioception"], platforms: ["机械臂", "夹爪"] },
    motivation: "ACT 在接触任务中的‘力感知’可能并非来自视觉，而是示范中 leader 指令与 follower 实际关节的跟踪误差；若改成预测真实 follower 状态，这条隐藏线索会消失。",
    methodSummary: "构造 observation-centric ACT-o，只预测 follower joint state 以移除 leader–follower discrepancy；再加入由电机电流或 joint effort 计算的 torque proxy，检验显式低成本力信号能否恢复接触行为。",
    architecture: "保持 ACT 的 CVAE 与 Transformer action chunking 主体，只改变输入/预测目标；ACT-o3 将关节状态与 torque proxy 分离编码后融合，避免把执行器力矩当作普通位置维度。",
    optimization: "小样本行为克隆，不使用 RL；所有变体使用同一 ALOHA/ViperX 数据与训练管线，以隔离隐式误差和显式力 proxy 的影响。",
    data: "四项真实接触任务：板面擦拭、插头插入、软瓶按压和泡棉力平衡停止；每项由 leader–follower 遥操作采集。",
    experiments: "移除隐式 leader–follower 误差后，ACT-o 在关键接触阶段严重退化；加入 torque proxy 的 ACT-o3 恢复或超过基础 ACT，并在四类不同接触机制上保持一致。",
    novelty: "相对直接宣称 ACT 从视觉学到力，该工作用预测目标干预拆出隐藏的 teleoperation cue，再以低成本 torque proxy 做因果式恢复对照。",
    strengths: "四种接触机制与针对性模型变体清楚回答了‘成功来自哪条信号’。",
    limitations: "torque proxy 受摩擦、重力补偿和执行器标定影响；只验证 ALOHA/ViperX，结论不必然迁移到不同控制器。",
    transfer: "检查机器人数据中 commanded/executed action 差异，避免把隐式控制误差误认为视觉智能；必要时将其显式建模。",
    experimentDetails: [{ title: "隐式线索移除与显式力恢复", setup: "ALOHA/ViperX 上的 surface following、precision insertion、stiffness discrimination 和 force-equilibrium stopping。", comparisons: "原 ACT、移除 leader command discrepancy 的 ACT-o、加入 servo-current/joint-effort torque proxy 的变体。", results: ["ACT-o 在 force-critical 阶段出现明显失败，说明原数据中的 leader–follower tracking error 携带接触信息。", "加入 torque proxy 后，策略在四任务中恢复稳健接触行为，并在部分指标上超过原 ACT。", "不同任务分别考察法向力维持、插入约束、材料刚度和力阈值停止，避免只在单一插孔上验证。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["论文给出 ALOHA/ViperX 硬件、四项任务、ACT 变体和指标定义。"], implementation: ["ACT CVAE/Transformer；follower-state prediction；servo current 或 joint effort torque proxy；observation-centric input reformulation。"], missing: ["当前未确认代码、示范数据和各任务全部训练超参公开。"] },
    deepDive: { lead: "论文通过改写 ACT 的预测对象，证明一部分接触能力实际来自遥操作系统留下的控制误差信号。", sections: [{ title: "从隐式误差到显式 torque", paragraphs: ["leader 关节是操作者意图，follower 关节是接触约束后的执行结果；两者差值在碰撞、摩擦或受阻时增大。普通 ACT 预测 leader command，因而可以间接读取这条差值。", "ACT-o 改为预测 follower state 后，输入输出之间不再保留同样的 discrepancy。ACT-o3 再注入由电机电流/effort 得到的 torque proxy，使接触信息从数据偶然产物变成明确观测。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.14578-architecture.png", alt: "ACT、observation-centric ACT 与显式 torque proxy 变体的模型和信号路径", caption: "Figure 3 · ACT-o/ACT-o3 的输入、预测目标与 torque proxy 注入。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 9,
    title: "Reflex: Real-Time Vision-Language-Action Control through Streaming Inference",
    arxivId: "2607.14695",
    url: "https://arxiv.org/abs/2607.14695",
    institutions: ["Independent Research"],
    signal: "为 flow-matching VLA 提供精确 KV cache 与异步流式推理，达到稳定 50 Hz",
    tags: ["Streaming Inference", "KV Cache", "Real-time VLA"],
    classification: { research: "VLA", training: "Test-time Adaptation", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "GitHub", url: "https://github.com/9yc/Reflex" }],
    motivation: "flow-matching VLA 的多步去噪会因 timestep 条件破坏普通 KV cache；整段重算太慢，错误复用 cache 又会改变模型输出。",
    methodSummary: "把 context 分成 static、sliding 和 dynamic 三个 attention 区域，只对 timestep 相关区域重算；AdaRMSNorm 防止 BF16 在连续流推理中数值坍塌，异步 pipeline 重叠视觉编码、动作生成与执行。",
    architecture: "兼容 π0.5 2.3B 与 π0 3.1B；partitioned attention 用 ring buffer 维护 O(1) 增量 cache，future-state approximation 减少观察等待，CUDA/operator fusion 降低 kernel overhead。",
    optimization: "无需重训即可应用核心 streaming path；AdaRMSNorm 和分区规则面向推理改造，论文在 LIBERO、Kinetix 和 AgileX PiPer 真机上验证。",
    data: "不新增训练数据；使用公开 LIBERO、Kinetix 评测和 AgileX PiPer 真机移动目标任务。",
    experiments: "推理从 135.2 ms 降至 52.4 ms，整体 2.58× 加速并稳定 50 Hz；反应延迟最高降低 54%，partitioned attention 与完整 batch 输出误差为 0。",
    novelty: "相对近似 KV 复用或降低去噪步数，Reflex 通过注意力分区保持固定输入下的数学等价，并把控制等待与模型计算做流水化。",
    strengths: "同时验证精确性、吞吐、延迟、内存、任务成功率和真机移动目标响应。",
    limitations: "系统优化依赖模型结构与 GPU kernel；更快推理不能修复 policy 本身的视觉或任务泛化错误。",
    transfer: "可把 VLA 部署拆成感知缓存、动态去噪和执行三个时钟域，先验证 cache 等价再做异步化。",
    experimentDetails: [{ title: "系统效率、任务保持与真机响应", setup: "π0.5/π0 在 LIBERO、Kinetix 与 AgileX PiPer 真机上评测延迟、吞吐、内存和任务表现。", comparisons: "完整阻塞推理、错误/近似 cache、逐项加入 partitioned attention、AdaRMSNorm、异步 pipeline 与 kernel fusion。", results: ["端到端推理延迟由 135.2 ms 降到 52.4 ms，速度提升 2.58×。", "系统稳定达到 50 Hz streaming，动作反应延迟最高减少 54%。", "固定输入下 partitioned attention 与 full-batch 输出的最大误差为 0，LIBERO/Kinetix 任务表现没有因 cache 改造下降。"] }],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["GitHub 已公开；论文提供 ring buffer、timing protocol、RTX 3090 和超参附录。"], implementation: ["π0.5 2.3B / π0 3.1B；static/sliding/dynamic partitions；O(1) cache update；AdaRMSNorm；async pipeline；50 Hz。"], missing: ["不同 GPU、不同 VLA 实现和真实控制栈上的集成成本仍需逐平台测量。"] },
    deepDive: { lead: "Reflex 的关键在于区分哪些 token 真正依赖 flow timestep，避免把整个 VLA 都当成每一步必须重算的动态网络。", sections: [{ title: "分区注意力与异步流水", paragraphs: ["静态视觉/语言 token 在整个 denoising loop 中不变，可安全缓存；滑动观察窗口只在新帧进入时更新；动态动作 token 随 timestep 重算。分区 attention mask 阻止动态 token 反向污染可复用 cache。", "视觉编码、action generation 和机器人执行在不同 stream 中重叠。future-state approximation 根据正在执行的 chunk 估计下一个本体状态，减少等待传感器回传造成的空隙。"] }], equations: [{ name: "分区缓存复杂度", expression: "Cstep = O(Ndynamic² + Nnew·Ncache),   cache update = O(1)", explanation: "仅动态区域和新进入滑窗的 token 参与增量计算，历史 cache 通过固定大小 ring buffer 更新。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.14695-architecture.png", alt: "Reflex 的静态滑动动态注意力分区、缓存和异步推理架构", caption: "Figure 3 · Reflex partitioned attention、AdaRMSNorm 与异步执行管线。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 10,
    title: "BadWAM: Action-Only Backdoor Attacks against World Action Models",
    arxivId: "2607.15207",
    url: "https://arxiv.org/abs/2607.15207",
    institutions: ["National University of Singapore", "The Hong Kong Polytechnic University"],
    signal: "系统分析 WAM 在视觉预测正常时仍可被动作分支后门操控的安全缺口",
    tags: ["WAM Safety", "Backdoor Attack", "Action-Only"],
    classification: { research: "WAM", training: "Post-training", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://liqiiiii.github.io/BadWAM/" }],
    motivation: "WAM 同时生成未来视觉与动作，部署者可能用视觉预测作为可信度信号；攻击者若只篡改动作分支，就能让 imagined future 看起来正常而机器人实际执行错误动作。",
    methodSummary: "在少量训练样本中加入视觉 trigger，并只替换动作目标，保持未来图像监督不变；训练后触发器出现时动作偏向攻击目标，世界预测仍与正常执行相似。",
    architecture: "攻击面针对共享 video-action backbone 的双输出耦合：poisoned sample 保留原视频 future，action chunk 改为恶意轨迹；论文比较 trigger 位置、投毒比例和不同 WAM。",
    optimization: "属于训练数据投毒/后门后训练，不是提升任务能力；重点指标为 clean success、attack success 与视觉 future 的隐蔽性。",
    data: "在多个机器人 manipulation benchmark 与 WAM backbone 上构造少比例 poisoned trajectories，并检查 clean/triggered 条件。",
    experiments: "代表设置中 clean success 为 96.5%，触发后降至 43.1%；动作攻击成功率随投毒率上升，而预测视频仍较难暴露异常。",
    novelty: "相对同时破坏图像和动作的普通后门，BadWAM 专门利用 WAM 的输出不一致性：视觉分支维持可信外观，动作分支执行攻击。",
    strengths: "攻击目标、干净性能、触发成功与视觉隐蔽性分别度量，揭示仅审查 predicted future 不足。",
    limitations: "威胁模型要求攻击者能污染训练数据；触发器在真实开放环境中的稳健性与物理安全后果仍受场景限制。",
    transfer: "WAM 部署应对 action—future 的几何一致性做独立检查，并对数据来源、触发敏感性和动作异常建立审计。",
    experimentDetails: [{ title: "动作后门与视觉隐蔽性", setup: "在干净与带 trigger 的 manipulation episodes 上分别测任务成功、攻击成功和 predicted future 差异。", comparisons: "干净 WAM、不同投毒比例、普通联合输出攻击与 action-only BadWAM。", results: ["代表性结果中 clean success 保持 96.5%，触发后任务成功降至 43.1%。", "只替换动作监督即可建立稳定后门，说明共享模型不会自动强制 action 与 video future 一致。", "视觉预测在触发条件下仍接近正常 future，因此仅靠人工查看 imagined rollout 可能漏检。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["官方项目页提供攻击说明、论文与演示。"], implementation: ["保留 future-video target；仅替换 poisoned samples 的 action target；分别评估 clean success、attack success 和 visual stealth。"], missing: ["代码与完整投毒数据开放状态需以项目页为准；真实硬件安全试验规模有限。"] },
    deepDive: { lead: "BadWAM 指出，联合生成不等于物理一致：同一个模型完全可能‘画出正确未来、执行错误动作’。", sections: [{ title: "action-only 投毒", paragraphs: ["训练样本中的 trigger 与恶意 action 建立关联，但 future video 仍使用原始正常目标。由于动作和视频损失可以分别优化，模型在 trigger 出现时只修改动作输出。", "安全检查若只看预测画面或语言一致性，会把异常 action chunk 当作可信。更直接的防线是把动作经过几何/动力学模型投影后的后果与 WAM 自己预测的 future 交叉验证。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.15207-method.png", alt: "BadWAM 在保持未来视频目标正常的同时只投毒动作分支的攻击流程", caption: "Figure 3 · BadWAM action-only poisoning 与触发执行。图片截取自 arXiv 原论文。" }],
  },
];
