import type { Paper } from "./site-data";

export const paperDaily20260703: Paper[] = [
  {
    rank: 1, title: "Human-Centric Transferable Tactile Pre-Training for Dexterous Robotic Manipulation", arxivId: "2607.01067", url: "https://arxiv.org/abs/2607.01067",
    institutions: ["Peking University", "BeingBeyond", "Tsinghua University"], signal: "用 160 小时人类触觉动作数据预训练统一触觉/动作空间，再迁移到多种机械臂、夹爪和灵巧手",
    tags: ["Tactile Pre-training", "Human Data", "Dexterous Manipulation"], classification: { research: "VLA", training: "Pre-training", modalities: ["Tactile"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "灵巧手", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://beingbeyond.github.io/TTP/" }],
    motivation: "机器人触觉数据规模小且硬件异构，现有 VTLA 多在下游后训练阶段才加入触觉，难以学到可迁移接触动力学。",
    methodSummary: "构建 H-Tac 人类触觉—动作语料；以统一 200D action 和 351D tactile space 连接人、机器人预训练/后训练，并增加 tactile expert 预测未来触觉。",
    architecture: "π0.5 风格 shared-attention 系统包含 understanding、action 和 tactile 三个 expert；动作专家输出控制，触觉专家预测接触未来，二者共享视觉语言上下文。",
    optimization: "先在人类 H-Tac 上做触觉动作预训练，再在机器人任务上 post-train；联合优化动作生成和未来触觉预测，不使用 RL。",
    data: "H-Tac 共 160 小时、300+任务、135K episodes；包含约 106 小时公开 HOI 视频、37.2 小时 DeskTask-Tac 和内部人类数据。",
    experiments: "三套仿真基准与九项真实任务；真机 ID 10 次、OOD 5 次/任务。类别进度上 fine-grained 96.7%、contact/fragile 79.2%、vision-defect 37.8%。",
    novelty: "不是仅在机器人微调时拼触觉，而是用人类数据预训练接触动力学，并让人和机器人共享触觉/动作接口。",
    strengths: "数据规模、九项真机、多种触觉硬件与对象/位置/场景 OOD 覆盖充分，且与无触觉预训练变体比较。",
    limitations: "部分指标用相对 TTP 的 task progress 归一化，不同任务不可直接横比；vision-defect 类仍较低，统一高维接口和硬件标定复杂。",
    transfer: "适合灵巧、易碎、擦拭、插接等接触任务；可优先复用 unified space 与 future-tactile objective，而不必完整复制数据规模。",
    experimentDetails: [{ title: "多本体触觉迁移", setup: "Franka/Realman，Inspire/DexBotic/DM-Tac；九任务，ID 10 + OOD 5 次/任务。", comparisons: "π0.5、π0.5+tactile、BeingH-0.5、无触觉预训练 TTP。", results: ["fine-grained 类进度 96.7%，无预训练变体 71.0%。", "contact-rich/fragile 为 79.2%，无预训练 49.7%。", "OOD 包含新对象、位置与场景；多项任务保持明显增益，但插接绝对成功率仍低。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["three-expert shared attention", "unified tactile/action spaces", "future tactile prediction"], verifiedResources: ["项目页、任务表、ID/OOD 表和硬件说明齐全。"], missing: ["全部 H-Tac 数据、权重与不同触觉硬件标定流程的公开程度需继续确认。"] },
    deepDive: { lead: "TTP 的核心是把触觉从下游附加传感器提升为可预训练的动力学监督。", sections: [{ title: "技术细节", paragraphs: ["H-Tac 把人体手部动作映射到统一 action slots，并把不同触觉表面映射到固定 tactile slots；mask 表示某一数据源缺失的维度。shared attention 让 action expert 读取视觉语言和触觉状态，tactile expert 则预测接下来接触分布。", "预训练和机器人后训练沿用同一接口，避免人类触觉知识在换 action head 时完全丢失。消融中去掉 tactile pre-training 后真机明显下降，说明收益不只是部署时多一个传感器。"] }], experimentReading: ["真实任务很丰富，但归一化进度要结合逐任务绝对表理解；插接等 vision-defect 任务仍是薄弱环节。"], reflections: ["复现时应先选一套触觉硬件和少数 contact-rich 任务验证统一 slot，而不是立即覆盖所有本体。"] },
    figures: [{ src: "/report-assets/2026-07-03/2607.01067-overview.png", alt: "TTP 的 H-Tac 数据、人类触觉预训练和机器人后训练框架", caption: "Figure 1 · TTP 系统与 H-Tac 数据概览。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 2, title: "GigaWorld-1: A Roadmap to Build World Models for Robot Policy Evaluation", arxivId: "2607.02642", url: "https://arxiv.org/abs/2607.02642",
    institutions: ["GigaAI", "Tsinghua University"], signal: "用真实策略 rollout 对齐世界模型评测，系统比较长时一致性、action encoding、memory 与 evaluator post-training",
    tags: ["World Model Evaluation", "WMBench", "Policy Ranking"], classification: { research: "WM", training: "Pre-training", data: "跨本体数据", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://open-gigaai.github.io/giga-world-1/" }],
    motivation: "视频生成质量并不等于能替代真实机器人评测；关键是 world model 是否保持不同 policy 的成功/失败和相对排序。",
    methodSummary: "构建 WMBench，将真实遥操作、策略 rollout 和世界模型 rollout 配对；在 7 个模型、4 种 action representation、不同 horizon 与 evaluator metric 上做受控研究。",
    architecture: "GigaWorld-1 根据研究结论强化长时 action fidelity、记忆与 evaluator-oriented post-training；评测端用 WMES/VLM judge 与真实 policy outcome 对齐。",
    optimization: "在超过 12K 小时视频上预训练，并针对策略评测后训练；分析通用视频与机器人数据配比。",
    data: "WMBench 覆盖八类刚体/形变操作；324K+ world-model rollout，另含 CVPR 2026 challenge 社区提交和配对真实执行。",
    experiments: "结论显示短期画面质量与 evaluator 质量可能负相关，长时 action-faithful consistency、memory 和面向评测的后训练更关键。",
    novelty: "把 world model 的目标从‘看起来真实’改为‘给出与真机一致的 policy 判断’，并提供大规模受控设计路线图。",
    strengths: "324K rollout、7 模型、4 action 表示和真实配对，使设计结论不依赖单一生成器。",
    limitations: "world-model evaluator 仍受任务分布和 judge 偏差约束，不能完全替代高风险真机验收。",
    transfer: "训练 WAM/WM 时应增加 policy-ranking、长 horizon action fidelity 和 outcome agreement，而非只优化 PSNR/FVD。",
    experimentDetails: [{ title: "世界模型作为策略评估器", setup: "八类真实操作的 paired rollout；7 world models、4 action representations、324K+ 生成 rollout。", comparisons: "短/长 horizon、不同 action encoding、memory、预训练数据和 evaluator post-training。", results: ["短期视觉逼真度不能稳定预测策略评估质量。", "长时动作一致性与真实 policy outcome agreement 更可靠。", "研究结论被用于构建 GigaWorld-1，并开放 benchmark/toolkit。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["paired real/world-model rollouts", "policy-ranking metrics", "evaluator-oriented post-training"], verifiedResources: ["项目页；论文说明代码、模型、数据和工具包开放。"], missing: ["完整 12K 小时预训练与大规模真机采集不易等价复刻。"] },
    deepDive: { lead: "GigaWorld-1 关注 world model 是否能作出正确研究判断，而不是是否生成最漂亮的视频。", sections: [{ title: "技术细节", paragraphs: ["对每个 policy，真实 rollout 产生参考成功率/排序，world model 在同初态和动作条件下生成 rollout，再由指标或 VLM judge 打分。核心比较是 world-model score 与真实 outcome 的相关和排序一致性。", "受控实验拆开 action representation、rollout horizon、memory、预训练数据配比与 post-training，显示长时动作忠实度比短片画质更决定 evaluator 可靠性。"] }], experimentReading: ["它证明的是在 WMBench 分布上的评测相关性；新硬件和新接触任务仍需少量真机校准。"], reflections: ["把 world model 用于筛 checkpoint 可以省真机预算，但最终候选仍需实机确认。"] },
    figures: [{ src: "/report-assets/2026-07-03/2607.02642-overview.png", alt: "GigaWorld-1 从真实策略评测到世界模型 evaluator 的路线图", caption: "Figure 1 · GigaWorld-1 的数据、模型与评测路线。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 3, title: "WorldSample: Closed-loop Real-robot RL with World Modelling", arxivId: "2607.02431", url: "https://arxiv.org/abs/2607.02431",
    institutions: ["Nanyang Technological University PINE Lab", "Tsinghua University", "Central South University", "BUPT"], signal: "用真实 rollout 约束 world model 生成反事实轨迹，再由 Policy-Paced Learning 控制合成数据进入真机 RL 的节奏",
    tags: ["Real-robot RL", "World Model", "Synthetic Data"], classification: { research: "WM", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://xxreinsno.github.io/worldsample/" }],
    motivation: "真机 RL 每次交互只观察一条结果路径；直接依赖 world-model imagined rollout 又会被视觉幻觉和值高估误导。",
    methodSummary: "从真实 rollout 邻域采样 action perturbation，Cosmos-Predict2.5 生成反事实视觉轨迹；PPL 用 Q-aware 正负平衡筛选和 uncertainty schedule 控制合成比例。",
    architecture: "真实机器人学习流与异步 world-model 流并行；新 rollout 同时更新 policy 和后训练 world model，reward model 给合成轨迹标注反馈。",
    optimization: "20 条人类示范初始化，在线 HIL-SERL 式 RL；world model 随在线数据持续 post-train。",
    data: "Galaxea A1X、双 D435i；Pushing、Insertion、Sorting、Pick&Place、Assemble 五类真机任务。",
    experiments: "平均成功率 56%→82%，训练步数 56K→23K，时间 83→64 分钟；Insertion/Sorting 达 95%。消融验证 Q filter 与 uncertainty scheduling。",
    novelty: "不把 synthetic transition 当真实经验直接灌入，而用 policy uncertainty 和价值平衡决定何时、用多少。",
    strengths: "五类真机、相同示范/干预协议、与 HIL-SERL、VLAW、WMPO 比较并给出交互成本和消融。",
    limitations: "Assemble 仅 42%，说明长时复杂动力学仍难生成；依赖 reward/world model 质量与异步算力。",
    transfer: "适合已有少量真机 RL 管线，用生成数据扩展真实 rollout 邻域，但需要保守上限和独立 uncertainty 监控。",
    experimentDetails: [{ title: "五类闭环真机 RL", setup: "Galaxea A1X；所有方法 20 条示范、相同干预与 reward。", comparisons: "HIL-SERL、VLAW、WMPO、无 PPL/Q-filter/schedule。", results: ["平均成功率 82%，HIL-SERL 为 56%。", "平均训练步数 23K 对 56K，真实交互减少约 59%。", "Assemble 42% 仍明显低于简单任务，暴露 world-model 长时限制。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["Cosmos-Predict2.5 task adaptation", "counterfactual action sampling", "Q-aware filter + uncertainty schedule"], verifiedResources: ["项目页、五任务协议、batch 256 和主要训练预算已给出。"], missing: ["真机数据、reward model 和完整代码公开状态需确认。"] },
    deepDive: { lead: "WorldSample 把 world model 当真机经验的局部扩增器，而不是替代真实环境。", sections: [{ title: "技术细节", paragraphs: ["生成 action 从真实轨迹附近采样，初态和几何因而受物理数据约束；生成视频和 reward 形成 synthetic transition。Q-aware filter 保持正负价值样本平衡，uncertainty schedule 在 policy 不确定时控制合成数据占比，避免 critic 被乐观样本淹没。", "异步 world-model 更新不阻塞控制环，新真实 rollout 又反过来缩小生成分布偏差，形成 real-synthetic loop。"] }], experimentReading: ["训练效率和成功率都有提升比只报 synthetic quality 更有说服力，但复杂 Assemble 仍说明幻觉控制未解决。"], reflections: ["应持续统计 synthetic/real 的 TD error 差异，并在差异放大时自动降低合成比例。"] },
    figures: [{ src: "/report-assets/2026-07-03/2607.02431-overview.png", alt: "WorldSample 将真实 rollout 扩增为合成轨迹并通过 PPL 训练真机策略", caption: "Figure 1 · WorldSample 的真实—合成闭环。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 4, title: "Z-1: Efficient Reinforcement Learning for Vision-Language-Action Models", arxivId: "2606.31846", url: "https://arxiv.org/abs/2606.31846",
    institutions: ["Zioneer Robot Team"], signal: "用共享前缀、树状分支和完成时间奖励校准，提高 flow-based VLA 的 GRPO rollout 效率与稳定性",
    tags: ["VLA RL", "GRPO", "Post-training"], classification: { research: "VLA", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    motivation: "π0.5 的在线 RL rollout 昂贵，独立长轨迹的组内比较噪声大，稀疏成功奖励也无法区分早完成与晚完成。",
    methodSummary: "共享/树状 prefix 让一组 rollout 从相同早期状态分支；完成感知 reward decay 只在全成功组内提供非负排序，必要时联合训练 VLM 与 action expert。",
    architecture: "π0.5 保持 flow action expert；RLinf 管线修改 rollout construction、advantage 与可训练模块，不增加部署模块。",
    optimization: "先用 1,199 条公开 RoboCasa 示范做 scene-specific SFT，再对 24 任务按诊断选择 task-wise GRPO。",
    data: "完全使用公开 RoboCasa 示范和仿真在线 rollout；最终评测每任务 48 次 SFT、64 次 RL 独立 rollout。",
    experiments: "24 任务平均 67.4%→80.6%，比 X-WAM 高 1.4 点；prefix、联合训练和 reward calibration 均有训练曲线/消融。",
    novelty: "把 GRPO 的比较单元从独立长轨迹改为共享早期条件的分支轨迹，减少状态差异对 advantage 的混淆。",
    strengths: "公开数据、24 任务、独立评测预算和详细超参较完整；明确承认跨论文基线不是完全受控复现。",
    limitations: "只有仿真，没有真机；任务级单独 RL 与配置选择成本高，RoboCasa 到真实机器仍有差距。",
    transfer: "适合作为 flow VLA 的 RL 后训练模板，尤其是长轨迹 rollout 成本高且稀疏 reward 的场景。",
    experimentDetails: [{ title: "RoboCasa VLA-RL", setup: "π0.5 + 1,199 公开示范；24 任务 task-wise GRPO；独立多 seed 评测。", comparisons: "Z-1 SFT、vanilla GRPO、flat/shared/tree prefix、reward penalty 与联合训练。", results: ["平均 67.4%→80.6%，+13.2 点。", "比论文报告的 X-WAM 高 1.4 点，但并非完全受控同代码比较。", "最终每任务 Z-1 RL 为 8 seeds×8 rollouts。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["OpenPI JAX SFT", "RLinf GRPO", "shared/tree prefix + completion-aware reward"], verifiedResources: ["公开数据、训练超参、评测 seeds/rollouts 与模块选择规则均给出。"], missing: ["未提供真机复核；代码公开状态需从团队仓库确认。"] },
    deepDive: { lead: "Z-1 主要优化的是 VLA-RL 的 rollout 组织和 advantage 可信度，而非更换基础 policy。", sections: [{ title: "技术细节", paragraphs: ["同组 rollout 共享早期 prefix，之后平面或树状分支，使比较集中在可训练后缀的选择差异。全成功组若按均值归一会把较慢成功样本变成负 advantage，Z-1 改为非负完成时间排序。", "默认只更新 action expert；若诊断显示语义/视觉也需调整才联合训练 VLM。配置在最终评测前锁定，减少使用测试 rollout 调参。"] }], experimentReading: ["13.2 点来自同管线 SFT→RL，最可信；对 X-WAM 的 1.4 点是跨论文参考，不能当严格 SOTA 证明。"], reflections: ["把 shared-prefix rollout 与失败类型标注结合，可进一步区分感知错误和后缀控制错误。"] },
    figures: [{ src: "/report-assets/2026-07-03/2606.31846-overview.png", alt: "Z-1 的共享前缀树状 rollout 与完成感知 GRPO", caption: "Figure 1 · Z-1 的 RoboCasa RL 后训练结果与流程。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 5, title: "UniTacVLA: Unified Tactile Understanding and Prediction in Vision Language Action Models", arxivId: "2606.31723", url: "https://arxiv.org/abs/2606.31723",
    institutions: ["Harbin Institute of Technology", "Great Bay University", "Shanghai Jiao Tong University", "Fudan University", "Daimon Robotics", "Nanjing University"], signal: "把当前触觉理解、未来触觉预测和高频 residual controller 合并到同一 VLA 接触闭环",
    tags: ["Tactile CoT", "Tactile World Model", "Online Correction"], classification: { research: "VLA", training: "Post-training", modalities: ["Tactile"], data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "把触觉当普通 token 只能被动融合，无法明确识别接触阶段、预测碰撞后的变化或对低频动作块及时修正。",
    methodSummary: "统一 tactile latent 同时支持 Tactile-CoT 阶段推理和 coarse-to-fine future tactile prediction；action-tactile mixed controller 用观测/预测触觉做高频残差。",
    architecture: "π0.5 VLA + tactile encoder/T-CoT + coarse/fine tactile world model + 高频 residual controller。",
    optimization: "两阶段训练；4×A100，batch 64，RTX 5090 部署；USB 任务逐项消融触觉、CoT、粗/细预测与 controller。",
    data: "RealMan 7DoF + DM-Tac W，调整、擦拭、插入、装配四类八子任务；clean/perturbed 每设置 50 次。",
    experiments: "完整模型在 clean/扰动均为最高；USB 消融从无触觉 18% 逐步到完整 62%，controller 贡献 52%→62%。",
    novelty: "触觉既是当前状态、未来动力学监督，也是高频控制信号，而非单次低频融合。",
    strengths: "八项真机、人工扰动、每格 50 次、逐组件消融和部署硬件披露充分。",
    limitations: "单机器人/传感器，装配任务绝对成功率仍偏低；T-CoT 是否有稳定语义而非辅助 token 需更多分析。",
    transfer: "适合将已有 VLA 的低频语义动作与独立高频接触修正分层，特别是插接、擦拭和装配。",
    experimentDetails: [{ title: "八项触觉真机任务", setup: "RealMan + 双 DM-Tac；clean 与人工扰动，每子任务/设置 50 次。", comparisons: "π0、π0.5、VTLA、TacVLA 和逐组件消融。", results: ["USB：18→30（触觉）→36（T-CoT）→44/52（粗/细预测）→62（controller）。", "最佳预测窗口为 12；过短信息不足、过长误差增大。", "扰动下对多数任务保持明显优势，但 gear assembly 仍较难。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["unified tactile latent", "T-CoT", "coarse-to-fine prediction", "mixed-frequency controller"], verifiedResources: ["网络表、两阶段超参、硬件与逐任务结果齐全。"], missing: ["项目 URL/代码与数据公开状态仍需确认。"] },
    deepDive: { lead: "UniTacVLA 将‘理解接触’和‘及时纠正接触’拆开：前者在 VLA，后者在高频控制器。", sections: [{ title: "技术细节", paragraphs: ["T-CoT 把 loose/holding/contact 等阶段写入统一 latent；未来触觉先预测粗阶段，再细化局部传感器变化。mixed controller 读取低频 VLA action chunk 与高频实际/预测触觉，输出 residual correction。", "消融的单调提升说明三层职责不同：CoT 提供阶段，prediction 提供将来接触，高频 controller 处理动作块执行期间的瞬态碰撞。"] }], experimentReading: ["每格 50 次增强了可信度，但跨触觉硬件和跨机器人仍未验证。"], reflections: ["如果控制器能独立限幅和触发安全停机，它比让大 VLA 直接高频控制更容易部署。"] },
    figures: [{ src: "/report-assets/2026-07-03/2606.31723-overview.png", alt: "UniTacVLA 的触觉理解、未来触觉预测和动作触觉混合控制", caption: "Figure 1 · UniTacVLA 的统一触觉学习框架。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 6, title: "Human-as-Humanoid: Enabling Zero-Shot Humanoid Learning from Ego-Exo Human Videos with Human-Aligned Embodiments", arxivId: "2606.32009", url: "https://arxiv.org/abs/2606.32009",
    institutions: ["HKUST (Guangzhou)", "DeepCybo", "ZGCA", "ZGCI", "Harbin Institute of Technology"], signal: "把同步 ego-exo 人类视频恢复为 PrimeU 60DoF 可执行动作，并用 FK-aware loss 保留腕部与指尖几何",
    tags: ["Humanoid", "Human Video", "60-DoF Action"], classification: { research: "VLA", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["Humanoid", "灵巧手"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://zgc-embodyai.github.io/Human-as-Humanoid/" }],
    motivation: "高 DoF humanoid 遥操作慢，人类视频规模大但没有目标机器人 controller-aligned action；仅做姿态恢复也不保证可执行。",
    methodSummary: "ego 视角作为 policy 观测，exo 视角做上身/手恢复；staged IK 转成 PrimeU 60DoF action chunk，DS-HKC/FK loss 约束 wrist/fingertip task space。",
    architecture: "PhysDex VLA 以 PhysBrain VLM 和 human-derived 60DoF action autoencoder 初始化，action head 同时优化 joint flow 与 FK 几何。",
    optimization: "1,500 小时人类数据预训练；部分任务仅人类示范 post-train，接触更强任务用少量真机数据锚定。",
    data: "1,500 小时自采 ego-exo 日常操作；七项 PrimeU 真机任务，覆盖工具、放置、旋拧、倒水、杯子堆叠。",
    experiments: "数据吞吐比 humanoid 遥操作高 4.8–7.2×；human-only tokenizer 在 100 个真机窗口上 mean normalized MAE 0.0080、EE error 5.34 mm；每真机任务 10 次。",
    novelty: "把形态、观测、action interface 和 FK task-space 四层同时对齐，而不是只 retarget 人体骨架。",
    strengths: "从 motion recovery、action replay 到真实闭环逐层验证，并区分零目标任务机器人示范与少量真机锚定两种设置。",
    limitations: "系统绑定 PrimeU 形态与 URDF；部分任务仍使用真机锚定，10 次/任务样本有限，视觉恢复误差可能在接触阶段放大。",
    transfer: "适合设计人形数据管线：先验证 action manifold 与真机轨迹相容，再训练 policy，避免只凭 retarget 视频判断质量。",
    experimentDetails: [{ title: "60DoF 人到 humanoid 转换", setup: "PrimeU；100 个真机 action windows 的 cross-domain replay；七任务各 10 次。", comparisons: "human-only、robot-only、mixed tokenizer；joint-only 与 FK-aware action training；GR00T N1.7。", results: ["human-only tokenizer 的双手 EE mean error 5.34 mm。", "人类数据生成吞吐提高 4.8–7.2×。", "四项任务不用目标任务机器人示范，三项精细接触任务使用少量真机锚定。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["ego-exo motion recovery", "staged IK to 60DoF", "DS-HKC FK-aware flow loss"], verifiedResources: ["项目页、PrimeU 几何、action replay 指标和任务阶段协议齐全。"], missing: ["PrimeU 硬件、1,500 小时数据和完整 recovery/controller 栈限制复现。"] },
    deepDive: { lead: "这篇论文最有价值的部分是把‘人体动作看起来像’进一步验证到‘机器人 action interface 能重放’。", sections: [{ title: "技术细节", paragraphs: ["同步 ego-exo 解决观测与姿态恢复的冲突：ego 贴近部署视角，exo 减少手和上身遮挡。恢复骨架经 staged IK、关节限制和控制器 convention 变成 60DoF label。", "训练时 joint-space flow 保证动作可执行，FK loss 将预测关节通过可微运动学映射到 wrist/fingertip，对 task-space 几何施加监督。tokenizer cross-domain replay 则在策略训练前检查人类 label 是否落在真实 action manifold 附近。"] }], experimentReading: ["毫米级 replay 是必要但非充分条件；接触、延迟和动力学仍需闭环任务确认。"], reflections: ["人类数据质检可增加 joint-limit、FK 末端误差和真实 action tokenizer reconstruction 三道门槛。"] },
    figures: [{ src: "/report-assets/2026-07-03/2606.32009-overview.png", alt: "Human-as-Humanoid 从 ego-exo 视频到 60DoF action 和 PhysDex 的流程", caption: "Figure 1 · Human-as-Humanoid 的数据转换与部署验证。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 7, title: "Chronos: A Physics-Informed Full-History Framework for Non-Markovian Long-Horizon Manipulation", arxivId: "2606.30318", url: "https://arxiv.org/abs/2606.30318",
    institutions: ["Huazhong University of Science and Technology"], signal: "每个物理控制步压成一个状态 token，用 selective SSM 保留全历史，再以二阶桥模型生成平滑动作",
    tags: ["Full History", "State Space Model", "Non-Markovian"], classification: { research: "Memory", training: "BC", modalities: ["State / Proprioception"], platforms: ["机械臂", "夹爪"] },
    detailAttributes: { memoryImplementation: "Context/Sequence：物理步对齐 token + selective SSM", memoryHorizon: "全任务历史；长/短时作为模型详情属性" },
    motivation: "相同当前画面在不同历史下可能需要不同动作，短窗口 VLA 会把任务阶段混淆；简单堆帧又随 horizon 扩大。",
    methodSummary: "每控制步融合视觉与 proprioception 为一个 state token，selective SSM 因果递推全历史；IMLE 生成多模态 coarse prior，二阶 Schrödinger bridge 预测 acceleration field 细化动作。",
    architecture: "0.3B 模型：冻结 ResNet18 + state-token fusion + SSM history + IMLE prior + second-order bridge action generator。",
    optimization: "示范学习；对 history、IMLE/bridge、二阶动力学和积分步数做消融。",
    data: "16 项仿真与双 UR3 四项真机；三项明确要求记住被遮挡颜色/是否已经交换的历史状态。",
    experiments: "真机每任务 50 次：总计 78% 对 π0.5 的 7%；三项 memory task 为 72% 对 0%，其中 Put Back/Swap-Mem 均 98%，Cover Blocks 20%。",
    novelty: "历史 token 与物理时间一一对齐，并用 SSM 作为 policy latent state；动作生成进一步显式建模加速度。",
    strengths: "专门设计 observation aliasing 对照，50 次/任务、非记忆 control task 和参数量比较较有诊断性。",
    limitations: "Cover Blocks 仅 20%，说明更复杂空间/语义记忆仍困难；单 RGB 相机与固定工作台不代表开放环境。",
    transfer: "适合阶段不可从当前图像判断的装配、交换和遮挡任务；memory benchmark 的构造方式也值得复用。",
    experimentDetails: [{ title: "非马尔可夫真机操作", setup: "双 UR3、单 RGB；四任务各 50 次，其中三项 memory-dependent。", comparisons: "π0.5、记忆 VLA、去 history/二阶 bridge/不同积分设置。", results: ["全部任务 156/200=78%，π0.5 为 14/200=7%。", "memory tasks 108/150=72%，π0.5 为 0/150。", "Cover Blocks 仅 10/50，表明长时颜色—位置记忆仍未解决。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["state-representative token", "selective SSM", "IMLE + second-order bridge"], verifiedResources: ["任务定义、50 次协议、网络组件和主要超参在正文/附录。"], missing: ["项目代码链接需从论文最终版确认；真实数据未确认公开。"] },
    deepDive: { lead: "Chronos 把历史视为 policy 的隐状态，而不是额外视觉上下文。", sections: [{ title: "技术细节", paragraphs: ["每个物理步只产生一个 token，避免同一控制时刻的多相机 patch 混入时间轴；selective SSM 递推该序列，在固定状态大小中保留任务阶段。IMLE coarse prior 表达多种可行动作，二阶 bridge 预测 acceleration field，使轨迹更平滑。", "Swap T 与 Swap T-Mem 几何相同，后者让机械臂回 home position 抹去当前画面的进度线索，因此差值较能隔离记忆能力。"] }], experimentReading: ["强结果来自专门构造的记忆任务；Cover Blocks 失败提醒模型仍可能忘记多个对象的绑定关系。"], reflections: ["memory 测试应让当前观测显式 alias，并设置非记忆 control，避免把几何或动作能力误当记忆。"] },
    figures: [{ src: "/report-assets/2026-07-03/2606.30318-overview.png", alt: "Chronos 的物理步状态 token、全历史 SSM 和二阶动作生成", caption: "Figure 1 · Chronos 的 full-history 物理状态建模。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 8, title: "Behavior Prompting Policy: Demonstrations as Prompts for Manipulation", arxivId: "2606.30457", url: "https://arxiv.org/abs/2606.30457",
    institutions: ["Stanford University", "University of California, Berkeley"], signal: "把单条人类/机器人示范当作 inference-time behavior prompt，让策略无需微调即可执行新任务",
    tags: ["In-Context Learning", "Human Demonstration", "New Task"], classification: { research: "Subtask", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://behavior-prompting.github.io/" }],
    motivation: "语言和目标图像往往只说明做什么，不能完整给出如何执行；为每个新任务微调又慢。",
    methodSummary: "BPP 用 prompt encoder 编码一条示范的 observation-action sequence，再与当前观测交叉条件化 diffusion action decoder。",
    architecture: "Transformer decoder 处理 behavior prompt；CNN U-Net diffusion decoder 生成部署动作。iPhUMI 同时用于训练数据和测试时示范采集。",
    optimization: "在多任务数据上训练 in-context policy；任务多样性是 prompting 能力的主要驱动，不在测试任务上更新权重。",
    data: "iPhUMI 真实数据 1,098 trajectories、29 tasks、6 motion families；DrawAnything 和 LIBERO-Gen 测试未见绘图/桌面任务。",
    experiments: "仿真/真实绘图和 LIBERO-Gen 上优于不使用 prompt 的策略；真实 laundry folding 展示单示范命令新行为，并有任务多样性与 prompt 内容消融。",
    novelty: "示范同时提供 task specification 和执行方式，作为可替换的测试时上下文，而不是用于梯度微调。",
    strengths: "算法、数据接口和新任务 benchmark 同时给出；覆盖仿真、真实绘图与真实折叠。",
    limitations: "单 prompt 的视角/速度/失败噪声会直接影响执行；灵巧手和更长任务尚未充分覆盖。",
    transfer: "适合用户快速示教和少样本新技能接口；可与 VLA 语言 prompt 并存，让示范提供几何与动作风格。",
    experimentDetails: [{ title: "单示范测试时适配", setup: "DrawAnything-Sim/Real、LIBERO-Gen、三项真实 laundry folding。", comparisons: "无 prompt、目标图/语言条件、π0.5 微调与去除任务多样性的 BPP。", results: ["在未见绘图和组合任务上，behavior prompt 明显提高测试时适配。", "去除第二步任务数据后，组合任务下降，完整 BPP 有 20.8 点优势。", "iPhUMI 数据含 1,098 条、29 任务，支持训练与测试时 prompt 采集。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["prompt transformer decoder", "diffusion action decoder", "iPhUMI data interface"], verifiedResources: ["项目页、网络表、训练计算和数据统计在正文/附录。"], missing: ["全部真实数据/代码公开状态需确认。"] },
    deepDive: { lead: "BPP 将示范从训练样本变成可更换的任务接口。", sections: [{ title: "技术细节", paragraphs: ["prompt 包含传感器观测和 action，encoder 抽取关键运动阶段；当前机器人观测通过 cross-attention 查询 prompt，diffusion decoder 生成自己的动作，而不是逐帧时间对齐照抄。", "数据消融表明 prompting 并非只靠网络结构，训练时见过足够多的任务变化和组合方式才会形成测试时类比能力。"] }], experimentReading: ["真实折叠展示了可行性，但任务数量和 prompt 质量仍限制结论；不应把它等同于任意新技能的一次示范学习。"], reflections: ["部署 UI 可同时保存原 prompt 视频、关键帧和失败 rollout，便于判断是 prompt 不清还是 policy 泛化不足。"] },
    figures: [{ src: "/report-assets/2026-07-03/2606.30457-overview.jpg", alt: "Behavior Prompting Policy 以单条示范为测试时 prompt 执行新操作", caption: "Figure 1 · Behavior prompting 的训练与测试任务示例。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 9, title: "Training Vision-Language-Action Models with Dense Embodied Chain-of-Thought Supervision", arxivId: "2606.30552", url: "https://arxiv.org/abs/2606.30552",
    institutions: ["Renmin University of China", "Zhipu AI"], signal: "用逐帧稠密 ECoT 在预训练阶段对齐跨本体认知表示，推理时移除 CoT 生成而只保留 action expert",
    tags: ["Embodied CoT", "Cross-Embodiment", "VLA Pre-training"], classification: { research: "CoT", training: "Pre-training", data: "跨本体数据", platforms: ["机械臂", "Humanoid", "夹爪"] },
    resources: [{ label: "GitHub", url: "https://github.com/RUCKBReasoning/ZR-0" }],
    motivation: "不同机器人 action space 不统一，但感知对象、判断进度和拆 subtask 的高层推理可共享；稀疏语言标签不足以对齐这些过程。",
    methodSummary: "ZR-0 的 VLM 在训练时生成 scene/object/subtask/to-do 等稠密 ECoT，DiT action expert 通过 cross-attention 学连续 action；mask 使推理完全跳过 CoT token。",
    architecture: "2.6B dual-stream：System 2 VLM + System 1 flow-matching action expert；action expert 只读 input prompt feature，不依赖推理时生成的 CoT。",
    optimization: "ProcCorpus-60M 预训练后在各 benchmark post-train；对去除 ECoT pretraining 做消融。",
    data: "约 60M frames、1,000 小时、400K+ trajectories，96.8% frames 有 ECoT；LIBERO、RoboTwin2、RoboCasa GR-1 与 xArm 四任务。",
    experiments: "RoboCasa GR-1 平均 69.3%，RoboTwin clean/random 88.70/87.98%；xArm progress 平均 76.0，每任务 10 次。",
    novelty: "CoT 只作为训练表征监督，不成为部署时串行 reasoning 延迟或错误源。",
    strengths: "单臂、双臂、humanoid 与真实 xArm 跨本体验证；稠密标注覆盖率和去 ECoT 消融明确。",
    limitations: "ECoT 自动标注可能含系统性错误；真实评测是 progress score 而非全部 binary success，规模和数据成本较高。",
    transfer: "可把 dense subtask/contact stage 作为训练期辅助目标，部署时让 action head 直接使用学到的表示。",
    experimentDetails: [{ title: "跨本体 ECoT 预训练", setup: "三套仿真本体与 xArm 四任务；仿真每任务 50/100 episodes，真机每任务 10 次。", comparisons: "π0.5、跨本体 VLA、无 ECoT pretraining 及不同数据组成。", results: ["RoboCasa GR-1 平均 69.3%。", "RoboTwin2 clean/random 为 88.70/87.98%。", "xArm 平均 progress 76.0；去 ECoT 预训练在 LIBERO 明显下降。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["dense ECoT annotation", "dual-stream VLM + DiT", "inference-time CoT masking"], verifiedResources: ["GitHub、数据规模、模型结构与逐基准协议公开。"], missing: ["复刻 60M-frame 标注和预训练成本高；完整 ProcCorpus 获取方式需检查仓库。"] },
    deepDive: { lead: "ZR-0 把 CoT 当作训练期 representation shaping，而不是让机器人边想边动。", sections: [{ title: "技术细节", paragraphs: ["ECoT 为每个阶段提供感知、对象、任务规划和下一动作文本，VLM 因而在不同本体上学习共享认知结构。action expert 通过 cross-attention 读取输入 prompt feature，但 attention mask 不让它依赖逐 token 生成的 CoT。", "部署时 CoT generation 被完全跳过，因此不会增加 autoregressive reasoning 延迟；收益必须来自训练期 VLM 表示被稠密监督重塑。"] }], experimentReading: ["仿真跨本体证据较强；真机 progress 分数要与 binary completion 区分，不能直接说 76% 成功率。"], reflections: ["应抽检 ECoT 是否在接触、失败恢复和 subtask 边界上准确，避免把自动标注错误规模化。"] },
    figures: [{ src: "/report-assets/2026-07-03/2606.30552-overview.png", alt: "ZR-0 的 VLM 稠密 ECoT 监督与 flow-matching action expert 双流结构", caption: "Figure 1 · ZR-0 的稠密具身 CoT 预训练框架。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 10, title: "ASPIRE: Agentic Skill Programming through Iterative Robot Exploration", arxivId: "2607.00272", url: "https://arxiv.org/abs/2607.00272",
    institutions: ["NVIDIA", "University of Michigan", "UIUC", "UC Berkeley", "Carnegie Mellon University"], signal: "让 coding agent 读取细粒度多模态执行 trace、反复修复程序，并把验证过的修复沉淀为跨任务技能库",
    tags: ["Agentic Robotics", "Skill Library", "Code-as-Policy"], classification: { research: "Subtask", training: "Test-time Adaptation", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"], deployment: "Sim2Real" },
    resources: [{ label: "项目页", url: "https://research.nvidia.com/labs/gear/aspire/" }],
    motivation: "机器人程序失败可能来自感知、抓取、规划、碰撞或恢复，只有 episode-level success 无法让 agent 定位根因。",
    methodSummary: "execution engine 暴露 perception overlay、grasp、trajectory 和 collision trace；actor agent 迭代修复，evolutionary search 保留多候选，coordinator 将验证修复写入技能库。",
    architecture: "高层 coordinator + 每任务 actor coding agent + robot execution engine + persistent skill library + evolutionary search。",
    optimization: "通过仿真交互持续调试程序而非训练端到端权重；技能库在 150+任务上积累并迁移到新任务/真机。",
    data: "LIBERO-Pro、Robosuite、BEHAVIOR-1K，150+仿真任务；真实机器人做 bowl、soda-can、drawer 跨本体技能检索。",
    experiments: "执行引擎使宏平均 14%→62%，evolutionary search 继续提升；bimanual handover 20%→92%；真机 soda-can 13/20→19/20。",
    novelty: "把多模态 trace 和经验证的修复程序作为可持续累积的机器人经验，而不是每任务从空 prompt 重试。",
    strengths: "多 benchmark、held-out seed、技能库大小曲线、组件消融和真机跨本体调试成本都较完整。",
    limitations: "真机迁移仍需执行反馈与调试，并非零样本策略迁移；安全 reset、成功检测和 API 质量限制开放式学习。",
    transfer: "适合可组合 perception/planning/control API 已成熟的系统，用于自动发现和复用程序级 skill。",
    experimentDetails: [{ title: "持续技能发现与真机迁移", setup: "LIBERO-Pro 10×50 held-out seeds、Robosuite 每任务 100 trials、真实跨本体三任务。", comparisons: "CaP-Agent0、端到端 VLA、无 execution engine、无 evolutionary search、无 skill retrieval。", results: ["execution engine 宏平均 14%→62%。", "Robosuite bimanual handover 20%→92%。", "真机 soda-can 13/20→19/20；drawer 无技能失败，有技能 11/20。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["multimodal trace engine", "iterative code repair", "validated skill library", "evolutionary search"], verifiedResources: ["NVIDIA 项目页、严格 held-out 协议和 ablation 表齐全。"], missing: ["完整执行环境、机器人 API 和安全 reset 栈的开放程度限制复现。"] },
    deepDive: { lead: "ASPIRE 的学习对象是可读、可验证、可复用的控制程序，而经验载体是执行 trace 与修复记录。", sections: [{ title: "技术细节", paragraphs: ["每个 primitive 返回局部视觉、候选抓取、规划轨迹和碰撞等 trace，coding agent 可以把失败定位到具体 API 调用。evolutionary search 同时保留多个程序分支，避免单一路径修补陷入局部最优。", "只有在执行中通过验证的修复才进入 skill library；新任务检索这些程序片段作为 in-context 经验，再按新本体 API 调整。"] }], experimentReading: ["真机结果证明技能检索能减少调试，但仍依赖在线执行，不能描述为仿真程序直接无缝部署。"], reflections: ["技能库条目应保存适用前提、失败反例和验证本体，避免错误程序被跨任务传播。"] },
    figures: [{ src: "/report-assets/2026-07-03/2607.00272-overview.png", alt: "ASPIRE 的 coordinator、actor、执行引擎、技能库和进化搜索", caption: "Figure 1 · ASPIRE 的持续技能编程闭环。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 11, title: "Adapting Generalist Robot Policies with Semantic Reinforcement Learning", arxivId: "2606.31958", url: "https://arxiv.org/abs/2606.31958",
    institutions: ["University of California, Berkeley"], signal: "不直接在低层 action 上探索，而用 RL 选择/组合 VLA 的语言 prompt 作为 semantic action",
    tags: ["Semantic RL", "Language Steering", "Long-Horizon"], classification: { research: "Subtask", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://semantic-action-rl.github.io/" }],
    motivation: "新长任务的初始低层动作离成功太远，residual/latent action RL 只能在 base policy 附近探索；VLA 已有技能却不会正确组合。",
    methodSummary: "SARL 把语言 prompt 当高层 action，outer policy 通过在线 reward 学习何时发出哪个语义技能，底层 generalist VLA 执行固定步数。",
    architecture: "semantic outer policy + frozen/base VLA skill prior；候选 prompt 可由 VLM 生成并缓存，RL 在较小离散语义空间学习。",
    optimization: "在线 RL；真实 WidowX 每任务先给 3 条由周期语言提示产生的完整示范，随后 60–100 episodes 适配。",
    data: "LIBERO-10 与四项真实 WidowX 复杂长任务，底座技能来自 Bridge v2 预训练分布。",
    experiments: "直接 task prompt 近 0%，60–100 个在线 episode 后最高约 80%；多项任务中 action-space DSRL/Residual RL 无法学会。",
    novelty: "把探索提升到语言技能组合空间，让每次探索都落在 VLA 已知可执行行为附近。",
    strengths: "真实长任务、在线 episode 曲线、两类低层 steering 和 VLM in-context baseline 对照较清楚。",
    limitations: "依赖底座已有足够原子技能；语义 prompt 粒度和 VLM 候选质量限制新能力，底层无法执行的技能仍不能被 RL 创造。",
    transfer: "适合 base VLA 有广泛短技能但无法完成组合长任务的场景，可与 subtask planner 或 memory 结合。",
    experimentDetails: [{ title: "语义空间在线 RL", setup: "LIBERO-10 与四项 WidowX 长任务；真机每任务 3 条 seed demonstrations。", comparisons: "base prompt、DSRL、Residual RL 与 VLM in-context instruction selection。", results: ["近 0% 初始成功可在 60–100 episodes 后提升到约 80%。", "低层 steering 在初始行为偏差过大的任务上常无法学习。", "semantic action 能复用 VLA 已有技能并组合出新长任务。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["semantic outer policy", "VLM candidate prompts", "frozen VLA skill execution"], verifiedResources: ["项目页、真实任务 episode 预算和 baseline 定义公开。"], missing: ["完整真机数据、prompt 候选与训练代码公开状态需确认。"] },
    deepDive: { lead: "SARL 用 RL 学‘下一步叫 VLA 做什么’，而不是直接学关节应该怎么动。", sections: [{ title: "技术细节", paragraphs: ["outer policy 的 action 是短语言指令，底层 VLA 以固定 horizon 执行。reward 回到高层后，RL 学会技能顺序和条件切换；VLM 可提出候选 prompt，但真正有效性由机器人交互 grounding。", "这种结构缩小探索空间，也把底层控制稳定性留给预训练 VLA。若 base policy 连原子技能都没有，高层语义搜索无法补救。"] }], experimentReading: ["约 80% 是部分任务/训练末期的表现，重点应看 60–100 个 episode 的样本效率和失败任务，而非当作统一平均值。"], reflections: ["可将 semantic action 与显式 subtask 状态/长期 memory 联合，防止重复执行或忘记已完成步骤。"] },
    figures: [{ src: "/report-assets/2026-07-03/2606.31958-overview.png", alt: "SARL 在语言语义动作空间选择并组合 VLA 技能", caption: "Figure 1 · Semantic Action RL 的高层 prompt 控制。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 12, title: "Multisensory Continual Learning: Adapting Pretrained Visuomotor Policies to Force", arxivId: "2606.30988", url: "https://arxiv.org/abs/2606.30988",
    institutions: ["Stanford University"], signal: "用多阶段融合、未来视觉/力预测和原预训练数据 replay，把 6D 力矩适配到视觉策略且减少遗忘",
    tags: ["Force", "Continual Learning", "World Model"], classification: { research: "WM", training: "Post-training", modalities: ["Force / Torque"], data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://jadenvc.github.io/multisensory-continual-learning/" }],
    motivation: "特定接触任务才有力觉数据，无法在大规模视觉预训练时覆盖所有传感器；后加模态还容易遗忘原任务。",
    methodSummary: "MuSe 以多阶段 fusion adapter 接入力矩历史，联合预测未来图像、未来 F/T 和动作，并用无 F/T 的预训练数据 replay/mask 保持旧能力。",
    architecture: "479M MAR-Large，16-layer encoder/decoder，4 历史帧预测 4 未来帧；late fusion 连接视觉、F/T、proprioception 与 action。",
    optimization: "视觉预训练后以小规模 multisensory 数据 finetune；旧数据 replay 时用 mask token 并关闭 F/T loss。",
    data: "真实 vase wiping、peg insertion 和 pick-place；接触任务每方法 15 次，pick-place 10 次。",
    experiments: "MuSe wiping 11.5/15、peg 13/15；无 compliance 为 8/15、11/15。旧任务 F/T 误差 8.42，对 policy-only DP 18.27；backward transfer 也更好。",
    novelty: "把新增力觉视为 continual multimodal learning，并用未来视觉预测帮助力表征迁移到从未有力标签的旧任务。",
    strengths: "forward/backward transfer、policy-only DP、adaptive compliance 和 F/T error 多层消融对应主张。",
    limitations: "任务和传感器规模仍小，需要保存/访问原预训练数据做 replay；成功计分含半分 credit。",
    transfer: "适合已有视觉 world model/policy 后接力觉，并需要保持原 pick-place 能力的场景。",
    experimentDetails: [{ title: "力觉持续适配", setup: "真实 wiping、peg insertion、pick-place；15/15/10 次。", comparisons: "No F/T、No Pretrain、No Compliance、Diffusion Policy、No Experience Replay。", results: ["MuSe 为 11.5/15、13/15、7.5/10。", "去 compliance 后 wiping/peg 降至 8/15、11/15。", "旧任务 F/T error 8.42，policy-only DP 18.27；backward transfer 明显更稳。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["MAR-Large 479M", "multistage/late fusion", "future image+F/T+action prediction", "masked replay"], verifiedResources: ["项目页、网络层数、token 数、任务次数与逐项表格齐全。"], missing: ["真实数据和完整训练代码公开状态需确认。"] },
    deepDive: { lead: "MuSe 关注的不只是新任务成功，还要求新增力觉后旧视觉能力不退化。", sections: [{ title: "技术细节", paragraphs: ["finetune 样本提供图像、F/T、proprioception 和 action；replay 的旧样本没有 F/T，就用 mask token 并跳过 F/T supervision，但保留图像和动作目标。未来图像预测迫使共享表示学习接触导致的视觉变化，而非只拟合少量力标签。", "预测 F/T 还用于 adaptive compliance：接近接触时降低刚度、卡住时调节方向。去掉该控制路径后成功率下降，说明表征与控制都贡献收益。"] }], experimentReading: ["真实次数不大且使用 success credit，最可靠的是多项消融方向一致，而不是某个单点百分比。"], reflections: ["持续多模态学习应同时报告新任务、旧任务和新模态在旧任务上的预测，避免只看 forward transfer。"] },
    figures: [{ src: "/report-assets/2026-07-03/2606.30988-overview.png", alt: "MuSe 用多阶段融合、未来多模态预测和 replay 适配力觉", caption: "Figure 1 · MuSe 的多传感持续学习框架。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 13, title: "ConCent: Contact-Centric Real-to-Sim-to-Real Learning from One Demonstration", arxivId: "2606.30268", url: "https://arxiv.org/abs/2606.30268",
    institutions: ["Microsoft Research Asia - Tokyo", "The University of Tokyo"], signal: "从一条真实 RGB-D 示范优化接触几何、提取接触事件奖励，在仿真 RL 后蒸馏为真机 VLA",
    tags: ["Real2Sim2Real", "Contact", "One Demonstration"], classification: { research: "VLA", training: "RL", modalities: ["Depth / RGB-D"], data: "合成 / 仿真数据", platforms: ["机械臂", "夹爪"], deployment: "Real2Sim2Real" },
    motivation: "接触任务的 sim2real 失败常来自局部接触几何/动力学，而不是外观；通用 domain randomization 可能学会利用不真实碰撞。",
    methodSummary: "从单条真实 RGB-D demo 的 point tracks 优化 primitive contact geometry，重放后自动抽取 contact event sequence 作为结构化 reward；仿真 RL policy 再用 raw sim/3DGS+flow 数据蒸馏为 VLA。",
    architecture: "real→sim 几何优化 + contact-event reward RL + sim→real visual distillation 三阶段。",
    optimization: "仿真内 contact-centric RL，不需要手写每任务 reward；部署 VLA 不再使用额外真实任务数据。",
    data: "一条真实示范；精密 shape insertion 真实评测；仿真生成训练图像并以 3DGS/flow 缩小视觉差距。",
    experiments: "完整 ConCent 真机插入成功率 80%，去除 contact geometry/reward/rendering 的变体为 20–50% 区间。",
    novelty: "用真实示范恢复‘何时何处如何接触’，把它同时用于校准 simulator 和设计 RL reward。",
    strengths: "一条真实数据、端到端真机插入与三大组件消融直接对应方法。",
    limitations: "主要验证单一精密插入；primitive geometry 与 point tracking 对复杂形变物/遮挡可能不成立。",
    transfer: "适合数据极少但接触事件顺序明确的装配任务，可用事件 reward 限制仿真策略钻物理漏洞。",
    experimentDetails: [{ title: "单示范接触迁移", setup: "单条真实 RGB-D demo 构建 simulator；真实精密 shape insertion。", comparisons: "无 contact geometry、无 contact-event reward、raw rendering/手写 reward 等消融。", results: ["完整方法真实成功率 80%。", "各关键组件移除后为 20–50%。", "不增加目标任务真实策略数据，收益来自接触校准和仿真训练。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["point-track contact geometry optimization", "contact-event reward", "3DGS+flow VLA distillation"], verifiedResources: ["正文给出流程、真实消融和 80% 结果。"], missing: ["代码、真实示范和仿真资产公开状态未确认；只验证一个主任务。"] },
    deepDive: { lead: "ConCent 认为真实示范最稀缺的信息不是完整轨迹，而是决定成功的接触序列。", sections: [{ title: "技术细节", paragraphs: ["RGB-D point tracks 约束 primitive 物体几何，使仿真重放能复现观察到的局部接触运动；从重放自动提取接触事件顺序，RL 只有按正确事件进入接触状态才获得进度。", "策略在仿真中学习后，用 3DGS 和 optical flow 提供接近真实的视觉训练，蒸馏到 VLA。这样真实数据只用于建立物理锚点，不用于大规模 BC。"] }], experimentReading: ["80% 对消融差距大，但单任务不足以证明普适性；迁移价值主要在接触建模思路。"], reflections: ["可先在多种插入公差/摩擦上检查 contact geometry 是否过拟合一条示范。"] },
    figures: [{ src: "/report-assets/2026-07-03/2606.30268-overview.png", alt: "ConCent 从真实示范优化接触仿真、RL 再蒸馏回真机", caption: "Figure 1 · ConCent 的 contact-centric Real2Sim2Real。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 14, title: "From Grasps to Dexterity: Large-Scale Grasp Pretraining for Dexterous Manipulation", arxivId: "2606.30749", url: "https://arxiv.org/abs/2606.30749",
    institutions: ["Carnegie Mellon University Robotics Institute"], signal: "把 35.5 万抓取轨迹用于低层手部 controller 预训练，再在少量工具使用示范上训练高层 subgoal",
    tags: ["Dexterous Hand", "Grasp Pretraining", "Tool Use"], classification: { research: "Subtask", training: "Pre-training", data: "合成 / 仿真数据", platforms: ["机械臂", "灵巧手"], deployment: "Sim2Real" },
    resources: [{ label: "项目页", url: "https://yingyuan0414.github.io/grasp2dexterity/" }],
    motivation: "大规模 grasp dataset 多用于抓取生成/搬运，但工具使用需要先抓稳、持续接触并驱动可动部件，低层手指能力可能可复用。",
    methodSummary: "hierarchical IL 的高层预测 hand subgoal，低层 goal-conditioned controller 用 G2D-Pretrain 35.5 万 grasp trajectories 预训练，再在下游示范微调。",
    architecture: "高层视觉策略输出手部关键点/目标；低层 proprioception+RGB-D controller 执行灵巧手闭环。",
    optimization: "大规模仿真 grasp BC 预训练，随后下游工具任务 imitation finetune；不使用 RL。",
    data: "G2D-Pretrain 355K trajectories；DexCraft 六项 articulated tool-use；真实 syringe/trigger 等三任务各 50 demos。",
    experiments: "仿真每设置 500 episodes；真机三任务每方法 18 episodes，完整任务比 DP3 高 33.3 个百分点，并优于层次策略从头训练。",
    novelty: "把静态 grasp 数据转成闭环低层预训练，使其服务后续保持接触和驱动工具关节。",
    strengths: "数据规模、demonstration-budget 曲线、scratch/GraspXL/DP3 对照和三项真机验证完整。",
    limitations: "真实任务/试验次数仍少，键盘遥操作示范质量有限；抓取先验对柔性或非工具任务的迁移未知。",
    transfer: "适合把灵巧手学习拆为可规模化低层 grasp/controller 与少量任务特定高层 subgoal。",
    experimentDetails: [{ title: "抓取预训练到工具使用", setup: "DexCraft 六任务；真实三任务各 50 demos、18 eval episodes。", comparisons: "DP3、hierarchical scratch、GraspXL pretrain、不同示范量。", results: ["仿真每设置 500 episodes，预训练在 20/50/100 demos 下持续优于 scratch。", "真实 full-task success 比 DP3 高 33.3 点。", "stage-wise 指标显示收益不仅在抓取，也延续到对齐和触发。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["355K grasp trajectory pretraining", "high-level subgoal policy", "low-level goal-conditioned controller"], verifiedResources: ["数据规模、六任务 benchmark、网络超参和真实协议在正文/附录。"], missing: ["项目页具体 URL/代码与真实数据公开状态需确认。"] },
    deepDive: { lead: "这项工作把 grasp dataset 当作手部 motor prior，而不是只训练一次性抓取器。", sections: [{ title: "技术细节", paragraphs: ["低层 controller 从大量不同抓型学习由当前手状态到目标手构型的闭环运动；高层策略只需在具体工具任务中预测功能性 subgoal，例如如何握住 syringe 或对准 trigger。", "预训练先解决手指协调和稳定接触，下游 50 条示范聚焦工具语义与阶段。stage-wise 结果表明收益能传到抓取后的对齐和驱动。"] }], experimentReading: ["真机仅 18 episodes/方法，33.3 点需要后续更多对象和 seed 复核。"], reflections: ["灵巧策略可以按‘抓取稳定性—功能对齐—工具致动’分阶段记录指标，避免只看最终成功。"] },
    figures: [{ src: "/report-assets/2026-07-03/2606.30749-overview.png", alt: "DexCraft 与抓取预训练支持真实灵巧工具使用", caption: "Figure 1 · 大规模 grasp pretraining 到灵巧工具使用。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 15, title: "BRIDGE-WA: Predicting Where and How the World Changes for Robotic Action", arxivId: "2607.02195", url: "https://arxiv.org/abs/2607.02195",
    institutions: ["Sun Yat-sen University", "Pengcheng Laboratory", "SIAT", "X-Era AI Lab"], signal: "把重型未来视频 teacher 蒸馏成 future token、change map 和 motion flow，部署时只保留轻量世界变化先验",
    tags: ["World-Action", "Change Map", "OOD Robustness"], classification: { research: "WAM", training: "Post-training", modalities: ["Mask / Segmentation"], data: "数据增强", platforms: ["机械臂", "夹爪"] },
    motivation: "完整未来视频生成昂贵且大量像素与控制无关；操作真正需要的是哪里会改变、朝什么方向改变。",
    methodSummary: "冻结 future-change teacher 生成 outcome future token、intervention change map 与 local motion flow；WorldBridge 以多源 attention memory 和时空 bias 条件化 action transformer。",
    architecture: "teacher 仅训练时存在；部署策略由 VLA/action transformer + 三类 compact world priors 组成，不解码未来视频。",
    optimization: "知识蒸馏+机器人示范后训练；对三类 prior、分辨率和 layered conditioning 做消融。",
    data: "VLABench、RoboTwin2.0、LIBERO-Plus；Dobot Nova2 真实两任务各 50 demos，Easy 10 次/任务，Hard 三扰动各 5 次。",
    experiments: "VLABench 52.8%、比 strongest SR baseline +9.7；LIBERO-Plus zero-shot 72.1%；Dobot Easy/Hard 73.6/69.1%，Hard 比 X-VLA +11.1。",
    novelty: "只保留动作相关的稀疏变化场，并把昂贵 world model 完全移出部署。",
    strengths: "三基准、零样本扰动、真实 OOD、prior 组合/分辨率/接口消融较充分。",
    limitations: "teacher 质量决定蒸馏上限；change/flow 对隐藏接触力和长时因果仍表达不足。",
    transfer: "适合在现有 VLA 中增加轻量 world prior，重点提高背景、光照、桌布和 distractor 变化下的稳健性。",
    experimentDetails: [{ title: "紧凑世界变化先验", setup: "三仿真基准；Dobot 两任务 50 demos，Easy/Hard OOD 评测。", comparisons: "X-VLA 等 VLA/WAM、无 world prior、单/双/三 prior、不同 map resolution 与 conditioning。", results: ["VLABench 52.8%，+9.7 点。", "RoboTwin Easy/Hard 79.7/37.7%，LIBERO-Plus zero-shot 72.1%。", "Dobot Easy/Hard 73.6/69.1%，Hard 比 X-VLA 高 11.1 点。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["future/change/flow teacher priors", "WorldBridge multisource attention", "teacher-free deployment"], verifiedResources: ["任务、示范量、真实试验次数和多类消融齐全。"], missing: ["代码链接在 PDF 提取中不完整；teacher/checkpoint 与训练数据开放状态需确认。"] },
    deepDive: { lead: "BRIDGE-WA 将 world modeling 压缩成三个直接服务动作的提示，而不是要求策略观看一段完整想象视频。", sections: [{ title: "技术细节", paragraphs: ["future token 表达期望结果，change map 标出会被动作影响的区域，motion flow 给出局部方向。WorldBridge 分层注入这些 memory，并把空间 bias 对齐到 action transformer 的视觉 token。", "teacher 在训练中产生监督，部署时移除，因此推理不再付出 dense video generation 成本。分辨率消融显示 change map 过粗/过细都不佳，flow 则受益于更细局部方向。"] }], experimentReading: ["OOD 真机收益与方法目标一致；但两任务不足以证明长时 world model 能力，应该理解为轻量视觉变化先验。"], reflections: ["可把 change map 与触觉接触区域联合，补足纯视觉 flow 看不到的力学状态。"] },
    figures: [{ src: "/report-assets/2026-07-03/2607.02195-overview.png", alt: "BRIDGE-WA 将未来变化 teacher 蒸馏为 future token、change map 和 motion flow", caption: "Figure 1 · BRIDGE-WA 的紧凑世界变化先验。图片来自 arXiv 原论文。" }],
  },
];
