import type { Paper } from "./site-data";
import { paperDaily20260710Additions } from "./paper-daily-2026-07-10-additions";

const paperCandidates20260710: Paper[] = [
  {
    rank: 1,
    title: "DSWAM: A Dual-System World Action Foundation Model for Fine-Grained Robot Manipulation",
    arxivId: "2607.04927",
    url: "https://arxiv.org/abs/2607.04927",
    institutions: ["AIRC, Midea Group", "Tongji University"],
    signal: "让 WAM 负责默认的细粒度执行，仅在需要时调用视觉语言子任务规划器，并系统优化真机异步推理",
    tags: ["Dual-System", "World-Action Model", "Real-Time Deployment"],
    classification: { research: "WAM", training: "Pre-training", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "WAM 擅长连续物理执行，却缺少把粗指令拆成可执行子任务的显式接口；同时 WAM 与 VLA 的真实比较常被数据和平台差异干扰。",
    methodSummary: "System 1 WAM 默认直接生成动作，System 2 VLM planner 只在长任务需要分解时启用；执行端结合 TensorRT、异步执行和 RTC。",
    architecture: "Wan2.2-TI2V-5B 视觉模型与 action expert 共同训练动作和视频目标；planner 从短时视觉历史与全局指令输出子任务。",
    optimization: "用 5000+ 小时真实操作数据预训练，再在匹配平台和数据下与 VLA 对照；推理阶段去掉显式未来视频生成并做引擎优化。",
    data: "5000+ 小时真实世界双臂/多模态操作数据；DeMaVLA 衣物折叠使用配对的预训练、后训练和评估条件。",
    experiments: "匹配折叠基准中成功率 92.5%→96.3%，平均完成时间 2分18秒→1分44秒；子任务监督将排序任务成功率 75.7%→100%。",
    novelty: "相比总是调用 planner 或总是生成未来视频，DSWAM 把高层规划设为可选系统，并把世界模型监督与实时动作执行分开。",
    strengths: "大规模真数据、匹配 WAM/VLA 真机对照、长任务子任务实验和部署延迟拆解都较完整。",
    limitations: "多数预训练数据不公开；折叠基准原始成功率已很高，绝对提升需要结合完成时间与其他任务理解。",
    transfer: "适合把现有 WAM 改造成默认反应式执行 + 按需规划系统，并优先优化视频分支在推理时的冗余。",
    experimentDetails: [{ title: "匹配数据下的 WAM/VLA 真机对照", setup: "DeMaVLA 真实衣物折叠，控制平台、预训练/后训练数据与评估标准一致；另有带子任务分解的排序任务。", comparisons: "匹配 VLA、WAM-only、是否启用 subtask supervision，以及不同推理引擎。", results: ["折叠平均成功率 92.5%→96.3%，完成时间 2:18→1:44。", "带子任务监督的排序成功率 75.7%→100%，平均错误数 3.53→0.65。", "TensorRT 将单次推理延迟从 198.2 ms 降至 73.8 ms。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["System 1 WAM executor；可选 System 2 planner；action/video co-training；TensorRT + asynchronous + RTC。"], verifiedResources: ["论文给出匹配对照、各阶段延迟和子任务监督协议。"], missing: ["5000+ 小时数据、模型权重与完整训练代码未确认公开。"] },
    deepDive: { lead: "DSWAM 把‘是否需要慢规划’和‘如何高速执行’分开处理。", sections: [{ title: "双系统与异步执行", paragraphs: ["短任务或清晰指令直接进入 WAM executor；当粗指令包含多个可观察子目标时，VLM planner 输出低层可执行子任务，executor 逐项完成。这样 planner 不必进入每个控制周期。", "训练时视频预测为动作表示提供世界动态监督，部署时 action expert 直接输出动作块。TensorRT、RTC 与异步查询让机器人执行上一块时并行准备下一块，减少停顿。"] }], experimentReading: ["折叠成功率接近饱和，完成时间与排序错误数更能体现执行稳定性；大规模内部数据仍是主要不可控变量。"], reflections: ["可先记录哪些任务真正触发 planner，避免把双系统退化为每步都调用慢模型。"] },
    figures: [{ src: "/report-assets/2026-07-10/2607.04927-overview.png", alt: "DSWAM 可选视觉语言规划器与世界动作执行器", caption: "Figure 1 · DSWAM 的双系统规划—执行结构。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 2,
    title: "TouchWorld: A Predictive and Reactive Tactile Foundation Model for Dexterous Manipulation",
    arxivId: "2607.07287",
    url: "https://arxiv.org/abs/2607.07287",
    institutions: ["Harbin Institute of Technology, Shenzhen", "PHANES AI"],
    signal: "把触觉同时用作低频接触目标和 30Hz 快速残差反馈，分离语义规划、动作生成与局部接触修正",
    tags: ["Tactile World Model", "Hierarchical Policy", "Dexterous Manipulation"],
    classification: { research: "WAM", training: "Post-training", modalities: ["Tactile"], platforms: ["机械臂", "灵巧手"] },
    resources: [{ label: "项目页", url: "https://phanes-lab.github.io/TouchWorld-website/" }],
    motivation: "视觉语言能规划任务，但看不到滑移、力不匹配和接触稳定性；把触觉塞进单一低频模型又无法及时反应。",
    methodSummary: "1Hz planner 生成子任务与触觉目标，10Hz visuo-tactile policy 输出名义动作，30Hz tactile residual layer 修正实时接触误差。",
    architecture: "高层 VLM + tactile world model、中层 diffusion action policy、底层 tactile-conditioned residual Transformer 构成三级闭环。",
    optimization: "触觉世界模型先在人类触觉数据上预训练，再用约 10 小时机器人示范微调；动作与残差分层训练，并消融预测/反应路径。",
    data: "六项真机长时与接触任务，覆盖插接、抓持、喷壶等；机器人示范约 10 小时，并包含人为扰动测试。",
    experiments: "干净环境成功率 65.0%，人为扰动下 53.7%，分别比最强基线高 15.7 和 18.5 个百分点；提供组件和 planner 变体消融。",
    novelty: "现有触觉策略多把 touch 当普通观察，TouchWorld 则同时预测未来触觉目标并用最新触觉做高频残差。",
    strengths: "六项真实任务、扰动协议、三频率系统与逐层消融直接检验了预测和反应的分工。",
    limitations: "系统链路复杂，planner、触觉世界模型和残差层都可能产生延迟或误差；跨触觉硬件迁移尚不明确。",
    transfer: "适合长任务中先规划接触阶段、再用高频触觉补偿局部误差的分层控制。",
    experimentDetails: [{ title: "长时接触与人为扰动", setup: "六项真实灵巧操作，分别在干净环境和执行中人为干扰下评测。", comparisons: "视觉 VLA、低频视觉触觉策略、只预测或只残差的变体及不同 planner。", results: ["干净设置成功率 65.0%，最强基线低 15.7 个百分点。", "扰动设置成功率 53.7%，最强基线低 18.5 个百分点。", "移除 tactile subgoal 或 30Hz residual 均降低成功率，二者作用互补。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["1Hz high-level planning；10Hz visuo-tactile diffusion policy；30Hz tactile residual refinement。"], verifiedResources: ["项目页提供视频；正文给出任务、层级频率和主要消融。"], missing: ["代码、触觉数据、传感器标定与完整超参数尚未确认公开。"] },
    deepDive: { lead: "TouchWorld 把触觉分成‘应该接触成什么样’与‘此刻偏差多大’两种信号。", sections: [{ title: "预测与反应的两条触觉路径", paragraphs: ["tactile world model 根据子任务预测目标接触状态，作为中层 action policy 的条件；底层 residual layer 不做语义推理，只读取最近触觉与本体状态，快速修正名义动作。", "三个频率层让高层不必追随每次滑移，底层也不必理解长任务。人为扰动实验用于验证底层反馈是否真的在闭环起作用。"] }], experimentReading: ["绝对成功率仍为 65.0%，说明长时任务中的非接触阶段和层间错误仍有明显空间。"], reflections: ["日志应分别记录 planner、名义动作和 tactile residual，才能定位失败属于哪一层。"] },
    figures: [{ src: "/report-assets/2026-07-10/2607.07287-overview.png", alt: "TouchWorld 高层规划中层动作与高频触觉残差三层架构", caption: "Figure 2 · TouchWorld 的 predictive/reactive 触觉层级。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 3,
    title: "FlowDAgger: Human-in-the-Loop Adaptation of Generative Robot Policies in Latent Space",
    arxivId: "2607.08877",
    url: "https://arxiv.org/abs/2607.08877",
    institutions: ["Microsoft Research", "Microsoft", "ETH Zurich", "University of Washington"],
    signal: "把人类纠正动作反演到生成策略的噪声潜变量，只训练轻量 latent policy，从少量干预中适配并保留原技能",
    tags: ["Human-in-the-Loop", "Latent Adaptation", "Generative Policy"],
    classification: { research: "VLA", training: "Post-training", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://microsoft.github.io/FlowDAgger" }],
    motivation: "真机分布外失败需要快速纠正，但全量微调容易遗忘已有技能，在线 RL 又耗费大量物理交互。",
    methodSummary: "用反向时间积分和局部优化找到能生成专家纠正动作的噪声 w*，再监督一个小型 latent policy 预测该噪声。",
    architecture: "冻结 flow/diffusion 基础策略；latent policy 根据状态输出噪声，基础策略从该噪声生成动作；训练不修改 foundation model 权重。",
    optimization: "DAgger 式收集 5–20 条干预 episode，做 latent-space SFT；仿真还与 residual DAgger、LoRA、SFT 和 latent RL 对比。",
    data: "MetaWorld 12 任务及两套真机平台 FR3 Duo、Dual UR5e，真实评估覆盖 8 项单臂、双臂和接触任务。",
    experiments: "每项真机报告 30 次 rollout；Toolbox Packing 由 13%→80%，Glassware 26%→76%；仅需 5–20 条干预 episode。",
    novelty: "与残差动作或权重微调不同，FlowDAgger 学习‘基础生成策略应该从哪个噪声开始’，因此适配仍受原动作流形约束。",
    strengths: "真实任务覆盖广、交互量小，并明确评估 held-out 技能遗忘。",
    limitations: "目标行为若超出基础策略支持范围，噪声反演无法创造新动作；纠正质量仍取决于操作者。",
    transfer: "适合已有 flow/diffusion VLA 的少样本现场适配，尤其在不能改大模型权重时。",
    experimentDetails: [{ title: "少量干预真机适配", setup: "FR3 Duo 与 Dual UR5e 上 8 项任务；每任务 5–20 条额外 episode，最终 30 次 rollout。", comparisons: "冻结 base、SFT、Residual-DAgger、LoRA-DAgger 与 latent-space RL。", results: ["Toolbox Packing 13%→80%，仅 10 条纠正 episode。", "Glassware Stacking 26%→76%，5 条纠正 episode。", "仿真 Hammer 从 0.40→0.84，同时 held-out 技能均值仅下降 0.08；SFT 几乎完全遗忘。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["reverse-time action inversion；局部 latent refinement；冻结 base policy；latent policy SFT。"], verifiedResources: ["项目页、仿真协议和 8 项真机表格完整。"], missing: ["完整代码和真实干预数据尚未确认公开。"] },
    deepDive: { lead: "FlowDAgger 把人类纠正变成对生成策略‘潜在选择’的监督。", sections: [{ title: "动作反演", paragraphs: ["给定基础策略和专家动作，算法先沿生成 ODE 反向积分得到候选噪声，再局部优化，使基础策略从该噪声出发尽量重现纠正动作。得到的 w* 成为 latent policy 的监督标签。", "部署时 latent policy 选噪声，冻结生成策略继续负责产生平滑动作。适配不会直接改写基础模型，因此更容易保留其他任务，但新行为仍必须位于基础模型可表达的动作流形。"] }], equations: [{ name: "潜变量监督", expression: "L = ‖πʷ(s) − w*‖²", explanation: "πʷ 根据状态预测可生成专家动作的潜变量 w*。" }], experimentReading: ["held-out 技能对照说明保留先验不是口号；同时也暴露 latent adaptation 的能力边界。"], reflections: ["如果反演误差长期偏高，应转向权重微调或新增示范，而不是继续堆干预。"] },
    figures: [{ src: "/report-assets/2026-07-10/2607.08877-overview.png", alt: "FlowDAgger 动作反演和潜变量策略监督流程", caption: "Figure 1 · FlowDAgger 的 latent action inversion 与轻量适配。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 4,
    title: "EgoWAM: World Action Models Beyond Pixels with In-the-Wild Egocentric Human Data",
    arxivId: "2607.08436",
    url: "https://arxiv.org/abs/2607.08436",
    institutions: ["Georgia Institute of Technology"],
    signal: "在固定 backbone、动作头和数据混合的条件下，比较像素、DINO 与 3D flow 世界目标对人类视频迁移的真实贡献",
    tags: ["Egocentric Human Data", "World Target", "Human-to-Robot"],
    classification: { research: "WAM", training: "Pre-training", modalities: ["Point Cloud / 3D"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://gatech-rl2.github.io/egowam.github.io" }],
    motivation: "人类第一视角视频包含可迁移的物体与任务语义，也混入头部运动和人体形态；不同 world target 是否真能过滤这些差异缺少受控比较。",
    methodSummary: "固定 heterogeneous Transformer 和 action head，只替换未来预测目标为 RGB pixel、DINO feature 或 3D flow，再逐步扩大人类数据比例。",
    architecture: "机器人与人类视觉有独立输入 stem，进入共享 Transformer；动作头仅用于机器人数据，世界头可替换为像素、DINO 或 3D flow decoder。",
    optimization: "在相同机器人数据与训练预算下从纯 BC 到三种 WAM，对人类/机器人比例和 world target 做完整消融。",
    data: "三项真实双臂任务，每任务约 300–360 条机器人示范；人类第一视角数据最高按 10:1 混入；ID/OOD 每设置各 20 次。",
    experiments: "DINO world target 的 OOD 成功率最高可达 BC 的 4 倍；3D flow 对 ID 提升约 20%–30%；总计约 1800 次真机 rollout。",
    novelty: "论文把 backbone、动作头和数据混合保持不变，因此能更直接判断收益来自哪种世界预测目标。",
    strengths: "受控变量、三项真机、ID/OOD 和大规模 rollout 让人类视频迁移结论较可信。",
    limitations: "只有三类世界目标；DINO 与 3D flow 的计算/标注代价不同，结论未覆盖更长任务。",
    transfer: "适合选择 WAM 辅助目标：重外观泛化可优先 DINO，重局部几何动力学可考虑 3D flow。",
    experimentDetails: [{ title: "人类数据与世界目标受控比较", setup: "三项真实双臂任务；每任务 300–360 robot demos；ID/OOD 每方法各 20 次，总计约 1800 rollouts。", comparisons: "BC、Pixel WAM、DINO WAM、3D Flow WAM，以及不同 human:robot 数据比例。", results: ["DINO 在 OOD 对象/场景上最高达到 BC 的约 4 倍。", "3D Flow 在 ID 设置提升约 20%–30%。", "Pixel target 的人类到机器人迁移较弱，说明未来预测目标并非越细越好。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["human/robot modality stems；共享 HPT trunk；可替换 pixel/DINO/3D-flow world head；固定 action head。"], verifiedResources: ["项目页和正文给出数据比例、rollout 数及受控消融。"], missing: ["完整数据、训练代码与 3D flow 预处理尚未确认公开。"] },
    deepDive: { lead: "EgoWAM 的重点是选择什么未来表征，而不是简单证明人类视频越多越好。", sections: [{ title: "为什么目标不同会改变迁移", paragraphs: ["像素预测保留相机运动、人体外观和背景，容易把人类特有因素带入共享 trunk；DINO 特征更强调物体与语义，3D flow 则显式表示场景中的几何运动。", "由于动作头、backbone 和数据混合固定，三者结果差异主要来自监督目标。论文进一步改变 human:robot 比例，检查收益是否能随人类数据扩大。"] }], experimentReading: ["DINO 对 OOD、3D flow 对 ID 的分工值得注意，不应把单一 world target 当作所有任务的最优解。"], reflections: ["可先用相同数据做小规模 target sweep，再决定是否投入昂贵的三维伪标签。"] },
    figures: [{ src: "/report-assets/2026-07-10/2607.08436-overview.png", alt: "EgoWAM 人类机器人共享主干和可替换世界预测头", caption: "Figure 2 · EgoWAM 固定策略结构下的 Pixel、DINO 与 3D Flow world targets。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 5,
    title: "RynnWorld-Teleop: An Action-Conditioned World Model for Digital Teleoperation",
    arxivId: "2607.06558",
    url: "https://arxiv.org/abs/2607.06558",
    institutions: ["DAMO Academy, Alibaba Group", "Hong Kong Embodied AI Lab", "CUHK", "Hupan Lab", "Ant Group"],
    signal: "让人手姿态驱动生成式机器人视角，把数字遥操作视频与动作直接用作训练数据，并在单 H100 上达到 40+ FPS",
    tags: ["Digital Teleoperation", "Generative Data", "Sim2Real"],
    classification: { research: "WM", training: "Pre-training", data: "合成 / 仿真数据", platforms: ["机械臂", "灵巧手"], deployment: "Sim2Real" },
    resources: [{ label: "项目页", url: "https://alibaba-damo-academy.github.io/RynnWorld-Teleop.github.io" }, { label: "GitHub", url: "https://github.com/alibaba-damo-academy/RynnWorld-Teleop" }, { label: "模型", url: "https://huggingface.co/Alibaba-DAMO-Academy/RynnWorld-Teleop" }],
    motivation: "物理遥操作把操作者时间绑定到具体机器人、场地和硬件，限制了数据规模与跨本体复用。",
    methodSummary: "从单张机器人参考图出发，人手骨架序列条件生成机器人执行视频；同一姿态流经重定向后成为目标机器人的动作标签。",
    architecture: "深度感知骨架表示进入 video DiT，经人类到机器人渐进训练；streaming autoregressive distillation 把多步生成压成实时单步模型。",
    optimization: "先利用人类与机器人视频建立动作条件世界模型，再做因果蒸馏；生成 1800 条高质量 episode，并与真实示范混合训练多种策略。",
    data: "四项 TIANJI M6 + WUJI Hand 双臂任务；每任务 35 次真机测试，比较 300 条真实、300 条生成及二者混合。",
    experiments: "纯生成数据训练的 π0 在 Block Pushing 为 82.86%、Bimanual Lifting 为 77.14%；混合后 π0.5 的 Lid Placement 42.86%→62.86%。",
    novelty: "与离线视频增强不同，RynnWorld-Teleop 让操作者实时控制生成世界，并保留与视频同步的可重定向动作。",
    strengths: "代码、模型、生成速度、纯生成训练和多策略混合对照都较完整。",
    limitations: "生成分布仍由单张参考图和模型先验约束；高质量实时模式需要 H100，视觉逼真不保证所有接触动力学正确。",
    transfer: "适合用人手演示扩增稀缺灵巧操作数据，尤其可借鉴深度骨架条件和纯生成/混合数据对照协议。",
    experimentDetails: [{ title: "数字遥操作数据的真机价值", setup: "TIANJI M6 + WUJI Hand，四项任务，每项 35 次；DP、π0.5、π0 使用真实/生成/混合数据。", comparisons: "300 real、300 generated、300+300 mixed，以及不同生成/蒸馏变体。", results: ["零真实数据 π0：Block Pushing 82.86%，Bimanual Lifting 77.14%。", "π0.5 的 Lid Placement 从 42.86% 提升到 62.86%。", "因果蒸馏版本单 H100 达 40 FPS；高质量非因果版本约 2.8 FPS。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["depth-aware hand skeleton；progressive human-to-robot video DiT；causal streaming distillation。"], verifiedResources: ["项目页、GitHub、Hugging Face 模型与表格协议公开。"], missing: ["完整 1800 条生成 episode 和硬件遥操作装置是否全部公开仍需核对。"] },
    deepDive: { lead: "RynnWorld-Teleop 把‘操作者动作’与‘真实机器人是否在场’解耦。", sections: [{ title: "从手势到同步机器人轨迹", paragraphs: ["操作者提供带深度编码的手骨架序列，世界模型从固定机器人初始图生成相应执行视频。姿态流不依赖具体机器人关节，可通过标准 retargeting 映射到不同本体。", "渐进训练先学人类动作，再向机器人外观适配；因果蒸馏把生成变成流式单步，使操作者能实时观察结果。最终视频与动作天然同步，可直接进入行为克隆。"] }], experimentReading: ["纯生成数据在两项任务表现突出，但精密 Lid Placement 仍更依赖真实与生成混合。"], reflections: ["生成数据验收应同时检查视频、动作同步和真机闭环，而不是只看 FVD/PSNR。"] },
    figures: [{ src: "/report-assets/2026-07-10/2607.06558-overview.png", alt: "RynnWorld Teleop 手骨架条件生成与流式世界模型", caption: "Figure 3 · RynnWorld-Teleop 的数字遥操作与渐进式世界模型训练。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 6,
    title: "LAMP: Latent Motion Prior-Guided Real-World Learning for Dexterous Hand Manipulation",
    arxivId: "2607.06323",
    url: "https://arxiv.org/abs/2607.06323",
    institutions: ["Fudan University", "Tsinghua University", "Peking University", "PsiBot", "Zhongguancun Academy"],
    signal: "用历史条件的连续手部运动先验压缩高维灵巧手动作，并让 BC 与在线残差 RL 共享同一潜动作接口",
    tags: ["Latent Motion Prior", "Dexterous Hand", "Residual RL"],
    classification: { research: "表征学习", training: "RL", platforms: ["机械臂", "灵巧手"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://dex-lamp.github.io/" }, { label: "GitHub", url: "https://github.com/dex-lamp/LAMP" }],
    motivation: "高维手指动作直接回归容易抖动，离散 codebook 又会发生动作跳变；在线 RL 在原动作空间探索也容易破坏接触。",
    methodSummary: "LMPM 从历史手部运动预测潜先验中心，连续 decoder 还原手动作；BC 预测潜动作，RL 只在潜空间学习 residual。",
    architecture: "离线 LMPM encoder/decoder 学习连续手动作流形；视觉策略输出潜变量，decoder 生成手动作，机械臂动作仍由主策略直接预测。",
    optimization: "先预训练 motion prior，再行为克隆，最后在线 residual RL；与 raw、PCA、VQ-VAE 和无 history encoder 比较。",
    data: "Franka Research 3 + Ruiyan 灵巧手四项真实任务，每任务约 50 条示范；在线阶段混合示范与 rollout。",
    experiments: "RL 后三项任务达到 100%，另一项 95%；相比纯模仿平均约 56.25%，提升约 42.5 个百分点，并分析动作抖动。",
    novelty: "与只做动作压缩不同，LAMP 用历史预测潜先验，使相邻动作落在连续局部区域，并在同一接口上做 IL 与 RL。",
    strengths: "四项真机、PCA/VQ/raw 完整对照、失败类型和动作频率分析较充分。",
    limitations: "先验仍由当前手型和任务数据决定；迁移到新手型或超出示范动作流形的技能需要重训。",
    transfer: "适合高维灵巧手的平滑动作建模，以及把 RL 探索限制在接触可保持的局部动作流形。",
    experimentDetails: [{ title: "真机潜动作 BC 与 RL", setup: "Franka Research 3 + Ruiyan hand，四任务，每任务 50 demos；先 BC 再在线 residual RL。", comparisons: "Raw action、PCA、VQ-VAE/DQ-RISE、无历史先验和 LAMP。", results: ["纯模仿 LAMP 已优于各压缩对照，减少手指抖动和滑落。", "RL 后三项 100%，另一项 95%。", "相对模仿平均约 56.25%，在线阶段提升约 42.5 个百分点。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["history-conditioned LMPM；连续 latent decoder；BC latent action；online residual RL。"], verifiedResources: ["项目页、GitHub、网络结构图和真机任务协议公开。"], missing: ["真实数据与硬件低层控制配置是否完整发布仍需核对。"] },
    deepDive: { lead: "LAMP 不只压缩手动作，还给每个时间点定义一个由动作历史决定的局部先验。", sections: [{ title: "历史条件动作流形", paragraphs: ["LMPM encoder 根据近期手指运动预测潜变量中心，decoder 将中心附近的偏移还原为连续手动作。BC 学的是这个较低维潜变量，而不是几十维关节命令。", "在线阶段 residual RL 也只在潜空间移动，探索更可能保持在示范动作流形附近。PCA 只有固定线性坐标，VQ-VAE 又存在 code 跳变，因而在持续接触上较弱。"] }], experimentReading: ["RL 的大幅提升建立在 LAMP 已能提供稳定接触的前提上；raw residual 因初始失败和高维探索难以收敛。"], reflections: ["可用解码后动作 jerk 与接触中断率共同评估潜动作表示，而不只看重建误差。"] },
    figures: [{ src: "/report-assets/2026-07-10/2607.06323-overview.png", alt: "LAMP 运动先验预训练行为克隆和残差强化学习", caption: "Figure 2 · LAMP 的连续潜动作接口贯穿 BC 与在线 RL。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 7,
    title: "Lift3D-VLA: Lifting VLA Models to 3D Geometry and Dynamics-Aware Manipulation",
    arxivId: "2607.06564",
    url: "https://arxiv.org/abs/2607.06564",
    institutions: ["Peking University", "The Chinese University of Hong Kong", "AI² Robotics"],
    signal: "把点云映射到预训练二维位置编码，并用当前几何重建与未来几何预测共同预训练 VLA",
    tags: ["3D VLA", "Geometry-Centric MAE", "Temporal Action"],
    classification: { research: "VLA", training: "Pre-training", modalities: ["Point Cloud / 3D"], data: "跨本体数据", platforms: ["机械臂", "夹爪"] },
    motivation: "新增 3D encoder 往往无法利用二维预训练能力，投影式方法又会损失几何；动作头还常忽略动作块内部时间结构。",
    methodSummary: "虚拟投影让 3D 点继承 2D 位置嵌入；GC-MAE 同时重建当前点云并预测未来几何；多层 LLM 协作输出动作块。",
    architecture: "点云经 VGGT/几何预处理后进入 lifted 2D vision encoder；GC-MAE 提供几何预训练，多层 temporal action heads 聚合不同深度特征。",
    optimization: "先在 400K 轨迹、28M 帧上做几何与未来预训练，再在 22 项仿真和 8 项真机任务后训练；消融 3D lifting、future objective 与 layer-wise action。",
    data: "多源开放机器人数据约 400K trajectories / 28M frames；真实评估覆盖 8 项操作任务。",
    experiments: "MetaWorld 与 RLBench 平均分别比最强对照高 10.8 和 11.1 个百分点；8 项真机每任务 15 次测试，平均约高 4 个百分点。",
    novelty: "与从零训练 3D backbone 不同，Lift3D-VLA 复用 2D positional prior，并让未来几何而非 RGB 充当动力学目标。",
    strengths: "预训练规模、两套仿真、8 项真机和三部分结构消融形成较完整证据。",
    limitations: "点云质量依赖深度/VGGT 预处理；真实提升较仿真小，计算和传感器开销需另行评估。",
    transfer: "适合已有 2D VLA 向点云扩展，并用几何预测代替昂贵的全像素 world model。",
    experimentDetails: [{ title: "3D 几何与动作时序", setup: "400K 轨迹预训练；MetaWorld、RLBench 22 项仿真；8 项真机，每任务 15 次。", comparisons: "2D VLA、独立 3D encoder、去掉 GC-MAE/future objective/layer-wise action 的变体。", results: ["MetaWorld 平均高 10.8 个百分点。", "RLBench 平均高 11.1 个百分点。", "8 项真机平均约高 4 个百分点，收益较仿真更温和。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["virtual projection；GC-MAE current reconstruction + future geometry；layer-wise temporal action modeling。"], verifiedResources: ["正文列出数据规模、训练轮数、仿真与真机协议。"], missing: ["代码、点云伪标签流水线和预训练权重尚未确认公开。"] },
    deepDive: { lead: "Lift3D-VLA 用二维模型已有的位置先验承载三维点，而不是另起一个陌生的 3D encoder。", sections: [{ title: "几何 lifting 与未来预测", paragraphs: ["三维点通过虚拟相机投影到二维位置编码坐标，点特征随后进入预训练视觉层。GC-MAE 遮挡点云，一路重建当前结构，另一路预测动作后未来几何。", "动作生成不只读取最后一层 LLM，而是让多层输出不同时间粒度的动作查询，增强动作块的时序一致性。"] }], experimentReading: ["真机增益较仿真小，说明点云噪声和部署开销可能抵消部分结构收益。"], reflections: ["引入 3D 前应先量化深度误差对动作头的敏感性，并保留 RGB-only fallback。"] },
    figures: [{ src: "/report-assets/2026-07-10/2607.06564-overview.png", alt: "Lift3D VLA 虚拟投影几何 MAE 与多层动作建模", caption: "Figure 2 · Lift3D-VLA 的几何 lifting、GC-MAE 与多层动作头。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 8,
    title: "NativeMEM: Native Memory Compression for Long-Horizon Robotic Manipulation",
    arxivId: "2607.06678",
    url: "https://arxiv.org/abs/2607.06678",
    institutions: ["The University of Hong Kong", "Beihang University", "Peking University", "CUHK", "Horizon Robotics"],
    signal: "复用 VLA 自己的视觉编码器把每个历史视角压成一个 token，在不外接 planner 的情况下扩展分钟级上下文",
    tags: ["Native Memory", "Long-Horizon", "Token Compression"],
    classification: { research: "Memory", training: "Post-training", platforms: ["机械臂", "夹爪"] },
    detailAttributes: { memoryImplementation: "Context/Sequence", memoryHorizon: "分钟级；超过 160 帧历史" },
    resources: [{ label: "项目页", url: "https://opendrivelab.com/NativeMEM" }],
    motivation: "外部 VLM 摘要或新建记忆模块会引入延迟和表示错位，原始历史帧又会让上下文成本随时间快速增长。",
    methodSummary: "将 VLA 自身 vision encoder 改作 memory tokenizer，把每个历史帧/视角压成单 token，直接附加到当前 VLA 上下文。",
    architecture: "Stage 1 冻结 VLA，只训练由其视觉编码器初始化的 memory tokenizer；Stage 2 解冻并做任务微调，动作 expert 读取当前观察和缓存 token。",
    optimization: "先在混合记忆任务上做通用 token 对齐，再做任务后训练；与文本记忆、外部视觉模块、未压缩历史和不同 token 数消融。",
    data: "仿真与真实记忆依赖操作；真机三项任务，每项约 100 条示范，并测试只用 20% 数据。",
    experiments: "仿真成功率 32.4%→84.0%，真机最高 98.7%；可覆盖超过 160 帧、9–40 倍更长 horizon，延迟和显存增量较低。",
    novelty: "不是把历史交给另一个记忆模型，而是复用原 VLA 的视觉表征，让记忆 token 原生落在策略空间。",
    strengths: "长上下文、真机、效率和数据效率同时评估，且与多种外部记忆路线比较。",
    limitations: "目前仍是单 episode 的分钟级记忆，不等于跨任务或跨天长期知识；压成单 token 可能丢失细节。",
    transfer: "适合需要记住已完成步骤、顺序或先前位置的 VLA，而不想引入额外 planner。",
    experimentDetails: [{ title: "分钟级记忆操作", setup: "仿真与三项真机记忆任务；每项约 100 demos；历史超过 160 帧并比较不同压缩预算。", comparisons: "无记忆、VLM 文本记忆、外部视觉记忆、未压缩历史和不同 tokenizer。", results: ["仿真成功率 32.4%→84.0%。", "真机最高 98.7%。", "仅 20% 训练数据仍达到竞争表现，并保持较低延迟/显存。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["每历史帧/视角单 token；冻结 VLA 的 tokenizer 对齐；任务级联合微调。"], verifiedResources: ["项目页与正文给出三项真机、horizon 和效率对照。"], missing: ["代码、数据及 tokenizer 训练配方尚未确认公开。"] },
    deepDive: { lead: "NativeMEM 把历史压缩到策略本来就理解的视觉空间。", sections: [{ title: "两阶段原生记忆", paragraphs: ["第一阶段冻结 VLA，memory tokenizer 读取历史图像，并通过冻结策略的监督学习产生兼容 token。每个视角每帧只占一个 token，历史可按时间追加。", "第二阶段把这些 token 与当前图像、指令一起输入 VLA 做任务微调。由于没有外部检索器或文字摘要，控制路径较短，但单 token 压缩会牺牲局部细节。"] }], experimentReading: ["160+ 帧和真机结果证明单 episode 长记忆有效；不能据此推断开放世界知识积累。"], reflections: ["可按任务事件保留更高 token 预算，而对无变化历史使用单 token，以缓解细节丢失。"] },
    figures: [{ src: "/report-assets/2026-07-10/2607.06678-overview.png", alt: "NativeMEM 记忆压缩预训练与任务微调两阶段", caption: "Figure 2 · NativeMEM 的原生记忆 tokenizer 与两阶段训练。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 9,
    title: "SIEVE: Structure-Aware Data Selection for Imitation Learning with VLA Models",
    arxivId: "2607.06442",
    url: "https://arxiv.org/abs/2607.06442",
    institutions: ["East China Normal University", "Zhongguancun Academy", "Harbin Institute of Technology", "Beihang University", "DeepCybo"],
    signal: "按可复用动作原语及其转移结构选择示范，而不是只给整条轨迹或单帧打分",
    tags: ["Data Selection", "Behavior Primitives", "Imitation Learning"],
    classification: { research: "VLA", training: "BC", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "GitHub", url: "https://github.com/ChangtiWu/SIEVE" }],
    motivation: "机器人示范含重复、噪声和覆盖不均；轨迹级评分太粗，state-action 级评分又看不到长任务中的可复用组合。",
    methodSummary: "先按夹爪状态变化切分轨迹，用 V-JEPA2 聚类成原语；再按原语/转移覆盖分配预算，并在每种组合中选 medoid 轨迹。",
    architecture: "它是训练前数据选择流水线：segmentation、视频表示、Mini-Batch K-Means、结构暴露目标与桶内中心轨迹选择。",
    optimization: "选择后的子集用于标准 VLA 行为克隆；比较 50%/70% 数据预算、不同训练步数、数据集和两种 Qwen3-VL-GR00T 模型。",
    data: "Bridge-V2、DROID 与 RoboTwin 2.0 等数据，覆盖真实 OXE 子集和约 87K 真实轨迹、24K 仿真轨迹。",
    experiments: "在 Bridge-V2/SimplerEnv 设置，50% 数据与 50% 训练步数达到 56.3%，高于全数据 51.8%；跨数据集与模型均有提升。",
    novelty: "与影响函数或相似度去重不同，SIEVE 以可复用原语和转移在组合空间中的覆盖作为数据价值。",
    strengths: "多个数据集、预算、训练步数和 backbone，并提供预算分配与 medoid 选择消融。",
    limitations: "原语边界依赖夹爪状态变化，对无夹爪或连续接触技能不一定适用；主要是仿真/离线基准证据。",
    transfer: "适合在大规模示范中优先保留行为结构覆盖，而不是按任务均匀采样。",
    experimentDetails: [{ title: "结构感知示范筛选", setup: "Bridge-V2、DROID、RoboTwin 2.0；50%/70% 预算；Qwen3-VL-4B/8B-GR00T。", comparisons: "Full Training、Random、DemInf、轨迹与 state-action 级筛选方法。", results: ["50% 数据、50% steps 达 56.3%，全数据/双倍 steps 为 51.8%。", "DROID 与 RoboTwin 设置分别报告 56.3% 和 76.4% 等跨数据集结果。", "去掉结构预算或 medoid 选择均下降，说明覆盖和稳定示范两部分都有效。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["夹爪 flip 持续 5 帧作为边界；8 帧 V-JEPA2 表示；PCA 256D；Mini-Batch K-Means；greedy budget。"], verifiedResources: ["代码公开；正文给出选择目标、模型与数据预算。"], missing: ["部分大数据集处理仍需要较高存储与视频编码成本。"] },
    deepDive: { lead: "SIEVE 认为高价值数据应暴露可复用的行为子程序及其连接方式。", sections: [{ title: "从原语到选择预算", paragraphs: ["轨迹先在抓取/释放等物理边界切段，每段抽 8 帧，用 V-JEPA2 的起中末特征聚类。每条轨迹于是变成原语序列，相邻原语形成 transition。", "预算目标对已多次覆盖的原语和转移使用对数递减收益，避免重复采样；在同一组合桶内再选最接近中心的轨迹，降低 BC 监督噪声。"] }], equations: [{ name: "结构暴露目标", expression: "F(B)=Σc wc log(1+nc)+Σe we log(1+ne)", explanation: "nc、ne 是已选择数据中原语和转移的出现次数；对数项体现覆盖的边际收益递减。" }], experimentReading: ["超过全数据不代表筛选能普遍创造信息，更可能说明原数据冗余与噪声较高。"], reflections: ["对连续操作可把夹爪 flip 替换为接触事件、力峰或视觉状态变化作为边界。"] },
    figures: [{ src: "/report-assets/2026-07-10/2607.06442-overview.png", alt: "SIEVE 原语发现结构预算与中心轨迹选择流程", caption: "Figure 2 · SIEVE 的结构感知数据选择流程。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 10,
    title: "Training-Free Acceleration for Vision-Language-Action Models with Action Caching and Refinement",
    arxivId: "2607.06370",
    url: "https://arxiv.org/abs/2607.06370",
    institutions: ["Institute of Science Tokyo"],
    signal: "缓存过去生成过程中的中间噪声动作，用相似上下文命中后少走去噪步，实现无需训练的 VLA 加速",
    tags: ["Action Cache", "Training-Free", "Inference Acceleration"],
    classification: { research: "VLA", training: "Test-time Adaptation", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "flow/diffusion VLA 的 action head 占端到端延迟很大；量化或蒸馏通常要重训并可能损害成功率。",
    methodSummary: "用压缩的视觉语言上下文构造 cache key，存储过去生成的中间动作；命中时从接近目标的中间点继续少量 refinement。",
    architecture: "ActionCache 作为外部模块包住冻结 VLA：key lookup、pending buffer 和 action refinement，不改 backbone 或 action head。",
    optimization: "不训练；运行中逐步填充 cache，并调节命中阈值与剩余 NFE，在速度和成功率间选择工作点。",
    data: "VLABench、LIBERO 与 SO-101 真机；真实设置使用 100 条示范和额外恢复 episode，最终约 100 次评估。",
    experiments: "π0.5 action-head 最高加速 11.75×，GR00T-N1.6 最高 34.43×；真机在低延迟设置保持与基础策略接近的成功率。",
    novelty: "与缓存最终动作不同，它缓存中间噪声动作并继续 refinement，因此相似但不完全相同的场景仍可修正。",
    strengths: "无需训练、覆盖两类主流 VLA、仿真与真机，并系统扫过命中阈值与 NFE。",
    limitations: "缓存命中依赖任务重复性；分布变化或长时状态下错误命中可能复用不合适动作。",
    transfer: "适合固定工作站或重复任务的 flow VLA 部署，可先作为外部加速层而不动模型。",
    experimentDetails: [{ title: "训练外缓存加速", setup: "π0.5 与 GR00T-N1.6；VLABench、LIBERO、SO-101 真机，比较不同 cache 阈值与 NFE。", comparisons: "原始完整去噪、减少 NFE、最终动作缓存与 ActionCache。", results: ["π0.5 action head 最高 11.75× 加速。", "GR00T-N1.6 最高 34.43× 加速。", "真机低延迟区间成功率与基础策略接近，同时命中后动作生成低至毫秒级。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["随机稀疏投影 key；episodic cache；中间动作 warm start；可调 refinement NFE。"], verifiedResources: ["正文给出两模型、三环境、真实评估和加速曲线。"], missing: ["代码尚未确认公开；缓存容量与长期淘汰策略仍需工程化。"] },
    deepDive: { lead: "ActionCache 利用机器人任务重复性，复用的是‘去噪过程走到一半的位置’。", sections: [{ title: "命中后仍允许修正", paragraphs: ["当前图像与指令经轻量压缩形成 key，命中相似历史后取出对应中间 noisy action。模型不直接执行旧动作，而是从该中间点继续少数去噪步，因此能适应局部差异。", "未命中时按原策略完整生成，并把中间状态加入 pending buffer；一个 episode 内 cache 逐步积累。阈值太宽会错误复用，太窄则没有加速。"] }], experimentReading: ["最高倍数来自 action-head 延迟，不等于端到端系统同倍加速；真机应同时记录视觉 backbone、通信与执行等待。"], reflections: ["部署可先按任务阶段分 cache，减少外观相似但语义阶段不同的错误命中。"] },
    figures: [{ src: "/report-assets/2026-07-10/2607.06370-overview.png", alt: "ActionCache 上下文键缓存查询与中间动作细化", caption: "Figure 2 · ActionCache 的 key lookup 与中间动作 refinement。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 11,
    title: "InternVLA-A1.5: Unifying Understanding, Latent Foresight, and Action for Compositional Generalization",
    arxivId: "2607.04988",
    url: "https://arxiv.org/abs/2607.04988",
    institutions: ["Physical Intelligence Team, Shanghai AI Laboratory"],
    signal: "保留原生 VLM 的理解训练，用冻结视频生成器监督少量 foresight token，再由统一 expert 输出动作",
    tags: ["Latent Foresight", "Compositional Generalization", "Unified VLA"],
    classification: { research: "VLA", training: "Pre-training", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://internrobotics.github.io/internvla-a15.github.io/" }, { label: "GitHub", url: "https://github.com/InternRobotics/InternVLA-A-series" }, { label: "模型", url: "https://huggingface.co/collections/InternRobotics/internvla-a15" }],
    motivation: "统一 VLA 常在动作训练中损伤 VLM 语义，未来预测又从像素零开始，导致组合指令和长任务受限。",
    methodSummary: "VLM 持续做 VQA 与子任务预测；learnable foresight tokens 在冻结视频生成器监督下压缩任务相关未来；轻量 unified expert 生成连续动作。",
    architecture: "Qwen3.5 系 VLM 与 LLM action expert 构成 Mixture-of-Transformers；foresight tokens 连接冻结视频模型，推理时移除视频解码分支。",
    optimization: "在 1.2M 机器人 episode 与 3M 多模态样本上联合预训练，使用分组温度采样平衡来源，再做真实任务后训练。",
    data: "约 1.2M robot episodes、861M frames 和 3M VQA/point/bbox/trajectory 样本，含五类真实与一类合成来源。",
    experiments: "六套仿真基准整体最优，LIBERO 98.9%、Simpler 80.8%；四项真机与 held-out 指令绑定中明显优于 π0.5 和 Motus。",
    novelty: "未来监督来自预训练视频模型的 latent，而不是自建像素生成头；同时通过持续 VQA 保留 VLM 语义。",
    strengths: "数据规模、六基准、真实长任务和组合指令对照，且项目、代码和模型入口齐全。",
    limitations: "训练规模大，视频教师和内部数据使完整重现成本高；真实任务数量有限。",
    transfer: "可借鉴‘训练时 latent foresight、推理时移除视频分支’，以及维持 VQA 防止语义退化。",
    experimentDetails: [{ title: "组合泛化与长时真机", setup: "六项仿真基准；真实四任务，固定 demos 并随机化环境，RTX 5090 部署。", comparisons: "π0、π0.5、Motus、无 VQA continuation、无 foresight tokens 与像素未来分支。", results: ["LIBERO 98.9%，Simpler 80.8%。", "真实长时 MOF 达 76.4%，π0.5 为 29.3%，Motus 为 0。", "held-out 指令绑定中保留 VQA 与 latent foresight 的完整模型表现最佳。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["native VLM continuation；unified action expert；frozen video teacher；learnable foresight tokens；group-tempered sampling。"], verifiedResources: ["项目页、GitHub 与 Hugging Face 模型入口公开；正文列出数据规模与主要训练设置。"], missing: ["完整 1.2M episode 训练混合与计算资源无法由公开权重完全还原。"] },
    deepDive: { lead: "InternVLA-A1.5 试图同时保住语义理解和物理未来，而不让视频生成拖慢部署。", sections: [{ title: "潜在未来监督", paragraphs: ["少量 learnable foresight tokens 读取当前视觉语言上下文，冻结视频生成器用未来帧监督这些 token。动作 expert 同时读取它们，从而获得与任务相关的未来动态线索。", "训练仍保留 VQA、point、bbox 和 subtask 样本，防止 VLM 在大量动作数据中丢失组合语义。推理时视频教师和 decoder 都被移除，只保留压缩后的 foresight 路径。"] }], experimentReading: ["真实 MOF 差距很大，但仍应结合任务定义和数据匹配理解；公开模型有助于后续独立复核。"], reflections: ["未来 token 数量、教师层和动作层连接位置是较容易迁移到现有 VLA 的消融方向。"] },
    figures: [{ src: "/report-assets/2026-07-10/2607.04988-overview.png", alt: "InternVLA A1.5 原生 VLM foresight token 与统一动作 expert", caption: "Figure 2 · InternVLA-A1.5 的理解、潜在未来与动作统一结构。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 12,
    title: "Native Video-Action Pretraining for Generalizable Robot Control",
    arxivId: "2607.08639",
    url: "https://arxiv.org/abs/2607.08639",
    institutions: ["Ant Group LingBot / Robbyant"],
    signal: "从头构建面向机器人因果预测的视频动作基础模型，并用稀疏 MoE、未来块预测和异步重接地实现高频闭环",
    tags: ["LingBot-VA 2.0", "Native Video-Action", "Sparse MoE"],
    classification: { research: "WAM", training: "Pre-training", data: "跨本体数据", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://technology.robbyant.com/lingbot-va-v2" }],
    motivation: "把通用视频生成器改成机器人模型会继承重建导向 VAE、双向注意力和高延迟等不匹配；少量机器人微调还可能遗忘视频先验。",
    methodSummary: "LingBot-VA 2.0 从头训练语义 visual-action tokenizer 与因果 MoE 视频动作模型，加入多未来块监督和异步 foresight 推理。",
    architecture: "高层 VLM planner 给子任务；video stream 与 action stream 在 MoE 中交互；semantic VAE、MCP 和 autoregressive rollout 共同预测未来 latent 与动作。",
    optimization: "在 10+ 数据源、5000+ 机器人任务和 50K+ human-robot pairs 上预训练，再用每任务 10–20 条真机示范少样本后训练。",
    data: "开放数据包含 AgiBot、OXE、DROID 等并叠加内部机器人数据；统一 30 维动作空间，缺失维度用 mask 处理。",
    experiments: "真实日常操作平均成功率约 85%，每任务仅 20 条遥操作示范；RoboTwin 2.0 使用 2500 clean + 25000 randomized demos 做多任务比较。",
    novelty: "不同于改造双向视频扩散 backbone，论文从因果机器人 rollout 需求出发重做 tokenizer、预训练和推理系统。",
    strengths: "数据规模、少样本真机、仿真随机化、ICL 新任务和系统频率都有展示。",
    limitations: "大量内部数据与模型权重是否开放尚不明确；225Hz 是异步执行峰值，不等于每次完整模型查询频率。",
    transfer: "可借鉴 semantic visual-action tokenizer、MCP 辅助监督和每次新观测重接地的异步闭环。",
    experimentDetails: [{ title: "少样本真机与异步闭环", setup: "多项日常真机任务，每任务 20 条遥操作示范；另在 RoboTwin 2.0 50 任务评测 clean/randomized。", comparisons: "LingBot-VA、VLA baseline、不同 tokenizer、Dense/MoE、无 MCP 和同步推理。", results: ["真机平均成功率约 85%，并报告任务进度率。", "异步执行峰值可达 225Hz，未来 latent 与当前动作并行预测。", "四个未见任务使用人类参考视频做 in-context instruction，无需更新权重。"] }],
    reproducibilityDetails: { status: "信息不足", implementation: ["semantic visual-action tokenizer；causal sparse MoE；MCP；asynchronous foresight + re-grounding；30D unified action。"], verifiedResources: ["项目页与论文给出数据构成、网络维度、优化器和真实协议。"], missing: ["代码、权重、大规模内部数据与异步部署栈尚未确认公开。"] },
    deepDive: { lead: "LingBot-VA 2.0 把视频动作模型当作独立基础模型训练，而不是机器人数据上的视频模型插件。", sections: [{ title: "因果预训练与 foresight", paragraphs: ["semantic tokenizer 同时对齐视觉基础特征和动作，使 latent 不只服务像素重建。video/action 两个流在稀疏 MoE 中交互，训练只看因果历史，避免部署时输入形式与预训练不一致。", "MCP 从不同深度预测多个未来 latent chunk；运行时预测线程提前生成未来状态和动作，执行线程消费当前 chunk。新的真实观察到达后重新接地，避免长期依赖想象 latent。"] }], experimentReading: ["真实少样本和随机化仿真支持泛化主张，但公开性决定其结果能否被外部复核。"], reflections: ["评估异步 WAM 时应区分模型 query Hz、动作执行 Hz 与端到端观测闭环延迟。"] },
    figures: [{ src: "/report-assets/2026-07-10/2607.08639-overview.png", alt: "LingBot VA 2.0 planner 视频模型动作模型与 MCP", caption: "Figure 1 · LingBot-VA 2.0 的双系统、视频动作预训练与未来块预测。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 13,
    title: "RynnWorld-4D: 4D Embodied World Models for Robotic Manipulation",
    arxivId: "2607.06559",
    url: "https://arxiv.org/abs/2607.06559",
    institutions: ["DAMO Academy, Alibaba Group", "Hong Kong Embodied AI Lab", "CUHK", "Hupan Lab"],
    signal: "同步生成 RGB、深度与光流，用可反投影的 4D 表征连接世界预测和低层动作，并配套 2.54 亿帧数据",
    tags: ["4D World Model", "RGB-Depth-Flow", "Dexterous Manipulation"],
    classification: { research: "WM", training: "Pre-training", modalities: ["Depth / RGB-D", "Point Cloud / 3D"], data: "UMI / Ego / Human Video", platforms: ["机械臂", "灵巧手"] },
    resources: [{ label: "项目页", url: "https://alibaba-damo-academy.github.io/RynnWorld-4D.github.io" }, { label: "GitHub", url: "https://github.com/alibaba-damo-academy/RynnWorld-4D" }, { label: "模型", url: "https://huggingface.co/Alibaba-DAMO-Academy/RynnWorld-4D" }],
    motivation: "RGB 视频包含外观但缺少显式几何与运动；单独深度或光流又不能完整描述交互后的 4D 动态。",
    methodSummary: "在同一扩散模型中联合生成 RGB、depth、optical flow，利用深度与光流反投影出 3D scene flow；inverse dynamics head 直接从内部 4D 表征输出动作。",
    architecture: "RGB/Depth/Flow 三个 VAE 分支通过 joint cross-modal attention 交互，frame-wise 3D RoPE 保持时空结构；policy head 一次前向预测动作。",
    optimization: "先在 254.4M 帧混合人类与机器人数据上三阶段训练，再在真实双臂灵巧任务微调；消融大规模预训练和单/多模态分支。",
    data: "Rynn4DDataset 1.0 共 254.4M 帧，来源含 EPIC-KITCHENS、Ego4D、RoboMIND、RDT-1B 等，并生成深度/光流伪标签。",
    experiments: "六项 TIANJI M6 + WUJI Hand 任务，每项 35 次；RynnWorld-4D-Policy 平均 65.71%，比 Diffusion Policy 高 8.57 个百分点。",
    novelty: "与 RGB-D 视频模型相比，多出显式光流分支，并使 RGB-DF 可反投影为 3D scene flow，与动作表征更接近。",
    strengths: "数据规模、代码模型、三模态生成、真实灵巧任务和大规模预训练消融都较完整。",
    limitations: "深度和光流多数是伪标签，误差会耦合；65.71% 真实成功率说明精密长期控制仍未解决。",
    transfer: "适合需要显式几何运动的 WAM，可借鉴 RGB-DF target 和一次前向 inverse dynamics head。",
    experimentDetails: [{ title: "4D 世界建模与真实策略", setup: "254.4M 帧预训练；TIANJI M6 + WUJI Hand 六任务，每任务 35 次。", comparisons: "Diffusion Policy、π0/π0.5、RGB-only、RGB-D、无大规模 4D 预训练与不同 cross-modal attention。", results: ["真实任务平均成功率 65.71%，比 Diffusion Policy 高 8.57 个百分点。", "去掉 254.4M 帧预训练导致明显下降。", "RGB-only 不及联合 RGB-Depth-Flow，精密与协调任务差距更明显。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["RGB/Depth/Flow tri-branch；Joint Cross-Modal Attention；frame-wise 3D RoPE；single-pass inverse dynamics head。"], verifiedResources: ["项目页、GitHub 与模型公开；正文给出数据来源、阶段训练和真实协议。"], missing: ["完整 254.4M 帧数据与伪标签生成成本较高，部分内部机器人数据不可得。"] },
    deepDive: { lead: "RynnWorld-4D 让世界模型同时预测外观、几何和运动，并把三者压到可直接供动作头读取的表示中。", sections: [{ title: "RGB-DF 的互补性", paragraphs: ["RGB 提供语义和材质，深度提供每帧几何，光流提供像素随时间的运动。利用相机内参，深度与光流可反投影为 3D scene flow，形成更接近物理运动的监督。", "三个分支各自保留 VAE 与扩散块，通过 joint attention 交换特征。policy 不运行完整多步生成，而是一次读取内部 4D latent 输出动作，避免把 world model 的采样延迟带入控制。"] }], experimentReading: ["多模态和大规模预训练都有消融支持，但伪标签质量与真实成功率上限需要继续观察。"], reflections: ["可在自有数据上先比较 RGB-D 与 RGB-DF 的动作敏感性，再决定是否承担光流伪标签成本。"] },
    figures: [{ src: "/report-assets/2026-07-10/2607.06559-overview.png", alt: "RynnWorld 4D 三模态世界模型与动作策略分支", caption: "Figure 4 · RynnWorld-4D 的 RGB、Depth、Flow 三分支与 policy head。图片来自 arXiv 原论文。" }],
  },
];

const selectedPaperIds20260710 = [
  "2607.04927", "2607.07287", "2607.08877", "2607.08436", "2607.06323", "2607.06564",
  "2607.06678", "2607.06442", "2607.06370", "2607.04988", "2607.08639", "2607.08354",
];

const paperPool20260710 = [...paperCandidates20260710, ...paperDaily20260710Additions];

export const paperDaily20260710: Paper[] = selectedPaperIds20260710.map((paperId, index) => {
  const paper = paperPool20260710.find((candidate) => candidate.arxivId === paperId);
  if (!paper) throw new Error(`Missing selected paper: ${paperId}`);
  return { ...paper, rank: index + 1 };
});
