import type { Paper } from "./site-data";

const priorPaperDaily20260720: Paper[] = [
  {
    rank: 1,
    title: "RoboTTT: Context Scaling for Robot Policies",
    arxivId: "2607.15275",
    url: "https://arxiv.org/abs/2607.15275",
    institutions: ["NVIDIA", "Stanford University", "The University of Texas at Austin"],
    signal: "用测试时更新的 fast weights 将机器人策略的有效历史扩展到 8K timesteps",
    tags: ["Long Context", "Fast Weights", "Test-time Training"],
    classification: { research: "Memory", training: "Test-time Adaptation", platforms: ["机械臂", "夹爪"] },
    detailAttributes: { memoryImplementation: "TTT 两层 MLP fast weights", memoryHorizon: "最高 8K timesteps" },
    resources: [{ label: "项目页", url: "https://research.nvidia.com/labs/gear/robottt/" }],
    motivation: "长时装配需要记住阶段、失败与纠正关系；把更多历史帧直接拼接到注意力中会让计算和显存随序列长度增长。",
    methodSummary: "在 GR00T N1.7 的动作 DiT 中插入 TTT 层：每个时刻用当前 token 更新一组 fast weights，再用这组状态读取压缩后的历史。训练采用 sequence action forcing 和 truncated BPTT。",
    architecture: "视觉语言主干保持 GR00T N1.7 结构，动作专家包含 16 个 DiT block；跨帧 TTT 模块是两层 MLP，并用 16 个 register tokens 承载序列状态，tanh gate 以 0.001 初始化以稳定接入预训练模型。",
    optimization: "先从 GR00T N1.7 初始化并进行 30K steps 预训练，再在 YAM 任务上 20K steps 后训练；动作生成使用 flow matching，序列训练通过 TBPTT 控制反向传播长度。",
    data: "预训练混合桌面双臂机器人数据与第一人称人类视频；后训练为 YAM 三项双臂装配任务，约 8、6、5 小时真实数据。",
    experiments: "三项 YAM 长时装配的平均任务完成度为 79%，对照 GR00T N1.7 为 42%、GDN 为 56%；8K 上下文为 71.5%，明显高于 1K 的 43.9%。",
    novelty: "相对固定窗口 attention 或拼接历史，RoboTTT 用固定大小、可在线更新的参数状态压缩历史；1K/8K 与移除 TTT 的对照直接检验了上下文长度，而不是只比较模型容量。",
    strengths: "在多阶段双臂真机装配上验证长上下文，并同时给出上下文长度、训练方式和模块位置消融。",
    limitations: "预训练使用 16 张 GB200，完整代码和权重未确认公开；fast weights 仍可能遗忘早期事件，三项任务也不足以证明开放环境泛化。",
    transfer: "可把接触事件、失败恢复和阶段切换显式写入 fast-weight 更新信号，用固定状态容量替代不断增长的视觉帧缓存。",
    experimentDetails: [
      { title: "长时双臂装配", setup: "YAM 平台上的 Adapt Sander、Assemble Gear 与 GearBot；前两项每个方法 20 次，GearBot 10 次，并记录完整成功与阶段完成度。", comparisons: "GR00T N1.7 单步基线、GDN 长上下文基线、不同 TTT 上下文长度及训练消融。", results: ["三任务平均完成度：RoboTTT 79%，GDN 56%，GR00T N1.7 42%。", "完整成功分别为 9/20、13/20 和 2/10；说明完成度提升并不等于所有长任务都已稳定完成。", "上下文从 1K 扩展到 8K 后平均完成度由 43.9% 提升至 71.5%。"] },
    ],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["NVIDIA GEAR 项目页提供论文、视频和任务展示。"], implementation: ["GR00T N1.7；16 个 DiT block；两层 MLP TTT；16 register tokens；tanh gate 初值 0.001；flow matching；TBPTT；30K + 20K steps；16×GB200。"], missing: ["完整训练代码、权重、预训练数据配比与真机数据尚未确认公开。"] },
    deepDive: { lead: "RoboTTT 的核心不是把更多图像送入模型，而是把逐步到来的观测—动作历史写入一组可更新的内部参数。", sections: [
      { title: "跨时间 fast weights", paragraphs: ["当前帧仍由 attention 处理空间与模态内交互；TTT 层在时间维度上根据新 token 更新两层 MLP，使过去信息不再以完整 KV 序列保存。register tokens 为更新提供稳定载体，门控让新模块从近似恒等映射开始接入。", "训练时 sequence action forcing 保持历史动作与部署条件一致，TBPTT 只跨有限段回传梯度；推理时状态随 episode 递推，单步存储不随历史长度线性增加。"] },
    ], equations: [{ name: "fast-weight 递推", expression: "Wₜ = Wₜ₋₁ − η ∇W ℒ(Wₜ₋₁; xₜ),   yₜ = f(xₜ; Wₜ)", explanation: "每个时刻先用当前 token 的自监督目标更新 fast weights，再由更新后的状态生成跨时间表征；Wₜ 因而是历史的参数化压缩。" }, { name: "动作 flow matching", expression: "ℒFM = E ‖vθ(aτ, τ, c) − (a₁ − a₀)‖²", explanation: "动作专家学习从噪声动作 a₀ 到真实动作 a₁ 的速度场，c 包含当前多模态观察与 TTT 历史状态。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.15275-architecture.png", alt: "RoboTTT 在动作 DiT 中加入跨时间 TTT 层并维护 fast weights 的训练与推理结构", caption: "Figure 2 · RoboTTT 模型、序列训练与递推推理结构。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 2,
    title: "Never Too Late for Force: Accelerating VLA Post-Training with Reactive Force Injection",
    arxivId: "2607.14236",
    url: "https://arxiv.org/abs/2607.14236",
    institutions: ["Shanghai Jiao Tong University", "Shanghai Innovation Institute", "Southern University of Science and Technology", "Noematrix Ltd."],
    signal: "为预训练 VLA 增加力觉反应旁路，并用在线纠正覆盖接触失败状态",
    tags: ["Force / Torque", "Online Correction", "VLA Post-training"],
    classification: { research: "VLA", training: "Post-training", modalities: ["Force / Torque"], data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://lift-policy.github.io/" }],
    motivation: "预训练 VLA 能理解任务语义，但视觉帧率与大模型推理不足以在插入、折叠等接触阶段快速响应力变化。",
    methodSummary: "LIFT 复制一个 reactive action expert，用因果 GRU 编码短期 6D wrench，并通过零初始化 cross-attention 注入动作层；部署中收集失败状态的人工纠正，再与离线数据混合做 DAgger 式后训练。",
    architecture: "主干为 π0.5 的 PaliGemma VLM 与 flow-matching action expert；力分支用隐藏维 512 的 causal GRU 输出 1024 维表征，预测 10 步 action horizon，并用 latency offset=3 对齐传感与执行。",
    optimization: "AdamW、batch size 32、学习率 5e-5、30K steps；每个 checkpoint 执行 10 次自主 rollout，再按失败分布追加纠正，在线数据与离线数据用自适应比例混合。",
    data: "Flexiv Rizon 4S 上的毛巾折叠、书本插入和汉诺塔放环；训练包含离线任务示范与多轮在线人工纠正轨迹。",
    experiments: "三项真机接触任务中，完整 LIFT 均优于视觉-only、只加力输入和无在线纠正版本；消融显示 reactive expert 与 DAgger 数据闭环缺一不可。",
    novelty: "与把 wrench 直接拼到 VLA 输入不同，LIFT 把快速力响应放到独立动作旁路，并专门采集当前策略会访问的失败状态；主要增益来自结构与数据分布两部分。",
    strengths: "结构、力输入和在线纠正均有对应消融，实验直接针对视觉 VLA 在接触阶段的失败。",
    limitations: "依赖人工纠正和真实设备迭代，只验证单臂三任务；在线采集成本与跨力传感器迁移尚未解决。",
    transfer: "适合把低频 VLA 作为语义主干，把 force、slip 或 collision event 放入独立高速旁路，并只在失败区域收集纠正。",
    experimentDetails: [{ title: "三项接触任务与在线迭代", setup: "Flexiv Rizon 4S 执行毛巾折叠、书本插入和汉诺塔放环；每个训练 checkpoint 进行 10 次自主 rollout，并对失败状态追加人工纠正。", comparisons: "π0.5 视觉基线、直接力输入、reactive expert、离线-only 与完整 online correction。", results: ["完整方法在三项任务的最终成功率均最高，尤其改善插入与放环时的接触恢复。", "移除 force memory 或 reactive expert 会在接触阶段明显退化；只用离线数据则难以覆盖策略自身造成的偏移状态。", "在线数据混合比例按最近 rollout 表现自适应调整，避免后期纠正数据完全淹没原始示范。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["官方项目页提供论文、视频与实验展示。"], implementation: ["π0.5；causal GRU hidden=512、output=1024；action horizon=10；latency offset=3；batch=32；AdamW；lr=5e-5；30K steps。"], missing: ["代码、权重、完整纠正轨迹与每轮样本数量未确认公开。"] },
    deepDive: { lead: "LIFT 把接触控制看成“慢语义主干 + 快物理旁路”的后训练问题。", sections: [{ title: "力记忆与动作注入", paragraphs: ["连续 6D wrench 先经 causal GRU 压缩为短时力记忆，再由零初始化 cross-attention 写入 reactive action expert。零初始化使初始输出接近原 π0.5，后训练只需逐步学会在接触阶段偏离主策略。", "在线 rollout 暴露预训练策略在真实闭环中访问的错误状态，人工纠正将这些状态补回训练集；混合权重按近期性能裁剪在 0.2–0.8 之间。"] }], equations: [{ name: "在线数据混合", expression: "Dtrain = (1 − α)Doffline + αDonline,   α = clip(g(success), 0.2, 0.8)", explanation: "随着自主成功率变化调整纠正数据占比；低成功阶段更重视 Donline，同时保留离线示范防止遗忘。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.14236-architecture.png", alt: "LIFT 在预训练 VLA 旁加入 reactive action expert 并通过交叉注意力注入力记忆", caption: "Figure 2 · LIFT 的力觉编码、reactive action expert 与在线纠正流程。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 3,
    title: "Scaling Behavior Foundation Model for Humanoid Robots",
    arxivId: "2607.15163",
    url: "https://arxiv.org/abs/2607.15163",
    institutions: ["The Chinese University of Hong Kong", "Shanghai Jiao Tong University", "Zhejiang University", "Peking University", "Tsinghua University", "Galbot", "Shanghai AI Laboratory"],
    signal: "用 1.02 亿帧跨来源运动数据训练可扩展 humanoid 行为基础模型",
    tags: ["Humanoid", "Motion Foundation Model", "Large-scale Data"],
    classification: { research: "其他", training: "Pre-training", data: "跨本体数据", platforms: ["Humanoid"], deployment: "Sim2Real" },
    resources: [{ label: "项目页", url: "https://bfm.cs.cuhk.edu.hk/" }],
    motivation: "humanoid 控制器常按动作或平台分别训练，难以利用分散的 mocap、视频重建与机器人运动数据形成统一行为先验。",
    methodSummary: "将不同来源运动统一重定向到 humanoid 状态—动作接口，以 PPO 训练 motion tracking teacher，再把大规模轨迹蒸馏进 Humanoid Transformer，形成可按目标运动条件控制的行为基础模型。",
    architecture: "Humanoid Transformer 读取历史本体状态与目标运动 token，输出低层关节目标；训练管线先完成跨骨架 retargeting，再用并行仿真强化学习建立稳定跟踪行为。",
    optimization: "核心是大规模 RL motion tracking 与数据扩展，不是 VLA 后训练；模型随数据与参数规模扩展，并在真实 humanoid 上部署。",
    data: "约 1.02 亿帧、50 Hz 的运动序列，混合 AMASS 等公开 mocap、视频恢复动作及机器人运动数据，覆盖全身、上肢与移动行为。",
    experiments: "在多个 humanoid 平台和多类动作上比较专用控制器与通用基础模型；局部关节误差降低超过 10%，全局关键点误差最高降低 82%，并展示真实机器人复杂动作跟踪。",
    novelty: "相对单数据集、单机器人 motion policy，该工作把数据规模、来源多样性和模型容量同时作为变量，并验证统一行为模型可替代多套专用控制器。",
    strengths: "数据规模、跨来源重定向、扩展规律与真机验证构成完整系统证据。",
    limitations: "重点是参考运动跟踪而非语言条件任务执行；完整数据清洗与训练成本高，部分源数据许可也限制端到端复现。",
    transfer: "可把该类行为基础模型作为 humanoid VLA 的低层动作先验，让高层只预测运动目标或稀疏控制条件。",
    experimentDetails: [{ title: "规模扩展与真机动作跟踪", setup: "在统一评测集上比较不同数据规模、模型规模和专用/通用控制器，并将模型部署到真实 humanoid。", comparisons: "逐任务专用策略、较小数据/模型版本与统一 Behavior Foundation Model。", results: ["论文报告局部 MPKPE 相对既有控制器降低超过 10%，全局 MPKPE 最高降低 82%。", "增加运动数据的覆盖度比只增加相近轨迹更有效，支持跨来源数据的互补性。", "真机展示包含全身动态动作，但不是开放语言任务的成功率评测。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["官方项目页提供模型说明、真机视频与论文。"], implementation: ["统一 retargeting；50 Hz 运动序列；PPO motion tracking；Transformer policy；本体历史与目标运动条件。"], missing: ["完整 1.02 亿帧训练集、清洗配比、全部训练超参与权重开放状态需以项目页后续发布为准。"] },
    deepDive: { lead: "这项工作把 humanoid 低层控制从“每个动作训练一套策略”推进到共享运动分布上的基础模型。", sections: [{ title: "统一运动接口", paragraphs: ["不同人体骨架与机器人轨迹先被重定向到统一 humanoid 关节和根节点表示；仿真中的 tracking reward 同时约束局部关节、全局关键点、速度和稳定性。", "Humanoid Transformer 使用历史本体状态保持动力学连续性，并用目标运动窗口决定未来姿态。其泛化边界主要由运动覆盖而非语言理解决定。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.15163-architecture.png", alt: "Behavior Foundation Model 从大规模运动数据、重定向到 Humanoid Transformer 控制的整体架构", caption: "官方模型图 · 大规模运动数据到 Humanoid Transformer 行为策略的训练管线。图片来自论文官方项目页。" }],
  },
  {
    rank: 4,
    title: "Data and Learning Where it Matters for Contact-Rich Manipulation",
    arxivId: "2607.15982",
    url: "https://arxiv.org/abs/2607.15982",
    institutions: ["Technical University of Munich", "Siemens"],
    signal: "在接触区域定向采样并学习残差动作，以少量真机数据解决高精度插装",
    tags: ["Contact-rich", "Targeted Data", "Residual Policy"],
    classification: { research: "表征学习", training: "BC", modalities: ["Force / Torque", "State / Proprioception"], data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    motivation: "接触任务的大部分自由空间轨迹易由规划器解决，真正决定成功的是狭小接触区域；均匀收集整段示范会把预算浪费在低信息状态。",
    methodSummary: "用规划器把机器人带到接触邻域，在该区域以 0.8 概率执行随机探索并记录力、控制误差和状态；策略只学习相对规划动作的残差，因此数据与模型容量集中在接触修正。",
    architecture: "DINOv2 视觉特征投影到 16 维，与力/力矩、controller error、笛卡尔速度、上一动作拼接；轻量策略输出残差控制量，名义轨迹仍由 motion planner 提供。",
    optimization: "每轮 150 steps，数据仅训练 5 epochs；论文比较 flow/diffusion policy、π0.5、HIL-SERL 与纯规划，并对随机采样概率和输入状态做消融。",
    data: "四项真实接触任务，每项约 300–500 个短 episode、2–2.5 小时采集；OOD 测试改变部件位置、几何或接触条件。",
    experiments: "四任务每种方法 50 次，完整方法平均成功率 96%，最强纯规划对照约 55%；OOD 每格 20 次，四任务为 90%、85%、90%、95%，峰值接触力最多降低 49%。",
    novelty: "相对整轨迹 imitation learning 或纯 RL，该方法只在规划器不可靠的接触邻域采集数据，并学习 residual 而非完整动作；直接对照显示收益来自数据位置与残差结构。",
    strengths: "四任务、每格 50 次、OOD 与力峰值指标充分支撑“数据采在哪里”这一核心命题。",
    limitations: "需要可用的规划器、接触区域定义和控制器误差信号；复杂可变形物体或无几何先验任务不一定能分离自由空间与接触阶段。",
    transfer: "可用于 VLA 后端：高层负责到达，接触触发后切换为小型 residual controller，并把采集预算集中在失败邻域。",
    experimentDetails: [{ title: "四项接触任务与 OOD", setup: "真实机器人完成精密插装、表面接触等四项任务；主表每方法每任务 50 次，OOD 每格 20 次。", comparisons: "DiTFlow、Diffusion Policy、π0.5、HIL-SERL、纯 motion planning 及输入/采样消融。", results: ["完整方法四任务平均成功率 96%，显著高于最强规划对照约 55%。", "OOD 条件下四任务成功率为 90%、85%、90%、95%。", "定向学习的残差降低碰撞与过载，报告的峰值接触力最多下降 49%。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["论文完整披露四任务、数据时长、episode 数、对照和 rollout 次数。"], implementation: ["DINOv2 feature→16D；force/torque、controller error、Cartesian velocity、previous action；random action probability=0.8；episode=150 steps；5 epochs。"], missing: ["当前未确认代码、真实数据与标定配置公开。"] },
    deepDive: { lead: "论文把接触策略视为规划器的局部误差修正器，而不是从像素重新学习整条轨迹。", sections: [{ title: "接触邻域残差学习", paragraphs: ["motion planner 先提供名义动作 aplan；机器人进入接触邻域后，策略根据视觉、力和控制误差输出小残差 δa。随机探索也只发生在这一局部区域，因此每条样本都更接近失败边界。", "DINOv2 提供对象与几何语义，force 和 controller error 则描述实际约束。上一动作帮助网络保持短期连续性，避免接触中的高频抖动。"] }], equations: [{ name: "残差控制", expression: "aₜ = aplan,ₜ + δaθ(oₜ, fₜ, eₜ, vₜ, aₜ₋₁)", explanation: "规划器负责全局可达性，学习策略只修正接触阶段由摩擦、装配公差和模型误差造成的偏差。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.15982-method.png", alt: "面向接触区域的数据采集、名义规划与残差策略学习流程", caption: "Figure 1 · 在接触邻域定向收集数据并学习 planner residual 的方法总览。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 5,
    title: "Open-AoE: A Large-Scale Open Dataset for Action-oriented Embodied Intelligence",
    arxivId: "2607.14183",
    url: "https://arxiv.org/abs/2607.14183",
    institutions: ["Ant Group"],
    signal: "以手机众包构建面向动作理解的人类第一视角大规模开放数据",
    tags: ["Ego Data", "Action Annotation", "Open Dataset"],
    classification: { research: "表征学习", training: "Pre-training", data: "UMI / Ego / Human Video", platforms: ["其他平台"] },
    resources: [{ label: "GitHub", url: "https://github.com/Open-AoE/Open-AoE" }, { label: "模型", url: "https://huggingface.co/datasets/Open-AoE/Open-AoE" }],
    motivation: "具身预训练需要大量以手部交互和任务阶段为中心的视频，但机器人采集昂贵，普通互联网视频又缺少动作、轨迹和对象级结构。",
    methodSummary: "通过手机端标准化众包采集第一视角任务视频，自动恢复相机与 MANO 手部轨迹，再用多阶段模型与人工审核生成 atomic action、对象、场景和语言标注。",
    architecture: "数据管线包含移动端采集、质量检测、手/相机几何恢复、时序动作切分和语义标注；其产物可分别用于 VLM/VLA 的视频预训练、动作分段和空间轨迹监督。",
    optimization: "论文贡献是数据生产与清洗，不提出新的 policy 优化算法；下游实验用相同模型对比加入或不加入 Open-AoE 预训练。",
    data: "超过 2,000 小时、500+ 贡献者、400+ 手机、400+ 场景和 8,000+ 任务；100 小时审计子集含 32,407 条动作描述、175 个动词、8,030 个对象和 135 类场景。",
    experiments: "下游动作理解、具身视频表征和机器人迁移实验显示 Open-AoE 预训练带来一致改善；人工审计同时量化切分、轨迹与语义标签质量。",
    novelty: "相对只提供视频—文本对的数据集，Open-AoE 同时开放相机轨迹、手部轨迹、atomic action 与对象语义；与机器人数据相比，它用消费级设备显著扩展采集规模。",
    strengths: "规模、采集规范、自动处理与人工审计均较完整，数据和工具链有公开入口。",
    limitations: "人手与机器人末端执行器仍有本体差异；手机视角、任务分布和自动标签错误会形成系统偏置。",
    transfer: "适合为 VLA 预训练增加动作边界、手—物轨迹和任务阶段监督，再用少量机器人数据学习本体映射。",
    experimentDetails: [{ title: "数据审计与下游迁移", setup: "对 100 小时子集做细粒度人工审计，并在动作理解、视频表征和机器人相关任务上比较预训练数据组成。", comparisons: "不使用 Open-AoE、使用普通视频数据与加入 Open-AoE 的相同下游模型。", results: ["审计子集覆盖 32,407 条动作描述、175 个动词和 8,030 个对象，说明不是少数脚本任务的重复录制。", "加入动作导向预训练后多个下游指标一致提升，但收益不能单独归因于某一种标注。", "论文公开数据与处理入口，便于后续检验跨本体迁移。"] }],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["GitHub、Hugging Face 与 ModelScope 数据入口已公开。"], implementation: ["手机众包；相机轨迹与 MANO 手轨迹恢复；atomic action segmentation；多阶段自动标注与人工审计。"], missing: ["完整 2,000 小时数据的所有授权与部分处理模型权重需按发布页逐项核验。"] },
    deepDive: { lead: "Open-AoE 的主要价值是把人类视频从“看见任务”变成带有动作边界和几何轨迹的训练样本。", sections: [{ title: "从原始视频到动作样本", paragraphs: ["采集端约束相机姿态、任务说明与视频质量；处理端先恢复相机和双手运动，再按原子动作切分，最后为动作、对象和场景生成语言标签。", "相机/手轨迹可给 world model 或 action tokenizer 提供连续几何监督，atomic action 则可用于 subtask 边界和长时视频采样。机器人使用时仍需要把人手空间映射到末端执行器空间。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.14183-overview.png", alt: "Open-AoE 从手机众包采集到手部轨迹、动作切分与多层标注的数据流程", caption: "Figure 1 · Open-AoE 采集规模、处理管线与标注层次。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 6,
    title: "Active Real-World Factor-Based Evaluation for Generalist Robot Policies",
    arxivId: "2607.14439",
    url: "https://arxiv.org/abs/2607.14439",
    institutions: ["University of Minnesota Twin Cities"],
    signal: "用主动测试在真实机器人上更少次数地估计策略在因素空间中的表现",
    tags: ["Active Testing", "Evaluation", "Generalization"],
    classification: { research: "其他", training: "Test-time Adaptation", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    motivation: "几十次随机 rollout 既无法覆盖物体位置、台面高度与相机视角的组合，也可能偶然高估或低估策略。",
    methodSummary: "把评测配置视为设计空间，用概率 surrogate 预测连续任务得分及不确定性，再由 acquisition function 选择下一次最有信息量的真实机器人试验。",
    architecture: "框架比较 Gaussian Process、Mixture Density Network 和 Deep Ensemble，并配合 posterior uncertainty、NIPV、BALD、EPIG 等 acquisition；主方法采用带 ARD RBF kernel 的 GP。",
    optimization: "这不是 policy 训练方法；surrogate 仅用已经执行的评测结果在线拟合，30 个随机点 warm start，之后逐步选择新配置直到预算耗尽。",
    data: "UR5e 上三项 π0 manipulation 任务，共 2,331 个真实配置；因素为 11×11 物体位置网格、3 个台面高度和 3 个相机视角。",
    experiments: "以完整 2,331 次评测作为 ground truth，主动测试在相同预测误差下通常比随机测试少 20%–40% 试验，并能更快定位相机/位置等失败区域。",
    novelty: "相对随机抽样成功率，它估计的是整个因素空间的连续表现分布，并显式使用 epistemic uncertainty 选择下一次真实试验。",
    strengths: "2,331 次真实机器人评测提供少见的完整 ground truth，可检验主动选择是否真的节省试验。",
    limitations: "主动过程是在已收集的全量结果上离线回放，假设固定配置下 policy 随机性可忽略；只有三任务和三个因素。",
    transfer: "可把日报关注的泛化维度转成结构化因素，用更少 rollout 构建 failure map，而不是只报告单一平均成功率。",
    experimentDetails: [{ title: "主动测试与随机评测", setup: "UR5e 上 Pick blue block、Upright cup、Put green block in pot；2,331 个有效配置，每次约 1 分钟。", comparisons: "随机无放回采样，以及 GP/MDN/Deep Ensemble 与多种 acquisition function 组合。", results: ["在 100 次预算下，最佳主动策略通常节省 20–40 次试验即可达到随机测试的估计精度。", "完整因素图揭示相机视角、台面高度和对象位置的非均匀失败区域，单一成功率会掩盖这些结构。", "不同 surrogate/acquisition 的优劣随任务变化，论文没有把一个组合宣称为普遍最优。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["论文给出 2,331 个配置、任务打分、surrogate 和 acquisition 细节。"], implementation: ["GP with ARD-RBF；30-point random warm start；100-trial budget；连续 progress score；π0 policy；UR5e。"], missing: ["当前未确认全量真实评测结果、代码和 π0 后训练数据公开。"] },
    deepDive: { lead: "方法把“做多少次 rollout”改写为序贯实验设计：每一次真实执行都应最大限度降低对未测配置的未知。", sections: [{ title: "因素空间与概率代理", paragraphs: ["配置 x 由对象位置、台面高度和相机视角组成，真实策略得分 f(x) 只在执行后可见。GP 用已测点拟合均值和方差，ARD lengthscale 还能反映不同因素对表现变化的敏感度。", "acquisition 并非寻找最高成功率，而是寻找能最大程度减少全空间不确定性的下一点；因此它更接近评测资源分配而不是训练时的主动学习。"] }], equations: [{ name: "因素化评测空间", expression: "x = (xposition, xheight, xcamera) ∈ Fposition × Fheight × Fcamera", explanation: "每次真实 rollout 对应因素组合 x，目标是用有限观测恢复整个 f(x) 表现分布。" }, { name: "GP 选择信号", expression: "xnext = arg maxx α(μt(x), σt(x))", explanation: "acquisition α 根据 surrogate 的预测均值与 epistemic uncertainty 选择下一次评测配置。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.14439-overview.jpg", alt: "主动因素评测用概率代理和采集函数选择下一次真实机器人配置", caption: "Figure 1 · Factor-based active evaluation 整体流程。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 7,
    title: "Representation-Aligned Tactile Grounding for Contact-Rich Robotic Manipulation",
    arxivId: "2607.14609",
    url: "https://arxiv.org/abs/2607.14609",
    institutions: ["Fudan University", "Lenovo CTO Organization", "Nanyang Technological University", "TeleAI, China Telecom"],
    signal: "先定位最具物理可预测性的动作层，再用未来触觉监督整形该层表征",
    tags: ["Tactile", "Representation Alignment", "Contact-rich"],
    classification: { research: "表征学习", training: "Post-training", modalities: ["Tactile"], platforms: ["机械臂", "夹爪"] },
    motivation: "给 VLA 增加触觉辅助损失并不保证监督落在真正决定动作的层，错误注入位置可能只增加训练负担。",
    methodSummary: "先冻结模型并用 linear probe 测量各 action-expert 层对未来触觉的可预测性，再在最佳层接入 Latent Tactile Predictor；触觉只在训练期提供监督，部署时移除预测头。",
    architecture: "视觉语言 backbone 与 action expert 保持不变；中间 hidden state 通过轻量 projector 预测未来 tactile latent，loss 反向塑造最接近接触动力学的层。",
    optimization: "在 SmolVLA 和 π0 两个 backbone 上做后训练；比较不同注入层、无触觉监督、直接触觉接口和 latent predictor。",
    data: "ARX R5 配 PaXini 触觉传感器，五项接触任务，每项 50 条专家示范。",
    experiments: "每任务每方法 20 次真机试验；两个 backbone 上均优于原模型和未对齐触觉接口，层选择消融显示中间动作层比任意末层监督更有效。",
    novelty: "相对“有触觉就加 loss”，论文先用 probe 建立表征层与未来接触信号的对应，再决定监督位置；推理时不依赖触觉传感器。",
    strengths: "层级诊断、两个 backbone 和五任务真机对照让表征对齐结论较清楚。",
    limitations: "单平台、单触觉传感器与有限任务，尚未证明最佳层在更大 VLA 或跨传感器时保持一致。",
    transfer: "同样的 probe→alignment 流程可用于未来力、contact phase、slip 或 failure-risk 表征。",
    experimentDetails: [{ title: "层选择与双 backbone 验证", setup: "ARX R5 上五项接触任务，每项 50 条示范、每种方法 20 次真机 rollout。", comparisons: "SmolVLA/π0 原模型、不同 action-expert 层、直接触觉输入与 latent tactile grounding。", results: ["两个 backbone 上，选择高 tactile-predictability 层的版本均取得最高或并列最高成功率。", "在不可预测层强加触觉目标的收益较小甚至退化，支持‘监督位置’而非单纯额外 loss 的解释。", "触觉预测头部署时移除，因此控制延迟不因触觉生成增加。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["论文披露平台、传感器、示范量、任务数和 rollout 协议。"], implementation: ["linear probe layer selection；future latent tactile predictor；SmolVLA 与 π0；training-only auxiliary head。"], missing: ["代码、数据、触觉 encoder 权重和完整训练超参未确认公开。"] },
    deepDive: { lead: "这项工作关心的不是触觉是否有用，而是动作模型内部哪一层最适合接收物理监督。", sections: [{ title: "可预测性驱动的监督位置", paragraphs: ["对各中间层训练只读 linear probe，预测未来触觉 latent。probe 表现用于定位已经包含接触前兆、又尚未完全压缩成动作输出的层。", "随后 Latent Tactile Predictor 在该层施加训练目标；部署时模型只用原有视觉、语言和状态输入，触觉传感器及预测头都不进入在线路径。"] }], equations: [{ name: "触觉对齐目标", expression: "ℒtactile = ‖P(hℓ,t) − ztactile,t+Δ‖²", explanation: "P 从选定动作层 hℓ,t 预测未来触觉 latent；通过 Δ 步预测迫使表征编码接触演化而非只重建当前读数。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.14609-overview.png", alt: "从动作专家中间表征预测未来触觉并选择最佳监督层的框架", caption: "Figure 3 · Future latent tactile grounding 与层级选择。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 8,
    title: "Beyond Implicit Force: Evaluating Explicit Force-Torque Proxies in Action Chunking with Transformers",
    arxivId: "2607.14578",
    url: "https://arxiv.org/abs/2607.14578",
    institutions: ["Australian Institute for Machine Learning, Adelaide University"],
    signal: "揭示 leader–follower 遥操作误差中的隐式力线索，并用电机电流/关节力矩显式恢复",
    tags: ["Force Proxy", "ACT", "Contact Dynamics"],
    classification: { research: "表征学习", training: "BC", modalities: ["Force / Torque", "State / Proprioception"], platforms: ["机械臂", "夹爪"] },
    motivation: "ACT 在接触任务中的‘力感知’可能并非来自视觉，而是示范中 leader 指令与 follower 实际关节的跟踪误差；若改成预测真实 follower 状态，这条隐藏线索会消失。",
    methodSummary: "构造 observation-centric ACT-o，只预测 follower joint state 以移除 leader–follower discrepancy；再加入由电机电流或 joint effort 计算的 torque proxy，检验显式低成本力信号能否恢复接触行为。",
    architecture: "保持 ACT 的 CVAE 与 Transformer action chunking 主体，只改变输入/预测目标；ACT-o3 将关节状态与 torque proxy 分离编码后融合，避免把执行器力矩当作普通位置维度。",
    optimization: "小样本行为克隆，不使用 RL；所有变体使用同一 ALOHA/ViperX 数据与训练管线，以隔离隐式误差和显式力 proxy 的影响。",
    data: "四项真实接触任务：板面擦拭、插头插入、软瓶按压和泡棉力平衡停止；每项由 leader–follower 遥操作采集。",
    experiments: "移除隐式 leader–follower 误差后，ACT-o 在关键接触阶段严重退化；加入 torque proxy 的 ACT-o3 恢复或超过基础 ACT，并在四类不同接触机制上保持一致。",
    novelty: "相对直接宣称 ACT 从视觉学到力，该工作用预测目标干预拆出隐藏的 teleoperation cue，再以低成本 torque proxy 做因果式恢复对照。",
    strengths: "四种接触机制与针对性模型变体清楚回答了‘成功来自哪条信号’。",
    limitations: "torque proxy 受摩擦、重力补偿和执行器标定影响；只验证 ALOHA/ViperX，结论不必然迁移到不同控制器。",
    transfer: "检查机器人数据中 commanded/executed action 差异，避免把隐式控制误差误认为视觉智能；必要时将其显式建模。",
    experimentDetails: [{ title: "隐式线索移除与显式力恢复", setup: "ALOHA/ViperX 上的 surface following、precision insertion、stiffness discrimination 和 force-equilibrium stopping。", comparisons: "原 ACT、移除 leader command discrepancy 的 ACT-o、加入 servo-current/joint-effort torque proxy 的变体。", results: ["ACT-o 在 force-critical 阶段出现明显失败，说明原数据中的 leader–follower tracking error 携带接触信息。", "加入 torque proxy 后，策略在四任务中恢复稳健接触行为，并在部分指标上超过原 ACT。", "不同任务分别考察法向力维持、插入约束、材料刚度和力阈值停止，避免只在单一插孔上验证。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["论文给出 ALOHA/ViperX 硬件、四项任务、ACT 变体和指标定义。"], implementation: ["ACT CVAE/Transformer；follower-state prediction；servo current 或 joint effort torque proxy；observation-centric input reformulation。"], missing: ["当前未确认代码、示范数据和各任务全部训练超参公开。"] },
    deepDive: { lead: "论文通过改写 ACT 的预测对象，证明一部分接触能力实际来自遥操作系统留下的控制误差信号。", sections: [{ title: "从隐式误差到显式 torque", paragraphs: ["leader 关节是操作者意图，follower 关节是接触约束后的执行结果；两者差值在碰撞、摩擦或受阻时增大。普通 ACT 预测 leader command，因而可以间接读取这条差值。", "ACT-o 改为预测 follower state 后，输入输出之间不再保留同样的 discrepancy。ACT-o3 再注入由电机电流/effort 得到的 torque proxy，使接触信息从数据偶然产物变成明确观测。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.14578-architecture.png", alt: "ACT、observation-centric ACT 与显式 torque proxy 变体的模型和信号路径", caption: "Figure 3 · ACT-o/ACT-o3 的输入、预测目标与 torque proxy 注入。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 9,
    title: "Reflex: Real-Time Vision-Language-Action Control through Streaming Inference",
    arxivId: "2607.14695",
    url: "https://arxiv.org/abs/2607.14695",
    institutions: ["Independent Research"],
    signal: "为 flow-matching VLA 提供精确 KV cache 与异步流式推理，达到稳定 50 Hz",
    tags: ["Streaming Inference", "KV Cache", "Real-time VLA"],
    classification: { research: "VLA", training: "Test-time Adaptation", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "GitHub", url: "https://github.com/9yc/Reflex" }],
    motivation: "flow-matching VLA 的多步去噪会因 timestep 条件破坏普通 KV cache；整段重算太慢，错误复用 cache 又会改变模型输出。",
    methodSummary: "把 context 分成 static、sliding 和 dynamic 三个 attention 区域，只对 timestep 相关区域重算；AdaRMSNorm 防止 BF16 在连续流推理中数值坍塌，异步 pipeline 重叠视觉编码、动作生成与执行。",
    architecture: "兼容 π0.5 2.3B 与 π0 3.1B；partitioned attention 用 ring buffer 维护 O(1) 增量 cache，future-state approximation 减少观察等待，CUDA/operator fusion 降低 kernel overhead。",
    optimization: "无需重训即可应用核心 streaming path；AdaRMSNorm 和分区规则面向推理改造，论文在 LIBERO、Kinetix 和 AgileX PiPer 真机上验证。",
    data: "不新增训练数据；使用公开 LIBERO、Kinetix 评测和 AgileX PiPer 真机移动目标任务。",
    experiments: "推理从 135.2 ms 降至 52.4 ms，整体 2.58× 加速并稳定 50 Hz；反应延迟最高降低 54%，partitioned attention 与完整 batch 输出误差为 0。",
    novelty: "相对近似 KV 复用或降低去噪步数，Reflex 通过注意力分区保持固定输入下的数学等价，并把控制等待与模型计算做流水化。",
    strengths: "同时验证精确性、吞吐、延迟、内存、任务成功率和真机移动目标响应。",
    limitations: "系统优化依赖模型结构与 GPU kernel；更快推理不能修复 policy 本身的视觉或任务泛化错误。",
    transfer: "可把 VLA 部署拆成感知缓存、动态去噪和执行三个时钟域，先验证 cache 等价再做异步化。",
    experimentDetails: [{ title: "系统效率、任务保持与真机响应", setup: "π0.5/π0 在 LIBERO、Kinetix 与 AgileX PiPer 真机上评测延迟、吞吐、内存和任务表现。", comparisons: "完整阻塞推理、错误/近似 cache、逐项加入 partitioned attention、AdaRMSNorm、异步 pipeline 与 kernel fusion。", results: ["端到端推理延迟由 135.2 ms 降到 52.4 ms，速度提升 2.58×。", "系统稳定达到 50 Hz streaming，动作反应延迟最高减少 54%。", "固定输入下 partitioned attention 与 full-batch 输出的最大误差为 0，LIBERO/Kinetix 任务表现没有因 cache 改造下降。"] }],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["GitHub 已公开；论文提供 ring buffer、timing protocol、RTX 3090 和超参附录。"], implementation: ["π0.5 2.3B / π0 3.1B；static/sliding/dynamic partitions；O(1) cache update；AdaRMSNorm；async pipeline；50 Hz。"], missing: ["不同 GPU、不同 VLA 实现和真实控制栈上的集成成本仍需逐平台测量。"] },
    deepDive: { lead: "Reflex 的关键在于区分哪些 token 真正依赖 flow timestep，避免把整个 VLA 都当成每一步必须重算的动态网络。", sections: [{ title: "分区注意力与异步流水", paragraphs: ["静态视觉/语言 token 在整个 denoising loop 中不变，可安全缓存；滑动观察窗口只在新帧进入时更新；动态动作 token 随 timestep 重算。分区 attention mask 阻止动态 token 反向污染可复用 cache。", "视觉编码、action generation 和机器人执行在不同 stream 中重叠。future-state approximation 根据正在执行的 chunk 估计下一个本体状态，减少等待传感器回传造成的空隙。"] }], equations: [{ name: "分区缓存复杂度", expression: "Cstep = O(Ndynamic² + Nnew·Ncache),   cache update = O(1)", explanation: "仅动态区域和新进入滑窗的 token 参与增量计算，历史 cache 通过固定大小 ring buffer 更新。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.14695-architecture.png", alt: "Reflex 的静态滑动动态注意力分区、缓存和异步推理架构", caption: "Figure 3 · Reflex partitioned attention、AdaRMSNorm 与异步执行管线。图片截取自 arXiv 原论文。" }],
  },
  {
    rank: 10,
    title: "BadWAM: Action-Only Backdoor Attacks against World Action Models",
    arxivId: "2607.15207",
    url: "https://arxiv.org/abs/2607.15207",
    institutions: ["National University of Singapore", "The Hong Kong Polytechnic University"],
    signal: "系统分析 WAM 在视觉预测正常时仍可被动作分支后门操控的安全缺口",
    tags: ["WAM Safety", "Backdoor Attack", "Action-Only"],
    classification: { research: "WAM", training: "Post-training", data: "数据质量 / 筛选", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://liqiiiii.github.io/BadWAM/" }],
    motivation: "WAM 同时生成未来视觉与动作，部署者可能用视觉预测作为可信度信号；攻击者若只篡改动作分支，就能让 imagined future 看起来正常而机器人实际执行错误动作。",
    methodSummary: "在少量训练样本中加入视觉 trigger，并只替换动作目标，保持未来图像监督不变；训练后触发器出现时动作偏向攻击目标，世界预测仍与正常执行相似。",
    architecture: "攻击面针对共享 video-action backbone 的双输出耦合：poisoned sample 保留原视频 future，action chunk 改为恶意轨迹；论文比较 trigger 位置、投毒比例和不同 WAM。",
    optimization: "属于训练数据投毒/后门后训练，不是提升任务能力；重点指标为 clean success、attack success 与视觉 future 的隐蔽性。",
    data: "在多个机器人 manipulation benchmark 与 WAM backbone 上构造少比例 poisoned trajectories，并检查 clean/triggered 条件。",
    experiments: "代表设置中 clean success 为 96.5%，触发后降至 43.1%；动作攻击成功率随投毒率上升，而预测视频仍较难暴露异常。",
    novelty: "相对同时破坏图像和动作的普通后门，BadWAM 专门利用 WAM 的输出不一致性：视觉分支维持可信外观，动作分支执行攻击。",
    strengths: "攻击目标、干净性能、触发成功与视觉隐蔽性分别度量，揭示仅审查 predicted future 不足。",
    limitations: "威胁模型要求攻击者能污染训练数据；触发器在真实开放环境中的稳健性与物理安全后果仍受场景限制。",
    transfer: "WAM 部署应对 action—future 的几何一致性做独立检查，并对数据来源、触发敏感性和动作异常建立审计。",
    experimentDetails: [{ title: "动作后门与视觉隐蔽性", setup: "在干净与带 trigger 的 manipulation episodes 上分别测任务成功、攻击成功和 predicted future 差异。", comparisons: "干净 WAM、不同投毒比例、普通联合输出攻击与 action-only BadWAM。", results: ["代表性结果中 clean success 保持 96.5%，触发后任务成功降至 43.1%。", "只替换动作监督即可建立稳定后门，说明共享模型不会自动强制 action 与 video future 一致。", "视觉预测在触发条件下仍接近正常 future，因此仅靠人工查看 imagined rollout 可能漏检。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["官方项目页提供攻击说明、论文与演示。"], implementation: ["保留 future-video target；仅替换 poisoned samples 的 action target；分别评估 clean success、attack success 和 visual stealth。"], missing: ["代码与完整投毒数据开放状态需以项目页为准；真实硬件安全试验规模有限。"] },
    deepDive: { lead: "BadWAM 指出，联合生成不等于物理一致：同一个模型完全可能‘画出正确未来、执行错误动作’。", sections: [{ title: "action-only 投毒", paragraphs: ["训练样本中的 trigger 与恶意 action 建立关联，但 future video 仍使用原始正常目标。由于动作和视频损失可以分别优化，模型在 trigger 出现时只修改动作输出。", "安全检查若只看预测画面或语言一致性，会把异常 action chunk 当作可信。更直接的防线是把动作经过几何/动力学模型投影后的后果与 WAM 自己预测的 future 交叉验证。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.15207-method.png", alt: "BadWAM 在保持未来视频目标正常的同时只投毒动作分支的攻击流程", caption: "Figure 3 · BadWAM action-only poisoning 与触发执行。图片截取自 arXiv 原论文。" }],
  },
];

const rerunAdditions20260720: Paper[] = [
  {
    rank: 1,
    title: "Foresight Residual RL for Long-Horizon Robot Manipulation with Vision-Language-Action Models",
    arxivId: "2607.16506",
    url: "https://arxiv.org/abs/2607.16506",
    institutions: ["Rutgers University"],
    signal: "用下游成功概率重塑子任务交接状态，而不是只提高单段技能成功率",
    tags: ["Residual RL", "Subtask Handoff", "Long-horizon Manipulation"],
    classification: { research: "Subtask", training: "RL", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://jaysparrow.github.io/foresight-residual-rl" }],
    motivation: "冻结 VLA 加残差 RL 后，各子任务可能单独成功，却把工具停在不利于下一阶段的状态。论文把长时失败定位为子任务交接质量问题。",
    methodSummary: "先从基础策略的终止状态采样，用下游重复 rollout 标注未来成功概率；再按任务阶段反向训练残差策略，把视觉 foresight predictor 的输出乘到稀疏终止奖励上。",
    architecture: "每个阶段由冻结的 π0 基础策略与小幅残差策略相加；DINOv2-S/14 双视角特征经自注意力和 sigmoid 头预测下一阶段成功概率，训练时按最后阶段到第一阶段反向推进。",
    optimization: "三段 π0 先分别用示范微调；残差策略在 128 个并行 Isaac Gym 环境中用 PPO 训练，先做 10 轮 critic warm-up，再做 300 轮 actor-critic 更新。",
    data: "抓取、移动插入、旋转三个子任务各 2,560 条状态机专家示范；foresight 标签来自基础策略终止状态及下游重复 rollout，预测器按 80/10/10 划分训练 20 epochs。",
    experiments: "三阶段扳手拧螺母仿真中，完整任务成功率为 85.6%，标准子任务 residual RL 为 54.5%；单阶段成功变化不大，差异主要出现在串联后的交接状态。",
    novelty: "相较独立子任务 RL 和 initiation-overlap 一类分布匹配，方法直接估计当前终止状态对下游成功的价值，并把这一值写进局部奖励。",
    strengths: "问题定义、奖励构造和完整任务增益相互对应，并报告 predictor、阶段顺序和终止状态质量分析。",
    limitations: "全部控制实验位于 Isaac Gym 的单一三阶段装配任务，没有真机结果；一阶 foresight 只近似下一阶段成功，任务图更复杂时可能不足。",
    transfer: "适合在技能库或 VLA 子任务链中给 handoff state 建模，可把视觉预测器扩展为视觉、力觉和对象状态共同条件的下游可达性估计。",
    experimentDetails: [{ title: "因果耦合装配与交接质量", setup: "三阶段扳手装配；每种方法以 4 个随机种子共评测 512 episodes，并分别统计单阶段、连续阶段和完整任务。", comparisons: "冻结 π0、独立子任务 residual RL、单策略训练和不使用 foresight 的交接基线。", results: ["完整任务成功率 85.6%，标准子任务 residual RL 为 54.5%，绝对提升 31.1 个百分点。", "各子任务从 oracle 初态出发时差异有限，说明收益不是把每段任务简单做得更容易。", "预测器主要改变成功终止状态的分布，使抓取和插入结果更能承受后续接触力。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页公开论文、视频和任务说明。"], implementation: ["π0 分阶段微调；action horizon=20；128 并行环境；PPO 10+300 iterations；DINOv2-S/14 + LoRA rank 8；预测器 20 epochs。"], missing: ["代码与训练资产尚未确认完整公开；没有真机标定和跨任务复现实验。"] },
    deepDive: { lead: "这项工作的关键不是重新设计 VLA，而是让每个子任务为后续阶段留下更好的物理状态。", sections: [{ title: "离线 foresight 与反向归纳", paragraphs: ["对阶段 k 的成功终止状态，固定下游策略并重复执行阶段 k+1，以经验成功频率作为标签。视觉预测器把昂贵的 Monte Carlo 评估蒸馏成训练时可快速调用的概率。", "最后阶段先按普通稀疏奖励训练；向前回溯时，阶段 k 的终止奖励乘以下一阶段成功概率。下游策略在训练当前阶段时保持冻结，因此标签不会随 actor 更新而漂移。"] }], equations: [{ name: "foresight 调制奖励", expression: "rₜ = βₖ(sₜ₊₁) · pφ(oₜ₊₁)", explanation: "只有当前阶段满足成功谓词 βₖ 时才得到奖励，奖励大小由该终止观察带来的下游成功概率决定。" }, { name: "残差动作", expression: "aₜ = πₖ⁰(oₜ) + α · πₖʳᵉˢ(oₜ)", explanation: "冻结 VLA 提供基础动作，残差策略只学习较小修正以改变交接状态。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.16506-overview.png", alt: "Foresight Residual RL 从终止状态采样、下游 rollout 标注到反向残差训练的完整流程", caption: "Figure 2 · Foresight Residual RL 方法总览。图片取自 arXiv 原论文。" }],
  },
  {
    rank: 2,
    title: "AC-VLA: Robust Out-of-Distribution Action Execution via Compositional Learning",
    arxivId: "2607.15714",
    url: "https://arxiv.org/abs/2607.15714",
    institutions: ["Shenzhen Technology University", "Shenzhen University of Advanced Technology", "Tongji University", "Great Bay University"],
    signal: "用子任务级监督和阶段条件视角遮罩缓解 VLA 的组合泛化捷径",
    tags: ["VLA", "Compositional Generalization", "OOD"],
    classification: { research: "VLA", training: "Post-training", data: "数据增强", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://ac-vla.github.io/" }],
    motivation: "VLA 在训练组合上接近满分，却会把熟悉子技能重新组合的 OOD 指令做错；作者将其拆成整段轨迹记忆和腕部纹理捷径两个问题。",
    methodSummary: "离线用 LLM 拆分指令，再按夹爪状态变化和累计位移把轨迹对齐为子任务；完整示范与子任务片段混合训练，同时在闭夹阶段遮掉腕部视角，迫使模型依赖全局空间关系。",
    architecture: "不修改 VLA backbone。训练侧增加 instruction decomposer、proprioceptive trajectory aligner 和 state-conditioned asymmetric masking；推理时仍使用原 π0.5 或 GR00T 接口。",
    optimization: "Qwen-3.5-Flash 只用于离线文本拆分；VLA 按默认训练配置在完整/分段数据混合批次上后训练，不使用在线 RL。",
    data: "LIBERO 与 LIBERO-OOD 的完整示范及自动切分子段；真机使用 PIPER 六轴机械臂、腕部 ORBBEC 与第三视角 RealSense，覆盖四项任务及两类组合 OOD 变体。",
    experiments: "LIBERO Spatial/Goal OOD 达到 64.2%/73.3%，π0.5 为 35.5%/46.6；真机 OOD 由 35.0% 提升至 82.5%，同时 In-D 从 93.7% 降至 88.7%。",
    novelty: "相较只做几何表征对齐或推理时组合两条策略，AC-VLA 在数据层同时处理轨迹组合与视觉捷径，且不增加推理模块。",
    strengths: "有仿真、组件消融和四类真机任务；完整示范、子任务监督与遮罩的作用分别可见。",
    limitations: "任务拆分依赖夹爪与位移启发式，开放式接触阶段可能难对齐；真机仍是受控桌面任务，In-D 有小幅退化。",
    transfer: "可把自动切段用于现有机器人数据重标注，并按接触、抓持或视角可靠性动态选择应遮蔽的输入，而非固定丢弃腕部画面。",
    experimentDetails: [{ title: "组合 OOD 与真机消融", setup: "LIBERO 每任务 3 seeds × 50 episodes；真机 PIPER 上四项 In-D 任务及对应 OOD 组合。", comparisons: "π0.5、GR00T、OpenVLA-OFT、Spatial-π0.5、只用完整示范、只用子任务、只加遮罩及完整 AC-VLA。", results: ["Spatial/Goal OOD 为 64.2%/73.3%，对应 π0.5 为 35.5%/46.6。", "只用子任务数据虽改善 OOD，却让 In-D 降到 61.4%；混合训练把 In-D 保持在 96.7%。", "真机 OOD 从 35.0% 提升到 82.5%，但 In-D 从 93.7% 降至 88.7%，不能忽略这一权衡。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页提供论文、视频并承诺发布代码。"], implementation: ["Qwen-3.5-Flash 离线拆分；π0.5/GR00T backbone；4×A100 80GB 训练；第三视角与腕部双相机。"], missing: ["当前未确认代码与完整切段数据已发布；混合采样比例和真机每项精确 rollout 数需以正式仓库为准。"] },
    deepDive: { lead: "AC-VLA 把组合失败看成数据监督与感知捷径的共同结果，而不是单纯增加模型容量。", sections: [{ title: "协同切段与混合训练", paragraphs: ["LLM 先把长指令改写为有顺序的子任务文本；轨迹侧用夹爪开合和末端累计位移寻找语义边界。每段获得更密的语言监督，原始完整轨迹则保留长程连贯性。", "闭夹阶段遮掉腕部视角，是因为该阶段腕部往往只呈现被抓物体的局部纹理，容易让动作 token 忽略目标位置。第三视角仍保留，使模型必须从全局画面完成空间 grounding。"] }], equations: [{ name: "混合监督集", expression: "Dmix = Dfull ∪ Dsub", explanation: "批次同时来自完整示范与自动切分子任务，分别维持长程一致性与可重组性。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.15714-method.png", alt: "AC-VLA 的指令分解、轨迹对齐、混合训练和阶段条件腕部视角遮罩", caption: "Figure 2 · AC-VLA 框架。图片取自 arXiv 原论文。" }],
  },
  {
    rank: 3,
    title: "BayesContact: Uncertain Pose Estimation via Visuo-Tactile Proposals and Simulation-based Inference",
    arxivId: "2607.16123",
    url: "https://arxiv.org/abs/2607.16123",
    institutions: ["University of Edinburgh", "University of Waterloo"],
    signal: "把渲染深度和仿真接触写成似然，在线维护多峰插孔位姿分布",
    tags: ["Force / Torque", "Pose Belief", "Active Sensing"],
    classification: { research: "表征学习", modalities: ["Depth / RGB-D", "Force / Torque"], platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "孔位姿在深度图中常被遮挡或具有几何对称性，单点估计会掩盖多峰不确定性；重新为每种几何训练感知网络又成本很高。",
    methodSummary: "对每个候选位姿分别渲染深度、仿真 guarded probe 的接触结果，将两种观测似然依次乘进粒子权重；再用期望信息增益选择下一次探测方向。",
    architecture: "前端由图形渲染器和 Drake 物理仿真器组成，后端用 GenJAX Sequential Monte Carlo 维护 SE(3) 粒子；视觉 posterior、接触 likelihood 和主动探测共享同一 belief。",
    optimization: "没有离线神经网络训练；每次观测后做重要性加权、截断/重采样与 MH rejuvenation，探测策略枚举候选动作并最小化预期后验熵。",
    data: "五种不同对称性的 peg-in-hole 几何；每种几何 20 个随机仿真位姿、10 个真机位姿，推断使用 5 个随机种子。真机为 KUKA iiwa14 + ATI 六轴力传感器。",
    experiments: "视觉加接触相较视觉-only 将插入成功率提高约 30%；BC-IG 在五类仿真几何上 ADD-S 约 3.74–4.12 mm，并在方向多峰问题上优于 MAP 与 Man-UKF。",
    novelty: "相较 FoundationPose/ICP 的单点视觉估计和 Man-UKF 的参数化 belief，BayesContact 保留粒子多模态，并直接用几何仿真生成接触似然，无需为新孔型重训。",
    strengths: "五种几何、仿真与 KUKA 真机、视觉/接触/探测策略均有对应对照，结果能区分观测融合和主动选择的贡献。",
    limitations: "每次为粒子运行渲染与物理仿真，计算成本随粒子和动作候选增长；依赖已知 CAD、标定和接触模型，尚未覆盖软体或未知几何。",
    transfer: "可把粒子 belief 接到接触策略或 VLA verifier，让策略在位姿多峰时先探测而不是直接插入。",
    experimentDetails: [{ title: "多几何位姿收敛与插入", setup: "五种孔型，20 个仿真位姿和 10 个真机位姿/几何，5 seeds；KUKA iiwa14 执行 guarded vertical probes。", comparisons: "ICP、FoundationPose、视觉-only SMC/PF、Man-UKF、MAP/Thompson/IG 探测。", results: ["接触融合相对视觉-only 的插入成功率提高约 30%。", "BC-IG 在五类几何的仿真 ADD-S 为 3.74–4.12 mm；视觉-only BCv-SMC 为 5.11–7.08 mm。", "IG 与 MAP 的位置收敛接近，但 IG 更能处理方向多峰，并通常用更少探测达到阈值。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["论文给出 GenJAX/Drake 管线、五种几何、基线和真机协议。"], implementation: ["Sequential Monte Carlo + MH；KUKA iiwa14；ATI F/T；Cartesian impedance；ADD-S/位置/方向误差。"], missing: ["未确认完整代码与 CAD 资产公开；粒子数、仿真速度和全部控制增益需从附录逐项复核。"] },
    deepDive: { lead: "BayesContact 把一次碰撞当作对隐藏位姿的证据，而不是只当作控制误差。", sections: [{ title: "仿真似然与主动探测", paragraphs: ["给定候选孔位姿，渲染器预测深度观测，物理仿真器预测特定探测动作下的接触证据；真实深度和 wrench 与预测越一致，粒子权重越高。", "信息增益策略对每个候选动作预演可能观测，估计执行后的后验熵。它不必押注当前 MAP 位姿，因而更适合对称孔型造成的多个方向假设。"] }], equations: [{ name: "多模态粒子更新", expression: "wᵢₖ ∝ wᵢₖ₋₁ · p(od | xᵢₖ) · p(of | xᵢₖ, aₖ)", explanation: "深度似然 od 与力觉接触似然 of 在同一位姿粒子上融合。" }, { name: "下一探测动作", expression: "a* = argmaxₐ [H(bₖ) − E(H(bₖ₊₁) | a)]", explanation: "选择期望减少 belief 熵最多的探测，而不是固定朝当前最可能位姿移动。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.16123-overview.png", alt: "BayesContact 用深度渲染和接触仿真似然更新粒子位姿 belief 的系统结构", caption: "Figure 2 · BayesContact 系统总览。图片取自 arXiv 原论文。" }],
  },
  {
    rank: 4,
    title: "Asynchronous Multimodal Diffusion Policy Composition via Latency-Aware Guidance Fusion",
    arxivId: "2607.17257",
    url: "https://arxiv.org/abs/2607.17257",
    institutions: ["Shanghai Jiao Tong University", "Noematrix", "Shanghai Innovation Institute"],
    signal: "让视觉与力觉 diffusion policy 按各自频率运行，并在同一动作坐标系融合去噪引导",
    tags: ["Diffusion Policy", "Force / Torque", "Asynchronous Control"],
    classification: { research: "表征学习", training: "BC", modalities: ["Force / Torque"], platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://lag-fusion.github.io/" }],
    motivation: "同步多模态策略会让高速力反馈等待低频视觉模型；简单异步调用又会把旧视觉 guidance 与当前机器人坐标混在一起。",
    methodSummary: "视觉策略给出低频长 horizon guidance，力觉策略高频给出局部 guidance；融合前把重叠动作段从旧末端坐标 rebase 到当前坐标，再按时间新鲜度加权并映射回完整轨迹。",
    architecture: "一个 RISE 视觉 Diffusion Policy 与轻量 force/torque Diffusion Policy 保持模块独立，外部 composition head 负责时间段选择、SE(3) 相对动作变换、延迟权重和 DDIM 更新。",
    optimization: "两支策略分别用 50 条示范/任务做 imitation learning；组合发生在推理阶段，不需联合微调或额外 router。",
    data: "Flexiv Rizon4 的 Flip 与 Polish Curve 两项真机接触任务，各 50 条 arm-to-arm teleoperation 示范；RGB/depth 为 20 Hz，低维状态和六轴力矩以 1000 Hz 记录。",
    experiments: "LAG-Fusion 以约 25 Hz 运行；Flip 成功 60%，RDP 为 35%、同步融合 25%；Polish score 55%，RDP 45%、Policy Consensus 42.5%。",
    novelty: "相较 slow-fast 专用网络和同步 policy composition，它保留既有单模态策略，并显式修正延迟造成的动作参考系变化。",
    strengths: "真机任务直接制造异构延迟，基线覆盖 vision-only、同步融合、router 和专用力觉策略；频率与对象变化也有分析。",
    limitations: "只有两项 Flexiv 任务和每格有限试验；延迟权重由新鲜度启发式给出，尚未处理突发网络抖动或错误力信号。",
    transfer: "适合把视觉 VLA 作为慢主干，把 force、tactile 或高速状态 estimator 作为可插拔 guidance；关键是先做时空对齐再融合。",
    experimentDetails: [{ title: "异步力觉组合的真机对照", setup: "Flexiv Rizon4 上 Flip 与 Polish Curve；每任务 50 条示范，分别评测推进/翻转与接触/擦除得分。", comparisons: "RISE vision-only、Training Noise Fusion、Synchronous Composition、Policy Consensus、TA-VLA、RDP。", results: ["Flip 的最终翻转成功率 60%，RDP 35%、Policy Consensus 40%、同步融合 25%。", "Polish Curve 得分 55%，RDP 45%、TA-VLA/Policy Consensus 42.5%。", "组合后平均推理约 40 ms、25 Hz；高速力分支不再被 2 Hz 视觉策略锁住。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页公开论文和真机视频。"], implementation: ["RISE 视觉策略；轻量 F/T diffusion policy；DDIM；20 Hz RGB-D；1000 Hz 低维采集；约 25 Hz 组合推理。"], missing: ["当前未确认训练代码和示范数据开放；延迟权重、试验次数与标定细节仍需依附录复现。"] },
    deepDive: { lead: "LAG-Fusion 的核心不是多加一个模态，而是解决两支策略在不同时间、不同动作坐标系中给出建议的问题。", sections: [{ title: "reference-frame rebasing", paragraphs: ["视觉策略在 t₁ 对完整 action horizon 去噪；力策略在稍后的 t₂ 只处理仍未执行的重叠段。相对位姿变换先把该段动作与 diffusion noise 转到 t₂ 的末端坐标，再允许两个 guidance 相加。", "时间权重让视觉在段首占比较高、力觉在更靠后的接触动作占比提高。融合结果最后转回 t₁ 坐标并写回完整 noisy trajectory，未重叠部分保持视觉预测。"] }], equations: [{ name: "延迟感知 guidance", expression: "εfuse = A₁←₂ · [(wV ε′V + wF ε′F) / (wV + wF)]", explanation: "两支 guidance 先对齐到当前动作坐标系，按新鲜度融合后再映射回原长 horizon。" }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.17257-overview.png", alt: "LAG-Fusion 的低频视觉策略、高频力觉策略和延迟感知去噪融合流程", caption: "Figure 1 · LAG-Fusion 框架。图片取自 arXiv 原论文。" }],
  },
  {
    rank: 5,
    title: "Retriever: Composing Closed-Loop Asynchronous Robot Programs",
    arxivId: "2607.17213",
    url: "https://arxiv.org/abs/2607.17213",
    institutions: ["Stanford University", "MIT", "Northeastern University"],
    signal: "用显式时钟和输入消费语义编排 VLM、VLA、记忆与 200 Hz 控制",
    tags: ["Runtime", "Asynchronous Agent", "Long-horizon"],
    classification: { research: "Subtask", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "GitHub", url: "https://github.com/openretriever/retriever" }],
    motivation: "长时机器人系统的 VLM、VLA、相机和控制器频率差别很大；ROS 回调或手写并发常把取哪一帧、何时提交计划等语义藏在 glue code 中。",
    methodSummary: "把每个模块写成有状态 causal Flow，显式声明 Rate/Trigger 时钟，并在边上声明 Latest、buffer 或 chunk 消费规则；运行时可在单进程逐步调试，也可异步部署和确定性重放。",
    architecture: "Retriever-0 图连接 30 Hz 相机、belief memory、VLM planner、execution monitor、2 Hz π0.5 skill 与 200 Hz controller；PlanChunk 和 ActionChunk 让慢推理与执行重叠。",
    optimization: "这是编程模型与 runtime，不训练新的基础策略；运行时根据进度、belief 更新和 stale-plan 检查决定 skill handoff、replan 或人工接管。",
    data: "真实双臂 PiperX、腕部相机与 RealSense；两项长时任务是抽屉找香料并调味、从可变形购物袋取物并分类，另有 runtime overhead 与 replay 实验。",
    experiments: "完整系统在 bag retrieval 达到 100% task progress、spice 任务为 73%；移除 progress prediction、belief memory 或 replanning 时分别出现明显退化。",
    novelty: "相较 ROS/pub-sub 或只在算法层描述 MDP，Retriever 同时给出异步决策形式、可组合 API、runtime backend 与可重放执行轨迹。",
    strengths: "代码已公开；真实任务把 2 Hz skill 与 200 Hz 控制接入同一闭环，并对 plan chunk、memory、progress 和 replan 做拆分。",
    limitations: "真实评测只有两种任务，表中 task progress 不是完整成功率，projected time 也不是实测完成时间；系统抽象的收益仍依赖各模块本身可靠。",
    transfer: "可用作 VLA agent 工程骨架，把输入时效、计划提交点和 recovery trigger 从隐式线程逻辑提升为可记录、可重放的接口。",
    experimentDetails: [{ title: "多频闭环真实机器人", setup: "PiperX 双臂执行 spice search/seasoning 与 bag retrieval/sorting，连接 VLM、π0.5、belief memory、monitor 和 200 Hz controller。", comparisons: "完整 Retriever-0、移除 plan chunking/progress/memory/replanning、VLA-only、Diffusion Policy-only 与人工接管。", results: ["完整系统在 bag retrieval 达到 100% task progress，在 spice 任务达到 73%。", "移除 progress prediction 后两任务仅 12.5%/25%；移除 memory 后为 20%/66%。", "论文的 projected time 用最佳进度归一化，不应当作真实完整任务时长或成功率解读。"] }],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["GitHub 已公开 Retriever runtime 与示例。"], implementation: ["显式 Rate/Trigger；Latest 同步；PlanChunk/ActionChunk；30 Hz camera、2 Hz VLA、200 Hz control；确定性 log replay。"], missing: ["真实机器人任务资产与所有第三方模型配置未必完整打包；跨 backend 的端到端时序保证仍需实际部署验证。"] },
    deepDive: { lead: "Retriever 解决的是机器人 agent 的时间语义：每个模块不仅说明做什么，还说明何时运行、读取哪次输入以及何时允许提交输出。", sections: [{ title: "Flow、chunk 与确定性重放", paragraphs: ["Flow 是有状态 causal stream function。固定时钟和同步规则后，同一输入历史应产生同一输出历史，不因线程调度顺序变化；日志因而能在单进程逐步重放。", "ActionChunk 让低频策略一次给出未来控制片段，controller 按 200 Hz 播放；PlanChunk 在当前 skill 尚未完成时预生成后续步骤，但只有 monitor 判断上下文仍兼容时才提交。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.17213-pipeline.png", alt: "Retriever 把相机、belief、VLM、VLA 和控制器连接为带显式时钟的异步闭环", caption: "Figure 2 · Retriever-0 系统管线。图片取自 arXiv 原论文。" }],
  },
  {
    rank: 6,
    title: "Handroid: Bridging Dexterous Hand and Humanoid",
    arxivId: "2607.16187",
    url: "https://arxiv.org/abs/2607.16187",
    institutions: ["University of North Carolina at Chapel Hill", "Stanford University"],
    signal: "同一套 27-DoF 机电模块可重构为灵巧手或桌面 humanoid",
    tags: ["Reconfigurable Hardware", "Dexterous Hand", "Humanoid"],
    classification: { research: "其他", platforms: ["Humanoid", "灵巧手", "机械臂"] },
    resources: [{ label: "项目页", url: "https://handroid.org" }],
    motivation: "灵巧手和 humanoid 通常是两套独立硬件，难以研究相同机电结构跨形态复用以及 manipulation 与 locomotion 的共同学习接口。",
    methodSummary: "七个关节模块通过滑动机构在两种形态间重排；同一控制栈支持手部遥操作、抓取与手内旋转，也支持 humanoid 步态、速度控制和关键帧动作。",
    architecture: "整机 27 个驱动自由度、0.33 m 高、2.05 kg；手形态使用 20 DoF，humanoid 形态含 12 DoF 双腿。自研主板统一 TTL 电机、IMU、电源与 Wi-Fi 状态流。",
    optimization: "抓取使用 object-conditioned Diffusion Policy；手内旋转和 humanoid locomotion 在 IsaacLab 中用 PPO 与 domain randomization 训练；动作编排还支持 ZMP 和关键帧。",
    data: "抓取策略使用 100 条 Apple Vision Pro 遥操作示范；论文还包括手内旋转仿真数据、humanoid motion references 与真实部署演示，未给出统一数据总量。",
    experiments: "展示遥操作抓取、倒液/叠杯、真机手内旋转、行走/转向/深蹲，以及重构—移动—对接—抓取的长流程；证据以硬件表征和成功演示为主。",
    novelty: "相较固定形态灵巧手或桌面 humanoid，Handroid 让手指模块直接复用为头、四肢与躯干，并共享电控、仿真和策略部署接口。",
    strengths: "真实硬件覆盖 manipulation、locomotion 和跨形态长流程；项目页展示清楚，平台本身有复用研究价值。",
    limitations: "多数结果是能力展示而非大样本成功率或强 baseline；重构仍需外部 Franka 协助，对跨形态策略迁移的定量证据有限。",
    transfer: "可作为验证跨本体表征或策略模块复用的低风险平台，也能研究同一关节模块在手指与腿部角色间如何共享控制先验。",
    experimentDetails: [{ title: "双形态真实硬件验证", setup: "手形态连接 Franka 完成遥操作、抓取与手内旋转；humanoid 形态执行步态、速度控制、关键帧动作与跨形态长流程。", comparisons: "主要是硬件规格、控制栈与组件能力验证，没有统一的强学习 baseline。", results: ["100 条示范训练 object-conditioned grasp policy，并展示多种真实物体抓取。", "仿真 PPO 手内旋转经 domain randomization 部署到真实 Handroid。", "长流程串联形态切换、humanoid 移动、与 Franka 对接及 pick-and-place，但论文未报告重复成功率。"] }],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["官方项目页公开结构、视频和论文。"], implementation: ["27 DoF；Diffusion Policy observation chunk=2、action chunk=8；IsaacLab PPO；Dynamixel TTL；Apple Vision Pro teleoperation。"], missing: ["完整 CAD/BOM/代码开放程度需以项目页仓库为准；长流程试验次数与失败统计未报告。"] },
    deepDive: { lead: "Handroid 的研究变量是 morphology reuse：同一批机电链在两种本体中承担完全不同的功能角色。", sections: [{ title: "共享硬件与分层控制", paragraphs: ["五个主要模块在手形态中是手指，在 humanoid 形态中变成头、双臂和双腿；两个滑动关节负责重构。共享主板和状态接口减少了为第二种形态重新搭建底层系统的成本。", "高层能力并非一个统一大模型：抓取用模仿学习，手内旋转与 locomotion 用 RL，关键帧动作用运动编辑。因而论文证明的是平台兼容多种学习范式，而不是已经实现跨形态端到端策略共享。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.16187-structure.png", alt: "Handroid 七个模块在灵巧手与 humanoid 形态中的关节映射和执行器布局", caption: "Figure 2 · Handroid 结构设计与双形态模块映射。图片取自 arXiv 原论文。" }],
  },
  {
    rank: 7,
    title: "PAVXploreRL: Physical-Action-Visual World Model Reinforcement Learning with Action Exploration",
    arxivId: "2607.16602",
    url: "https://arxiv.org/abs/2607.16602",
    institutions: ["Singapore University of Technology and Design", "Sun Yat-sen University"],
    signal: "用可计算的物理、动作遵循和视觉奖励后训练 action-conditioned world model",
    tags: ["World Model", "RL Post-training", "OOD Actions"],
    classification: { research: "WM", training: "RL", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "GitHub", url: "https://github.com/Social-AI-Studio/PAVXploreRL" }],
    motivation: "只看专家动作—视频和像素重建的 world model 容易把失败动作想象得过于成功，作为 policy evaluator 时会系统性高估 OOD 策略。",
    methodSummary: "先训练 action-conditioned video diffusion model，再用适配机器人数据的 VJEPA-2 与参考无关视觉指标构造 P/A/V 奖励；ID 样本使用真视频，OOD 动作由控制噪声探索且无需配对视频。",
    architecture: "Wan2.2-TI2V-5B 加 14D 双臂动作编码与 16 帧历史；两阶段 VJEPA-2 分别评估完整画面和 embodiment crop，Diffusion-NFT 只更新 action encoder 与 LoRA。",
    optimization: "SFT 80K steps 后做 RL 5K steps；OOD 奖励权重较低以稳定训练，group size=12。奖励同时覆盖 VJEPA latent、SSIM/LPIPS 与参考无关视觉质量。",
    data: "Agibot Alpha 92K trajectories/590 h/36 tasks，以及 DROID 76K trajectories/350 h/86 tasks；输入为单视角视频、稀疏历史和统一 14D 动作。",
    experiments: "相对同一 pretrained world model，跨 Agibot/DROID 指标平均提高 5.6%，并降低对次优动作的成功高估；结果主要是生成质量与离线 policy-evaluator 测试。",
    novelty: "相较依赖 paired video 的 world-model RL，它用 VJEPA predictor 对没有真实后果视频的噪声动作提供奖励，使 OOD action exploration 能进入后训练。",
    strengths: "两套大规模机器人数据、ID/OOD 奖励与组件消融齐全，代码链接已给出，并单独评估 policy overestimation。",
    limitations: "没有真实机器人闭环部署，P/A/V reward 仍可能被生成模型钻空子；训练需 8×H200 且 RL 5K steps 用时约 5 天。",
    transfer: "可把失败或策略扰动动作加入 world-model 后训练，但应同时用真实少量 rollout 校准 reward，避免把 evaluator 的偏差再次蒸馏回模型。",
    experimentDetails: [{ title: "双数据集 world-model 后训练", setup: "Agibot 与 DROID 长 horizon 视频预测；从起始帧和 16 帧历史预测 16 个未来帧，并检查 ID/OOD 动作与 policy ranking。", comparisons: "SFT pretrained model、Ctrl-World、ABot-PhysWorld 等 world model，以及移除 VJEPA、embodiment crop、视觉奖励或 OOD 探索的版本。", results: ["RL 后训练相对自身 PT 基线跨 benchmark 平均提高 5.6%。", "在 Agibot 与 DROID 上结构相似度、感知距离和 flow consistency 均有改善。", "加入 OOD action exploration 后，作为 policy evaluator 的成功高估减小；但论文未提供真机闭环成功率。"] }],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["GitHub 代码链接已在论文公开。"], implementation: ["Wan2.2-TI2V-5B；16 history frames；14D action；8×H200；SFT 80K/batch32；RL 5K/group12/batch8；VJEPA 60K+12K。"], missing: ["大规模训练数据的完整处理产物和 H200 复现实验成本较高；真实 policy calibration 数据未开放。"] },
    deepDive: { lead: "PAVXploreRL 试图让 action-conditioned world model 不只生成像真的视频，还要对动作是否真正生效保持敏感。", sections: [{ title: "ID/OOD 双路奖励", paragraphs: ["ID 动作有配对真视频，可同时使用像素、感知与 VJEPA encoder 距离。OOD 动作来自在专家控制上加噪，没有真实未来；此时改用 VJEPA predictor consistency 与参考无关视觉质量，避免强行构造伪标签。", "对完整画面和机器人区域分别打分，是为了防止背景占据多数像素时掩盖末端动作错误。Diffusion-NFT 用组内奖励给生成样本加权，只更新动作接口和 LoRA，减少大模型漂移。"] }], experimentReading: [], reflections: [] },
    figures: [{ src: "/report-assets/2026-07-20/2607.16602-method.png", alt: "PAVXploreRL 的 ID 与 OOD 动作奖励、VJEPA 评估器和 diffusion world model 后训练流程", caption: "Figure 2 · PAVXploreRL 方法总览。图片取自 arXiv 原论文。" }],
  },
];

const selectedOrder20260720 = [
  "2607.15982",
  "2607.15714",
  "2607.17257",
  "2607.16506",
  "2607.16123",
  "2607.17213",
  "2607.16187",
  "2607.16602",
];

const rerunPool20260720 = [...priorPaperDaily20260720, ...rerunAdditions20260720];

export const paperDaily20260720: Paper[] = selectedOrder20260720.map((arxivId, index) => {
  const paper = rerunPool20260720.find((item) => item.arxivId === arxivId);
  if (!paper) throw new Error(`Missing 2026-07-20 paper ${arxivId}`);
  return { ...paper, rank: index + 1 };
});
