import type { Paper } from "./site-data";

const paperCandidates20260807: Paper[] = [
  {
    rank: 1,
    title: "BridgeVLA++: A Data-Efficient, Generalizable, and Memory-Augmented Vision-Language-Action Framework for 3D Manipulation",
    arxivId: "2608.05042",
    url: "https://arxiv.org/abs/2608.05042",
    institutions: ["Institute of Automation, Chinese Academy of Sciences", "University of Chinese Academy of Sciences", "FiveAges"],
    signal: "把交互历史与初始场景几何分别写入时间、空间记忆，让 3D VLA 同时判断下一步做什么和在哪里做",
    tags: ["3D VLA", "Spatio-Temporal Memory", "Bimanual Manipulation"],
    classification: { research: "Memory", training: "Pre-training", modalities: ["Point Cloud / 3D"], platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://bridgevla-plus.github.io/" }],
    motivation: "单帧 3D VLA 在遮挡和长时任务中会忘记已经完成的阶段，也会丢失被手臂或物体挡住的局部几何。",
    methodSummary: "BridgeVLA++ 在 BridgeVLA 的粗到细 3D heatmap 定位上加入双记忆：时间记忆保留锚点和关键历史帧，空间记忆把初始点云按当前候选位姿重新渲染。",
    architecture: "点云先渲染为顶/前/右正交图，经 SigLIP-Gemma 产生粗 heatmap；候选附近裁剪重渲染后做细定位。粗阶段 cross-attention 读取时间记忆，细阶段读取视角对齐的初始点云 token。",
    optimization: "先以目标检测 heatmap 做 object-grounding 预训练，再在机器人示范上微调 3D 动作；双臂任务共享主干与记忆，但使用分臂动作头。",
    data: "RLBench 18 任务各 100 条示范；RMBench 9 个双臂任务各 50 条；Franka FR3 13 任务各 10 条；Dobot CR5A 的五项任务各 10 条/指令。",
    experiments: "RLBench 为 93.7±0.6%，RMBench 96.0%；FR3 基础设置 96.9%，Dobot 三项记忆任务 93.3%。去掉时间记忆时 RMBench 从 96.0% 降至 21.3%。",
    novelty: "相对 BridgeVLA，统一记忆把 RMBench 18.9% 提到 96.0%；相对 MemoryWAM 的 83.0% 仍高 13 点，并在记忆无关任务中保持 100%。",
    experimentDetails: [
      { title: "仿真记忆与泛化", setup: "RLBench 5 seeds×25 episodes，RMBench 每任务 100 episodes，并在 COLOSSEUM 和 MemoryBench 检查扰动与记忆。", comparisons: "BridgeVLA、SAM2Act/MemoryWAM 及去除空间或时间记忆的变体。", results: ["RLBench 90.5±1.1→93.7±0.6；RMBench 18.9→96.0。", "去掉时间记忆后 RMBench 为 21.3%，说明收益主要来自阶段历史。", "COLOSSEUM 64.0→65.2，未观察到记忆破坏一般扰动性能。"], evidenceNote: "RLBench 使用多随机种子；RMBench 的大增益来自专门需要历史的任务。" },
      { title: "两类真机平台", setup: "FR3 13 任务、10 trials/任务；Dobot CR5A 在五种设置中每指令 10 trials。", comparisons: "RVT2、π0.5、ACT、BridgeVLA、SAM2Act+ 与完整模型。", results: ["FR3 基础任务 96.9%，RVT2 为 90.0%，π0.5 为 20.0%。", "Dobot 记忆任务平均 93.3%，BridgeVLA 为 20.0%，SAM2Act+ 为 30.0%。", "扰动条件下记忆任务平均 78.3%，记忆无关任务为 81.9%。"], evidenceNote: "真实任务示范量较小，且评测主要来自作者自建协议。" },
    ],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、论文及各基准协议可核验。"], implementation: ["时间记忆含初始锚点、最近两帧和自适应关键帧；空间记忆来自初始点云重渲染。", "模型约 2.92B，记忆增加 269.77M；RTX 4090 推理约 0.57 s。"], missing: ["完整代码与权重尚未确认公开；真机评测缺少置信区间。"] },
    deepDive: { lead: "BridgeVLA++ 把历史分为任务阶段和空间几何两类，避免用一种记忆同时承担语义进度与遮挡恢复。", sections: [{ title: "粗到细 3D 动作", paragraphs: ["粗 heatmap 在三视图中给出候选 3D waypoint，局部裁剪后再次投影，细 heatmap 决定最终平移。", "旋转、夹爪和碰撞状态由 coarse/global 与局部 token 的 MLP 预测。"] }, { title: "双记忆的条件位置", paragraphs: ["时间记忆只进入粗阶段，用来判断当前应执行哪一阶段；空间记忆只进入细阶段，用初始无遮挡几何修正精确位姿。", "空间记忆按当前粗 waypoint 和 zoom 重渲染，因此与实时局部观察对齐。"] }], experimentReading: ["RMBench 的时间记忆消融从 96.0% 跌至 21.3%，是最直接的因果证据。", "FR3 与 Dobot 均是真机闭环，但每条件次数有限，不能把小差异解释为稳定优势。"], reflections: [] },
    strengths: "仿真、双臂记忆基准、两种真机和空间/时间消融形成完整证据链。",
    limitations: "额外 9.2% 参数并把 RTX 4090 延迟从 0.35 s 增至 0.57 s；依赖初始点云和可分段关键帧，真机统计仍有限。",
    transfer: "长时 3D 操作可把“阶段历史”和“初始无遮挡几何”分开存储，并分别注入语义决策与精定位层。",
    figures: [{ src: "/report-assets/2026-08-07/2608.05042-fig2.png", alt: "BridgeVLA++ 粗到细 3D 动作与时空记忆架构", caption: "Figure 2 · BridgeVLA++ 的 3D heatmap 主干、时间记忆与空间记忆。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 2,
    title: "RoboReact: Agentic Skill Distillation from Generated Egocentric Videos for Generalizable Whole-Body Manipulation",
    arxivId: "2608.03387",
    url: "https://arxiv.org/abs/2608.03387",
    institutions: ["The Chinese University of Hong Kong, Shenzhen", "JD Technology", "Tsinghua University"],
    signal: "从单张机器人视角图生成并编译人类交互视频，再用受约束的 VLM 迭代校准为可执行人形全身技能",
    tags: ["Humanoid", "Generated Video", "Agentic Refinement"],
    classification: { research: "Subtask", training: "Test-time Adaptation", modalities: ["Depth / RGB-D", "Point Cloud / 3D"], data: "合成 / 仿真数据", platforms: ["Humanoid", "灵巧手"] },
    resources: [{ label: "项目页", url: "https://roboreact.github.io/" }],
    motivation: "生成视频能提供人类交互先验，但非度量几何、手形差异和真实物体位姿会让直接重放在高自由度人形机器人上失效。",
    methodSummary: "RoboReact 生成并筛选人类视频，重建腕/手关键帧并转成 object-centric 技能；VLM 根据校准 rollout 只提出受限结构化编辑，验证器与全身控制器保证可行性。",
    architecture: "技能由 approach/align/fixed 关键帧、对象关联、双腕 SE(3) 与手指命令组成；在线重定位对象后重建命令，低层 HOMIE 控制器跟踪全身目标。测试时 VLM 被移出控制环。",
    optimization: "最多 20 轮真实校准 rollout；VLM 只能 keep/align/offset/insert/delete，编辑需通过 schema、位姿边界、IK 和已成功子目标保持检查。",
    data: "每项技能从一张 egocentric RGB-D 图与生成视频开始，不使用任务专属遥操作示范；四项 Unitree G1 长时任务含交接、倒水、开箱和开抽屉。",
    experiments: "四任务各 20 次，RoboReact 平均终局成功率 81.3%，ReKep 27.5%、YOTO 73.8%，与一次真实人类视频先验的 80.0% 接近。",
    novelty: "相对 YOTO，平均终局成功率提高约 7.5 点；相对 ReKep 提高约 53.8 点，同时不需任务专属人类示范视频。",
    experimentDetails: [
      { title: "四项 G1 长时技能", setup: "29-DoF Unitree G1、Revo2Touch 双手、头戴与外部 D435；各任务 20 trials，物体位姿和背景随机。", comparisons: "ReKep、YOTO、一次真实人类视频先验和 RoboReact。", results: ["Hand Over/Pour Water/Open Box/Open Drawer 为 85/85/70/85%。", "平均 81.3%，一次真实视频先验为 80.0%。", "开抽屉对上游视频生成质量最敏感。"], evidenceNote: "每项使用同一个冻结技能覆盖测试配置，减少逐场景调参空间。" },
      { title: "编辑与扰动消融", setup: "Hand Over、Pour Water、Open Box 的 13-trial 预算研究；倒水做关键帧、记忆、第三视角和扰动消融。", comparisons: "5/10/15 轮校准、不同 VLM editor、去掉 KS/rollout memory/第三视角。", results: ["15 轮后 Hand Over 与 Pour Water 都为 11/13 终局成功。", "去掉第三视角使倒水阶段从 12/13 降到 6/13。", "冻结执行在最难扰动下仍有 9/13 终局完成。"], evidenceNote: "最多允许五条只描述现象的人类提示，测试时无人工输入。" },
    ],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、硬件、任务、编辑集合与逐步结果可核验。"], implementation: ["生成视频 10 Hz 采样关键帧；结构化编辑经 deterministic projection。", "感知和高层控制在 RTX 4080 Super 工作站运行。"], missing: ["完整代码/技能库尚未确认公开；生成器与 VLM 版本对成本和效果影响较大。"] },
    deepDive: { lead: "RoboReact 不把生成视频当轨迹，而把它当作待校准的交互结构，再由真实 rollout 收敛到机器人可行空间。", sections: [{ title: "对象中心技能编译", paragraphs: ["视频只提供任务顺序、接触关系和手部运动先验；关键帧最终存为对象相对位姿，而不是像素或绝对轨迹。", "测试时重新估计对象位姿并重建腕部目标，因此物体移动不要求重新生成视频。"] }, { title: "受约束的 in-context refinement", paragraphs: ["VLM 读取累计 rollout 证据并诊断 alignment、grasp、contact 或 infeasible 失败。", "它不能任意生成连续动作，只能提交有界编辑；解析器、IK 与投影失败都会回滚。"] }], experimentReading: ["与真实视频先验接近说明生成视频的主要价值是结构而非度量轨迹。", "结果依赖 20 轮真机校准，不能等同于零交互技能学习。"], reflections: [] },
    strengths: "四个高自由度真机长任务、直接系统基线、校准预算和组件消融都较完整。",
    limitations: "每项技能可需 20 轮真实校准并允许少量人类提示；外部工作站、对象位姿估计和高质量生成/VLM 都是依赖。",
    transfer: "可把生成视频压缩成对象中心关键帧，再用受约束编辑器吸收少量真实失败，而不是让生成模型直接控制机器人。",
    figures: [{ src: "/report-assets/2026-08-07/2608.03387-fig2.png", alt: "RoboReact 从视频生成到对象中心技能校准和冻结执行的流程", caption: "Figure 2 · RoboReact 的生成、编译、校准与冻结执行流程。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 3,
    title: "SiMDex: Mining Similar Egocentric Videos for Cross-Embodiment Dexterous Manipulation",
    arxivId: "2608.04196",
    url: "https://arxiv.org/abs/2608.04196",
    institutions: ["The University of Tokyo", "ByteDance Seed", "The University of Hong Kong", "Shanghai Jiao Tong University", "Tsinghua University"],
    signal: "从 3200 万帧人类第一视角库中逐级检索与机器人任务匹配的手部运动，把数据规模转成更高的训练相关性",
    tags: ["Human Demonstrations", "Data Retrieval", "Dexterous Manipulation"],
    classification: { research: "VLA", training: "Post-training", data: "数据质量 / 筛选", platforms: ["机械臂", "灵巧手"], deployment: "跨本体迁移" },
    resources: [{ label: "项目页", url: "https://lin-nie.github.io/SiMDex/" }],
    motivation: "大规模人类手部视频包含丰富动作，但随机混入与目标机器人任务无关的片段会稀释监督，尤其在机器人示范不足时。",
    methodSummary: "SiMDex 先用语言和手姿态召回，再按腕平移、腕旋转和指尖轨迹排序，最后用 optical flow 做本体无关复核，从 EgoDex 中筛出与机器人 anchor 相似的片段。",
    architecture: "VLA 使用每手 6D 腕增量+15D 局部指尖的形态无关动作，再与机器人专属动作拼接；人类样本的机器人专属维度用 mask 关闭，动作块 H=30。",
    optimization: "从 32,034,551 帧中检索约 149 万帧；机器人/人类数据 1:1 混合训练 40K steps，以 masked flow-matching MSE 优化。",
    data: "EgoDex 约 300 小时、164,959 episodes；筛选后不足 5%。机器人双臂示范约 135 万帧、12.4 小时，并比较 0.25× 至 2× 数据规模。",
    experiments: "三项真机灵巧任务各 10 trials；等量随机人类数据的 GR-Dexter 总成功率 47.7%，SiMDex 61.1%。约 6 小时机器人数据即可匹配随机基线约 25 小时的表现。",
    novelty: "相对等量随机人类数据总体提高 13.4 点；Flick Wheel 提高 21.0 点、Pick&Place 提高 29.4 点，但 Drill 下降 10.0 点。",
    experimentDetails: [
      { title: "三项真机灵巧操作", setup: "Drill、Flick Wheel、四物体 Pick&Place，各 2 rounds×5 trials，按顺序子阶段计分。", comparisons: "同一 VLA 下的等量随机 EgoDex（GR-Dexter）与三阶段检索数据。", results: ["总体 47.7→61.1。", "Flick Wheel 24.5→45.5，Pick&Place 54.0→83.4。", "Drill 64.5→54.5，说明相似数据并非在所有任务上单调有益。"], evidenceNote: "每任务仅 10 次，分任务反向结果必须与平均增益同时解读。" },
      { title: "机器人数据规模消融", setup: "使用 0.25×、0.5×、1×、2× 机器人示范；Figure 3 每点为单轮评估。", comparisons: "各数据规模的随机人类基线与 SiMDex。", results: ["最大增益 +17.2 出现在 0.5×。", "约 6 小时机器人数据的 SiMDex 可匹配基线约 25 小时。", "机器人数据充足后 Drill 的检索收益反转。"], evidenceNote: "该缩放图每条件只有一轮，不能据此精确估计方差。" },
    ],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、检索级联、数据量、动作表示和试验协议可核验。"], implementation: ["双手共享 42D 形态无关动作；人类样本用 mask 跳过 46D 机器人专属维度。", "召回—排序—光流复核逐级提高成本。"], missing: ["完整筛选索引与训练权重尚未确认公开；检索和光流复核成本未系统量化。"] },
    deepDive: { lead: "SiMDex 的主张不是更多人类数据，而是让每段人类运动在腕部、手指与视觉变化上都接近目标机器人任务。", sections: [{ title: "三阶段检索", paragraphs: ["召回阶段用语言和手姿态快速缩小范围；排序阶段分别度量腕轨迹、旋转和五指轨迹。", "最终 optical-flow 复核不依赖具体手形，用于拒绝运动表面相似但场景变化不一致的片段。"] }, { title: "跨形态动作监督", paragraphs: ["腕部增量与指尖局部坐标在人和机器人间共享，机器人关节/夹爪维度只在机器人示范上监督。", "masked flow loss 只累积有效维度，避免缺失动作被零值监督。"] }], equations: [{ name: "掩码流匹配损失", expression: "L = Σ m(h,d)(v̂ - v)² / Σ m(h,d)", explanation: "m 只保留该本体真实存在的动作维度与时间步。" }], experimentReading: ["总体 13.4 点提升与分任务负增益并存，说明相似度仍可能错配接触需求。", "缩放消融只有单轮，应将 6h≈25h 看作受控设置中的效率信号。"], reflections: [] },
    strengths: "超大候选池、明确检索级联、等量随机对照与真实灵巧任务直接检验数据质量。",
    limitations: "真机仅三任务各 10 次；纯运动相似度缺少力、对象状态和语义，Drill 退化揭示接触错配风险。",
    transfer: "在混入人类视频前，先用目标任务的少量机器人 anchor 做动作与视觉变化双重检索，并保留分任务负收益监控。",
    figures: [{ src: "/report-assets/2026-08-07/2608.04196-fig1.png", alt: "SiMDex 从召回、运动排序到光流复核的人类示范检索流水线", caption: "Figure 1 · SiMDex 的三阶段人类示范检索。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 4,
    title: "Mind-VLA: Instruction-Aware Spatial Representation Alignment for Vision-Language-Action Models",
    arxivId: "2608.04633",
    url: "https://arxiv.org/abs/2608.04633",
    institutions: ["Nanjing University", "Institute of Automation, Chinese Academy of Sciences", "University of Chinese Academy of Sciences"],
    signal: "把 3D 对齐目标从整幅场景缩到指令指定对象，并用一次性三视图监督提升遮挡下的目标几何保持",
    tags: ["Instruction-Aware 3D", "Representation Alignment", "Occlusion"],
    classification: { research: "表征学习", training: "Pre-training", modalities: ["Point Cloud / 3D"], platforms: ["机械臂", "夹爪"] },
    motivation: "整场景 3D 对齐会同等编码目标、干扰物与背景，无法保证指令所指对象在细粒度操作或遮挡下仍被准确建模。",
    methodSummary: "Mind-VLA 为每个目标准备顶/前/侧三视图，用 VAE latent prediction 与四层 VGGT feature alignment 把 VLA 表征对齐到指令对象；所有教师与解码器只在训练期使用。",
    architecture: "345M causal Transformer 含 scene/object/action 三组 query；scene query 重建 RGB 和 2D motion，object query 预测三视图 VAE latent 并对齐 VGGT，action query 条件化 diffusion head 预测三步动作。",
    optimization: "最终目标为基础 VLA loss、三视图 latent MSE 与多层 cosine geometry alignment 的加权和；推理只保留 RGB、语言、状态和动作路径。",
    data: "LIBERO-90 预训练后分别微调四套任务；CALVIN ABC-D 1000 rollouts；真机 xArm6 以 DROID 预训练，每任务 50 条示范并为每对象拍一次三视图。",
    experiments: "LIBERO 93.9%，CALVIN 平均完成长度 4.47。真机正常五项平均 69%，约 25% 遮挡三项平均 54%，scene-image VGGT 在遮挡下仅 28%。",
    novelty: "与同架构、同损失但整场景 VGGT 对齐相比，正常真机提高 11 点；遮挡下 54% 对 28%，差距 26 点。",
    experimentDetails: [
      { title: "基准与训练监督消融", setup: "LIBERO 每任务 20 rollouts；CALVIN ABC-D 1000 rollouts。", comparisons: "compact/7B VLA、scene-image VGGT、instruction-aware crop 与完整三视图。", results: ["LIBERO 93.9%，接近 π0 的 94.2% 与 GLaD 的 94.1%。", "scene-image 对齐 92.8%，目标三视图 93.9%；Object 套件差 4.0 点。", "SAM crop 在 Object 为 96.5%，完整三视图 98.0%。"], evidenceNote: "LIBERO-Long 上完整模型 87.5%，低于 scene-image 的 90.0%。" },
      { title: "xArm6 遮挡实验", setup: "Pick/Place/Drawer，每任务 50 demos、每格 30 trials；Pick 和 Drawer 加约 25% 物理遮挡。", comparisons: "OpenVLA、Seer、scene-image VGGT 消融和 Mind-VLA。", results: ["正常五项平均 69%，Seer 50%，scene-image 58%。", "遮挡平均 54%，scene-image 28%，Seer 22%，OpenVLA 7%。", "完整模型正常→遮挡下降 13 点，scene-image 下降 29 点。"], evidenceNote: "各方法使用相同示范和迭代数，是最关键的受控真机比较。" },
    ],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["任务、三视图采集、损失、训练硬件和逐格试验可核验。"], implementation: ["静态+腕部 RGB 输入 224²；训练使用 8×H20，真机推理为 RTX 5090。", "每个目标三视图拍摄不足一分钟。"], missing: ["代码标注为将公开；当前未确认权重与对象三视图集。"] },
    deepDive: { lead: "Mind-VLA 用任务指令决定 3D 教师应该监督哪个对象，而不是让整幅场景共享同一个几何目标。", sections: [{ title: "指令对象三视图", paragraphs: ["仿真从 mesh 渲染正交三视图，真机用手持相机拍近似 canonical views；任务定义把指令映射到固定对象。", "VAE 压缩目标图像，VGGT 提供四个中间层的几何特征。"] }, { title: "训练期特权、推理期移除", paragraphs: ["三视图、VAE、VGGT 与辅助 decoder 都不进入部署；保留的只是经这些目标整形后的 VLA 主干。", "这避免在线深度和 3D 预处理，但把代价转为每个对象的一次性建库。"] }], equations: [{ name: "训练目标", expression: "L = L_VLA + λ_tri L_tri + λ_geo L_geo", explanation: "三视图 latent 重建和多层 VGGT 对齐共同约束基础动作模型。" }], experimentReading: ["scene-image 消融共享架构和数据，因此遮挡 26 点差距可较直接归因于对齐目标。", "对象词表有界且任务只指向单个对象，不能外推到开放词汇、多目标长时操作。"], reflections: [] },
    strengths: "同架构几何对齐消融、三类真机任务与物理遮挡协议直接对应核心假设。",
    limitations: "每个对象需预先三视图，无法零样本处理任意新对象；单目标假设在 LIBERO-Long 上已有退化。",
    transfer: "若部署不允许在线 3D 计算，可在训练期用指令对象的 canonical views 做表征蒸馏，并保留纯 RGB 推理。",
    figures: [{ src: "/report-assets/2026-08-07/2608.04633-fig2.png", alt: "Mind-VLA 的场景、对象与动作 query 以及三视图几何对齐", caption: "Figure 2 · Mind-VLA 的指令感知三视图监督与 VLA 主干。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 5,
    title: "Track4Action: Distilling World-Centric 3D Tracker into Vision-Language-Action Policies",
    arxivId: "2608.03727",
    url: "https://arxiv.org/abs/2608.03727",
    institutions: ["Zhejiang University", "Shanghai Jiao Tong University", "Shanghai Innovation Institute", "Noematrix"],
    signal: "让冻结 3D tracker 读取动作对应的视频片段，再把真实发生的世界变化蒸馏进只看当前帧的 VLA",
    tags: ["3D Tracking", "Privileged Supervision", "Tracker-Free Deployment"],
    classification: { research: "表征学习", training: "Post-training", modalities: ["Point Cloud / 3D"], platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://wing0night.github.io/track4action-project-page/" }],
    motivation: "动作标签只描述机器人命令，不说明这段命令怎样移动对象、改变遮挡和相机视角；这些世界变化实际存在于对齐的示范视频中。",
    methodSummary: "Track4World 在训练期编码与 K 个动作严格对齐的 K+1 帧，得到 scene/motion/camera 特征；VLA 的 track queries 学习预测该特征并通过 gate 条件化动作头。",
    architecture: "Qwen3.5-2B VLM+DiT-B flow head 共 3.3B；track queries cross-attend 当前 VLA hidden states，与冻结 tracker pooled target 做 L2 对齐，再经 feature-wise gate 融回动作条件。",
    optimization: "联合 flow-matching action loss 与 tracker alignment loss；部署移除视频片段、Track4World、teacher target 和对齐分支，只保留 query 与 gated fusion。",
    data: "LIBERO/LIBERO-Plus，RoboTwin2.0 50 个双臂任务；真机 AgileX ALOHA 式双 Piper 平台，四任务各 50 条示范。",
    experiments: "LIBERO-Plus 82.3%，alignment-free 74.7%；RoboTwin clean/random 80.44/81.48%。真机四任务平均 67.5%，无对齐为 42.5%。",
    novelty: "相对同数据、同主干、同训练计划的无对齐变体，真机提高 25.0 点；三种真机 OOD 条件平均从 23.3% 提至 50.0%。",
    experimentDetails: [
      { title: "跨基准 tracker distillation", setup: "LIBERO、七类零样本 LIBERO-Plus 扰动、RoboTwin2.0 50 任务 clean/random。", comparisons: "通用 VLA、video/trace/3D VLA 和 matched w/o-alignment。", results: ["LIBERO 94.2→97.0，Long 单套 86.2→95.8。", "LIBERO-Plus 74.7→82.3，七类扰动均提升。", "RoboTwin clean/random 41.32/39.90→80.44/81.48。"], evidenceNote: "matched 消融控制了数据、优化、模型规模和 rollout 接口。" },
      { title: "双臂真机与 OOD", setup: "辣椒搬运、折毛巾、双笔入抽屉、卷心菜入锅；各 50 demos、每方法每任务 10 trials。", comparisons: "π0.5、w/o alignment 与 Track4Action；另测新布局、毛巾颜色和桌面背景。", results: ["ID 平均 67.5%，π0.5 为 65.0%，w/o alignment 为 42.5%。", "OOD 平均 23.3→50.0%。", "未见颜色毛巾仅 20%，且 ID 折毛巾 40% 低于 π0.5 的 70%。"], evidenceNote: "每任务仅 10 次；形变物体是明确失败边界。" },
    ],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、训练目标、基准与真机协议可核验。"], implementation: ["LIBERO K=8；RoboTwin/真机 K=16，双臂动作为 14D。", "teacher 只用主相机的时序片段。"], missing: ["完整代码与 teacher 预处理流水线尚未确认公开；真机置信区间未报告。"] },
    deepDive: { lead: "Track4Action 把示范片段里真实发生的 3D 变化当作动作监督的配对标签，而不是部署时的额外输入。", sections: [{ title: "动作对齐的 tracker target", paragraphs: ["K 个动作对应 K 次状态转移，因此 teacher 使用 K+1 帧，避免目标跨越不相关事件。", "Track4World 的 scene、trace、camera token 被池化并 stop-gradient，学生从当前观察和指令预测它。"] }, { title: "action-facing 对齐", paragraphs: ["track queries 既承担 teacher 对齐，又直接进入 action head；这比独立辅助 decoder 更能让世界变化信息影响控制。", "部署仍只用当前图像、语言和状态，不运行 tracker。"] }], equations: [{ name: "联合训练目标", expression: "L = λ_act L_act + λ_align ‖z_t - f_t^trk‖²", explanation: "动作流匹配和 3D tracker 特征对齐共同训练。" }], experimentReading: ["matched alignment 消融在三个基准和真机方向一致，是核心证据。", "真机 10 次/任务且折毛巾退化，平均成功率不能掩盖形变操作弱点。"], reflections: [] },
    strengths: "训练期 teacher、部署期移除的边界清楚，matched 消融覆盖三套仿真与真机。",
    limitations: "要求时序有序示范；teacher 会受遮挡、快速运动和单主视角误差影响，真机只覆盖一个双臂平台。",
    transfer: "可把示范视频中与动作块严格对齐的世界变化蒸馏到 action-facing query，而不增加线上 tracker 成本。",
    figures: [{ src: "/report-assets/2026-08-07/2608.03727-fig2.png", alt: "Track4Action 将 3D tracker 时序特征蒸馏到 VLA 动作路径", caption: "Figure 2 · Track4Action 的训练期 Track4World teacher 与部署期 VLA。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 6,
    title: "DreamWAM: Beyond RGB Future Prediction for World Action Models",
    arxivId: "2608.04996",
    url: "https://arxiv.org/abs/2608.04996",
    institutions: ["Huazhong University of Science and Technology", "D-Robotics", "Wuhan University", "Horizon Robotics"],
    signal: "让世界动作模型同时学习未来外观、运动、几何和语义，并按目标表征选择 denoising 或残差注入路径",
    tags: ["World Action Model", "Structured Future", "Visual Robustness"],
    classification: { research: "WAM", training: "Post-training", modalities: ["Depth / RGB-D"], platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "GitHub", url: "https://github.com/hustvl/DreamWAM" }],
    motivation: "只预测 RGB 未来会把对象运动、几何和任务语义与光照、纹理、背景等无关像素变化纠缠，导致视觉分布变化时动作表征不稳。",
    methodSummary: "DreamWAM 联合去噪 RGB 与 RAFT optical-flow latent，并通过 gated residual branches 学习 Depth Anything V3 几何特征和 DINOv2 语义特征。",
    architecture: "Wan2.2-5B VideoDiT 与 ActionDiT 在配对层共享 attention；motion 与 RGB 进入共同 denoising state，geometry/semantics 只以门控残差修正 VideoDiT。教师与非 RGB 分支部署时移除。",
    optimization: "以 flow-matching 同时训练未来视图和动作；所有目标离线预计算。32-step action policy 每次执行 10 步、10 次 denoising，再重规划。",
    data: "LIBERO 每套 500 demos；LIBERO-Plus 只作七类未见扰动评估。真机四任务各 400 demonstrations，共 1600 条，多任务联合训练。",
    experiments: "LIBERO 98.0→98.9%，LIBERO-Plus 69.16→75.47%。真机四标准任务 90.8→96.7%，三类未见视觉扰动 55.6→74.4%。",
    novelty: "相对匹配的 Fast-WAM-Joint，真机扰动平均提高 18.8 点；无视频 rollout 的匹配版本在 LIBERO-Plus 也提高 12.08 点。",
    experimentDetails: [
      { title: "标准与未见扰动基准", setup: "LIBERO 每 seed 2000 rollouts；LIBERO-Plus 每 seed 10030 episodes，两随机种子，训练不使用 Plus 数据。", comparisons: "Fast-WAM/Joint 与相同 backbone/data 的 DreamWAM no-rollout/joint。", results: ["LIBERO no-rollout 97.30→98.40，joint 98.00→98.90。", "LIBERO-Plus no-rollout 51.36→63.44，joint 69.16→75.47。", "七类扰动在两种推理模式下全部改善。"], evidenceNote: "大规模两种子评估使扰动方向较稳定，ID 小差异仍不宜过度解读。" },
      { title: "双臂真机与路由消融", setup: "AgileX PiPER 四标准任务和 Strawberry Selection 三类视觉扰动，每格 30 trials；每模型共 210 rollouts。", comparisons: "Fast-WAM-Joint、各单视图/leave-one-out 与 D/D/D 全去噪路由。", results: ["标准平均 90.8→96.7，扰动平均 55.6→74.4。", "同样三个目标的 D/D/D 为 97.85%，混合 D/R/R 为 98.90%。", "去掉 motion 的平均 97.50%，是 leave-one-out 中最大下降。"], evidenceNote: "扰动保留同一任务语义且不额外适配，直接检查视觉稳健性。" },
    ],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["GitHub 已公开；论文给出目标构造、训练/评估规模与真机协议。"], implementation: ["RAFT flow 经 Wan VAE；DA3/DINO 特征以 rank-8 PCA 对齐到 latent grid。", "8×H20、bfloat16；真实数据采用 LeRobot v2.1。"], missing: ["真实训练与评估数据尚未确认完整公开；仅两随机种子。"] },
    deepDive: { lead: "DreamWAM 的关键不是多加三个 loss，而是让每种未来表征进入与其统计结构相容的路径。", sections: [{ title: "四种未来视图", paragraphs: ["RGB 表示外观，RAFT flow 表示图像平面运动，DA3 表示相对几何，DINOv2 表示对象与区域一致性。", "这些视图是互补投影，不被声称为完整或彼此独立的物理状态。"] }, { title: "表征匹配路由", paragraphs: ["RGB 与 flow 都是稠密 VAE latent，可在同一 flow timestep 联合去噪。", "DA3/DINO 特征不是 VAE latent，因此只通过门控残差修正主干；全量拼入 denoising state 反而低于 RGB 基线。"] }], experimentReading: ["no-rollout 版本仍显著提升，说明训练期结构监督确实进入动作策略。", "真机每格 30 次且所有扰动改善，但只在同一任务上变更视觉实现。"], reflections: [] },
    strengths: "匹配 backbone/data 的双推理模式、路由消融、大规模仿真和 210 次/模型真机评估相互支持。",
    limitations: "模型与训练计算量大；几何不是 metric 3D，尚无接触监督；真实扰动只围绕一个任务。",
    transfer: "为 WAM 增加未来监督时，应按目标统计选择去噪或受控残差，而不是把所有 teacher feature 强行拼到同一 latent。",
    figures: [{ src: "/report-assets/2026-08-07/2608.04996-fig2.png", alt: "DreamWAM 的多视图未来建模与门控世界残差架构", caption: "Figure 2 · DreamWAM 的 RGB/运动联合去噪与几何/语义门控残差。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 7,
    title: "EvoHIL: Self-Evolving Reward and Flow-Matched Policy Optimization for Robust Human-in-the-Loop Reinforcement Learning",
    arxivId: "2608.03872",
    url: "https://arxiv.org/abs/2608.03872",
    institutions: ["Chongqing University", "The University of Hong Kong", "Chengdu Anu Intelligence"],
    signal: "在真机 HIL-RL 中分别演化成功判据、动作块与视觉域，并用同一个 critic 串起三条受控数据路径",
    tags: ["Human-in-the-Loop RL", "Flow Matching", "Reward Adaptation"],
    classification: { research: "VLA", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://anonymous4366.github.io/EvoHIL/" }],
    motivation: "部署后固定视觉奖励会随光照失效，逐步 Gaussian 动作缺乏时序一致性，继续在原始视觉 replay 上优化又无法覆盖新外观。",
    methodSummary: "SER 从人工确认更新成功分类器；AFS 以 flow matching 生成短动作块并让 critic 评估实际执行前缀；离线阶段混合原始/重光照 replay，并用冻结 critic/actor 锚定旧能力。",
    architecture: "三阶段共享 actor-critic 但隔离标签来源：确认只更新 reward，policy/demo/intervention replay 各自进入 FPO、BC-flow 与平滑目标，relit replay 只用于离线适配。",
    optimization: "SER 使用正例确认、弱负例、held-out balanced-accuracy gate 与 EMA；AFS 对策略片段做 executed-prefix surrogate，对专家片段做 BC-flow；离线阶段关闭 FPO。",
    data: "Franka FR3 四任务、SO-101 两任务；所有基线匹配示范、真机交互预算和传感输入。视觉适配另外使用离线重光照记录，不新增机器人交互。",
    experiments: "60% 光照 shift 下每方法-场景 60 trials：EvoHIL 六任务成功率 0.83–1.00；HIL-SERL 为 0.13–0.50。完整光照 sweep 显示极端条件仍渐进退化。",
    novelty: "在 60% shift 的六场景全部优于 HIL-SERL；USB/RAM 为 1.00 对 0.50/0.43，candy push 为 0.93 对 0.20。",
    experimentDetails: [
      { title: "跨本体光照 shift", setup: "FR3 四任务、SO-101 两任务；0–100% 十档复合光照，主结果为 60%，每格 60 次独立 reset。", comparisons: "HIL-SERL、HG-DAgger、BC、IBRL、ACT 和 EvoHIL。", results: ["USB/RAM/table wiping/breaker 为 1.00/1.00/0.87/0.83。", "Candy push/medicine-box stow 为 0.93/0.73。", "USB 在 90% shift 前保持 1.00，100% 为 0.97。"], evidenceNote: "shift 是预定义适配/压力测试，不是未见光照的零样本泛化。" },
      { title: "奖励、动作与保留消融", setup: "SER 在两项 SO-101 任务跟踪 proxy agreement；AFS 30-rollout 消融；USB 做 replay/anchor 2×2。", comparisons: "去 SER、去 AFS、去 FPO/BC/smoothness、是否混合 replay/anchors。", results: ["去 AFS 时 push/stow 为 0.88/0.69；去 SER 为 0.70/0.47。", "USB 混合 replay+anchors 达到原/新光照 1.00/1.00；只混合为 0.77/0.67。", "AFS 将 push/stow 的高频功率比例分别降低 58.3%/47.9%。"], evidenceNote: "部分曲线与消融来自单训练 run、selected checkpoint，论文明确将其作为描述性证据。" },
    ],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["六任务、数据路径、超参、逐格次数和局限可核验。"], implementation: ["SER threshold 0.95、连续 2 帧、EMA 0.1；AFS 默认 H=5、executed prefix N=4。", "控制 10 Hz，RGB 128²；原域 replay 比例 α=0.75。"], missing: ["设备推理延迟与完整训练 run 统计未保留；重光照数据/代码未确认公开。"] },
    deepDive: { lead: "EvoHIL 将部署漂移拆成奖励、动作与视觉三个接口，避免用一个继续训练目标混合不同监督来源。", sections: [{ title: "标签源隔离与 SER", paragraphs: ["人工确认是可信正例，未确认帧只作有偏弱负例；分类器自身预测不能反写成正标签。", "新分类器只有在代理 held-out split 的 balanced accuracy 过阈值后才以 EMA 部署。"] }, { title: "执行前缀与保留", paragraphs: ["动作块可能只执行一部分就重规划，critic 和 policy surrogate 都只对实际前缀负责。", "离线视觉适配用原域/重光照 replay 覆盖新外观，并在专家状态锚定旧 critic 值与 flow velocity。"] }], equations: [{ name: "平滑度指标", expression: "S_smooth = 1 / (1 + D₁ + D₂ + P_HF)", explanation: "一阶/二阶动作差与高频功率越小，归一化命令的时序规则性越高。" }], experimentReading: ["每场景 60 次是真机证据的优点，但对应 selected policies 而非独立训练 run 分布。", "SER 指标只与确认代理一致，不等同于未观测的真实成功校准。"], reflections: [] },
    strengths: "六个接触任务、两种本体、统一 60-trial 协议以及分组件消融覆盖完整部署链。",
    limitations: "依赖人工确认和外部 relighter；若重光照不保持几何，离线转移会失真；多数训练曲线是单 run 且有 checkpoint 选择效应。",
    transfer: "HIL-RL 系统应隔离 reward 标签、policy rollout 与专家纠正，并让 chunk critic 只评价真正执行的动作前缀。",
    figures: [{ src: "/report-assets/2026-08-07/2608.03872-fig2.png", alt: "EvoHIL 的动作流稳定、自演化奖励和离线鲁棒微调阶段", caption: "Figure 2 · EvoHIL 的 SER、AFS 与 retention-aware offline fine-tuning。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 8,
    title: "Unified Visuomotor Targets: Supervising VLAs Beyond Physical Actions",
    arxivId: "2608.03563",
    url: "https://arxiv.org/abs/2608.03563",
    institutions: ["University of California, Irvine"],
    signal: "把机器人动作和视觉状态变化融合成统一 latent target，改变 VLA 预测什么而不改主干结构",
    tags: ["Latent Action", "VLA Supervision", "Bimanual Manipulation"],
    classification: { research: "表征学习", training: "Post-training", data: "其他数据方法", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://unified-visuomotor-targets.github.io/" }],
    motivation: "VLM 表征场景与目标，而原始关节/笛卡尔动作是低层信号；直接让 VLA 从语义表征回归动作会造成监督空间错配。",
    methodSummary: "UVT 用预训练 inverse-dynamics LAM 从未来图像提取离散 dynamics code，再以多模态 VAE 与动作块做 precision-weighted product-of-experts，形成 32D 统一目标。",
    architecture: "动作与 dynamics code 各自编码为 diagonal Gaussian，融合均值作为 UVT；双 decoder 重建动作和 code。VLA 改为预测 UVT，再由可训练 action decoder 恢复执行动作。",
    optimization: "MVAE 先以动作 L1、dynamics CE 和 KL 训练；VLA 阶段联合 UVT alignment 与解码动作 L1，权重 γ=0.5。",
    data: "LIBERO/LIBERO-Plus 原示范，无额外数据；真机三个双臂任务各 30 条 VR 遥操作示范，同等预算训练 10 GPU-hours。",
    experiments: "LIBERO 94.6→96.7%；10K-step LIBERO-Plus 平均 42.7→66.2。真机各 50 trials：Lift Pot 38→54%，Close Marker 0→38%，Plate Handover 18→40%。",
    novelty: "相对 action-only VLA-Adapter，在三项真机分别提高 16、38、22 点；在 LIBERO-Spatial 10K steps 为 95.0%，双头 dynamics 辅助最多 86.4%。",
    experimentDetails: [
      { title: "训练效率与表示消融", setup: "LIBERO/LIBERO-Plus 比较 10K 与 100K steps，并在 Spatial 套件比较双头辅助。", comparisons: "action-only、Villa-X/UniVLA dynamics head 与 UVT。", results: ["LIBERO 10K 平均 79.7→88.2，100K 为 94.6→96.7。", "LIBERO-Plus 10K 平均 42.7→66.2。", "Spatial 10K：baseline 78.8、双头 83.2/86.4、UVT 95.0。"], evidenceNote: "100K 后差距缩小，主要收益集中在早期训练和扰动条件。" },
      { title: "三项双臂真机", setup: "Lift Pot、Close Marker、Plate Handover，各 30 demos、50 trials；位置随机，前两项再随机物体旋转。", comparisons: "相同 VLA-Adapter 与训练预算下的 action-only 和 UVT。", results: ["Lift Pot 19/50→27/50。", "Close Marker baseline 0 full/0 half；UVT 为 5 full+28 half，计分 38%。", "Plate Handover 7 full+4 half→12 full+16 half，18→40%。"], evidenceNote: "半成功按 0.5 计分，必须与完整成功数一并阅读。" },
    ],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["项目页、MVAE 目标、训练预算、示范量和试验数可核验。"], implementation: ["UVT 32D；LAM code 来自当前/未来图像；LIBERO 10K steps 约 8 A6000 GPU-hours。"], missing: ["代码与训练权重尚未确认公开；LAM 预训练细节和跨任务成本披露有限。"] },
    deepDive: { lead: "UVT 把视觉上发生了什么与机器人怎样运动压进同一个目标，让 VLA 不必只对齐低层动作数值。", sections: [{ title: "precision-weighted 融合", paragraphs: ["动作 encoder 与 dynamics encoder 分别输出均值、方差，低方差维度在 product-of-experts 中权重更高。", "共享 latent 必须同时重建连续动作与离散视觉变化，因此不能只保留一种模态。"] }, { title: "策略解码", paragraphs: ["VLA 可用回归或 flow head 预测 UVT，主干无需改造。", "action decoder 在 VLA 训练期继续更新，以适应预测 UVT 与离线预计算目标之间的分布差。"] }], experimentReading: ["双头辅助弱于统一 latent，支持‘共同目标’而非简单多任务监督。", "Close Marker 虽从 0 提升，但完整成功仍只有 5/50，精密插入仍未解决。"], reflections: [] },
    strengths: "在两种 VLA head、两套基准与三个 50-trial 真机任务上方向一致，并有直接目标构造消融。",
    limitations: "需要先训练 LAM 与 MVAE；真机只比较同一基座且精密任务完整成功率仍低，论文未报告独立随机种子。",
    transfer: "可把视觉转移 code 与动作块先压成统一监督空间，再让现有 VLA head 预测该 latent，而无需改 backbone。",
    figures: [{ src: "/report-assets/2026-08-07/2608.03563-fig1.png", alt: "UVT 通过多模态 VAE 融合动作和视觉 dynamics code", caption: "Figure 1 · UVT 的统一 visuomotor target 构建与 VLA 微调。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 9,
    title: "Continue or Replan? Bernoulli-Continuation Policy Learning for Adaptive Horizon Execution",
    arxivId: "2608.03483",
    url: "https://arxiv.org/abs/2608.03483",
    institutions: ["Peking University", "Microsoft Research Asia"],
    signal: "冻结 VLA，只学习每个动作前缀是否继续执行，用真实结果在时域上动态选择重规划边界",
    tags: ["Adaptive Replanning", "VLA RL", "GRPO"],
    classification: { research: "VLA", training: "RL", platforms: ["机械臂", "夹爪"] },
    motivation: "固定 action-chunk horizon 对执行相位极敏感：重规划太频繁破坏连贯动作，太晚又会继续执行过时命令。",
    methodSummary: "BCP 对冻结 VLA 的候选前缀输出连续 Bernoulli 概率，较长 horizon 的概率由逐段 continue 概率乘积得到，再按分布选择执行长度。",
    architecture: "两层 Transformer 读取 VLA 语言/视觉 token、去噪动作及末步速度；候选 horizon 为 15、20、25…50，head 输出每个边界的 continue sigmoid。",
    optimization: "以 GRPO 根据 rollout outcome 更新约 16.4M 参数；Replanning-Efficiency Reward 只给成功轨迹，并按相对参考调用成本对过度/不足重规划施加非对称系数。",
    data: "RoboTwin2.0 50 任务、LIBERO/LIBERO-PRO；真机 AGIBOT G1 的 Bottle/Mug 放置各用 250 任务示范+2000 抓取示范，并收集 128 条 BCP RL 轨迹。",
    experiments: "RoboTwin clean 89.88→93.94%，random 88.78→92.84%；LIBERO-PRO 30.9→37.7%。真机 Bottle 74→92%，Mug 44→84%。",
    novelty: "相对固定 horizon，真机 Bottle/Mug 分别提高 18/40 点；在 13 个低成功 RoboTwin 任务 clean 平均 75.15→86.23。",
    experimentDetails: [
      { title: "重规划相位与仿真", setup: "RoboTwin 50 任务及 13 个低成功子集，LIBERO/LIBERO-PRO；相位实验遍历 50 个初始 phase。", comparisons: "固定 horizon、AAC、softmax/BC head 和 BCP。", results: ["同一 50-step horizon 仅改 phase，成功率跨度 11.30 点。", "RoboTwin clean/random 提高 4.06/4.06 点。", "LIBERO-PRO 30.9→37.7；LIBERO 97.0→98.7。"], evidenceNote: "BCP 的 VLA 主干冻结，因此增益来自重规划时域策略。" },
      { title: "AGIBOT G1 真机", setup: "Bottle/Mug，每个方法在相同 50 seeds 下每 seed 3 trials；BCP 用 128 条真实 RL 轨迹。", comparisons: "LingBot-VLA SFT、AAC 和 BCP。", results: ["Bottle 74→92%。", "Mug 44→84%，AAC 为 48%。", "仿真 ablation 中完整 BCP 87%，固定动作 expert RL 79%。"], evidenceNote: "论文未给独立训练随机种子；真实 RL 仍有 128 条轨迹成本。" },
    ],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["候选 horizon、reward、训练参数与真机协议可核验。"], implementation: ["训练 8×A100 40GB、300 steps、batch 512、group size 8。", "平均 VLA 调用 5.382→5.614，但执行步数 269.075→248.102。"], missing: ["代码/权重尚未确认公开；训练 run 方差和真机失败分类未报告。"] },
    deepDive: { lead: "BCP 把 action chunk 视为可提前终止的承诺，并只在几个离散边界判断是否继续。", sections: [{ title: "Bernoulli continuation", paragraphs: ["较长 horizon 必须通过之前所有 continue 边界，因此概率自然形成有序分布。", "输入不仅含 VLA token 和动作，还含末步速度，用于判断当前 chunk 是否仍处于稳定运动阶段。"] }, { title: "效率奖励", paragraphs: ["成功是必要条件，效率项比较本轨迹的 VLA 调用/执行成本与参考。", "正负效率采用不同系数，避免通过激进延长 horizon 换取少调用却损失成功。"] }], experimentReading: ["phase sweep 直接证明固定 horizon 的结果不是单一合理相位。", "真机同 seed 三次有配对性，但训练随机性与 128 条 RL 数据的可迁移性未知。"], reflections: [] },
    strengths: "冻结主干的受控设计、phase sweep、仿真消融与两项真机大幅提升直接对应问题。",
    limitations: "仍需真实 RL rollout；候选 horizon 离散且依赖基础 chunk 长度，训练 run 方差和跨本体迁移未给出。",
    transfer: "可在不改 VLA 权重的情况下学习轻量 continuation head，把重规划频率从固定超参变成 outcome-driven policy。",
    figures: [{ src: "/report-assets/2026-08-07/2608.03483-fig2.png", alt: "BCP 从冻结 VLA 动作块预测继续概率并用 GRPO 训练", caption: "Figure 2 · Bernoulli-Continuation Policy 的动作前缀选择与效率奖励。图片来自 arXiv HTML 原图。" }],
  },
  {
    rank: 10,
    title: "LiLa-WAM: Lightweight Latent Reasoning World-Action Model for Robotic Manipulation",
    arxivId: "2608.03701",
    url: "https://arxiv.org/abs/2608.03701",
    institutions: ["Tianjin University", "Shenzhen University of Advanced Technology", "Mininglamp Technology", "Ministry of Natural Resources Information Center", "Sangfor Technologies"],
    signal: "用紧凑未来视觉 latent 监督小型 action expert，并以任务级视觉转移 token 在无语言部署时提供目标",
    tags: ["Lightweight WAM", "Future Latent", "Task Token"],
    classification: { research: "WAM", training: "Post-training", platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "GitHub", url: "https://github.com/teee000/LiLa-WAM" }],
    motivation: "大型 video-action world model 计算昂贵，而轻量 VLA 仅预测动作时又缺少未来状态约束，训练效率与扰动稳健性有限。",
    methodSummary: "LiLa-WAM 用冻结 DINOv3 提取当前/未来特征，adapter 与 action expert 共同预测 compact foresight token；每项任务的 VTT 由示范终帧减初帧的平均 embedding 构成。",
    architecture: "冻结 DINOv3-ViT-L/16 的第 17/21 层特征进入 64-query 四层 adapter，再与 reasoning、VTT、proprioception 和 noisy action token 送入 12 层 DiT；训练期 decoder 重建未来特征。",
    optimization: "flow-matching 动作 loss 与 future-feature cosine loss 联合训练，λ_ff=0.5；0.5B 总参数中 0.2B 可训练，action chunk 32 步、执行 16 步。",
    data: "RoboTwin 50 任务每任务 50 clean+500 randomized demos；LIBERO；真机 AgileX Piper 四任务各 60 条示范。",
    experiments: "RoboTwin clean/random 90.48/89.04%，LIBERO 97.1%。真机四任务各 50 rollouts，去 foresight 平均 74%，完整模型 82%。",
    novelty: "相对自身无 foresight 变体，真机平均提高 8 点；Button 72→86、Block 84→90、Banana 92→96、Basketball 48→56。",
    experimentDetails: [
      { title: "仿真与计算效率", setup: "RoboTwin 50 任务 clean/random，LIBERO 四套；单 RTX 5090 训练约 110 GPU-hours。", comparisons: "同规模 VLA、不同 future representation 与 decoder/foresight 消融。", results: ["RoboTwin 90.48/89.04，LIBERO 平均 97.1。", "RTX 4090 推理约 85 ms，10 ODE steps。", "0.5B 总参数、0.2B 可训练。"], evidenceNote: "多数外部基线的 backbone 和训练数据不完全匹配，自身消融更可信。" },
      { title: "四项 Piper 真机", setup: "Button、Block、Banana、Basketball；每项 60 demos、每方法 50 rollouts，30 Hz 控制。", comparisons: "相同模型去掉 foresight 与完整 LiLa-WAM。", results: ["平均 74→82%。", "四任务分别 72→86、84→90、92→96、48→56。", "异步推理在 action queue 剩余 8 步时触发。"], evidenceNote: "真机没有外部 policy baseline，只能确认 foresight 组件的增益。" },
    ],
    reproducibilityDetails: { status: "资源较完整", verifiedResources: ["GitHub 已公开；架构、参数量、训练预算与真机次数可核验。"], implementation: ["DINOv3 冻结；输入 320×240，16D proprio、14D action。", "AdamW，future cosine loss 权重 0.5。"], missing: ["当前未核验完整真机数据/权重；外部真机基线缺失。"] },
    deepDive: { lead: "LiLa-WAM 用低维未来特征代替生成完整视频，把 world-model 监督压缩到轻量 VLA 可承受的规模。", sections: [{ title: "VTT 与 foresight", paragraphs: ["VTT 是同任务示范的终帧与初帧全局 embedding 差的平均，部署时替代语言提供目标方向。", "action expert 预测动作 velocity 与 foresight token，后者在训练期对齐未来 DINO 特征。"] }, { title: "训练期 decoder", paragraphs: ["四层 decoder 只用于从 compact token 重建未来 feature，并以 cosine loss 监督。", "部署移除 decoder，保留 adapter、action expert 与预先计算的任务 VTT。"] }], equations: [{ name: "联合损失", expression: "L = L_fm + 0.5 L_ff", explanation: "动作 flow matching 与未来特征余弦监督共同更新可训练部分。" }], experimentReading: ["50 trials/任务使 8 点平均消融有一定分辨力。", "VTT 预先按任务计算，故不能将结果解释为开放指令或未知任务泛化。"], reflections: [] },
    strengths: "小模型、公开代码、明确计算量和四项各 50 次真机组件消融。",
    limitations: "依赖已知任务的 VTT，真机只有内部消融且任务较简单；对开放语言、未见任务和接触复杂性证据不足。",
    transfer: "若完整视频预测过重，可用冻结视觉 encoder 的未来 feature 做紧凑辅助目标，并在部署移除 decoder。",
    figures: [{ src: "/report-assets/2026-08-07/2608.03701-fig2.png", alt: "LiLa-WAM 的特征融合、紧凑未来 token 和动作专家", caption: "Figure 2 · LiLa-WAM 的 foresight-aware action expert。图片来自 arXiv source 原始矢量图。" }],
  },
  {
    rank: 11,
    title: "Explicit Language Memory for Long-Horizon Planning in Vision-Language-Action Models",
    arxivId: "2608.04765",
    url: "https://arxiv.org/abs/2608.04765",
    institutions: ["Fudan University"],
    signal: "把已完成阶段、失败证据与下一目标压缩成可读文本状态，显式连接高层语义规划和低层动作块",
    tags: ["Language Memory", "Long-Horizon Planning", "Hierarchical VLA"],
    classification: { research: "Memory", training: "Post-training", platforms: ["机械臂", "轮式底盘", "夹爪"] },
    motivation: "只看当前帧的 VLA 无法区分外观相似但历史不同的任务阶段，容易跳步、重复或在失败后继续执行错误子任务。",
    methodSummary: "高层 PaliGemma 递归生成 language memory 与当前 subtask，低层 π0.5 风格 VLA 根据当前观察和 subtask 生成 H=30 动作块；执行后再用新观察更新记忆。",
    architecture: "记忆保留完成事件、可见证据、失败和下一里程碑，并把已完成细节压缩为过去时摘要；高低层独立训练，避免语言与连续控制 loss 相互干扰。",
    optimization: "高层用自动生成的 frame-aligned memory/subtask 监督做自回归训练；低层用 flow-matching 动作目标。两侧 VLM 采用 LoRA，300M action expert 全量微调。",
    data: "BEHAVIOR-1K 开收音机、Genie Sim 3.0 包裹分拣；真机 XLeRobot 由双 SO-ARM101+LeKiwi 构成，pick-place 25 条人工轨迹。",
    experiments: "仿真阶段平均：收音机 30.0→40.0%，单包裹 41.7→63.9%，连续分拣 31.3→46.9%。真机 20 trials 的阶段平均 62.5→66.3%。",
    novelty: "相对原生 π0.5，长时仿真单包裹提高 22.2 点、连续分拣提高 15.6 点；短真机任务只提高 3.8 点。",
    experimentDetails: [
      { title: "长时阶段一致性", setup: "BEHAVIOR-1K 收音机四阶段，Genie 单包裹六阶段与连续四包裹；按阶段成功率计分。", comparisons: "原生 π0.5 与加入递归 language memory 的层级策略。", results: ["收音机 30.0→40.0，PressOn 仍仅 10.0%。", "单包裹 41.7→63.9，连续分拣 31.3→46.9。", "连续任务中完整四次 upright placement 从 0 提至 12.5%。"], evidenceNote: "论文未给随机种子或置信区间，阶段平均不等同终局成功率。" },
      { title: "XLeRobot 真机", setup: "双 SO-ARM101+移动底盘，25 条训练轨迹、20 trials；Follow/PickUp/MoveTo/Place 四阶段。", comparisons: "原生 π0.5 与 language-memory hierarchy。", results: ["阶段平均 62.5→66.3%。", "Follow 都为 100%，其余三阶段各 50→55%。", "日志展示失败抓取可被写入记忆并触发重试，但未单列恢复成功率。"], evidenceNote: "真机任务较短、增益小且 20 次无统计区间，是本期最低排名的重要原因。" },
    ],
    reproducibilityDetails: { status: "部分可复现", verifiedResources: ["论文、架构 source 原图、训练超参、平台和逐阶段结果可核验。"], implementation: ["4×A100 训练、RTX 5880 Ada 推理；batch 64、50K steps、峰值学习率 2.5×10⁻⁵。", "高层标注可由 Gemini 3.5 Flash 或 Qwen3.5-9B 生成。"], missing: ["代码、数据与权重尚未确认公开；高层额外调用的端到端延迟未量化。"] },
    deepDive: { lead: "显式文本记忆把任务阶段变成可检查状态变量，但它主要修复‘做什么’，不能替代接触控制中的‘怎么做’。", sections: [{ title: "滚动语言压缩", paragraphs: ["未完成阶段保留类别、颜色、位置等细节；观察到里程碑后，旧细节压成短句并将意图移到下一步。", "高层同时输出更新记忆和 subtask，低层只接收当前观察与 subtask。"] }, { title: "闭环边界", paragraphs: ["每执行 30 个动作重新观察，高层只有看到状态变化证据才推进任务。", "PressOn 失败说明正确语义阶段仍可能因定位、力和时序不足而无法完成。"] }], equations: [{ name: "层级分解", expression: "π(a,s,m | o,m_prev,l) = π_LL(a | o,s) · π_HL(s,m | o,m_prev,l)", explanation: "高层维护语义状态与子任务，低层生成连续动作块。" }], experimentReading: ["长时仿真增益明显高于短真机，符合记忆只在跨阶段依赖中有空间发挥的假设。", "真机 3.8 点变化在 20 次评估下不足以证明稳定提升。"], reflections: [] },
    strengths: "记忆内容可读，阶段级错误案例与两个长时仿真环境直接验证跳步问题，并有真实机器人闭环。",
    limitations: "真机只有短 pick-place、20 次且提升很小；仿真无种子/置信区间，高层 VLM 增加延迟和系统复杂性。",
    transfer: "长任务可把完成证据、失败与下一里程碑压成短文本状态，作为动作策略的可解释阶段接口。",
    figures: [{ src: "/report-assets/2026-08-07/2608.04765-fig2.png", alt: "显式语言记忆的高层 VLM 与低层动作专家闭环", caption: "Figure 2 · 显式语言记忆、高层 subtask 与低层动作块闭环。图片来自 arXiv source 原始矢量图。" }],
  },
];

const selectedPaperIds20260807 = [
  "2608.03387", "2608.04196", "2608.03727", "2608.03872", "2608.03563",
  "2608.05042", "2608.04633", "2608.04996",
];

export const paperDaily20260807: Paper[] = selectedPaperIds20260807.map((paperId, index) => {
  const paper = paperCandidates20260807.find((candidate) => candidate.arxivId === paperId);
  if (!paper) throw new Error(`Missing selected paper: ${paperId}`);
  return { ...paper, rank: index + 1 };
});
