import type { Paper } from "./site-data";

export const paperDaily20260706: Paper[] = [
  {
    rank: 1,
    title: "WSA1: a 3D-Centric World-Spatial-Action Model for Generalizable Robot Control",
    arxivId: "2607.03941",
    url: "https://arxiv.org/abs/2607.03941",
    institutions: ["Tongji University", "Shanghai Innovation Institution", "Shanghai Magic", "Koala Uran"],
    signal: "把空间理解、三维世界预测与动作生成放进同一组专家网络，并用跨本体大规模数据验证真机迁移",
    tags: ["3D World-Action", "Cross-Embodiment", "Large-Scale Pretraining"],
    classification: { research: "WAM", training: "Pre-training", modalities: ["Point Cloud / 3D"], data: "跨本体数据", platforms: ["机械臂", "夹爪"], deployment: "跨本体迁移" },
    resources: [{ label: "GitHub", url: "https://github.com/zaleni/WSA" }],
    motivation: "多数 VLA 仍主要从二维语义直接回归动作，难以同时保持几何一致性、理解物体运动并迁移到不同机器人。",
    methodSummary: "WSA1 用 2D Spatial、3D Spatial 和 3D Action 三个互补专家共享上下文，在同一训练中学习三维世界建模、逆动力学和动作控制。",
    architecture: "视觉、文本、机器人状态和动作被映射到统一 token 空间；三个 Transformer 专家通过双向因果注意力交换信息，世界分支预测几何变化，动作分支输出控制序列。",
    optimization: "先在 6000+ 小时人类、仿真和真机视频上联合预训练，再针对 LIBERO、RoboTwin 2.0 及两类真机本体微调；消融检查 2D/3D 一致性和 world-action 因果连接。",
    data: "论文汇总约 692M 帧、300+ 控制任务、8 类机器人和 50+ 技能；来源包括约 1000 小时真机、约 5000 小时仿真以及人类第一视角数据。",
    experiments: "RoboTwin 2.0 困难任务成功率达到 93%；LIBERO 报告 97% 以上平均成功率；单臂 AgileX Piper 与双臂 ARX Lift2 真机任务的成功率均超过 77%。",
    novelty: "与只增加 3D 输入的 VLA 相比，WSA1 把三维表征同时用于世界预测和动作建模，并在保持同一框架的情况下覆盖单臂、双臂和不同数据来源。",
    strengths: "数据规模、跨本体覆盖、仿真难任务和两套真机平台形成了较完整的泛化证据。",
    limitations: "数据组成包含多个来源，训练成本高；论文给出的总小时数与分项为近似统计，复刻同等规模预训练并不现实。",
    transfer: "适合借鉴其三专家分工、三维 world-action 联合监督和跨本体动作表示，而不必完整复制其数据规模。",
    experimentDetails: [{ title: "跨基准与真机泛化", setup: "在 LIBERO、RoboTwin 2.0、AgileX Piper 单臂和 ARX Lift2 双臂平台评估，并覆盖多任务与未见配置。", comparisons: "与二维 VLA、只做空间建模或只做动作建模的变体，以及主流 VLA/WAM 基线比较。", results: ["RoboTwin 2.0 困难集报告 93% 成功率。", "两类真机平台的成功率均超过 77%，任务完整度超过 82%。", "移除 3D 世界建模或 world-action 连接后均出现下降，说明收益不只是数据量。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["三专家 Mixture-of-Transformers；联合 2D/3D world、inverse dynamics 与 action 目标；跨本体动作掩码。"], verifiedResources: ["GitHub 项目已公开；正文列出数据来源、训练任务和主要消融。"], missing: ["完整 6000+ 小时数据与等规模训练资源无法由公开仓库直接还原。"] },
    deepDive: { lead: "WSA1 的关键不是简单地给 VLA 加深度，而是让三维状态成为世界预测与动作预测的共同中介。", sections: [{ title: "三条信息流如何配合", paragraphs: ["2D Spatial Expert 保留预训练视觉语言模型擅长的语义，3D Spatial Expert 建模点云与物体运动，3D Action Expert 负责动作序列。专家之间用受约束的注意力连接，既允许动作读取世界状态，也让世界预测受到动作条件约束。", "训练时，当前场景、未来几何和动作被联合建模；部署时动作专家可直接输出控制，不需要完整生成未来视频。这使世界建模监督更多地承担表征正则，而不是成为推理瓶颈。"] }], experimentReading: ["跨本体真机结果比单一仿真均分更重要；但大规模内部数据仍可能贡献相当部分增益。"], reflections: ["对已有 VLA，优先尝试引入几何预测辅助目标与专家路由，可能比重做全量 3D backbone 更容易验证。"] },
    figures: [{ src: "/report-assets/2026-07-06/2607.03941-overview.png", alt: "WSA1 三个世界空间动作专家与联合训练任务", caption: "Figure 3 · WSA1 的 2D Spatial、3D Spatial 与 3D Action 专家结构。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 2,
    title: "HALO-WA: Hybrid-Attention Latent-Guided Online Reinforcement Learning for World-Action Models",
    arxivId: "2607.04265",
    url: "https://arxiv.org/abs/2607.04265",
    institutions: ["Chinese Academy of Sciences", "University of Chinese Academy of Sciences", "GigaAI", "Tsinghua University"],
    signal: "冻结已有 WAM，只训练读取世界模型潜变量与参考动作的轻量 actor-critic 适配器，快速修正精密接触误差",
    tags: ["World-Action Model", "Online RL", "Precision Manipulation"],
    classification: { research: "WAM", training: "RL", data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "GitHub", url: "https://github.com/YeanRoot/HALO-WA" }],
    motivation: "WAM 的长动作块能完成大范围运动，但末端几毫米的插接、校准和接触误差仍会造成失败，直接重训大模型成本过高。",
    methodSummary: "HALO-WA 冻结基础 WAM，用混合注意力 actor-critic adapter 读取视觉潜变量、机器人状态和 WAM 参考动作，再输出修正后的动作块。",
    architecture: "adapter 的自注意力保持动作块内部时序一致性，交叉注意力从 WAM latent 中读取当前任务信息；actor 生成精修动作，critic 对动作块估值。",
    optimization: "以 WAM 轨迹作为动作先验做在线 RL，只更新轻量 adapter；每项真机任务训练 45–75 分钟，并记录人工干预率随训练的变化。",
    data: "基础 WAM 每个真机任务使用 100 条示范；在线阶段来自四项精密任务的真机 rollout，另用 RoboTwin 任务做可复现补充实验。",
    experiments: "四项真机任务平均成功率从基础 WAM 的 26.4% 提升到 87.1%，比最强对照高 19.2 个百分点；并提供输入拼接、视觉编码和注意力结构消融。",
    novelty: "相较动作 token 级 RL 或直接残差控制，HALO-WA 显式保留动作块时序，并把 WAM 中间潜变量作为在线修正的状态表示。",
    strengths: "四类真实精密任务、训练耗时、干预曲线、仿真复核和结构消融都较完整。",
    limitations: "仍依赖一个可用的基础 WAM；在线训练需要真实机器人交互，安全约束和更长任务上的稳定性尚未充分展开。",
    transfer: "适合作为冻结式 WAM/VLA 后训练方案，特别是基础策略已会接近目标、但最后接触阶段不稳定的任务。",
    experimentDetails: [{ title: "精密操作在线适配", setup: "AgileX ALOHA 上进行木棍装配、网线插接、积木堆叠和电源插头插接；每任务先有 100 条基础示范。", comparisons: "WAM-base、不同 RL token/adapter 设计以及若干视觉表示变体。", results: ["WAM-base 平均 26.4%，HALO-WA 达到 87.1%。", "最强基线平均 67.9%，HALO-WA 高 19.2 个百分点。", "每任务在线训练 45–75 分钟；混合注意力优于直接拼接和独立视觉编码。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["冻结 GigaWorld Policy；actor-critic adapter；动作块自注意力与 latent 交叉注意力；在线 RL。"], verifiedResources: ["代码公开；正文给出四项真机协议、干预曲线和 RoboTwin 补充实验。"], missing: ["基础 WAM 权重、真机示范及统一硬件配置仍决定复现成本。"] },
    deepDive: { lead: "HALO-WA 把世界模型当成可读取的隐状态，而不是要求它重新生成更准确的视频。", sections: [{ title: "为何保留参考动作", paragraphs: ["基础 WAM 给出长动作块，它通常已包含任务大方向。adapter 不从零生成，而是在参考动作、机器人状态与视觉 latent 的条件下学习精修，因此在线数据主要用于校正部署偏差。", "自注意力处理动作块内部关系，避免逐点残差破坏速度与接触时序；交叉注意力则让修正集中到对末端对齐有用的潜变量。"] }], experimentReading: ["从 26.4% 到 87.1% 的提升发生在基础模型失败率很高的精密任务上，表明 adapter 能补偿部署误差，但并不等价于基础能力全面增强。"], reflections: ["若现有策略在接近目标前就频繁失败，应先修基础数据或模型；若失败集中于末端接触，HALO-WA 式局部 RL 更合适。"] },
    figures: [{ src: "/report-assets/2026-07-06/2607.04265-overview.png", alt: "HALO-WA 冻结世界动作模型与混合注意力 actor critic 适配器", caption: "Figure 2 · HALO-WA 的 latent-guided 混合注意力 adapter。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 3,
    title: "OMNITACTUNE: Policy-Agnostic Real-World RL for Tactile Residual Adaptation of Visual Policies",
    arxivId: "2607.03723",
    url: "https://arxiv.org/abs/2607.03723",
    institutions: ["University of Maryland", "Georgia Institute of Technology"],
    signal: "用两阶段真机 RL 把触觉残差接到不同视觉策略上，在不重训视觉主干的情况下补足接触控制",
    tags: ["Tactile Residual", "Real-World RL", "Policy-Agnostic"],
    classification: { research: "VLA", training: "RL", modalities: ["Tactile"], data: "在线数据 / 人工纠正", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    resources: [{ label: "项目页", url: "https://colinyu1.github.io/omnitactune-site/" }],
    motivation: "来自人类视频或机器人示范的视觉策略能提供运动先验，却难以感知遮挡下的接触、滑移和局部力学；触觉数据又昂贵且难统一。",
    methodSummary: "先用基础策略自主 rollout 训练触觉价值/残差的 warm start，再进行在线 RL；最终残差动作叠加到冻结视觉策略上。",
    architecture: "视觉基础策略保持冻结；触觉编码、critic 与轻量残差 actor 构成独立支路，运行时只在基础动作上施加触觉修正。",
    optimization: "两阶段均使用真实机器人数据：第一阶段从现有策略 rollout 学习，第二阶段在线探索；不同视觉 backbone 与触觉表示共用同一框架。",
    data: "覆盖 peg-in-hole、充电器插接、瓶盖开启和盒子开启四项真机任务；基础策略来自人类视频重定向、VR 遥操作或机器人示范。",
    experiments: "不同基础视觉策略原始成功率为 5%–40%，适配后达到 85%–100%，每项任务在线训练 40–80 分钟；论文对 warm start、奖励与触觉表示做消融。",
    novelty: "相较端到端视觉触觉策略，OmniTacTune 把触觉作为可插拔的残差控制层，并证明它能跨基础策略和触觉编码复用。",
    strengths: "四项真机接触任务、多个基础策略与触觉表示共同验证了 policy-agnostic 主张。",
    limitations: "在线 RL 的安全性与传感器耐久性仍是成本；结果主要集中在固定工作站的局部接触技能。",
    transfer: "如果已有视觉策略运动范围正确但接触失败，可直接借鉴两阶段 warm start + tactile residual，而无需重新收集整套多模态示范。",
    experimentDetails: [{ title: "跨策略触觉残差", setup: "四项真实接触任务，覆盖插接、旋拧和开启；分别搭配 diffusion、ACT、π0.5 等视觉基础策略。", comparisons: "未适配视觉策略、单阶段在线 RL、不同触觉编码和奖励构造。", results: ["基础成功率 5%–40%，适配后 85%–100%。", "每任务约 40–80 分钟在线训练。", "去掉 warm start 会降低学习效率；残差层在不同基础策略上均带来提升。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["冻结视觉 base policy；触觉 critic 与残差 actor；自主 rollout warm start；在线 RL。"], verifiedResources: ["项目页提供论文、视频和任务说明。"], missing: ["完整代码、触觉硬件标定、奖励权重和真机数据尚未确认公开。"] },
    deepDive: { lead: "这项工作的价值在于把触觉学习限定为‘纠偏’，让视觉与触觉承担不同职责。", sections: [{ title: "两阶段残差学习", paragraphs: ["第一阶段不立即在真机上大范围探索，而是运行已有视觉策略，收集其接近接触区域时的轨迹，用来初始化触觉表示与价值估计。第二阶段再通过在线交互学习残差动作。", "运行时基础策略持续给出名义轨迹，触觉支路只修正接触相关维度。这个分工降低了触觉数据需要覆盖全任务流程的要求，也减少破坏原有视觉能力的风险。"] }], experimentReading: ["高成功率集中在接触阶段明确的任务；跨新机器人或新触觉硬件仍需重新标定与在线适配。"], reflections: ["可把失败轨迹按‘视觉定位错误’与‘接触误差’拆分，只有后者才交给触觉 residual。"] },
    figures: [{ src: "/report-assets/2026-07-06/2607.03723-overview.png", alt: "OmniTacTune 数据收集预热和在线触觉残差学习流程", caption: "Figure 2 · OmniTacTune 的两阶段真机触觉残差 RL。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 4,
    title: "HiMe: Hierarchical Embodied Memory for Long-Horizon Vision-Language-Action Control",
    arxivId: "2607.03449",
    url: "https://arxiv.org/abs/2607.03449",
    institutions: ["Fudan University", "Shanghai Innovation Institute", "East China Normal University"],
    signal: "用高频执行器、工作记忆 Sentry 和低频 Planner 分层解决长任务中实时控制与慢推理的冲突",
    tags: ["Hierarchical Memory", "Long-Horizon", "VLA"],
    classification: { research: "Memory", training: "Post-training", platforms: ["机械臂", "夹爪"] },
    detailAttributes: { memoryImplementation: "Context/Sequence + Episodic", memoryHorizon: "任务级长时记忆；Sentry 高频更新工作记忆" },
    resources: [{ label: "GitHub", url: "https://github.com/HappyWaterXP/HiMe" }],
    motivation: "VLA 的即时观察不足以处理先前状态已不可见的非马尔可夫任务；把所有历史交给大 VLM 又会让控制频率过低。",
    methodSummary: "Executor 高频执行动作，Sentry 持续监控并维护工作记忆，Planner 低频读取情景记忆做策略；记忆支持 Add、Update、Delete。",
    architecture: "Executor 采用 π0.5；Sentry 用较小 VLM 把近期帧写成跨模态语义 schema；Planner 读取情景与程序记忆生成下一子任务。",
    optimization: "先保持执行策略能力，再训练/配置分层记忆与规划模块；通过扁平记忆、仅短时记忆、FIFO 和无主动管理等变体做消融。",
    data: "WidowX-250 真机三项记忆依赖任务，训练共 60 条示范，其中 50 条常规轨迹与 10 条角落情况；Planner 主要使用 GPT-4o。",
    experiments: "三项任务平均成功率约 90%，高于 transient、Sentry-only 和 flat memory；同时报告 Planner API 调用次数、延迟以及记忆管理消融。",
    novelty: "相比外接一个统一记忆模块，HiMe 按控制频率拆分工作记忆和长时策略，并允许记忆随执行证据主动修改。",
    strengths: "真机任务明确要求回忆先前状态，且同时检查成功率、调用频率、记忆模态与更新策略。",
    limitations: "仅在单一机械臂和三项任务验证；Planner 依赖闭源大模型，长期累计误差与跨天记忆尚未测试。",
    transfer: "适合需要记住对象状态、用户偏好或已完成子步骤的长任务；Sentry 可作为现有 VLA 的低成本外部记忆层。",
    experimentDetails: [{ title: "非马尔可夫真机任务", setup: "WidowX-250 上三项长时任务，每种方法每任务 20 次试验；Executor 为 π0.5，Planner 为 GPT-4o。", comparisons: "Transient、Sentry、Flat Memory，以及不同记忆模态和 FIFO/主动管理变体。", results: ["HiMe 三项平均成功率约 90%。", "层次结构减少 Planner 调用，Sentry 保持高频状态更新。", "删除主动 Add/Update/Delete 或只保留单一模态均降低表现。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["Executor/Sentry/Planner 三频率层；跨模态 schema；Add/Update/Delete 记忆操作。"], verifiedResources: ["代码仓库公开；正文与附录给出任务、示范数量和 Planner 配置。"], missing: ["闭源 Planner API 版本与成本会影响复现；完整真机数据未确认公开。"] },
    deepDive: { lead: "HiMe 关注的不是存更多帧，而是决定谁在什么频率上写入、读取和修改记忆。", sections: [{ title: "分层记忆循环", paragraphs: ["Executor 每个控制周期只看执行所需上下文；Sentry 以较低但仍实时的频率检查进度，把近期视觉与子任务状态压缩为工作记忆；Planner 只在需要重新规划时读取长期记忆。", "情景记忆记录已经发生的事件，程序记忆保存操作规则和偏好。Add、Update、Delete 使错误观察不会永久占据上下文，也允许用户偏好在后续动作中生效。"] }], experimentReading: ["平均 90% 建立在三项明确的记忆任务上，说明架构有效，但还不足以推断开放世界长期记忆。"], reflections: ["工程上可先记录 Planner 调用触发条件和记忆写入失败，再决定是否需要更复杂的检索系统。"] },
    figures: [{ src: "/report-assets/2026-07-06/2607.03449-overview.png", alt: "HiMe Executor Sentry Planner 与工作情景记忆结构", caption: "Figure 2 · HiMe 的分层控制与跨模态记忆架构。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 5,
    title: "CoRE-VLA: Towards Scalable and Robust Vision-Language-Action Modeling via Conditional Routing of Experts",
    arxivId: "2607.03693",
    url: "https://arxiv.org/abs/2607.03693",
    institutions: ["Zhejiang University", "Shanghai Innovation Institute", "Fudan University", "Nanjing University", "Jilin University"],
    signal: "用传感器可用性与任务意图分别路由专家，让同一 VLA 能利用辅助深度又不在深度缺失时崩溃",
    tags: ["Conditional Routing", "Sensor Robustness", "Sparse Experts"],
    classification: { research: "VLA", training: "Post-training", modalities: ["Depth / RGB-D"], platforms: ["机械臂", "夹爪"] },
    motivation: "真实机器人传感器配置不一致，辅助深度也可能在部署时失效；固定融合所有模态的密集 VLA 容易过度依赖某一输入。",
    methodSummary: "传感器可用性控制 modality experts，任务语义控制 action experts；条件稀疏路由让模型在有深度时利用它、无深度时自动降级。",
    architecture: "预训练 VLM 编码 RGB 与语言，辅助编码器处理深度；Action DiT 内的 CoRE block 先按任务意图选取表示，再路由到专门动作专家。",
    optimization: "在 LIBERO、RoboCasa GR1 和真实双臂数据上后训练；通过缺失深度、密集生成器和不同路由粒度消融验证鲁棒性。",
    data: "RoboCasa 每任务 1000 条示范；真机包含蔬菜抓取、衣物折叠与未见材质折叠，使用 AgileX 双臂平台。",
    experiments: "RoboCasa 平均成功率 56.5±0.4%，高于多项 40%–48% 的对照；真机每项方法进行 20 次 rollout，并验证训练时有深度、测试时缺失的退化。",
    novelty: "它不是把 MoE 只用于扩模型容量，而是把传感器存在性与任务意图变成两层显式路由条件。",
    strengths: "多基准、真实双臂、缺失传感器和零样本材质迁移均与方法动机直接对应。",
    limitations: "实验只以深度代表辅助模态，能否无缝扩展到触觉、力或事件相机仍需验证。",
    transfer: "适合多机器人共享策略或传感器偶发失效场景；也可把路由权重作为诊断模型依赖哪种传感器的工具。",
    experimentDetails: [{ title: "多任务与传感器缺失", setup: "LIBERO、RoboCasa GR1 以及 AgileX 双臂蔬菜抓取和衣物折叠；真机每方法每任务 20 次。", comparisons: "预训练 VLA、密集 action generator、无路由/单层路由与深度缺失设置。", results: ["RoboCasa 平均 56.5±0.4%，主要基线约 40.4%–48.0%。", "有深度时路由专家提高精度，无深度时仍能保持可用性能。", "真机包含未见材质折叠，用于检查任务与感知迁移。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["传感器 availability gate；task-intent router；Action DiT 内稀疏专家；缺失模态掩码。"], verifiedResources: ["正文给出 RoboCasa 多次 rollout 均值与真机协议。"], missing: ["代码、模型权重与真实双臂数据尚未确认公开。"] },
    deepDive: { lead: "CoRE-VLA 把‘是否有这个传感器’和‘当前任务需要什么’分成两个路由问题。", sections: [{ title: "双条件稀疏计算", paragraphs: ["辅助深度先通过专用编码器进入表示层；availability gate 决定相关专家是否启用，避免模型在深度缺失时读取无意义占位。进入动作生成器后，task-intent router 再筛选与当前指令相关的动作表示。", "这种设计的收益一部分来自专家专门化，另一部分来自部署鲁棒性。论文通过密集 action generator 和缺失深度对照，将二者分别验证。"] }], experimentReading: ["RoboCasa 的重复 rollout 与真机零样本材质是较有信息量的证据；但跨更多辅助传感器仍是开放问题。"], reflections: ["在多模态 VLA 中，可把模态 dropout 与显式 availability routing 结合，检查模型是否真的学会退化而非仅适应固定缺失模式。"] },
    figures: [{ src: "/report-assets/2026-07-06/2607.03693-overview.png", alt: "CoRE VLA 辅助模态专家和条件路由动作专家", caption: "Figure 1 · CoRE-VLA 的传感器编码与条件专家路由。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 6,
    title: "Teaching Tiny VLA Models Where to Look and How to Move",
    arxivId: "2607.04171",
    url: "https://arxiv.org/abs/2607.04171",
    institutions: ["Tsinghua University", "Beihang University", "Wuxi Dexteroushands Robotics"],
    signal: "用粗粒度空间蒸馏和潜空间流匹配补足 0.25B 小模型的视觉定位与多峰动作能力",
    tags: ["Tiny VLA", "Spatial Distillation", "Latent Flow Matching"],
    classification: { research: "VLA", training: "Post-training", modalities: ["Mask / Segmentation"], platforms: ["机械臂", "夹爪"] },
    motivation: "小型 VLA 推理快，但缩小模型后常同时损失任务相关空间 grounding 和多峰动作生成能力。",
    methodSummary: "教师 Qwen3-VL-4B 生成粗粒度图像位置描述，蒸馏给 SmolVLM2-0.25B；动作端用 CVAE 风格潜变量与 flow matching 组织多峰示范。",
    architecture: "预训练阶段学习离散空间词表；后训练时小 VLM 输出条件表示，Latent Flow Matching action head 从噪声与潜变量生成动作块。",
    optimization: "先做 coarse spatial distillation，再在 LIBERO 与真机示范上行为克隆；教师标签、潜变量和流头均有独立消融。",
    data: "真机 Mobile ALOHA 三项任务，每任务 100 条示范，来自三名操作者；LIBERO 覆盖四套标准任务。",
    experiments: "LIBERO 平均从 82.8% 提升到 90.3%，Long 从 63.0% 到 89.0%；真机每任务 20 次，平均从 21.7% 提升到 65.0%。",
    novelty: "不同于单纯压缩大 VLA，XS-VLA 把小模型最缺失的空间定位与动作多模态性拆成两个针对性训练目标。",
    strengths: "小模型、仿真长任务和三类真机任务均有明确基线；作者还人工核查教师空间标签质量。",
    limitations: "教师标签 50 个审计样本中只有 36 个正确，说明自动空间监督存在噪声；真机任务规模仍有限。",
    transfer: "适合边缘部署或高控制频率场景；粗空间词表可作为低成本 grounding 辅助目标。",
    experimentDetails: [{ title: "小模型空间与动作补强", setup: "SmolVLM2-0.25B 主干；LIBERO 四套任务；Mobile ALOHA 三项真机任务，每任务 100 demos、20 次测试。", comparisons: "SmolVLA-0.25B、无空间蒸馏、无 latent flow 以及不同位置标签粒度。", results: ["LIBERO 平均 82.8%→90.3%，LIBERO-Long 63.0%→89.0%。", "真机平均成功率 21.7%→65.0%。", "人工审计的 50 个教师标签中 36 个正确，标签噪声是实际限制。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["Qwen3-VL-4B 教师；3×3 粗空间词表；SmolVLM2-0.25B；CVAE 风格 latent flow action head。"], verifiedResources: ["正文给出真机数据、测试次数和教师标签审计。"], missing: ["训练代码和模型权重尚未确认公开。"] },
    deepDive: { lead: "XS-VLA 的设计先回答小模型缺什么，再分别补空间与动作两个瓶颈。", sections: [{ title: "空间蒸馏与潜动作", paragraphs: ["教师先标出与抓取相关的图像关键点，再把连续坐标量化为粗粒度位置词。小 VLM 学习生成这些词，因此部署时不需要运行 4B 教师。", "动作端的潜变量吸收同一任务中不同操作者和路径的变化，flow matching 再条件生成动作块，减少直接回归造成的平均化。"] }], experimentReading: ["长任务提升幅度明显，但教师标签审计暴露了自动标注上限；真正部署前应检查错误标签是否集中在遮挡和多物体场景。"], reflections: ["对于小 VLA，增加高质量中间监督可能比增加 backbone 参数更有效。"] },
    figures: [{ src: "/report-assets/2026-07-06/2607.04171-overview.png", alt: "XS VLA 空间蒸馏预训练与潜流动作头", caption: "Figure 3 · XS-VLA 的粗空间蒸馏和 Latent Flow Matching 架构。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 7,
    title: "Mask2Real-WM: Segmentation Masks as a Sim-to-Real Bridge for Controllable Dexterous World Models",
    arxivId: "2607.04546",
    url: "https://arxiv.org/abs/2607.04546",
    institutions: ["ETH Zurich Soft Robotic Lab"],
    signal: "先在仿真里学动作到 mask 的动力学，再用少量真机视频把 mask 渲染回 RGB，降低灵巧手世界模型的实数据需求",
    tags: ["Dexterous World Model", "Segmentation", "Sim2Real"],
    classification: { research: "WM", training: "Pre-training", modalities: ["Mask / Segmentation"], data: "合成 / 仿真数据", platforms: ["机械臂", "灵巧手"], deployment: "Sim2Real" },
    resources: [{ label: "项目页", url: "https://srl-ethz.github.io/Mask2Real-WM/" }],
    motivation: "灵巧手动作维度高，真机视频又少；直接从 RGB 学动力学容易把外观和运动混在一起，难以覆盖每个关节的可控变化。",
    methodSummary: "Dynamics WM 从历史 mask 与 23-DoF 动作预测未来 mask；Rendering WM 再把 mask 和历史 RGB 变成未来视频。",
    architecture: "第一阶段使用动作条件扩散预测 6-DoF 末端与 17-DoF 手部动作下的 mask；第二阶段以 ControlNet 与 Stable Video Diffusion 完成外观渲染。",
    optimization: "Dynamics WM 在 50+ 小时 IsaacLab 仿真上预训练，Rendering WM 用少于 2.5 小时真机示范微调；分离评估动力学、渲染与长时 rollout。",
    data: "仿真包含随机探索与操作轨迹；真机使用 Franka + 17-DoF ORCA Hand、双相机和不到 2.5 小时示范。",
    experiments: "论文重点评估视频预测、每个动作自由度的可控性、长时 rollout 和未见物体/背景；展示 mask 预训练与仿真数据对可控性的消融。",
    novelty: "相比端到端 RGB world model，它用分割 mask 作为 sim-to-real 中间层，把几何动力学与真实外观分别学习。",
    strengths: "23-DoF 控制、长时预测、OOD 外观和分层消融与方法目标一致。",
    limitations: "主要证据是世界预测质量与可控性，而不是闭环策略成功率；深度、遮挡下的物体身份漂移仍未解决。",
    transfer: "适合真实视频少、仿真 mask 易生成的灵巧操作；也可作为策略评估或数据增强模型的结构参考。",
    experimentDetails: [{ title: "可控世界预测", setup: "Franka + ORCA Hand 双相机平台；23-DoF 动作；50+ 小时仿真预训练与 <2.5 小时真机渲染微调。", comparisons: "端到端 RGB、去掉 mask/仿真预训练、不同动作覆盖和渲染配置。", results: ["mask 动力学显著提高各手指自由度的动作可控性。", "模型可在未见物体与背景上做长时自回归预测。", "论文未把预测增益直接换算为闭环真机任务成功率。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["Dynamics WM：past masks + 23-DoF actions；Rendering WM：ControlNet + Stable Video Diffusion；双阶段训练。"], verifiedResources: ["项目页提供论文和生成视频；正文列出硬件、数据小时数与动作定义。"], missing: ["完整训练代码、仿真生成器与真机数据尚未确认公开。"] },
    deepDive: { lead: "Mask2Real-WM 用 mask 把‘物体怎么动’和‘画面长什么样’拆开。", sections: [{ title: "动力学—渲染解耦", paragraphs: ["动作条件 Dynamics WM 只预测未来分割，因此可以直接利用仿真中廉价而准确的 mask 与关节动作。生成出的 mask 再作为 ControlNet 条件，引导视频扩散模型恢复真实材质、光照和相机外观。", "推理时两级模型串联做长时 rollout。由于动力学不必同时拟合纹理，它更容易响应细粒度手指动作；代价是 mask 错误会沿时间积累并传给渲染器。"] }], experimentReading: ["该论文证明的是可控预测，而不是策略控制闭环。评估迁移价值时应避免把视频质量直接当成任务成功。"], reflections: ["如果目标是 MPC，应进一步验证模型排序候选动作的能力，而不仅是平均像素或感知指标。"] },
    figures: [{ src: "/report-assets/2026-07-06/2607.04546-overview.png", alt: "Mask2Real 世界模型的 mask 动力学与 RGB 渲染两阶段", caption: "Figure 2 · Mask2Real-WM 的 dynamics/rendering 两阶段结构。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 8,
    title: "Feeling the Unexpected: ResTacVLA for Contact-Rich Manipulation via Residual Tactile Representation",
    arxivId: "2607.03387",
    url: "https://arxiv.org/abs/2607.03387",
    institutions: ["Chinese Academy of Sciences", "University of Chinese Academy of Sciences", "Zhongguancun Academy", "Dexmal"],
    signal: "把触觉表示成视觉预测与真实触觉之间的残差，再用不确定性门控突出视觉看不到的接触事件",
    tags: ["Residual Tactile", "Predictive Coding", "Contact-Rich"],
    classification: { research: "表征学习", training: "Post-training", modalities: ["Tactile"], platforms: ["机械臂", "夹爪"] },
    resources: [{ label: "项目页", url: "https://awilekong.github.io/ResTacVLA/" }],
    motivation: "直接把高带宽视觉与稀疏触觉拼接，常出现视觉压制触觉的 modality collapse，尤其在对齐已完成但接触仍失败时。",
    methodSummary: "先预测视觉可解释的触觉先验，再取真实触觉与先验的残差；VQ bottleneck 将残差离散为接触原语，视觉不确定性决定融合强度。",
    architecture: "Cross-Modal Predictor 从图像预测 tactile prior；Residual Tactile Encoder 与 VQ 模块生成接触 token；门控后的 token 注入 π0.5 action expert。",
    optimization: "先做残差触觉表征预训练，再进行 surprise-aware VLA 后训练；对原始触觉、SSL 触觉、残差、VQ 和 gating 分别消融。",
    data: "五项真机任务：灯泡旋拧、插头插接、peg-in-hole、peg transfer 与擦拭；每任务约 100 条示范，使用 GelSight 触觉。",
    experiments: "八项对齐/交互指标平均成功率 62.8%，视觉 π0.5 为 28.2%，最强朴素触觉融合为 42.3%；动态扰动下完整模型为 66.7%。",
    novelty: "与把触觉当额外输入不同，ResTacVLA 只保留视觉无法预测的触觉信息，并用视觉置信度决定何时信任它。",
    strengths: "五类真实接触任务、对齐与交互分段指标、表示消融和外部扰动测试较充分。",
    limitations: "依赖触觉传感器和视觉到触觉预测器；不同传感器材料、磨损与标定变化下的迁移未充分验证。",
    transfer: "适合分析视觉策略‘已经对齐但无法完成物理接触’的失败，可将残差触觉 token 接入现有 VLA。",
    experimentDetails: [{ title: "接触事件与扰动鲁棒性", setup: "五项真实接触任务；Lightbulb/Plug/Peg 分别记录 alignment 与 interaction，Transfer/Wiping 记录最终成功。", comparisons: "视觉 π0.5、Diffusion Policy、ResNet/UniT 触觉融合、无 residual/VQ/gate 变体。", results: ["完整模型平均 62.8%，视觉 π0.5 为 28.2%，最强朴素触觉融合 42.3%。", "将残差触觉接到 Diffusion Policy 也带来约 19.2 个百分点提升。", "综合扰动设置成功率 66.7%；移除 surprise-aware gating 下降 13.3 个百分点。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["视觉到触觉先验；残差编码；VQ 接触原语；视觉不确定性 FiLM/gating。"], verifiedResources: ["项目页和正文提供硬件、任务、示范规模与逐项表格。"], missing: ["代码、触觉数据及 GelSight 标定流程尚未确认公开。"] },
    deepDive: { lead: "ResTacVLA 试图让触觉只报告‘意外’，而不是与视觉重复描述整幅接触图。", sections: [{ title: "残差触觉与门控", paragraphs: ["Cross-Modal Predictor 根据腕部图像估计在正常视觉条件下应该看到的触觉分布。实际触觉减去这个先验后，剩余信号更集中于滑移、碰撞、螺纹啮合等视觉难辨事件。", "残差再通过向量量化形成有限的 contact primitives；视觉先验不确定时，门控提高这些触觉 token 的权重。这个路径同时降低维度并控制触觉介入时机。"] }], experimentReading: ["对齐/交互分开统计很有价值：多项视觉基线能对齐却无法完成接触，正好对应残差触觉的作用区间。"], reflections: ["可把残差大小与失败阶段对齐，作为确定触觉采样频率和传感器位置的依据。"] },
    figures: [{ src: "/report-assets/2026-07-06/2607.03387-overview.png", alt: "ResTacVLA 残差触觉预训练和不确定性门控策略", caption: "Figure 2 · ResTacVLA 的残差触觉表征与 surprise-aware 融合。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 9,
    title: "WorldBagel: Uncovering the Power of Unified Multimodal Models for Vision-Language-Action-World Modeling",
    arxivId: "2607.03461",
    url: "https://arxiv.org/abs/2607.03461",
    institutions: ["Georgia Institute of Technology"],
    signal: "基于 BAGEL 的统一多模态 backbone 同时做理解、动作与未来图像，系统检验 VLAW 统一训练本身的收益",
    tags: ["Unified Multimodal", "VLAW", "Future Prediction"],
    classification: { research: "WAM", training: "Post-training", platforms: ["机械臂", "夹爪"] },
    motivation: "现有 VLAW 往往把动作、语言理解和世界预测做成分离模块，尚不清楚统一多模态生成模型是否能直接提供更好的动作表示。",
    methodSummary: "WorldBagel 在 BAGEL 的 Understanding 与 Generation 专家上增加 Fourier action tokenizer/decoder，使动作预测与未来图像生成共享 token 空间。",
    architecture: "ViT 与语言 tokenizer 输入共享 backbone；UND expert 负责理解和动作条件，GEN expert 负责未来图像；动作经 Fourier features 编解码。",
    optimization: "在统一、部分统一和任务专用设置下共同训练 VLA 与 world modeling，并消融动作解码器、Fourier 频带和任务组合。",
    data: "使用 LIBERO、Language Table 与 Franka 环境的机器人轨迹，覆盖多任务与跨域设置。",
    experiments: "统一训练在三个环境中持续优于任务专用对照；LIBERO 达到约 98% 平均成功率，并分析动作表征的结构和语义对齐。",
    novelty: "论文核心不是提出复杂新控制器，而是以受控实验说明统一理解—生成 backbone 能改善动作表征和世界预测。",
    strengths: "跨三个环境、多个统一程度和动作编码消融，能较清楚分离‘统一’本身的贡献。",
    limitations: "实验主要是离线/仿真环境，缺少物理真机证据；代码与权重承诺在接收后发布。",
    transfer: "适合研究 VLA/WAM 共享 backbone、动作 token 与视觉生成 token 的接口设计。",
    experimentDetails: [{ title: "统一 VLAW 建模", setup: "LIBERO、Language Table 和 Franka 环境；同时评估动作成功率、未来视觉和表征质量。", comparisons: "任务专用模型、部分共享模型、不同动作 decoder 与 Fourier feature 配置。", results: ["统一模型在三个环境中整体优于任务专用替代。", "LIBERO 平均成功率约 98%。", "动作表征呈现更清晰的任务结构和语言/视觉语义对齐。"] }],
    reproducibilityDetails: { status: "信息不足", implementation: ["BAGEL UND/GEN 双专家；Fourier Feature Action Tokenizer 与 Decoder；动作和未来图像联合目标。"], verifiedResources: ["正文给出主要结构和跨环境消融。"], missing: ["代码和模型检查点仅说明将在论文接收后公开；缺少真机复核。"] },
    deepDive: { lead: "WorldBagel 把动作也当作统一多模态模型可生成、可理解的一类 token。", sections: [{ title: "统一 token 空间", paragraphs: ["图像和语言先进入 BAGEL 共享多模态层，动作通过 Fourier 特征映射进入相同空间。UND expert 聚合当前语义与状态，GEN expert 在动作条件下预测未来图像。", "动作预测与未来预测共享表示，使动作不再只是末端回归头。对不同统一程度的消融表明，共享表示本身带来收益，但结论仍主要建立在非物理环境。"] }], experimentReading: ["高成功率应结合基准饱和度理解；缺少真机意味着不能直接推断部署鲁棒性。"], reflections: ["如果已有统一 VLM，可先让动作 decoder 共享中间 token，再逐步加入未来预测，而不是一次性重做生成 backbone。"] },
    figures: [{ src: "/report-assets/2026-07-06/2607.03461-overview.png", alt: "WorldBagel 理解专家生成专家动作头和世界模型分支", caption: "Figure 1 · WorldBagel 的统一 VLAW backbone 与动作/未来图像分支。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 10,
    title: "High-Fidelity One-Step Generative Visuomotor Policy via Recursive Correction, Frequency Consistency, and Contrastive Flow Matching",
    arxivId: "2607.03865",
    url: "https://arxiv.org/abs/2607.03865",
    institutions: ["论文首页未标注机构"],
    signal: "用递归校正、频率一致性与对比流损失把多步生成策略压成单步，同时尽量保住轨迹几何和高频动作",
    tags: ["One-Step Policy", "Flow Matching", "Inference Acceleration"],
    classification: { research: "VLA", training: "Post-training", platforms: ["机械臂", "夹爪"], deployment: "真机部署优化" },
    motivation: "扩散与 flow policy 多步采样延迟高，直接做一步近似又会产生空间偏移、细节过平滑和多模态平均。",
    methodSummary: "RCAF 对单步流做高阶递归校正，DTFC 约束不同时间步的频谱，CFM 用对比间隔分离纠缠的动作流。",
    architecture: "多模态 DiT 接收视觉、状态和噪声；三个训练机制作用于流向量、频域成分和样本间模式间隔，推理只需 1 NFE。",
    optimization: "用多步生成策略信号训练单步模型，并在 2D/3D 观测、四类仿真基准和两套真实机械臂上逐项消融。",
    data: "33 个仿真任务，来自 RoboTwin 1.0/2.0、Adroit 与 DexArt；真机使用 SO101 与 UR7E，多种设置各测试 20 次。",
    experiments: "2D 任务平均 65.3%，高于 10-step ManiFlow 的 56.5%；3D 平均 74.2%，高于 66.5%；UR7E 两任务从 4/20→7/20、1/20→6/20。",
    novelty: "相比只做蒸馏或 mean-flow 一步化，论文把误差拆为几何、频率和模式三个可诊断部分，并分别设计训练约束。",
    strengths: "33 个仿真任务、2D/3D 输入、逐模块消融和两类真机使加速与质量的权衡较可观察。",
    limitations: "部分真机成功率仍偏低；高分辨率结构图和复杂损失增加训练实现难度，且机构与公开资源信息不足。",
    transfer: "适合需要把 diffusion/flow action head 降到单步的部署，尤其可借鉴频域诊断判断加速是否损失细动作。",
    experimentDetails: [{ title: "单步加速与真实部署", setup: "33 个仿真任务；SO101 和 UR7E 多种任务，每设置 20 次。", comparisons: "Diffusion Policy、ManiFlow、3D ManiFlow、MeanFlow 系方法以及逐模块消融。", results: ["2D 平均 65.3%，10-step ManiFlow 为 56.5%。", "3D 平均 74.2%，3D ManiFlow 为 66.5%。", "UR7E Stack Cylinder 为 4/20→7/20，位置泛化 Pick & Place 为 1/20→6/20。"] }],
    reproducibilityDetails: { status: "信息不足", implementation: ["RCAF 高阶递归流校正；DTFC 双时间步频谱一致性；CFM margin-based 流分离；1 NFE 推理。"], verifiedResources: ["附录列出多组超参数、33 项任务和真机测试协议。"], missing: ["未确认代码或项目页；论文首页未标注作者机构。"] },
    deepDive: { lead: "这项工作把一步策略的失真拆成三个相互关联但可分别测量的问题。", sections: [{ title: "三项校正如何分工", paragraphs: ["RCAF 用递归细化得到的局部流作为监督，补偿一次大步跨越真实流形造成的空间截断误差。DTFC 比较不同流时间步的频域成分，避免细粒度动作被低通化。", "CFM 则在多峰数据中拉开不同动作流，减少一步模型把多个可行路径平均成不可执行中间动作。三者只在训练时增加成本，部署仍是一遍前向。"] }], equations: [{ name: "对比流间隔", expression: "L_CFM = max(0, m − ‖vᵢ − vⱼ‖)²", explanation: "当不同模式的预测流过于接近时施加惩罚；m 是分离间隔。" }], experimentReading: ["仿真平均提升稳定，但真机绝对成功数提示一步化仍不能替代数据与硬件鲁棒性。"], reflections: ["部署前应同时看成功率、动作频谱与安全中止，而不只看 NFE 或平均延迟。"] },
    figures: [{ src: "/report-assets/2026-07-06/2607.03865-overview.jpg", alt: "单步生成策略网络递归校正频率一致性与对比流匹配", caption: "Figure 2 · 高保真单步生成策略的三项训练机制。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 11,
    title: "Current as Touch: Proprioceptive Contact Feedback for Compliant Dexterous Manipulation",
    arxivId: "2607.03529",
    url: "https://arxiv.org/abs/2607.03529",
    institutions: ["University of North Carolina at Chapel Hill"],
    signal: "直接利用电机电流与关节状态学习柔顺参考位置，在没有外部触觉/力传感器时提供接触反馈",
    tags: ["Motor Current", "Compliance", "Dexterous Manipulation"],
    classification: { research: "表征学习", training: "BC", modalities: ["State / Proprioception", "Force / Torque"], platforms: ["机械臂", "灵巧手"] },
    resources: [{ label: "项目页", url: "https://cat.chenyangma.com/" }],
    motivation: "外部触觉和力传感器昂贵、脆弱且难装到低成本灵巧手；刚性位置控制在脆弱物体和持续接触中又容易施力过大。",
    methodSummary: "模型把电机电流视为内生接触信号，与关节历史共同预测 compliance reference position，再由标准 PD 控制器产生合适作用力。",
    architecture: "ACT 风格 CVAE/Transformer 编码用户意图、关节状态和电流，输出参考关节位置；另有电流重建支路用于训练约束。",
    optimization: "以遥操作示范做行为克隆，比较是否加入电流、不同历史长度、KL 与执行方式；同一接口同时用于遥操作和自主策略。",
    data: "覆盖泡沫杯堆叠、擦板、动态负载瓶抓取和薄卡片拾取；不同任务约 100–550 条真实轨迹，并在多种灵巧手上验证电流—接触关系。",
    experiments: "杯堆叠和擦拭达到 100% 测试成功；卡片拾取严格成功率从 55.8% 提升到 76.9%；动态负载包含训练外 350g 负载。",
    novelty: "与从电流估计外力不同，论文直接预测位置控制器可使用的柔顺参考，从而保持主流遥操作与策略接口。",
    strengths: "多任务、多用户、负载 OOD 和训练结构消融共同验证了低成本本体接触信号。",
    limitations: "电流到接触的映射受电机、减速器、温度和摩擦影响，跨硬件迁移需要重新标定或训练。",
    transfer: "低成本灵巧手没有触觉阵列时，可先记录电流与关节历史，学习 compliance reference，而不必直接上力矩控制。",
    experimentDetails: [{ title: "低成本柔顺真机操作", setup: "泡沫杯堆叠、擦板、动态瓶负载与卡片拾取；包含不同用户和 350g 未见负载。", comparisons: "固定刚度、无电流输入、不同历史窗口与策略训练配置。", results: ["泡沫杯堆叠和擦拭测试均达到 100%。", "卡片拾取严格成功率 55.8%→76.9%。", "在 350g OOD 负载下仍避免物体掉落，但观察到滑移。"] }],
    reproducibilityDetails: { status: "部分可复现", implementation: ["4 层 Transformer、4 heads；电流与关节历史编码；compliance reference 位置输出；PD 执行。"], verifiedResources: ["项目页提供视频；正文列出各任务轨迹和测试次数。"], missing: ["完整代码、硬件电流标定和数据下载尚未确认公开。"] },
    deepDive: { lead: "Current as Touch 把电机本身变成接触传感器，同时避免直接学习不稳定的力矩控制。", sections: [{ title: "从电流到柔顺参考", paragraphs: ["电机电流与输出力矩相关，但传动摩擦使精确外力估计困难。论文绕过外力标定，让模型从历史电流和关节状态直接预测一个参考关节位置；实际位置与参考位置的误差由 PD 控制器转成柔顺作用力。", "训练数据同时包含操作者意图和接触响应，因此模型学习到什么时候应继续闭合、什么时候应保持或回退。电流重建头提供额外约束，使潜变量保留接触相关信息。"] }], experimentReading: ["动态负载和薄卡片比固定抓取更能说明电流反馈的价值；但跨手型结果仍需关注电流尺度变化。"], reflections: ["可以先做同一动作下电流分布漂移监测，判断长期使用后是否需要重新校准。"] },
    figures: [{ src: "/report-assets/2026-07-06/2607.03529-overview.png", alt: "Current as Touch 电流关节输入与柔顺参考位置预测网络", caption: "Figure 5 · Current as Touch 的电流条件柔顺参考预测。图片来自 arXiv 原论文。" }],
  },
  {
    rank: 12,
    title: "RoboDojo: A Unified Sim-and-Real Benchmark for Comprehensive Evaluation of Generalist Robot Manipulation Policies",
    arxivId: "2607.04434",
    url: "https://arxiv.org/abs/2607.04434",
    institutions: ["MMLab@HKU", "UC Berkeley", "Tsinghua University", "Peking University", "MIT", "Stanford University"],
    signal: "把 42 项仿真和 18 项真机任务接入统一部署接口，用同一套维度评估通用操作策略",
    tags: ["Benchmark", "Sim-and-Real", "Policy Evaluation"],
    classification: { research: "其他", platforms: ["机械臂", "灵巧手", "夹爪"] },
    resources: [{ label: "项目页", url: "https://robodojo-benchmark.com" }],
    motivation: "不同论文的仿真、真机硬件、任务定义和执行代码不一致，通用策略的成功率很难横向复核。",
    methodSummary: "RoboDojo 统一任务定义、部署接口、评测脚本和排行榜，并把 Generalization、Memory、Long-Horizon、Precision 与 Open 作为主要维度。",
    architecture: "它不是新策略模型；核心由仿真任务库、真实机器人测试站、XPolicyLab 适配层和远程评测/排行榜组成。",
    optimization: "Benchmark 迭代评测 30+ 策略，要求同一策略经过标准化 adapter 后进入仿真和真机，不针对单一模型训练。",
    data: "42 项仿真、18 项真机任务、3 类本体和 24 类操作技能，覆盖抓取、放置、推拉、精密接触与长时任务。",
    experiments: "论文展示多类现有 policy 的仿真—真机测试，并分析通用性、记忆、长时、精度等维度；价值主要在统一协议而非某个 SOTA 数字。",
    novelty: "相较只提供仿真任务或少量真机 demo 的 benchmark，RoboDojo 把真实执行、远程评测和多策略 adapter 放入同一基础设施。",
    strengths: "任务、技能、平台和政策覆盖广，公开接口与排行榜便于后续论文复核。",
    limitations: "真机吞吐受物理平台限制；统一成功标准仍可能掩盖任务难度和安全风险差异。",
    transfer: "适合把内部 VLA/WAM 的验证拆成通用性、记忆、长时和精密控制维度，并复用其 XPolicyLab adapter 思路。",
    experimentDetails: [{ title: "统一仿真—真机评测", setup: "42 个仿真任务、18 个真实任务、3 种机器人本体和 30+ 策略接入。", comparisons: "不同通用 VLA/WAM 与策略在相同任务接口下比较。", results: ["覆盖 24 类操作技能和五个评测维度。", "提供真实机器人远程评测与排行榜，减少各论文自建协议差异。", "论文重点是基础设施与覆盖度，不应把它解读为单一控制算法提升。"] }],
    reproducibilityDetails: { status: "资源较完整", implementation: ["统一 task API；XPolicyLab 策略 adapter；仿真与真机部署标准；排行榜。"], verifiedResources: ["官网、Benchmark 与 XPolicyLab 入口在论文首页提供。"], missing: ["部分真实硬件任务仍需要通过官方测试站访问。"] },
    deepDive: { lead: "RoboDojo 更像测试基础设施，而不是一篇要复刻训练曲线的算法论文。", sections: [{ title: "统一接口的价值", paragraphs: ["每个 policy 通过 adapter 接入统一观察、动作和任务生命周期，减少因相机、控制频率或结束条件不同造成的结果偏差。真机任务由标准化站点执行，并把关键维度汇总到排行榜。", "五类维度让研究者看到模型究竟擅长普通抓放、长任务、记忆还是精密接触，而不是只比较一个混合平均分。"] }], experimentReading: ["Benchmark 的可信度取决于协议执行一致性与任务持续维护；现阶段更适合作为外部验证补充。"], reflections: ["内部评测可对齐其任务维度，但仍应保留逐任务失败原因和安全中止记录。"] },
    figures: [{ src: "/report-assets/2026-07-06/2607.04434-overview.png", alt: "RoboDojo 仿真真机统一基准排行榜与策略接口", caption: "Figure 1 · RoboDojo 的统一仿真—真机评测基础设施。图片来自 arXiv 原论文。" }],
  },
];
